- .circleci/config.yml
- .circleci/redhat-registry.sh
Hits redhat certified image registry to build newly tagged release.
> [NEW] Automatically trigger Redhat registry build when tagging new release

- packages/rocketchat-ui/client/components/popupList.html
- packages/rocketchat-ui/client/components/popupList.js
Closes #9890
This change adds the real name to the user popup list (used for inviting users to channels) when the admin has set the option to Use Real Names.
> [NEW] Shows user's real name on autocomplete popup

- packages/rocketchat-api/server/api.js
Removes the developer warning added when we removed the `usernames` array from the room objects being removed. The comment on it said to remove it on v64, so I am doing so. :)
> [OTHER] Removed the developer warning on the rest api

- packages/rocketchat-lib/server/functions/settings.js
- packages/rocketchat-lib/server/startup/settings.js
- packages/rocketchat-ui-admin/client/admin.html
- packages/rocketchat-ui-admin/client/admin.js
Closes #10137
Adds the autocomplete option to settings, fixing the issue above and opens the possibility to customize the settings a little further.
The autocomplete option still has some issues since browsers do not respect it 100% (see [caniuse](https://caniuse.com/#feat=input-autocomplete-onoff) )
> [NEW] Prevent the browser to autocomplete some setting fields

- packages/rocketchat-channel-settings/client/views/channelSettings.html
- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-theme/client/imports/forms/button.css
> [FIX] Button to delete rooms by the owners wasn't appearing

- package-lock.json
- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-channel-settings/server/functions/saveRoomAnnouncement.js
- packages/rocketchat-lib/client/lib/RocketChatAnnouncement.js
- packages/rocketchat-lib/client/lib/index.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-theme/server/colors.less
- packages/rocketchat-ui/client/views/app/room.html
- packages/rocketchat-ui/client/views/app/room.js
Adds some form of modularity to the Room Announcements so they can be changed easily by other packages and even other Apps.
Room Announcement example:
```
import { RocketChatAnnouncement } from 'meteor/rocketchat:lib';
const newAnnouncement = new RocketChatAnnouncement({
room: _rid, // REQUIRED: The room ID which the announcement is set
message: "New Room Announcement", // REQUIRED: the message displayed, currently does not support markdown
callback: "myCustomCallback", // OPTIONAL: a callback implemented by your app/feature that triggers when the user clicks the Announcement
style: "" // OPTIONAL: currently supports the default (when style is null/undefined), warning and error
})
newAnnouncement.save(); //updates the room with the new announcement
```
Result:
With `style: "error"`
With …
> [NEW] Add internal API to handle room announcements

- package-lock.json
- packages/rocketchat-lib/server/functions/setUsername.js
- packages/rocketchat-livechat/server/models/LivechatDepartmentAgents.js
Closes #2115
When a user's username has changed and that user is an Livechat agent, it's necessary to rename their username in Livechat departments.
> [FIX] Renaming agent's username within Livechat's department

- packages/rocketchat-ui-message/client/message.js
- packages/rocketchat-ui/client/lib/RoomManager.js
Closes #9926
Tested locally with @geekgonecrazy's script for load testing and this seems to fix most of the issues.
Reproducing while offline (Messages on the right are grouped with the wrong user)
After fix:
Even though the timestamp is not respected, the messages are grouped correctly.
> [FIX] Messages was grouping wrong some times when server is slow

- packages/rocketchat-emoji/client/lib/EmojiPicker.js
- packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.js
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-header.css
- packages/rocketchat-ui-flextab/client/flexTabBar.js
- packages/rocketchat-ui-flextab/client/tabs/membersList.js
- packages/rocketchat-ui-flextab/client/tabs/userInfo.js
- packages/rocketchat-ui-message/client/messageBox.js
- packages/rocketchat-ui-sidenav/client/sidebarHeader.js
- packages/rocketchat-ui-sidenav/client/sidebarItem.js
- packages/rocketchat-ui/client/views/app/popover.js
- packages/rocketchat-ui/client/views/app/room.js
now you can just pass the anchor element as `currentTarget` and the script will find the right position
Closes #10068
before: 
after:
> [FIX] Wrong positioning of popover when using RTL languages

- packages/rocketchat-lib/server/lib/defaultBlockedDomainsList.js
This pull request adds a domain to the default blocked domains list. I've seen some abuse from this domain and can confirm it's temporarily, it's even listed elsewhere in other lists (Ref: https://github.com/wesbos/burner-email-providers/blob/master/emails.txt). Thoughts?
> Added one2mail.info to default blocked domains list

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
- packages/rocketchat-livechat/.app/client/lib/_livechat.js
- packages/rocketchat-livechat/.app/client/lib/commands.js
- packages/rocketchat-livechat/.app/client/views/livechatWindow.js
- packages/rocketchat-livechat/.app/client/views/message.js
- packages/rocketchat-livechat/client/views/app/livechatAppearance.html
- packages/rocketchat-livechat/client/views/app/livechatAppearance.js
- packages/rocketchat-livechat/config.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/methods/getInitialData.js
- packages/rocketchat-livechat/server/methods/saveAppearance.js
- packages/rocketchat-livechat/server/publications/livechatAppearance.js
Closes #9873 
This PR allows to customize the message that will be displayed at the end of the conversation in LiveChat widget.
> [NEW] Livechat setting to customize ended conversation message

- packages/rocketchat-api/server/v1/chat.js
- tests/end-to-end/api/05-chat.js
Add REST endpoint chat.reportMessage.
Closes #10343.
> [NEW] REST endpoint to report messages

- packages/rocketchat-i18n/i18n/de.i18n.json
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
Closes #10385 
Added missing "Unread" key to the i18n files.
> [FIX] Missing i18n translation key for "Unread"

- packages/rocketchat-integrations/server/api/api.js
When using content-type as application/json, the raw content is not available to the user, as it has already been read. This PR adds the body (parsed JSON) to the request object so it can be used instead.
> [NEW] Body of the payload on an incoming webhook is included on the request object

- .docker/Dockerfile.rhel
- .docker/licenses/LICENSE
- .github/history.json
- .scripts/set-version.js
- HISTORY.md
- packages/meteor-accounts-saml/saml_utils.js
Sync develop up with the changes from the hotfix release
> [OTHER] Develop sync

- packages/rocketchat-api/server/v1/channels.js
> [FIX] The 'channel.messages' REST API Endpoint error

- packages/rocketchat-lib/server/functions/sendMessage.js
Closes #9942 
Since Javascript Regexp currently does not support lookbehind, we needed to match all urls and urls specifically inside blockquotes so we could remove those later. Used this change to remove duplicity in links embeded when the same URL appeared more than once.
> [FIX] Links being embedded inside of blockquotes

- packages/rocketchat-ui-flextab/client/tabs/userInfo.js
Closes #9930
When you change the username of a user through the administration, the web interface was failing to load the user data in the userInfo view.
> [FIX] Empty panel after changing a user's username

- packages/rocketchat-api/server/v1/misc.js
- packages/rocketchat-api/server/v1/settings.js
- tests/end-to-end/api/00-miscellaneous.js
- tests/end-to-end/api/08-settings.js
Add oauth services missing fields and add field to indicate whether the oauth service is customized.
Closes #10298
Closes #10332
@rafaelks , @filipedelimabrito, @cardoso .
> [FIX] REST API OAuth services endpoint were missing fields and flag to indicate custom services

- packages/rocketchat-api/server/v1/settings.js
Remove "secret" from REST endpoint /settings.oauth response.
> Fix: Remove "secret" from REST endpoint /settings.oauth response

- packages/rocketchat-theme/client/imports/forms/select.css
- packages/rocketchat-ui-account/client/accountPreferences.html
- packages/rocketchat-ui-admin/client/admin.html
Closes [my promise](https://github.com/RocketChat/Rocket.Chat/pull/9883#issuecomment-368663288) to @karlprieb.
This PR changes all dropdown element types from rc-input__element to rc-select__element.
Two more things:
1. The dropdown has still a cut off at the bottom (like any other dropdown in RC). May someone can give me a hand with that? :)
2. Is it possible to remove the margin ("0.5rem 0") from the rc-select element? Looks a lot better without it.
**Before (User UI):**
**After (User UI):**
**Before (Admin UI):**
**After (Admin UI):**
> [FIX] Dropdown elements were using old styles

- packages/rocketchat-api/server/v1/misc.js
- tests/end-to-end/api/00-miscellaneous.js
Add REST /directory endpoint.
Closes #9961.
> [NEW] REST API endpoint `/directory`

- packages/rocketchat-api/server/helpers/deprecationWarning.js
- packages/rocketchat-api/server/v1/channels.js
- packages/rocketchat-api/server/v1/rooms.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/cleanChannelHistory.js
- packages/rocketchat-lib/server/methods/cleanRoomHistory.js
- tests/end-to-end/api/02-channels.js
- tests/end-to-end/api/09-rooms.js
Rename endpoint to clean history messages, from `/channels.cleanHistory` to `rooms.cleanHistory`.
Refs #2355.
> [FIX] Rename method to clean history of messages

- packages/rocketchat-api/package.js
- packages/rocketchat-api/server/helpers/insertUserObject.js
- packages/rocketchat-api/server/v1/channels.js
- packages/rocketchat-api/server/v1/groups.js
- packages/rocketchat-api/server/v1/im.js
Add user object to responses in /[groups, channels, im].files Rest endpoints.
Closes #10449.
> [FIX] Add user object to responses in /*.files Rest endpoints

- .eslintignore
- .eslintrc
- packages/rocketchat-migrations/migrations.js
If any exception occurs during a migration, the real error message is not logged because the `makeABox` method uses a lib that is not imported.
> Included missing lib for migrations

- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-channel-settings/server/functions/saveRoomAnnouncement.js
- packages/rocketchat-lib/server/models/Rooms.js
- packages/rocketchat-ui/client/views/app/room.js
- server/publications/room.js
- server/startup/migrations/v115.js
Reverts the change made to Room Announcement structure, which broke mobile usage of the feature. This adds a new field for the announcementDetails (containing the new properties added) and reverts the message field back to be used from the `announcement` field in the Room Details.
See #10396 for more details
> Regression: Revert announcement structure

- packages/rocketchat-ui/client/views/app/room.js
Fix the rc1 regression bug that causes the announcement bar to be displayed even when the content is empty.
> Regression: Fix announcement bar being displayed without content

- packages/rocketchat-api/server/v1/settings.js
> Regression: /api/v1/settings.oauth not returning clientId for Twitter

- packages/rocketchat-lib/client/MessageAction.js
- packages/rocketchat-ui/client/lib/chatMessages.js
Fix a bug that was created on #10437 since the logic for mentioning user was duplicated.
Fixed:
> Regression: Remove added mentions on quote/reply

- packages/rocketchat-wordpress/common.js
> [FIX] Wordpress oAuth authentication wasn't behaving correctly

- packages/rocketchat-integrations/server/lib/triggerHandler.js
Closes #10416
Also, this fixes an issue happening inside of Zapier.
Basically we are writing to history and doing it by reference then updating the reference of the rooms. So, we are now cloning the data going onto history due to us adjusting the data stored three.
cc: @mrsimpson
> [FIX] Integrations with room data not having the usernames filled in

- .vscode/launch.json
- package.json
Special thanks to @mrsimpson for his effort and research, we now have the ability to debug and step through the Rocket.Chat application via Visual Studio Code's amazing debugging!!
There are a few different configurations, so I'll explain what they are:
- `Attach to meteor debug` - use this when you have already started the application via `npm run debug`
- `Frontend (Chrome)` - this opens a new Chrome instance and allows debugging the client code inside of VSCode
- `Server (debug)` - launches the server code but it only hits breakpoints **after Meteor has started up**
- `Server (debug-brk)` - launches the server code, however it allows setting a breakpoint in code that Meteor calls during the startup phase
- `Server (Testmode)` - works like the regular debug but has the environmental …
> Development: Add Visual Studio Code debugging configuration

- packages/rocketchat-ui-sidenav/client/sidebarHeader.js
This PR extends #10171 and closes #10226
**Description**
The following permissions need to enable the three dots admin menu as well:
- manage-integrations
- manage-oauth-apps
- manage-own-integrations
- manage-sounds
- view-logs
- view-statistics
>  [FIX] Missing "Administration" menu for users with some administration permissions

- packages/rocketchat-apps/package.js
- packages/rocketchat-apps/server/converters/messages.js
- packages/rocketchat-apps/server/converters/users.js
This was due to the Livechat users not actually being true Rocket.Chat system users.
> Regression: Apps and Livechats not getting along well with each other

- packages/rocketchat-lib/server/functions/sendMessage.js
- packages/rocketchat-markdown/markdown.js
- packages/rocketchat-markdown/parser/original/code.js
- packages/rocketchat-markdown/tests/client.tests.js
Original PR was https://github.com/RocketChat/Rocket.Chat/pull/10496
closes #10616
> [FIX] Regression on 0.64.0 was freezing the application when posting some URLs

- packages/meteor-accounts-saml/saml_server.js
Closes #10436 
SAML login result data was previously stored in memory, which caused the login to sometimes fail when using multiple instances of Rocket.Chat. This PR moves this data to mongo to solve this problem.
> [FIX] SAML wasn't working correctly when running multiple instances

- packages/rocketchat-lib/server/functions/createRoom.js
- tests/end-to-end/api/05-chat.js
Fix create channel, when created a readonly channel, the owner of the channel should be able to send messages.
Closes #10657.
> [FIX] Channel owner was being set as muted when creating a read-only channel

- README.md
I'm trying to set up Rocket.Chat locally. While browsing through the `README.md`, I noticed some broken links targeting the documentation section. The docs seem to be moved to another location.
_So this PR tries to correct all documentation links in the project readme file._
- **Use the valid URL to the docs**
Replace `docs.rocket.chat` with `rocket.chat/docs` in all URLs
- **Add trailing slashes where missing**
Most documentation links have a trailing slash. So I added them where missing.
➕  With my Chrome browser, links without the slashes are redirected, which results in a failure to load assets (might _just_ be a caching issue, works on Firefox; can give system details if wanted).
- https://rocket.chat/docs/developer-guides/branches-and-releases/ _works like a charm_
- …
> Correct links in README file

- packages/rocketchat-theme/client/imports/components/message-box.css
Fixes the flickering in the message box caused by the scaling of the flex container.
Previously:
Fix:
> [FIX] Message box emoji icon was flickering when typing a text

- packages/rocketchat-apps/server/converters/messages.js
Closes #10671 
Fixes the problem of missing data on message attachments when Apps are enabled.
> [FIX] Missing attachment description when Rocket.Chat Apps were enabled

- packages/rocketchat-lib/lib/roomTypes/direct.js
- packages/rocketchat-lib/server/functions/notifications/audio.js
- packages/rocketchat-lib/server/functions/notifications/desktop.js
- packages/rocketchat-lib/server/functions/notifications/email.js
- packages/rocketchat-lib/server/functions/notifications/mobile.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
With the new logic for sending notifications we forgot adding a specific condition to send notifications to all messages on direct messages, even if the selected preferences is `mentions`.
> Regression: Fix notifications for direct messages

- packages/rocketchat-api/package.js
- packages/rocketchat-api/server/api.js
- packages/rocketchat-api/server/default/metrics.js
- packages/rocketchat-lib/lib/callbacks.js
- packages/rocketchat-lib/server/functions/notifications/audio.js
- packages/rocketchat-lib/server/functions/notifications/desktop.js
- packages/rocketchat-lib/server/functions/notifications/email.js
- packages/rocketchat-lib/server/lib/PushNotification.js
- packages/rocketchat-lib/server/lib/debug.js
- packages/rocketchat-lib/server/lib/metrics.js
- packages/rocketchat-lib/server/startup/settings.js
> Add setting and expose prometheus on port 9100

- packages/rocketchat-mentions/Mentions.js
- packages/rocketchat-mentions/tests/client.tests.js
One of the XSS is happening when the "Use Real Name" setting is enabled. You can change your display name to this for example:
`<svg onload=alert(69)>`
And then mention yourself with @ in a room. Everybody in the room will execute the code. Exfiltrating the data is left to the reader as an excercise.
I have no instance to test this but I think it should work.
Timeline:
20.04.2018 - Send two XSS two security@rocket.chat, Received link to HackerOne but issues are deactivated
11.05.2018 - asked for update
17.05.2018 - no answer, so created this PR
I found this bug together with @Faradax during our work at [G Data - Advanced Analytics](https://www.gdata-advancedanalytics.de/)
> [FIX] Not escaping special chars on mentions

- packages/rocketchat-ui-admin/client/admin.js
- packages/rocketchat-ui-admin/client/adminFlex.js
This PR disables caching for private settings, so that they are not stored in the local browser storage. This is done because private settings may contain sensitive data (such as private keys).
> [FIX] Private settings were not being cleared from client cache in some cases

- packages/rocketchat-api/server/v1/subscriptions.js
- tests/end-to-end/api/10-subscriptions.js
> [NEW] Add REST endpoint `subscriptions.unread` to mark messages as unread

- packages/rocketchat-api/server/v1/settings.js
This closes the issue #9628 
In addition, I added an extra case to trigger action-buttons in the settings via api.
To set a color via api use the normal url `/api/v1/settings/:_id` with the following arguments:
```
{
value: '<color-code>',
editor: 'color'
}
```
To trigger a action-button use:
```
{
execute: true
}
```
> [NEW] REST API endpoint `settings` now allow set colors and trigger actions

- packages/rocketchat-api/server/v1/users.js
- tests/end-to-end/api/01-users.js
> [NEW] Add REST API endpoint `users.getUsernameSuggestion` to get username suggestion

- packages/rocketchat-i18n/i18n/ar.i18n.json
- packages/rocketchat-i18n/i18n/de-AT.i18n.json
- packages/rocketchat-i18n/i18n/el.i18n.json
- packages/rocketchat-i18n/i18n/fi.i18n.json
- packages/rocketchat-i18n/i18n/fr.i18n.json
- packages/rocketchat-i18n/i18n/he.i18n.json
- packages/rocketchat-i18n/i18n/hr.i18n.json
- packages/rocketchat-i18n/i18n/hu.i18n.json
- packages/rocketchat-i18n/i18n/id.i18n.json
- packages/rocketchat-i18n/i18n/ja.i18n.json
- packages/rocketchat-i18n/i18n/km.i18n.json
- packages/rocketchat-i18n/i18n/ko.i18n.json
- packages/rocketchat-i18n/i18n/ku.i18n.json
- packages/rocketchat-i18n/i18n/lo.i18n.json
- packages/rocketchat-i18n/i18n/ms-MY.i18n.json
- packages/rocketchat-i18n/i18n/nl.i18n.json
- packages/rocketchat-i18n/i18n/pl.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
- packages/rocketchat-i18n/i18n/ro.i18n.json
- packages/rocketchat-i18n/i18n/ru.i18n.json
- packages/rocketchat-i18n/i18n/sq.i18n.json
- packages/rocketchat-i18n/i18n/sr.i18n.json
- packages/rocketchat-i18n/i18n/sv.i18n.json
- packages/rocketchat-i18n/i18n/ta-IN.i18n.json
- packages/rocketchat-i18n/i18n/tr.i18n.json
- packages/rocketchat-i18n/i18n/ug.i18n.json
- packages/rocketchat-i18n/i18n/uk.i18n.json
- packages/rocketchat-i18n/i18n/zh-TW.i18n.json
- packages/rocketchat-i18n/i18n/zh.i18n.json
Closes #10097 
Removed translations that were still pointing to the old hubot scripts repo, as they are now misleading.
> [FIX] Remove outdated translations of Internal Hubot's description of Scripts to Load that were pointing to a non existent address

- packages/rocketchat-channel-settings/client/views/channelSettings.html
- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-lib/lib/RoomTypeConfig.js
- packages/rocketchat-lib/lib/roomTypes/direct.js
- packages/rocketchat-lib/lib/roomTypes/private.js
- packages/rocketchat-lib/lib/roomTypes/public.js
- packages/rocketchat-theme/client/imports/components/userInfo.css
- server/publications/room.js
> [FIX] Missing option to disable/enable System Messages

- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-message-attachments/client/messageAttachment.js
Closes #10424 
Enabling the setting "Collapse Embedded Media by Default" was hiding replies and quotes as well. This pr fixes this.
> [FIX] Enabling `Collapse Embedded Media by Default` was hiding replies and quotes

- packages/rocketchat-livechat/config.js
Closes #10609 
Closes #8072
This PR fixes a bug in Livechat administrative area.
The Livechat settings of the `color` types  were not appearing correctly as seen below.
> [FIX] Livechat settings not appearing correctly

- packages/rocketchat-lib/lib/getDefaultSubscriptionPref.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/functions/notifications/index.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-lib/server/models/Subscriptions.js
- packages/rocketchat-push-notifications/server/methods/saveNotificationSettings.js
- packages/rocketchat-ui-account/client/accountPreferences.html
- server/methods/createDirectMessage.js
- server/startup/migrations/v121.js
Closes #10844
Closes #10787
* The value was being saved correctly, but due a change on the value saved (from `disabled` to `nothing`) the `<select/>` element was not showing the correct selected value.
* On the [channel preferences screen](https://github.com/RocketChat/Rocket.Chat/pull/10847/files#diff-c4b149a43ae0425e6d25c114be7a6a9aL40) the value was being transformed, but there is not need for that
* Fixed an issue when creating a new room/direct message the user preferences were not being applied
* Added back the `Uploaded a file` message for push notifications
> Regression: Fix email notification preference not showing correct selected value

- packages/rocketchat-api/server/v1/push.js
Parameter name on the JSON object is `value`, not `token`.
> Fix: typo on error message for push token API

- packages/rocketchat-theme/client/imports/general/base_old.css
- packages/rocketchat-ui-message/client/popup/messagePopupSlashCommandPreview.html
Slash commands preview now align horizontally.
Based on https://github.com/RocketChat/Rocket.Chat/pull/6090#issuecomment-281163639
> [FIX] Horizontally align items in preview message

- packages/rocketchat-apps/assets/stylesheets/apps.css
- packages/rocketchat-apps/client/admin/appManage.html
- packages/rocketchat-apps/client/admin/apps.html
- packages/rocketchat-apps/client/admin/apps.js
Adds some missing interface elements to the Manage Apps page:
Also adds client side filter based on App name.
> Fix: Manage apps layout was a bit confuse

- packages/rocketchat-slackbridge/server/slackbridge.js
> [FIX] Slack-Bridge bug when migrating to 0.64.1

- packages/rocketchat-push-notifications/server/models/Subscriptions.js
`Go to message` email links were incomplete due to lack of data when generating the links.. this fixes that.
> [FIX] Incomplete email notification link

- packages/rocketchat-lazy-load/client/index.js
- packages/rocketchat-lazy-load/client/lazyloadImage.js
- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-ui-account/client/avatar/avatar.html
- packages/rocketchat-ui-message/client/message.js
- packages/rocketchat-ui/client/lib/menu.js
> [FIX] Image lazy load was breaking attachments

- packages/rocketchat-error-handler/server/lib/RocketChat.ErrorHandler.js
Closes #10899
Registering the error handler after `Mateor.startup` will not prevent errors from happening but if one is using `Log exceptions to channel` feature it will show where exactly the error is happening instead of trying to send a message before the whole server is up and then blaming `Apps` like the msg bellow (the following error was caused intentionally by adding a `throw 'anything'` at any place):
I have done additional changes to the file, but the only important one to fix the issue is [the Meteor.startup() wrap](https://github.com/RocketChat/Rocket.Chat/pull/10934/files#diff-47cf041a588181e55b9366a0cb63d219R7)
> [FIX] Application crashing on startup when trying to log errors to `exceptions` channel

- packages/rocketchat-i18n/i18n/de-AT.i18n.json
- packages/rocketchat-i18n/i18n/de.i18n.json
The time unit in German is wrong (has to be sec) and not needed (not specified ini other languages)
> Remove wrong and not needed time unit

- .snapcraft/resources/preparecaddy
- .snapcraft/snapcraft.yaml
For the snap updates caddy to 0.11.0 and updates node.js to 8.11.2
I've already updated the 0.65.1 snap which is live for everyone.  This is just making these changes upstream :)
> Snap update caddy and nodejs

- packages/rocketchat-ui-master/server/inject.js
This meta tag will change the referrer of all cross origin links to send only the origin part of the url (dropping the params).
> [NEW] Added meta referrer tag

- packages/meteor-accounts-saml/saml_utils.js
Closes #10931 
Mongo DB don't support "." as key so replace in attributes urn:oid the "." to "-"
https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name
> [FIX] for issue 10931

- packages/rocketchat-analytics/client/loadScript.js
Piwik analytics has been updated to use an implicit reference instead of "piwik.php" and "piwik.js", as per the [documentation suggestions](https://github.com/matomo-org/matomo/blob/master/js/README.md).
Closes #10889
> [FIX] Piwik (Matomo) analytics updated to implicit reference

- server/lib/accounts.js
- server/methods/sendForgotPasswordEmail.js
Closes #3883
Closes #9863
Closes #8650
Closes #9923
This PR removes the hash/fragment identifier from the password reset url by overriding the base url.
**Before:**
**After:**
> [FIX] Reset password URL incorrect

- .sandstorm/build.sh
- .sandstorm/setup.sh
- packages/rocketchat-sandstorm/server/lib.js
- packages/rocketchat-sandstorm/server/powerbox.js
[FIX] update dependence for Sandstorm version.
Adding dependence. for building new version RocketChat for Sandstorm
1: install the requirement capnproto and capnp.
2: include some needed .so files.
3: fix import in rocketchat-sandstorm.
And If need any information about building for Sandstorm. I can help.
> [FIX] Build for Sandstorm missing dependence for capnp

- packages/rocketchat-lib/server/functions/updateMessage.js
Now its working properly 
> When I edit my sent message and remove a link from it, the link preview stays in the chat.
Mac App Version 1.3.1 (15)
Closes #2833
> [FIX] Link previews not being removed from messages after removed on editing

- .circleci/config.yml
Turned out the steps on workflow were object properties and not array elements.
> Fix Docker image for develop commits

- packages/rocketchat-lib/client/lib/LoginPresence.js
- packages/rocketchat-lib/client/lib/index.js
This change will affect only unlogged users and instances without anonymous configuration.
When the user remove his focus from the window a timer will disconnect the websocket after 10 minutes, if the user put focus on the window again the connection will be restored.
> [NEW] Disconnect users from websocket when away from the login screen by 10min

- packages/rocketchat-ui-sidenav/client/roomList.js
Actually we don't have name on direct message rooms, so we cant set `lowerCaseName` and `lowerCaseFName` without use and subscriptions
Closes #11088
> Regression: sorting direct message by asc on favorites group

- packages/rocketchat-ui/client/views/app/popover.html
- packages/rocketchat-ui/client/views/app/popover.js
> [FIX] Popover position

- packages/rocketchat-assets/server/assets.js
- packages/rocketchat-autotranslate/server/methods/getSupportedLanguages.js
- packages/rocketchat-autotranslate/server/methods/saveSettings.js
Some places were returning `error-action-now-allowed` instead of `error-action-not-allowed`, which is all a bit confusing but definitely should not be the case.
> [FIX] Some typos in the error message names

- packages/rocketchat-ui-sidenav/client/roomList.js
Fixes the following error:
```
Uncaught TypeError: Cannot read property 'name' of undefined
at roomList.js:127
at callbacks.js:97
at Array.reduce (<anonymous>)
at Object.RocketChat.callbacks.run (callbacks.js:88)
at Streamer.<anonymous> (cachedCollection.js:340)
at ev.js:11
at Array.forEach (<anonymous>)
at Streamer.emit (ev.js:11)
at StreamerCentral.<anonymous> (client.js:66)
at ev.js:11
```
> [FIX] Room creation error due absence of subscriptions

- server/methods/saveUserProfile.js
- tests/end-to-end/api/01-users.js
> [FIX] REST endpoint `users.updateOwnBasicInfo` was not returning errors for invalid names and trying to save custom fields when empty

- .github/history.json
- HISTORY.md
Include the nodejs and npm versions to all release notes.
We get the meteor version from `.meter/release`, get a file from meteor's repository containing the versions of the given release.
> New history source format & add Node and NPM versions

- .sandstorm/setup.sh
[FIX] Update capnproto dependence for Sandstorm Build
Just update capnproto dependence for building Sandstorm version Rocket.Chat.
Still working on setup wizard for Sandstorm. It need some modify.
> [FIX] Update capnproto dependence for Sandstorm Build

- .circleci/config.yml
> Fix Docker image build on tags

- packages/rocketchat-reactions/setReaction.js
> [FIX] Reaction Toggle was not working when omitting the last parameter from the API (DDP and REST)

- packages/rocketchat-lib/client/lib/cachedCollection.js
- packages/rocketchat-ui-sidenav/client/roomList.js
> Regression: sidebar sorting was being wrong in some cases where the rooms records were returned before the subscriptions

- packages/rocketchat-integrations/server/lib/triggerHandler.js
When the integrations has a script that access some kind of async (made sync by Fibers) method the VM timeout would be fired after the timeout time and would generate some zoombie fibers cousing the oplog tailing (that uses Fibers) to stop working util a cursor timeout.
> [FIX] Outgoing integrations were stopping the oplog tailing sometimes

- packages/rocketchat-ui-account/client/accountProfile.html
Closes #8992
Allow changing avatar by using initials, uploading or external URL while RC is trying to load suggestions.
This is a quickfix for #8992 where users cannot change their avatar if RC has no internet access. This will also help if avatar services act very slow.
Before
After
> [FIX] Loading avatar suggestions with no internet connection

- packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
Before:
After:
Msg schema:
```javascript
{
"_id": "bQggkDyau77q9obZX",
"msg": "",
"attachments": [
{
"fields": [
{
"title": "Small field",
"value": "one line",
"short": true
},
{
"title": "Big field",
"value": "multiple\nlines\nsee?",
"short": true
}
]
}
],
"bot": {
"i": "EivbwgSN3eqWkENFw"
},
"groupable": false,
"emoji": ":bug:",
"ts": "2018-07-04T16:55:04.361Z",
"u": {
"_id": "rocket.cat",
"username": "rocket.cat",
"name": "Rocket.Cat"
},
"rid": "GENERAL",
"_updatedAt": "2018-07-04T16:55:04.367Z"
}
> [FIX] Message attachment's fields with different sizes

- packages/rocketchat-theme/client/imports/general/base_old.css
- packages/rocketchat-ui-message/client/popup/messagePopup.js
- packages/rocketchat-ui-message/client/popup/messagePopupChannel.html
- packages/rocketchat-ui-message/client/popup/messagePopupChannel.js
- packages/rocketchat-ui-message/client/popup/messagePopupSlashCommand.html
> [FIX] Message popup responsiveness in slash commands

- server/startup/migrations/v125.js
Closes #11353
Unfortunate seems like some databases have `settings` field on `users` as `null`, which causes migration 125 to fail.
This will fix the migration for those who have not ran it yet.
For those who are still locked on migration 125, upgrading to a new release with this fix will require the migration to be unlocked manually only using the following command:
```javascript
db.migrations.update({ version: 124, locked: true }, { $set: { version: 124, locked: false } })
```
For those who have skipped migration 125-129 manually, the recommended action is to revert back to version 125 and start the server with this fix. To revert back you can use the following command:
```javascript
db.migrations.update({ version: 129, locked: false }, { $set: { version: 124 } })
```
And finally for …
> Regression: Fix migration 125 checking for settings field

- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/methods/takeInquiry.js
Closes #11347 
When the Livechat routing method is `Guest Pool` and an agent takes an incoming Livechat, the route link is breaking.
> [FIX] Livechat taking inquiry leading to 404 page

- packages/rocketchat-webrtc/server/settings.js
While working on the video conferencing docs, I've noted the clear confusion of users between Jitsi and WebRTC methods. My suggestion is to make the the WebRTC options not default (like jitsi currently is) so if a server admin wants Video Conference he will have to set it up one of those, instead of using the currently preset default. I believe that this plus the upcoming docs PR that explains the difference between each other and how to set them up will greatly help reduce this confusion.
Link to documentation: https://github.com/RocketChat/docs/pull/841
> [NEW] Make WebRTC not enabled by default

- .docker/Dockerfile.rhel
Will close: https://bugzilla.redhat.com/show_bug.cgi?id=1570462
Also trick here might help with others having issues with sharp on centos.
No release needs to happen, but would be great to have merged down so the redhat build service can auto build again.
> Fix dependency issue in redhat image

- packages/rocketchat-file-upload/server/startup/settings.js
The current default experience (2mb max upload size) is confusing for users of other chat platforms. (eg. Slack allows 1gb uploads in their free plan)
Rationale for 100mb is 1 min video output from iPhone X
> [IMPROVE] Set default max upload size to 100mb

- .snapcraft/resources/startRocketChat
- .snapcraft/snapcraft.yaml
Another sharp issue.  If using https://{server}/avatar/{username}?format=jpg on an avatar that is an svg it would show just a block
Previously adding the desktop plug fixed this.  No longer does.  So a new fix :smile:
> [FIX] Snap font issue for sharp

- packages/rocketchat-mentions/Mentions.js
This is solves a bug introduced by #11165 when replying messages that contain channel mentions.
> [FIX] Check for channels property on message object before parsing mentions

- packages/rocketchat-file-upload/globalFileRestrictions.js
- packages/rocketchat-file-upload/lib/FileUpload.js
- packages/rocketchat-file-upload/server/startup/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-livechat/imports/server/rest/upload.js
This PR fixes a problem where instances configured to have unlimited uploads were failing to upload every file.
This might be the problem causing #10278, but further testing is needed.
> [FIX] Unlimited upload file size not working

- packages/rocketchat-lib/client/MessageAction.js
- packages/rocketchat-lib/lib/roomTypes/direct.js
- packages/rocketchat-ui/client/lib/RoomHistoryManager.js
Closes #11400
This PR makes two changes: First, it fixes the "Permalink" option to generate valid URLs on direct messages, where it was broken.
The second change is to make it so that permalinks on DMs work for both users on the conversation, regardless of which username is on the URL itself.
> [FIX] Invalid permalink URLs for Direct Messages

- packages/rocketchat-api/server/v1/users.js
- tests/end-to-end/api/01-users.js
A dd new REST endpoint to user delete you own account without verify "delete-user" permission. Add tests for this endpoint and user.delete.
Closes #11059
> [NEW] Add /users.deleteOwnAccount REST endpoint to an user delete his own account

- packages/rocketchat-importer-hipchat-enterprise/info.js
- packages/rocketchat-importer-hipchat-enterprise/server/importer.js
- packages/rocketchat-importer-hipchat/info.js
The cloud export is now the same format of the enterprise one, so I changed the naming of the enterprise to `HipChat (tar.gz)` and the old hiptchat cloud to `HipChat (zip)` to try to keep compatibility with who already have the old export.
We may need to change the documentation https://rocket.chat/docs/administrator-guides/import/hipchat/enterprise/ and https://rocket.chat/docs/administrator-guides/import/hipchat/cloud/ @MartinSchoeler can you help on that? Let me know then we can discuss what to change.
> [FIX] HipChat importer wasn’t compatible with latest exports

- .meteor/packages
- .meteor/versions
- packages/rocketchat-ui/package.js
- server/lib/cordova.js
While this https://github.com/raix/push/pull/344 isn't merged I have [forked](https://github.com/RocketChat/push) that package and released a new version with that fix.
The fix prevents a failure on polling query from preventing to send push notifications.
> [FIX] Push notifications stuck after db failure

- packages/rocketchat-setup-wizard/client/setupWizard.html
- packages/rocketchat-theme/client/imports/components/setup-wizard.css
Currently (broken):
Before (old logo):
New:
> [FIX] Broken logo on setup wizard

- .meteor/versions
- package-lock.json
Closes #11293
Updating user presence package with the following fix https://github.com/Konecty/meteor-user-presence/pull/31 will prevent a race condition where already closed connections are still being saved on db, and due so they never removed, causing an user status getting stuck as online until a server restart.
> [FIX] Closed connections being storing on db

- client/startup/i18n.js
- packages/rocketchat-ui-login/client/login/form.js
With the new logic, the user's language takes precedence, then the language stored on `localStorage`, then default server's language.
> [FIX] Default server language not being applied

- packages/rocketchat-ldap/server/ldap.js
- packages/rocketchat-ldap/server/loginHandler.js
In some cases (including mine) LDAP servers use the full user dn to filter members belonging to a group.
Here by adding a template tag `#{userdn}` composed of the complete DN of the user, we can easily translate this into the group member format to find it :
Ping @rodrigok :)
> [IMPROVE] Add template tag #{userdn} to filter LDAP group member format

- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
the pr #11342 introduced a small bug on the attachments, this pr fix this problem
**short**
**normal**
Closes #11669
> [FIX] Message attachments was not respecting sort and lost spacing

- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-message-attachments/client/messageAttachment.js
Render pretext as markdown when mrkdown_in contains "pretext"
Closes #3828
> [FIX] Render Attachment Pretext When Markdown Specified

- packages/rocketchat-ui/client/views/app/directory.js
- packages/rocketchat-ui/client/views/app/helpers.js
- packages/rocketchat-ui/client/views/app/tests/helpers.tests.js
Fix #11663 
Adding `timeAgo` function to a `helpers` file so we can test it because just importing it from the previous file will cause an error `Template is not defined`. I reproduced the mentioned case on a test.
> [FIX] Fixing timeAgo function on directory

- packages/rocketchat-custom-sounds/client/admin/soundEdit.html
- packages/rocketchat-custom-sounds/client/admin/soundEdit.js
Closes #8460
_Actually_ closes #6200
A fix that was made before only fixed half of the issue, sadly.
Now it is fully fixed and happy, and you can silently change your coworker's notification sound to the loudest version of the Monopoly theme you can find on the internet, all from Firefox.
Oh yeah, Firefox wasn't showing the file picker properly either, it let you select non-mp3 files. So that's fixed too, in case you find yourself confusing .mp3 and .png far too often. :-)
Before:
After:
> [FIX] Custom sound uploader not working in Firefox and IE

- packages/rocketchat-theme/client/imports/general/base_old.css
Closes #11466
**Before**
**After**
Affects Chromium/WebKit browsers and people relying on Rocket.Chat to just copy important IDs properly.
> [FIX] Code tag duplicating characters

- packages/rocketchat-theme/client/imports/general/base_old.css
- packages/rocketchat-theme/server/colors.less
- packages/rocketchat-ui-message/client/message.html
Role and bot tags are too prominent. When conversations involve lots of sequential messages from bots or users with role tags, the tags make it hard on the eye to track down the message stream. The end effect is a messy view and high cognitive load.
I removed the bot tag from sequential messages entirely and reduced the visual impact of all role tags.
Includes:
- Visual enhancement for less busy tags
- Consolidated styles for role tags
- Use color classes in markup instead of css
Example shows a conversation I'm having with our new buddy Faldo...
Before:
After:
> [IMPROVE] Role tag UI

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.js
- server/lib/cordova.js
> [IMPROVE] Warn about push settings that need server restart

- packages/rocketchat-livechat/server/models/Rooms.js
- packages/rocketchat-livechat/server/startup.js
Closes #11777
This PR fixes the Livechat open room method that was not returning an array when calling the `RoomFind` method.
Because of this, when the Livechat Manager attempted to open a Livechat Room on admin panel, the method was returning `room not found`.
> [FIX] Livechat open room method

- packages/rocketchat-theme/client/imports/components/header.css
Fix #11672
I was checking taking a look on commit history and it seems that a margin was changed here: https://github.com/RocketChat/Rocket.Chat/commit/7145112b2f61c0a9cd5d54aa416d4afe037be8ec#diff-8058da55e1244af44de84d849f6351dcR33
Current
When putting it back we have:
> [FIX] re-adding margin to menu icon on header

- packages/rocketchat-apps/client/admin/appManage.js
- packages/rocketchat-apps/client/communication/websockets.js
- packages/rocketchat-apps/client/orchestrator.js
- packages/rocketchat-apps/lib/misc/Utilities.js
- packages/rocketchat-apps/server/bridges/commands.js
To prevent conflicts among apps translations we added a unique key for the apps strings changing the keys in runtime to add `apps-${ id }-` in front of them.
Example for an app with id `my-app-id`:
Registered key:
`param_description`
Will be registered internally as:
`apps-my-app-id-param_description`
The slashcomands will require app developers to provide the translation since it will not allow fallback to the i18n strings of the project, but the settings will try to find the translation first in the app and then in the project strings (using only the last part eg: `param_description`).
The app developer need to do nothing, it's just an internal change.
> [FIX] Translations were not unique per app allowing conflicts among apps

- packages/rocketchat-slackbridge/server/SlackAdapter.js
The code looked for the key `SlackBridge_Botnames`, which is not referenced
anywhere else. Instead, it now looks for the key `SlackBridge_ExcludeBotnames`.
> [FIX] Typo in a configuration key for SlackBridge excluded bot names

- server/startup/migrations/v132.js
In #10956, we replaced the `label` property with the` fname` property in Livechat rooms, but a migration was not implemented to set the value of the `label` property in the new property `fname`.
> [FIX] Missing `fname` property in Livechat rooms

- packages/rocketchat-ui-master/client/main.js
Closes #8503
This pr makes it so that popovers close on 2 kinds of events:
Whenever someone uses a shortcut (like `cmd+k` for example);
Or when someone press a key that will trigger a `.focus()` on the `rc-message-box`, so it won't affect navigation with `tab` for example.
> [FIX] Close popover on shortcuts and writing

- packages/rocketchat-apps/client/admin/appManage.html
- packages/rocketchat-apps/client/admin/appManage.js
Making a code setting field for an app is not viable with this bug. (unless you do cmd+a in the code before saving)
> [FIX] Apps: setting with 'code' type only saving last line

- packages/rocketchat-ui-vrecord/client/vrecord.html
- packages/rocketchat-ui/client/lib/recorderjs/videoRecorder.js
Closes #11651 
This was broken by adding a wrong css class in [this commit](https://github.com/RocketChat/Rocket.Chat/commit/831f757f12a7d646a8f3819cd2f3f5af3cecd1c1#diff-ff868971f6509568c40009e48cbae836), causing the wrong click handler to be executed.
Also removed a warning about the deprecated api `createObjectURL`.
> [FIX] video message recording, issue #11651

- packages/rocketchat-ui/client/views/app/directory.js
- packages/rocketchat-ui/client/views/app/helpers.js
- packages/rocketchat-ui/client/views/app/tests/helpers.tests.js
Related with #11663, but I added a bug removing `t` function on this PR 😬 https://github.com/RocketChat/Rocket.Chat/pull/11728
Now we're translating 🗣 🌎 🌍 🌏
> [FIX] Fixing translation on 'yesterday' word when calling timeAgo function

- packages/rocketchat-lib/server/lib/index.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-livechat/.app/i18n/de.i18n.json
- packages/rocketchat-livechat/.app/i18n/en.i18n.json
- packages/rocketchat-livechat/server/lib/QueueMethods.js
Closes #7292
This fixes desktop notifications not being created if a live chat visitor created a room by sending the first message.
- Notifications other than livechat and guest pool are based upon the user's subscriptions. Only for the live chat inquiries (the "requests for an agent to join"), there's a need for an alternative mechanism.
- Once an agent is joined, he's the only one to notify which matches the default: He'll have a valid subscription once joined.
- All code added is non-destructive (new functions, arrays concatenated, ...) - it will most likely not make things worse, even if it doesn't meet all the aspects
- From an architectural perspective, it would be better to have the code for creating the livechat-notifications in a separate hook defined in the livechat-package. The …
> [NEW] Livechat notifications on new incoming inquiries for guest-pool

- .circleci/config.yml
- .travis.yml
- package-lock.json
- package.json
I've done a few things on this PR:
* Merge `eslint` and `stylelint` into `lint` npm script. This is better IMO because where ever we use `lint` script (like `husky` pre-push hook) it will validate both javascript and css.
* Changed to use Meteor's `npm` instead of installed on host. This will make sure the correct `npm` version is used to everything
* Removed `npm i` from `start` script. This doesn't make sense IMO and was causing changes to `package-lock.json` everytime `start` was called.
> Better organize package.json

- packages/rocketchat-livechat/.app/client/lib/_livechat.js
As a guest's conversation is picked from the livechat queue, the agent is getting assigned to the room.
However, this was not properly subscribed to on the widget.
This lead to multiple issues:
- The agent's name was not depicted on the header of the livechat window
- The full name of the agent was not displayed but his username
The streamer subscription had a filter which did not match the actual property of the room.
It's a one-liner, but has quite nasty side-effects - and was tedious to fix. Any efforts on providing integration tests for livechat on the horizon?
> [FIX] Livechat agent joining on pick from guest pool

- packages/rocketchat-migrations/migrations.js
This is minor patch to allow multiple subcommands in the env var named "MIGRATION_VERSION" that is read by the DB Migration script. I have also replaced the occurrence of what I believe is now obsolete "MIGRATE" env var in some comments.
Background:
Currently, MIGRATION_VERSION supports a single command like "rerun", "exit" . There are cases, when we want to rerun a specific DB migration script and exit right away. This requires a combination of both "rerun" and "exit" to be passed in. This could be better than creating another subcommand that does the combination of both. The change should also be backwards compatible.
> [NEW] Allow multiple subcommands in MIGRATION_VERSION env variable

- packages/rocketchat-e2e/client/rocketchat.e2e.js
> Fix: Change wording on e2e to make a little more clear

- packages/rocketchat-lib/server/models/Users.js
Saving account preferences is giving `Internal Server Error`:
```
I20180926-14:13:22.553(-3)? Exception while invoking method 'saveUserPreferences' TypeError: Cannot read property 'clockMode' of undefined
I20180926-14:13:22.554(-3)?     at ModelUsers.setPreferences (/Users/diegosampaio/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:11608:56)
I20180926-14:13:22.554(-3)?     at MethodInvocation.saveUserPreferences (/Users/diegosampaio/dev/Rocket.Chat/.meteor/local/build/programs/server/app/app.js:11864:29)
I20180926-14:13:22.554(-3)?     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20180926-14:13:22.554(-3)?     at MethodInvocation.methodsMap.(anonymous function) …
```
> [FIX] Saving user preferences

- packages/rocketchat-markdown/parser/original/markdown.js
- packages/rocketchat-markdown/tests/client.tests.js
Fix #6586 
I added the same example from #6586 and it's working. Added a test case to it.
> [FIX] Markdown ampersand escape on links

- packages/rocketchat-theme/client/imports/components/modal.css
- packages/rocketchat-theme/client/imports/components/userInfo.css
Closes #11961 
I'm fixing errors on modal.css to avoid build breaking
> [FIX] Horizontal scroll on user info tab

- packages/rocketchat-lib/server/functions/notifications/index.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-lib/server/models/Subscriptions.js
Currently, mentions on public channels to users already in the room are sending two emails.
If the user is not already in the room, the user does not join automatically.
> [FIX] Duplicate email and auto-join on mentions

- packages/rocketchat-setup-wizard/client/setupWizard.html
This pull request aims to fix the behavior for Setup Wizard forms when a submit action is triggered, e.g., when ENTER key is typed in a input text field.
> [FIX] Set default action for Setup Wizard form submit

- README.md
Link in README is invalid and different with docs on https://rocket.chat/docs/contributing/translating/
> Correct LingoHub link in README.md

- server/startup/presence.js
You might want to disable the user presence monitor in a multi-instance setup because you don't need to **all** instances keep monitoring each user's status.
So starting up an instance with env var `DISABLE_PRESENCE_MONITOR` as `yes` or `true` and it will be disabled.
> [NEW] Ability to disable user presence monitor

- packages/rocketchat-livechat/client/lib/dateHandler.js
The check on the left and right hand side of `&&` is identical. From the surrounding code, it looks like the second part should be `isSame(to)`.
> [FIX] Date range check on livechat analytics

- packages/rocketchat-ui/getAvatarUrlFromUsername.js
Session seems to be always defined, but the Session.keys[key] is almost never defined resulting in avatar url's that look like /avatar/username?_dc=undefined
Feelings won't be hurt by dismissing for a better way.  :) Just would like to get rid of avatars requested like this.
> [FIX] avatar?_dc=undefined

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-header.css
> [NEW] sidenav size on large screens

- packages/rocketchat-e2e/client/rocketchat.e2e.room.js
Unlike in OTR, currently e2e rooms are not properly rendering UTF-8 encoded messages.
> [FIX] E2E: Decrypting UTF-8 encoded messages

- packages/rocketchat-channel-settings-mail-messages/client/views/mailMessagesInstructions.js
The input Subject in Mail Messages was receiving an __undefined__ value as room name.
This was happening whenever the open room type was Direct Messages.
To solve this, I started to get the room name value like Header and SideNav do.
These components get the room name even if the open room type is Direct Messages.
They both use `RocketChat.roomTypes.getRoomName()`.
The Header example:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/components/header/header.js#L45
Closes #12363
> [FIX] Correct roomName value in Mail Messages (#12363)

- .vscode/launch.json
Debugging of files on root level was not possible using the awesome VSCode.
This PR adds a mapping of the meteor generated files and the source files on root-level. It was only done on`package/...` level earlier on.
> Fix: Developers not being able to debug root files in VSCode

- packages/rocketchat-i18n/i18n/zh.i18n.json
The word 'Disabled' original translation '残疾人' means 'disabled man' in English, which should be translated to '已禁用' in Chinese.
See the screenshot below.
> [FIX] `Disabled` word translation to Chinese

- packages/rocketchat-ui-message/client/messageBox.js
It limits the number of usernames shown above the textbox when people
are typing.
If the number of typing users isn't greater than 4, then the text will
show all usernames:
`username1, username2, username3 and username4 are typing`
But, if the number of typing users is greater than 4, then the last
username will be replaced by `others`, like this:
`username1, username2, username3 and others are typing`
The number 4 was chosen because it was already in the code
Closes #8722
> [IMPROVE] Limit the number of typing users shown (#8722)

- packages/rocketchat-emoji/client/lib/EmojiPicker.js
> [FIX] Emoji picker is not in viewport on small screens

- packages/rocketchat-ui-message/client/popup/messagePopupConfig.js
Based on emojiPicker's search:
https://github.com/RocketChat/Rocket.Chat/blob/dcdcbfba9eb10a4b87ad16f2628ec126444853d7/packages/rocketchat-emoji/client/emojiPicker.js#L59
Emoji search on messageBox is now looking for any occurence of search term in emoji name.
It doesn't expect anymore the emoji name starts with the search term.
Closes #9607
> [IMPROVE] Emoji search on messageBox behaving like emojiPicker's search (#9607)

- packages/rocketchat-i18n/i18n/de-AT.i18n.json
- packages/rocketchat-i18n/i18n/de-IN.i18n.json
- packages/rocketchat-i18n/i18n/de.i18n.json
This translation was too literal and didn't take the meaning and context into account.
> [FIX] German translation for for API_EmbedIgnoredHosts label

- packages/rocketchat-ui-master/client/main.js
- packages/rocketchat-ui-message/client/popup/messagePopup.js
- packages/rocketchat-ui-message/client/popup/messagePopupSlashCommandPreview.js
- packages/rocketchat-ui-sidenav/client/sidebarHeader.html
- packages/rocketchat-ui-sidenav/client/sidebarHeader.js
- packages/rocketchat-ui-sidenav/client/toolbar.html
- packages/rocketchat-ui-sidenav/client/toolbar.js
- packages/rocketchat_theme/client/imports/components/sidebar/toolbar.css
Previously the `toolbar` template was always rendered and its visibility was being controlled by CSS. That was causing a call to `spotlight` method on client startup and every time the use changed his status (due to reactivity).
So I changed to not render the `toolbar` template until the _search_ icon is clicked or the shortcut (Ctrl/CMD+K) is fired.
> [FIX] Spotlight method being called multiple times

- packages/rocketchat-channel-settings-mail-messages/client/index.js
- packages/rocketchat-channel-settings-mail-messages/client/lib/startup.js
- packages/rocketchat-channel-settings-mail-messages/client/views/mailMessagesInstructions.js
- packages/rocketchat-channel-settings-mail-messages/package.js
- packages/rocketchat-channel-settings-mail-messages/server/index.js
- packages/rocketchat-channel-settings-mail-messages/server/lib/startup.js
- packages/rocketchat-channel-settings-mail-messages/server/methods/mailMessages.js
> Convert rocketchat-channel-settings-mail-messages to main module structure

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-slashcommands-help/server.js
- packages/rocketchat-ui-master/client/main.js
As pointed out in #12519 Chrome already uses `Shift+ESC`, colliding
with the 'mark all messages as read' keyboard shortcut in
RocketChat. This change adds the `CTRL` modifier to the shortcut,
i.e. mapping
Shift+ESC | CTRL+ESC
Closes #12519
> [IMPROVE] Add CTRL modifier for keyboard shortcut

- packages/rocketchat-apps/client/admin/appLogs.html
- packages/rocketchat-integrations/client/views/integrations.html
- packages/rocketchat-integrations/client/views/integrationsNew.html
- packages/rocketchat-integrations/client/views/integrationsOutgoing.html
- packages/rocketchat-integrations/client/views/integrationsOutgoingHistory.html
- packages/rocketchat-ui-admin/client/admin.html
- packages/rocketchat_theme/client/imports/general/base_old.css
- tests/pageobjects/administration.page.js
> [FIX] Admin styles

- packages/rocketchat-api/server/api.js
This PR adds a new acceptable header('x-visitor-token') to allow Livechat REST requests when CORS is enabled.
> [IMPROVE] Add new acceptable header for Livechat REST requests

- packages/rocketchat-mailer/package.js
Added `email` as a dependency in `rocketchat-mailer` package. This was causing a warning while running the tests (`cannot read 'send' of undefined`). Although the package has not been modified, probably the cause of this is the conversion of packages to `mainModules`.
> Fix: Add email dependency in package.js

- .eslintrc
Removed `RocketChatFile` from globals variables. Done in https://github.com/RocketChat/Rocket.Chat/pull/12644.
> Removed RocketChatFile from globals

- packages/rocketchat_theme/client/imports/components/emojiPicker.css
- packages/rocketchat_theme/client/imports/components/messages.css
- packages/rocketchat_theme/client/imports/general/base_old.css
> [IMPROVE] border-radius to use --border-radius

- packages/rocketchat-apps/server/bridges/rooms.js
- packages/rocketchat-lib/server/models/Rooms.js
Allow apps to create direct messages;
Implements getMembers;
Allow apps to search for direct message rooms based on usernames;
> [IMPROVE] Rocket.Chat.Apps

- packages/rocketchat-apps/server/bridges/persistence.js
Update persistence based on association record.
> [IMPROVE] Allow apps to update persistence by association

- packages/rocketchat-ui-admin/client/admin.html
- packages/rocketchat-ui-admin/client/admin.js
- packages/rocketchat_theme/client/imports/general/base_old.css
- tests/pageobjects/administration.page.js
To keep the Administration sections accessible, the whole section title is clickable instead of just the arrow button.
> Regression: Expand Administration sections by toggling section title

- .circleci/update-releases.sh
This will help fail the build if for some reason the release doesn't get uploaded
> Add check to make sure releases was updated

- server/methods/getUsernameSuggestion.js
> [IMPROVE] Username suggestion logic

- packages/rocketchat-i18n/i18n/de-AT.i18n.json
- packages/rocketchat-i18n/i18n/de-IN.i18n.json
- packages/rocketchat-i18n/i18n/de.i18n.json
Closes https://github.com/RocketChat/Rocket.Chat/issues/12720
Just a small fix for a typo in German translation for Reacted_with ("you reacted with")
> German translation typo fix for Reacted_with

- packages/rocketchat-livechat/.app/client/lib/_livechat.js
Closes #12849.
This PR fixes a bug on Livechat stream, where a wrong parameter name is being passed over `extraData` object. Because of this, the agent data is not being updated on Livechat client when an agent takes the inquiry from the Livechat queue.
Curiously, the commit with the wrong implementation was submitted by the same community member that has detected the bug, as you can see below: 
https://github.com/RocketChat/Rocket.Chat/commit/933378a7f6939adb493d9d2d6241f3780a52fc5e#diff-cb44dc00ab056e5ec45123dcc1bbf8ec
> [FIX] Incorrect parameter name in Livechat stream

- packages/rocketchat-lib/server/lib/debug.js
Closes #12868
Closes #12762
Closes #12820
YES I REMOVED `this.unblock()` I really dont belive its a "performance hack"
> [FIX] cannot reset password

- server/stream/messages.js
Closes #12574 
Closes https://github.com/RocketChat/Rocket.Chat.js.SDK/issues/38
This fix is temporary, the room information will be removed in the future duo to performance reasons. Right now we back the code to encode each message individually to send the user's room information for each subscribed room, which is not performatic but keeps the compatibility.
> [FIX] Stream of my_message wasn't sending the room information

- packages/rocketchat-cas/server/cas_server.js
Closes #12656 
This PR fixes CAS login for renamed users and also prevents RocketChat from storing invalid emails as verified when logging though CAS.
> [FIX] CAS Login not working with renamed users

- packages/rocketchat-ui/client/lib/RoomManager.js
Allow users/developers to change the max number of rooms opened using `localStorage` its temporary and if results in some benefit we gonna remove and develop changes based on that data
> changed maxRoomsOpen

- packages/rocketchat-ui-message/client/popup/messagePopup.js
Currently there are many situations where `spotlight` can be called even if it's closed.
This PR fixes it by adding the reactivity only to the template, so when it's destroyed, the reactivity is destroyed as well.
There are still other times that it's called unnecessarily, like if you click on a result from a toolbar search it will be called again after you click. But this fix prevent many calls like when you search from someone it will call `spotlight` on background for every message you receive.
> [FIX] Spotlight being called while in background

- .eslintrc
- packages/rocketchat-custom-oauth/client/custom_oauth_client.js
- packages/rocketchat-custom-oauth/server/custom_oauth_server.js
- packages/rocketchat-lib/server/methods/refreshOAuthService.js
- packages/rocketchat-lib/server/oauth/oauth.js
- packages/rocketchat-lib/server/startup/oAuthServicesUpdate.js
- packages/rocketchat-ui/client/lib/iframeCommands.js
- server/startup/migrations/v018.js
- server/startup/migrations/v075.js
> Remove global ServiceConfiguration

- packages/rocketchat-livechat/client/views/app/tabbar/visitorForward.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/models/Users.js
Currently, when an agent wants to tranfer a Livechat to another one, all agents are displayed on the list, even offline agents.
The fact is that when a Livechat is transferred to an offline agent, the visitors on Widget side stay wanting for a response that never comes, so this situation brings a very bad user experience to Livechat users.
This PR adds some improvements related to the situation described above, such as filtering/displaying only online agents, as well as improve the transfer method, which will not accept any offline agent.
A few Livechat customers/partners are complaining about the case I just described, they're getting bad feedbacks from their clients, so would be good having this fix on our next release(`0.73`).
> [IMPROVE] Allow transfer Livechats to online agents only

- packages/rocketchat-api/server/v1/chat.js
- packages/rocketchat-lib/server/models/_Base.js
- packages/rocketchat-lib/server/models/_BaseDb.js
- tests/data/chat.helper.js
- tests/end-to-end/api/05-chat.js
Closes: https://github.com/RocketChat/Rocket.Chat/issues/12155
> [NEW] Added chat.getDeletedMessages since specific date

- packages/rocketchat-lib/server/functions/setUserAvatar.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/12787
> [FIX] Fix set avatar http call, to avoid SSL errors

- packages/rocketchat-file-upload/server/config/GridFS.js
Fallback content-type as application/octet-stream for uploaded files
Closes #8540
> [FIX] Download files without extension wasn't possible

- packages/rocketchat-models/server/models/Rooms.js
Current model name is incorrect causing all previous rooms to be not accessible.
> [FIX] Rooms model's collection name

- packages/rocketchat-livechat/server/api/lib/livechat.js
- packages/rocketchat-livechat/server/api/v1/message.js
- packages/rocketchat-livechat/server/lib/Livechat.js
We have a setting that defines if it's necessary to display a `connecting...` message when a new livechat is started.
This setting depends on `guest pool` routing method and it wasn't being sent over the `GET` config payload.
> [IMPROVE] Adds the "showConnecting" property to Livechat Config payload

- packages/rocketchat-livechat/server/api/lib/livechat.js
- packages/rocketchat-livechat/server/api/v1/room.js
To close Livechat rooms through `RocketChat.Livechat.closeRoom` method, the room type field is required on the object passed by parameter.
The `livechat/room.close` endpoint gets the room data through the `findRoom` method, but it wasn't returning the room type field and, because of this, the `livechat/room.close` endpoint was not being able to close Livechat rooms.
> [IMPROVE] Return room type field on Livechat findRoom method

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-statistics/server/functions/get.js
- packages/rocketchat-ui-admin/client/adminInfo.html
This adds number of uploads and how much storage those uploads are using to the admin screen:
> [NEW] Display total number of files and total upload size in admin

- packages/rocketchat-emoji/client/emojiPicker.js
The issue was the conflict with variable `emoji` [here](https://github.com/RocketChat/Rocket.Chat/pull/13207/files#diff-79b87b9e381bc2396dc549a127e8e776L87).. So in order for better reading I changed it to `current` inside the loop.
> Regression: Fix emoji search

- packages/rocketchat-lib/client/CustomTranslations.js
- packages/rocketchat-lib/client/OAuthProxy.js
- packages/rocketchat-lib/client/UserDeleted.js
- packages/rocketchat-lib/client/defaultTabBars.js
- packages/rocketchat-lib/client/lib/LoginPresence.js
- packages/rocketchat-lib/client/lib/formatDate.js
- packages/rocketchat-lib/client/lib/openRoom.js
- packages/rocketchat-lib/client/lib/roomExit.js
- packages/rocketchat-lib/client/lib/settings.js
- packages/rocketchat-lib/client/lib/startup/commands.js
- packages/rocketchat-lib/client/lib/userRoles.js
- packages/rocketchat-lib/client/methods/sendMessage.js
- packages/rocketchat-lib/client/views/customFieldsForm.js
- packages/rocketchat-lib/lib/getUserPreference.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-utils/client/index.js
- packages/rocketchat-utils/client/lib/CustomTranslations.js
> Remove some dependencies inside rocketchat-lib/client 

- packages/rocketchat-message-pin/server/pinMessage.js
PR #12739 added authentication checks for message pinning, however it does not actually work and will always error with not-authorized because it's checking a subscription-based role without providing the room ID.
> Regression: Fix message pinning

- packages/rocketchat-livechat/server/api/v1/room.js
- packages/rocketchat-livechat/server/methods/transfer.js
This PR adds a new REST endpoint allowing authenticated users(livechat agents/managers) to forward livechat rooms over REST API approach.
> [NEW] REST endpoint to forward livechat rooms

- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/saveSettings.js
- packages/rocketchat-settings/lib/settings.js
the old method was calling multiple times `saveSetting`, now we have one `saveSettings`, that you can pass all settings in a row.
> [FIX] Settings saving was being called multiple times and being denied by Rate Limiter in some cases

- packages/rocketchat-lib/server/startup/settings.js
No migration is required, it will update the setting visibility on next start.
> [IMPROVE] Send `uniqueID` to all clients so Jitsi rooms can be created correctly

- packages/rocketchat-lib/server/publications/settings.js
- packages/rocketchat-models/server/models/Settings.js
Closes #11604
Closes #12399
An `else` directive introduced the issue at version 0.67.0: https://github.com/RocketChat/Rocket.Chat/pull/10749/files#diff-ff8f9f02a53856a978c533000a92bd12R70
> [FIX] Notify private settings changes even on public settings changed

- docker-compose.yml
The current recommendation of Rocket.Chat is MongoDB 3.6.
Initializing a Docker Compose Setup with MongoDB 3.2 would require a step by step upgrade via MongoDB 3.4. See the release notes of Mongo DB:
* [3.4](https://docs.mongodb.com/manual/release-notes/3.4-upgrade-standalone/)
* [3.6](https://docs.mongodb.com/manual/release-notes/3.6-upgrade-standalone/)
This can be skipped by just using a more recent version of MongoDB.
> [IMPROVE] Update to MongoDB 4.0 in docker-compose file

- packages/rocketchat-api/package.js
- packages/rocketchat-api/server/api.js
- packages/rocketchat-apps/client/admin/appInstall.html
- packages/rocketchat-apps/server/communication/rest.js
Adds a new option for defining endpoints that require user permissions for access
> [IMPROVE] Add API option "permissionsRequired"

- packages/rocketchat-channel-settings/server/functions/saveRoomType.js
- packages/rocketchat-lib/server/functions/notifications/email.js
- packages/rocketchat-lib/server/functions/notifications/index.js
- packages/rocketchat-livechat/lib/messageTypes.js
- packages/rocketchat-livechat/server/api/v1/room.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/methods/closeByVisitor.js
- packages/rocketchat-livechat/server/startup.js
- packages/rocketchat-mailer/server/api.js
Some emails were not translated due to two main issues:
- Wrong language setting - https://github.com/RocketChat/Rocket.Chat/commit/351c44a988be936d05db60076ff7426fe40774d9
- Mailer was not looking for server's default language - https://github.com/RocketChat/Rocket.Chat/commit/3d15fb210b5779d838f0b2139ad763a18c8816d9
> [FIX] Not translated emails

- packages/rocketchat-lib/client/lib/openRoom.js
- packages/rocketchat-models/client/models/Users.js
Code to show the amount of finds via console
```javascript
models = require('meteor/rocketchat:models');
Object.keys(models).forEach((modelName) => {
if (models[modelName].after) {
models[modelName].after.find(function(userId, selector) {console.log('find', modelName, selector/*, (new Error).stack*/)});
models[modelName].after.findOne(function(userId, selector) {console.log('findOne', modelName, selector/*, (new Error).stack*/)});
}
})
```
> Room loading improvements

- packages/rocketchat-notifications/server/lib/Notifications.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/13514
> [FIX]Fix wrong this scope in Notifications

- packages/rocketchat-ui-flextab/client/flexTabBar.html
- packages/rocketchat_theme/client/imports/components/tooltip.css
Additionally, it avoids horizontal scrolling in room view when tooltip text is too large.
> Add better positioning for tooltips on edges

- packages/rocketchat-lib/server/functions/index.js
- packages/rocketchat-lib/server/functions/setUsername.js
- packages/rocketchat-tokenpass/client/tokenpassChannelSettings.js
- packages/rocketchat-ui-message/client/messageBoxAudioMessage.js
Problem found when testing https://github.com/RocketChat/Rocket.Chat/pull/13598 and tying to send an audio.
I've created a script to check all imports:
```javascript
const fs = require('fs');
const glob = require('glob');
const packagesToMove = {
'rocketchat:cors': 'rocketchat-cors',
'rocketchat:sms': 'rocketchat-sms',
'rocketchat:2fa': 'rocketchat-2fa',
'rocketchat:accounts': 'rocketchat-accounts',
'rocketchat:analytics': 'rocketchat-analytics',
'rocketchat:api': 'rocketchat-api',
'rocketchat:assets': 'rocketchat-assets',
'rocketchat:authorization': 'rocketchat-authorization',
'rocketchat:autolinker': 'rocketchat-autolinker',
'rocketchat:autotranslate': 'rocketchat-autotranslate',
'rocketchat:bot-helpers': 'rocketchat-bot-helpers',
'rocketchat:cas': 'rocketchat-cas', …
```
> Fix wrong imports

- packages/rocketchat-markdown/lib/parser/original/markdown.js
- packages/rocketchat-markdown/tests/client.tests.js
Closes #13187 
cc @tassoevan, would you please review
> [FIX] Partially messaging formatting for bold letters

- packages/rocketchat-markdown/lib/parser/marked/marked.js
Messages parsed using `Marked` as the `Markdown Parser` would contain links that would send the current window to that location. This fix makes sure those links are opened in a new tab.
This change has made my team very happy.
> [FIX] Bugfix markdown Marked link new tab

- packages/rocketchat-apps/client/admin/apps.js
This fixes an issue where if you select the `Installed` Apps tab before the loading of the Marketplace Apps finished, the marketplace apps would be displayed when it finished loading.
> [FIX] Race condition on the loading of Apps on the admin page

- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-lib/lib/roomTypes/direct.js
- packages/rocketchat-ui-sidenav/client/chatRoomItem.js
The icon `@` was missing on room header:
added it back:
> Regression: Fix icon for DMs

- packages/rocketchat-lib/server/functions/cleanRoomHistory.js
- packages/rocketchat-models/server/models/Messages.js
- packages/rocketchat-ui-clean-history/client/views/cleanHistory.html
- packages/rocketchat-ui-clean-history/client/views/cleanHistory.js
- packages/rocketchat-ui-utils/client/lib/RoomManager.js
> Regression: Prune Threads

- app/federation/client/main.js
- app/federation/server/peerDNS.js
Now, DNS TXT resolution happens using a subdomain, making it easier to maintain the records.
> Change the way to resolve DNS for Federation

- .snapcraft/snap/hooks/post-refresh
Previous version of refresh hook force setting of default values, causing that next snap release overwrites previous configurations by users, this new refresh hook only set default values if not configured by the user before, which is still necessary for the case that the refresh happens of snap versions prior to 0.73.2
Refresh tested from 0.72 to 1, and 0.74 to 1 (pre hooks existence, and post hooks existence)
> [FIX] Fix snap refresh hook

- app/models/server/models/Rooms.js
There are some queries that sort by `ts` field, specially some for livechat. Those queries are very low on large databases due to this missing index.
> [IMPROVE] Add index for room's ts

- app/apps/server/bridges/messages.js
- app/apps/server/bridges/rooms.js
- app/apps/server/communication/rest.js
- app/authorization/client/startup.js
- app/authorization/client/views/permissionsRole.js
- app/authorization/server/publications/permissions.js
- app/models/server/models/Messages.js
- app/models/server/models/Subscriptions.js
- app/models/server/models/Users.js
- app/models/server/models/_BaseDb.js
- app/tokenpass/server/cronRemoveUsers.js
- app/ui-cached-collection/client/models/CachedCollection.js
- app/ui/client/lib/esc.js
- app/utils/lib/templateVarHandler.js
Removing almost all dynamic imports, except those with circular dependency between archives.
```
app/models/server/Messages.js => app/file-upload/server/lib/FileUpload.js
app/ui-cached-collection/client/models/CachedCollection.js => app/ui-utils/client/lib/RoomManager.js
app/ui-cached-collection/client/models/CachedCollection.js => app/models/client/ChatRoom.js
app/ui-cached-collection/client/models/CachedCollection.js => app/models/client/CachedChatRoom.js
app/ui-utils/client/lib/MessageAction.js => app/ui/client/views/app/room.js
```
> Removing (almost) every dynamic imports

- app/threading/server/authorization.js
The Livechat fileupload was breaking because the validation method was not checking the `room` object.
> Fix: addRoomAccessValidator method created for Threads

- app/theme/client/imports/forms/input.css
- app/ui-message/client/messageBox.html
- app/ui-message/client/messageBox.js
- app/ui-message/client/messageBoxAudioMessage.html
- app/ui-message/client/messageBoxAudioMessage.js
Before:
After:
Before:
```
TypeError: undefined is not an object (evaluating 'navigator.permissions.query') – undefined
```
After:
Only use Permissions API when available on the browser and assume the audio recording is allowed; when denied to start recording, hides the audio recording button (microphone icon).
> [FIX] Some Safari bugs

- .circleci/config.yml
Our jobs are stuck at this moment, this is intended to keep things working might (or not) be reverted after the instability on CircleCI is gone
> Use CircleCI Debian Stretch images

- .circleci/config.yml
Fix `deploy` job since last update on #13906
> Fix missing dependencies on stretch CI image

- .docker-mongo/Dockerfile
Since our base image is now using Stretch, the packages installed should use same sources.
Also, updated to MongoDB 4.0
> Update preview Dockerfile to use Stretch dependencies

- app/ui-sidenav/client/chatRoomItem.js
- app/ui-sidenav/client/roomList.js
- app/ui-sidenav/client/sidebarItem.html
- app/ui-sidenav/client/sidebarItem.js
Previously when "Hide Counter" was chosen in combination with "Show Unread on Top", rooms with mentions were not being shown there, this PR fixes it by showing there.
> [IMPROVE] Show rooms with mentions on unread category even with hide counter

- app/theme/server/server.js
Change the technique used to serve the `theme.css` file.
Previous code was overwriting an internal meteor function that read/validate all assets of the app and if perhaps the CSS theme was already "ready" (the less was compiled), it was then added to assets list. This was causing an issue though, that on the first start of a server, where the compiled CSS was not yet saved on DB, then the `theme.css` was being served. Causing the UI to look like this:
Previously, to fix the above issue a restart was required.
> [FIX] Loading theme CSS on first server startup

- server/startup/serverRunning.js
I thought about showing an alert.. but i'm not sure how we are injecting .node_version.txt or i'd try to do the same for mongodb.
I thought about hard coding `^3.2.0` but meteor cli doesn't even ship with that yet 🤦‍♂️
> [BREAK] Prevent start if incompatible mongo version

- app/api/server/v1/users.js
Closes #12976
When **normal users** doesn't have any preferences, `user.settings` is an empty object instead of undefined. My solution was to check both.
Maybe a better solution is all users start with settings as undefined.
> [FIX] users.getPreferences when the user doesn't have any preferences

- app/federation/server/federation-settings.js
- app/ui-admin/client/admin.js
This is a proposal to allow disabling the `reset` button on some settings.
The motivation is that some settings are not useful on their default state, so I think that having a reset button might mislead the user.
Just FYI, I based this branch of off #14025.
> Settings: disable reset button

- app/lib/server/functions/notifications/email.js
- app/lib/server/lib/sendNotificationsOnMessage.js
The issue was:
If someone mentions an user that is not following the thread, that user (the user mentioned) would not get a notification.
Also fixes #14019 by always using the sender as the email `From`
> Fix sending notifications to mentions on threads and discussion email sender

- app/discussion/client/lib/messageTypes/discussionMessage.js
- app/mentions/client/client.js
- app/mentions/client/index.js
- app/mentions/client/mentionLink.css
- app/mentions/lib/MentionsParser.js
- app/mentions/server/Mentions.js
- app/mentions/tests/client.tests.js
- app/theme/client/imports/components/badge.css
- app/theme/client/imports/components/sidebar/sidebar-item.css
- app/theme/client/imports/general/base_old.css
- app/theme/client/imports/general/variables.css
- app/ui-sidenav/client/sidebarItem.html
- app/ui-sidenav/client/sidebarItem.js
- app/ui-utils/client/lib/RoomManager.js
- private/client/imports/general/variables.css
- private/server/colors.less
> [IMPROVE] New sidebar item badges, mention links, and ticks

- app/ui-sidenav/client/sidebarItem.js
Now if there is both an `@user` and `@here` or `@all` in a channel, the badge will be blue
> Prioritize user-mentions badge

- app/custom-oauth/client/custom_oauth_client.js
- app/custom-oauth/server/custom_oauth_server.js
- app/oembed/server/server.js
- app/ui/client/views/app/room.js
- app/utils/lib/getURL.js
- app/utils/lib/isURL.js
The problem was the function `getURL` being introduced on the `messageAttachment` template in order to resolve the `image_url` field from the `attachment`. The function is currently prepending the URL provided with the `CDN_PREFIX` setting.
This PR simply introduces a way for the `getURL` function to identify absolute URLs, so that it doesn't prepend the path received when that's the case
> [FIX] Gifs not rendering

- app/meteor-accounts-saml/server/saml_server.js
- app/meteor-accounts-saml/server/saml_utils.js
- app/ui-sidenav/client/sidebarItem.js
Closes: #13562 
SAML experts please let me know if something is missing?
> [FIX] Support for handling SAML LogoutRequest SLO

- app/ui-utils/client/lib/RoomHistoryManager.js
- app/ui/client/views/app/room.js
The template wasn't aware of changes on field `subscription.ls` when handling the `scroll` event on the message list.
> Fix top bar unread message counter

- app/custom-oauth/server/custom_oauth_server.js
Initially implemented by @mklan on PR #10711 
Since his fork has been deleted, it was no longer possible to solve the conflicts on the original PR.
Original Description:
> There are cases where the user's name is changed in the external database. This feature will update the name if it was changed and when the option merge users is set to true.
> [NEW] update name of user if changed externally using CustomOAuth

- app/ui-message/client/message.js
If some user is sending messages uninterruptedly before and after midnight, the `new-day` class is added together with the regular `sequential` class for sequences of messages from the same user, leading to a broken date separator.
> Fix: Remove message class `sequential` if `new-day` is present

- app/integrations/client/views/integrationsIncoming.html
- app/integrations/client/views/integrationsIncoming.js
- app/integrations/client/views/integrationsOutgoing.html
- app/integrations/client/views/integrationsOutgoing.js
- app/integrations/client/views/messageExample.js
The message examples in the integrations stopped working after the changes in the message component.
> [Regression] Fix integrations message example

- app/livechat/server/api/lib/livechat.js
- app/livechat/server/api/v1/message.js
- app/livechat/server/api/v1/visitor.js
- app/livechat/server/lib/Livechat.js
When a guest is registered through the new Livechat widget, there is no DDP connection available yet, so we need to collect the information related to HTTP header from the REST API endpoints.
> [FIX] Missing connection headers on Livechat REST API

- app/lib/server/functions/deleteMessage.js
- app/lib/server/functions/updateMessage.js
- app/message-pin/server/pinMessage.js
- app/message-snippet/server/methods/snippetMessage.js
- app/models/server/models/Messages.js
Related to https://github.com/RocketChat/Rocket.Chat/pull/14127
Updating a message from Apps is currently failing if `Keep Per Message Editing History` setting is `true`, because the model is calling `Meteor.userId()`, but it doesn't the needed context if being called from an app.
> [FIX] Updating a message from apps if keep history is on

- app/ui-utils/client/lib/RoomHistoryManager.js
When a thread message has no `msg` and all its attachments have neither `title` nor `description`, the preview fails.
> Prevent error on normalize thread message for preview

- app/meteor-accounts-saml/server/saml_rocketchat.js
The default certificate setting is expected on a different format from the other certificate settings. This PR changes it to accept it on the other format as well.
> [FIX] SAML certificate settings don't follow a pattern

- app/lib/server/lib/notifyUsersOnMessage.js
- app/theme/client/imports/components/badge.css
- app/theme/client/imports/general/variables.css
- app/ui-sidenav/client/sidebarItem.js
- private/client/imports/general/variables.css
Before now, all messages on DMs would should a "black" badge showing how many messages were sent.
This PR changes that behavior to show the badge as blue if a mention is sent inside the DM, like in the image below:
> Increment user counter on DMs

- app/ui-utils/client/lib/messageBox.js
One hour debugging and one character to fix it. If Discussions are not enabled, the `discussionFromMessageBox` module accidentally remove all `Create_New` message box actions.
> Regression: wrong expression at messageBox.actions.remove()

- app/mentions/client/client.js
Sometimes `Meteor.user()` is falsy even with `Meteor.userId()` defined.
> Regression: Prevent startup errors for mentions parsing

- app/emoji/client/emojiParser.js
- app/theme/client/imports/general/base_old.css
- app/threads/client/flextab/thread.html
- inline images were too large
- emojis were improperly tagged as `big`
- thread title not rendered as HTML in thread tab
> Regression: Broken UI for messages

- app/livechat/server/index.js
- app/livechat/server/methods/setUpConnection.js
We need to handle the `onClose` connections created from the new livechat client.
Since the new Livechat client works through the REST API approach, we need to update the guest status after its connection is closed.
> [NEW]Set up livechat connections created from new client

- app/lib/server/functions/notifications/mobile.js
Adds a default empty object when getting the badge count notification.
> [FIX] Empty result when getting badge count notification

- app/ui-message/client/message.js
as we are grouping message outside Blaze's reactivity, when we insert back reactivity some things are fighting (:, we should fix the grouping code, but its good for now
> Regression: fix grouping for reactive message

- app/lazy-load/client/lazyloadImage.js
Closes #5028 and #14092 
**Issue and research**: On researching and playing around with codebase a bit I found out that message is re-created everytime someone updates the message, (e.g: Starring or adding a reaction as mentioned in the issues that this PR solves.)Since it is meteor's default reactivity system because of which it is happening, my resolution is a simple work-around.
**Resolution**:  Add a `onDestroy` function to the lazyloadtemplate(This template is responsible for showing the preview of the attachment.) This template gets destroyed and recreated whenever there is some update in the message (e.g: Starring or adding a reaction). Workaround is a simple `Template.onDestroy` call that stores the value of `loaded` state before being destroyed because of the update in the …
> [FIX] Image attachment re-renders on message update

- app/apps/client/admin/apps.html
Right now is showing Marketplace in the apps section
Before:
> [FIX] Wrong header at Apps admin section

- server/startup/serverRunning.js
Switching to short link to redirect.  This will let us direct to the 1.0 upgrade document and then in the future we can redirect to a specific doc with out having to modify this again.
> [FIX] Switch oplog required doc link to more accurate link

- app/ui-flextab/client/tabs/userActions.js
- app/ui-utils/client/lib/MessageAction.js
> [Fix] group name appears instead of the room id

- app/gitlab/lib/common.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/14307
According to [OAuth Gitlab's docs](https://docs.gitlab.com/ee/api/README.html#oauth2-tokens) the correct name for token is `access_token`.
> [FIX] Wrong token name was generating error on Gitlab OAuth login

- server/stream/streamBroadcast.js
> [FIX] Stream not connecting connect when using subdir and multi-instance

- app/meteor-accounts-saml/client/saml_client.js
- app/meteor-accounts-saml/server/saml_server.js
Reverts #13791 
This makes both mobile applications not be able to authenticate. So reverting the change
ios and android both send a random token.  So we cannot simply stop accepting: https://github.com/RocketChat/Rocket.Chat.Android/pull/1326/files#diff-7274909d551b0d3613c6ba7ef386cfb1R280
> [FIX] SAML credentialToken removal was preventing mobile from being able to authenticate

- app/statistics/server/functions/get.js
- app/utils/server/functions/getMongoInfo.js
- app/utils/server/index.js
- server/startup/serverRunning.js
Falls back to old way and just sets engine to unknown if it can't get it.
cc @LuluGO this will help with helm chart once merged
> [FIX]  Fallback to mongo version that doesn't require clusterMonitor role

- app/threads/client/flextab/thread.js
- app/threads/client/flextab/threads.js
- app/ui-utils/client/lib/messageContext.js
that's why some message actions disappeared.
> [FIX] Messages on thread panel were receiving wrong context/subscription

- app/discussion/server/methods/createDiscussion.js
Closes #14378
Discussion names should not be validated by regular validators, because it is a random value.
> [FIX] Discussion name being invalid

- app/theme/client/imports/components/contextual-bar.css
- app/theme/client/imports/general/base_old.css
> [FIX] Channel Leader Bar is in the way of Thread Header 

- app/theme/client/imports/components/messages.css
- app/threads/client/flextab/thread.html
- app/threads/client/flextab/thread.js
- app/threads/client/flextab/threads.html
- app/ui-message/client/message.js
Closes #14413
Behavior inside thread tab and styles were updated too.
> [FIX] Ignored messages

- app/custom-sounds/client/admin/adminSounds.html
- app/custom-sounds/client/admin/adminSounds.js
> [NEW] Add pause and reset button when adding custom sound  

- .meteor/versions
Updating to fix an issue with Edge browser which was calling back to server any received event.
https://github.com/RocketChat/meteor-streamer/pull/41
> Update Meteor Streamer package

- app/message-star/client/actionButton.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/14501
> [FIX] Duplicated link to jump to message 

- app/emoji-emojione/lib/rocketchat.js
Closes #14575
Some emojis where moved to `shortnames` instead of having their own item on the list, which makes sense but broke recent emoji's list for those who have one of those moved ones.
> Fix: Add emoji shortnames to emoji's list

- app/emoji-emojione/lib/rocketchat.js
The shortname for thumbs up emoji `:+1:` was not working because its `+` sign is escaped on the `shortnames` string, where it tries to find using `indexOf`..
for the fix I needed to copy the whole function and add the same escape method (`replace(/[+]/g, '\\$&')`) pior the `indexOf`
> Fix thumbs up emoji shortname

- app/mailer/server/api.js
Closes https://github.com/RocketChat/feature-requests/issues/121.
The Email sender wasn't supporting the `replyTo` property.
> [FIX] Send replyTo for livechat offline messages

- server/startup/migrations/index.js
- server/startup/migrations/v147.js
This removes old, pre-beta, federation configs from the database
> Removing unnecesary federation configs

- app/meteor-accounts-saml/server/saml_server.js
> [FIX] SAML login error.

- app/federation/server/PeerDNS.js
Docs in: https://github.com/RocketChat/docs/pull/1307
> [IMPROVE] Add an optional rocketchat-protocol DNS entry for Federation

- app/livechat/server/publications/livechatRooms.js
CLOSES #14395.
The `label` property is not used anymore in Livechat rooms. The right property to filter `rooms` by name is `fname`.
> [FIX] Wrong filter field when filtering current Livechats

- app/lib/server/functions/saveUser.js
If your server is configured to not require user's real name and an admin modifies anything else on the user's data, the real name is being erased.
> [FIX] User Real Name being erased when not modified

- app/utils/lib/fileUploadRestrictions.js
Since we may have specific integrations that involve file sharing, it's a good approach allowing to pass a custom whitelist to validate file extensions.
> Add custom fileupload whitelist property

- app/authorization/server/functions/canAccessRoom.js
- app/authorization/server/functions/hasPermission.js
- app/authorization/server/index.js
- app/authorization/server/methods/addPermissionToRole.js
- app/authorization/server/methods/addUserToRole.js
- app/authorization/server/methods/deleteRole.js
- app/authorization/server/methods/removeRoleFromPermission.js
- app/authorization/server/methods/removeUserFromRole.js
- app/authorization/server/methods/saveRole.js
- app/authorization/server/publications/usersInRole.js
- app/file-upload/server/lib/FileUpload.js
- app/models/server/models/Users.js
- app/models/server/raw/BaseRaw.js
- app/models/server/raw/Permissions.js
- app/models/server/raw/Roles.js
- app/models/server/raw/Settings.js
- app/models/server/raw/Subscriptions.js
- app/models/server/raw/Users.js
- app/models/server/raw/index.js
- app/settings/server/index.js
- app/settings/server/observer.js
- app/settings/server/raw.js
- server/methods/canAccessRoom.js
This is the very first step in moving the code base away from any Meteor dependency.
The idea is to do this in parts, without breaking any code that depends on the "extracted" functions. So all extracted functions will be changed to return Promises, but to not break the current code we'll be also exporting those functions with `Promise.await`, so they'll still run "sync" in a Fiber environment.
So as you can see, [here](https://github.com/RocketChat/Rocket.Chat/pull/14777/files#diff-48f4f4974c2ee4726675e31798be3996R28) is the new promisified version of `canAccessRoom` and [here](https://github.com/RocketChat/Rocket.Chat/compare/demeteorize-canacessroom?expand=1#diff-30586305bbfef99e80591874e91f4627R28) is the `Promise.await` version being exported. So from now on, all code running within …
> Extract permissions functions

- server/lib/accounts.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/14637
Closes https://github.com/RocketChat/Rocket.Chat/issues/14755
We must the [`username` property to be able to set the user avatar](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/file-upload/server/lib/FileUpload.js#L283). Otherwise we'll get an [error for trying to set the avatar name to `undefined`](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/models/server/models/Avatars.js#L70). 
Previously this worked due to the fact that MongoDB accept `undefined` fields, behavior removed in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13586/files#diff-9c2d4074b56b688a6e8079932226d8a2L6).
> [FIX] Move the set Avatar call on user creation to make sure the user has username

- app/api/server/v1/channels.js
- tests/end-to-end/api/02-channels.js
This API Endpoint is made for RC Alexa and Google Action to allow Anonymous READ in VUI Devices without linking their accounts first to the Apps. This endpoint will enable access to messages in public channels, which are by definition public - and should be anonymous readable. In addition to that, this endpoint can be accessed by VUI user without any registration required. Also if admin has disabled anonymous read on his server, it won't work. So to summarise, after merging this API endpoint, we will be able to enable Alexa skill and Google Action to non-registered user if anonymous reading options are enabled on that server.
* Enable `Allow Anonymous Read` inside **Administration -> Accounts**
* Now you can use this to get message anonymously
```
curl …
```
> [NEW] Endpoint to anonymously read channel's messages

- app/models/server/models/Messages.js
CLOSES #14809.
When a new Livechat session starts we update the records(documents) related to the visitor navigation history because we track/store its navigation even when the visitor is not yet registered.
Due to that, we need to update those data, assigning the new `rid` related to the new livechat room, but we detected that there is a high latency happening during this process because there is not an `index` for the field -> `navigation.token`.
> [IMPROVE] Add new index to speed up the Livechat navigation history query's 

- app/emoji/client/emojiPicker.js
- app/lib/server/methods/getSingleMessage.js
- app/ui-master/client/main.js
- app/ui-sidenav/client/roomList.js
- app/ui-sidenav/client/sidebarItem.js
- app/ui-utils/client/lib/messageContext.js
- server/methods/browseChannels.js
Closes #14701
Closes #14712
Closes https://github.com/RocketChat/Rocket.Chat/issues/14764
- Fix loading chat rooms
- Fix loading Directory page
Still doesn't fix when first hit is on a room (i.e.: http://localhost:3000/channel/general). But this is an old issue (present since 0.74.3 at least).
> [FIX] Anonymous chat read

- app/theme/client/imports/general/base.css
- app/webdav/client/webdavFilePicker.html
- app/webdav/client/webdavFilePicker.js
As a part of my GSoC project to improve the webdav file picker UI/UX, I have added loading animation when the file picker loads for the first time, when a folder is opened, when back is pressed and when a file is selected.
> [NEW] Add loading animation to webdav file picker

- app/utils/lib/RoomTypeConfig.js
Turned out there was an issue when getting the setting value.
The error on production was:
```
TypeError: Cannot read property 'get' of undefined
at PublicRoomType.getNotificationDetails (app/utils/lib/RoomTypeConfig.js:261:29)
at notifyDesktopUser (app/lib/server/functions/notifications/desktop.js:23:54)
at Promise.asyncApply (app/lib/server/lib/sendNotificationsOnMessage.js:102:3)
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the …
```
> Regression: Fix desktop notifications not being sent

- app/apps/client/admin/appManage.js
Currently, when the App Details page sends a request to the marketplace to get the app data, it errors out when the marketplace can't find data for a local app (i.e. that is not published) and leaves with a blank page.
This PR fixes this behavior so that the App Details page keeps showing the content correctly even if the marketplace returns an error
> [FIX] Not showing local app on App Details

- app/meteor-accounts-saml/server/saml_server.js
> [FIX] SAML login by giving displayName priority over userName for fullName

- app/lib/client/methods/sendMessage.js
- app/lib/server/functions/sendMessage.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Closes https://github.com/RocketChat/Rocket.Chat/issues/2872
Closes https://github.com/RocketChat/Rocket.Chat/issues/14486
Closes https://github.com/RocketChat/Rocket.Chat/issues/14616
> [FIX] Prevent error on trying insert message with duplicated id

- app/ui-message/client/message.html
- app/ui-message/client/message.js
> [FIX] OTR key icon missing on messages

- app/ui/client/components/icon.js
- app/ui/client/index.js
- app/utils/client/index.js
- app/utils/client/lib/browsers.js
- package-lock.json
Since those helpers are specific to solve bugs related to SVG XLink on `icon` template, there is no need to make them global. Also, it discourages using browser hacks.
> [IMPROVE] Remove too specific helpers isFirefox() and isChrome()

- app/theme/client/imports/components/tabs.css
- app/ui/client/components/tabs.html
- app/ui/client/components/tabs.js
- app/ui/client/index.js
- Render tabs as `HTMLButtonElement`
- Add some ARIA attributes
- Add a focus style for keyboard navigation
> [IMPROVE] Update tabs markup

- app/livechat/server/api/v1/pageVisited.js
This PR implements the same behavior we had on the old Livechat widget.
We need to store the visitor's navigation history even if they are not yet registered, so we can't verify that the visitor or room exists before calling the Livechat related method.
> [FIX] Allow storing the navigation history of unregistered Livechat visitors

- app/federation/server/PeerServer/routes/events.js
- app/federation/server/PeerServer/routes/uploads.js
- app/federation/server/PeerServer/routes/users.js
- app/federation/server/config.js
- app/federation/server/index.js
This PR changes the improvements from #14972 to better organize the code, keeping the standards adopted in the code base regarding route definitions for the REST APIs.
With the changes implemented in this PR, whenever someone needs to know only the config for the Federation module, they'll be able to include only the file that exports those configs.
Thanks @sampaiodiego for the help with this 🤗
> [IMPROVE] Extract federation config to its own file

- app/custom-oauth/server/custom_oauth_server.js
For the identity step, Rocket.Chat is not asking for a JSON response. This is not a problem in case of success (as the user is redirected and the result doesn't matter), but in case of failure it generates a hard to read log.
This may the fix needed on #13331 as well.
> [FIX] CustomOauth Identity Step errors displayed in HTML format

- app/federation/server/PeerClient.js
- app/federation/server/PeerServer/PeerServer.js
- app/federation/server/federatedResources/FederatedUser.js
- app/federation/server/federation-settings.js
- app/federation/server/methods/dashboard.js
- app/lib/server/functions/deleteUser.js
- app/models/server/models/FederationEvents.js
- app/models/server/models/FederationPeers.js
- app/models/server/models/Users.js
- app/models/server/raw/Users.js
- app/statistics/server/functions/get.js
- package-lock.json
- server/startup/migrations/index.js
- server/startup/migrations/v148.js
> [IMPROVE] Add flag to identify remote federation users

- app/cloud/server/functions/getWorkspaceLicense.js
- app/cloud/server/index.js
> [IMPROVE] Connectivity Services License Sync

- app/api/server/v1/users.js
Not being able to send an empty string means the message cannot go back to the regular "online", "away", etc.
> [FIX] users.setStatus REST endpoint not allowing reset status message

- app/models/server/models/Rooms.js
- app/ui-admin/client/rooms/adminRooms.html
- app/ui-admin/client/rooms/adminRooms.js
- app/ui-admin/server/publications/adminRooms.js
> [NEW] Options to filter discussion and livechat on Admin > Rooms

- app/logger/server/server.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- server/startup/serverRunning.js
Support for MongoDB 3.2 will be removed on version 2.0 scheduled for October 2019.
The deprecation warning will be shown at:
- Logs in a box just after `SERVER RUNNING`
- Top banner for admins
- Direct message from Rocket.Cat to admins
> [NEW] Deprecate MongoDB version 3.2

- app/apps/server/communication/rest.js
When you visit an App's details page from the Marketplace it will request the versions from the marketplace to get more information about the App. This commit broke how it works and so this is a regression fix. https://github.com/RocketChat/Rocket.Chat/blame/develop/app/apps/server/communication/rest.js#L267
> Regression: Framework version being attached to a request that doesn't require it

- app/webdav/client/webdavFilePicker.css
- app/webdav/client/webdavFilePicker.html
- app/webdav/client/webdavFilePicker.js
*Webdav File Picker*: Added search functionality and fixed overflows
- Fixed overflows in the file path breadcrumbs and made it scrollable
- Added file search functionality with nice animations
- Added tooltips to the buttons in the file picker
- Truncated middle part for long file names in the file picker
> Regression: Webdav File Picker search and fixed overflows

- app/apps/client/admin/appManage.js
- app/apps/server/communication/rest.js
- app/apps/server/communication/websockets.js
- app/apps/server/orchestrator.js
- app/apps/server/storage/storage.js
- package.json
This PR improves HA behaviors for app management, which currently was preventing the new changes for the marketplace to work.
It's still a draft because we need [changes on the Apps-Engine side](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/128) as well.
> Regression: Improve apps bridges for HA setup

- .circleci/config.yml
Fix Docker images created from PRs containing a debug build.
> Add new step to build Docker image from PRs for production again

- app/ui-flextab/client/flexTabBar.js
- app/ui-flextab/client/tabs/inviteUsers.js
Closes #14796
This change hides the Threads button when threads are disabled.
> [FIX] Threads contextual bar button visible even with threads disabled

- .docker/Dockerfile.rhel
- .travis/snap.sh
- app/utils/rocketchat.info
- package-lock.json
- package.json
Since we'll remove some deprecations for the next release, we decided to release it as `2.0.0`
> Update to version 2.0.0-develop

- app/api/server/v1/emoji-custom.js
- tests/end-to-end/api/12-emoji-custom.js
Use `/api/v1/emoji-custom.list` instead. https://rocket.chat/docs/developer-guides/rest-api/emoji-custom/list/
> [BREAK] Remove REST endpoint `/api/v1/emoji-custom`

- .circleci/config.yml
- server/startup/serverRunning.js
Also add env var flags to bypass validations:
- `BYPASS_OPLOG_VALIDATION`
- `BYPASS_NODEJS_VALIDATION`
- `BYPASS_MONGO_VALIDATION`
Where do you guys think we can add those to our docs?
> [BREAK] Remove support to MongoDB 3.2 and deprecate MongoDB 3.4

- app/apps/client/admin/helpers.js
- app/apps/server/communication/rest.js
- app/apps/server/cron.js
With this PR, apps will be automatically enabled after install, and a different text will be shown if the app is in the `INVALID_SETTINGS_DISABLED` state.
> NEW: Apps enable after install

- app/channel-settings-mail-messages/client/views/mailMessagesInstructions.js
- app/e2e/client/accountEncryption.js
- app/e2e/client/rocketchat.e2e.js
- app/emoji/client/lib/EmojiPicker.js
- app/oauth2-server-config/client/oauth/oauth2-client.js
- app/setup-wizard/client/final.js
- app/setup-wizard/client/setupWizard.js
- app/ui-account/client/accountPreferences.js
- app/ui-login/client/login/footer.js
- app/ui-master/server/inject.js
- app/ui-utils/client/config.js
- app/ui-utils/client/lib/menu.js
- app/ui-utils/lib/Message.js
- app/ui/client/lib/chatMessages.js
- app/utils/client/lib/RestApiClient.js
- app/utils/lib/tapi18n.js
- client/startup/i18n.js
> [FIX] Forget user session on window close

- app/file-upload/ufs/Webdav/server.js
- app/webdav/client/addWebdavAccount.js
- app/webdav/server/lib/webdavClientAdapter.js
- app/webdav/server/methods/addWebdavAccount.js
- app/webdav/server/methods/getFileFromWebdav.js
- app/webdav/server/methods/getWebdavFileList.js
- app/webdav/server/methods/uploadFileToWebdav.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/14900
For some reasons the `status` property is inside the `error.response` https://github.com/perry-mitchell/webdav-client/blob/master/source/interface/stat.js#L8 :man_shrugging: 
Related to https://github.com/RocketChat/Rocket.Chat/issues/14243#issuecomment-489458014
Also for some reasons all exceptions coming from the `webdav` npm package, seems return axios response inside the error object instead the original error itself. Due to that an error is caused by Meteor when trying to parse the response content with the EJSON. EJSON is trying to parse the axios response that is a circular JSON. Maybe related to it: https://github.com/perry-mitchell/webdav-client/issues/159
Maybe related to …
> [FIX] Webdav crash

- packages/rocketchat-mongo-config/server/index.js
Closes #15017
Since we always suggest to run Rocket.Chat behind a proxy this PR enforce the environment variable `HTTP_FORWARDED_COUNT` to have value `1` if not set preventing false limits due to use the proxy IP instead of the client IP.
More information [here](https://github.com/RocketChat/Rocket.Chat/issues/15002#issuecomment-513468261)
> [NEW] Assume that Rocket.Chat runs behind one proxy by default (HTTP_FORWARDED_COUNT=1)

- app/assets/server/assets.js
Assets requested with a query string were receiving a `403` response due to wrong detection of asset extension.
> Regression: Fix assets extension detection

- app/api/server/v1/misc.js
Reverts RocketChat/Rocket.Chat#15197
Will keep this endpoint as deprecated until the next major release.
> Revert "[BREAK] Remove REST endpoint `/api/v1/info`"

- packages/rocketchat-i18n/i18n/en.i18n.json
> Improve text of the search bar description

- server/startup/initialData.js
closes #4806
Remove console log that spits out ADMIN_PASS
> Remove log ADMIN_PASS environment variable

- app/integrations/server/lib/triggerHandler.js
When notifying foreign systems about a message, it can be desirable that the remote system responds back. In order to do that, it needs to know from which system the orginal message was issued.
In order to do that, the site-url shall be propagated to the webhook implementation which can then pass it on.
Of course, there are other options (such as setting the referrer in the HTTP-request), but sometimes it's handy to explicitly be able to handle it.
> [NEW] Provide site-url to outgoing integrations

- packages/rocketchat-i18n/i18n/en.i18n.json
> Fix typo in LDAP User Search setting description

- app/models/server/models/ReadReceipts.js
- app/models/server/models/Subscriptions.js
Adds two missing indices on Subscriptions collection used by read receipts queries:
```
{ rid: 1 }
{ rid: 1, ls: 1 }
```
And another on on ReadReceipts collection used to see who read a message:
```
{ messageId: 1 }
```
> [IMPROVE] Add missing indices used by read receipts

- app/metrics/server/lib/metrics.js
On Meteor 1.8.1 the variable `Meteor.server.sessions`  used to get DDP metrics has changed to a `Map`, so a tweaking was needed to get it working again.
> Regression: Fix DDP metrics

- app/discussion/client/tabBar.js
"Discussions" item in "More" menu not hidden, when Discussions are disabled by Administrator
Closes #14684
> [FIX] "Discussions" item in "More" menu not hidden, when Discussions are disabled (#14684)

- app/ui-message/client/message.html
> [FIX] The icon for 'Message sent by email' does not work

- app/autotranslate/server/deeplTranslate.js
The API Version for the DeepL translation has been changed. And it is recommended to use the api version 2.
As per the [DeepL documentation](https://www.deepl.com/de/docs-api.html?part=accessing)
> Please note that:
> 
> Version 1 (v1) of the DeepL API is not supported by the DeepL API plan available from October 2018. Please use version 2 for all new products other than CAT tool integrations.
> Version 2 (v2) of the DeepL API is not compatible with CAT tools and is not included in DeepL plans for CAT tool users. If you intend to integrate DeepL Pro into a CAT tool or another tool assisting translation, please contact support@DeepL.com
> Use version 2 of the DeepL API

- app/livechat/imports/server/rest/departments.js
- app/livechat/server/lib/Livechat.js
- app/models/server/models/LivechatDepartment.js
CLOSES #15337
Currently, the `agents` field is required to update Livechat departments, but there are some use cases where it's difficult to force providing the `agents` field, such as the REST API approach.
So, to support any use case, the `agents` field is no longer mandatory, we'll only deal with the `agents` field when the function parameter is a valid array, otherwise we'll just skip the updating process of Livechat `agents`.
> [IMPROVE] Make the agents field optional when updating Livechat departments

- app/api/server/api.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/15138
> [FIX] REST API to return only public custom fields

- app/meteor-accounts-saml/server/saml_server.js
When authenticated using SAML, users get a username but not a (full) name. That has a couple of nasty side effects since `name` is expected to be available for authenticated users.
This PR adds a determination to the user registration via SAML.
The username is split by non-word-characters (e. g. the very common `.`) and each resulting word is capitalized.
We've been running this for a long time on our branch and did only experience positive effects ;)
Fixes #15236
> [NEW] Guess a user's name from SAML credentials

- app/ui-message/client/messageBox/messageBox.js
- app/ui/client/lib/chatMessages.js
It adds a binary semaphore to the send event, avoiding trigger the message deletion modal when editing a message.
> [FIX] Double send bug on message box

- app/integrations/client/views/integrationsOutgoing.html
- app/ui-admin/client/admin.html
- app/ui-admin/client/users/adminUsers.html
- app/ui-flextab/client/tabs/uploadedFilesList.js
- client/templateHelpers/escapeCssUrl.js
- client/templateHelpers/index.js
- client/templateHelpers/not.js
- package-lock.json
- `not` could be replaced with `$not` from `raix:handlebar-helpers`
- `escapeCssUrl` was used only in one template
> [IMPROVE] Remove global Blaze helpers

- app/theme/client/imports/components/header.css
- app/theme/client/imports/components/tooltip.css
- app/ui/client/components/header/header.js
- app/ui/client/components/header/headerRoom.html
- app/ui/client/components/header/headerRoom.js
- app/ui/client/index.js
- Add missing tooltip
- Change colors for hover and checked state
> Regression: Favorite room button

- app/autolinker/client/client.js
> [FIX] Emoji are rendered in URL

- app/api/server/v1/autotranslate.js
- tests/end-to-end/api/00-autotranslate.js
Fix typo in autotranslate method
> [FIX] Typo in autotranslate method

- server/methods/readMessages.js
- tests/end-to-end/api/10-subscriptions.js
> [FIX] Read Recepts was not working

- app/ui-flextab/client/tabs/userActions.js
> [FIX] adjustments for tooltips to show room name instead of id

- app/models/server/models/Subscriptions.js
- imports/message-read-receipt/server/lib/ReadReceipt.js
May be related to https://github.com/RocketChat/Rocket.Chat/issues/15484#issuecomment-545425902
The Read Receipts logic was getting the oldest `ls` (last seen, field where we store the time the user read the subscription last time) for the channel, so if some user, like a bot, was in the channel without that property set yet, the result could be `undefined`. If that user never enter in the channel to receive his first `ls` the read receipts would stop working (the case for the bots)
> [FIX] Read Receipts were not working properly with subscriptions without ls

- app/integrations/client/views/integrationsIncoming.html
The global `not` helper was deprecated in favor of `$not`.
> Regression: Remove reference to obsolete template helper

- app/lib/server/startup/settings.js
- app/ui-account/client/accountPreferences.html
- app/ui-account/client/accountPreferences.js
- packages/rocketchat-i18n/i18n/en.i18n.json
The labels were of two different nature, for hiding avatars and to hide avatars in room view.
Closes #15585
- Changed the name of the labels to `Hide Avatars` and `Hide Avatars Sidebar`
> [FIX] Duplicate label 'Hide Avatars' in accounts

- app/livechat/server/hooks/sendToCRM.js
- app/utils/server/functions/normalizeMessageFileUpload.js
Closes #15557 
An exception was raised because of an attribute access on an undefined property who does not exists when coming from livechat message.
See how to simulate below:
> [FIX] fix bug on livechat message webhook when sending a image

- app/livechat/client/views/app/livechatAgents.js
- app/livechat/client/views/app/livechatDepartments.js
- app/livechat/imports/server/rest/departments.js
- app/livechat/imports/server/rest/users.js
- app/livechat/server/api/lib/departments.js
- app/livechat/server/api/lib/users.js
- app/models/server/raw/Users.js
After replacing `publications` with the` REST` approach, the filters were being applied only on the client-side, so the results reflected only on data that had been fetched from the server without any filters, based on pagination only.
Now, the filters will be sent to the server through the `REST` endpoint.
> [FIX]  Apply server side filters on Livechat lists

- app/theme/client/imports/components/table.css
Closes #15354 
This PR fixes the line-height on the Directory view, fixing the letter issue mentioned in #15354, as the screenshot shows
> [FIX] line-height to show entire letters

- client/components/admin/info/InstancesSection.js
The `boolean` data was missing after moving to React components.
> Regression: fix admin instances info page

- server/startup/migrations/v161.js
This was causing both settings to not being displayed on admin panel after an upgrade to version `2.1.1` or `2.2.0`.
This change will prevent it from happen if upgrading straight from 2.0.0 to 2.3.0
> Fix notification migration

- app/push-notifications/client/views/pushNotificationsFlexTab.js
Closes #14946
Closes #15747
Closes #13931
> [FIX] Channel notification audio preferences

- app/meteor-accounts-saml/client/saml_client.js
- app/meteor-accounts-saml/server/saml_server.js
> [NEW] SAML login without popup windows

- app/push-notifications/server/lib/PushNotification.js
Currently Rocket.Chat is sending notifications using FCM by the default priority of data messages [1]. Those messages have no service-level objective. This PR changes the priority to '10' which should be the default for instant messaging (as defined in the FCM documentation). The same priority of '10' is also recommended for apple [2]. However for some reason the "push" lib already defaults to '10' for apple [3]. This change relies on [4] to be functional. Yet, it shouldn't brick anything without it.
[1] https://firebase.google.com/docs/cloud-messaging/http-server-ref
[2] https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
[3] https://github.com/RocketChat/push/blob/master/lib/server/push.api.js#L185
[4] …
> [FIX] Push: fix notification priority for google (FCM)

- app/lib/server/startup/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- server/lib/cordova.js
Let the admin configure the batch size and interval of the push notification queue. Hardcoding these values assume these numbers are fine for all setups - i don't think that's a valid assumption.
Related #15791
> [IMPROVE] Make push notification batchsize and interval configurable

- app/ui-flextab/client/tabs/userEdit.html
- app/ui-flextab/client/tabs/userEdit.js
> Improvements to random password field on user edit/creation

- app/livechat/client/route.js
- app/livechat/client/stylesheets/livechat.less
- app/livechat/client/views/app/livechatCurrentChats.html
- app/livechat/client/views/app/livechatDepartmentForm.html
- app/livechat/client/views/app/livechatDepartmentForm.js
- app/livechat/client/views/app/livechatRoomTagSelector.html
- app/livechat/client/views/app/livechatRoomTagSelector.js
- app/livechat/client/views/regular.js
We're facing an issue related to Templates duplicated when running the `Enterprise` edition.
To fix it, I changed the way we're dealing with the `livechatRoomTagSelector` and `livechatDepartmentForm`. Now, instead of replacing the entire file, I'm using the same approach we've on other custom Templates, where we add custom templates inside the original one(yield approach), so the replacement of the entire files is no longer necessary.
> Fix Livechat duplicated templates error

- app/livechat/server/lib/QueueManager.js
The related methods were waiting for an `id` value, not a query object.
> [FIX] Replace findOne with findOneById methods (Omnichannel)

- app/ui-flextab/client/tabs/userEdit.html
- app/ui-flextab/client/tabs/userEdit.js
**Why**
when I add a new user, I constantly forget to click 'Add Role' button.
**Solution**
Now the role will be added when the value is selected
> [IMPROVE] Update ui for Roles field

- app/livechat/server/config.js
- server/startup/migrations/index.js
- server/startup/migrations/v170.js
The default value of the `Livechat_webhookUrl` setting was defined as `false`, but it's a `string` setting, so the webhook was being fired unnecessarily.
> [FIX] Default value of the Livechat WebhookUrl setting

- app/lib/server/functions/sendMessage.js
When using IPreMessageSentPrevent in the apps-engine, the message would be followed by an "Error".
This seems to fix the problem and the output no longer triggers an error.
> [FIX] Don't throw an error when a message is prevented from apps engine

- app/livechat/server/api/v1/agent.js
- app/livechat/server/methods/getNextAgent.js
CLOSES #15842 
The `Livechat.getNextAgent` method returns a promise, but there was a promise handler missing when calling this method inside the `livechat/agent.next` endpoint, then the expected value wasn't being returned.
> [FIX] Livechat triggers not firing

- app/ui-sidenav/client/sidebarHeader.js
Integration permissions were renamed in https://github.com/RocketChat/Rocket.Chat/pull/13902/ and forgotten elsewhere
Docs are outdated too: https://rocket.chat/docs/administrator-guides/permissions/
> [FIX] Admin menu not showing after renamed integration permissions

- packages/rocketchat-livechat/plugin/build.sh
Closes #15889
Fixes `packages/rocketchat-livechat/plugin/build.sh: node: not found` when building bundle.
> [FIX] Livechat build without NodeJS installed

- app/livechat/server/lib/Helper.js
- app/livechat/server/lib/Livechat.js
CLOSES #15923 
Since the Guest's name field is not mandatory, the check validation needs to be optional on this field to allow transferring livechat rooms from the REST API endpoint.
> [FIX] Guest's name field missing when forwarding livechat rooms

- app/ui-account/client/accountFlex.html
- app/ui-account/client/accountFlex.js
> [FIX] Empty security section when 2fa is disabled

- app/katex/client/index.js
Wrong renderMessage priority was using katex before code block, causing some char combination to be replaced with tokens.
Additionally, it was discovered that Katex wasn't being turned off via the interface. Fixed.
Closes #15160
Closes #8640
Closes #11006
Closes #13538
Maybe related #12336
> [FIX] Changed renderMessage priority, fixed Katex on/off setting

- app/theme/client/imports/general/base_old.css
Closes #14615
Fixing z-index of the new message button by overriding the side menu thread.
> [FIX] z-index of new message button

- app/meteor-accounts-saml/server/saml_server.js
- app/models/server/models/Users.js
If SAML is turned on but an user logs out without logging in with SAML before, Rocket.Chat will throw the following error:
```
I20191212-12:50:08.442(-3)? Exception while invoking method 'samlLogout' TypeError: Cannot read property 'services' of undefined
I20191212-12:50:08.443(-3)?     at MethodInvocation.samlLogout (app/meteor-accounts-saml/server/saml_server.js:64:25)
I20191212-12:50:08.443(-3)?     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)
I20191212-12:50:08.444(-3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20191212-12:50:08.445(-3)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20191212-12:50:08.503(-3)?     at …
```
> [FIX] SAML logout error

- app/lib/client/lib/formatDate.js
Closes #15857 
The sidebar time fomat was static and thus not dependent on the time format set by the user . Made changes so that it depends on user time format
For Format HH:mm:ss
For HH:mm
etc
> [FIX]Add time format for latest message on the sidebar

- app/theme/client/imports/general/base_old.css
- app/ui-message/client/messageThread.html
Closes #15448
When "Hide Avatars" is set in the user's preference, the thread icon will be placed on the right of the text so that everything aligns correctly.
> [FIX] Thread message icon overlapping text

- app/lib/server/startup/settings.js
- app/ui/client/views/app/room.html
- app/ui/client/views/app/room.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Closes #12287
Added a new setting in Administration > Layout > User Interface, named "Show top navbar in embedded layout". When false, embedded layout works as is. When true, the top navbar will be shown while on embedded layout.
> [NEW]  Setting Top navbar in embedded mode 

- app/ui/client/lib/iframeCommands.js
Closes #12324
When using the 'go' command, with the embedded style (iframe), whenever a new query parameter was added, the flow router would concat it with the previous, transforming the url into something similar to: http://localhost:3000/channel/general?layout=embedded?layout=embedded.
Now every time the command is called, if a new param is added, it will override the previous onde.
> [FIX] Embedded style when using 'go' command

- app/ui/client/views/404/roomNotFound.html
- app/ui/client/views/404/roomNotFound.js
Closes #8113
Changed the room header message when a User doesn't exist. Channel and Group messages persisted.
> [FIX] "User not found" for direct messages

- app/ui-vrecord/client/VRecDialog.js
- app/ui-vrecord/client/vrecord.js
Closes #14872
When recording a video, if trying to record a new one on another room (direct, channel, group), sending the video would upload it to the first channel the video recorder rendered.
Changed data to reactive vars and moved some code to a more appropriate place.
> [FIX] Video message sent to wrong room

- app/theme/client/imports/general/base_old.css
- app/threads/client/flextab/thread.html
- app/threads/client/flextab/thread.js
- app/ui/client/views/app/room.html
- app/ui/client/views/app/room.js
Closes #7816
Drag and Drop now is disabled when the File Upload is disabled.
> [FIX] Drag and drop disabled when file upload is disabled

- app/oembed/server/server.js
Closes #9849
Now whenever there is no port defined in the URL, HTTP will be treated as 80, 8080, and HTTPS as 443, thus making it possible to block embedding of these ports through the "Safe Ports" setting in the admin menu.
> [FIX] SafePorts: Ports 80, 8080 & 443 linked to respective protocols (#16108)

- client/components/admin/settings/GroupPage.js
Resolving console errors Administration -> Message related to Skeleton (Received `true` for a non-boolean attribute `animated`) and  validateDOMNesting (h1 cannot appear as a child of h1).
> [FIX] Resolving console errors Administration

- packages/rocketchat-i18n/i18n/en.i18n.json
Cloud_Info was being displayed instead of Cloud Info
Before:
After:
> Add Cloud Info to translation dictionary

- app/message-attachments/client/stylesheets/messageAttachments.css
Closes #16034 
Pushed the overflowing content to the next line, content is still responsive
> [FIX] Break message-attachment text to the next line

- app/theme/client/imports/components/modal.css
- app/ui-utils/client/lib/modal.html
Closes #15588 
The cancel button  looks more pronounced and visible
> [IMPROVE] Set the color of the cancel button on modals to #bdbebf for enhanced  visibiity

- app/ui-account/client/accountProfile.js
Closes #16057 
User can click "Save Profile and thus can update password"
The "Save Profile" button is disabled if password is not equal to confirm-password
> [FIX] Save password without confirmation

- .snapcraft/resources/prepareRocketChat
- .snapcraft/resources/preparecaddy
- .snapcraft/resources/preparemongo
- .snapcraft/resources/preparenode
- .snapcraft/resources/startRocketChat
- .snapcraft/snap/hooks/configure
- .snapcraft/snap/hooks/install
- .snapcraft/snap/hooks/post-refresh
- .snapcraft/snap/hooks/pre-refresh
- .snapcraft/snap/snapcraft.yaml
updates:
mongodb: 3.4 to 3.6
node: 8.11 to 8.15
caddy: 0.11 to 1.0
plus pre-refresh hook to backup rocketchat mongo db
> [NEW] update on mongo, node and caddy on snap

- app/apps/server/bridges/messages.js
- app/lib/server/functions/sendMessage.js
- app/lib/server/methods/sendMessage.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/16187
> Regression: Enable apps change properties of the sender on the message as before

- app/apps/server/bridges/uploads.js
There was a `converter` missing when calling the `FileUpload.getBuffer` from the`Apps-Engine`.
Due to that the `File Buffer` returned was always the same, because of the `_id` of the file was missing in the payload provided by the `Apps-Engine`.
> [FIX] FileUpload.getBuffer was not working through the Apps-Engine

- app/integrations/client/views/integrations.js
- app/integrations/client/views/integrationsOutgoing.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/16185
> [FIX] Integrations list without pagination and outgoing integration creation

- app/lib/server/functions/sendMessage.js
Fix the validation that should be preventing API users to set  `alias` property to other than their names but was preventing the usage of the setting `Set a User Name to Alias in Message` instead.
> Regression: Fix set name to alias validation

- app/invites/client/admin/startup.js
- app/invites/server/functions/findOrCreateInvite.js
- app/invites/server/functions/useInviteToken.js
- app/invites/server/functions/validateInviteToken.js
- app/lib/server/functions/setUsername.js
- app/models/server/models/Invites.js
- app/models/server/models/Users.js
- app/ui-flextab/client/tabs/membersList.js
- app/utils/lib/getURL.js
closes  https://github.com/RocketChat/Rocket.Chat/issues/16242#issuecomment-574163166
> [FIX] Invite links usage by channel owners/moderators

- app/authorization/client/views/permissionsRole.html
- app/theme/client/imports/general/base_old.css
- packages/rocketchat-i18n/i18n/en.i18n.json
Closes #16350
Adding an alert that explains 'if you let the description field blank, the role will not be shown
> [FIX] Role tags missing - Description field explanation

- .docker-mongo/Dockerfile
Current develop CI is breaking because the NodeJS version of the Dockerfile used to builde the preview image was not updated.
> Fix Preview Docker image build

- client/startup/i18n.js
Adding the 'lang' tag to fix accessibility problems
> [FIX] Adding 'lang' tag

- app/apps/server/communication/rest.js
- app/models/server/models/apps-logs-model.js
Add bypass for the trash collection when removing logs as well.
> Regression: App deletion wasn’t returning the correct information

- app/livechat/client/views/app/tabbar/visitorInfo.html
- app/livechat/client/views/app/tabbar/visitorInfo.js
- app/livechat/server/lib/Livechat.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
- Display the Omnichannel room closing data on the `Visitor Info` panel
- Send a system message to display who closed the room when the author is the **visitor**(or external systems). This process wasn't working because the `sendMessage` method was expecting a valid **user** and the **visitor** wasn't being considered.
- Also, now the `subscription` will be removed after the room is closed. The `Agent` doesn't need the `subscription` anymore.
> [IMPROVE] Show more information related to the Omnichannel room closing data

- app/livechat/client/views/sideNav/livechat.js
- app/ui-sidenav/client/sidebarItem.js
This PR allows defining the order of the Omnichannel Chat list according to the user preferences as displayed below:
> [NEW] Sort the Omnichannel Chat list according to the user preferences

- .github/workflows/build_and_test.yml
Need to revert this change because PRs from forks cannot use our secrets to store on our S3.
> Use GitHub Actions to store builds

- app/apps/server/bridges/activation.js
- app/models/server/models/Users.js
- imports/users-presence/server/activeUsers.js
This PR tries to make the app user's status sync with its app's status ( '*_enabled' -> 'online'; other status -> 'offline').
> [IMPROVE] Changes App user's status when the app was enabled/disabled

- app/logger/server/streamer.js
The new `stdout` streamer was in infinite loop when log level was 2 and running in multiple instances.
> [FIX] `stdout` streamer infinite loop

- app/apps/server/bridges/activation.js
The method that communicated apps' statuses changes was trying to change the app's user status even if that user didn't exist.
This PR fixes that behavior
> Regression: Fix app user status change for non-existing user

- app/ui-message/client/messageBox/messageBox.js
- app/ui/client/lib/chatMessages.js
> [FIX] Send message with pending messages

- app/ui-flextab/client/tabs/userInfo.js
The endpoint was being called when opening Members List without any arguments thus giving an error.
Related to https://github.com/RocketChat/Rocket.Chat/pull/16495
> Remove users.info being called without need

- app/models/server/models/Users.js
- app/statistics/server/lib/statistics.js
- client/components/admin/info/UsageSection.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
This PR makes the active user count of the statistics stop taking app and federated users into consideration
**Before**
**After**
**Criteria for active users**
Things to consider:
- Do we want the count of app + federated users to go to the **Deactivated users** count?
- Should we add **App users** and **Federated users** counts?
> Exclude federated and app users from active user count

- app/apps/server/bridges/uiInteraction.js
New field `appInfo` on interaction payload with app name and icon
```
{
"type": "modal.open",
"triggerId": "yAgYdsCMLbcr5woNY",
"appId": "c33fa1a6-68a7-491e-bf49-9d7b99671c48",
"view": {
"appId": "c33fa1a6-68a7-491e-bf49-9d7b99671c48",
"type": "modal",
"id": "968821df-a7ad-46bb-98c2-2c1a40e0d62a",
"title": {
"type": "plain_text",
"text": "Create a poll"
},
"submit": {
"type": "button",
"text": {
"type": "plain_text",
"text": "Create"
},
"actionId": "e8615d12-49b3-11ea-9ef6-a9e83d103daf"
},
"close": {
"type": "button",
"text": {
"type": "plain_text",
"text": "Dismiss"
},
"actionId": "e8615d13-49b3-11ea-9ef6-a9e83d103daf"
},
"blocks": [
{
"type": "input",
"blockId": "poll",
"element": {
"type": "plain_text_input",
"initialValue": "",
"actionId": "question"
},
"label": {
"type": …
```
> Regression: Send app info along with interaction payload to the UI

- package-lock.json
- package.json
Update the Livechat dependency to `1.3.1` version.
> [FIX] Livechat Widget version 1.3.1

- app/ui-flextab/client/tabs/createInviteLink.js
This only happened if you closed the invite link sidenav and opened it again, or opened it in another room.
> [FIX] When copying invite links, multiple toastr messages

- .github/workflows/build_and_test.yml
When building PR images, the docker authentication fails once an organization (and not an individual user) is creating the PR, see https://github.com/assistify/Rocket.Chat/runs/431633181
The docker login needs to use credentials matching `GITHUB_TOKEN`
https://github.com/assistify/Rocket.Chat/runs/432851281
> Fix github actions accessing the github registry

- app/livechat/client/lib/stream/queueManager.js
- app/livechat/client/views/app/livechatReadOnly.js
- app/livechat/server/lib/Livechat.js
- app/livechat/server/methods/removeAllClosedRooms.js
- app/livechat/server/methods/removeRoom.js
- app/models/server/models/LivechatInquiry.js
We detected some issues related to the Omnichannel Inquiries when removing chats:
- The `streaming` was relying on the `rid` field, but when removing an `inquiry`,  only the `_id` is propagated, so it wasn't working properly.
- Also, the `inquiry` was not being removed in some events when the `room` was removed, so the `inquiry` was becoming available even without the existence of the related `room`.
Some customers have experienced issues related to this case, as shown below:
> [FIX] Omnichannel Inquiry queues when removing chats

- server/startup/migrations/index.js
- server/startup/migrations/v174.js
Currently, the expected permissions are not added to the `app` role on the server startup for workspaces that already had been installed previously to v3.0.
This migration updates the data for all those workspaces
> [FIX] Regression: New 'app' role with no permissions when updating to 3.0.0

- app/livechat/client/views/app/livechatCurrentChats.html
- app/livechat/client/views/app/livechatCurrentChats.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Closes #12703
This implementation stores de filter values in the `localStorage` and will load the last used values as the default filter values.
In addition, a new action was added to allow quick cleaning of the input / filter values.
> [NEW] Save default filters in the Omnichannel Current Chats list

- app/ui-utils/client/lib/readMessages.js
> [FIX] Clear unread red line when the ESC key is pressed 

- app/theme/client/imports/general/base_old.css
When the content from the contextual bar is bigger than its container, an additional scroll bar for the entire room would appear.
> [FIX] Additional scroll when contextual bar is open

- app/ldap/server/ldap.js
- app/ldap/server/sync.js
- app/ldap/server/syncUsers.js
- app/lib/server/functions/setUserActiveStatus.js
- server/methods/setUserActiveStatus.js
> [FIX] LDAP sync admin action was not syncing existent users

- app/ui/client/lib/chatMessages.js
> [FIX] If InternalHubot_Username is undefined then rocket.cat should be default bot

- app/ui-vrecord/client/vrecord.html
- app/ui-vrecord/client/vrecord.js
Closes #16220 
It has been moved to feature request
https://github.com/RocketChat/feature-requests/issues/262
> [IMPROVE] Added timer in video message recorder

- app/message-star/client/actionButton.js
> [FIX] "Jump to message" is rendered twice when message is starred.

- app/user-status/client/admin/userStatusEdit.css
- app/user-status/client/admin/userStatusEdit.html
Closes #16145 
Used default value of margin used in different components to keep UI consistent.
> [FIX] Correctly aligned input element of custom user status component

- app/ui-utils/client/lib/RoomHistoryManager.js
closes  #16413
From what I understand, it try to finds the message in the room if not it fetches it deletes it and fetches it again from the backend and search for specific message.
so what i did i made the deletion part after we fetch it from the backend to make sure not to delete the whole chat.
> [FIX] Delete messages while searching bug

- server/routes/avatar/room.js
> [FIX] TypeError when trying to load avatar of an invalid room.

- app/api/server/v1/cloud.js
- app/cloud/client/admin/cloud.html
- app/ui-utils/client/lib/modal.html
Right now uses connectToCloud which is purely the intent to register not if its already registered
> [FIX] Manual Register use correct state for determining registered

- app/lib/server/startup/settings.js
- app/ui-account/client/accountProfile.js
- server/methods/saveUserProfile.js
Closes #16740
Closes #16747
When Require Name For Signup was set to false, it was impossible to change anything regarding the user Account if the Name field was empty (even though not required).
> [FIX] Cannot edit Profile when Full Name is empty and not required

- app/ui-account/client/accountPreferences.js
- client/startup/i18n.js
Languages including country variations like `pt-BR` were ignoring the country party because the user's preference has been saved in lowercase `pt-br` causing the language to not match the available languages. Now we enforce the uppercase of the country part when loading the language.
> [FIX] Language country has been ignored on translation load

- app/livechat/lib/LivechatRoomType.js
Some resources were renamed from "livechat" to "omnichannel" in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/16752), but the `icone` name had not been renamed in the Livechat RoomType.
Before:
After:
> Regression: Fix omnichannel icon missing on sidebar

- app/livechat/lib/LivechatRoomType.js
- app/ui/client/views/app/room.js
- app/utils/lib/RoomTypeConfig.js
> [FIX]  Flextab information is not working when clicking on visitor or agent username in Omnichannel messages

- app/ui-message/client/popup/messagePopupSlashCommandPreview.js
Closes #16741 
When slash commands presented popup items, it would only be possible to select the first one. Also, scrolling would trigger the send action upon touch end. Moving the touch also triggered the sidebar to try and appear, even though that was not the intended action.
> [FIX] Slash command preview: Wrong item being selected, Horizontal scroll

- app/meteor-accounts-saml/server/saml_rocketchat.js
- app/meteor-accounts-saml/server/saml_utils.js
- packages/rocketchat-i18n/i18n/de.i18n.json
- packages/rocketchat-i18n/i18n/en.i18n.json
Closes https://github.com/RocketChat/Rocket.Chat/issues/16409
The clock of your Identity Provider may drift slightly ahead of your system clock. In that case you'll find something like this in your logfile and user logins are not possible:
```
Error: Unable to validate response url: Error: NotBefore / NotOnOrAfter assertion failed
```
To allow for a small amount of clock drift you can use `Allowed clock drift` within your SAML settings. Its value must be given in a number of milliseconds (ms). The value given is added to the current time at which the response is validated. The default setting is 0 milliseconds, so the new feature doesn't affect existing SAML configurations.
> [NEW] SAML config to allow clock drift

- app/file-upload/server/config/FileSystem.js
…m upload location
Pull #13033 only fixed the issue for GridFS. This commit adds the same
fix for FileSystem location.
> [FIX] Fallback content-type as application/octet-stream for FileSystem uploads

- app/threads/client/messageAction/follow.js
- app/threads/client/messageAction/unfollow.js
close #15765 
In the thread panel, the unfollow option was not there for the first message. Add checks to toggle the notification option (i.e follow/unfollow) for the thread's first message which was previously for the subsequent options in the thread.
> [FIX] Cannot unfollow message from thread's panel

- app/integrations/client/views/integrations.js
- app/models/server/models/Integrations.js
Integrations were being requested out of order, so when requesting new items after getting to the bottom of the list, if an incoming webhook is returned it will not be placed at the end of the list, resulting in weird results.
> [FIX] Integrations page pagination

- app/custom-oauth/server/custom_oauth_server.js
- app/models/server/models/Users.js
This pull request fixes a bug in Custom OAuth flow of Rocket.Chat. Custom OAuth right now depends upon the **services** block of user data to validate and find user from the database. Following is a sample services block, with `alexapnr` as **OAuth servicename**:
```
services: {
password: {
bcrypt: '$2b$10$dWQ7Vjfb8jRaT15/wpqdZOZXLmHOM.rx69GQjos.cUM4Oqyszr.ry',
reset: [ Object ]
},
email: {
verificationTokens: [ Array ]
},
resume: {
loginTokens: [ Array ]
},
alexapnr: {
id: 'Dv8cbqqFYuG6cvmWP',
accessToken: '57fbbe8c1a16d4b2181e12fc52cfd6e634eaede5',
email: 'ravalprajval@gmail.com',
expiresAt: 1583579264954,
name: 'Prajval Raval',
roles: [ Array ],
username: 'prajval.raval'
}
}
```
In the above block you can see, the data is stored as `services.[serviceName].id: userId` but in current …
> [FIX] Custom OAuth Bug

- app/api/server/v1/users.js
- app/models/server/models/Users.js
> [NEW] API `users.deactivateIdle` for mass-disabling of idle users

- app/emoji/client/emojiParser.js
Small correction in a comment.
Noticed while looking for emoji parser regex.
> Fixed Line break incorrectly being called apostrophe in code

- app/ui-utils/client/lib/openRoom.js
Closes #16791
The main issue here is that `const mainNode (line 31)` is null if anonymous read is allowed in the scenario mentioned in the issue.
Therefore solved this by adding `BlazeLayout.render('main'); (line 52)` if anonymous read is allowed.
> [FIX] Public channel cannot be accessed via URL when 'Allow Anonymous Read' is active

- app/message-pin/client/views/pinnedMessages.html
- app/message-star/client/views/starredMessages.html
- app/search/client/provider/result.html
> [FIX] Correct thread messages display in context bar.

- server/methods/browseChannels.js
Admin users can see the email column for users in the directory view, but attempting to sort on the email column breaks the list of users. This is because the method checks to see if a field is a legal field to sort by, and email is not in that list of fields. I have added email to the list of fields, allowing it to sort on email when fetching users.
> [FIX] admin can sort users by email in directory view

- app/ui-utils/client/lib/MessageAction.js
Previously, when trying to quote messages inside threads, the quote would be sent to room instead to the thread.
> [FIX] Message quote button inside threads

- app/apps/server/bridges/livechat.js
There was a `await` statement missing, so the Apps weren't getting the expected return value.
> [FIX] Make the AppLivechatBridge.createMessage works properly as a promise

- app/ldap/server/loginHandler.js
- app/ldap/server/settings.js
With this change, the LDAP Login Fallback isn't necessary anymore to allow system users to login (usual for admin accounts that were created before the LDAP sync). So now the LDAP Fallback is disabled by default meaning that the users' passwords will not be saved in rocket.chat by default anymore.
Closes #6144
> [IMPROVE] Allow login of non LDAP users when LDAP is enabled

- app/models/server/models/LivechatDepartment.js
The use of the `name` field in the LivechatDepartment model is increasing.
Some customers are consuming the Omnichannel REST API to perform several things and this field is being used a lot, so we need to add a new index to this field in order to get better performance when fetching Omnichannel departments.
> Add an index to the name field for omnichannel department

- app/authorization/client/startup.js
- app/ui-sidenav/client/userPresence.js
- app/webdav/client/startup/sync.js
- client/lib/userData.js
Prevent few events happening out of the expected hour.
> [FIX] Race conditions on/before login

- app/livechat/client/collections/LivechatInquiry.js
- app/livechat/client/lib/stream/queueManager.js
- app/livechat/client/views/sideNav/livechat.js
- app/livechat/lib/LivechatRoomType.js
- app/livechat/server/config.js
- server/startup/migrations/index.js
- server/startup/migrations/v178.js
The Omnichannel setting -> `Livechat_enable_inquiry_fetch_by_stream` is no longer necessary since we removed the subscription that was used to fetch the queue data from the client-side.
Now, the Omnichannel queue works through the `stream` approach, only.
> Regression: Remove deprecated Omnichannel setting used to fetch the queue data through subscription 

- app/2fa/server/code/index.ts
When a DDP method that requires 2FA is called from inside an API without 2FA required the code verification wasn't possible to happen since the API didn't set the context as authorized and the method didn't have access to the headers to execute the authorization process.
This change makes it possible by getting the information from the connection headers if not passed to the 2FA process, it's only possible for this type of call since the connection originates from the API and the headers refer to the call.
> Fix: 2FA DDP method not getting code on API call that doesn’t requires 2FA

- app/lib/lib/roomTypes/direct.js
An error was thrown when getting the avatars and listing the chat room items of search results.
> Regression: Broken Search if users without DM subscriptions are listed

- app/livechat/server/lib/stream/queueManager.js
- server/stream/rooms/index.js
The rule of thumb is: events from oplog should be emitted without broadcast.
> [FIX] Emit livechat events to instace only

- app/livechat/client/lib/stream/queueManager.js
- app/livechat/server/lib/stream/queueManager.js
The queue emitter only needs to propagate changes to the client when the agent is not automatically assigned to the chat.
> Regression: Check Omnichannel routing system before emitting queue changes

- app/federation/server/endpoints/dispatch.js
When adding a federated user to channel. The user on the federated server don't know about it.
> [FIX] Federation Event ROOM_ADD_USER not being dispatched

- app/api/server/api.js
Fixes an error when using a `POST` on `/login` with 2FA activated, this needs to return the details of the error to be used by 2FA.
> Regression: Can't login with 2FA over REST API when 2FA via Email is enabled

- app/livechat/server/api/lib/inquiries.js
- app/models/server/raw/LivechatInquiry.js
When an agent takes a new chat, the server was returning `null` to the client, which was bringing a very bad UX to the agent that had to refresh the page to be able to start chatting.
This was happening because the endpoint that was returning the inquiry was filtering only inquiries with the `status = queued`, but when the agent takes the inquiry its status changes to `taken`.
> [FIX] Omnichannel endpoint `inquiries.getOne` returning only queued inquiries

- app/api/server/api.js
- app/lib/server/startup/settings.js
- app/metrics/server/lib/metrics.js
- package-lock.json
- package.json
- packages/rocketchat-i18n/i18n/en.i18n.json
New settings:
- `Reset Interval (ms)` reset metrics if greater than 0
- `Collect NodeJS GC` false by default
- `API: Track User Agent` false by default reducing the number of metrics
New metrics:
- `rocketchat_metrics_size` the calls received from prometheus to pull the data
- `rocketchat_metrics_requests` the size of the metrics reported to prometheus
- `rocketchat_info` to concentrate the version/url/unique id
Removed the default labels that were replicating the version, URL and unique id among all the records.
> Metrics: New metrics, performance and size improvements

- server/publications/room/emitter.js
The `clientAction` value was being passed as a parameter, but the method was expecting the `room id`.
> [FIX] Room event emitter passing an invalid parameter when finding removed subscriptions

- app/emoji/client/emojiPicker.js
closes #16636
Currently, Searching for emojis produces inconsistent results(doesn't able to recognize emojis having alias name). Used the `shortnames` of each emojis to query for the correct emoji.
> [FIX] Search valid for emoji with dual name

- app/ui-admin/client/components/AdministrationRouter.js
- app/ui-admin/client/routes.js
Some distinct routes can render the same component but with different props. This PR enables it.
> Static props for Administration route components

- app/ui/client/views/app/components/Directory/DirectoryTable.js
- app/ui/client/views/app/components/Directory/index.js
closes https://github.com/RocketChat/Rocket.Chat/issues/17242
> [FIX] Directory default tab

- app/livechat/imports/server/rest/sms.js
On the `3.1`([here](https://github.com/RocketChat/Rocket.Chat/pull/16557)) we started supporting the location sharing through the SMS/WhatsApp integration, but some providers other than Twilio may not support the `extra` property through the `parse` method.
Due to that, we need to make this property optional when extracting the location data, otherwise, an error will be raised.
>  [FIX] Omnichannel SMS / WhatsApp integration errors due to missing location data

- app/ldap/server/loginHandler.js
> [FIX] LDAP users lose session on refresh

- app/ui-flextab/client/tabs/userActions.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Minor word change from "Conversation" to "Direct Message". To keep UI consistency with the left side bar.
> [FIX] Change wording to start DM from info panel

- app/ui-cached-collection/client/models/CachedCollection.js
- app/ui-sidenav/client/roomList.js
BUT the room name will appear as `"[object Object]"` 🤷
> [FIX] Prevent user from getting stuck on login, if there is some bad fname

- app/meteor-accounts-saml/server/saml_utils.js
Closes #17319
Closes #14881
When the SAML IdP sends a LogoutRequest to Rocket.Chat, we're looking for a `<saml:NameID>` tag in the request, but some IdPs may send it as `<NameID>`, so I changed the code to accept both.
Since this is a Logout operation there's no harm in accepting either one.
> [FIX] SAML Idp Initiated Logout Error

- packages/rocketchat-i18n/i18n/es.i18n.json
Fix 2FA not showing codes: https://github.com/RocketChat/Rocket.Chat/issues/10455
Closes 10455
> [FIX] 2FA not showing codes for Spanish translation

- app/authorization/server/functions/hasPermission.js
- app/models/client/models/Subscriptions.js
- app/ui-utils/client/lib/MessageAction.js
`mem` version [v6](https://github.com/sindresorhus/mem/releases/tag/v6.0.0) has changed the default cache strategy and now it caches only the first argument by default.
So I have changed `cacheKey` where we use `mem` for functions with more than one argument to use `JSON.stringify`
I have also improved to get only the needed fields on has permission functions.
> Regression: Fix mem usage with more than one argument

- README.md
Follows-up 4cc8092dc / https://github.com/RocketChat/Rocket.Chat/pull/17081.
> Fix moving-to-a-single-codebase link in README

- app/authorization/server/functions/canSendMessage.js
- app/lib/lib/roomTypes/private.js
- app/lib/lib/roomTypes/public.js
Closes #17400
It doesn't make sense to block a user when looking its info from a channel. Blocking users is only intended  to be done on DMs, so preventing both users from sending messages to each other.
> [FIX] Allowing blocking a user on channels

- app/livechat/server/lib/Helper.js
- app/livechat/server/methods/takeInquiry.js
CLOSES #17405.
Since `3.1` version we only allow online agents/users to get Omnichannel Inquiries.
Unfortunately, external systems are now facing an issue because they have bot agents that get the Omnichannel Inquiries through the REST API endpoint -> `livechat/inquiries.take`.
As the current implementation doesn't check the `bot` role, the external user just can't get the inquiry because the `bot` role isn't being checked as we do in another similar process.
> [FIX] Bot Agents not being able to get Omnichannel Inquiries

- app/ldap/server/loginHandler.js
Closes #17363
In `loginHelper.js` the function `addLdapUser` from `sync.js` was called with the wrong argument count. The reference to `ldap` was missing, so `searchAllSync` got called on `undefined`
Function signature in sync.js:
```
export function addLdapUser(ldapUser, username, password, ldap) {...}
```
Call in loginHelper.js:
```
const result = addLdapUser(ldapUser, username, loginRequest.ldapPass);
```
Fix:
```
const result = addLdapUser(ldapUser, username, loginRequest.ldapPass, ldap);
```
That's it.
> [FIX] LDAP Sync error

- app/ldap/server/sync.js
- app/models/server/models/Rooms.js
This PR fixes this problem:
https://forums.rocket.chat/t/ldap-channel-sync-works-for-1st-user-breaks-subsequent/6503
> [FIX] LDAP error when trying to add room with spaces in the name

- app/ldap/server/loginHandler.js
- app/ldap/server/sync.js
- ee/app/ldap-enterprise/server/listener.js
This PR fixes an issue where the LDAP login was always trying to load user roles from LDAP on Rocket.Chat Enterprise, even when this feature is disabled.
It also adds a few additional debug logs to help identify similar issues in the future.
> [FIX] LDAP login error on Enterprise version

- app/theme/client/imports/general/forms.css
- package-lock.json
A broken composition of `var()` and `calc()` is failing the build.
> [FIX] Invalid CSS syntax

- .github/history.json
During Houston upgrade, it did not catch the metadata on some releases.
> Add some missing metadata information

- app/user-data-download/server/cronProcessDownloads.js
```
- Change from `roomId` variable to `roomData` the value to get iterate on `uids` fields
```
1.  Have 2 users and create a DM and send some message between them in your environment;
2.  As admin user, go to "Administration" > "User Data Download" and make sure this option is enabled;
3.  As any of the users, go to "My Account" > "Preferences" and click at "Export My Data" or "Download My Data" located at the bottom of that page;
4.  When the cron runs it will fail with `"TypeError: Cannot read property 'filter' of undefined"` because `roomId` is a string and has no `uids` in it;
> [FIX] Error during data export for DMs

- app/ldap/server/loginHandler.js
Closes #17539
This PR makes two changes:
- Ignore the LDAP Login Fallback setting when LDAP is disabled
- Only block 'password' logins of LDAP users when the fallback is disabled.
The second change is necessary because an LDAP user can have other login services associated with them and there's no reason to block them since they were not generated by the LDAP sync process like the password.
> [FIX] Login Forbidden on servers that had LDAP enabled in the past

- app/lib/server/startup/settings.js
This should reduce confusion.  If push gateway is selected setting the other push settings are pointless.  So this will help reflect that when gateway is selected these settings can't be used.
> [FIX] Push settings enabled when push gateway is selected

- app/ui-account/client/accountPreferences.js
Closes #17509  
This implements the removal of multiple options from the Don't ask me again list. Previously this was not possible but desired as the HTML of this page showed that the "select" field had the "multiple" attribute set to true. 
You can test this by adding an extra option to the don't ask me again select field in the Global section on the Preferences page.
Select multiple options and click remove. Both will be removed.
> [FIX] remove multiple options from dontAskMeAgain

- app/ui-sidenav/client/sideNav.js
closes https://github.com/RocketChat/Rocket.Chat/issues/17650
> [FIX] Not redirecting to `First Channel After Login` on register

- app/message-star/client/actionButton.js
- app/message-star/client/views/starredMessages.html
- app/ui-message/client/message.html
- app/ui-message/client/message.js
- Added star icon to starred messages
- Fixed jump to message condition
- Added `starred` context prop to starred messages display
Closes #16445
Closes #16661
Co-author: @manosriram
Co-author: @antkaz
> [IMPROVE] Starred Messages

- packages/rocketchat-mongo-config/server/index.js
When we updated to Meteor 1.10.x, Mongo npm package has updated to version 3.2 which is then using `retryWrites: true` as default.
This PR forces the option value to stay as it previously default value, which is `false`, as it would probably be a breaking change because `retryWrites` is support only by WiredTiger.
MongoDB docs https://docs.mongodb.com/manual/core/retryable-writes/#enabling-retryable-writes
> Regression: Set retryWrites=false as default Mongo options

- app/models/server/models/Users.js
- server/methods/registerUser.js
This query takes too long for large databases since it evaluates the entire index unnecessarily, we already save the emails forced to lower case.
> Improve: Remove uncessary RegExp query by email

- app/livechat/server/lib/Helper.js
- app/livechat/server/lib/Livechat.js
- app/livechat/server/lib/RoutingManager.js
- package.json
Import changes on the Apps-Engine weren't reflected in other places.
Additional tests would make this automatically identifiable.
> Regression: Fix incorrect imports of the Apps-Engine

- app/livechat/client/views/app/livechatCurrentChats.js
The default filters on the `Omnichannel Current Chats` template weren't working properly because the values were being loaded on the `onCreated` instead of the `onRendered` event, but the components/selectors may not exist until the creating process is completed.
> [FIX] Default filters on Omnichannel Current Chats screen not showing on first load

- app/crowd/server/crowd.js
- app/crowd/server/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/it.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Closes #14659
I made a simple implementation that removes users not found in Crowd from Rocketchat.
Maybe this will help someone to cover other needs
> [NEW] Option to remove users from RocketChat if not found in Crowd

- packages/rocketchat-i18n/i18n/en.i18n.json
> Fix typo "You aren't part of any channel yet"

- app/ui-message/client/popup/messagePopup.js
Initially the action clicking action button of any search result made the list disappear.
Now the the list doesn't go off and user can perform actions using the button.
Fixes #16436 
Then:
Now:
> [FIX] Can't click on room's actions menu of sidebar list when in search mode

- package-lock.json
- package.json
Upgrade the Livechat widget dependency to the latest version(1.5.0)
#17581 will provide some of the new resources expected on the new release.
> Upgrade Livechat Widget version to 1.5.0

- .circleci/update-releases.sh
We are switching up our internal release service and in order to improve the efficiency of it we are now expecting a payload to be sent to the release service so we don't have to make multiple round trip calls. This PR changes the `update-release.sh` script to provide the said payload.
Run the new release service locally (private repository), set the expected variables to values they would be, and then run the changed command.
Environmental variables are set here: https://github.com/RocketChat/Rocket.Chat/blob/0d2723f3196242b1f9e3fb45c868899065e52b70/.github/workflows/build_and_test.yml#L368-L397
> Submit a payload to the release service when a release happens

- .circleci/update-releases.sh
The payload sent to the release service contains an invalid reference to the tag/version and wasn't working when building develop branch.
> Fix invalid develop payload to release service

- package-lock.json
- package.json
> Update Apps-Engine version

- app/apps/client/admin/appManage.js
- app/apps/client/admin/helpers.js
The wrong method was being called and the UI was trying to update a non-existing app.
* Purchase an App (could be a "Free" one). The app will be installed right after that;
* Uninstall that App;
* Try to install it again;
> [FIX] Error when re-installing an App

- app/mailer/server/api.js
I've created a list of 'data keys' that should be escaped during the email sending, so added `room_path` to it that is the key that receives the value of "go to message" button link.
Send a message that notifies someone via email, inspect the email content and you'll see the link has the chars `&` escaped to `&amp`, i.e.: `https://go.rocket.chat/room?rid=GENERAL&amp;mid=7GubnFuWZRigynuJK&amp;host=localhost%3A3000&amp;path=channel%2Fgeneral%3Fmsg%3D7GubnFuWZRigynuJK&amp;secure=no`
> [FIX] Email link "go to message" being incorrectly escaped

- .houston/metadata.js
- .houston/templates/versions.hbs
Adds the Apps-Engine version to the `Engine versions` section of the history generated by Houston
Some things to consider:
* Should we "clean up" the version we pull from the `package.json` so we don't end up with `Apps-Engine: ^1.14.0`?
* This is not directly related to the PR, but I'm wondering whether we should _erase_ the `history.json` file to add the new field to all previous versions (which would be good for us to map Rocket.Chat versions to Apps-Engine versions) or not 🤔
> Add Apps-Engine to Engine Versions on History

- app/version-check/server/functions/checkVersionUpdate.js
- app/version-check/server/functions/getNewUpdates.js
Fix the update checker.
Implement the update check endpoint and wait for it to be hit. Realize it isn't being hit.
No idea how long this has been broken now.
Also, the reason we changed the format of the id for the banner is because if you previously dismissed the `versionUpdate` banner then it wouldn't display again. This will obviously increase the size of the user object in the database, so how do we go about implementing a fix for this?
> Fix the update check not working

- app/federation/server/lib/dns.js
- app/federation/server/lib/http.js
Docs: https://github.com/RocketChat/docs/pull/1742
> [IMPROVE][Federation] Add support for _tcp and protocol DNS entries

- app/importer-slack/server/importer.js
Fixes the import of the settings object in the slack importer. **Prerequisite for #17637**
Fixes import of settings object in slack importer.
> [FIX] Slack importer settings object

- client/admin/rooms/EditRoom.js
Fix logic for room type radio buttons
#17851
Fixed logic for public/private room types on room edit panel
> [FIX] Logic for room type was inverted in edit panel (#17851)

- app/importer/server/classes/ImporterBase.js
When importing a file, the server would send a new socket message to the client after every imported message. Sometimes when importing a large file this could overwhelm the web socket and cause the progress bar to fall behind. This PR changes the server to only send one update every 50ms.
> [FIX] Importers progress sending too much update events to clients

- app/apps/server/converters/rooms.js
Add a new field in the rooms converter.
Without this addition, information is lost between the execution of the `IPreRoomCreateExtend` and `IPreRoomCreateModify` events.
> [FIX] Apps room events losing data

- app/file-upload/server/startup/settings.js
- app/importer/server/classes/ImporterBase.js
- app/ui-message/client/messageBox/messageBoxActions.js
- app/ui-message/client/messageBox/messageBoxAudioMessage.js
- app/utils/lib/fileUploadRestrictions.js
- packages/rocketchat-i18n/i18n/en.i18n.json
> [NEW] Blocked Media Types setting

- app/lib/server/functions/notifications/email.js
- app/lib/server/lib/sendNotificationsOnMessage.js
- app/notification-queue/server/NotificationQueue.ts
This reverts some undesired changes introduced by #17357, so with this changes:
- it will not send emails to connected users
- send notifications to away users right away
Closes https://github.com/RocketChat/Rocket.Chat/issues/17492
- While online, receive a message and wait 2 minutes without looking anything, you will receive an email
- Open mobile app and send it to background (the connection will be set to away), receive a message, a notification will be sent only after 2 minutes
> [IMPROVE] Don't send emails to online users and remove delay when away/idle

- app/lib/server/functions/saveUserIdentity.js
Update messages only if user changed his username
Save a user profile without changing anything and see messages being updated on Websocket.
> [FIX] Undesirable message updates after user saving profile

- app/file-upload/server/startup/settings.js
Change default upload settings to only block SVG files and allow everything else.
> [IMPROVE] Change default upload settings to only block SVG files

- client/admin/settings/inputs/CodeSettingInput.js
The UI freezes when a `CodeSettingInput` is rendered.
An effect has an array as dependency with a default value recomputed on each render. The solution is making that value constant by placing it in module scope.
Open `Administration > Accounts` or `Administration > General`.
> Regression: Infinite loop in CodeSettingInput

- app/oembed/server/providers.js
Use native oembed API for twitter in order to embed Tweets for direct links to Twitter posts
https://github.com/RocketChat/Rocket.Chat/issues/12924
Paste a direct link to any tweet in any chat window in Rocket.Chat v3.3.3 and nothing happens. For example:
https://twitter.com/Pokemon/status/1273682732594475013
Instance without proposed fix:
Instance with the proposed fix:
Native Twitter oembed support for direct links to tweets
Recommendedations for the future:
- Consider making oembed url patterns configurable in the Admin panel
- Determine feasibility of embedding images and video
Also note that I have been unsuccessful in getting a Meteor environment set up on my machine, but I was able to test through manual changes to the bundle within Docker. Would be helpful if someone else could …
> [FIX] Added explicit server oembed provider for Twitter

- app/lib/server/functions/processWebhookMessage.js
At the moment, outgoing integrations can only respond in the form of a message (and not as an answer in a thread). 
With this change, if a `tmid` is received, it will respond as an answer to a thread instead of a message. 
Adds ability to outgoing integration to respond in a thread.
I don't know if tests are needed, and don't really know how to make them.
> [IMPROVE] Allow webhook message to respond in thread

- app/reactions/client/init.js
> [FIX] Cannot react while "Allow reaction" is set to true

- app/api/server/lib/rooms.js
- app/livechat/client/views/app/livechatDepartmentForm.html
- app/livechat/client/views/app/livechatDepartmentForm.js
Closes #17902 #17914
The Autocomplete component used to search channels in the `Livechat Department Form` is not working properly because the search term passed to the endpoint is wrong.
> [FIX] Autocomplete component is not working property when searching channels in the Livechat Departments form

- client/admin/apps/hooks/useAppInfo.js
Some APIs failed to show in the app details page. Add `Promise.all` to make sure all promises could be resolved before return the data.
n/a
1. Create an example app that registered a webhook URL, deploy it to the dev server.
2. Go to admin - apps - apps detail, check if APIs section is missing.
> Regression: App info broken

- app/lib/server/functions/notifications/email.js
E-mail notifications were broken for livechat when using `Manual Selection` routing method because the `sender` is the visitor in this context and it has no email addresses.
- Set livechat routing method to `Manual Selection`
- Start a new livechat
> Regression: Only add reply-to if sender has emails

- server/configuration/accounts_meld.js
When the 'Verify Email for External Accounts' setting is turned off, OAuth users are being asked to change their passwords.
Closes #18000
> [FIX] User is prompted to reset their password when logging with OAuth

- app/lib/server/functions/notifications/email.js
Fix the following error
```
W20200622-19:13:23.208(-3)? (STDERR) (node:52243) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
W20200622-19:22:19.636(-3)? (STDERR) === UnHandledPromiseRejection ===
W20200622-19:22:19.637(-3)? (STDERR) TypeError: Cannot set property 'Reply-To' of undefined
W20200622-19:22:19.637(-3)? (STDERR)     at getEmailData (app/lib/server/functions/notifications/email.js:163:3)
W20200622-19:22:19.638(-3)? (STDERR)     at app/lib/server/lib/sendNotificationsOnMessage.js:162:12
W20200622-19:22:19.638(-3)? (STDERR)     at Array.some (<anonymous>)
W20200622-19:22:19.638(-3)? (STDERR)     at …
```
> Regression: Fix setting reply-to email header

- app/api/server/v1/chat.js
- app/integrations/server/api/api.js
- app/integrations/server/lib/triggerHandler.js
- app/lib/server/functions/processWebhookMessage.js
Deprecate a permission check added to integrations.
- Create an incoming webhook to a channel
- Don't add the user to that channel 
- Test the webhook, it should fail with `error-not-allowed`
> Regression: Deprecate check permission on integrations

- client/admin/settings/inputs/CodeSettingInput.js
Settings with the type `code` are shown as duplicated CodeMirror editors on Administration and App Details pages.
Open `Administration > Accounts` or `Administration > General`.
> Regression: Repair CodeMirror component reactivity

- client/admin/settings/Section.js
- packages/rocketchat-i18n/i18n/en.i18n.json
> Regression: Reset section button

- app/discussion/client/public/stylesheets/discussion.css
- app/models/server/models/Subscriptions.js
- app/theme/client/imports/components/header.css
- app/theme/client/imports/components/sidebar/sidebar-item.css
- app/threads/client/components/ThreadList.js
- app/threads/client/components/ThreadListMessage.js
- app/threads/client/components/hooks/useLocalstorage.js
- app/threads/client/flextab/threadlist.js
- app/threads/client/threads.css
- app/threads/server/functions.js
- app/ui-flextab/client/flexTabBar.html
- app/ui-message/client/message.html
- app/ui-message/client/message.js
- app/ui-sidenav/client/sidebarItem.html
- app/ui-sidenav/client/sidebarItem.js
- app/ui-utils/client/lib/messageContext.js
- app/ui-utils/client/lib/openRoom.js
- server/publications/subscription/index.js
Implement badge colors for threads.
> Regression: Fix threads badge color indicators

- client/views/setupWizard/steps/SettingsBasedStep.js
One of the dependencies of an effect on `SettingsBasedStep` is a callback continuously updated by the own effect, which resets the whole form state. Its PR fixes that by making the callback stable, i.e., not changing at every update.
Closes #18060
> Regression: Infinite render loop on Setup Wizard

- app/ui/client/views/app/room.js
Fixes the issue that happens when one try to reply a broadcast message and it get errors on the console
> Regresion: Issue with reply button on broadcast channels

- app/livechat/server/lib/Livechat.js
After [this change](https://github.com/RocketChat/Rocket.Chat/commit/6c2f4ff703f2815f5fb86e3cd55d857a0fb35985#diff-f20a1194b623fbbd79899c3fd5c3b2b0R52) (release 3.4) one of the callbacks is returning a promise instead of a regular value, so the callback handler needs to handle it properly.
- Setup the Omnichannel webhooks
- Select `Send Request on Chat Close` option
- Start an Omnichannel conversation
- Close the conversation
> [FIX] Omnichannel close room callback returning promise

- app/livechat/server/statistics/LivechatAgentActivityMonitor.js
The livechat agent activity monitor wasn't initialized because the class attribute `_started` had a typo.
On the Rocket.Chat MongoDB database, and with an agent registered that had started and stopped the activity, type: `db.rocketchat_livechat_agent_activity.find({})` to get the data about agents activity.
> [FIX] The livechat agent activity monitor wasn't being initialised because due to an internal error

- app/theme/client/imports/components/messages.css
closes #18069
- [ X ] Bugfix (non-breaking change which fixes an issue)
- [ X ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ X ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ X ] Lint and unit tests pass locally with my changes
- [ X ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ X ] I have added necessary documentation (if applicable)
- [ X ] Any dependent changes have been merged and published in downstream modules
> [FIX] "Add reaction" icon missing when the viewport size is smaller than 500px

- app/message-pin/client/actionButton.js
- app/message-star/client/actionButton.js
- app/ui-utils/client/lib/MessageAction.js
Closes #13130
Also did some small cleanups on the files
> [FIX] Clipboard not working when permalinking a pinned message

- client/admin/apps/AppDetailsPage.js
Make it so that when clicking `Back` returns to the previous loaded page.
Enter marketplace, select app, click `back` button. It redirects to the apps page, instead of marketplace.
> [FIX] App details returns to apps table, instead of previous page.

- client/admin/sidebar/AdminSidebar.js
Closes: #18105
Related: #17801
1. Start server with ROOT_URL http://localhost:3000/rc
2. Navigate to /rc/admin
3. Observe admin closes
3. Observe admin remains open
1. Start server with ROOT_URL http://localhost:3000
2. Navigate to /admin
3. Observer admin remains open
Fixed cannot open admin when server uses ROOT_URL with subpath
> [FIX] Cannot open admin when server uses ROOT_URL with subpath (#18105)

- app/cas/server/cas_server.js
When you use CAS to login, if the same user already exists as a local account, the users are not being merged. There's a setting to determine if CAS usernames should be trusted, so there's no reason not to merge them when the setting is on.
> [FIX] CAS login not merging users with local accounts

- app/ui/client/lib/notification.js
> [FIX] Fix sticky notifications not working

- app/apps/server/communication/uikit.js
The `viewClose` interaction sent by the `ui.interaction` endpoint to the Apps-Engine was incorrect, sending both `view  and `isCleared` properties as `undefined` always.
> [FIX] View close uikit event sending wrong payload

- app/ldap/server/sync.js
Closes #15374
This fixes the mentioned issue by merging the current `customFields` with the changes from LDAP.
> [FIX] Merge user custom fields on LDAP sync

- app/2fa/client/callWithTwoFactorRequired.js
- app/ldap/client/loginHelper.js
If LDAP is enabled and you try to login with a non-LDAP password account that has email 2FA enabled, the window to input the totp code was never shown.
> [FIX] Local Account login error when both LDAP and Email 2FA are enabled

- app/meteor-accounts-saml/server/lib/Utils.ts
- app/meteor-accounts-saml/tests/server.tests.ts
- Join all values into a single string for fields that absolutely need to be a string;
- Change the user map JSON parser to allow specific array elements to be picked instead of the whole array.
When the Idp sends multiple username values, Rocket.Chat is saving all of them as an array.
Closes #14895
> [FIX] SAML login saves invalid username when receiving multiple values

- app/version-check/server/addSettings.js
- app/version-check/server/index.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Way back in v0.62.0 an update check was implemented into Rocket.Chat (https://github.com/RocketChat/Rocket.Chat/commit/b81b3668e077b7b762f0c29265efe56c9373d8ad). The concept behind this update checker was to notify Rocket.Chat server administrators about new releases and security releases. Neither the server side update notification nor the alert server were ever implemented up until the end of May 2020. Up until now, there was no way, inside Rocket.Chat, to disable this update/alert checker. Moving forward, this will require that people select `Register Server` in the setup wizard in order for this update check to be enabled. Disabling it is as simple as going into Rocket.Chat's settings and disabling the registration of the server in the Wizard settings. Thus, this requires that an …
> [FIX] Update check not able to be disabled

- app/push-notifications/server/lib/PushNotification.js
Add a space on the `text` property of the notification just to this be right handled by iOS devices.
It's an under development feature on our mobile clients so only can be tested by users that have our internal beta test on TestFlight using the unstable server.
We're doing something similar [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/functions/notifications/mobile.js#L59) to handle the case where the `roomName` and `message` was hidden by admin on notification privacy settings.
> Regression: Notification with id-only isn't showed by iOS devices

- client/channel/Discussions/ContextualBar/List.js
- client/channel/Threads/ContextualBar/List.js
- client/components/basic/VerticalBar.js
> Regression: Thread Title not being escaped

- client/account/AccountProfileForm.js
- client/account/AccountProfilePage.js
- client/admin/users/UserInfo.js
- client/channel/UserCard/index.js
- client/channel/UserInfo/index.js
- client/components/basic/UserCard.js
- client/components/basic/UserInfo.js
Added hints to indicate why some fields might be disabled.
> Regression: nickname field in user profile.

- app/models/server/models/_BaseDb.js
- app/models/server/raw/BaseRaw.js
I'm proposing the following changes:
* support `null` as options on models (see logs below)
* do not change `options` object as they are passed as reference
* fix cases in Raw Models where it were mixing both `fields` and `projection` options, in this case mongodb driver gives preference to the latter, possibly causing issues by not returning desired fields.
[This particular case](https://github.com/RocketChat/Rocket.Chat/blob/e73b7cb2f34a2358cfcee8c597e7d6485fa9ab3b/app/models/server/raw/Users.js#L22) was forcing `options` to be `null`, causing the following error:
```
I20200722-11:37:06.974(-3)? Exception while invoking method 'login' TypeError: Cannot set property 'fields' of null
I20200722-11:37:06.974(-3)?     at UsersRaw._ensureDefaultFields (app/models/server/raw/BaseRaw.js:8:4) …
```
> Regression: Fix defaultFields for null values

- app/utils/lib/fileUploadRestrictions.js
I When the block list is empty, all file types should be allowed. But if the browser does not recognize the mime of a file type, the file is still rejected.
#16836
> [FIX] File uploads for unknown file types but nothing is blocked

- app/lib/server/functions/notifications/index.js
- app/lib/server/functions/notifications/mobile.js
- app/lib/server/lib/sendNotificationsOnMessage.js
- app/push-notifications/server/lib/PushNotification.js
> Regression: Return original message on push API

- client/admin/cloud/ConnectToCloudSection.js
- packages/rocketchat-i18n/i18n/en.i18n.json
> [FIX] Missing Privacy Terms Cloud Register warning

- ee/app/canned-responses/client/startup/responses.js
> [FIX] Uncaught (in promise) undefined

- app/message-pin/client/views/pinnedMessages.html
- app/search/client/provider/result.js
- app/threads/client/flextab/thread.js
- app/ui-message/client/message.js
- app/ui-message/client/messageThread.js
- app/ui-utils/client/lib/RoomHistoryManager.js
closes https://github.com/RocketChat/Rocket.Chat/issues/18340
closes https://github.com/RocketChat/Rocket.Chat/issues/18337
> [FIX] Thread reply disappearing and threads result on search

- app/push/server/apn.js
- app/push/server/gcm.js
- app/push/server/push.js
This actually fixes two things:
* When sending the same notification to multiple devices, the `notification` object was being modified to create a `payload` property as an `EJSON`, but since this object was a reference, it was being encoded multiple times (for each device sent), so I move the enconding to inside each push notification provider function (APN and GCM) instead of modifying the `notification` object itself
* If there was any error with an APN certificate, an error was thrown while instantiating `apn.Provider` and the server start up was getting stuck, so I added a `try/catch` to prevent that from hapenning.
> [FIX] Multiple push notifications sent via native drivers

- app/livechat/server/lib/Helper.js
- app/livechat/server/lib/Livechat.js
The [REST API method](https://docs.rocket.chat/api/rest-api/methods/livechat/department#update-a-department) used to update omnichannel departments is not working properly when the `agents` field is not set.
In addition: We're checking now if all agents passed through the `agents` field are valid users.
CLOSES #18392
Just try to update a department trhough the [REST API/PUT method](https://docs.rocket.chat/api/rest-api/methods/livechat/department#update-a-department) without the `agents` field. An error will be raised/returned and the department won't be updated.
> [FIX] Error when updating omnichannel department without agents parameter

- app/livechat/server/lib/stream/agentStatus.ts
The Omnichannel session monitor wasn't being initiated due to bad implementation, there was a wrong type cast statement which was causing the issue.
CLOSES #18259
- Go to Omnichannel admin area
- Go to the `Sessions` section
- Set `Close` or `Forward` to `How to Handle Open Sessions When Agent Goes Offline` setting
- Set a valid value to the `How Long to Wait After Agent Goes Offline` setting
- Set the agent's status to `offline`
- Wait for the system to perform the selected action set on the `How to Handle Open Sessions When Agent Goes Offline` after the `How Long to Wait After Agent Goes Offline` is reached
> [FIX] Omnichannel session monitor is not starting

- server/startup/migrations/v194.js
Fixing the bug in migration v194, which prevented me from upgrading.
Not sure, if there was an open issue.
Migrating from v193 to v194 without having a settings entry for id "SAML_Custom_Default_user_data_fieldmap".
not adequate
Fixed migration v194; in cases there is no SAML configuration, the database couldn't be migrated from v193 to v194.
not required
> [FIX] Migration 194

- app/models/server/models/Subscriptions.js
- app/models/server/raw/Subscriptions.js
- app/threads/server/functions.js
- server/lib/markRoomAsRead.ts
- server/methods/readMessages.js
With this change if you have an unread thread in a channel, the channel will not be marked as read, that means it will still be highlighted and appear in the "unread" section of the rooms list.
* with user A send a message to a thread where user B is following
* with user B mark that channel as read - the room should be kept as unread
* with user B open the thread as the message was sent
* the room should be marked as read
> [FIX] Marking room as read with unread threads still

- app/push/server/push.js
Previews logic was retring in **0.1s, 1s, 11s, 2m, 18m, 3h and 31h**, now it’s retrying in **1m, 3m, 7m, 15m and 31m**
> Reduce Push Notifications retry from max 31 hours to max 31 minutes

- client/account/security/AccountSecurityPage.js
Hide the option to enable/disable the 2FA by Email for the user when disabled in the admin area.
Closes #17755
The option to disable/enable the **Two-factor authentication via Email** at `Account > Security > Two Factor Authentication
` was visible even when the setting **Enable Two Factor Authentication via Email** at `Admin > Accounts > Two Factor Authentication` was disabled leading to misbehavior since the functionality was disabled.
> [FIX] 2FA by Email setting showing for the user even when disabled by the admin

- app/livechat/server/api/v1/videoCall.js
- app/livechat/server/methods/startVideoCall.js
- app/videobridge/client/views/videoFlexTab.js
- app/videobridge/server/methods/jitsiGenerateToken.js
- app/videobridge/server/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Closes #17389 
This adds a switcher that allows to choose if Jitsi room name should be plain or using the hash (default to hash, so no BC break)
> [IMPROVE] Jitsi room name hash or plain

- app/apps/server/bridges/api.js
- app/apps/server/communication/uikit.js
Change to use a non-deprecated API. The old one shows the following on server logs:
```
W20200826-19:12:53.182(-3)? (STDERR) Wed, 26 Aug 2020 22:12:53 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at app/app.js:71439:34
```
> Do not use deprecated express API

- app/channel-settings/server/methods/saveRoomSettings.js
> Fix saveRoomSettings method complexity

- client/contexts/ServerContext.ts
- client/hooks/useFileInput.js
- client/hooks/useUpdateAvatar.js
closes https://github.com/RocketChat/Rocket.Chat/issues/18736
> [FIX] File upload (Avatars, Emoji, Sounds)

- app/2fa/server/code/index.ts
- app/lib/server/startup/settings.js
Don't show `Cloud registration is still pending` banner while still at setup wizard by changing the default state to `false`.
Don't ask second factor authentication during setup wizard by not requiring it right after registration.
- Start a new server
- Complete first step of setup wizard
- The alert `Cloud registration is still pending` should not appear
- Complete the second step of setup wizard
- No password as second factor authentication should not be asked if setup wizard is being completed less then 30 minutes after completing first step (or if user filling the setup wizard was registered in past 30 minutes)
> [FIX] Showing alerts during setup wizard

- packages/rocketchat-i18n/i18n/fr.i18n.json
Add missing variable (`__online__`) in translation strings for French. This is linked to #18762.
> [FIX] French: Add missing __online__ var

- client/components/CustomFieldsForm.js
> [FIX] Show custom fields of invalid type

- app/ui-login/client/username/username.js
- app/ui-message/client/message.js
- app/ui-utils/client/lib/RoomManager.js
- app/ui-utils/client/lib/messageContext.js
closes #18652
closes https://github.com/RocketChat/Rocket.Chat/issues/18204
closes https://github.com/RocketChat/Rocket.Chat/issues/16756
> [FIX] Open room after guest registration

- client/channel/hooks/useUserInfoActions.js
> [FIX] Block user action

- client/admin/users/UsersTable.js
* Refactored Table for better readability.
* Added translation for statuses.
* When deactivated, user status now shows "Disabled".
Closes #18660
> [FIX] Deactivated users show as offline

- app/channel-settings/server/methods/saveRoomSettings.js
- app/e2e/client/tabbar.js
- app/ui/client/components/header/headerRoom.js
- client/components/basic/avatar/UserAvatar.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/17014
[FIX] Users not being able to activate/deactivate E2E in DMs
> [FIX] Users not being able to activate/deactivate E2E in DMs

- app/lib/server/startup/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt-BR.i18n.json
Adds "Allow_Save_Media_to_Gallery" setting under mobile section, so the mobile client can check it and allow saving medias accordingly.
- Added a new setting to allow/disallow saving media to device's gallery on mobile client
Mobile PR: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2459
> [IMPROVE] Add "Allow_Save_Media_to_Gallery" setting

- app/models/server/models/_oplogHandle.ts
Closes https://github.com/RocketChat/Rocket.Chat/issues/18987
> Regression: Handle MongoDB authentication issues

- app/federation/server/endpoints/dispatch.js
- app/federation/server/handler/index.js
- app/federation/server/lib/callbacks.js
Fixes:
- Federation was not working at all on newer versions, callbacks were not being correctly registered due to the new file import order throughout the system;
- Some issues were introduced by this line [Dispatch Event L71](https://github.com/RocketChat/Rocket.Chat/blob/1cfd8201112b654a1c53696e5ed6eb6b88b882a9/app/federation/server/handler/index.js#L71)
- Adjusted the rate limiter for federation requests;
> [FIX] Federation issues

- app/models/server/models/_oplogHandle.ts
- mongodb.aug.d.ts
- typings.d.ts
Closes https://github.com/RocketChat/Rocket.Chat/issues/19082
A missing configuration was not limiting the new oplog tailing to pool the database frequently even when no data was available, leading to both node and mongodb process been consuming high CPU even with low usage. This case was happening for installations using `mmapv1` database engine or when no admin access was granted to the database user, both preventing the usage of the new [Change Streams](https://docs.mongodb.com/manual/changeStreams/) implementation and fallbacking to our custom oplog implementation in replacement to the Meteor's one what was able to be disabled and use the native implementation via the environmental variable `USE_NATIVE_OPLOG=true`.
> [FIX] Performance issues when using new Oplog implementation

- ee/client/audit/AuditPage.js
[FIX] Omnichannel auditing required field
Also fixes height bug when errors appear on the fields
> [FIX] Omnichannel auditing required field

- app/push/server/gcm.js
According to https://www.npmjs.com/package/node-gcm#usage and recommendation in https://developer.android.com/training/monitoring-device-state/doze-standby
Continuation of https://github.com/RocketChat/Rocket.Chat/pull/15803#issuecomment-657771803
According to [node-gcm](https://www.npmjs.com/package/node-gcm#usage), it should be like this:
```jsx
var message = new gcm.Message({
collapseKey: 'demo',
priority: 'high',
...
```
Compared to what `gcm.js` does as of v3.6.3:
```jsx
const message = new gcm.Message({
collapseKey: notification.from,
//    delayWhileIdle: true,
//    timeToLive: 4,
//    restricted_package_name: 'dk.gi2.app'
data,
});
```
Fixes https://github.com/RocketChat/Rocket.Chat/pull/15803#issuecomment-657771803
Improves upon …
> [FIX] Push notifications with lower priority for Android devices

- README.md
Because does not exist anymore.
WeDeploy has been [shut down as of April 2019](https://twitter.com/wedeploy/status/1120429392713453569).
> Remove WeDeploy from README

- app/irc/server/irc-bridge/index.js
- app/irc/server/irc-bridge/localHandlers/onCreateRoom.js
- app/irc/server/irc-bridge/localHandlers/onLogin.js
- app/irc/server/irc-bridge/localHandlers/onSaveMessage.js
- app/irc/server/irc-bridge/peerHandlers/disconnected.js
- app/irc/server/irc-bridge/peerHandlers/sentMessage.js
- app/irc/server/methods/resetIrcConnection.js
- app/irc/server/servers/RFC2813/index.js
- app/irc/server/servers/RFC2813/localCommandHandlers.js
- app/ldap/server/sync.js
This PR fixes issues that caused the irc bridge to stop working after an IRC user receives a DM;
It also adds support to multiline messages from rocket.chat to IRC.
It also fixes the message loop error that happened when replying to a DM started by an IRC user.
Closes #18654
Closes #18655
Closes #18157
> [FIX] IRC Bridge not working

- .github/workflows/build_and_test.yml
Build micro services Docker images with correct tags after `deploy` job, that means, in tags or pushes to `develop`.
> Build micro services Docker images with correct tags

- app/livechat/server/roomAccessValidator.internalService.ts
- app/search/server/search.internalService.ts
- app/tokenpass/server/roomAccessValidator.internalService.ts
- ee/app/license/server/license.internalService.ts
- ee/app/settings/server/settings.internalService.ts
- ee/server/broker.ts
- server/sdk/lib/Api.ts
- server/sdk/types/ServiceClass.ts
- server/services/meteor/service.ts
I'm proposing a way to control if a service should be registered on **network broker** of rocket.chat instances, which can be controlled via two different env vars:
- `INTERNAL_SERVICES_ONLY` (default `false`) - if set to `true` rocket.chat will register only internal services, that are services that only rocket.chat instances have the information to respond or emit events, i.e.: `meteor-service`
- `SERVICES_ALLOWED` (default `empty`) - a comma separated list of services that when set will control which service will be registered on the rocket.chat instance, it has precedence over the `INTERNAL_SERVICES_ONLY` which means if you set `INTERNAL_SERVICES_ONLY=authorization` it will not even start `meteor-service`
Services are considered "external" by default, which means they're by default …
> Micro Services: Create internal services and allowed services list

- client/sidebar/RoomList.js
Fix the undefined message in view mode extended when the last message has an attachment and no title or description.
> Regression: Attachment without title or description show "sent attachment" in view mode extended 

- app/livechat/imports/server/rest/upload.js
- app/livechat/server/roomAccessValidator.compatibility.js
- app/livechat/server/roomAccessValidator.internalService.ts
- app/tokenpass/server/roomAccessValidator.internalService.ts
- server/modules/notifications/notifications.module.ts
- server/sdk/types/IAuthorization.ts
- server/services/authorization/canAccessRoom.ts
- server/services/authorization/canAccessRoomLivechat.ts
- server/services/authorization/canAccessRoomTokenpass.ts
The new permission validation functions created on the micro services were not properly validating livechat calls that doesn't have an authenticated user, so I had to turn those params as optional and validate them on every "canAccessRoom validator".
This is supposed to fix:
- All livechat actions such as:
- typing
- message receiving
- file upload
- notifications
> Regression: Fix livechat permission validations

- server/modules/listeners/listeners.module.ts
The problem was that the function `EnterpriseSettings.changeSettingValue` returns `undefined` if the setting is not an enterprise setting but the code was always replacing the property `value` with its return, causing the `value` not being sent through setting streamers.
- Open network tab on browser
- Go to Admin and change a setting
- You should receive a `public-settings-changed` or `private-settings-changed` without the `value` property.
> Regression: Fix setting value not being sent over websocket

- ee/server/broker.ts
Prevent issue with memory and CPU when a service is down and `waitForService` method keeps checking if the service is available forever and blocks the call.
> Micro Services: Do not wait forever for a service. Fail after 10s or 10 minutes if whitelisted

- app/cloud/server/functions/connectWorkspace.js
- app/cloud/server/functions/startRegisterWorkspace.js
- app/cloud/server/methods.js
Currently when registering your Rocket.Chat Cloud workspace, you can submit an empty token and it will fail with an ambiguous error. This fixes the error message and makes it more verbose.
Register/Connect your workspace and don't enter a token but click the button; see a non-descriptive message.
> [FIX] Cloud Register Allowing Empty Tokens

- ee/server/broker.ts
Network broker was starting when not really needed. So now it requires the `TRANSPORTER` env var to be set.
> Regression: Prevent network broker from starting when not needed

- app/ldap/server/ldap.js
OpenLDAP uses *entryUUID* as a Unique id for each ldap entry. This attribute is hidden from normal search. Adding attributes: ['*','+'] to searchOptions will allow use them to get unique ids for each ldap entry.
If I set *entryUUID* in **Unique Identifier Field**, LDAP search will use only uid as idAttribute for LDAP users in mongoDB.
Set **Unique Identifier Field** value to *entryUUID*, then run **Execute Synchronization Now** in LDAP Administration page
> [FIX] LDAP Unique Identifier Field can not use operational attributes

- app/2fa/client/TOTPLDAP.js
- app/2fa/client/lib/2fa.js
- app/ldap/client/loginHelper.js
Pior to 3.9, whenever an LDAP login resulted in a totp-required error, Rocket.Chat would assume it was a login fallback and redirect the TOTP request to a password login. Now that LDAP 2FA is implemented this should no longer be done.
> Regression: Fix LDAP 2FA not working when Login Fallback is off

- app/lib/server/functions/notifications/mobile.js
Add fallback message "You have a new message" when "Show Message in Notification" is set to false.
Closes #10364
With the configuration for Push Notification working:
- Toggle the "Show Message in Notification" under `Admin > Push > Privacy`. The content will be shown if set to true and "You have a new message" fallback will show when set to false.
* When Show Message in Notification is set to true:
* When Show Message in Notification is set to false:
> [FIX] Add fallback message when show notification content is disabled

- client/sidebar/RoomList.js
There was an issue where the sidebar status for Omnichannel visitors would not correctly refresh.
> [FIX] Sidebar presence will now correctly update for Omnichannel rooms

- client/views/room/contextualBar/UserInfo/index.js
> Regression: UserInfoWithData endpoint variable

- app/message-attachments/client/renderField.js
- lib/escapeHTML.spec.ts
- lib/escapeHTML.ts
> [FIX] Issue with special message rendering

- client/lib/createSidebarItems.ts
Removing the extra parentheses allows this component to be compiled using Babel.
\-
Test using Babel JS Repl:
1. Open [Babel JS Repl](https://babeljs.io/en/repl)
2. Check "PRESETS: typescript"
3. Paste file source to the input field
It's expected the code to be compiled, but it errors `/repl.tsx: Unexpected token, expected ";" (7:68)`.
\-
\-
\-
> Chore: Remove extra parentheses from return type

- ee/server/broker.ts
Now it is possible to set an enterprise key without the need to restart the services.
> Chore: Add watch.settings to events whitelist

- client/views/admin/users/UsersTable.js
Sorting Issue on USERS page
1.  Go to admin
2.  Click on USERS
3.  Click on STATUS (or any column)
Items are sorted correctly.
*   Version of [Rocket.Chat](http://Rocket.Chat) Server: 3.8.0
*   Operating System: Ubuntu 20.04.1
*   Deployment Method: Manual;
*   Number of Running Instances: 1
*   DB Replicaset Oplog:
*   NodeJS Version: 12.18.4
*   MongoDB Version: 4.0.21
*   Desktop App or Browser Version: Browser (Chrome Edge)
*   Operating System: Windows 10
> [FIX] Admin Users screen sorting showing deactivated users in wrong order

- .docker/Dockerfile.rhel
Update base NodeJS image, and remove OS-level workarounds
Fixes #19035 
Tested successfully using https://quay.io/repository/akrohg/rocketchat
Update base image for Dockerfile.rhel to registry.access.redhat.com/ubi8/nodejs-12
> [FIX] Update base image in Dockerfile.rhel

- client/components/Sidebar.js
> Regression: Admin Sidebar Scroll

- app/threads/client/components/ThreadComponent.tsx
- app/ui/client/views/app/lib/getCommonRoomEvents.js
- client/components/UserCard.js
> Regression: UserCard "See full profile" link broken

- tests/end-to-end/api/00-miscellaneous.js
Adding more tests situations to the `instances.get` endpoint, mostly fails tests, for example: 
- If the user is not logged in, it should fail;
- If the user is logged in but does not have the right permission, it should fail.
> Chore: add tests to api/instances.get endpoint 

- app/authorization/server/startup.js
- app/livechat/client/lib/stream/queueManager.js
- client/providers/OmniChannelProvider.tsx
It was necessary to be a manager to take queue chats from the pending list, so we removed the managers permission from the logic and now the agents also can pick up queue chats.
As an agent:
Try to take a chat from the queue list.
You'll see the chat will be duplicated and the room will be read only.
> [FIX] Omnichannel Agents unable to take new chats in the queue

- tests/end-to-end/api/20-licenses.js
Adding api tests for the new `licenses.*` endpoints (`licenses.get` and `licenses.add`)
> Chore: Add tests for the api/licenses.* endpoints

- app/lib/server/functions/saveUserIdentity.js
Since we store user's `username` on message objects, we need to update them when a user updates his username, but this update was being triggered even if the user was updating other details (like his avatar for example) which was leading to unneeded updates of the messages. This PR fixes it by triggering an update of the message **only** if the username has been changed.
> [FIX] Messages being updated when not required after user changes his profile

- client/views/room/contextualBar/UserInfo/index.js
- client/views/room/hooks/useUserInfoActions.js
Users can be removed from channels without any error message.
https://user-images.githubusercontent.com/55157259/103759202-5b4c0a00-5039-11eb-82c9-a3d37726160a.mp4
Closes #20058 
Closes #20095
> [FIX] Actions from User Info panel

- client/views/account/preferences/AccountPreferencesPage.js
- client/views/account/preferences/PreferencesGlobalSection.js
- client/views/account/preferences/PreferencesHighlightsSection.js
- client/views/account/preferences/PreferencesLocalizationSection.js
- client/views/account/preferences/PreferencesMessagesSection.js
- client/views/account/preferences/PreferencesNotificationsSection.js
- client/views/account/preferences/PreferencesSoundSection.js
- client/views/account/preferences/PreferencesUserPresenceSection.js
#19927 
1. Go to My Account -> Preferences. In Highlights, start editing the "Highlighted words" TextArea.
2. Enter "klt"
3. Save Changes
4. Change to "kl" [ "Save Changes" activates ]
5. Change back to "klt" [ "Save Changes" deactivates]
> [FIX] Initial values update on Account Preferences

- app/ui-message/client/message.html
- app/ui-message/client/message.js
> Regression: reactAttachments cpu

- packages/rocketchat-i18n/i18n/zh-HK.i18n.json
- packages/rocketchat-i18n/i18n/zh.i18n.json
> [FIX] Incorrect translations ZN

- client/views/room/providers/ToolboxProvider.tsx
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- I have added necessary documentation (if applicable)
- Any dependent changes have been merged and published in downstream modules
When we click on a username and then click on see user's full profile, a tab gets active and shows us the user's profile, the problem occurs when the tab is still active and we try to see another user's profile. In this case, tabbar gets closed.
To resolve this, added context check for closing action of active tabbar.
fixes #20227
Refer issue #20227 
We are checking active tabbar action id, in order to close the active tab if any action like clicking button member-list is performed twice. But this creates an issue if we try to see user's info back to back because the …
> [FIX] Added context check for closing active tabbar for member-list

- client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.js
Added success message after saving notification preferences.
https://user-images.githubusercontent.com/55157259/104774617-03ca3e80-579d-11eb-8fa4-990b108dd8d9.mp4
Fixes #20219
> [FIX]Added success message on saving notification preference.

- app/ui-message/client/messageThread.html
- packages/rocketchat-i18n/i18n/en.i18n.json
Remove unnecessary spaces from the translation key, and added English translation value for the key.
Closes #20145 
1. Make a thread in a channel
2. Mouse over blue thread link in channel
3. Look at tooltip
> [FIX] "Open_thread" English tooltip correction

- client/views/room/contextualBar/UserInfo/index.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Fix the `Full Name` translation keyword, so that it can be translated.
None. 
Full Name isn't translated at the moment due to using the wrong translation keyword. 
Check User info sidebar in another language and notice that it's in English.
I also added Full_Name in the English JSON.
> [FIX] User info 'Full Name' translation keyword

- client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js
The "Hide room" and "Leave Room" confirmation prompts use the "name" key from the room info. When the setting "
Allow Special Characters in Room Names" is enabled, the prompts show the normalized names instead of those that contain the special characters.
Changed the value being used from name to fname, which always has the user-set name.
Previous:
Updated:
Closes #20276 
1. Login as administrator
2. Go to Administration
3. Under "Layout", check "Allow Special Characters in Room Names"
4. Change the name of a room to "The Room ;;"
5. Try to leave the aforementioned room [ The prompt calls the room "the-room" instead of "The Room ;;" ]
> [FIX] Room special name in prompts

- client/views/admin/permissions/UsersInRole.js
- client/views/admin/permissions/UsersInRoleTable.js
- ee/client/audit/AuditPage.js
> [FIX] Fields overflowing page

- client/views/admin/users/EditUser.js
Disallows showing a success popup when email field is made blank in Edit User and instead shows the relevant error popup.
https://user-images.githubusercontent.com/28918901/104960749-dbd81680-59fa-11eb-9c7b-2b257936f894.mp4
Closes #20258 
1. Go to Administration -> Users.
2. Click on any User and click on Edit.
3. Clear out the prefilled email.
4. Hit Save.
> [FIX] Saving with blank email in edit user

- app/theme/client/imports/general/base_old.css
- client/components/Message/Attachments/Attachment.tsx
- client/components/Message/Attachments/DefaultAttachment.tsx
- client/components/Message/Attachments/Files/AudioAttachment.tsx
- client/components/Message/Attachments/Files/ImageAttachment.tsx
- client/components/Message/Attachments/Files/VideoAttachment.tsx
- client/components/Message/Attachments/Files/index.tsx
- client/components/Message/Attachments/QuoteAttachment.tsx
- client/components/Message/Attachments/index.tsx
> Regression: Attachments

- tests/end-to-end/api/21-banners.js
Add tests for the new `banners.*` endpoints: `banners.getNew` and `banners.dismiss`.
> Regression: Add tests to new banners REST endpoints

- app/file-upload/server/lib/FileUpload.js
- client/components/Message/Attachments/Attachment.tsx
- client/components/Message/Attachments/Files/AudioAttachment.tsx
- client/components/Message/Attachments/Files/GenericFileAttachment.tsx
- client/components/Message/Attachments/Files/ImageAttachment.tsx
- client/components/Message/Attachments/Files/VideoAttachment.tsx
> Regression: Set image sizes based on rotation

- client/components/UserCard.js
Added Bio Structure for rendering Skeleton View on loading UserCard.
fix #20283 
Check the Issue
Until UserCard received bio, it was passing Skeleton as content to Markdown, so it was returning [Object][Object], which was shown to user. So Made one more entity called as bioStructure, now if bio is present, bio will be passed to markdown and everything would work as it is supposed to, but if bio is not present, bioStructure would be rendered as skeletonView.
> [FIX] Added Bio Structure for UserCard, rendering Skeleton View on loading Instead of [Object][Object] 

- app/models/server/models/Messages.js
When setting 'Message_ShowDeletedStatus' is set to true, deleting a message with `tshow: true` causes a bug on the frontend. This issue should, however, never be logically possible as a 'removed' message should not have tshow anyway. Hence, this PR unsets that when the message is set to "Message Removed".
Closes #20443 
1. Set setting 'Message_ShowDeletedStatus' to true
2. Send a message. [ Message A ]
3. Send a message in the same room after it.
4. Reply to Message A. [ Reply B ]
5. Send another message in the room(not thread).
6. Delete reply B.
7. Empty hoverable box appears where reply B was placed.
> [FIX] Unset tshow on deleted messages

- app/theme/client/imports/general/base_old.css
- packages/rocketchat-i18n/i18n/en.i18n.json
Changed the spelling of *Characther* to *Character*
- Go to Admin Panel
- Then Select Omnichannel from the left sidebar
It has been used from this file when translated to english - [/client/views/omnichannel/appearance/AppearanceForm.tsx#L120](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/omnichannel/appearance/AppearanceForm.tsx#L120)
> [FIX] Typo in Message Character Limit

- app/lib/server/methods/sendInvitationEmail.js
- client/views/admin/users/InviteUsers.js
Resolved structure where no response was being received. Changed from callback to async/await.
Added error in case of empty submission, or if no valid emails were found.
https://user-images.githubusercontent.com/38764067/105613964-dfe5a900-5deb-11eb-80f2-21fc8dee57c0.mp4
Closes #19021 
1. Open administration
2. Invite by email addresses
3. Submit invalid or empty email input [ No error ]
4. No feedback at all on submission
> [FIX] Feedback on bulk invite

- ee/client/audit/UserAutoCompleteMultiple.js
Added debouncing to that search field so after every key stroke API is not called.
BEFORE
https://user-images.githubusercontent.com/55157259/105350722-98a3c080-5c11-11eb-82f3-d9a62a4fa50b.mp4
AFTER
https://user-images.githubusercontent.com/55157259/105350757-a2c5bf00-5c11-11eb-91db-25c0b9e01a28.mp4
Closes #20263
> [FIX] Add debouncing to add users search field.

- client/components/UserStatus.js
- client/hooks/usePresence.ts
- client/hooks/useUserData.ts
- client/lib/presence.ts
- client/views/room/contextualBar/OTR/OTR.js
> [NEW] useUserData Hook

- client/views/blocks/ModalBlock.js
- package-lock.json
> Remove `uiKitText` reference

- server/modules/core-apps/nps.module.ts
- server/modules/core-apps/nps/createModal.ts
- server/services/nps/service.ts
If you change you mind after choosing a score on the banner, you can change it on the modal it opens, and now the question will update accordingly.
> [FIX] Update NPS banner when changing score

- client/views/room/Announcement/Announcement.js
Announcements with multiple lines used to break UI for announcements bar. Fixed it by replacing all break lines in announcement with empty space (" ") . The announcement modal would work as usual and show all break lines.
fixes #20380 
check issue.
> [FIX] Announcements with multiple lines fixed.

- app/ui/client/views/app/room.js
- client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.js
> [FIX] Room Scroll to Bottom

- app/file-upload/server/lib/FileUpload.js
- client/components/Message/Attachments/components/Image.tsx
> [FIX] Gif images aspect ratio on preview

- client/components/Message/Attachments/Files/GenericFileAttachment.tsx
Added target = '_self' to attachment link, this seems to fix the problem, without this attribute, error page is displayed.
fixes #20583 #20559 
given on issue
> [FIX] Attachment download from title fixed

- app/emoji-emojione/lib/generateEmojiIndex.mjs
- package-lock.json
- package.json
This dependency is only used by the [emoji sprite generator](https://github.com/RocketChat/Rocket.Chat/blob/950766f3dae1d277121360b47100ce7b1fb0015b/app/emoji-emojione/lib/generateEmojiIndex.mjs#L7), which is not used that often (maybe it was used only once in a life time) but it adds an annoying error during `meteor npm i` due to a missing peer dependency, so I'm proposing removing it and adding a comment on the script it is used to install dependency manually, I hope this change brings peace to everyone trying out building rocket.chat from source.
> Chore: Remove node-sprite-generator dependency

- app/threads/client/components/ThreadView.tsx
- packages/rocketchat-i18n/i18n/en.i18n.json
Added tooltips to "Expand" and "Follow Message"/"Unfollow Message" in ThreadView for coherency.
Closes #20455 
1. Open any thread
2. Hover over top-right buttons and wait for tooltip.
> [FIX] Add tooltips to Thread header buttons

- app/custom-oauth/client/custom_oauth_client.js
- app/custom-oauth/client/swapSessionStorage.js
Firefox is for some reason losing the sessionStorage during the redirection phase. This PR implements a workaround to this, but this fix should only be temporary.
Closes #20374
A special thanks for @LeSuisse for helping debug this issue and providing the tools necessary to reproduce it.
> [FIX] OAuth Login not working on Firefox

- app/api/server/v1/misc.js
- tests/end-to-end/api/00-miscellaneous.js
1. Login as X user
2. Make a GET request to `/api/v1/me`
3. In the key `services.password` you should see a property `bcrypt` with the hashed password of the current user
- This only affects current user
- User is not able to get info from other users
- Unit test updated to check `passowrd` key is missing.
> Exclude user's own password from /me endpoint

- app/2fa/server/code/ICodeCheck.ts
- app/2fa/server/code/PasswordCheckFallback.ts
- app/2fa/server/code/index.ts
- app/api/server/v1/users.js
- server/methods/saveUserProfile.js
> [FIX] Save user password and email from My Account

- client/views/room/contextualBar/ExportMessages/index.js
https://user-images.githubusercontent.com/64399555/105844776-c157fb80-5fff-11eb-90cc-94e9f69649b6.mp4
This PR closes #20407
> [FIX] Selected messages don't get unselected

- app/lib/server/functions/saveUser.js
When the API users.update is called to update user data, it passes data to saveUser function. Here before saving data like bio or nickname we are checking if they are available or not. If data is available then we are saving it, but we are not doing anything when data isn't available.
So unsetting data if data isn't available to save. Will also fix bio and other fields. :)
fixes #20783
> [FIX] Admin cannot clear user details like bio or nickname

- app/message-star/client/views/starredMessages.js
The getCommonRoomEvents() returned functions were bound to the starredMessages template twice. This was causing some bugs, as detailed in the Issue mentioned below.
I removed the top events call that only bound the getCommonRoomEvents(). Therefore, only one call for the same is left, which is at the end of the file. Having the events bound just once removes the bugs mentioned.
Closes #20184  
https://user-images.githubusercontent.com/38764067/104407257-36025300-5587-11eb-86e4-18605f9083dd.mp4
1. Make sure the channel has at least one starred message
2. Go to the menu for the channel ('...')
3. Click on 'Starred Messages'
4. Hover over any starred message to get the menu ('...') and click on it.
5. Click anywhere. The menu just doesn't go away.
> [FIX] Remove duplicate getCommonRoomEvents() event binding for starredMessages

- client/components/Message/Attachments/Attachment.tsx
- client/components/Message/Attachments/DefaultAttachment.tsx
Removed truncating of text in `Attachment.Text`. 
Added `Attachment.Text` to be parsed to markdown by default.
Closes #20560 
[#20560 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/20560#issuecomment-773190476) shows the bug which can be reproduced by using the `cURL` command if you already have a bot with the correct credentials.
Otherwise you can use this way to reproduce the message, (I have used a bot for that):
1. On the terminal, do `git clone https://github.com/aditya-mitra/rocketchatbot.git  && cd rocketchatbot && git checkout reproducing-issue-md && npm install` (this will clone the repo and install dependencies)
2. Add [this bot with these username and password](https://github.com/aditya-mitra/rocketchatbot/blob/reproducing-issue-md/src/index.ts) to the **list of …
> [FIX] Default Attachments - Show Full Attachment.Text with Markdown

- server/modules/listeners/listeners.module.ts
closes https://github.com/RocketChat/Rocket.Chat/issues/19566
closes https://github.com/RocketChat/Rocket.Chat/issues/19567
closes https://github.com/RocketChat/Rocket.Chat/issues/19433
closes https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/121
closes https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/126
closes https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/127
> [FIX] Message payload from `__my_messages__` stream

- app/lib/server/lib/notifyUsersOnMessage.js
- Unread messages count won't be incremented when the message sent is on a thread (thread count is treated different)
- No open issue. 
- Issue description: when a user answers a direct message by answering in a thread, the `unread` counter next to user's name will mark 2 instead of 1.
- Start a direct conversation with another person
- After the first message from the other one, instead of answering to the main conversation, write your reply in a thread\
- The other person will see a badge of `2` unread messages instead of `1` (since we sent just one message)
> [FIX] Increasing unread counter twice for new threads in DMs or with mentions

- client/views/omnichannel/departments/DepartmentEdit.js
> [FIX] Missing height on departments agents table

- app/cloud/server/functions/buildRegistrationData.js
- app/metrics/server/lib/collectMetrics.js
- app/models/server/models/Statistics.js
- app/models/server/models/Users.js
- app/models/server/raw/Users.js
- app/statistics/server/lib/statistics.js
- server/startup/migrations/index.js
- server/startup/migrations/v218.js
track what languages get picked the most as preferred ui language.
> [NEW] Statistics about language usage

- client/components/Message/Attachments/Attachment.tsx
- client/components/Message/Attachments/Files/AudioAttachment.tsx
- client/components/Message/Attachments/Files/GenericFileAttachment.tsx
- client/components/Message/Attachments/Files/VideoAttachment.tsx
- client/components/Message/Attachments/providers/AttachmentProvider.tsx
closes https://github.com/RocketChat/Rocket.Chat/issues/20674
closes https://github.com/RocketChat/Rocket.Chat/issues/20543
> [FIX] Download buttons on desktop app and CDN being ignored

- app/ui-utils/client/lib/Layout.js
- app/ui-utils/client/lib/messageContext.js
> Regression: Prevent Message Attachment rendering

- app/livechat/lib/LivechatRoomType.js
- app/ui/client/views/app/room.js
> [FIX] Open Visitor Info when omnichannel chat was open

- app/e2e/client/rocketchat.e2e.js
- app/e2e/client/rocketchat.e2e.room.js
related to https://github.com/RocketChat/Rocket.Chat/pull/20704#issuecomment-784129854
> Regression: Messages not being encrypted E2E

- app/videobridge/client/views/bbbLiveView.html
The current flags prevent audio and video to be shared in a session.
> [FIX] Iframe flags for audio and video on the BigBlueButton integration

- client/sidebar/header/actions/CreateRoom.js
- client/sidebar/header/actions/CreateRoomList.js
- client/sidebar/header/actions/CreateRoomListItem.js
Use a better way to handle the popover on channel creation button, previously it was too reliant on the blaze renderer.
_"I cant hug the world." unidentified philosopher, circa early 20s_
> [IMPROVE] Better new channel popover

- app/assets/server/assets.js
- app/custom-sounds/server/methods/uploadCustomSound.js
- app/emoji-custom/server/methods/uploadEmojiCustom.js
- app/importer-hipchat/server/importer.js
- app/importer-slack-users/server/importer.js
- app/importer/server/classes/ImporterBase.js
- app/importer/server/methods/uploadImportFile.js
- app/irc/server/servers/RFC2813/index.js
- app/ldap/server/ldap.js
- app/lib/server/functions/setUserAvatar.js
- app/meteor-accounts-saml/server/lib/ServiceProvider.ts
- app/meteor-accounts-saml/server/lib/Utils.ts
- app/webdav/server/methods/uploadFileToWebdav.ts
- server/routes/avatar/utils.js
- server/startup/migrations/v002.js
- Changes `new Buffer` to `Buffer.from` since the first one is deprecated.
> Chore: Remove `new Buffer` in favor of `Buffer.from`

- app/api/server/v1/teams.ts
- app/models/server/raw/Rooms.js
- app/models/server/raw/Team.ts
- app/models/server/raw/TeamMember.ts
- server/sdk/types/ITeamService.ts
- server/services/team/service.ts
- tests/end-to-end/api/25-teams.js
- Allows users to specify the owner of the team when using the API (useful for bots :) )
- Allows users to retrieve a list of the members of a team (when they are either admin, have permissions or are members of the team)
- Add some e2e tests to the functionality
- Create unique indexes for Team.name and (TeamMember.userId & TeamMember.teamId)
> [NEW] New/teams back owner

- app/api/server/v1/teams.ts
- app/models/server/raw/TeamMember.ts
- server/sdk/types/ITeamService.ts
- server/services/team/service.ts
- tests/end-to-end/api/25-teams.js
Add the following endpoints:
- `teams.addMembers`;
- `teams.updateMember`;
- `teams.removeMembers`;
- `teams.leave`.
Update the `teams.members` endpoint in order to support pagination and `teamName` (when `teamId` is not provided).
[Task - Clickup](https://app.clickup.com/t/3k4fca)
Example calls and results are described in [this document](https://docs.google.com/document/d/1305Ovreq6iyDduNTPb5YWrRiRR7G3YWMesm9Sd6RISM/edit?usp=sharing).
> [NEW] Add Team Members' endpoints

- client/views/admin/info/LicenseCard.js
- ee/app/license/server/license.ts
The administration info panel was showing the *total of users* as the number counted for the usage of the license seats. Now it's showing the correct number that is *active users*. This was not affecting the license validation on the server-side, only causing confusion for the administrators to check how the usage was being counted.
> [FIX] Wrong license seats number administration info panel

- app/api/server/lib/rooms.js
- app/models/server/raw/Rooms.js
> [FIX] rooms.adminRooms endpoint teams filter

- app/apps/server/communication/rest.js
Change **error** message to a **warn** message when uploading a  `.zip` file app into a air-gapped environment.
The **error** message was giving the impression for the user that the app wasn't properly being installed , which it wasn't the case:
A more detailed **warn** message can fix that impression for the user:
Fixes [Task](https://app.clickup.com/t/376x06)
1. Go to` Admin > Logs` and change the log level to at least 1 (**warn** messages are level 1)
2. Cut the internet connection from a Rocket Chat server
2. Upload a `.zip` app file and installed it
3. The message will appear in the console
> [FIX] [APPS] Warn message while installing app in air-gapped environment

- client/sidebar/RoomList.js
Added hide unread counter check, if the show unread messages is turned off, now unread messages badge won't be shown to user.
fixes #20866 
##Before 
Even after turning off unread counter, it showed unread counter on room list.
##After
Now added check before showing unread messages badge. If option to show counter is turned off, unread badge won't be shown.
> [FIX] Added hideUnreadStatus check before showing unread messages on roomList

- app/api/server/lib/users.js
- app/api/server/v1/users.js
The users listed in the admin panel were sorted in a case-sensitive manner , where the capitals came first and then the small letters (like - *A B C a b c*). This Change fixes this by sorting the names in a caseinsensitive manner (now - *A a B b C c*).
Closes #14735 
1. Go to Administration
2. Select the Users Tab
3. Users Names are sorted in case-sensitive manner ( like A B C a b c )
https://user-images.githubusercontent.com/55396651/108191923-b3e2ec80-7139-11eb-9970-690915592e11.mp4
> [IMPROVE] Sort Users List In Case Insensitive Manner

- app/reactions/client/init.js
The $().data function was returning outdated values for re-assigned emoji buttons with new data. Changed that to use the .attr() function. This works perfectly.
Closes #20734 
1. React to a message
2. React to the same message again using a different reaction
3. Click the first reaction. It disappears.
4. Click the only remaining reaction. The first reaction reappears.
> [FIX] Correct Inline reactions behaviour

- client/views/room/Header/Header.js
> regression: Discussion room crashing if not member of parent channel

- app/api/server/v1/teams.ts
- app/models/server/raw/Rooms.js
- server/sdk/types/ITeamService.ts
- server/services/team/service.ts
- Add support for queries (within the `query` parameter);
- Add support to pagination (`offset` and `count`) when an user doesn't have the permission to get all rooms.
[Task - ClickUp](https://app.clickup.com/t/3z2qq8)
**Example input (using cURL):**
```
curl -G 'http://localhost:3000/api/v1/teams.listRooms?teamId=60538ebf22ff2e119e52f086' \
--data-urlencode 'query={"ts":{"$gt":{"$date":"2021-03-26T19:46:38.143Z"}}}' \
-H 'X-Auth-Token: c3rQDH_Fpa7JHSgUrWvlpxwIi1AAu4qTnfAF4SFgWkB' \
-H 'X-User-Id: dizcH9Edm8hC7ziDX' \
-H 'Content-Type: application/json'
```
> Regression: Add support to filter on `teams.listRooms` endpoint

- client/omnichannel/directory/chats/contextualBar/ChatInfo.js
> [FIX] Incorrect time format of the Queue Time field on the room information page

- app/api/server/v1/groups.js
The previous check didn't consider that the endpoint could also be called with a roomName instead of a roomId.
> Regression: invalid permission check.

- app/file-upload/server/config/FileSystem.js
- app/file-upload/server/config/GridFS.js
- app/file-upload/server/lib/ranges.js
Closes #20203
Related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2759
> [IMPROVE] Add support to range downloads on file system storage

- client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
- definition/IMessage.ts
- ee/app/livechat-enterprise/server/api/lib/tags.js
> [FIX]  Close chat button is not available for Omnichannel agents

- app/apps/client/orchestrator.js
- package-lock.json
- package.json
Fixes the marketplace app installation not correctly displaying the permissions modal.
> [FIX] App installation from marketplace not correctly displaying the permissions

- client/components/Header/Header.tsx
- client/views/room/Header/Header.js
> [FIX] Header component breaking if user is not part of teams room.

- app/lib/server/functions/parseUrlsInMessage.js
- app/lib/server/functions/sendMessage.js
- app/lib/server/functions/updateMessage.js
- tests/end-to-end/api/24-methods.js
- Fix `updateMessage` to avoid parsing URLs inside markdown
- Honor `parseUrls` property when updating messages
> [FIX] Updating a message causing URLs to be parsed even within markdown code

- app/discussion/client/discussionFromMessageBox.js
Permissions 'start-discussion-other-user' and 'start-discussion' are checked everywhere before letting anyone start any discussions, this permission check was missing for message box actions, so added it.
fixes #21546
> [FIX] Checking 'start-discussion' Permission for MessageBox Actions

- client/views/admin/rooms/RoomsTable.js
- packages/rocketchat-i18n/i18n/en.i18n.json
> [FIX] Team types in admin -> rooms.

- app/api/server/v1/emoji-custom.js
- app/emoji-custom/server/methods/uploadEmojiCustom.js
- package-lock.json
- package.json
- server/sdk/index.ts
- server/sdk/types/IMediaService.ts
- server/services/image/service.ts
- server/services/startup.ts
- Create new MediaService (ideally, should be in charge of all media-related operations)
- Resize emojis to 128x128
> [IMPROVE] Resize custom emojis on upload instead of saving at max res

- .github/workflows/build_and_test.yml
Current build on CI is failing probably because he using an old `node_modules` cache. Doing this change will invalidate the validate but also is the recommended way to calculate a hash for more than one file: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-with-multiple-patterns
> Regression: Change CI files hashes for caching

- client/components/Message/Attachments/components/Image.tsx
- client/providers/createReactiveSubscriptionFactory.ts
- client/views/room/contextualBar/Threads/ThreadList.js
- client/views/room/contextualBar/Threads/useThreadsList.ts
Actually thats 'solves' a major issue: somehow rendering react -> blaze -> react -> blaze -> react makes some trackers loose the tracking (😏) creating some reactivity issues. Solves because I just detached the tracker from the rendering flow. But since we want to remove blaze that should not be a problem.
> Regression: Unread Threads Header and List

- tests/end-to-end/api/25-teams.js
add more tests to this endpoint
> Chore: Add tests for teams.update REST endpoint

- app/models/server/raw/Users.js
- ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.js
- ee/app/livechat-enterprise/server/lib/Helper.js
The Omnichannel Concurrent Chat Limit feature is not working properly when checking the limit per department, the reason is that the algorithm that fetches the number of ongoing chats per agent wasn't considering the department of the subscriptions, hence,  the number returned from DB was bigger than it should be.
> [FIX][Enterprise] Omnichannel simultaneous chat limit is not properly checking the limit by department

- app/file-upload/server/lib/FileUpload.js
- app/webdav/server/lib/webdavClientAdapter.ts
> [FIX] Uploading files from WebDAV

- app/api/server/v1/teams.ts
- app/models/server/raw/Users.js
- server/sdk/types/ITeamService.ts
- server/services/team/service.ts
- Send a warning message to a team's main channel when a user is removed from the team;
- Trigger events while removing a user from a team's main channel;
- Fix `usersCount` field in the team's main room when a user is removed from the team (`usersCount` is now decreased by 1).
[Task - ClickUp](https://app.clickup.com/t/4h2e5e) (no warning messages are sent)
[Task - ClickUp](https://app.clickup.com/t/4h2duk) (`usersCount` field is decreased by 2)
Create a new team and insert/remove a member. When a user is removed or leaves a team, its main channel's `usersCount` field will be decreased by 1 and a warning message will be sent.
Fixes #21901 (includes its changes)
> [FIX] No warning message is sent when user is removed from a team's main channel

- client/views/teams/contextualBar/channels/BaseTeamsChannels.js
- client/views/teams/contextualBar/channels/RoomActions.js
- client/views/teams/contextualBar/channels/TeamsChannelItem.js
#21595
- Create a team
- Add channels to the team
- Check the permissions as a not-allowed user
> [FIX] Missing proper permissions on Teams Channels

- ee/app/livechat-enterprise/server/permissions.js
By design, users with `livechat-monitors` role might be able to deal with all departments associated with `units` they're monitoring, but currently, Omnichannel Monitors are not authorized to view any department. 
This is happening because the permission `manage-livechat-departments` is not granted to `livechat-monitors` role.
> [EE] Omnichannel monitors not authorized to view departments

- app/authentication/server/lib/restrictLoginAttempts.ts
- app/models/server/raw/Rooms.js
> Regression: Match `name` or `fname` when fetching room to send notification for blocked log in attemps

- app/file-upload/server/config/Webdav.js
> [FIX] App crashes when downloads come from WebDAV and the server is not available

- app/google-oauth/server/index.js
- server/importPackages.js
> [IMPROVE] Support for Google OAuth for mobile app

- app/lib/server/functions/saveUser.js
- app/mailer/server/api.js
fixes an issue where if password contains special HTML character like &, in the email it would end up something like `&amp;amp;`
password was going through multiple escapeHTML function calls
`secure&123 => secure&amp;123 => secure&amp;amp;123
`
Closes #21986 
edit user from admin panel
enable the option "Set random password and send by email"
check your email or see logs for email html
> [FIX] Emails being sent with HTML entities getting escaped multiple times

- app/ldap/server/settings.js
In LDAP, port input box is accepting string value as a correct input. But it should only accept integer as a correct value.
Steps to reproduce :
1. Go to administration.
2. Go to LDAP.
3. Enable the first configuration.
4. Type input in port input box. 
Before:
After:
> [IMPROVE] LDAP port setting input type to allow only numbers

- app/ui-sidenav/client/roomList.js
- client/views/room/contextualBar/Call/Jitsi/CallJitsWithData.js
- client/views/room/contextualBar/Call/Jitsi/lib/JitsiBridge.js
The new rewrite in react of contextual call component broke the Jitsi "click to join" messages. The issue being after 10 seconds of initiating the call, the message "click to join" always returned "Call Ended" even if the call was still going on.
This was due to the fact that after closing the contextual bar, the react component gets unmounted and we are not able to keep track of ongoing call and increase jitsi room timeout. 
This PR solves this issue by using the setInterval methods on component will unmount. When the call component unmounts, we keep on checking the state of jitsi call and based on conditions increase the jitsi room timeout. After the call is ended all setInterval calls are closed.
This PR also removes the implementation of HEARTBEAT events of JitsiBridge. This is …
> [FIX] Fixing Jitsi call ended Issue.

- app/message-read-receipt/client/index.js
- app/message-read-receipt/client/views/readReceipts.html
- app/message-read-receipt/client/views/readReceipts.js
- client/importPackages.ts
PR #21318 had removed the readReceipts views - I've restored the old files here, without changing anything on the code.
> [FIX] Read receipts are broken

- server/modules/watchers/watchers.module.ts
With the introduction of micro services and the new DB watchers in https://github.com/RocketChat/Rocket.Chat/pull/19000 the env var `DISABLE_PRESENCE_MONITOR` used to control whether an instance should be watching for user presence events was not being respected.
> [FIX] Support DISABLE_PRESENCE_MONITOR env var in new DB watchers
