client/stylesheets/base.less
client/views/app/sideNav/userStatus.html
client/views/avatar/avatar.coffee
client/views/avatar/avatar.html
client/views/avatar/avatarPrompt.coffee
client/views/avatar/avatarPrompt.html
client/views/login/social.html
i18n/en.i18n.json
i18n/pt.i18n.json
server/methods/setAvatarFromService.coffee

No require avatar fixes

---

client/stylesheets/base.less
client/views/app/chatMessageDashboard.coffee
client/views/app/chatMessageDashboard.html
client/views/app/chatWindowDashboard.coffee
client/views/app/chatWindowDashboard.html

Group messages

---

client/stylesheets/base.less
client/stylesheets/global/_variables.less

Better organization for stylesheet folders, specific file for variables,
fix fort when you don't have any message and scroll always appear (same
for channel list and user list).

Better Stylesheet organization + Fix for scroll in chatlist/messages/userlist

---

.meteor/packages
.meteor/versions
packages/rocketchat-irc/Readme.md
packages/rocketchat-irc/irc.server.coffee
packages/rocketchat-irc/package.js
server/lib/accounts.coffee
server/methods/joinRoom.coffee
server/methods/leaveRoom.coffee
server/methods/receiveMessage.coffee
server/methods/registerUser.coffee

Just a prototype, still need a lot of things to do. Please don't accept it.

IRC prototype.

---

README.md

HTML embed does not work on docker hub and the SVG is broken.   Change to more universal markdown supported by both.

Fix logo markdown for docker hub compatibility

---

.meteor/packages
.meteor/versions
client/lib/chatMessages.coffee
client/lib/collections.coffee
client/methods/updateMessage.coffee
client/stylesheets/base.less
client/views/app/message.html
client/views/app/room.coffee
i18n/en.i18n.json
server/methods/updateMessage.coffee

Once more as discussed with @sampaiodiego now adjusted to new message rendering 
Link to old PR RocketChat/Rocket.Chat#189

Implemented delete button next to edit and modal confirmation

---

packages/rocketchat-webrtc/webrtc.js

stream can emit data at anytime, this eliminates some edge-condition lock-ups

improve stability of callee #115

---

client/stylesheets/base.less
client/stylesheets/global/_variables.less
client/views/app/layout.coffee
client/views/app/layout.html
client/views/app/room.coffee
client/views/app/room.html

non-intrusive implementation, no impact to rest of UI when web-rtc video is not in session
ONLY when web-rtc video is showing, click on the remote-video window to switch modes
HELP  please  ...  (need experts)  TODOS:
- the ugly `{{#if}}` in `room.html`  needs to be refactored into one single set of `<div><video>`, perhaps some template helpers,  and CSS3 transition added to make boxes 'fly into place'

proposed initial poc 'benchmark' ui - #115

---

client/views/app/room.html

flexbox differences in firefox caused zero-height video element when flex-direction is row and align-item is center

fix up flexbox differences with firefox - #115

---

packages/rocketchat-webrtc/webrtc.js

Firefox has event.target instead of event.srcElement.

Fix Firefox event difference  -  #115

---

.editorconfig
client/views/app/layout.coffee
client/views/app/room.coffee
client/views/app/room.html

Added two new modes:
HD mode - just click on the remote-video to see the new mode.
Fullscreen mode - click on the local-video while you're in HD mode to enter full-screen.
Ready for @rodrigok  's  720p HD conferences
Also cleaned up some code - adding new mode is easier now.  
Added [EditorConfig](http://editorconfig.org/)  support  so there is less chance of  a mega-commit when a contributor only changed a single line of code ... due to tab/space conversions.

add Video Chat HD and fullscreen modes for web-rtc #115

---

client/views/app/room.coffee
packages/rocketchat-webrtc/webrtc.js

Mode is now reset to zero if user closes flex tab directly.
Also fixes a web-rtc edge condition that usually does not occur in production, but frequently during testing.
@rodrigok  - thanks for the deferred mute BTW ... unfortunately I blew my tube amp on feedback before then :(

reset video chat mode when user close flex tab directly + minor webrtc edge cond fix #115

---

packages/rocketchat-lib/server/sendMessage.coffee

The message count when viewing History is incorrect because the ChatRoom message count and last message timestamp is not updated when a message is sent.
The ChatRoom update selector referenced the wrong (non-existant) field.
Thus, the room's message count was never incremented.  Also fixes issue
where the room's last message timestamp is not set on the room document.

Fix RocketChat/Rocket.Chat#239 room's message count and last message

---

client/views/app/room.coffee

Restore code removed by:
https://github.com/RocketChat/Rocket.Chat/commit/4d4625202002c8d92870500b530ef9cdcfc4d3ac
This should restore webrtc operations.

restore webrtc code removed by recent merge commit

---

client/lib/collections.coffee
server/lib/collections.coffee
server/publications/messages.coffee
server/startup/migrations/v9.coffee

Standardize collection names to rocketchat_XXX (from data.ChatXXX).
Update Collection variables to use new rocketchat_XXX collections and
migrate data (v9.coffee) from old collection to new collections.  After
migration, drop old collection (data.ChatXXX) via rawCollection access.
Note: rawCollection access added with Meteor version 1.0.4.

Fix RocketChat/Rocket.Chat#12 Standardize collection names

---

.meteor/packages
client/views/app/message.coffee
client/views/app/room.coffee
packages/rocketchat-webrtc-ib/adapter.js
packages/rocketchat-webrtc-ib/common.js
packages/rocketchat-webrtc-ib/package.js
packages/rocketchat-webrtc-ib/server.js
packages/rocketchat-webrtc-ib/webrtc.js
packages/rocketchat-webrtc-ib/webrtcmsg.coffee

This is a solid and reliable (but less efficient than default) rtc signaling stack.  
It is in-band, so as long as private messaging works, it will also work.
Works across most edge conditions including -  single client reload, both clients reload, client up and client down, server up and server down, code hot-deploy, and so on.
Artifacts:  Ghost messages - the room UI leaves space for these 'unrendered' messages - I think because we currently have no other message type that does not create at least one line of output.

Add web-rtc in-band signaling stack as an optional (not installed by default) package

---

packages/rocketchat-lib/settings/lib/settings.coffee
packages/rocketchat-oembed/server/server.coffee
server/startup/migrations/v9.coffee

Migrate data from settings and oembed_cache collections to rocketchat_settings and rocketchat_embed_cache.

Update RocketChat/Rocket.Chat#12 Prefix settings and oembed_cache collections with rocketchat_

---

client/stylesheets/base.less
client/views/app/room.html
packages/rocketchat-webrtc/webrtc.js

720p video will now display full screen (while in full screen video conferencing mode) on Chrome browsers.  Previously it was centered and had a big black border.
Tested, on in-band stack, with calls from Chrome to Chrome, Firefox to Chrome, and Chrome to Firefox.

Fix probem with 720p video full screen display on chrome browser

---

packages/rocketchat-webrtc/webrtc.js

Description of bug condition:
* caller clicks `Video` button:  `webrtc.to` is set in `Video onclick`,  stack starts and `stream.emit()` issued to callee
* callee receives message and displays dialog:  for convenience, callee uses the `from` field of message as the caller's **name** to be displayed in dialog;  callee needs to respond immediately; since `Video` button was not clicked on callee - `webrtc.to` is not set, callee ends up calling `stream.emit()` with destination **undefined** (most of the time, unless callee's video button was clicked in a previous test, and the browser has not been reloaded - and there were no intervening code hot-deploys)
This bug was discovered while experimenting with the in-band stack. The fix should greatly improve usability of the default stream stack.

fix a bug in webrtc stream signaling stack to improve stability

---

client/lib/chatMessages.coffee
packages/rocketchat-lib/client/slashCommand.coffee
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/slashCommand.coffee
packages/rocketchat-me/me.coffee

Handles all /commands by allowing registered callbacks for commands
First to register takes that command
Any entry starting with / will be intercepted and a message will not be delivered
Format is /command this goes as one big parameter
Updated /me as example

Slash command handler

---

client/views/app/sideNav/createChannelFlex.coffee
client/views/app/sideNav/createChannelFlex.html
client/views/app/sideNav/privateGroupsFlex.coffee
client/views/app/sideNav/privateGroupsFlex.html
i18n/en.i18n.json
server/methods/createChannel.coffee
server/methods/createPrivateGroup.coffee

channel or private group
Queried ChatRoom for Room with same name and returned a descriptive
error if one was found when creating a Channel or Private Group.

Fix RocketChat/Rocket.Chat#329. Check for duplicate name before creating Channel and Private Group.  Also, check Private Group for illegal name. 

---

server/methods/getUsernameSuggestion.coffee
server/methods/setUsername.coffee

I was looking into open source slack alternatives for a little startup and came across rocket.chat. I deployed it locally and when I tried to signup with username IshwerDAS (that's how we would like to spell it as DAS is actually an acronym). Anyway, it gave me an error. It took me a while to figure out what was wrong as all that error said was `use only letters, numbers, dots and dashes` and that was all I was using. A little look into code made me realize that regex used was only for lower case letters. So now either the error given should have been better or it should accept mixed case usernames. I preferred later and edited code to accept mixed case usernames. But I also didn't want 2 people signing up with same username in different case, so changed the function `usernameIsAvaliable` …

Case insensitive username

---

client/stylesheets/base.less

Fixing the bug described in #343

Allow scrolling user status sidebar when screen height is too small

---

server/methods/canAccessRoom.coffee

Fix a minor bug when room id supplied to canAccessRoom is not valid, discovered during REST-full API testing.

fix prob when room id is not valid

---

README.md
client/stylesheets/base.less
client/views/app/room.coffee
client/views/app/room.html
packages/rocketchat-webrtc-ib/webrtc.js

Working implementation.  Some edge conditions, multiple-modes handling, and timeouts need to be studied and tuned.
Implementation isolated to the webrtc-ib   (our in-band signaling, R&D) stack -- zero to minimal impact on the mainstream code.
The webrtc-ib stack is not installed by default.  Once the feature is solid, it can be back ported to the stream stack.

Initial implementation of scalable remote video monitoring - closes #385

---

client/lib/chatMessages.coffee
client/views/app/room.coffee
client/views/app/room.html
packages/rocketchat-lib/settings/server/startup.coffee

This fixes #38
- introduce Message_MaxAllowedSize setting that defaults to 500
- set max-length attribute on the message textarea equal to Message_MaxAllowedSize
- do not send messages with size >  Message_MaxAllowedSize

Limit maximum message size

---

client/views/app/room.coffee
client/views/app/room.html

The conversation button is currently visible, but doesn't work because
the user can't start a direct message with themself.  This change hides
the button only when viewing their own profile.

Fix RocketChat/Rocket.Chat#412.  Hide button when user views their profile in a private group or channel's member section.

---

.dockerignore
README.md
docker-compose.yml

hi,
added some files to quickstart rocket.chat with docker and another hosting option with sloppy.io.
mike

docker quickstarter, compose and dev

---

client/views/app/message.coffee

Fix for #466 
Replaces gender specific translation with non-gender translation.
Grammatical gender change from 6329d071180bccf86586c5627cb8bc06bf231c39
references 'gender' message field.  If field doesn't exist, then
username is not replaced.
Gender specific messages don't seem to be implemented.  The
6329d071180bccf86586c5627cb8bc06bf231c39 commit hardcoded "male" value
in other places that used gender specific translation.
Replaced gender specific translation with non-gender specific translation, and
removed gender option.

User left message token replacement not working

---

client/lib/RoomManager.coffee
client/routes/roomRoute.coffee
client/views/app/room.coffee
client/views/app/sideNav/chatRoomItem.coffee
client/views/app/sideNav/chatRoomItem.html
client/views/app/sideNav/listChannelsFlex.html
packages/rocketchat-colors/client.coffee
server/publications/room.coffee

Better urls

---

client/views/main.coffee

This fixes #531
Tested this on mac / windows / linux.  Super + p on windows and linux is a no go.  
On the gnome display environment in linux it actually is bound to changing between mirrored and extended for your monitors.

Fix search not coming up

---

packages/rocketchat-oembed/client/oembedImageWidget.html

By setting height to 200 you were causing images to stretch.  Setting it to a max-height, makes it fit auto resize to fit your max height.
This would fix #543

Fix image stretching

---

client/stylesheets/base.less
client/views/admin/admin.html
client/views/app/sideNav/sideNav.coffee
client/views/app/sideNav/sideNav.html
i18n/en.i18n.json
packages/rocketchat-lib/settings/server/startup.coffee

I just created a setting to allow overriding the sidenav footer content, allowing the use of own logos on Rocket.Chat.

Setting: Layout Sidenav Footer

---

packages/rocketchat-lib/server/functions/getStatistics.coffee

Checks if statistic is defined in collection before setting value.  Defaults to 0, if statistic not found and logs message in case statistic should exist (e.g. if schema changes and map/reduce function is incorrect).

Fixes #580.  Undefined statistic when no private group exists

---

client/startup/unread.coffee
client/views/main.coffee
i18n/en.i18n.json
packages/rocketchat-lib/settings/server/startup.coffee
server/startup/migrations/v16.coffee

This configures the ability to set the Site Name.
In the future meta tags need to be updated as well..

Configure Site Name

---

client/lib/readMessages.coffee
client/lib/readMessagesOnFocus.coffee
client/routes/roomRoute.coffee
client/startup/unread.coffee
client/stylesheets/base.less
client/views/app/room.coffee

- If window loses focus user needs to scroll or click/touch some place inside messages-box
- On hit ESC enable read and force read of current room
- When user change room disable read until user interaction
- Only read if mark of *first-unread* is visible for user or if flag *force* was passed
- Always read the opened room
- The default method *read* has a delay of 2000ms to prevent multiple reads and to user be able to see the mark

Add unread mark

---

client/stylesheets/base.less
client/views/app/message.coffee
client/views/app/room.coffee
client/views/app/room.html
server/methods/searchMessage.coffee
server/startup/indexes.coffee

Initial implementation of search in channel

---

server/methods/deleteMessage.coffee
server/methods/deleteUser.coffee
server/methods/updateMessage.coffee

Only two I could find that still needed it.

Added checks to updateMessage and deleteMessage

---

.meteor/packages
.meteor/versions
packages/rocketchat-slashcommands-invite/invite.coffee
packages/rocketchat-slashcommands-invite/package.js

Allow invite via: `/invite username`

Added /invite slash command

---

packages/rocketchat-sharedsecret/package.js
packages/rocketchat-sharedsecret/sharedsecret.coffee

See issue #268
Note that this plugin was always intended to do both encryption and decryption on the client.
The current implementation does encryption on the server, and uses a temporary server-side key storage which means a user has to set the shared secret every time they open the client and enter a room. If the server restarts all keys are lost and have to be entered again.
This means the data is encrypted at rest, but can be intercepted by anyone who has access to the server. To offer proper confidentiality of message contents you would have to move the encryption to the client.

Feature/sharesecret #268

---

.meteor/packages
.meteor/versions
packages/meteor-accounts-saml/.npm/package/npm-shrinkwrap.json
packages/rocketchat-slashcommands-leave/leave.coffee
packages/rocketchat-slashcommands-leave/package.js

Lets try this again.  Now this includes just the slashcommand-leave package.  Kick will be done seperately. 
Looks like two copies of xmldom were in npm-shrinkwrap.json and meteor decided one didn't belong.

Added /leave and alternate /part

---

client/stylesheets/base.less

I'm guessing there was some sort of regression which went uncaught, because it's hard to see how/why this was the intended behavior:
But with this change, we now have:
---
Screenshots come from Chrome 45.0.2454.85 on Linux

Improves styling for code.inline runs

---

client/views/admin/admin.coffee

should fix it.  spin button on UI ensures only int data is incoming - no need to validate again.
closes #701 
pls merge and push 2 demo, need for ongoing bot testing

fix problem of saving int typed setting #701

---

client/views/account/accountProfile.coffee
client/views/account/accountProfile.html
packages/rocketchat-lib/server/methods/setUsername.coffee
server/methods/saveUserProfile.coffee

Addresses https://github.com/RocketChat/Rocket.Chat/issues/695

adding the ability to edit usernames

---

client/lib/notification.coffee
client/notifications/notification.coffee
packages/rocketchat-lib/server/sendMessage.coffee

Re enable desktop notifications via stream notifications

---

client/stylesheets/base.less

when opening `My Account` or `Administration`, link in nav-bar footer no longer clickable

fix nav-bar footer covered by flex-nav

---

packages/rocketchat-oembed/server/server.coffee

Reference issue: #727
I think also an issue being had where uploads aren't showing previews when behind nginx with ssl.

Allow invalid ssl certs.  IE self signed on oembed fetch

---

i18n/en.i18n.json
packages/rocketchat-lib/settings/server/startup.coffee
packages/rocketchat-oembed/server/server.coffee

This is for #754.
The description was pulled from this comment, https://github.com/RocketChat/Rocket.Chat/pull/749#issuecomment-139316674, and might need to be changed up to make it easier to understand.

Allowing the rejecting/allowing of ssl certs to be configurable by the admin

---

client/stylesheets/base.less
client/stylesheets/utils/_colors.import.less

Except dropdown menu, all others are small fixes.
Images show more than words now.
Date before
Date after
--
Top Line before
Top Line after
--
Bottom box and attachment box before
Bottom box and attachment box after
--
I remeber something talkling about this, but i don't find the issue.
Before:
After:

Fixing misaligned boxes + Fix for dropdown menu appearing in front of username box

---

packages/rocketchat-slashcommands-invite/invite.coffee

This fixes #790 by verifying the username of who is being invited isn't already in that room.

Fix error on inviting already joined users, fixes #790

---

.meteor/packages
.meteor/versions
packages/rocketchat-slashcommands-join/join.coffee
packages/rocketchat-slashcommands-join/package.js

This adds the `/join` command, allowing a user to type `/join #test` to join the test channel if they haven't already joined it.
Couple of notes:
* The channels listed when you start typing `#` are ones you've joined, so it feels pointless at the moment
* There is no error message if you type a channel you're already part of
Those two things should probably be discussed on another issue to determine how they should be handled.

Add the join command

---

client/lib/RoomManager.coffee

Allow send a message to one user via the notification system, this message is temporary and go away when user lost the data on minimongo.
From **server** to **client**
```javascript
RocketChat.Notifications.notifyUser('UserID', 'message', messageObject);
```
Example:
```javascript
RocketChat.Notifications.notifyUser('MZiFvWAfF4RF4AD5u', 'message', {
_id: Random.id(),
rid: 'GENERAL',
ts: new Date,
msg: 'user/client only message'
});
```

Allow to send a temp message to one user to one room

---

packages/rocketchat-mentions/client.coffee
packages/rocketchat-mentions/server.coffee

Prevents turning hashtags into channel links if there are no such channel (should close #807)

Avoid turning hashtags clickable if not related to channels

---

server/lib/accounts.coffee

Modifies admin role assignment to check if the inserted user is the
first user based on sorted query using "createdAt".
Originally, the admin role assignment was done onCreateUser before
the user record was inserted into the db.  It assigned the 'admin' role
to a user if no other user existed in the db.  However, with the change
to insertUserDoc, the 'admin' assignment is done AFTER the first user
is inserted and the original query logic (check if any user exists) no
longer applies

Fix issue where the first inserted user is not assigned the 'admin' role

---

client/views/app/messagePopupConfig.coffee

Currently the situation is something like this:
That first user should not be even displayed. If i'm typing @ something.  I would expect it to only match beginning with what i've typed.  Otherwise its more of a search then a completion.

Modified find for autocomplete to show usernames that begin your input

---

server/methods/addUserToRoom.coffee

Fix bug where username incorrectly passed to findOneByUsername.  Also adds argument validation.

Fix #857  Cannot add user to room.  

---

server/methods/joinRoom.coffee

also returns useful error if room doesn't exist.
Added this mainly to make interacting with the bot better.

joinRoom returns if room is already added

---

packages/rocketchat-lib/settings/server/startup.coffee

Set environment value after RocketChat.settings have been initialized.
RocketChat settings are loaded ASAP as of 39fe1365b58638e0fa9e66ade8c1705b05ea3692
RocketChat.settings depends on Meteor.settings under the covers, but Meteor.settings
doesn't seem to return values until Meteor is fully started.  Thus, we
can only call RocketChat.settings.get after Meteor.startup

Fix #911.  Set MAIL_URL variable after Meteor.startup

---

packages/rocketchat-hubot/hubot.coffee

this will close #895
Currently the bot listens in every room.  When having a private conversation its really annoying to have the bot pop in.  Could probably be limited further.  But this to me is a great start.

Changed internal bot to only listen on public rooms

---

packages/rocketchat-autolinker/autolinker.coffee
packages/rocketchat-spotify/spotify.coffee

Actual behavior
(Spotify is not installed on current demo)
As you can see links for media are rendered even inside `` `literal` `` markdown syntax.
Result

disable rendering media links/syntaxes inside literals

---

packages/rocketchat-lib/server/models/Users.coffee

RocketChat.models.Users findOneByEmailAddress had a typo in the query field.  The
following use cases are fixed:
1. sendConfirmationEmail
2. sendForgotPasswordEmail
3. lookup existing admin by email when initializing RocketChat at
startup

Fix #911 where emails not sent.

---

client/lib/fileUpload.coffee
server/startup/migrations/v20.coffee

Added room Id field for better relationship between objects.

---

.meteor/cordova-plugins
mobile-config.js

Crazy complicated fix:
* cordova 5.x will now needs npm modules for plug-ins  - causing  plug-in name change
* facebook connect plugin has library conflict and is not actively tested/maintained
* formerly maintained Telerik fork of facebook connect plugin never migrated to npm modules
* pull request to fix facebook connect plugin library version conflict was never merged
* need for fork and cherry pick from another fork to create our own (for now) working branch

fixes cordova build after meteor 1.2 update - closes #985

---

client/lib/avatar.coffee

Avatars using absolute url can generate erros on `toDataURL` when accessing via HTTPS and roo url was configured to HTTP

Fixes #942. Use relative url for avatars.

---

packages/rocketchat-markdown/package.js

This will prevent rocketchat:markdown tests to fail when PR #1045 is merged.

rocketchat:markdown - Settings file should only be present on server.

---

client/stylesheets/base.less

Fixed by applying “-webkit-user-select: none;” to everything except
inputs.
Should fix #1011 
Should fix #1019 as well.

Fix for Login/Signup form on Safari

---

client/views/app/room.coffee

Fixes the rendering of user info when accessed by @mention.

---

packages/rocketchat-github-enterprise/common.coffee
packages/rocketchat-github-enterprise/i18n/en.i18n.json
packages/rocketchat-github-enterprise/package.js
packages/rocketchat-github-enterprise/startup.coffee

Before when you put server URL in you'd have to put domain.com/ if you forgot the slash all urls would end up like this: `domain.comapi/v3/user`
Added i18n incase needed in future and added note to exclude trailing slash
@leefaus if you could take a look at your convenience.

Changed Github Enterprise endpoints to be relative to the domain.

---

.travis/setbuildinfo.js

Related to #1117 
Every new build now includes a version + build number.

Fix #1117 - Display Meteor package version information

---

.meteor/packages
packages/rocketchat-oembed/server/server.coffee
packages/rocketchat-soundcloud/lib/client/oembedSoundcloudWidget.html
packages/rocketchat-soundcloud/lib/client/widget.coffee
packages/rocketchat-soundcloud/package.js

**Attention** package is disabled (comment on https://github.com/kakawait/Rocket.Chat/blob/soundcloud-integration/.meteor/packages#L44) by default
related issue #1090
**Do not merge PR before reading below**
Indeed current implementation does not support *group* embed widget (like https://soundcloud.com/groups/made-with-ableton-live) unlike Slack
Problem is due to `meta` does not provide any direct link to `player`. I need to rebuild url but url should look like
https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Fgroups%2F3&show_artwork=true&maxheight=150
As you can see we need to use url like `api.soundcloud.com/groups/{id}` but meta does not provide `{id}` for group `made-with-ableton-live`.
We can use …

SoundCloud embed widget integration

---

packages/rocketchat-markdown/markdown.coffee

Pattern for MD images should start with `!`, otherwise the message will be treated as a normal link.

Fixing Markdown regex for image support

---

packages/rocketchat-oembed/client/oembedImageWidget.html
packages/rocketchat-theme/assets/stylesheets/base.less

Improve image oembed

---

client/views/app/tabBar/uploadedFilesList.html
packages/rocketchat-theme/assets/stylesheets/base.less

"**Files list**" felt sad. Did some minor changes to make it look a little more happy.
Screenshot:

Added some styling for files list.

---

i18n/en.i18n.json
i18n/pt.i18n.json
packages/rocketchat-lib/settings/server/startup.coffee
server/lib/accounts.coffee

Mostly wrapping [this](https://github.com/RocketChat/Rocket.Chat/pull/1053#issuecomment-146979501) up.
Closes #975 
Closes #1053

Domain whitelist for account registration

---

client/views/app/sideNav/chatRoomItem.html

Changed icon for hiding direct messages in sideNav

---

client/views/admin/rooms/adminRooms.html
client/views/admin/users/adminUsers.html
packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less

Various small improvements to the rocketchat-theme, affecting:
**Alignment of (Edited) status in messages**
**History**
Adding margin, padding, fixed on hover background colouring.
**Rooms**
Adding margin, padding, fixed on hover background colouring and mouse pointer.
**Deleting a Room**
Adding margin, padding and fixed top margin of .room-info-content. Replaced hash with a cancel icon.
**Users**
Converted table headings from _td_ to _th_, making them bold by default.

Improving rocketchat-theme styles

---

packages/rocketchat-oembed/server/server.coffee
packages/rocketchat-soundcloud/lib/client/oembedSoundcloudWidget.html
packages/rocketchat-soundcloud/lib/client/widget.coffee
packages/rocketchat-soundcloud/lib/server/server.coffee
packages/rocketchat-soundcloud/package.js

Use SoundCloud Oembed API https://developers.soundcloud.com/docs/api/reference#oembed in order to support more links than previous implementation
- for track
- for user
- for group
- for set

Use SoundCloud Oembed API for SoundCloud integration

---

packages/rocketchat-lib/server/models/Users.coffee
server/publications/filteredUsers.coffee

Since deactivated users are treated as banned users and they can't login anymore, don't suggest them to be mentioned. This might not be the best route to go as I'm not 100% sure what else uses the filteredUsers publication, but from my small amount of testing it seemed to do the trick just fine.

Only Suggest Active Users in the Popup

---

client/notifications/notification.coffee
client/startup/unread.coffee
packages/rocketchat-lib/server/sendMessage.coffee

First steps for #1068.
- HTML notifications are shown when the user has selected the room of the message but the chat window does not have the focus.
- HTML notification and new message sound use the same conditions.
- The unread count is updated (and a dock icon badge shown) if the chat window does not have the focus.
- For room messages with "@all", notifications are sent to all online users of the room except for the sender.
There is some duplicate code in /client/startup/unread.coffee (unread count) and /client/notifications/notification.coffee (notifications) for finding out whether the user has immediately read the new message. This could possibly be unified, but I need to get a better feel of the code first, I think.

More consistent HTML notifications and sounds

---

packages/rocketchat-theme/assets/stylesheets/base.less

Firefox interprets user-select: all; to mean that any clicks should result in
the entire element's container being selected, regardless of the user's gesture.
This results in the inability to select only a subset of characters in a chat
message.
Fixes #1242

Use user-select: text; to re-enable selections

---

packages/rocketchat-webrtc/WebRTCClass.coffee

Calling ```stop()``` on the localstream is deprecated.
Instead, this iterates through the localstream's tracks and calls ```stop()``` on each one.
Got it from here: 
https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en
> Use MediaStreamTrack.stop() to stop streaming, not MediaStream.stop()

webrtc: fix deprecation warning 'MediaStream.stop() is deprecated'

---

client/views/admin/admin.html
client/views/app/room.coffee
i18n/en.i18n.json
packages/rocketchat-lib/settings/server/startup.coffee

Hides the microphone for audio recordings (right hand side of chat box) unless wav files are in the file upload whitelist. Currently when wav's are disabled the record button silently fails to upload with no warning on finishing the recording (can test this on the demo server).
There is one slight problem I foresee with this is the default for the upload whitelist is images only, this means when merged everyone ones mic will disappear unless the have manually allowed wav's. If you are an existing user you might notice it disappear but a new user might not know they are missing a feature. Perhaps a compromise is to allow wav's on the demo server? Hopefully most people start there so they at least see the button to go looking into why it is not on their version. One other option is to add …

Autohide audio recorder

---

packages/meteor-accounts-saml/saml_utils.js

This fixes the problem that the SAML request are dated 2 hours into the future.
It implements the fix from https://github.com/nate-strauser/meteor-accounts-saml/issues/5 and generates correct dates.
It is also easier to read now.

Fixed strange date generation for SAML instant time that causes problems with some IDPs

---

client/lib/avatar.coffee
client/methods/updateMessage.coffee
client/views/app/message.coffee
client/views/app/message.html
packages/rocketchat-lib/server/models/Messages.coffee
packages/rocketchat-livechat/app/client/views/message.html
packages/rocketchat-theme/assets/stylesheets/base.less
server/methods/loadHistory.coffee
server/methods/loadMissedMessages.coffee
server/methods/updateMessage.coffee
server/startup/avatar.coffee
server/stream/messages.coffee

This comes in the form of the user's avatar, along with a hover
title that shows username and edit time. As a side note, this
requires us to start saving 'editBy' id as part of message updates.
This has been tested with all 4 of the current avatar methods.
fixes #824

feat(message-ui/edit-info): add information about message editor

---

packages/rocketchat-ldap/package.js

use nodejs 0.12.x on ldaps:// throw error #1363, update ldapjs fix this issuse

update ldapjs for support node 0.12.x tls

---

client/views/app/message.coffee
client/views/app/message.html

This makes message rendering much more self-contained and Meteor-like.
I also simplified `wasEdited`. Also I moved body to be rendered in `onCreated` so that it can be reused and accessed elsewhere. Ideally, I would make it so that it is simply a DOM fragment, as I described here: https://github.com/Konecty/meteor-nrr/issues/1. But I think it is a good first step.

Moved oembed code to a template helper

---

packages/rocketchat-authorization/server/startup.coffee
server/methods/createChannel.coffee
server/methods/registerUser.coffee
server/restapi/restapi.coffee

Fixes #1332 
Replaced bulk REST api methods rolesRequired option with RocketChat.authz.hasPermission checks because Restivus (provides our REST framework) does not support alanning:roles WITH groups (e.g. global, channel specific).  
Added 2 new permissions for bulk user registration and channel creation.  
@Sing-Li can you please take a look since you implemented the original rest api. Thanks!

Add permission checks to bulk rest api methods

---

packages/rocketchat-lib/server/models/Messages.coffee
packages/rocketchat-message-pin/client/actionButton.coffee

I was was not able to verify #1407 as being fixed since there wasn't step by step instructions on how to replicate it, but I was able to edit messages as a regular user and admin user.
Think this is a good point to say that when doing "code reviews" on pull requests we should be more detail focused. My reason for this is because a quick look at the code should have showed that the variables being referenced weren't actually there. I am to blame for not doing as thorough as I should have, but would have been helpful to have a someone else point it out before it got merged....just my two cents on the subject.

Fix for #1411 and #1407. Corrected ill-referenced variables

---

packages/rocketchat-lib/server/models/Messages.coffee

view will render oembed in (marked as deleted) msg - even if msg type is 'rm'

fix delete msg with oembed problem -  closes #1429

---

.travis.yml

@Sing-Li 
This adds spk generation to the travis-ci build. I didn't add a deploy step, since I'm not sure what you guys want to do there. Also, the commands to setup/build the spk got more complicated than I expected, and it may be better to move them to scripts in the `.travis` directory.
One thing worth noting. This uses a randomized app key instead of the private Rocket.chat key (see the `spk init/grep/sed` steps). This is useful for testing purposes, but means that you can't deploy the spk as-is. You could tweak this to use your Sandstorm private key by passing it in as a travis environment variable (obtainable by running `spk getkey vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0
`). Just be *very* careful to not leak it.
If there's interest, we could instead add a `spk repack` …

[sandstorm] Add spk generation to travis-ci

---

.travis.yml

There's a bug (feature?) in Sandstorm that prevents spks with an
improper PGP signature from being installed. This change produces an
spk without PGP signatures, and the future `spk repack` command will
allow you to add/change the PGP signatures in addition to changing app id.

Fix wrong PGP signature for Sandstorm spk builds

---

docker-compose.yml

* Removing --replSet rs0 which causes issue as [described here](https://github.com/RocketChat/Rocket.Chat/issues/1472)
* Updating the mongo database datadir location so that if somebody decides to use volumes in order to maintain state, it works. I'm guessing mongodb changed it's default location from "mongo" to "db" and nobody noticed.

Fixes to docker-compose.yml

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

These changes alters the theme of the text-area and the upload button to look correct with RTL interface.
Related issue: #1521

Textarea theme fix for RTL

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Updated the name of the flex-nav element for RTL from `hidden` to the correct name `animated-hidden`
Related issue: https://github.com/RocketChat/Rocket.Chat/issues/1521

Update the flex-nav hidden element for RTL

---

server/methods/setAvatarFromService.coffee

Adds a call to `RocketChatFileAvatarInstance.deleteFile` before uploading avatars, which removes the file from store before uploading new one. This prevents caching issues when avatar is later changed by the same user. Fixes issue #1546.

Reset avatar before uploading to prevent caching issues

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Many fixes for RTL

---

i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
packages/rocketchat-ui-login/login/form.coffee
packages/rocketchat-ui-login/login/form.html

Added a option to Accounts -> Registration to disable Forgot Password link on login page.
Link isn't necessary in our case as we use LDAP for authentication. This link will probably just confuse our users.
Perhaps anyone else needs this also :)
I'm not a developer so feel free to refactor as needed or toss it into junk :)

Added option to disable "Forgot Password" link on login page.

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

swipebox has not built in support for RTL, and without this fix the images will display outside of the window range since it does the calculation for the window location assuming every thing is aligned left, and that is hard-coded in its javascript and cannot be overridden with css.
The easiest fix which is proposed here is to override the global RTL just for swipebox, and make it display in LTR to match its calculations. The problem however, is that the Next and Prev buttons are still in LTR direction which is the opposite of what users of RTL expect.
The other solution is to either replace swipebox with something that is RTL aware, or modify swipebox code to add RTL support.

Fix for image swipebox to show in RTL interface

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

In RTL interface if the file name  has only number, or included RTL characters the file extension will be shown in the wrong side. This fix makes file extensions show correctly for all files

Force file names to always be in LTR

---

packages/rocketchat-ui-account/account/avatar/prompt.html

Currently when you upload an image as an avatar, the "SELECT FILE" button disappears and you get another button to use the uploaded file. However, if you didn't like how the uploaded image looks you cannot upload another one. The work around is to reopen the avatar settings page, instead the upload button should stay there to allow the user to upload a different image.

When uploading an avatar keep "Select file" button

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Code blocks and inline code that are preceded by RTL text will get displayed in RTL, and that breaks the formatting. This fix forces it to always display in LTR

Set code blocks to always be LTR

---

i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
packages/rocketchat-mentions/client.coffee

The current @mention (for user names and channel names) uses the regex `\b` to detect the name boundaries, however that token doesn't support Unicode characters. This solution replaces the word boundary with a regex that matches end of the word with any of the following white space, colon, comma and dot.
_However, ending a name with a dot still has a problem as it doesn't get a mention link and this fix does not fix it. Part of the problem is that dots are allowed in the name validation regex. So this problem need to be solved later._
Another thing that this fix adds is a description to the UTF8 Name Validation settings, to inform chat admins about the characters that they need to avoid using in their regexes to not break other chat functionalities that depends on special characters to …

Fix for mentioning RTL names

---

packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-theme/assets/stylesheets/rtl.less

Update to the previous pull https://github.com/RocketChat/Rocket.Chat/pull/1626
>Code blocks and inline code that are preceded by RTL text will get displayed in RTL, and that breaks the formatting. This fix forces it to always display in LTR
Moved the changes to the `base.less` since it is not specific to RTL interface it also applies even if the user interface is LTR.

Set code blocks to always be LTR globally

---

server/methods/setAvatarFromService.coffee
server/startup/avatar.coffee

When a new avatar is saved the user name gets encoded using `encodeURIComponent`, this does not affect names in latin characters, however it does change non-latin/unicode names to an encoded string.
However, when reading the avatar image file, the function uses the username directly without enocinding it, so latin names work since the encoding doesn't change anything, however, Unicode names don't since the usernames don't match the encoded names.
This fix adds the encoding function when reading the avatars.
Also adds the encoding to the function that writes avatars from URL.

Avatars for Unicode usernames

---

packages/rocketchat-oembed/client/oembedUrlWidget.coffee

When sending a link to Google Maps the preview image is broken. Background: The link to the image is grabbed from the target page from the meta.og:image element - which contains several "&amp" instead of "&" in case of GM.

fix broken image-link when og:image contains "&amp;" (e.g. Google Maps)

---

server/lib/accounts.coffee
server/startup/initialData.coffee

The recent addition of the user `Rocket.Cat` for integration and it being created as a first user has caused the "real" first users to no longer be made admin. This fixes #1632 and #1646

Rocket.Cat Shouldn't be Admin

---

packages/rocketchat-ui-sidenav/side-nav/listPrivateGroupsFlex.coffee

Currently, if one opens the list of their private groups ("More private groups ..") and then clicks on 'CREATE NEW'  the 'Create a new public channel' dialog is opened. I believe that this is not intended behaviour, so this PR makes it open the 'Create a new private group' dialog instead.

Fix 'create new' in private group list opening 'create channel' flex

---

i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
server/lib/accounts.coffee

Setting allows admin to modify Meteor.loginTokenExpires from default 90 days to something else.
Server restart is required for this setting to take effect.
Default value is still 90 days if not modified by admin.

Added setting Accounts_LoginExpiration

---

i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
packages/rocketchat-ui-message/message/message.coffee
packages/rocketchat-ui-message/message/message.html

Group message by time, default 5min

---

client/startup/startup.coffee

This fixes the issue https://github.com/RocketChat/Rocket.Chat/issues/1623
So basically if a user login from a new machine and the language loaded from their profile is different from the local one then set the correct language and if it is an RTL language set the RTL class immediately.

Adjust layout direction based on user's language

---

packages/rocketchat-integrations/server/api/api.coffee

Most modern browser will issue a pre-flight request with HTTP OPTION method before the actual asynchronous POST; and will not continue of it the OPTION fails.    This adds a CORS supporting option endpoint.

Support Integration webhook calls originating from client browsers

---

Dockerfile
install.sh

Since the tgz-name changed... #1737

adjust tgz filename

---

client/routes/adminRouter.coffee
client/routes/router.coffee
client/startup/defaultRoomTypes.coffee
packages/rocketchat-authorization/client/route.coffee
packages/rocketchat-channel-settings/client/startup/tabBar.coffee
packages/rocketchat-chatops/client/tabBar.coffee
packages/rocketchat-integrations/client/route.coffee
packages/rocketchat-lib/client/TabBar.coffee
packages/rocketchat-lib/client/defaultTabBars.js
packages/rocketchat-lib/client/lib/openRoom.coffee
packages/rocketchat-lib/package.js
packages/rocketchat-livechat/app/client/lib/triggers.js
packages/rocketchat-mailer/client/router.coffee
packages/rocketchat-mentions-flextab/client/tabBar.coffee
packages/rocketchat-message-pin/client/tabBar.coffee
packages/rocketchat-message-star/client/tabBar.coffee
packages/rocketchat-ui-admin/admin/users/adminUsers.coffee
packages/rocketchat-ui-admin/admin/users/adminUsers.html
packages/rocketchat-ui-flextab/flex-tab/flexTabBar.coffee
packages/rocketchat-ui-flextab/flex-tab/flexTabBar.html
packages/rocketchat-ui/lib/accountBox.coffee
packages/rocketchat-ui/views/app/privateHistory.coffee
packages/rocketchat-ui/views/app/room.coffee
server/startup/roomPublishes.coffee

Previously every time you access a room, all tab bar buttons were removed and re-added. This were done on `enter-room` callbacks.
Because of this a package was not able to display only one tab bar button, because everytime `enter-room` callbacks were called, all buttons are added again.
Now, every tab bar button is added once with a group option. Every time the tab bar buttons should be displayed, it's called to display a group of buttons, then each button from another group are simply hidden.

Tabbar rework

---

client/startup/startup.coffee
packages/rocketchat-ui-account/account/accountProfile.coffee
packages/rocketchat-ui-login/login/form.coffee
packages/rocketchat-ui-sidenav/side-nav/accountBox.coffee

1. Set current app language to user's language after user login;
If users language setting is different from default app language setting, front end app language should change to user's language once user login
2. Fix the wrong language display in the view of  accountProfile.

Change to user's language once user login if user's language is different from app language

---

i18n/de.i18n.json
i18n/en.i18n.json
i18n/fi.i18n.json
i18n/ro.i18n.json
packages/rocketchat-integrations/client/views/integrations.html

`There_are_no_integrations` should be `There_are_no_integrations` in both the source and interface. 
This is a redo of #1803, but I butchered the Pull Request, so this is fresh and clean.

Minor Grammar Fixup

---

packages/rocketchat-oembed/client/oembedUrlWidget.html

Because of the 10px top and 10px bottom padding the min-height for the content really is only 40.  So this causes the image to bleed over when there is no description.
Link used for testing: http://codenamecrud.ru
@sampaiodiego

Fix min-height on link oembed.

---

packages/rocketchat-ui-login/login/form.html

This will stop the browsers such as Firefox from trying to validate the input field since they are handled by the javascript.

Prevent browsers from trying to validate the input fields

---

packages/rocketchat-ui-flextab/flex-tab/tabs/messageSearch.coffee

If the scroll event does not get triggered, the "has more..." link does nothing. This adds the capability to click the "has more..." link and load more message search results

Include a fallback click event for loading more messages

---

packages/rocketchat-lib/server/functions/sendMessage.coffee
server/methods/updateMessage.coffee

#1857 allowed wider fragment matches, but breaks auto url embed with markdown urls. See #2034
This pr attemps to improve this behaviour.
**Previously :**
```javascript
"[stream](https://www.twitch.tv/stream)".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?#?([^\s]+)?)?/)
```
https://www.twitch.tv/stream)
**With this pr :**
```javascript
"[stream](https://www.twitch.tv/stream)".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\w]+)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s]+))?)?/)
```
https://www.twitch.tv/stream
**Fragments still works :**
```javascript
"https://www.twitch.tv/stream#with/fragment".match(/([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d …
```

Fix url parse on markdown formatted urls

---

server/methods/canAccessRoom.coffee
server/methods/joinRoom.coffee
server/startup/migrations/v28.coffee

A user without 'view-c-room' permission is not allowed to see the
channel list. However, it was still possible to read and write
to a channel by guessing the name and modifying the URL accordingly.
Reading channel contents now requires either the 'view-c-room' permission
or being a member of the channel.

Require 'view-c-room' permission for accessing channels

---

packages/rocketchat-webrtc/WebRTCClass.coffee
packages/rocketchat-webrtc/i18n/en.i18n.json
packages/rocketchat-webrtc/server/settings.coffee

I've added a few extra options to the settings panel where admins can configure custom STUN and TURN servers. We're trying to use RC in my organisation and the external calls made by the client whenever WebRTC sessions are started is troubling for the operations guys :)
This hopes to address this issue #1392 - I'll need someone from the RC dev team to verify that these changes actually work as intended.

Custom STUN and TURN servers

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Terminal output messages are in English and need to be displayed in a fixed direction

Terminal output should be displayed in LTR always

---

packages/rocketchat-ui-flextab/flex-tab/tabs/uploadedFilesList.coffee
server/methods/deleteMessage.coffee
server/publications/roomFiles.coffee

Turns out file deletion had a minor issue; this resolves it.

Allow deleting of files whose corresponding message is not currently loaded in the client

---

packages/rocketchat-ldap/server/ldap.js

the ldap refactoring broke older configurations that use a custom filter but use anonymous
access. Login per LDAP was not possible anymore.
The migration didnt add "userDN" and "password" to the Custom_Domain_Search JSON.
Since people might forget it in the future, just generally handle the case where these values are missing.
PR against master because it broke the 0.18.0 release

fix broken ldap when custom filter specifies no userId

---

packages/rocketchat-ldap/server/ldap.js

This is needed when LDAP server is using certificate which is issued by a CA.
As per NodeJS documentation:
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
ca: A string, Buffer or array of strings or Buffers of trusted certificates in PEM format. If this is omitted several well known "root" CAs will be used, like VeriSign. These are used to authorize connections.
Tested and working. Refactor code if necessary.
It would not resolve following issues:
https://github.com/RocketChat/Rocket.Chat/issues/2188
https://github.com/RocketChat/Rocket.Chat/issues/2035

Split LDAP_CA_Cert into array of strings.

---

server/startup/initialData.coffee

When using the environment variables to create the admin account, you're unable to login or reset your password until the account is [flagged as active in the db](https://github.com/RocketChat/Rocket.Chat/blob/0e95760e9173cebde107cac3a7b56588126b6c4a/server/lib/accounts.coffee#L103).
Adding the `{active: true}` flag here seems to make senses unless this was intentionally left out for some security reason.

Auto generated admin account should be active upon creation

---

packages/rocketchat-cas/cas_client.js
packages/rocketchat-cas/cas_rocketchat.js
packages/rocketchat-cas/cas_server.js

The CAS plugin was previously based on meteor-account-cas which used Meteor.settings to configure the plugin - since we know use a derived rocketchat-cas it way more useful to use the given RocketChat.settings to configure the service during runtime (Meteor.settings were at startup only)

Switched CAS configuration from Meteor.settings to RocketChat.settings.

---

server/publications/spotlight.coffee

this is try to fix the small bug :  I typed "Ctrl+P" to global search, but nothing changed when i selected a user in rocket.chat. There may be some fields (actually,name) lost.

fix publish user_data  under "spotlight"

---

packages/rocketchat-ui-sidenav/side-nav/createChannelFlex.coffee
packages/rocketchat-ui-sidenav/side-nav/privateGroupsFlex.coffee

the input add members tips ( auto-complete --"placeholder") should be replaced by some strings when create a new channel (or private group)

add or fix input tips when create a channel

---

README.md

First off, thanks for this fantastic project! Just adding Cloudron.io to the list of deployment strategies. I just added ours first since it doesn't appear alphabetically sorted. I am happy to move it around (or move it as you like).
The code for the app itself is at https://github.com/cloudron-io/rocketchat-app. It would be great if we could collaborate on the app together so that Rocket.Chat releases and Cloudron app releases move together. I have opened some update related issues on this repo's issue tracker already.
Also, I am happy to either add Rocket.Chat developers into the app repo or alternately move the rocketchat-app repo into the RocketChat org.

Add cloudron to deployment

---

.meteor/versions

emojione:emojione upgraded from 2.1.0 to 2.1.1
kenton:accounts-sandstorm upgraded from 0.1.8 to 0.2.1
mdg:validation-error upgraded from 0.4.0 to 0.5.1
meteorhacks:fast-render upgraded from 2.10.0 to 2.13.0
meteorhacks:meteorx added, version 1.4.1
momentjs:moment upgraded from 2.11.2 to 2.12.0
nimble:restivus upgraded from 0.8.4 to 0.8.7
nooitaf:colors upgraded from 0.0.2 to 0.0.3
underscorestring:underscore.string upgraded from 3.2.3 to 3.3.4
meteorhacks:inject-data upgraded from 1.4.1 to 2.0.0

meteor update

---

packages/rocketchat-channel-settings/client/views/channelSettings.coffee

Just stumbled over a bug where editing the room name in the 'Room Info' tab and then clicking on save without actually making any changes to the room name results in the following message being displayed in the room:
I added in a check to prevent this from happening. Now it will instead simply show the green success message, the same way as is done when editing one of the other values and leaving them unchanged.
Also, this problem only seems to affect the 'Room Info' tab but not the one in the admin area.

Fix bug when changing room name and leaving value unchanged

---

packages/rocketchat-ui-sidenav/side-nav/accountBox.coffee
packages/rocketchat-ui/lib/RoomManager.coffee

Close all opened rooms on logout

---

server/lib/accounts.coffee

restrictCreationByEmailDomain accepts either a function or a string. When it is a string, it will be used by some of the OAuth integrations (like google) to proactively restrict logins.
For my use case this means that employees are automatically asked by google to login with their work credentials instead of first having to select between their personal and work accounts.

Pass restricted domain as string when only one

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Closes #2566 
So the the emoji button won't overlap the message

RTL: Give `padding-right` to `.input-message`

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Reverts RocketChat/Rocket.Chat#2567
As per https://github.com/RocketChat/Rocket.Chat/pull/2572

Revert "RTL: Give `padding-right` to `.input-message`"

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

This fix moves the emoji icon to the left side in RTL interfaces
@sampaiodiego

Fix emoji picker icon location for RTL

---

packages/rocketchat-ui-message/message/message.coffee
packages/rocketchat-ui-message/message/message.html

Closes #2495
Pass "@username" in field "avatar" when posting new messages via integrations, like @rocket.cat, will use avatar from that username
Example: 
```javascript
{
"text": "Example message",
"alias": "Rodrigo Nascimento",
"avatar": "@rodrigo.nascimento",
"attachments": [
{
"title": "Rocket.Chat",
"title_link": "https://rocket.chat",
"text": "Rocket.Chat, the best open source chat",
"image_url": "https://rocket.chat/images/mockup.png",
"color": "#764FA5"
}
]
}
```

Allow pass @username in avatar

---

README.md
README.nitrous.md
nitrous.json

Nitrous.io provides a lightning fast way to set up development environments and code in the cloud. [Nitrous Quickstart](https://community.nitrous.io/posts/nitrous-quickstarts) button provides an easy way to run apps without requiring developers to install anything locally. This PR let users deploy their own version of 'Rocket.Chat' in their own container in an instant.
I'm also featuring [Rocket.Chat](https://www.nitrous.io/quickstarts/) on this page because I think it's a great use case for Nitrous Quickstarts.

Add nitrous.io quickstart config and update readme

---

packages/rocketchat-highlight-words/client.coffee

Closes #2610 
Updated regex that supports words using other than ASCII characters

Fix for word highlighting of none Latin characters

---

packages/rocketchat-ui-master/master/main.html

This uses the login layout setting for the reset password, pretty simple change that will make people happy who are currently relying on the settings to customize the Rocket.Chat experience.

Use the login layout for the reset password screen.

---

packages/rocketchat-lib/i18n/de.i18n.json
packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-message-attachments/client/messageAttachment.coffee
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-oembed/client/oembedAudioWidget.coffee
packages/rocketchat-oembed/client/oembedAudioWidget.html
packages/rocketchat-oembed/client/oembedFrameWidget.coffee
packages/rocketchat-oembed/client/oembedFrameWidget.html
packages/rocketchat-oembed/client/oembedImageWidget.coffee
packages/rocketchat-oembed/client/oembedImageWidget.html
packages/rocketchat-oembed/client/oembedUrlWidget.coffee
packages/rocketchat-oembed/client/oembedVideoWidget.coffee
packages/rocketchat-oembed/client/oembedVideoWidget.html
packages/rocketchat-oembed/client/oembedYoutubeWidget.coffee
packages/rocketchat-oembed/client/oembedYoutubeWidget.html
packages/rocketchat-oembed/package.js
packages/rocketchat-spotify/lib/client/oembedSpotifyWidget.html
packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-ui-account/account/accountPreferences.coffee
packages/rocketchat-ui-account/account/accountPreferences.html
packages/rocketchat-ui/views/app/room.coffee
server/methods/saveUserPreferences.coffee

Embedded media like images and video can now individually be collapsed
A new preference "Collapse media by default" is also added, the default
is to not collapse media.
Since images are not always shown, "showImage" is also renamed to
"loadImage"
Known limitation: if the same url is used multiple times in the same message, collapse only works for the first one. This is a deficiency in mongodb that already affects the "save bandwidth" feature, so I think it's not a big deal (who posts the same url twice in the same message anyway?)
Closes #1187

Add ability to hide embedded media

---

packages/rocketchat-ui-master/master/main.coffee

Closes #2696
Do not show the spotlight search when pressing `cmd/ctrl+shit+p`, only when pressing `cmd/ctrl+p`

RocketChat hijacking Firefox shortcut

---

packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/functions/deleteUser.js
packages/rocketchat-lib/server/methods/deleteUserOwnAccount.js
server/methods/deleteUser.coffee

Remove user's avatar from filesystem when deleting the user

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

Fix for the location in RTL interfaces of the email verification check mark which was added in this commit: https://github.com/RocketChat/Rocket.Chat/commit/2c8ceaeef93cf820eca0670e6fa335c269eb5981

Fix for email verification check alignment (RTL)

---

packages/rocketchat-markdown/markdown.coffee

Send:
```
bar
>fooooo
http://www.engadg..............
```
Before:
Unexpected blank-line have cut in between `>foooo` and `http://www.engad.....`.
After:

Remove whitespace around blockquote in message

---

server/startup/initialData.coffee

Closes #2841
Simplify and fix ADMIN_EMAIL verification regex.
* Email addresses start with something other than "@", have arbitrary characters,
at least one "@", at least one character after that.

Simplify and fix ADMIN_EMAIL verification regex.

---

packages/rocketchat-custom-oauth/custom_oauth_server.coffee

The new patch had a bug in it, where the variable name was mistyped.
This time, i have tested it with:
Oauth via header to my own django server (works!)
Oauth via payload to gitlab (works!)
Oauth via header to gitlab (works!)
We *should* also add some sort of note in the gui about what the setting means, since the authorization-bearer header is the RFC specified method, but the setting probably should default to payload for legacy reasons :). Does any other oauth provider use the access_token method? Then again, we probably won't know if its safe, unless you collect target oauth server statistics ;).

Fix oauth payload method

---

packages/rocketchat-custom-oauth/custom_oauth_server.coffee

Closes #2920
This pull request does three things in custom OAuth server module:
* it fixes a typo that prevented "Token Sent Via" switch from working
* it adds HTTP Basic Auth to token retrieval request (so it works with Reddit as per [their docs](https://github.com/reddit/reddit/wiki/OAuth2))
* it adds a fix for parsing response in `registerService` method for Reddit

Custom OAuth fixes

---

packages/rocketchat-message-pin/server/settings.coffee

When you assign the pin-message role to for example normal users, they lose that permission when the server restarts. This change prevents the permissions from resetting to default so that doesn't happen anymore.

Do not reset pin-message permission roles on server restart

---

.sandstorm/Vagrantfile

This pulls in some recent vagrant-spk changes: https://github.com/sandstorm-io/vagrant-spk/commit/ffd9cebd6f4e01323e6967fdc6da9debeabd82d7, https://github.com/sandstorm-io/vagrant-spk/commit/2e8a484af5f7f391b3d3c8d812ecaa7bf6480407, https://github.com/sandstorm-io/vagrant-spk/commit/f9d75eb6a7eca12cbc7f6af97d26f7aea548ffa0.
In particular, these make it possible to run the app with `vagrant-spk dev` using a [libvirt](https://github.com/sandstorm-io/vagrant-spk/blob/master/HOWTO-libvirt.md) provider on a Linux host.
cc @paulproteus, @zarvox

Update Sandstorm Vagrantfile.

---

packages/rocketchat-theme/assets/stylesheets/rtl.less

The `base.less` got change in https://github.com/RocketChat/Rocket.Chat/commit/f66d268b1f025bb406d061099106f5f8dd509eb9#diff-c4023c19e13c406c96de4b47e55a08acL2988 but the changes were not reflected on `rtl.less`

Show all - RTL fix

---

packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-theme/assets/stylesheets/rtl.less

1- `base.less` fix for Code-mirror not showing in full-screen when screen is smaller than 780px
2- `rtl.less` RTL related fixes for Code-mirror and other stuff

Fixing issues related mainly to Code-mirror and RTL

---

server/restapi/restapi.coffee

Adds a REST API method for listing online users in a room. Useful to show room activity on external sites. Example:
```
curl http://localhost:3000/api/rooms/GENERAL/online
{
"status": "success",
"online": [
"test",
"admin"
]
}
```

Add REST API method to list online users in a room

---

packages/rocketchat-ui-message/message/popup/messagePopup.coffee

Closes #2675
Message popups are invoked in chat window, when selecting channel suggestions, emoji, and more.
Before:
- suggestion is moved up/down on keyup
- long holding does nothing
Now:
- suggestion moves on keydown, which feels much more natural, as it fits behaviour from other parts of OS
- long holding cycles through all options
Also I gave keys names instead of only numbers as I tried to make sense of the code.

Changed arrow keybinding in message popups

---

packages/rocketchat-emojione/emojiPicker.html
packages/rocketchat-emojione/emojiPicker.js
packages/rocketchat-emojione/emojiPicker.less

The header was still there in a title, visible on mouse hover. However some people are very impatient and this change helps them understand which category are they currently viewing.
If you have suggestions about the size or appearance of the header, let them sound here.

added emoji category header in emoji picker

---

packages/rocketchat-authorization/server/startup.coffee
packages/rocketchat-integrations/client/startup.coffee
packages/rocketchat-integrations/client/views/integrations.coffee
packages/rocketchat-integrations/client/views/integrationsIncoming.coffee
packages/rocketchat-integrations/client/views/integrationsNew.coffee
packages/rocketchat-integrations/client/views/integrationsOutgoing.coffee
packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.coffee
packages/rocketchat-integrations/server/methods/incoming/deleteIncomingIntegration.coffee
packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.coffee
packages/rocketchat-integrations/server/methods/outgoing/addOutgoingIntegration.coffee
packages/rocketchat-integrations/server/methods/outgoing/deleteOutgoingIntegration.coffee
packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee
packages/rocketchat-integrations/server/publications/integrations.coffee

Closes #2900 
A new permission is added 'manage-own-integrations'.
The new permission, if present without 'manage-integrations', grants
the user access to add integrations, but only to view, modify or delete their own.
This permission is given to the 'bot' role , which has 'manage-integrations'
removed from it.

Feature to add permission for user to manage their own integrations only

---

packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui-message/message/messageBox.html

refs #2755 <-- addresses last comment in that issue, does not address the initial request
Adds KaTeX formatting tip under message entry field. Clicking on \[KaTeX\] in the formatting tip opens KaTeX docs in new tab.

Katex formatting tip

---

packages/rocketchat-highlight/highlight.coffee

Closes #3035 
When posting the following text:
it will now yield:
The code will check what languages are supported, and if it's not in the list of supported language, it will get HighlightJS to attempt to guess the language.

Automatic language detect on code blocks

---

packages/rocketchat-markdown/markdown.coffee

Add `\S` for non latin chars.
`[ ​\u00a0\u1680​\u180e\u2000​-\u200a​\u2028\u2029\u202f\u205f​\u3000\ufeff]` is similar `\s`, but without `\f\n\r\t\v`.
See also: [Regular Expressions - JavaScript | MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions)

Fix for markdown heading of non Latin characters

---

packages/rocketchat-highlight/highlight.coffee

Closes #3086 
Using the same example:
The message posted will now show as such:

Fix code highlight on code that contains delimiter

---

packages/rocketchat-ui-message/message/messageBox.coffee

Katex help as well as multiple line help was not being shown
because of a typo and a missing function.

fix message composing help

---

packages/rocketchat-lib/client/MessageAction.coffee
packages/rocketchat-ui/lib/chatMessages.coffee
packages/rocketchat-ui/lib/textarea-cursor/set-cursor-position.js
packages/rocketchat-ui/package.js

(Similarly for switching to next message)

New message editing features

---

packages/rocketchat-lib/client/MessageAction.coffee
packages/rocketchat-message-attachments/client/messageAttachment.coffee
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.less
packages/rocketchat-message-pin/server/pinMessage.coffee
packages/rocketchat-oembed/server/jumpToMessage.js

before/after:
Pressing the 'quote' button now inserts a permalink into the text box , which in turn shows the original message when posted.
So it basically just inserts `[ ](https://your.chat.site/channel/general?msg=msg_id)` instead of copying the message entirely.

Improves message quoting

---

packages/rocketchat-ui/lib/chatMessages.coffee

ALT+UP/DOWN sticks to edges when switching messages to allow easier navigation between messages:

Easier whole message navigation

---

packages/rocketchat-lib/client/MessageAction.coffee
packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui/lib/chatMessages.coffee

Closes https://github.com/RocketChat/Rocket.Chat/issues/3037
The issue was that box attempted to resize before it was cleared. I added a callback that is called after `input.val = ''` which fixes it.
The other issue was missing `input.updateAutogrow()` call

Message box resizes properly if sent via click event

---

packages/rocketchat-importer-slack/server.coffee

Fixes an issue reported in the slack-import channel on the demo server. If someone imported a slack export with 0.30 and try again with this change, they will get duplicate messages.

Add the channel id to the _id property of the messages

---

packages/rocketchat-importer-slack/server.coffee

This fixes an issue where someone already has a user account on the Rocket.Chat server that is not the same as in the import.

Fix 'username-already-in-use' on Slack Imports

---

packages/rocketchat-highlight/highlight.coffee

The new behavior only accepts starting a multiline code block at the beggining of the line (but still accepts spaces before starting \`\`\`)
I've sent the following messages:
And get this results (added a `hover` style between message to see clearly they are different messages):

Fix multiline code when there is text after closing ```

---

packages/rocketchat-ui/lib/RoomHistoryManager.coffee

When lots of unread messages appear and you click "Jump to first unread"...
The channel is highlighted and clicking the jump take you up to the first unread and unhighlights the channel. 
However it takes 3 seconds to unhighlight the channel. I thought this was a slow server issue but it turned out to be deliberate timer. I lowered the timer to 0.5 seconds so there is still time for your eye to travel, but it doesn't come across as a clunky application.

Lower highlight timeout.

---

packages/rocketchat-lib/client/TabBar.coffee
packages/rocketchat-theme/assets/stylesheets/base.less

Closes #1297
When clicking a tab bar button, it will cancel the animation if it is still animating. This is instead of waiting for the animation to finish before being able to close the sidebar.

Right sidebar animation cancelled on tab button clicked

---

packages/rocketchat-lib/client/MessageAction.coffee

When quoting a message, the URL that was being posted looked something like `http://httpsyourdomain.meteor.local/channel/general?msg=xxx` so it would not show the quoted message

fix URL for cordova when quoting a message

---

packages/rocketchat-theme/assets/stylesheets/base.less

Closes #1533
No need to have top and bottom padding when you have defined a height and line-heigt to vertically center the text.
**FireFox before**
**FireFox after**
**Chrome after** (no impact)

Fix text clipping in spotlight input

---

packages/rocketchat-otr/client/rocketchat.otr.room.js

If you receive a OTR request from another user while you are currently writing or clicking in Rocket.Chat, the window gets closed accidentally. 
This change keeps the window open until you click on accept or deny.

Do not close request window by mistake

---

packages/rocketchat-integrations/server/methods/outgoing/addOutgoingIntegration.coffee
packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee

Fixes an issue when adding an outgoing integration without providing a channel.

Fix outgoing integrations erroring out when a channel isn't provided

---

packages/rocketchat-lib/i18n/de.i18n.json
packages/rocketchat-lib/i18n/en.i18n.json

… At least for `de` and `en` language files.
I don’t know how you handle translations. Feel free to close the PR if it doesn’t fit your workflow.
**Before:**
**After:**

Add missing i18n properties

---

packages/rocketchat-cas/cas_client.js

Closes #3200
Cordova InAppBrowser doesn't have the "closed" property that is checked in the "checkPopupOpen" interval, so that interval immediately fires and fails to authenticate (since the user hasn't finished logging in inside the popup). This checks if we're in Cordova, then uses InAppBrowser events to check the status of the popup and act accordingly.
Needs testing in iOS before merging.

Fix CAS in Android Cordova

---

server/methods/getRoomIdByNameOrId.coffee

```
Exception while invoking method 'getRoomIdByNameOrId' TypeError: Cannot read property 'usernames' of undefined
```

Avoid exception if room not found

---

packages/rocketchat-lib/client/MessageAction.coffee
packages/rocketchat-mentions-flextab/client/actionButton.coffee
packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.coffee
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.less
packages/rocketchat-message-pin/client/actionButton.coffee
packages/rocketchat-message-pin/client/views/pinnedMessages.coffee
packages/rocketchat-message-pin/server/pinMessage.coffee
packages/rocketchat-message-star/client/actionButton.coffee
packages/rocketchat-message-star/client/views/starredMessages.coffee
packages/rocketchat-oembed/server/jumpToMessage.js
packages/rocketchat-ui-flextab/flex-tab/tabs/messageSearch.coffee
packages/rocketchat-ui-message/message/message.coffee
packages/rocketchat-ui-message/message/message.html
packages/rocketchat-ui/views/app/room.coffee

Closes #3278
* Fixes timestamp being incorrect when quoting a message
* Hide message actions dropdown when clicking the "quote message" button
* Make the timestamp from a quoted message clickable. When clicked it goes to the message.

Improvements to message quoting

---

packages/rocketchat-version/plugin/compile-version.coffee

Fixed the spelling from memmory to memory

Fix spelling on /api/info

---

packages/rocketchat-lib/server/startup/settings.coffee

Adds settings UI for bad word filter added via #2991 / #2940

Add bad word filter to settings UI

---

packages/rocketchat-katex/katex.coffee

KaTeX error messages are currently not being escaped. Sending a message containing the string `\( \/<s>test</s> \)` for instance gets us the following error message:
I simply added an `s.escapeHTML` instruction so the error message is properly displayed:

Escape KaTeX error messages

---

packages/rocketchat-lib/i18n/ca.i18n.json
packages/rocketchat-lib/i18n/es.i18n.json

I think the pull request is clear
this is an example of other translation that did it correctly:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/i18n/de.i18n.json#L539

fixes language_version on catalan and spanish translation

---

packages/rocketchat-lib/i18n/en.i18n.json

this patch adds the error message to be displayed when trying to create an already existing channel. It is referenced [here](https://github.com/RocketChat/Rocket.Chat/blob/ffef53e5235a9f932f48d611eb7498799fce485f/packages/rocketchat-ui-sidenav/side-nav/createChannelFlex.html#L40), but never defined in en.i18n.json.

add error message for duplicate channel creation

---

packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee

Closes #3571
rather than breaking out of the loop after processing the 11th slash command, we will process all of the slash commands, sort them alphabetically, then return the top 11

Fixes #3571: sort slash commands before filtering

---

packages/rocketchat-videobridge/server/settings.js

Time and again , the direct mention of "Jitsi" , either in watermark or settings or release notes, causes our user base to freak out and enter long drawn discussions of how video over the web should be accomplished.    
With no disrespect to our FOSS partner, we need to start calling this a Rocket.Chat Group VideoChat feature - powered by Jitsi to ease the fear factor.

Rename Video Chat settings group

---

packages/rocketchat-api/server/routes.coffee
packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
server/methods/addAllUserToRoom.js

Rest API method to add all existing users to a Channel

REST API Add all users to room

---

packages/rocketchat-custom-oauth/custom_oauth_server.coffee

Update for Dataporten closing #3580

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-videobridge/client/views/videoFlexTab.js
packages/rocketchat-videobridge/server/settings.js

adds new setting to be able to set the screenshare extension for jitsi:

Added Chrome Extension setting for jitsi integration

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-ui/lib/chatMessages.coffee

Closes #3697
If a user types an invalid slash command, we'll respond from `rocketbot` letting the user know that the command was invalid (rather than just calling `sendMessage` for the invalid slash command).

don't consider invalid commands to be messages

---

packages/rocketchat-otr/client/rocketchat.otr.js
packages/rocketchat-webrtc/WebRTCClass.coffee

This change wraps the `Notifications.onUser` subscription for WebRTC messages in an autorun, similar to how it is done elsewhere in the Rocket.chat codebase. It seems that Meteor.userId() takes a while to be populated on Sandstorm, so this subscription would never get setup correctly.
Also grep'ed the codebase and found another case of `Notifications.onUser` being called on startup without an autorun.

Fix sandstorm WebRTC

---

packages/rocketchat-ui-sidenav/side-nav/listChannelsFlex.coffee

1. Set `Merge private groups with channels` to `false`
2. Click `More channels...`
3. Set sort mode to `Name`, but not working
See also: [listCombinedFlex.coffee](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-sidenav/side-nav/listCombinedFlex.coffee#L110)
`@channelType.get()` to `'public'`

Bugfix: Sort channels list

---

.meteor/packages
.meteor/versions
packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui-message/message/messageBox.html
packages/rocketchat-ui-vrecord/client/VRecDialog.coffee
packages/rocketchat-ui-vrecord/client/vrecord.coffee
packages/rocketchat-ui-vrecord/client/vrecord.html
packages/rocketchat-ui-vrecord/client/vrecord.less
packages/rocketchat-ui-vrecord/loadStylesheet.coffee
packages/rocketchat-ui-vrecord/package.js
packages/rocketchat-ui-vrecord/server/settings.coffee
packages/rocketchat-ui/lib/fileUpload.coffee
packages/rocketchat-ui/lib/recorderjs/videoRecorder.coffee
packages/rocketchat-ui/package.js

The following pr adds the possibility to record a video from the webcam and upload it, just like it is currently possible for audio messages.
This patch adds a new button in the message box (visible only if the relevant setting is checked in the preferences) which opens a popup window with the webcam preview and allows to record and upload the video.
After this, the usual file upload dialog is showed (the file upload settings must be set to accept the video/webm mime type) and the possibility to preview the recorded video has been added.
Please let me know what do you think and if any change is needed in the code.

add on the fly video recording and uploading

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-lib/i18n/ja.i18n.json
packages/rocketchat-lib/server/methods/sendMessage.coffee
packages/rocketchat-lib/server/startup/settings.coffee

Related #1209
I think this solution is not perfect. However, this is easy and low cost.
I focused only to now and future messages. A message's alias not changed if a user has changed the name. But I thought that was okay anyway.
EDIT:
Add settings for this feature.

Set user's name to alias in message

---

packages/rocketchat-ui-account/account/accountProfile.coffee
server/methods/saveUserProfile.coffee

In my use case, allow only changing name.
I think unnecessary that re-enter password in this case.

Only require a password if change email or password in user profile

---

.meteor/versions

Closes #3055
This update to accounts-sandstorm fixes a bug on old versions of IceWeasel.
Or, at least, it should. I haven't personally attempted to build Rocket.Chat with this change.

Update accounts-sandstorm to 0.4.1

---

packages/rocketchat-lib/i18n/fr.i18n.json

Broken link due to long useless text.
Now fixed :

Fix "Show_only_online" link bug in french

---

packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui/lib/recorderjs/videoRecorder.coffee

I found some little problems with the new feature added with pullreq #3550:
- if the video button is disabled, it is shown anyway when typing a text message
- if no camera is found the cancel button in the video preview dialog raises an exception and the window is not closed
- a small typo to disable the video button if the relevant mime type is not found in the upload file preference
this small patch should fix them

Videomsg fixes

---

packages/rocketchat-slackbridge/slackbridge.js

The method `setUserActiveStatus` requires admin permission (`edit-other-user-active-status`) but slackbridge was calling it as a normal user.
So I'm doing the same stuff `setUserActiveStatus` does without calling it.
I'm also changing the logic to inactive the user even if he hasn't a real name.

Fix slackbridge calling setUserActiveStatus as normal user

---

packages/rocketchat-lib/server/models/Users.coffee
packages/rocketchat-ui-admin/admin/rooms/adminRooms.coffee
packages/rocketchat-ui-admin/admin/users/adminUsers.coffee
server/publications/filteredUsers.coffee
server/publications/fullUserData.coffee

Closes #3849 
Fix multiple errors thrown in console, and issues when searching for users and rooms with special regex characters such as `[`, including one error that appears to be thrown infinitely in the console.

Fix multiple issues when searching for users and rooms

---

packages/rocketchat-authorization/server/functions/removeUserFromRoles.coffee

Closes #3603 
it seems that the "invalid role" error message was introduced with this commit here:
https://github.com/RocketChat/Rocket.Chat/commit/eaf025ec372ea52121d702aeba4432d5901cc7c2#diff-f3c90a3a07547aae97a0932a692ed32cR11
and then fixed here:
https://github.com/RocketChat/Rocket.Chat/commit/d156abdc295094b8377ce616485a198dabde8291#diff-53bebdff2367150c99d8735019545906R11
but it seems that it was only fixed for the method ```addUserRoles``` and not also in ```removeUserFromRoles```
The attached pullreq should fix the problem.

fix invalid role error msg when removing user from room

---

packages/rocketchat-integrations/server/triggers.coffee

This pull request includes the fields 'alias' and 'bot' for outgoing webhooks. We needed this in our environment to make sure we did not echo messages from Rocket.Chat to Slack and back again (incoming messages from Slack are alias-tagged; refer to #3804).

Include alias and bot values in outgoing webhook.

---

packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.less

On JIRA the default icons are svgs. When using custom messages with attachments the `author-image` appears in the middle of the chat window with a size of 16x16 because of the `max-height` restriction. By setting `max-width` as well it appears on the left, where it should.
Also changed attachment fields width so they are just the size of the item put in the field, with a margin to add some space between. It also allows the items to wrap onto a new line if they don't fit on the screen.
Before: (small `author_icon` in middle of the screen & second field `User` in middle)
After: (icon on left & `User` field closer (allows for more fields to be put next to each other)
You can then choose to have a field go on a new line by specifying `short: false` as you could before.

Set max width on author icon

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-slackbridge/settings.js
packages/rocketchat-slackbridge/slackbridge.js

In our setup, we use an outgoing webhook to copy messages from Rocket.Chat to Slack. Unfortunately, in combination with SlackBridge, messages copied to Slack this way are copied back again to Rocket.Chat. This change adds a configuration option to prevent some bots' messages from propagating to Rocket.Chat; we use this option to pick out messages from Slack that originated from Rocket.Chat and ignore them.

Add an option to SlackBridge to exclude some bots messages from propagating

---

packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.coffee
packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.html

Closes #3847 
Remove the admin controls from the user display in channels, private groups and private messages. Make it so that it is only possible to edit, remove, make admin, and deactivate a user from the administration panel.
Before:
After:

Hide user admin controls except for in admin panel

---

packages/rocketchat-slackbridge/slackbridge.js

I noticed that bot messages were not propagated through SlackBridge. This is due to the fact that the processSubtypedMessage function did not return the crafted mgsObj when the subtype was a bot_message. As a result, saveMessage ignored messages that originated from bots.

Let bot messages propagate through SlackBridge again.

---

client/startup/startup.coffee

If Rocket.Chat is running in subfolder environment(ex: `ROOT_URL` is set to `https://domain/chat`), i18n is not working.
In spite of `ROOT_URL` is set to `https://domain/chat`, TAPi18n fetches `/tap-i18n/*.json`.
It should fetch `/chat/tap-i18n/*.json`.
Then, 404 error has occurred.
(this screenshot is produced with `ROOT_URL=http://localhost:3000/test meteor`)
If `TAPi18n.conf.cdn_path` or `TAPi18n.conf.i18n_files_route` is not set, TAPi18n fetches `/tap-i18n` (maps to packages/rocketchat-lib/i18n directory).
Please review. Is this correct implementation?

Fix i18n in subfolder environment

---

packages/rocketchat-channel-settings/client/views/channelSettings.coffee
packages/rocketchat-channel-settings/client/views/channelSettings.html

Closes #1578 
(already closed...)
I copied implementations from admin's' room info tab to general room's right tab can access non admin users.
This implementation allows deleting room to user who have `delete-*` permission.
If you want to enable this user, you need to add these permissions to owner or user.
I think there are no owners in direct channel. We have to add `delete-d` to **user**.

Allow owner to delete the room

---

packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui/lib/chatMessages.coffee

Message box does not handle well text consisting of both left-to-right and right-to-left parts. (Arch linux, Chrome version 51.0.2704.84 (Official Build) (64-bit))
Here is the behavior I experience when clicking only the left arrow:
Notice the skip over the space in the middle and the jump to the start right before the end.
After:
It seems to be a bug with how chrome handles `dir="auto"` in textareas (Firefox seems better, but not perfect. Other browsers might have problems too, I did not test).
This fix explicitly sets `dir="ltr"` or `dir="rtl"` depending on the input.
The problem I see with this fix is that now the entire message has the same direction. Ideally each line could have its own direction, but I couldn't a better solution.

Message box changes direction explicitly upon input change

---

.meteor/packages
.meteor/versions
.sandstorm/sandstorm-pkgdef.capnp
.sandstorm/setup.sh
packages/rocketchat-lib/server/functions/sendMessage.coffee
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-lib/server/methods/sendMessage.coffee
packages/rocketchat-sandstorm/package.js
packages/rocketchat-sandstorm/server/events.js
packages/rocketchat-ui/lib/notification.coffee

Sandstorm recently grew new mechanisms for notifications (see https://github.com/sandstorm-io/sandstorm/pull/2174). This PR disables normal desktop notifications under Sandstorm and replaces them with the new Sandstorm notification system. I tried to be as non-invasive as possible, with the bulk of the custom code going in a new package named `rocketchat-sandstorm`.
I did end up editing rocketchat-lib/sendMessage to include the sandstorm session id. The only other invasive change was in rocketchat-lib/sendNotificationsOnMessage, where I thought it made the most sense to re-use the current notification logic. The new method `RocketChat.Sandstorm.notify` is a no-op under non-Sandstorm environments.

Add Sandstorm activity/notification events

---

packages/rocketchat-ui-admin/admin/rooms/adminRooms.html

In Admin Rooms page, room type filter doesn't have label.
I want to click text `Channels`, `Direct Messages`, `Private Groups`.

add label tag for checkbox in adminRooms room type filter

---

packages/rocketchat-message-attachments/client/messageAttachment.coffee

Attachments were broken under Sandstorm. This commit fixes it, and makes it more clear in the future that attachments need to be handled slightly differently under Sandstorm.

Fix attachments under Sandstorm

---

packages/rocketchat-importer-slack/server.coffee
packages/rocketchat-slackbridge/slackbridge.js
server/startup/migrations/v056.js

Slack importer adds a `.` (dot) on the message _id which is causing problems because an HTML element cannot have a dot on the `id` property.

Remove dot from message _id on imported messages

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-oembed/client/baseWidget.coffee
packages/rocketchat-oembed/client/oembedSandstormGrain.coffee
packages/rocketchat-oembed/client/oembedSandstormGrain.html
packages/rocketchat-oembed/package.js
packages/rocketchat-oembed/server/server.coffee
packages/rocketchat-sandstorm/client/powerboxListener.js
packages/rocketchat-sandstorm/package.js
packages/rocketchat-sandstorm/server/events.js
packages/rocketchat-sandstorm/server/lib.js
packages/rocketchat-sandstorm/server/powerbox.js
packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui-message/message/messageBox.html

This adds support for Sandstorm powerbox sharing. What this means is you can share other grains quickly and easily with everyone else in your Rocket.chat by clicking the "plus" icon next to the attachment icon. See:
Or go to https://oasis.sandstorm.io/shared/8WwgH63Tie4VzBLp0eP2KsRX7d7obE1A-AUWL3yCD2E to see it in action.

Add sandstorm powerbox sharing

---

client/startup/defaultRoomTypes.coffee
packages/rocketchat-authorization/server/functions/hasPermission.coffee
server/startup/roomPublishes.coffee

Allow guest users to view joined direct rooms

---

packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.coffee

Closes #3953
Change user time to obey the system configured time format.

Add time formatting on user time.

---

packages/rocketchat-markdown/markdown.coffee

The previous `[text](URI)` regex stopped parsing at the first close parenthesis character inside the URI. This update fixes that.

Tweaked markdown regex for [text](URI) to ignore close parentheses

---

packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-theme/assets/stylesheets/rtl.less
packages/rocketchat-ui-message/message/messageBox.coffee
packages/rocketchat-ui-message/message/messageBox.html

Change the message input buttons layout

---

packages/rocketchat-livechat/app/client/stylesheets/main.less
packages/rocketchat-livechat/app/client/views/message.html
packages/rocketchat-livechat/app/i18n/en.i18n.json
packages/rocketchat-livechat/app/i18n/pt.i18n.json
packages/rocketchat-livechat/server/lib/Livechat.js

It's not the ideal solution, but it looks better than we have now.
Agent view | Guest view
---------------|------------
Agent view | Guest view
---------------|------------

Show guest name as message alias

---

packages/rocketchat-lib/server/models/Messages.coffee
packages/rocketchat-message-pin/server/pinMessage.coffee
packages/rocketchat-slackbridge/slackbridge.js

Closes #4032
With this PR, messages are pinned by checking their pin status, instead of looking for a "someone has pinned a message" message type. 
Also, the "someone has pinned a message" is now sent over to rocket.chat with the correct timestamp.

Improvements to pinned items

---

packages/rocketchat-lib/server/functions/sendMessage.coffee
packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
packages/rocketchat-lib/server/methods/sendMessage.coffee

@engelgabriel suggested ts is checked before sending notification; also thinks ts should not be sent by the client

Check timestamp before notifying users

---

packages/rocketchat-file-upload/server/methods/sendFileMessage.js
packages/rocketchat-lib/i18n/en.i18n.json

Closes #3944
Moves "File Uploaded" text into i18n so that it can be translated into other languages.
@Molle500 :wink:

Added File Uploaded text on attachments to i18n

---

packages/rocketchat-lib/i18n/en.i18n.json
packages/rocketchat-mapview/client/mapview.coffee

This is a small bugfix for when an administrator disables the mapview sharing, but there are still messages in a channel that require location rendering.
Previously, it would display a blank, empty message, post-pull these messages will show a link to google maps with the coordinates stored in msg.location.
Enabled, before/after
Disabled, Before
After

Handle shared locations better when new shares are disabled

---

packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-ui/lib/notification.coffee

Closes #3517
If multiple tabs of RocketChat are open, the user's screen was spammed with multiple notifications of the same message. This PR fixes this issue.
Also, now the notification is closed immediately after the user clicks on it.

Fix multiple notifications (closes #3517)

---

packages/rocketchat-ldap/server/ldap.js
packages/rocketchat-ldap/server/loginHandler.js
packages/rocketchat-ldap/server/settings.js
packages/rocketchat-ldap/server/sync.js
packages/rocketchat-lib/i18n/en.i18n.json

@RocketChat/core I would like to add LDAP import option (create users during sync) so users can mentioned and invite other users to channels if their have not logged yet.
I think it's important feature because it boosts service introduction. Users does not need to invite each other via email or other way and wait until they make a first login to invite them to channel or make a mention.
Please note I had to increase LDAP timeout because LDAP ldap search thought group of 300 users can take about 2 minutes.

Added option to populate Rocket Chat with LDAP users (import them)

---

.sandstorm/sandstorm-pkgdef.capnp
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-oembed/client/oembedSandstormGrain.coffee
packages/rocketchat-oembed/client/oembedSandstormGrain.html
packages/rocketchat-sandstorm/server/events.js
packages/rocketchat-sandstorm/server/powerbox.js

Fixes some minor issues with Sandstorm notifications:
* Sometimes DMs wouldn't trigger a notification
* Workaround an occasional bug in Sandstorm's supervisor when restoring identity capabilities
* Fix some wording for event types
* Offer grains with a title now

Various fixes to Sandstorm notifications

---

packages/rocketchat-gitlab/common.coffee

Closes #3987 
This pull request adds the default scope for gitlab. With the merge request for #3837 it broke gitlab oauth authentication.
I have not been able to test this, as we only have one production instance. I am hoping over the next few days I can standup a development rocket chat instance to verify.
Gitlab currently only supports a single oauth scope, api. There is work being done to allow for custom scopes but it has not been merged yet.

Set gitlabs scope to 'api', the only support scope.

---

packages/rocketchat-lib/server/models/Users.coffee

Closes #3985
If a user was deactivated, they shouldn't be considered when trying to send them offline emails.

Don't send offline emails to users who aren't active

---

packages/rocketchat-lib/server/methods/insertOrUpdateUser.coffee

Closes #4131
There was a check on the `update` part of `insertOrUpdateUser` which was checking, incorrectly, if the user being updated wasn't admin and if they weren't then the update wasn't allowed. Since the `update` part of that method doesn't actually handle roles I removed that check.

Don't Check for Last Admin on Update

---

packages/rocketchat-oembed/client/oembedSandstormGrain.html
packages/rocketchat-theme/assets/stylesheets/base.less

Remove the "Click to open grain" text and make the title look like a link.

Tweak SandstormOembed styling/format

---

packages/meteor-accounts-saml/saml_server.js

Closes #4177 
If "Generate username" in the SAML settings is switched off and the SAML IdP provides a username, use it.

Accept username from SAML response

---

packages/rocketchat-lib/package.js

Fix this error:
```
Exception in setTimeout callback: ReferenceError: CustomOAuth is not defined
at packages/rocketchat_lib/server/startup/oAuthServicesUpdate.coffee:40:10
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/meteor/timers.js:6:1
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

Fix error with CustomOAuth on startup

---

packages/rocketchat-lib/server/methods/insertOrUpdateUser.coffee

The purpose of this PR is to address a problem (seemingly a self-XSS issue, so not exploitable to attack other users as far as I know) where Rocket.Chat's username prompt can be abused to show HTML. This HTML can contain Javascript, per the following screenshots:
Note that I haven't tested this yet -- it might be missing a `require()` somewhere -- but it should be an adequate fix. I'm submitting it for feedback and to have Travis-CI run its tests. :)

HTML-escape user data when storing in Meteor Error

---

packages/rocketchat-markdown/markdown.coffee

Closes #3432
Markdown links such as `[Rocket.Chat](https://demo.rocket.chat/channel/meteor)` that point to the server URL should not open in  a new tab (_blank).

Markdown url links that point to server url should not open in blank

---

packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

Closes #4270
fixes the mobile notification preference not working

mobile notification fix

---

packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less

@rodrigok the change we discussed in relation to #4317
Haven't hovered over message window for a few seconds, bar is gone.
Mouse had just been in the message area:

Auto hide scrollbars on windows

---

.sandstorm/build.sh
.sandstorm/setup.sh

Rocket.Chat should now build properly for Sandstorm with this change. Tested working locally. Make sure to destroy your old box (`vagrant-spk destroy` then `vagrant-spk up`), since I changed setup.sh

Sandstorm: Update meteor-spk for Meteor 1.4

---

packages/rocketchat-crowd/server/crowd.js
packages/rocketchat-crowd/server/settings.js
packages/rocketchat-i18n/i18n/en.i18n.json

- Add reject unauthorized setting for crowd login to allow all ssl certificates (same as LDAP)
- Set password field as a password input to hide entered password

Add reject unauthorized option to crowd login

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
packages/rocketchat-ui/lib/chatMessages.coffee

Closes #3906
This adds a setting that allows unrecognized slash commands to be sent.  So they can be handled by bots if users wish

Added setting to allow the sending of unrecognized slash commands

---

packages/rocketchat-iframe-login/iframe_client.js

Closes #4086
Use `loginToken` instead of `token` when calling `login-with-token`

Allow Iframe login with default tokens

---

packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee

per @engelgabriel 's request
@rodrigok is there any reason to use `_id: '@all'` instead of just `_id: 'all'` ? I removed the `@` in advance.

Remove colon from users autocomplete

---

packages/rocketchat-crowd/server/settings.js
packages/rocketchat-i18n/i18n/en.i18n.json
server/startup/migrations/v062.js

Rename crowd setting to remove space (changing url from `admin/Atlassian%2520Crowd` to `admin/AtlassianCrowd`
I did this in a separate PR as I'm not sure if it requires a db migration or anything?

Rename atlassian crowd url to remove space

---

packages/rocketchat-integrations/server/processWebhookMessage.js

Had a typo in variable name that causes no webhooks to work.

Fix variable name issue from #4437

---

packages/rocketchat-ui-master/master/main.coffee
packages/rocketchat-ui/views/app/room.coffee

- Trigger global event to embedded images
- Do not open a new window if on embedded view mode

Add event to embed images

---

packages/rocketchat-oembed/server/providers.coffee
packages/rocketchat-oembed/server/server.coffee

Fix exception:
```
SyntaxError: Unexpected end of input
at Object.parse (native)
at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_oembed.js:421:24
at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:290:24
at Array.reduce (native)
at Object.RocketChat.callbacks.run (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:285:8)
at Object.OEmbed.getUrlMeta (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_oembed.js:191:31)
at Object.OEmbed.getUrlMetaWithCache (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_oembed.js:206:17)
at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_oembed.js:268:21
at Array.forEach (native)
at OEmbed.RocketUrlParser …
```

Prevent error when parsing oembed meta

---

packages/rocketchat-theme/assets/stylesheets/base.less

It happens depending on translation.. It's happening for portuguese:
Before:
After

Prevent edited messaged breaking line

---

packages/rocketchat-oembed/server/server.coffee

Fix exception:
```
Error: Future resolved more than once
at Object.Future.return (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:261:10)
at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/future.js:349:16)
at runWithEnvironment (/var/www/rocket.chat/bundle/programs/server/packages/meteor.js:1161:24)
at /var/www/rocket.chat/bundle/programs/server/packages/meteor.js:1174:14
at /var/www/rocket.chat/bundle/programs/server/packages/rocketchat_oembed.js:123:12
at runWithEnvironment (/var/www/rocket.chat/bundle/programs/server/packages/meteor.js:1161:24)
```

Fix OEmbed exception on request error

---

packages/rocketchat-ui/lib/recorderjs/videoRecorder.coffee

after using and closing the record video message button in the message box, the camera remains still in use, as indicated by the red icon in the chrome tab.
This happens because in the `stop()` function only the videotracks are stopped, but non the audio tracks.
This fix should solve the issue.

properly stop AV tracks when closing video recording dialog

---

packages/rocketchat-livechat/server/models/Users.js

If an user is created using the admin area, and put on some department, it will receive a livechat even if not logged in.

Fix livechat routing to agents that have never logged in

---

packages/rocketchat-api/server/api.coffee

Since we use `RocketChat.API.v1.unauthorized()` if a permission is not granted (see [here](https://github.com/RocketChat/Rocket.Chat/blob/25ffa1919ddc26939cbd6be5f0985f133d0d0404/packages/rocketchat-api/server/routes.coffee#L80), [here](https://github.com/RocketChat/Rocket.Chat/blob/25ffa1919ddc26939cbd6be5f0985f133d0d0404/packages/rocketchat-api/server/routes.coffee#L96), [here](https://github.com/RocketChat/Rocket.Chat/blob/25ffa1919ddc26939cbd6be5f0985f133d0d0404/packages/rocketchat-api/server/routes.coffee#L132) ), we should use `403 Forbidden` instead of `401 Unauthorized` ( [reference](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error) )
Also returns a pretty JSON =)

Use status code 403 forbidden instead of 401 unauthorized

---

packages/rocketchat-highlight-words/client.coffee

Highlight words and mentions have the same priority.
Highlight words seem to be processed before mentions, and this breaks mentions in certain cases.
If I have my name as a highlight word, mentioning me using `@my name` is incorrectly displayed. Clicking the mention in the message doesn't bring up my profile info.

Decrease the callback priority of highlight words

---

packages/rocketchat-authorization/server/publications/permissions.js
packages/rocketchat-lib/client/lib/cachedCollection.js
packages/rocketchat-lib/server/publications/settings.coffee
server/publications/subscription.coffee

Remove sync methods

---

packages/rocketchat-lib/server/functions/setUsername.coffee

It was giving an error because the use of `Meteor.userId()` outside a Meteor method.
I'm slightly changing rate limiter's behaviour. It was checking previously the user that is calling the `setUsername` function, now it checks for whom the username is being set. 
So, previously: the same user could not set more than one username per minute.
Now the same user can't change the *same* user's username more than once per minute.

Fix setting username from REST API

---

packages/rocketchat-ui/views/app/room.coffee

Closes #4420 
I changed the verification step because only Chrome has the ``items`` array in ``dataTransfer``. Other browsers such Firefox, Safari and IE still doesn't has this ``items`` implementation ([Firefox will in v50](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/items)). I found in [W3C docs](http://w3c.github.io/html/editing.html#events-summary) that only ``drop`` event is readable. Others events like ``dragenter`` are protected.
Chrome is the only browser that populate ``dataTransfer`` with files info, so I removed the count and string verification steps for others browsers. If the user drag and drop a string the ``over`` will appear but will not upload.
I think is just not fare to remove DnD from others browsers just for this verification step. …

fix for DnD files upload in Firefox

---

packages/rocketchat-emoji/emojiParser.js

Closes #2013
A simple line of regex in emojiParser.js to change `&#39;` to ' and then a second line after to change ' back to `&#39;`
The second line might not be needed, as everything seemed to work fine in my demo, but just in case the apostrophe needs to be put back to `&#39;` it is there.
Emjois which use the apostrophe  such as :') now work as expected.

added support for apostrophe emojis

---

packages/rocketchat-ui-master/master/main.coffee

Closes #3761
The `CachedChatSubscription.ready.get()` was not executed some times preventing the reactivity of this code based on Subscriptions load

Do not stuck in login page after logout

---

packages/rocketchat-authorization/client/views/permissionsRole.coffee

The usersInRole counts is sometimes that exceed the limit.

Bugfix: Does not show has more button in role editor

---

packages/rocketchat-theme/assets/stylesheets/base.less

Added transition in ``.main-content`` when open the flexbar.
Before:
After:

ADD transition to main-content

---

packages/rocketchat-ui/views/app/room.coffee

Closes #4420 
Fixes PR #4496
Firefox would still show overlay when dragging text over the main window. This fixes it.

Fix Firefox DnD by checking types of drag event

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-integrations/client/views/integrationsOutgoing.coffee
packages/rocketchat-integrations/client/views/integrationsOutgoing.html
packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee
packages/rocketchat-integrations/server/triggers.coffee

The feature allows an outgoing integration to be configured to post as the user that triggered the integration instead of as a separate bot account, similar to how links and other embedded media are handled. The main benefit is that it allows the triggering user to edit/delete the returned data. For example, giphy can always (even with the rating system) return an inappropriate gif. Right now an admin/moderator must be around the delete the image, it cannot be done by the user that triggered it.
Combined with a groupable integration, this also reduces the amount of noise in the chat window.
Setting:
When the setting is disabled, integrations behave exactly the same as they currently do. This is an opt-in behavior.

Allow outgoing integrations to post as the triggering user

---

.snapcraft/edge/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml

Closes #4432
for some reason imagemagick being installed file uploads end up as 0 byte files.

Switch snap from imagemagick to graphicsmagick

---

packages/rocketchat-ui-login/username/username.coffee

The jQuery selector used to get the username input is not specific. This can lead to some unexpected behavior (e.g when adding babrahams:constellation, which include other inputs)

change username input selector

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-mentions/client.coffee
packages/rocketchat-mentions/server.coffee
packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee

Closes #3283 
This pull request adds a new notification target, `@here`, which only notifies users that are either "online", "away", or "busy", and never sends push notifications.
This is essential for large deployments, especially where users are around the world. When a user uses `@all` it ends up sending notifications to people that are sleeping/not working/etc, making people really unhappy. `@here` is meant for when you need to ping anyone who is available but do not want people going out of their way to login and read/reply.

@here support for only notifying users that are active

---

packages/rocketchat-iframe-login/package.js

The `rocketchat-iframe-login` package uses `Match`, but the `check` package was not added in `package.js`.
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-iframe-login/iframe_client.js#L90

Add check package dependency to the iframe-login package.

---

packages/rocketchat-lib/package.js

The package `rocketchat:lib` is using `session` in `/packages/rocketchat-lib/client/CustomTranslations.js` but it's not declared as a direct dependency.
<pre>
Meteor.autorun(function() {
// Re apply translations if tap language was changed
Session.get(TAPi18n._loaded_lang_session_key);
RocketChat.applyCustomTranslations();
});
</pre>
This commit will add it as a dependency to let apps include `rocketchat:lib` with errors.

Add session as a dependency of rocketchat:lib

---

packages/rocketchat-ui/lib/chatMessages.coffee

This fixes issues with certain slash commands. (`/lennyface`, `/shrug`, `/gimme`, `/tableflip`, `/unflip`, and possibly others)
Before, if you sent a message such as `/gimme` (with no space after the command), your final message would be `༼ つ ◕_◕ ༽つ undefined`

Ensure slash command parameters are defined

---

packages/rocketchat-lib/server/methods/leaveRoom.coffee

Closes #4663
I removed the ability to leave a direct message room by using the /leave command by checking if room type is equal to d in the method leaveRoom to resolve and close issue #4663.

Added room check on leaveRoom to make sure it isn't a direct message

---

packages/rocketchat-logger/client/views/viewLogs.coffee
packages/rocketchat-ui/views/app/room.coffee

Closes #4673
This also adds a threshold when calling `checkIfScrollIsAtBottom`.
Without any threshold, being scrolled up by even a few pixels prevents autoscrolling on new messages.
I'm using 100 pixels as the threshold for the following reason:
I have my Windows 10 mouse scroll settings set to their default values.
If I scroll up one notch in Chrome, the text area is scrolled up 100 pixels.
While scrolled up 100 pixels, the view is still considered to be scrolled all the way down before this pull request.
If I scroll up another notch, then the view is not considered to be scrolled all the way down before this pull request.

Add scroll listener to rooms and admin log viewer

---

packages/rocketchat-oembed/package.js

When running the app in debug mode, at startup it hung at ip-range-check module cause there is a debugger call. This was removed in version 0.0.2, check [here ](https://github.com/Day8/ip-range-check/pull/1)

update ip-range-check to version 0.0.2 to get rid of debugger call

---

packages/rocketchat-message-attachments/client/messageAttachment.coffee
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-oembed/server/jumpToMessage.js

Closes #3855
This adds support for showing attachments in quoted messages or other attachments.
~~The only problem I am aware of is that the collapse button does not work in recursive attachments.~~
~~If I manually do something like `ChatMessage.update({_id: 'Huwgrfjya4NFsQwzE'}, {$set: {"attachments.0.attachments.0.collapsed": true}})` in Chrome's developer console, I can (un)collapse images.~~
~~`injectIndex` needs to set `data.index` to something like `#.attachments.#` (or `#.attachments.#.attachments.#` if there is a third level of attachments)~~
~~The development environment I have access to right now is extremely slow and broken, taking over 20 minutes for even a single change to be compiled, and I don't have that kind of patience to figure out what variables I have access to.~~ …

Add support for attachment recursion

---

.meteor/packages
.meteor/versions
packages/rocketchat-livechat/client/views/app/livechatCurrentChats.html
packages/rocketchat-livechat/server/publications/livechatRooms.js

Added Filter based on From date and To date from Room "ts".
Need a bit of design improvement and the To date currently takes the date as the 00:00 AM
Like if you select 10/14/2016 To 10/15/2016, it searches between 10/14/2016 00:00:00:000 AM To 10/15/2016  00:00:00.000am rather than 10/14/2016 00:00:00:000 AM To 10/15/2016  11:59:59.998pm as that seems more logical thing to do.

Time Range filter from and to in livechat current chat page

---

packages/rocketchat-custom-oauth/custom_oauth_server.coffee

Closes #4757
Hello ! 
I've made an update for the keycloak identity provider (openid) 
The userId is the property `sub` and the username is the property `preferred_username`
I've only add the missing properties 
Thanks !

Keycloak OpenID Custom Provider (#4757)

---

packages/rocketchat-ui-message/message/messageBox.coffee

@RocketChat/core this is a very simple pull request to fix something that was bothering me, the location button only listens for the icon being clicked and this changes it so the entire button area is used to be like the other buttons are.

Make the location button use the full button and not just the icon

---

packages/rocketchat-ui-master/master/main.coffee

If you hit any character-producing key while the swipebox is open, the message input area gains focus when it shouldn't.

Ignore keypress if swipebox is open

---

client/notifications/notification.coffee

When using the embedded mode (`?layout=embedded`) the expected behavior should only notify the user for messages on the current opened room since it has no way to see the list of joined rooms.
With this, Rocket.Chat will only show a desktop notification and play a sound if the message was sent to the opened room and the window has no focus.

Show a desktop notification only for the opened room if on embedded mode

---

packages/rocketchat-i18n/package.js
packages/rocketchat-lib/package.js

When you integrate the `rocketchat-i18n` package by creating a symbolic link to the rocket chat project folder (e.g `rocketchat-i18n -> /Users/User/Documents/meteor/Rocket.Chat/packages/rocketchat-i18n`), the `fs.readdirSync` will fail with unfound directory error.

add some missing dependencies

---

packages/rocketchat-lib/package.js

`rocketchat:lib` is using `rocketchat:authorization` but it's not listed as a dependency in `package.js`.
The problem here is that `rocketchat:authorization` is also using `rocketchat:lib`. The is a cyclic dependency between those two packages, there for the use of `{unordered: true}`.
All packages needs the namespace RocketChat which is defined in `rocketchat:lib`. I think it's best to define a new package `rocketchat:core` to broke many cyclic dependencies between packages. What do you guys think?

list rocketchat:authorization as a dependency of rocketchat:lib

---

packages/rocketchat-ui-sidenav/side-nav/listCombinedFlex.coffee

Closes: #4777
Users with only the create-p permission were not able to click the "create new" button in "all channels" tab

Fixes the create new btn bug

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-importer-slack/server.coffee
packages/rocketchat-importer/client/admin/adminImportPrepare.html
packages/rocketchat-importer/client/admin/adminImportProgress.coffee

Closes #4934 
Closes #4899
Closes #3911
A few other fixes:
* Fixed the file selection screen not looking like the rest of the import page
* Fixed Slack's `@here` not being converted to Rocket.Chat's
* Added reaction importing, Slack's naming of emojis doesn't always match Emoji One's so not all of them get imported.
* Fixed the edit timestamps being lost due to an internal change in Rocket.Chat
* A channel's purpose in Slack is a channel's description in Rocket.Chat
* Added import support for renaming channels

Import fixes

---

packages/meteor-accounts-saml/saml_utils.js

I had issues dealing with Japanese characters which used to get converted to unsafe xml characters. Instead of ascii, utf8 is a much better option.

updated buffer to string conversion using utf8.

---

packages/rocketchat-lib/server/models/_BaseCache.js

This fixes queries that were specifying nested fields like these: `model.find(query, { fields: { name: 1, username: 1, emails: 1, 'settings.preferences.emailNotificationMode': 1 } })`
In the query above the field `settings.preferences.emailNotificationMode` would not be returned.
@rodrigok is this fix ok or should we treat this somewhat different?

Fix picking fields from cache

---

packages/rocketchat-theme/server/server.coffee

@rodrigok
Closes #4818
`WebAppInternals.staticFiles` is [only exposed for testing purposes](https://github.com/meteor/meteor/blob/45b01ba8093ca207fe546a5db26f942cc3c5c188/packages/webapp/webapp_server.js#L528-L529) and does not seem to be suitable for reliably serving content. In particular, the [internal private variable](https://github.com/meteor/meteor/blob/45b01ba8093ca207fe546a5db26f942cc3c5c188/packages/webapp/webapp_server.js#L332) that it aliases can frequently get [cleared](https://github.com/meteor/meteor/blob/45b01ba8093ca207fe546a5db26f942cc3c5c188/packages/webapp/webapp_server.js#L461) in a way that can cause requests to a manually-injected file like "/theme.css" to fail to get served, causing the behavior described in #4818.
This pull request fixes the …

serve theme.css through WebApp.rawConnectHandlers

---

packages/rocketchat-ui-message/message/message.coffee

CSV usernames were broken when using spaces in list (it tried to match the name including the space).

Fix bug with Disable Embed for Users

---

packages/rocketchat-lib/server/functions/setEmail.js

It was giving an error because the use of `Meteor.userId()` outside a Meteor method.
This PR slightly change rate limiter's behaviour. It was checking previously the user that is calling the `setEmail` function, now it checks for whom the email is being set.
The same as previously done on `setUsername` function on #4520

Fix set user's email from REST API

---

packages/rocketchat-ldap/server/ldap.js

Closes #4387
This is the fix I originally attached as a patch to the issue. We've been running this patch for months without problems.

Fix issue #4387, crash when using StartTLS and LDAP

---

packages/rocketchat-theme/assets/stylesheets/base.less
packages/rocketchat-theme/assets/stylesheets/rtl.less
packages/rocketchat-ui-master/master/main.coffee
packages/rocketchat-ui-master/master/main.html
packages/rocketchat-ui/lib/menu.coffee
packages/rocketchat-ui/views/app/burger.coffee
packages/rocketchat-ui/views/app/burger.html

I moved rendering of sidebar, main content and "burger" blocks to new composite layers using `will-change`, which improve performance of open/close animations and overall rendering performance.
I removed some global classes, b/c applying them forces browser to unnecessary layout calculations on child elements. Now it use same method as in swiping (just operate on the numbers directly on selected elements) to open sidebar. Previously go get state of menu, we have to check if some element has an class, right now it's reactive, based on `Session` object and it's used also to set `menu-opened` class to 🍔 element (synchronizing DOM Ready events of few async modules it's kinda tricky, I'm not sure how to handle it).
I changed also a way of animating 🍔  icon, replacing not so …

Improved performance of sidebar rendering. Fixed RTL sidebar opening.

---

packages/rocketchat-sandstorm/client/setPath.js
packages/rocketchat-sandstorm/package.js

Currently if you have a Rocket.Chat grain open in Sandstorm and you refresh the page, you get navigated back to the grain's home screen, because the path of the URL gets lost. This pull request fixes that problem by calling Sandstorm's `setPath()` function to update the parent frame's path. 
Note that the strategy used here, where we hook into `FlowRouter,` has been [successfully used by Wekan](https://github.com/wefork/wekan/blob/cacaa0ee8c8811145df9a888ca5bce3c9178397d/sandstorm.js#L396-L402) for a while now. And note that Rocket.Chat [already depends on flow-router](https://github.com/RocketChat/Rocket.Chat/blob/a68c2dedc6ce10923dfe6ef85c8b2d20fca3df4e/.meteor/packages#L142).

[sandstorm] call setPath on navigation

---

packages/rocketchat-livechat/app/client/lib/_livechat.js

If a livechat room is closed, and then within the widget the guest sends a new message the guest creates a new room, but does not properly subscribe to it. A guest could try multiple times creating many dead livechat rooms.  
The Tracker.autorun stops after one call because of `c.stop` at the end of the function (https://docs.meteor.com/api/tracker.html), so I just removed it

removed stop from autorun

---

packages/rocketchat-message-pin/server/pinMessage.coffee

This allows for much simpler pinning via the meteor methods, which is helpful for any additional clients so they only have to pass the `_id` and `rid` instead of the full message.

Allow simpler pinning/unpinning via the methods, only require _id & rid

---

server/methods/groupsList.js

Right now the `groupsList` method is bugged due to the imposed requirement of the parameter `nameFilter`. I noticed this was broke when I was working on my Minecraft implementation which calls this method.
Note, this method can be done away with once the `experimental` branch gets merged as a result of the addition of the `rooms/get` method.

Fix the nameFilter being required on groupsList, since it isn't

---

packages/rocketchat-lib/client/lib/roomTypes.coffee
packages/rocketchat-lib/startup/defaultRoomTypes.coffee
packages/rocketchat-livechat/roomType.js
packages/rocketchat-ui-sidenav/side-nav/chatRoomItem.coffee
packages/rocketchat-ui/views/app/room.coffee
packages/rocketchat-ui/views/app/spotlight/spotlight.coffee
packages/rocketchat-ui/views/app/spotlight/spotlightTemplate.js

This adds the ability for custom room types to be able to control their own "status".
So it fixes livechat room status not showing properly.

Add status support to room types

---

server/methods/messageSearch.js

Closes #5105 
Fixes typo ("descening") in messageSearch results ordering.

Fix typo in result ordering regex.

---

packages/rocketchat-lib/server/functions/saveUser.js

If you call `user.update` even to set just the user's name, his email will be set to `unverified`. This PR fixes it.

Fix email being unverified when calling user.update

---

packages/rocketchat-ui-message/message/messageBox.coffee

The Sandstorm offer "+" button (added in #3932) does not work in the Cordova app. So let's hide it there.

hide Sandstorm offer button on Cordova

---

packages/rocketchat-channel-settings/client/views/channelSettings.coffee
packages/rocketchat-channel-settings/server/methods/saveRoomSettings.coffee
packages/rocketchat-i18n/i18n/en.i18n.json

Closes #5141 
This prevents users from changing the type of room if they don't have permission to create the other type of room. See #5141 for how to replicate this issue.

Don't allow changing the room type no other permission

---

packages/rocketchat-ui-account/account/accountFlex.html

Fixed an issue in accountFlex.html that was causing all options to be highlighted rather than only the hovered item. 
**Old Styling**
**New Styling**

fixed accountFlex highlight on hover issue

---

packages/rocketchat-livechat/app/client/lib/_livechat.js
packages/rocketchat-livechat/app/client/lib/hooks.js
packages/rocketchat-livechat/app/client/views/livechatWindow.js

Setting it as ready too early can lead to unwanted behavior because not all data is there yet.

Fix livechat setting itself as ready

---

packages/rocketchat-integrations/server/api/api.coffee

Closes [#5113](https://github.com/RocketChat/Rocket.Chat/issues/5113)
It appears that the Incoming Webhooks script accounted the fact that some JSONs might be packed inside a "payload" field, like the following:
```
{
"payload": { actual JSON here }
}
```
and started parsing from inside that field, if it was the case.
However, this solution conflicts with the possibility that this field is not a container for the whole thing, but simply another field, like Crashlytics's payloads:
```
{
"event": "issue_impact_change",
"payload_type": "issue",
"payload": {
"display_id": 123 ,
"title": "Issue Title" ,
"method": "methodName of issue",
"impact_level": 2,
"crashes_count": 54,
"impacted_devices_count": 16,
"url": "http://crashlytics.com/full/url/to/issue"
}
}
```
This resulted …

Fixed crash if a webhook payload had a field named "payload"

---

packages/rocketchat-api/server/v1/misc.js

I was working on a rest api client and noticed the server information wasn't consistent with the other v1 api results.

Make the server information of the api consistant with others

---

packages/rocketchat-channel-settings/client/views/channelSettings.coffee
packages/rocketchat-channel-settings/package.js
packages/rocketchat-channel-settings/server/functions/saveReactWhenReadOnly.js
packages/rocketchat-channel-settings/server/methods/saveRoomSettings.coffee
packages/rocketchat-channel-settings/server/models/Rooms.coffee
packages/rocketchat-channel-settings/server/startup.js
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-reactions/client/init.js
packages/rocketchat-reactions/client/methods/setReaction.js
packages/rocketchat-reactions/setReaction.js
packages/rocketchat-ui-message/message/message.coffee
server/startup/roomPublishes.coffee

Closes #5147 
This adds the ability to configure a room that is read only to allow people to react to messages. The usefulness of this is for servers that have "announcement/news" channels yet they would like to get their communities reactions to the news without spamming the channel with messages.

Add room setting which allows reacting when read only

---

packages/rocketchat-lib/server/models/Users.coffee

This seems to be a weird bug/typo.

Fix unset emails field if none set instead of name field

---

packages/rocketchat-lib/server/methods/sendMessage.coffee

Closes #5119 
Right now we rate limit everyone except for the internal "hubot" bot. With this pull request all of the bot users are now *not* rate limited.

Fix bot users being rate limited

---

packages/rocketchat-livechat/app/client/lib/commands.js
packages/rocketchat-livechat/client/views/app/tabbar/visitorEdit.js
packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.html
packages/rocketchat-livechat/server/lib/Livechat.js
packages/rocketchat-livechat/server/models/Users.js
packages/rocketchat-livechat/server/models/indexes.js
server/startup/migrations/v072.js

Using `emails` field to store livechat visitor's emails is leading to problems because `emails` field has an unique index created by [Meteor Accounts package](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1492).
So I'm moving to another field without the unique index but keeping all functionality.

Migrate livechat visitors' emails field to visitorEmails

---

packages/rocketchat-webrtc/WebRTCClass.coffee

After a user makes 6 consecutive calls, 7th call can't be established. Since the number of hardware contexts provided is only 6, we have to "close AudioContext" after user click the stop-call button.
related error message:
> WebRTCClass.coffee:330
> 
> Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
>     at onSuccessLocal (http://localhost:3000/packages/rocketchat_webrtc.js?hash=d0189ef653b43578dca35032cacb8073032dc160:523:24)
> onSuccessLocal @ WebRTCClass.coffee:330

Fix the over creation of AudioContexts.

---

packages/rocketchat-livechat/server/methods/takeInquiry.js
packages/rocketchat-livechat/server/models/Rooms.js

Livechat guest pool is currently broken on `develop` since we don't have the `username` fields on rooms anymore.

Fix livechat take inquiry after removing username fields from rooms

---

.snapcraft/edge/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml

We were spitting all output in the file, but we've been telling people to check the journal.  Going to use this way, as in the future logs will also be accessible via `snap logs rocketchat-server` and pulls from journal.

Snap print to journal

---

packages/rocketchat-ldap/server/sync.js

Closes #5227
Present implementation of bulk ldap sync doesn't merge existing users with ldap users if they exist. We have a lot of user signing by Google Auth but then we need to standardize them based on LDAP information. This modification makes this work.

Allow to merge users with LDAP on bulk sync

---

packages/rocketchat-ui/lib/recorderjs/audioRecorder.coffee

Same thing with this [pull request](https://github.com/RocketChat/Rocket.Chat/pull/5223). When a user records 6 consecutive audio message, DOMException happens. I added AudioContext's close function.

Fix the over creation of AudioContexts when record audio message.

---

packages/rocketchat-file-upload/server/config/configFileUploadGridFS.js

currently it is not possible to play multimedia files using the html5 player in rocket.chat using Safari because the web server used to serve the files is currently missing support for byte range requests, as documented [here](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6) for iOS.
This patch adds basic support for rfc 7233 making it possible to play multimedia files on that browser too.
I tested this very quickly and it seems to work fine on iOS 9.3.5 and Mac Os X 10.11.5, but please have a thorough look before merging.

Add basic support for rfc 7233

---

packages/rocketchat-webrtc/WebRTCClass.coffee

There is a bug at the [pull request](https://github.com/RocketChat/Rocket.Chat/pull/5223) which i made 6 days ago.
When a user makes a call and opponent refuse it, `close() function undefined` error occurs. If a call is not created, there will be no `window.audioContext`. Sorry about my mistake.

AudioContext can be closed only if it exists.

---

packages/rocketchat-oembed/client/oembedUrlWidget.coffee

Fixes oembed error with ogImage URLs that start with double slash

---

packages/rocketchat-webrtc/WebRTCClass.coffee

Closes #5286
How about set "video: false" as a default? I test a few cases and it works.

Fix screen sharing bug when receiving audio call. issue #5286

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json
packages/rocketchat-livechat/server/methods/startVideoCall.js
packages/rocketchat-videobridge/client/views/videoFlexTab.js
packages/rocketchat-videobridge/server/settings.js

Now, Jitsi URL is composed by: `[jitsi_domain] / RocketChat[room-unique-identifier]`
This PR adds the ability to change the only hard coded part of the URL: `RocketChat`

Add setting to change jitsi URL prefix

---

packages/rocketchat-api/server/v1/users.js
packages/rocketchat-lib/server/functions/saveUser.js

This was causing the rest api to fail when the error, 404, would happen which shouldn't happen.

Fix the gravatar failing when an email isn't a gravatar account

---

package.json
packages/rocketchat-assets/package.js
packages/rocketchat-file-upload/package.js
packages/rocketchat-importer-csv/main.js
packages/rocketchat-importer-csv/server.js
packages/rocketchat-importer-hipchat-enterprise/main.js
packages/rocketchat-importer-hipchat-enterprise/server.js
packages/rocketchat-importer-hipchat/main.coffee
packages/rocketchat-importer-hipchat/server.coffee
packages/rocketchat-importer-slack/main.coffee
packages/rocketchat-importer-slack/server.coffee
packages/rocketchat-importer/.npm/package/npm-shrinkwrap.json
packages/rocketchat-importer/client/admin/adminImportPrepare.coffee
packages/rocketchat-importer/client/admin/adminImportPrepare.html
packages/rocketchat-importer/lib/importTool.coffee
packages/rocketchat-importer/package.js
packages/rocketchat-importer/server/classes/ImporterBase.coffee
packages/rocketchat-importer/server/methods/restartImport.coffee
packages/rocketchat-importer/server/methods/setupImporter.coffee

@RocketChat/core Before now we relied on the operating system/browser to tell us which type of file the user is providing us, now we instead rely on [file signature](https://en.wikipedia.org/wiki/List_of_file_signatures) via the [file-type npm package](https://github.com/sindresorhus/file-type) which was suggested by @whren.
Closes #3050

Fix importer relying on os file type, use file signature instead

---

packages/rocketchat-lib/server/functions/deleteMessage.js
packages/rocketchat-slackbridge/README.md
packages/rocketchat-slackbridge/slackbridge.js

Delete Slack msgs from Slack
Delete Slack msgs from Rocket
Delete Rocket message from Rocket
Delete Rocket msg from Slack
Added the start to a README.md
Added a new Rocket event 'afterDeleteMessage'
Refactoring existing handling of Slack events into smaller single concern methods

Bi-directional message deletes between Rocket and Slack

---

packages/rocketchat-slackbridge/README.md
packages/rocketchat-slackbridge/slackbridge.js

Added the ability to change messages in both Rocket and Slack.
* Edit Slack message in slack: OK
* Edit Rocket message in rocket: OK
* Edit Rocket message in slack: NOT ALLOWED IN SLACK UI
* Edit slack message in rocket: FAIL (updates in Rocket, but doesn't in Slack) - Bot API Token not allowed.

Bi-directional editing of messages

---

packages/rocketchat-lib/server/models/Messages.coffee
packages/rocketchat-reactions/client/methods/setReaction.js
packages/rocketchat-reactions/setReaction.js
packages/rocketchat-slackbridge/README.md
packages/rocketchat-slackbridge/slackbridge.js

Added the ability to react to slack and rocket messages.  Doesn't quite work all the way because Slack sees the reactions as coming from the 'bot'.  I am working w/ the Slack team to figure out some work arounds based on some alternative bot authentication mechanisms.
* AddReact
* slack message in slack: OK
* rocket message in rocket:  BOT in slack
* slack message in rocket: BOT in slack
* rocket message in slack: OK
* RemoveReact
* slack message, reacted in slack, removed in slack: OK
* slack message, reacted in slack, removed in rocket: Removed in Rocket, BOT still in Slack
* rocket message, reacted in rocket, removed in rocket: OK
* rocket message, reacted in rocket, removed in slack: OK

Bi-directional reactions to messages

---

packages/rocketchat-livechat/server/models/Rooms.js
packages/rocketchat-livechat/server/startup.js

Closes #5547
@rodrigok how can we enable the find by index on cache for `t,code` fields?

Stop using cache to find a livechat room by code

---

packages/rocketchat-api/server/v1/groups.js

The Rest API Groups rename method was returning a channel object, when it was supposed to return a group object.

API Groups rename fix

---

packages/rocketchat-authorization/client/lib/ChatPermissions.coffee
packages/rocketchat-lib/client/lib/cachedCollection.js
packages/rocketchat-lib/client/lib/settings.coffee
packages/rocketchat-ui/lib/collections.coffee

Add relation between client cache and user’s token

---

packages/rocketchat-livechat/client/views/app/livechatQueue.html

The page permissions were mistakenly changed, this reverts it to the old permissions.
Maybe a hotfix should be released with this included.

Fix agents not being able to see queue list page

---

packages/rocketchat-ui-master/master/main.coffee
packages/rocketchat-ui/lib/menu.coffee

When you swipe to open sidenav the flex-tab-bar change its position like this:
Now its fixed :)

fix flex-tab-bar position on swipe

---

.meteor/packages
.meteor/versions
packages/rocketchat-lib/lib/getURL.js
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/lib/PushNotification.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

Closes #2812
I had to update the raix:push package to `3.0.3-rc.7` because it [was not included on 3.0.2](https://github.com/RocketChat/Rocket.Chat/issues/2812#issuecomment-232382040)
I'm using the `android-chrome 192x192 (png)` asset as the server icon on the push notification. if someone has an suggest/objection on that, please adivise.
_edit: I've changed to use the 192x192 icon instead of 512x512 after a few tests._
This is how the new notifications should look like:
- Single push notification on a channel:
- Multiple notifications for same channel:
- Single direct message notification:
- Multiple notifications for the direct message:
- Mixed notifications:

Add support to inbox style push notifications for Android

---

packages/rocketchat-ui-master/master/main.coffee

`useIframe` makes method call to `rocketchat-iframe-login` package, which throws if that package is disabled. Resolved with package enabled conditional.

Fix exception in template helper, iframe login

---

packages/rocketchat-api/server/api.js
packages/rocketchat-api/server/settings.js
packages/rocketchat-api/server/v1/im.js
packages/rocketchat-i18n/i18n/en.i18n.json

Adds a setting `API_Enable_Direct_Message_History_EndPoint` which is disabled by default.
The endpoint requires the permission `view-room-administration` to use.
Also, adds the ability for rest api endpoints to have several routes for the same logic. This adds `dm` to all of the current `im` items.
Closes #5492

Allow REST API viewing the messages of others direct messages

---

packages/rocketchat-integrations/server/processWebhookMessage.js

@RocketChat/core Right now the web client lets you send messages to any channels you have joined (aka have a subscription to) whether or not you have permission to view that channel type. This fixes the issue where the rest api `chat.postMessage` wasn't behaving that way as well by checking for a Subscription before we try to join the user to a room.
Closes #5477

Fix chat.postMessage not behaving like the web client

---

packages/rocketchat-importer-slack/server.coffee

@RocketChat/core Slack import no longer logs `missedTypes` when there are none. Also, adds a new message type from Slack.
Closes #5695

Fix Slack Importer incorrectly logging missed types and add missing type

---

packages/rocketchat-livechat/server/hooks/externalMessage.js

Hi, the API call to api.ai wasn't working as they have now a [required field `sessionId`](https://docs.api.ai/docs/query#query-parameters-and-json-fields)  that the codebase was not sending, I just made it send `room._id`. I used `room._id` because the intent there in api.ai needs to follow the whole conversation in order to fill all parameters and produce more accurate responses.

Add missing required sessionId to api.ai call on externalMessage

---

.openshift/rocket-chat-ephemeral.json
.openshift/rocket-chat-persistent.json

* There was a problem with DeploymentConfig that was missing the correct ImageStream (which should be merged in this file)
* Removing the host attribute from route object to let Openshift create a dynamic hostname for Rocket.Chat

Fix Openshift Templates

---

packages/rocketchat-lib/server/functions/setUserAvatar.js

My server logs were being spammed with gravatar fetch errors. I don't think it's worth reporting as an error when gravatar service returns a 404, it just means that email doesn't have a gravatar associated, which is pretty common.

Don’t report gravitar 404 as server error

---

packages/rocketchat-channel-settings/client/views/channelSettings.coffee

Related to #5808
I removed the "Private" button when `room.t` is not `c` or `p` and fixed the representation of this button when the room is private or not.

remove "Private" button for direct messages

---

packages/rocketchat-lib/server/lib/RateLimiter.coffee

When meteor is started with the env var TEST_MODE=true, this will make rocket chat ignore the rate limiters for the username and email changes, allowing to do consecutive tests without running into the `Too Many Requests` error

Remove Rate Limiters For Testing

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/default/helpers/getLoggedInUser.js
packages/rocketchat-api/server/default/info.js
packages/rocketchat-api/server/v1/helpers/getLoggedInUser.js
packages/rocketchat-api/server/v1/misc.js
tests/end-to-end/api/00-miscellaneous.js

Closes #3651 
When hitting /api/info or /api/v1/info, default response to be just version number of the info object. If user has admin role, show entire object.

Fix 3651, update to /api.../info endpoints to be secure and backwards compatible for mobile clients.

---

packages/rocketchat-ui/package.js
packages/rocketchat-ui/views/app/mobileMessageMenu.js

Closes #5963
`mobileMessageMenu` was deleted with the old spotlight.

fix message action menu on cordova

---

packages/rocketchat-theme/client/imports/base.less
packages/rocketchat-ui-admin/admin/admin.coffee

Closes #5965 
I dont know why the reset button is gray in the gif. In the application the button is still red :)

admin: fix reset to default

---

packages/rocketchat-ui-message/message/message.coffee

Closes #5859 
Improves the way that rocket chat verify the date to group messages under the `new day` line
so that the test don’t rely on the current language

The right way to verify the date

---

server/lib/accounts.js

**The bug:**
The first "user" should be made admin. Instead `rocket.cat` becomes the admin in new installs.
**History:**
* This Bug was fixed once in  #1647
* It regressed in https://github.com/RocketChat/Rocket.Chat/commit/6157e7763cb7fb3c0b068c9f67d1144383abda49#diff-80879a72bba8e1d0cb43a26400c2041f
* In a recent commit, the files were moved from coffee to js and the bug got carried over.
**The Fix**
Check `type: user` before making a user admin.

Only a User should become Admin

---

packages/rocketchat-ui/lib/chatMessages.coffee

Closes #5673 
It adds a line break when ctrl, alt or cmd is pressed with enter

Fix ctrl/alt/cmd+enter line break

---

packages/rocketchat-ui-master/master/main.coffee
packages/rocketchat-ui-sidenav/client/toolbar.js

Closes #6031 
When you open toolbar search from Ctrl/CMD + P the sidenav will close on esc, but if you open sidenav and click on toolbar search input ESC will only clear the input.

new behavior to ESC on toolbar search

---

packages/rocketchat-authorization/server/models/Roles.js
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/startup/settings.coffee
server/lib/accounts.js

Default oauth role

---

.eslintignore
.gitignore
packages/rocketchat-livechat/assets/demo.html
packages/rocketchat-livechat/client/views/app/livechatInstallation.js
packages/rocketchat-livechat/package.js
packages/rocketchat-livechat/plugin/build-livechat.js

The minified version is 41% lighter (not gzipped - 4.9KB vs 2.9KB) as you can see on the image below:
But with the additions of https://github.com/RocketChat/Rocket.Chat/pull/6070 it is 71% lighter (not gzipped - 22.3KB vs 6.5KB) as you can see on the image below:
@RocketChat/core how can we deprecate the old (non-minified) file and tell users to use the new minified version? I've added a [comment on the code](https://github.com/RocketChat/Rocket.Chat/pull/6071/files#diff-801b93110abea405d3309407f6e16db0R211) but I know it's not enough =\

Add minified version of livechat widget script

---

packages/rocketchat-livechat/client/views/app/livechatAppearance.js
packages/rocketchat-livechat/package.js
packages/rocketchat-livechat/server/methods/saveAppearance.js
packages/rocketchat-livechat/server/publications/livechatAppearance.js

Closes #5717
Doing this was necessary because a livechat manager could not be an admin, so it would not be able to save some settings and barely see some others.
So I had to everything related to settings management to server side. So I can properly check if the user has the proper access rights and manipulate settings directly on DB.

Fix livechat appearance page by not saving settings directly from client

---

packages/rocketchat-livechat/app/client/views/livechatWindow.html
packages/rocketchat-livechat/app/client/views/livechatWindow.js

Closes #4184
This PR prevents the livechat widget to displayed if there are no online agents and the offline form display setting is set to `false`

Fix livechat widget being displayed when offline

---

packages/rocketchat-livechat/server/models/LivechatExternalMessage.js

Closes #6101
Looks like it's currently needed to call `this._initModel` on client side.

Fix livechat knowledge base by properly initiating it's model

---

packages/rocketchat-lib/server/methods/updateMessage.js

This fixes a weird bug that was preventing a message mentioning `@all` from being updated.

Fix updating a message with @all by copying "u" property

---

packages/rocketchat-ui-master/master/main.coffee

Closes #6037 
When you press any key with photoswipe open, these keys will appear on message-box. This PR fix this behavior.

fix keydown when photoswipe is open

---

packages/rocketchat-ui-sidenav/client/createCombinedFlex.html

In order to fix the issue #5454, I removed the `.error-color` class from the markup. By doing this, I achieved the folowing result:

Remove error-color class when creating new channel. closes #5454

---

packages/rocketchat-message-attachments/client/messageAttachment.html

Closes #6205
Currently rocket chat prompts you to set a description for a file but doesn’t show this description on the actual message. This makes so that if a attachment has a description, it will show on the message.
@karlprieb what do you think?

Show File Description For All Files

---

packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/oauth/google.js
packages/rocketchat-lib/server/oauth/oauth.js

```javascript
Accounts.callLoginMethod({
methodArguments: [{
serviceName: 'google',
accessToken: 'xxx',
refreshToken: 'xxx',
idToken: 'xxx',
expiresIn: 3557,
scope: 'profile'
}],
userCallback: function() {
console.log(arguments);
}
});
```
```JSON
{
"msg": "method",
"method": "login",
"params": [{
"serviceName": "google",
"accessToken": "xxx",
"refreshToken": "xxx",
"idToken": "xxx",
"expiresIn": 3557,
"scope": "profile"
}],
"id": "25"
}
`

Allow login via OAuth access token. Only for Google now

---

packages/rocketchat-ui-message/client/messageBox.coffee

If the administrator turns off preview permission for users, when a user joins a channel, he can't see message history or new messages, until a reload of the page / application.
This is caused by a bug which prevents the handling of such situation from being executed.

fix the problem where user can't see messages (old or new) after joining a channel with preview disabled

---

packages/rocketchat-theme/client/imports/base.less

Fix firefox font smoothing to be consistent with chrome

---

packages/rocketchat-ui-message/client/messageBox.coffee

Closes #6270
Added some screenshots to the issue and waiting feedback.

#6270 Adds datetime to default filename on clipboard uploads

---

packages/rocketchat-custom-sounds/client/lib/CustomSounds.js

Closes #6112 
On Wi-Fi, the chromium browser tries to load the metadata from the mp3 files present on `audio` tags (even without preload).
This `fix` is just a temporary fix until someone with more Cordova experience may do a real fix.

Simple ignores the custom audio from being added

---

.sandstorm/sandstorm-pkgdef.capnp

Closes #6339
Adding environment variable for sandstorm deployments. Set babel_cache_dir to a folder inside sandstorm which is writeable (everything inside /var). This solution is based on the proposal by @graywolf336. After applying this patch, this should not happen anymore inside sandstorm:

Fixing #6339 - Integrations with scripts do not work in sandstorm

---

packages/rocketchat-markdown/markdowncode.coffee

Closes #6311
Adds some improvements to parsing multiline blockquotes, like parsing when inline.
Test cases and result:
```
```blockquote``` with following text
preceding text with inline ```multiline blockquote
second line of block
third line of block```
Starting text:
Second line
```blockquoteo n the third line```
End of text 4th line
preceding```blockquote```following
```

Improvements to multiline codeblock parsing

---

packages/rocketchat-file-upload/server/lib/requests.js
packages/rocketchat-message-attachments/client/messageAttachment.coffee
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-ui-sidenav/client/createCombinedFlex.coffee

Closes issues #1, #2 and #3 from security repo

Security Fixes

---

packages/rocketchat-oembed/server/providers.coffee

Closes #5861
The attribute ```host``` excludes another params (hostname, port, etc....)
Should shorter links like "https://goo.gl/UOAt0Q" be resolved? I think that would be nice.

embed from youtu.be fixed

---

packages/rocketchat-ui-admin/client/adminFlex.coffee

Closes #5722 
sort by translated name instead "key"

sort admin menu by translated name

---

packages/rocketchat-ui-master/client/main.coffee

With this event, people who are using Rocket.Chat as an iframe will be able to know when starting sending commands.

Add startup event for iframe integrations

---

packages/rocketchat-theme/client/imports/base.less
packages/rocketchat-ui-admin/client/users/adminUsers.html

Administrators can't tell which users are deactivated without going through each user. This PR made a small change to make the deactivated users look different (see screenshot below)

Make deactivated users look different in admin user list

---

packages/rocketchat-markdown/markdowncode.coffee

Closes #6273
Bug: 
Problem found: The start of URLs was getting removed from the start of blockquotes. This was caused by the regex parsing `http://url.com` in the same way the single word `http` was, which is unintended as far as I understood.
The feature of highlighting code snippets in blockquotes is still available, and if the user enters the single word http in the first line, it still identifies as a http code block.
The fix changed the `\w` which would parse words (and stop when reaching `:`) to `.` which parses every character (with the following rule for spaces and end of line to determine spaces), this will cause the regex to understand `http` and `perl` as languages but not `http://url.com` nor `perl?`.
Trying to reproduce the bug after the fix:

#6273 Fix http missing from links when starting blockquotes

---

packages/rocketchat-channel-settings-mail-messages/client/lib/startup.coffee
packages/rocketchat-channel-settings/client/lib/ChannelSettings.coffee
packages/rocketchat-channel-settings/client/views/channelSettings.coffee
packages/rocketchat-channel-settings/client/views/channelSettings.html
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/models/Rooms.coffee
packages/rocketchat-ui-admin/client/rooms/adminRoomInfo.coffee
packages/rocketchat-ui-admin/client/rooms/adminRooms.coffee
packages/rocketchat-ui-admin/client/rooms/channelSettingsDefault.js

closes #6403 
For default channels,
- If you are an admin you can change the type, but you need confirm that you will lost the "default"
- If you are the owner a message appears asking you to talk if your admin
I changed this methods to
```RocketChat.ChannelSettings.addOption```
```RocketChat.ChannelSettings.getOptions ```
now you can pass a filter, if you dont will return all options.

Just admins can change a Default Channel to Private (the channel will be a non default channel)

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-login/client/login/form.coffee
server/methods/sendForgotPasswordEmail.js

Related to https://github.com/RocketChat/Rocket.Chat/issues/6229#issuecomment-284205677

Password reset Cleaner text

---

packages/rocketchat-lib/lib/slashCommand.coffee
packages/rocketchat-slashcommands-join/client.coffee
packages/rocketchat-slashcommands-join/server.coffee
packages/rocketchat-ui/client/lib/chatMessages.coffee

Closes #5793
It will works just with public channels.
```javascript 
room = RocketChat.models.Rooms.findOneByNameAndType(channel, 'c') /// <-here
```

Join command

---

.eslintrc
packages/rocketchat-ui/client/lib/esc.js
packages/rocketchat-ui/client/lib/sideNav.coffee
packages/rocketchat-ui/package.js

While creating new channels by clicking + icon, first textbox input element of a rendered form gets focus.
Closes #6247
Closes #6248

focus first textbox element

---

packages/rocketchat-livechat/server/methods/transfer.js

This PR allows livechat managers to transfer chats. Right now, only the active agent is allowed to do that. 
Sometimes, those people forget to forward it and just leave it open and it's easier for the manager to simply forward it to someone else than having to ask the active agent to do it.

Allow livechat managers to transfer chats

---

.eslintrc
client/startup/userSetUtcOffset.js
lib/fileUpload.js
packages/rocketchat-file-upload/server/config/configFileUploadAmazonS3.js
packages/rocketchat-file-upload/server/config/configFileUploadGridFS.js
packages/rocketchat-file-upload/server/lib/requests.js
packages/rocketchat-file-upload/server/methods/getS3FileUrl.js
packages/rocketchat-integrations/client/views/integrationsOutgoing.js
packages/rocketchat-lib/lib/fileUploadRestrictions.js
packages/rocketchat-lib/server/functions/saveUser.js
packages/rocketchat-lib/server/functions/setUserAvatar.js
packages/rocketchat-lib/server/lib/PushNotification.js
packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-lib/server/methods/updateMessage.js
packages/rocketchat-livechat/app/client/views/messages.js
packages/rocketchat-livechat/app/client/views/register.js
packages/rocketchat-message-snippet/server/requests.js
packages/rocketchat-slackbridge/slashcommand/slackbridge_import.server.js
packages/rocketchat-slashcommands-archiveroom/server.js
packages/rocketchat-slashcommands-create/server.js
packages/rocketchat-slashcommands-inviteall/server.js
packages/rocketchat-slashcommands-open/client.js
packages/rocketchat-slashcommands-unarchiveroom/server.js
packages/rocketchat-ui-flextab/client/tabs/userInfo.js
server/lib/cordova.js
server/methods/addAllUserToRoom.js
server/methods/messageSearch.js

Add ESLint rule `one-var`

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js
server/methods/addAllUserToRoom.js

We need to add all active users to a private group or a channel, so we created the new groups.addAll endpoint and added the activeUsersOnly to addAllUsersToRoom.js

Create groups.addAll endpoint and add activeUsersOnly param.

---

packages/rocketchat-ui-message/client/messageBox.coffee
packages/rocketchat-ui-message/client/messageBox.html

Closes #2087
I create a hack that fix the problem, I'm not sure if is necessary yet, but ....
I think [this pull request](https://github.com/RocketChat/Rocket.Chat/pull/6272/)  must be done here to.

Clipboard [Firefox version < 50]

---

packages/rocketchat-ui-sidenav/client/sideNav.js

This fixes the problem where user's option of choosing not combining room list doesn't work. I believe it is caused by the conversion from CoffeeScript to JavaScript.

fix channel merge option of user preferences

---

packages/rocketchat-assets/server/assets.js

Fix typo of the safari pinned tab label

---

packages/rocketchat-oauth2-server-config/oauth/server/oauth2-server.coffee

Added as per part of the spec: https://connect2id.com/products/server/docs/api/userinfo
Ran into an application that needed this on the server to finish the oauth login process. Since its part of the spec, I went ahead and added it.

[New] Added oauth2 userinfo endpoint

---

packages/rocketchat-ui-flextab/client/tabs/membersList.js

UTC offset in members list displays `+1` for UTC offset instead of displaying `(UTC +1)`

[FIX] UTC offset missing UTC text when positive

---

client/startup/startup.js
packages/rocketchat-livechat/app/client/views/livechatWindow.js

Closes #4277
This PR allow the usage of languages subtags (like `pt-BR`, `zh-TW` and so on) instead of just using the region definition (like `pt` or `zh`).
I'm now checking if the subtag exists before discarding it's usage.

[FIX] Usage of subtagged languages

---

.meteor/versions
packages/rocketchat-ui-login/client/login/services.js
server/lib/accounts.js
server/startup/migrations/v091.js

I removed the migration for Real Names cuz it takes hours to run on our demo, we are working to fix that.

[FIX] Accounts from LinkedIn OAuth without name

---

server/lib/accounts.js

Closes #1848
The addition of default roles by #6028 also added default roles to livechat guests. Since the idea of default roles was to add them only for OAuth created users, I'm now checking if the `services` field exists and the `services.password` does not. This seems to be a better way to know if a user was created by an OAuth or not.

[FIX] Do not add default roles for users without services field

---

packages/rocketchat-ui/client/lib/fileUpload.coffee

We were loading every single file into memory.
This loads only if:
* Allowed file type
* Not over 10MB of size ( this might should be increased... But a 100MB file crashed my browser )
* An Image / Audio / Video file
Also if you upload a file of type other then image it'll now actually show the preview it.  It was accessing `file.type` and file.type was empty
Closes #6534 
Possibly also closes #5789

[FIX] Large files crashed browser when trying to show preview

---

packages/rocketchat-lib/client/lib/roomTypes.coffee
packages/rocketchat-lib/startup/defaultRoomTypes.js
packages/rocketchat-ui/client/views/app/room.coffee

The new logic introduced by #3851 broke livechat room titles, so I moved the logic to the specific roomType definition.

Move room display name logic to roomType definition

---

.snapcraft/candidate/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml
.travis.yml
.travis/snap.sh

I've added a `sed` command to replace the Rocket.Chat version on the `snapcraft.yml` file. I don't how we can properly get the RC version for `edge` channel though.

Add candidate snap channel

---

packages/rocketchat-logger/server.js

arrow function expression don't have `arguments`.

[FIX] arguments logger

---

.docker/develop/Dockerfile
.docker/latest/Dockerfile
.docker/release-candidate/Dockerfile
.snapcraft/resources/startRocketChat
app.json
packages/rocketchat-statistics/server/functions/get.js
scalingo.json

Added Deploy method and platform to stats

---

packages/rocketchat-ui-message/client/message.coffee
packages/rocketchat-ui-message/client/message.html

[FIX] Encode avatar url to prevent CSS injection

---

packages/rocketchat-katex/katex.coffee
packages/rocketchat-markdown/markdown.coffee
packages/rocketchat-markdown/markdowncode.coffee
packages/rocketchat-ui-message/client/message.coffee

[FIX] Improve markdown code

---

.meteor/versions
packages/rocketchat-ui-message/client/messageBox.html
packages/rocketchat-ui-message/client/popup/messagePopup.html

[FIX] Revert unwanted UI changes

---

packages/rocketchat-logger/server.js

[FIX] Fix Logger stdout publication

---

packages/rocketchat-custom-oauth/custom_oauth_client.js

[FIX] Allow question on OAuth token path

---

packages/rocketchat-custom-oauth/custom_oauth_server.js

Closes #4535
This just use the tokenSentVia parameter to sent clientID / secret to either parameter or header not both.

[NEW] Use tokenSentVia parameter for clientid/secret to token endpoint

---

packages/rocketchat-emoji-custom/client/lib/emojiCustom.js
packages/rocketchat-emoji/emojiPicker.js
packages/rocketchat-emoji/lib/EmojiPicker.js

Closes #6636
This changes are intended to fix the exception that was happening when changing the Emoji Picker filter text, which was caused by some race conditions with Blaze computations and the jquery used to clear the emoji picker window for the dynamic categories (recent and rocket).
I aimed at removing the jquery code that was a fix for the duplication bug for these categories, which was being caused by some bad structure on the UI. The fix I found was to add a new reactive variable as a flag, so whenever we need to update the dynamic categories, the flag would be set as true and the UI would react properly (see emojiPicker.js:268 and emojiPicker.js:282).
I noticed a small change that could improve the performance of the Emoji Picker rendering, because we were …

[FIX] emoji picker exception

---

.snapcraft/candidate/snapcraft.yaml
.snapcraft/edge/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml

Something changed in a dependency of caddy.  Causing the snap builds to fail. This fixes that.

[FIX] Fix Caddy by forcing go 1.7 as needed by one of caddy's dependencies

---

packages/rocketchat-api/server/v1/integrations.js
packages/rocketchat-integrations/server/api/api.js
tests/data/api-data.js
tests/end-to-end/api/00-miscellaneous.js
tests/end-to-end/api/01-users.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js
tests/end-to-end/api/04-direct-message.js
tests/end-to-end/api/05-chat.js
tests/end-to-end/api/06-outgoing-integrations.js
tests/end-to-end/api/07-incoming-integrations.js

- Allow create/remove incoming integrations via API
- [Test] Remove code duplication, use getCredentials method
- [Test] Rename outgoing integration file
- [Test] Add basic test for incoming integration
- [Fix] Bug wih incmoing integration

[Fix] Bug with incoming integration (0.55.1)

---

packages/rocketchat-lib/server/methods/archiveRoom.js
packages/rocketchat-slashcommands-archiveroom/server.js
packages/rocketchat-slashcommands-unarchiveroom/server.js

@RocketChat/core the reason I did not check the `unarchiveRoom` meteor method is because if a room is already archived, keeping the ability to unarchive a direct message room is the only way to unarchive one without editing the database.
Closes #6728

[FIX] Archiving Direct Messages

---

packages/rocketchat-livechat/app/client/stylesheets/main.less

Added CSS to handle long URL overflow
Closes #6329 
Updated box

Breaking long URLS to prevent overflow

---

packages/rocketchat-importer-csv/server.js

Makes more sense for testing purposes, or when there are other reasons to
import data separately or in blocks.

[FIX] CSV importer: require that there is some data in the zip, not ALL data

---

packages/rocketchat-ui-flextab/client/tabs/userInfo.html
packages/rocketchat-ui-flextab/client/tabs/userInfo.js

Closes #6726
This hides most of the interaction buttons when opening your own profile from a chat room or direct message. The changes are basically adding a helper function to check if the open userInfo is your own and adding a check on the layout to show or hide based on that.
Adding screenshots for the different cases:
When viewing profile from another person in a public/private room as a normal user:
When viewing your own profile in public room:
When viewing profile from another person in public/private chat as admin:
When viewing profile from another in direct chat:
When viewing your own profile in direct chat:

[FIX] Hides nav buttons when selecting own profile

---

packages/rocketchat-theme/client/imports/base.less
packages/rocketchat-ui-sidenav/client/createCombinedFlex.html
packages/rocketchat-ui-sidenav/client/createCombinedFlex.js

Closes #6711
The validation method wasn't being able to find the actual label for the inputs since it was changed from 'label' to 'span' in the html in a previous commit. So I rolled back the label versions since, in my opinion, it makes more sense than having the 'span's there. Changed the css selector as well and removed some console logging.
Message when trying to create a channel with empty name:

[FIX] Incorrect error message when creating channel

---

packages/rocketchat-theme/client/imports/base.less
packages/rocketchat-ui/client/lib/fireEvent.js
packages/rocketchat-webrtc/WebRTCClass.coffee

- https://github.com/RocketChat/Rocket.Chat/commit/7b636a7bc36d8b656d96d907d515e1eb065c8666 Try to directly install screen share extension or open a new windows if it's not allowed 
- https://github.com/RocketChat/Rocket.Chat/commit/e6004426bee9e7f14e9a994ccd7c536c5d162436 Wait for iframe setting to start sending `postMessage`s (previously some `postMessage` could being lost because the `Iframe_Integration_send_enable` was not loaded on the client yet)
- https://github.com/RocketChat/Rocket.Chat/commit/070a0089db1da25a06ba4da72b03a9f3f3851415 Hide users typing if on loaded on an iframe (to prevent the white space after the message input):
before:
after:

[FIX] Fix iframe wise issues

---

packages/rocketchat-api/server/v1/users.js
packages/rocketchat-authorization/server/startup.js
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/methods/createToken.js
tests/end-to-end/api/01-users.js

Allowed users (usually admins) can generate access tokens to another user.
Users can generate theirs tokens too.

[NEW] create a method 'create token'

---

packages/rocketchat-api/server/v1/users.js

@RocketChat/core the rest api `users.update` was throwing an error due to the update of the rate limit functions due to the call to the `RocketChat.setUsername` function not being ran as the calling user.
Closes #6787

[FIX] REST API user.update throwing error due to rate limiting

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/v1/helpers/getUserFromParams.js
packages/rocketchat-api/server/v1/helpers/isUserFromParams.js
packages/rocketchat-api/server/v1/users.js

* Refactors `users.getPresence` to use current user param matcher 
* Modifies `users.setAvatar` to support `username` parameter

[FIX] Added helper for testing if the current user matches the params

---

packages/rocketchat-message-star/client/actionButton.js

[FIX] start/unstar message

---

packages/rocketchat-api/server/v1/helpers/getUserFromParams.js
packages/rocketchat-api/server/v1/helpers/isUserFromParams.js

Fixed up definition of `isUserFromParams` to handle case where no params are passed
=> assumption is no user type params to mean 'current user'
Fixed bug where POST/PUT request method didn't use `bodyParams` in place of `queryParams`
Refactored `getUserFromParams` to remove duplication of calls to find user

[FIX] Bugs in `isUserFromParams` helper

---

packages/rocketchat-lib/lib/settings.js
packages/rocketchat-theme/server/server.js

[FIX] Compile CSS color variables

---

packages/rocketchat-ui/client/lib/fileUpload.coffee

[Fix] Error when trying to show preview of undefined filetype

---

packages/rocketchat-api/server/v1/channels.js

Seems to be an old mistake while rewriting code caused it to check for create-p.

[FIX] make channels.create API check for create-c

---

packages/rocketchat-file-upload/server/config/configFileUploadAmazonS3.js
packages/rocketchat-file-upload/server/lib/AWS4.js
packages/rocketchat-file-upload/server/methods/getS3FileUrl.js

Closes #3099
This will allow support to AWS regions that only supports V4 signature as shown [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)

[FIX] Use AWS Signature Version 4 signed URLs for uploads

---

packages/rocketchat-slashcommands-mute/server/mute.js
packages/rocketchat-slashcommands-mute/server/unmute.js

Closes #6835
When a user is muted or unmuted, the server checks if that user is in the room and if not, throw an error. Previously, the server would throw an error if the user was in the room.

[FIX] Check that username is not in the room when being muted / unmuted

---

server/configuration/accounts_meld.js
server/startup/migrations/v094.js

We were saving an object for `emails.address` user's property for Meteor's OAuth as shown bellow:
```json
{
"_id" : "fAkeId",
"type" : "user",
"name" : "fakename",
"emails" : [ 
{
"address" : {
"address" : "fakename@meteoroauth.com",
"verified" : true,
"primary" : true
},
"verified" : true
}
],
"roles" : [ 
"user"
]
}
```
This PR is to get only the primary email address from Meteor's OAuth and also fixes problems related to `getUsernameSuggestion` because `address` property was not a string.

[FIX] Fix login with Meteor saving an object as email address

---

packages/rocketchat-lib/server/lib/PushNotification.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
packages/rocketchat-lib/server/models/Subscriptions.coffee

[FIX] Fix badge counter on iOS push notifications

---

packages/meteor-accounts-saml/saml_utils.js

[FIX] This prevent invalid XML:
Element {urn:oasis:names:tc:SAML:2.0:metadata}KeyDescriptor: Missing child element(s). Expected is ( {http://www.w3.org/2000/09/xmldsig#}KeyInfo )
(see https://www.samltool.com/validate_xml.php)
See https://github.com/steffow/meteor-accounts-saml/pull/10

[FIX] SAML: Only set KeyDescriptor when non empty

---

packages/rocketchat-ldap/server/sync.js

This refers to #6172. A lot of ldap backends do not have a single attribut with the users name, but rather a combination of multiple. This PR makes it possible to use variables in the ldap userdata mapping as seen in the screenshot below. The variables will be replaced with the actual ldap values on ldap user sync.

[New] LDAP: Use variables in User_Data_FieldMap for name mapping

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js
packages/rocketchat-api/server/v1/helpers/getUserFromParams.js
packages/rocketchat-api/server/v1/helpers/isUserFromParams.js
packages/rocketchat-api/server/v1/helpers/requestParams.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js

A nice shortcut, also makes more sense with the returned error (The parameter "roomId" or "roomName" is required).
Would it make sense to update all channel/group calls to accept roomName? The only call that I think really won't play nice with this is rename - with both roomName and name parameters, it'll be confusing.

[NEW] Make channel/group delete call answer to roomName

---

packages/rocketchat-theme/client/imports/base.less

Beneath the message input field there is a line with formatting tips. If a user in a chat room starts to type a message a user-typing-hint is shown. If the width of the browser window is too narrow that hint will overlay the formatting tips making it hard to read. This patch just sets the background color of the hint element to white to preserve readability.

[FIX] overlapping text for users-typing-message

---

packages/rocketchat-markdown/markdown.js

Parsing links last prevents exploits to target _blank links.

[FIX] Parse markdown links last

---

packages/rocketchat-ui-vrecord/client/VRecDialog.js

[FIX] video message recording dialog is shown in an incorrect position
This [change](https://github.com/RocketChat/Rocket.Chat/commit/ae125556471b8a00a878c09699127e3d057a05d9#diff-f90978acbc3ad72cce9a3175f0ff8a71) caused the class variables to not being correctly defined, thus breaking the `setPosition()` method and causing the video recording dialog to be rendered in an incorrect position.
EDIT: image that shows the problem. The dialog is malpositioned because of this.width and this.height not being defined.

[FIX] video message recording dialog is shown in an incorrect position

---

tests/end-to-end/api/01-users.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/04-direct-message.js
tests/end-to-end/api/05-chat.js
tests/end-to-end/ui/00-login.js
tests/end-to-end/ui/01-register.js
tests/end-to-end/ui/02-forgot-password.js
tests/end-to-end/ui/03-user-creation.js
tests/end-to-end/ui/04-main-elements-render.js
tests/end-to-end/ui/05-channel-creation.js
tests/end-to-end/ui/06-messaging.js
tests/end-to-end/ui/07-emoji.js
tests/end-to-end/ui/08-resolutions.js
tests/end-to-end/ui/09-channel.js
tests/end-to-end/ui/10-user-preferences.js
tests/end-to-end/ui/11-admin.js
tests/end-to-end/ui/12-settings.js
tests/end-to-end/ui/13-permissions.js
tests/pageobjects/flex-tab.page.js
tests/pageobjects/global.js
tests/pageobjects/login.page.js
tests/pageobjects/main-content.page.js
tests/pageobjects/side-nav.page.js

This will fix some (hopefully all) of the current failing tests and improve the tests error messages.
Errors will look like that:

[FIX] Improve Tests

---

packages/rocketchat-webrtc/client/WebRTCClass.js
packages/rocketchat-webrtc/client/screenShare.js

Try to communicate with Chrome extension to see it is installed instead of checking for a cookie (the Chrome extension will not set a cookie anymore).
Chrome extension version 0.3+ accepts this method.

[FIX] New screen sharing Chrome extension checking method

---

packages/rocketchat-lib/server/startup/settings.js

Adding the html tags makes the emails sent out by rocket.chat better compliant with standards, and lowers the chance they'll be marked as spam.
Closes #7001

[FIX] Add <html> and </html> to header and footer

---

server/startup/migrations/v095.js

There was a typo in #7080. (“html” instead of “html”) This fixes it.

[FIX]Fixed typo hmtl -> html

---

packages/rocketchat-markdown/markdowncode.js

When I created an integration with Github (to notify PR comments), I noticed that the markdown is not working for code blocks if its a message attachment. Its because Github webhook payload has carriage return and new line `\r\n`. That's why javascript regex cannot split the text correctly
refs: <https://demo.rocket.chat/channel/support?msg=hkHxtB3vtnCq7X9JY>

[FIX] Add support for carriage return in markdown code blocks

---

packages/rocketchat-lib/server/startup/settings.js
packages/rocketchat-lib/server/startup/settingsOnLoadSMTP.js

email after email@1.1.18/node4mailer will STARTTLS automatically even if that is unwanted behaviour: 
Updates #6996
Adds an option to set "IgnoreTLS" when 'smtp' is selected in settings, allowing unencrypted SMTP if required.

[FIX] Add option to ignore TLS in SMTP server settings

---

packages/rocketchat-ldap/server/loginHandler.js

@TwizzyDizzy
See #6144
[Comment](https://github.com/RocketChat/Rocket.Chat/issues/6144#issuecomment-284715888) by [TwizzyDizzy](https://github.com/TwizzyDizzy)
> We do NOT want passwords to be saved in MongoDB when LDAP is enabled (this might be made into an option in the backend, if not, they should not be saved by default)
unless fallback-login is activated
> this means the passwords need to be erased (for LDAP-flagged accounts) on disabling fallback login and stored on next login, when this feature is enabled
This PR changes the password storage behaviour if `LDAP_Login_Fallback` is enabled. The password will not be saved in MongoDB.

[FIX] do only store password if LDAP_Login_Fallback is on

---

packages/rocketchat-i18n/i18n/de.i18n.json
packages/rocketchat-i18n/i18n/en.i18n.json

References #6921 
de.i18n.json and en.i18n.json edited. Explaining the usage of variables in ldap field mappings. 

Ldap: User_Data_FieldMap description

---

package.json

Closes #6814
The specific commit i'm referring to: https://github.com/isagalaev/highlight.js/commit/d05317a8bc9ad2335bd4b7709e507314546836b1
There have been commits since... So I don't know if we want those.  But we for sure want this one and no release has been made yet

[FIX] Fix highlightjs bug

---

.travis/setartname.sh

TRAVIS_BRANCH is always set.  In the case of a tag its set to the tag name.  TRAVIS_TAG however is only set when its a tag.

Switch logic of artifact name

---

.openshift/rocket-chat-ephemeral.json
.openshift/rocket-chat-persistent.json

This adds healthchecks to the OpenShift app templates.
Also fixes a couple of JSON indentation/formatting details in the template files.

[NEW] Add healthchecks in OpenShift templates

---

packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/lib/debug.js

This will help a lot with debugging multi-instance issues.
Debating putting behind a setting.  I don't think we use instance id for anything special, so I don't know that exposing it would be harmful in any way.

[New] Add instance id to response headers

---

packages/rocketchat-oauth2-server-config/oauth/server/default-services.js
server/startup/migrations/v098.js

This is a permanent oAuth return url which needs to be in everyone's system. Will be updated again when we go to a public beta instead of invite only.

Fix the Zapier oAuth return url to the new one

---

packages/rocketchat-ui/client/views/app/room.js

Fixes the `jump to unread` button not working

[FIX] Fix jump to unread button

---

packages/rocketchat-ui-message/client/messageBox.js

Closes #7318 and #7068
This is a bug caused by the coffeescript conversions

[FIX] Fix geolocation button

---

client/lib/handleError.js

Escape error messages

---

server/startup/migrations/v097.js
server/startup/migrations/xrun.js

Fix overall issues and run asynchronously which increases performance considerably.

[FIX] Improve avatar migration

---

packages/rocketchat-lib/server/models/Users.js

[FIX] Fix user's customFields not being saved correctly

---

.snapcraft/candidate/snapcraft.yaml
.snapcraft/edge/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml
packages/rocketchat-2fa/client/accountSecurity.html

This warning no longer needs to be displayed because 2FA support appears to be implemented in the native mobile apps:
* [2FA in Rocket.Chat Android](https://github.com/RocketChat/Rocket.Chat.Android/issues/248)
* [2FA in Rocket.Chat iOS](https://github.com/RocketChat/Rocket.Chat.iOS/issues/375)

[FIX] Remove warning about 2FA support being unavailable in mobile apps

---

.snapcraft/candidate/snapcraft.yaml
.snapcraft/edge/snapcraft.yaml
.snapcraft/stable/snapcraft.yaml
packages/rocketchat-2fa/client/accountSecurity.html

The version of Node v4 'Argon' LTS used in the Ubuntu Snap is currently two minor releases behind. Those minor releases contain fixes that may be applicable to Rocket.Chat.

[FIX] Update node-engine in Snap to latest v4 LTS relase: 4.8.3

---

packages/rocketchat-lib/client/MessageAction.js

Previously doing a reply in a DM mentioned them.  Which is pointless.  You don't need to mention the person you're sending the message directly to :)
There might be a better way of determining if the room type is DM.  If so please suggest :)

[Fix] Don't @ mention when doing reply in DM

---

packages/rocketchat-markdown/markdown.js

Links created by autolinker already have these attributes. However, links created via Markdown [title](link) or <link|title> didn't have these.
Links created using Markdown syntax leak channel names because they do not have `ref="noreferrer"`. Links created by autolinker have `noreferrer` and `noopener`. Add these two attributes to links created via Markdown.

[NEW] Add ref="noopener noreferrer" to Markdown links

---

packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json

There is no Issue for this fix.
Example:

[FIX] Translation of word Away to Ausente instead of ausente in (PT,PT-BR)

---

packages/rocketchat-channel-settings/client/lib/ChannelSettings.js
packages/rocketchat-ui-admin/client/rooms/adminRoomInfo.js

related #5975 and #7004 
Under administration -> Rooms if you selected a channel from the list, the `default channel` option would refer to that channel, even if you selected another channel in the list

[FIX] Fix not being able to add more than 2 default rooms

---

packages/rocketchat-lib/client/lib/cachedCollection.js

@RocketChat/core Reduce the amount of `console.log`'s that we do on the client for the `CacheCollection`.
Closes #7251

[FIX] Loads of console.log for CacheCollections

---

packages/rocketchat-integrations/server/lib/validation.js

Currently when creating Zaps the `rocket.cat` user is required. This improves the error message which comes up inside of Zapier when someone has deleted this user in their instance but tries to get a Zap going.

[FIX] Vague error message when creating integration and rocket.cat is deleted

---

packages/rocketchat-ui/client/lib/fileUpload.js

Closes #7220 
There was a scope error that caused the file uploaded ID to be undefined, causing the error to append instead of replace the file on the uploading list:
With the fix, the file upload indicator is replaced with the error and the close buttons works when trying to dismiss the error.
Not sure if the 'error.message' is the best choice there, but I think it's better than doing just the error code that was there previously.

[FIX] Fixes scope error preventing file upload errors from being dismissed

---

README.md

Would love to get your feedback about this PR: https://github.com/kubernetes/charts/pull/752
Also, I think it makes sense to replace openshift folder then.
And finally, solving the following issues would be really nice to have to help this deployment:

Add helm chart kubernetes deployment

---

packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/lib/cordova/urls.js
packages/rocketchat-ui/client/views/app/room.js

this should fix the following problems:
- exception on touchmove events in the cordova app
- http links are not opened in an external browser in the cordova app
- sometimes url clicks are not handled because the touchMoved variable is set
Please let me know if this also works for you.
Closes RocketChat/Rocket.Chat.Cordova#142 and #7075

[FIX] url click events in the cordova app open in external browser or not at all

---

packages/rocketchat-ldap/server/sync.js

This PR will prevent new LDAP logins from being stuck even if `Merge existing users` is disabled.
For users that currently cannot log in (see #7429 and #7405) you'll need to enable `Merge existing users`.

[FIX] Always set LDAP properties on login

---

packages/rocketchat-ui/client/lib/notification.js

Fix new room sound notification playing when any user data changes (the status is the most common)

[FIX] Prevent new room status from playing when user status changes

---

packages/rocketchat-cas/cas_client.js

Closes #7365
The fix checks whether the URL contains `?`, which means that the configured URL already has parameters(s). In that case instead of adding a `?`, a `&` will allow the chaining of parameters.

[FIX] Issue #7365: added check for the existence of a parameter in the CAS URL

---

packages/rocketchat-ui-flextab/client/tabs/membersList.js
packages/rocketchat-ui-message/client/message.js
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui/client/views/app/room.js

#
Closes #7396
Apparently fixes #6817 
This was caused by some coffeescript conversions removing files without adding some changes that where made on the coffee files

[FIX] Fix Anonymous User

---

packages/rocketchat-authorization/server/startup.js
packages/rocketchat-lib/server/methods/sendMessage.js

In the old coffee script code line 97 was `return 'bot' not in user.roles`, but it was converted to JavaScript to `user.roles.includes('bot')`.

[FIX] Modernize rate limiting of sendMessage

---

packages/rocketchat-2fa/client/accountSecurity.html
packages/rocketchat-emoji-custom/client/lib/emojiCustom.js
packages/rocketchat-emoji-emojione/emojiPicker.js
packages/rocketchat-emoji/emojiPicker.js
packages/rocketchat-emoji/rocketchat.js
packages/rocketchat-i18n/i18n/en.i18n.json

Closes #6969 and #5559
The emoji titles were being translated directly in their package, and this was causing to keep the first translation it got
also fixed a hardcoded string on the security page

[FIX] Fix emoji picker translations

---

packages/rocketchat-theme/client/imports/base.css

Using the embedded view mode (appending `?layout=embedded` to the URL) the flex-tab should be hidden. This behavior was changed by #7448 
Before:
After:

[FIX] Fix hiding flex-tab on embedded view

---

packages/rocketchat-channel-settings/client/views/channelSettings.html
packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.html
packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.html
packages/rocketchat-message-pin/client/views/pinnedMessages.html
packages/rocketchat-message-snippet/client/tabBar/views/snippetedMessages.html
packages/rocketchat-message-star/client/views/starredMessages.html
packages/rocketchat-otr/client/views/otrFlexTab.html
packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.html
packages/rocketchat-theme/client/imports/base.css
packages/rocketchat-ui-flextab/client/flexTabBar.html
packages/rocketchat-ui-flextab/client/flexTabBar.js
packages/rocketchat-ui-flextab/client/tabs/membersList.html
packages/rocketchat-ui-flextab/client/tabs/messageSearch.html
packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html
packages/rocketchat-videobridge/client/views/videoFlexTab.html

Closes #7435
What I did in most files was just removing the `<div class="content">` because I added it to the container template:

[NEW] Add close button to flex tabs

---

.github/ISSUE_TEMPLATE.md

Better Issue Template

---

packages/rocketchat-theme/client/imports/base.css
packages/rocketchat-ui/client/lib/iframeCommands.js
packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js

Closes #7433
This PR adds two new external commands: `set-toolbar-button` and `remove-toolbar-button`.
To add/set a button at the top toolbar:
```
document.querySelector('iframe').contentWindow.postMessage({
externalCommand: 'set-toolbar-button',
id: 'resize',
icon: 'icon-resize-small'
}, '*')
```
A button can be updated using the same `id`:
```
document.querySelector('iframe').contentWindow.postMessage({
externalCommand: 'set-toolbar-button',
id: 'resize',
icon: 'icon-resize-full'
}, '*')
```
To remove a toolbar button:
```
document.querySelector('iframe').contentWindow.postMessage({
externalCommand: 'remove-toolbar-button',
id: 'resize'
}, '*')
```
When a button is clicked, the parent window will receive a `postMessage` called `click-toolbar-button` and an object with …

[NEW] Add toolbar buttons for iframe API

---

packages/rocketchat-ui/client/lib/RoomManager.js

[NEW] Room type (direct or group or channel) and recipient username (room or person) data is missing from the global even fired when a new message is sent.

[NEW] Room type and recipient data for global event

---

.meteor/packages
.meteor/versions

Looks like the Sandstorm package does not work with Meteor 1.5. It's logging me out on every page refresh and given the error below:
Also looks like our latest version available on Sandstorm grain is outdated, so I'm removing the Sandstorm login package until it can get it fixed.

[BREAK] Remove Sandstorm login method

---

packages/rocketchat-livechat/server/lib/Livechat.js

Most reverse proxies set the original client IP address on [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For) header, so now livechat will be able to get it.

[FIX] Look for livechat visitor IP address on X-Forwarded-For header

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/users.js

Closes #7144 - to be able to use `/api/v1/users.list` you must have `view-d-room` permission and then to view other channels that you aren't joined you must have `view-c-room` and can not have `view-joined-room`.

[Fix] Users and Channels list not respecting permissions

---

packages/rocketchat-integrations/server/lib/triggerHandler.js

Closes #7008 - Allows returning a channel where the messages should be sent when inside of the integration script.
```
return {
content: {
text: 'Hiya ;)',
channel: data.channel || '@username'
}
};
```

[NEW] Allow channel property in the integrations returned content

---

server/methods/createDirectMessage.js

Closes #7302
The code is adapted from similar code in sendMessage.js, including the fix of #7325.

[NEW] Do not rate limit bots on createDirectMessage

---

packages/rocketchat-lib/server/models/Users.js

Closes #7333
* Changed `findByActiveUsersExcept` query to allow to search users also by email (`emails.address`) in toolbar

[NEW] Search users also by email in toolbar

---

server/startup/avatar.js

This PR updates the [`const svg`](https://github.com/filipedelimabrito/Rocket.Chat/blob/b9234457e57a8c600b94ebc6ca59b861ca49cce1/server/startup/avatar.js) replacing the `style` attribute by the `<rect` SVG shape element to build the user avatar image background.

[FIX] User avatar image background

---

packages/rocketchat-lib/client/lib/roomExit.js
packages/rocketchat-mentions-flextab/client/actionButton.js
packages/rocketchat-message-pin/client/actionButton.js
packages/rocketchat-message-star/client/actionButton.js
packages/rocketchat-ui-flextab/client/tabs/messageSearch.js

Closes #7370
When leaving a room on mobile UI (screen less than 500px) it automatically closes the tab bar so when the user goes back to the room it's not open by default.

[NEW] Closes tab bar on mobile when leaving room

---

packages/rocketchat-lib/server/functions/sendMessage.js

Closes #7169 #7482 
The url parse issue happens in `sendMessage` while the regex match looks for a url pattern. This pattern ignore the `(` and `)` characters. This has been added in this PR.
To test the regex you can use [Regex101.com](https://regex101.com/) with the new regex
<code>([A-Za-z]{3,9}):\/\/([-;:&=\+\$,\w]+@{1})?([-A-Za-z0-9\.]+)+:?(\d+)?((\/[-\+=!:~%\/\.@\,\(\)\w]*)?\??([-\+=&!:;%@\/\.\,\w]+)?(?:#([^\s\)]+))?)?</code>
Examples:
`https://en.wikipedia.org/wiki/Bear_(disambiguation)`
`https://cs.wikipedia.org/wiki/Bylina_(pov%C4%9Bst)`
Hope this helps!

[FIX] URL parse error fix for issue #7169

---

packages/rocketchat-lib/client/Notifications.js
packages/rocketchat-livechat/app/client/lib/fromApp/Notifications.js

`return this.streamUser.removeListener(Meteor.userId(), callback)` was missing eventName so listeners were leaking

[FIX] Missing eventName in unUser

---

packages/rocketchat-theme/server/colors.less
packages/rocketchat-ui-sidenav/client/chatRoomItem.html
packages/rocketchat-ui-sidenav/client/chatRoomItem.js

The default format for alert numbers by the room's name is the number only `@all and @here`
The rounded square will show only when there are mentions to the user.

[NEW] Show different shape for alert numbers when have mentions

---

server/publications/room.js

In 'userData' it is available now to see customFields, if this value exists, but in 'rooms/get' is not. I think, that it will be helpful.

[NEW] Add customFields in rooms/get method

---

packages/rocketchat-authorization/client/usersNameChanged.js
packages/rocketchat-authorization/package.js
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/methods/getRoomRoles.js
packages/rocketchat-theme/client/imports/base.css
packages/rocketchat-theme/server/colors.less
packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js

Improve room leader

---

packages/rocketchat-markdown/markdown.js

Improve link parser using tokens

---

packages/rocketchat-lib/server/functions/saveCustomFieldsWithoutValidation.js

@ggazzo 
This fixes the issue when registering with custom fields giving ` Exception while invoking method 'registerUser' TypeError: Cannot read property 'modifyRecordField' of undefined`
But this reveals more problems with custom fields, as roles being duplicate and problems to see the current roles #7618

[FIX] Fix Custom Fields Crashing on Register

---

packages/rocketchat-ui/client/views/app/room.js

Add missing parts of `one click to direct message`

---

packages/rocketchat-ui/client/lib/fileUpload.js

@RocketChat/core When uploading an unknown file type, such as a `.sketch`, and the browser doesn't have any mimetype about that file type it will currently error out. This handles that case.
Closes #7462

[FIX] Uploading an unknown file type erroring out

---

.github/changelog.js

This should fix incorrect generated links in changelog.

Fix typo in generated URI

---

packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui-master/package.js
packages/rocketchat-ui/client/lib/RoomManager.js
packages/rocketchat-ui/package.js

Some times when you first hit on a room URL (like https://demo.rocket.chat/channel/general) the room does not load due some kind of race condition.

[FIX] Fix room load on first hit

---

packages/rocketchat-markdown/markdown.js

Follow-up to #7327 fixing the usage of `ref` to `rel` as pointed out by @pitamar.

[FIX] Markdown noopener/noreferrer: use correct HTML attribute

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/lib/sendEmailOnMessage.js

This adds a email title for when you set the `all messages` email notifications preferences

[FIX] Wrong email subject when "All Messages" setting enabled

---

packages/rocketchat-oembed/client/oembedFrameWidget.html
packages/rocketchat-oembed/client/oembedVideoWidget.html
packages/rocketchat-oembed/client/oembedYoutubeWidget.html

Currently, the YouTube link in an preview opens the link in the current Rocket.Chat tab. This pull request changes this behaviour to open the YouTube link in a new tab.

[FIX] Make link inside YouTube preview open in new tab

---

packages/rocketchat-ui-account/client/avatar/prompt.js

When uploading avatar on Cordova app, Android or iOS, it can't work and appear js error below:
Clicking the error code, found the error near the "for...of" loop:
So i changed the for...of loop to the normal for loop, and it work fine.

[FIX] Fix avatar upload fail on Cordova app

---

packages/rocketchat-importer-csv/.npm/package/npm-shrinkwrap.json
packages/rocketchat-importer-csv/package.js
packages/rocketchat-importer-csv/server.js
packages/rocketchat-importer-hipchat-enterprise/server.js
packages/rocketchat-importer-hipchat/server.js
packages/rocketchat-importer-slack/server.js
packages/rocketchat-importer/client/admin/adminImportPrepare.html
packages/rocketchat-importer/client/admin/adminImportPrepare.js
packages/rocketchat-importer/server/classes/ImporterSelection.js

This is a continuation of #6768, fixing import when users.csv, channels.csv or both are missing.
It also fixes issues hit by doing a massive import from our internal chat implementation into RC.

[FIX] Csv importer: work with more problematic data

---

packages/rocketchat-theme/client/imports/base.css

[FIX] make flex-tab visible again when reduced width

---

package-lock.json

When I ran `meteor npm start ` to run a local environment, I got a "permission denied" error when trying to run PhantomJS. Upgrading to PhantomJS 2.1.14 fixes the problem for me. The issue may be related to [PhantomJS bug 107](https://github.com/Medium/phantomjs/issues/707).
[Here's my error log](https://hastebin.com/isibifejep.txt). I'm running Node 6.11.1, npm 3.10.10, and Fedora 26.
If I can provide any additional details, just let me know. Thanks!

FIX: Error when starting local development environment

---

package.json
packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.html
packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.js
packages/rocketchat-message-pin/client/views/pinnedMessages.html
packages/rocketchat-message-pin/client/views/pinnedMessages.js
packages/rocketchat-message-star/client/views/starredMessages.html
packages/rocketchat-message-star/client/views/starredMessages.js
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui-flextab/client/flexTabBar.html
packages/rocketchat-ui-flextab/client/tabs/membersList.html
packages/rocketchat-ui-flextab/client/tabs/messageSearch.html
packages/rocketchat-ui-flextab/client/tabs/messageSearch.js
packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html
packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js

[FIX] scroll on flex-tab

---

packages/rocketchat-lib/server/functions/settings.js

This fixes settings not getting applied when launching a fresh install of RC.
The issues are the variable `value` had an incorrect scope and Meteor.settings and process.env were accessed incorrectly. These crept up after the conversion from coffeescript to ES6.

[FIX] Settings not getting applied from Meteor.settings and process.env 

---

packages/meteor-accounts-saml/saml_client.js
packages/meteor-accounts-saml/saml_utils.js

Closes #7723
this fix adds support for ns0 and ns1 namespaces, to be able to process saml responses which are generated with pysaml2
this fix also adds the "id-" prefix to the unique id , to prevent issues with ids starting with a number

[FIX] meteor-accounts-saml issue with ns0,ns1 namespaces, makes it compatible with pysaml2 lib

---

packages/rocketchat-api/server/api.js
packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/chat.js
packages/rocketchat-api/server/v1/groups.js
packages/rocketchat-api/server/v1/im.js
packages/rocketchat-integrations/server/api/api.js
packages/rocketchat-integrations/server/processWebhookMessage.js
packages/rocketchat-lib/server/methods/getChannelHistory.js
packages/rocketchat-message-pin/server/pinMessage.js
packages/rocketchat-message-star/server/starMessage.js

@rafaelks here are a few additions for the mobile apps. Once you find out more information regarding the oAuth items I will start working on getting them added.
Closes #7775 4f3c9d4
Closes #7765 fb04102
Closes #7764 fb04102
Closes #7763 ae87222 `/api/v1/channels.messages?roomId=GENERAL&query={ "pinned": true }`
Closes #7762 ae87222 `/api/v1/channels.messages?roomId=GENERAL&query={ "starred._id": { "$in": ["${userid}"] } }`
Closes #7761 1914d7a
Closes #7760 25792e6
Closes #7770 ae3f821
Closes #7241 ae3f821
Closes #7262 ae87222
In addition to the items above, direct message endpoints no longer require a user to know the room's id. Instead you can now pass the query parameter `username` to the endpoints and it will assume you mean a direct message conversation between the authenticated user …

Additions to the REST API

---

packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.html

Add classes to each li in the notification menu so that they can be hidden using css. Right now, the name is just captured in the label HTML.

[NEW] Add classes to notification menu so they can be hidden in css

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json
packages/rocketchat-ldap/server/sync.js
packages/rocketchat-lib/lib/templateVarHandler.js
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/startup/settings.js
packages/rocketchat-ui-flextab/client/tabs/userInfo.html
packages/rocketchat-ui-flextab/client/tabs/userInfo.js

Closes #7610
This change allows admin user to choose extra fields to be shown in the user's info tab. A new field was introduced (Accounts):
Below is a screenshot of the UserInfo tab:
Besides that, as the template var handling logic was extracted to a method, I changed the ```getDataToSyncUserData``` method to use it.

[NEW] Template to show Custom Fields in user info view

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json
packages/rocketchat-lib/server/models/Users.js
packages/rocketchat-lib/server/startup/settings.js
server/publications/spotlight.js

These changes introduce the possibility of searching users by any field the Rocket.Chat's administrator defines in the new "Accounts -> Fields to consider in search" field.
Related to #7334 and #7210.

[NEW] Search users by fields defined by admin

---

.postcssrc

Closes #7699
This will fix issues with flexbox on older Safari versions, although we still not officially support old Safari versions.

[FIX] Add CSS support for Safari versions > 7

---

packages/rocketchat-file-upload/server/lib/proxy.js

When running RC with multi-instances and a path prefix like http://domain.com/rocket-chat, file uploads return an error when 2 requests are handled by different instances. The reason is req.url does not contain url prefix (it's stripped by Meteor https://github.com/meteor/meteor/blob/59aca741ccc22fbacc72786b94c97d74fb66e3a9/packages/webapp/webapp_server.js#L618) so when the request is rerouted to the correct instance it goes MIA.
I tested this change with 1 and many instances running, with a prefix and no prefix and using S3 and FileSystem.

[FIX] File upload on multi-instances using a path prefix

---

packages/rocketchat-emoji/client/emojiPicker.css
packages/rocketchat-emoji/client/lib/EmojiPicker.js

Closes #7875
Adds default search padding for the emoji search input so we don't add text below the search icon.
Also removes a console.log triggered when opening the emoji window.

[FIX] Adds default search text padding for emoji search

---

packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
packages/rocketchat-ui-message/client/popup/messagePopup.html
packages/rocketchat-ui-message/client/popup/messagePopup.js

[FIX] search results position on sidebar

---

packages/rocketchat-ui-account/client/accountProfile.html

Fixes wrong placeholders on account profile. Not sure if the placeholders are needed here though, since there's a label above each input field.
Before:
After:

[FIX] Fix placeholders in account profile

---

packages/rocketchat-ui-flextab/client/tabs/keyboardShortcuts.html

[FIX] Double scroll on 'keyboard shortcuts' menu in sidepanel

---

README.md

This PR changes the link to download the mobile apps on `README` file, since our native apps are now much more stable and being used by many people on the community.

[DOCS] Add native mobile app links into README and update button images

---

packages/rocketchat-ui/client/views/app/room.js

Display the leader at the top of the chat when you first enter a room. The room scrolls to the bottom, which will hide the leader, so manually unhide the leader.

[FIX] Show leader on first load

---

packages/rocketchat-autotranslate/server/autotranslate.js

Fix exception:
```
TypeError: Cannot read property 'length' of undefined
at AutoTranslate.tokenizeURLs (/app/bundle/programs/server/packages/rocketchat_autotranslate.js:118:30)
at AutoTranslate.tokenize (/app/bundle/programs/server/packages/rocketchat_autotranslate.js:83:19)
at /app/bundle/programs/server/packages/rocketchat_autotranslate.js:277:30
at [object Object].EVp.withValue (packages/meteor.js:1135:15)
at packages/meteor.js:452:25
at runWithEnvironment (packages/meteor.js:1189:24)
```

[FIX] Error when translating message

---

packages/rocketchat-ui-message/client/popup/messagePopupConfig.js

- Update the recent's list when adding via text `Ex: :smile:`
- Show recent emojis first on emoji popup
- Show emoji popup when type `:` directly, was expecting 2 chars to show it

[FIX] Recent emojis not updated when adding via text

---

packages/rocketchat-cors/common.js

Remove unnecessary returns in cors common

---

packages/rocketchat-ldap/server/sync.js

Closes #7405
Fixes an issue that makes the whole LDAP login process to fail when trying to set the user's avatar from AD.

[FIX] Fix setting user avatar on LDAP login

---

client/notifications/notification.js
packages/rocketchat-lib/client/lib/cachedCollection.js
packages/rocketchat-ui-sidenav/client/accountBox.js
packages/rocketchat-ui-sidenav/client/chatRoomItem.js
packages/rocketchat-ui-sidenav/client/sideNav.html
packages/rocketchat-ui-sidenav/client/sideNav.js
packages/rocketchat-ui/client/lib/notification.js

I removed logic from the template to a listener on the `subscription-changed` stream, so the sound will play only when new data comes from server and not due to any random reactivity.
I've also removed some calls to `Meteor.user()` which adds reactivity to changes to any field of the current user, which was not desired, and replaced by `Meteor.userId()` (when the test was to see the user is logged in) and by a query on specific fields (this way if I care about `settings` field my code will not reactivity ran if the `status` field changes).

[FIX] Fix new room sound being played too much

---

packages/rocketchat-lib/lib/fileUploadRestrictions.js
packages/rocketchat-ui/client/lib/fileUpload.js

Closes #7074 
This moves the type validity check down to fileUploadIsValidContentType(). This way the whitelist can be checked first, before denying uploads of unknown file types. This way unknown/undetected file types are allowed, if and only if the whitelist is completely empty.

[FIX] Allow unknown file types if no allowed whitelist has been set (#7074)

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js
packages/rocketchat-api/server/v1/im.js

[FIX] "*.members" rest api being useless and only returning usernames

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-livechat/app/client/lib/tapi18n.js
packages/rocketchat-livechat/client/stylesheets/livechat.less
packages/rocketchat-livechat/client/views/sideNav/livechat.html
packages/rocketchat-theme/client/imports/components/messages.css
packages/rocketchat-theme/client/imports/components/modal/create-channel.css
packages/rocketchat-theme/client/imports/components/modal/full-modal.css
packages/rocketchat-theme/client/imports/components/popover.css
packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-flex.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css
packages/rocketchat-theme/client/imports/forms/switch.css
packages/rocketchat-theme/client/imports/general/rtl.css
packages/rocketchat-theme/client/imports/general/variables.css
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui-sidenav/client/accountBox.js
packages/rocketchat-ui-sidenav/client/roomList.html
packages/rocketchat-ui/client/lib/menu.js
packages/rocketchat-ui/client/lib/tapi18n.js
packages/rocketchat-ui/client/views/app/createChannel.html
packages/rocketchat-ui/client/views/app/createChannel.js
packages/rocketchat-ui/client/views/app/popover.html
packages/rocketchat-ui/client/views/app/popover.js

Closes #8148 #8129 #8165 #8179 #8184 #8185 #8182
Sidebar:
* Removed empty space above sidebar header
* Fixed header color on lighten version of the sidebar
* Fixed empty room groups alignment
* Fixed livechat icon alignment
* Fixed Back button alignment
Create Channel:
* Fixed create channel page on mobile
* Now private channels are default
Popover:
* Fixed popover position on RTL

[FIX] Sidebar and RTL alignments

---

packages/rocketchat-iframe-login/iframe_client.js

Closes #8145
Fixes iframe login API response to match what documentation says.

[FIX] Fix iframe login API response (issue #8145)

---

packages/rocketchat-ui-sidenav/client/chatRoomItem.js
packages/rocketchat-ui-sidenav/client/sidebarItem.html

thanks @nishimaki10
Closes #7907
Fix to use original name for avatar URL.
Avatar URL is not correct when Use Real Name is True.

[FIX] User avatar in DM list.

---

.meteor/packages
.meteor/versions
packages/rocketchat-lib/client/lib/settings.js
packages/rocketchat-theme/client/imports/components/messages.css
packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-theme/client/imports/general/base.css
packages/rocketchat-ui-account/client/accountFlex.js
packages/rocketchat-ui-admin/client/adminFlex.js
packages/rocketchat-ui-message/client/message.js
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui-sidenav/client/roomList.js
packages/rocketchat-ui/client/views/app/room.js
tests/end-to-end/ui/11-admin.js
tests/pageobjects/administration.page.js

applied on sidenav and room
Closes #8049

[FIX] Scrollbar not using new style

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-livechat/app/client/lib/tapi18n.js
packages/rocketchat-livechat/client/stylesheets/livechat.less
packages/rocketchat-livechat/client/views/sideNav/livechat.html
packages/rocketchat-theme/client/imports/components/message-box.css
packages/rocketchat-theme/client/imports/components/messages.css
packages/rocketchat-theme/client/imports/components/modal/create-channel.css
packages/rocketchat-theme/client/imports/components/modal/full-modal.css
packages/rocketchat-theme/client/imports/components/popover.css
packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-flex.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css
packages/rocketchat-theme/client/imports/forms/popup-list.css
packages/rocketchat-theme/client/imports/forms/switch.css
packages/rocketchat-theme/client/imports/general/rtl.css
packages/rocketchat-theme/client/imports/general/variables.css
packages/rocketchat-ui-message/client/messageBox.html
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui-sidenav/client/accountBox.js
packages/rocketchat-ui-sidenav/client/roomList.html
packages/rocketchat-ui/client/lib/menu.js
packages/rocketchat-ui/client/lib/tapi18n.js
packages/rocketchat-ui/client/views/app/createChannel.html
packages/rocketchat-ui/client/views/app/createChannel.js
packages/rocketchat-ui/client/views/app/fullModal.html
packages/rocketchat-ui/client/views/app/popover.html
packages/rocketchat-ui/client/views/app/popover.js

Closes #8180
Closes #8181
Closes #8186 
Closes #8187
* Add cross icon to cancel button on modal and fix that button on RTL
* Fix unread message on RTL
* User is typing on RTL
* Fix message box placeholder direction on RTL

Fix more rtl issues

---

packages/rocketchat-lib/server/startup/settings.js
packages/rocketchat-ui/client/views/cmsPage.html

When RC was behind a prefix, navigating to and from the login terms would lead to an incorrect URL.

[FIX] Incorrect URL for login terms when using prefix

---

packages/rocketchat-theme/client/imports/components/popover.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/accountBox.js
packages/rocketchat-ui-sidenav/client/sidebarItem.js
packages/rocketchat-ui/client/views/app/popover.html
packages/rocketchat-ui/client/views/app/popover.js

Fix `leave and hide` click, color and position

---

packages/meteor-accounts-saml/saml_server.js

this fix, makes the email lookup for saml accounts case insensitve 
fixes  #8215

[FIX] Case insensitive SAML email check

---

packages/rocketchat-ui-account/client/accountProfile.html
packages/rocketchat-ui/client/views/app/createChannel.html

Closes #8268
I also rename key `username` to `Username_Placeholder`. I think it's better for placeholders.
We also need some key in language file:
```
"Username_Placeholder": "Please enter usernames...",
"Channel_Name_Placeholder": "Please enter channel name...",
"New_Password_Placeholder": "Please enter new password...",
"Name_Placeholder": "Please enter your name...",
"Email_Placeholder": "Please enter your email address...",
```

[FIX] some placeholder and phrase traslation fix

---

README.md
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-account/client/accountProfile.html

[FIX] [i18n] My Profile & README.md links

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/chatRoomItem.js
packages/rocketchat-ui-sidenav/client/sidebarItem.html
packages/rocketchat-ui-sidenav/client/sidebarItem.js

fix color on unread messages

---

packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

Prevents an error if `attachments` is undefined. It's not possible to create an empty message with no attachments in Rocket.Chat at the moment so this is mainly for those that are building on top of Rocket.Chat and are extending the message model.

[FIX] Check attachments is defined before accessing first element

---

packages/rocketchat-ui-message/startup/messageBoxActions.js

Closes #7876 
Fix file upload for cordova and mobile browsers

[FIX-RC] Mobile file upload not working

---

packages/rocketchat-livechat/client/views/sideNav/livechatFlex.html
packages/rocketchat-livechat/client/views/sideNav/livechatFlex.js
packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
packages/rocketchat-ui-account/client/accountFlex.html
packages/rocketchat-ui-account/client/accountFlex.js
packages/rocketchat-ui-admin/client/adminFlex.html
packages/rocketchat-ui-admin/client/adminFlex.js
packages/rocketchat-ui/client/views/app/burger.html
packages/rocketchat-ui/client/views/app/burger.js

[FIX] Remove sidebar header on admin embedded version

---

packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
packages/rocketchat-lib/server/models/Subscriptions.js
packages/rocketchat-ui-sidenav/client/roomList.js
server/publications/room.js
server/publications/subscription.js
server/startup/migrations/v101.js

Remove field `lastActivity` from subscription data

---

packages/rocketchat-theme/client/imports/components/badge.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html

[NEW] Unify unread and mentions badge

---

packages/rocketchat-api/server/api.js
packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js
packages/rocketchat-api/server/v1/helpers/parseJsonQuery.js
packages/rocketchat-api/server/v1/im.js
packages/rocketchat-api/server/v1/stats.js
packages/rocketchat-api/server/v1/users.js

@RocketChat/core moves a few internal things around with how the `parseJsonQuery` helper handles things, this way each individual controller doesn't have to worry about the result of that helper.

[FIX] Duplicate code in rest api letting in a few bugs with the rest api

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ldap/server/ldap.js
packages/rocketchat-ldap/server/settings.js
packages/rocketchat-ldap/server/sync.js

Fix: Missing LDAP reconnect setting

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/es.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json
packages/rocketchat-lib/server/startup/settings.js
server/methods/createDirectMessage.js

Closes #8015 
Add settings for that admins can setup allow/avoid user direct messages to yourself.

[NEW] Add settings for allow user direct messages to yourself

---

packages/rocketchat-autolinker/client/client.js
packages/rocketchat-autolinker/server/settings.js
packages/rocketchat-markdown/markdown.js
packages/rocketchat-markdown/settings.js
packages/rocketchat-ui-message/client/messageBox.js

[NEW] Setting to disable MarkDown and enable AutoLinker

---

packages/rocketchat-ui-login/client/reset-password/resetPassword.js

Closes #8472
When password is reset the user is logged in automatically, but one error is received when the user has 2FA enabled requiring to pass the token, that is why we have the password reset but one error is displayed.
This PR just check the error message and redirect the user to the login page when 2FA is required and show a success alert about the message reset.
The 2 possible results are:
- 2FA Disabled: After a successful password reset the user will be logged in automatically
- 2FA Enabled: After a successful password reset the user will receive a successful message and will be redirect to the login page

[FIX] Wrong message when reseting password and 2FA is enabled

---

packages/rocketchat-lib/server/methods/joinRoom.js
packages/rocketchat-ui-message/client/messageBox.html
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui/client/lib/chatMessages.js
packages/rocketchat-ui/client/views/app/room.js
server/publications/room.js

Closes #6106
- Fix: Room preview not opening on first click or redirecting to home on reload
- Fix: Console errors when room is in preview mode but code is trying to access the input
- Fix: Some locations uses the old label `Code`
- Fix: Password input not showing when room is protected

[FIX] Invalid Code message for password protected channel

---

.docker/Dockerfile
.snapcraft/snapcraft.yaml

New website, the paths that once existed don't any more.

Change artifact path

---

server/publications/room.js

Improve room sync speed

---

packages/rocketchat-lib/server/publications/settings.js
packages/rocketchat-ui-admin/client/admin.js

[FIX] Color reset when default value editor is different

---

README.md

Closes #8587
Updated the older /docs urls so you don't have to see "redirecting"

[FIX] Changed all rocket.chat/docs/ to docs.rocket.chat/

---

README.md

Fix community links in readme

---

.snapcraft/snapcraft.yaml

With out this snap builds for armhf (raspberry pi) fails.

install grpc package manually to fix snap armhf build

---

packages/rocketchat-file-upload/ufs/AmazonS3/server.js

Adds quotes around the filename attribute.
See:
- https://github.com/RocketChat/Rocket.Chat/issues/8584
- https://stackoverflow.com/questions/38320996/s3-downloading-images-with-comma-in-filename-results-in-neterr-response-heade
Fixes #8584

[FIX] AmazonS3: Quote file.name for ContentDisposition for files with commas

---

packages/rocketchat-lib/server/startup/settings.js

The use of the word 'temper' was a little misleading for users as it's not in the common lexicon. In the interests of keeping the UX as simple as possible, I propose that we change the default. :- )

[FIX] Improved grammar and made it clearer to the user

---

.circleci/config.yml
.circleci/update-releases.sh
.docker/Dockerfile

This will fix the `develop` docker image and other tags as well.

Fix Docker image build

---

packages/rocketchat-api/server/v1/chat.js
packages/rocketchat-lib/server/models/Messages.js
server/publications/messages.js

[NEW] code to get the updated messages

---

packages/rocketchat-emoji-emojione/client/sprites.css

[FIX] fix emoji package path so they show up correctly in browser

---

packages/rocketchat-i18n/i18n/en.i18n.json

Previously this wasn't too clear that it was for characters rather than the size for if you wanted to upload a larger file. Changed this to be more obvious by mentioning 'characters'. User-friendliness. :- )

Changed wording for "Maximum Allowed Message Size"

---

.meteor/versions
packages/rocketchat-lib/server/lib/PushNotification.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

Closes #8863 
~This is blocked by https://github.com/raix/push/pull/322 and https://github.com/raix/push/pull/321 though.~
New `raix:push` package version published so we are good to merge this as well :tada:

[NEW] Send category and title fields to iOS push notification

---

packages/rocketchat-lib/server/methods/filterATAllTag.js

Closes #8033
This was not working because `mention-all` permission was intended to be used on room scoped roles, this PR makes it check on room scope as well.

[FIX] Check for mention-all permission in room scope

---

packages/rocketchat-custom-oauth/server/custom_oauth_server.js

For users of XenForo forums using [BD]API plugin for Custom OAuth services, this change will ensure the proper arguments are passed to complete the authentication process. This was provided by user HallyNoona on XenForo community threads at https://xenforo.com/community/threads/bd-api.48900/page-19

[FIX]  Xenforo [BD]API for 'user.user_id; instead of 'id'

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-livechat/app/package-lock.json
packages/rocketchat-mentions/Mentions.js
packages/rocketchat-mentions/tests/client.tests.js

[FIX] Link for channels are not rendering correctly

---

packages/rocketchat-internal-hubot/hubot.js
packages/rocketchat-internal-hubot/settings.js
packages/rocketchat-ui/client/lib/chatMessages.js

when typing an unknown command, `rocketbot` respond, we're expecting `InternalHubot_Username`

[FIX] Change old 'rocketbot' username to 'InternalHubot_Username' setting

---

packages/rocketchat-custom-sounds/client/admin/soundInfo.js

Just a minor bug when i would like to upload custom sound and find no way to delete it.

[FIX] Cannot edit or delete custom sounds

---

packages/rocketchat-oembed/client/oembedUrlWidget.html

Closes #8977 
while rendering a message via oembedUrlWidget, use ogImage if it exists over image.

[FIX] if ogImage exists use it over image in oembedUrlWidget

---

packages/rocketchat-ui-message/client/messageBox.js

For small bug fix [https://github.com/RocketChat/Rocket.Chat.Electron/issues/589#issue](https://github.com/RocketChat/Rocket.Chat.Electron/issues/589#issue) .link of the KaTeX formatting was deprecated.

[FIX] Katex markdown link changed

---

packages/rocketchat-lib/server/lib/sendEmailOnMessage.js

Closes #8619
PR #8810 fixed an issue with DM email notifications always being sent regardless of account setting. This had an issue though if the subscription had never been set (alluded to in a comment https://github.com/RocketChat/Rocket.Chat/pull/8810#issuecomment-343900445
This PR should fix that lingering issue.

[FIX] DM email notifications always being sent regardless of account setting

---

packages/rocketchat-channel-settings/client/stylesheets/channel-settings.css
packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-theme/client/imports/forms/tags.css
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui/client/views/app/room.html

[FIX] Long room announcement cut off

---

packages/rocketchat-autolinker/client/client.js

Library default is to strip slashes, this is not helpful most of the time

[FIX] Don't strip trailing slash on autolinker urls

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-livechat/app/package-lock.json
packages/rocketchat-ui-account/client/accountPreferences.html
packages/rocketchat-ui-account/client/accountPreferences.js
packages/rocketchat-ui-sidenav/client/roomList.html
packages/rocketchat-ui-sidenav/client/roomList.js
server/methods/saveUserPreferences.js

Change 'message counter' to 'room counter'

[FIX] Wrong room counter name

---

packages/rocketchat-ldap/server/sync.js

- checks if the field is whitelisted for sync
- if a customField, checks its validity before syncing (through Accounts_CustomFields)
- fixes the case when the field is still absent in the user document
* This implementation does not allow dots in the customField name, because the dots would be treated as nested fields

[FIX] Sync of non existent field throws exception

---

.snapcraft/snapcraft.yaml
packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json

Without this snap install fails.  Also something to do with launchpad now fails with our redirect, so moved to using curl to download release.

[FIX] snap install by setting grpc package used by google/vision to 1.6.6

---

.circleci/config.yml
packages/rocketchat-ui/client/lib/notification.js

When busy notifications aren't supposed to be triggered.  Which is true... but it still dings.
That's just as disturbing as a notification scrolling by when you are trying to concentrate.
related to: #8806

[FIX] Notification sound is not disabling when busy

---

packages/rocketchat-custom-oauth/server/custom_oauth_server.js

We tried to enable oauth on unstable.rocket.chat with open.rocket.chat but couldn't because of this.

[FIX] Can't use OAuth login against a Rocket.Chat OAuth server

---

server/lib/accounts.js

The afterUserCreated callback is not called when creating a user on first CAS login. This causes inconsistent behaviour with the 'User created' integration when using CAS.
This PR adds the missing trigger after a user is created by CAS login.

[FIX] Added afterUserCreated trigger after first CAS login

---

packages/rocketchat-cas/package.js
packages/rocketchat-cas/server/cas_server.js
packages/rocketchat-cas/server/models/CredentialTokens.js

Closes #8032 
This fixes CAS login when running multiple instances of RocketChat. When using CAS, a so called credentialsToken is stored in the server process to identify login attempts via CAS pop-up. This is bad when it comes to running several instances of RocketChat because it can not be guaranteed to hit the same instance again. Thus, I changed storing those tokens in MongoDB. In addition, I added a cleanup mechanism to delete outdated tokens of failed login attempts.

[FIX] CAS does not share secrets when operating multiple server instances

---

.meteor/versions

Make it backwards compatible so it fixes this exception:
```
TypeError: undefined is not iterable
at Streamer.isReadAllowed (/app/bundle/programs/server/packages/rocketchat_streamer.js:258:37)
at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_streamer.js:356:15)
at Subscription.<anonymous> (/app/bundle/programs/server/packages/rocketchat_lib.js:2149:15)
at packages/matb33_collection-hooks.js:307:21
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1826:12)
at DDP._CurrentPublicationInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:1166:73)
at …
```

[FIX] Update rocketchat:streamer to be compatible with previous version

---

packages/rocketchat-theme/client/imports/components/modal.css
packages/rocketchat-ui/client/views/app/modal.html
packages/rocketchat-ui/client/views/app/modal.js

Fix: Confirmation modals showing `Send` button

---

packages/rocketchat-theme/client/imports/components/messages.css
packages/rocketchat-theme/client/imports/general/base.css
packages/rocketchat-theme/client/imports/general/base_old.css

Fix: Message action quick buttons drops if "new message" divider is being shown

---

.meteor/versions
tests/chimp-config.js
tests/data/checks.js
tests/pageobjects/login.page.js

Fix test without oplog by waiting a successful login on changing users

---

packages/rocketchat-api/server/v1/misc.js

Pretty much no oauth integration supports doing something like emails[0].address to grab the email address out of the /api/v1/me response.  So grabbing the email and surfacing as a property

[Fix] oauth not working because of email array

---

packages/rocketchat-i18n/i18n/en.i18n.json

Added paragraphing to email and password, and removed the irritating period that immediately followed the usage of [password] that was tripping up users who copied and pasted their passwords from the email.
Closes #9191

[FIX] Made welcome emails more readable

---

.postcssrc
package-lock.json
package.json

postcss-nesting uses the CSS rules, that are incompatible with BEM
postcss-nested uses SASS rules

Replace postcss-nesting with postcss-nested

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-account/client/avatar/avatar.js
packages/rocketchat-ui-sidenav/client/sidebarItem.html
server/startup/avatar.js

Fix: Rooms and users are using different avatar style

---

packages/rocketchat-ui/client/views/app/createChannel.js

I found that the cross icon in the users selection thing wasn't working. So I fixed it for the project I'm working using RocketChat.
So I'm sending this PR in case you guys find it handy ; )
Also I'm sending a screenshot to make it clear of which part I'm talking about.

[FIX] make the cross icon on user selection at channel creation page work

---

packages/rocketchat-theme/client/imports/forms/tags.css

Closes https://github.com/RocketChat/Rocket.Chat/issues/8785
before:
after:

[FIX] "Enter usernames" placeholder is cutting in "create channel" view

---

packages/rocketchat-file-upload/server/config/GridFS.js
packages/rocketchat-file-upload/server/lib/FileUpload.js
packages/rocketchat-file-upload/server/lib/requests.js

Fix: Upload access control too distributed

---

packages/rocketchat-api/server/api.js

Closes #9037
Only return the warning when calling routes starting with `channel(s)` or `group(s)` and the return contains the room info.

Fix: Unneeded warning in payload of REST API calls

---

.snapcraft/snapcraft.yaml

The launchpad workers don't have curl installed by default, so has to be explicitly added.

Add curl, its missing on worker nodes so has to be explicitly added

---

.docker/Dockerfile
.sandstorm/sandstorm-pkgdef.capnp
.scripts/set-version.js
.travis/snap.sh
HISTORY.md
package.json
packages/rocketchat-lib/rocketchat.info
packages/rocketchat-livechat/app/package-lock.json

Develop sync - Bump version to 0.61.0-develop

---

packages/rocketchat-ldap/server/ldap.js

LDAP/AD is only importing multiple of 500 users, the internal pagination system is not processing the rest of the records.
Closes #9279

[FIX] LDAP/AD is not importing all users

---

packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/components/icon.html
packages/rocketchat-ui/client/components/icon.js
packages/rocketchat-ui/package.js

[FIX] svg render on firefox

---

packages/rocketchat-lib/server/functions/deleteMessage.js
packages/rocketchat-lib/server/models/Messages.js

[FIX] Deleting message with store last message not removing

---

packages/rocketchat-lib/server/startup/settings.js

It's a small UX improvement about #7997 for set default footer value.

[NEW] add /home link to sidenav footer logo

---

packages/rocketchat-lib/server/functions/deleteUser.js

Bypass the cache and find the subscriptions directly from database to prevent the in memory changes while deleting.
The for each of the array in memory does not works cuz the array is changing the size.
Closes #6535

[FIX] Subscriptions not removed when removing user

---

packages/rocketchat-livechat/client/views/app/integrations/livechatIntegrationFacebook.js
packages/rocketchat-livechat/server/methods/facebook.js

This should improve livechat integration UX.
If it was the first time you're using it and you have enabled it from the admin panel you should end on an errored state and see no pages at integration page. This PR will force to fix this errored state and the user will just have to reload the pages.
This helps preventing the behavior described by https://github.com/RocketChat/Rocket.Chat/issues/9266#issuecomment-354486645

[FIX] Force enable Livechat Facebook integration on specific errors

---

packages/rocketchat-slashcommands-unarchiveroom/server/server.js

Same as #9428
When submitting a message like : `/unarchive #channel-that-dont-exist`
An exception is thrown on the server :
`Exception while invoking method 'slashCommand' TypeError: Cannot read property 't' of undefined`

[FIX] Slash command 'unarchive' throws exception if the channel does not exist 

---

packages/rocketchat-channel-settings/client/startup/messageTypes.js

In this PR I add translation support to `"room_changed_privacy"` message. Now it's always return **"Channel"** and ... for any language (it's a bug for non-English website) but with this PR we can translate **"Channel"** and any other room type too.
This PR can be useful for non-English users like me 😉

[FIX][i18n] add room type translation support for room-changed-privacy message

---

packages/rocketchat-i18n/i18n/en.i18n.json

Added text for mention-here in admin panel.
Closes #9455
Signed-off-by: Ry Jones <ry@walledcity.org>
Closes #9455
I overlooked i18n text for initial implementation of ACL for at-here. Here is the fixed version:

[FIX] mention-here is missing i18n text #9455

---

packages/rocketchat-api/server/v1/misc.js
packages/rocketchat-i18n/i18n/ca.i18n.json
packages/rocketchat-i18n/i18n/cs.i18n.json
packages/rocketchat-i18n/i18n/de.i18n.json
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/it.i18n.json
packages/rocketchat-i18n/i18n/ko.i18n.json
packages/rocketchat-i18n/i18n/ru.i18n.json

Closes #9488 
Add route:
`/api/v1/shield.svg?type=user&username=USERNAME`
Displays user's `name` and `status` as follows:
Please guide me how can I improve the code further. Thank You.

[NEW] Add route to get user shield/badge

---

packages/rocketchat-i18n/i18n/en.i18n.json

[FIX] Missing string 'Username_already_exist' on the accountProfile page

---

packages/rocketchat-gitlab/common.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/9660

[FIX] GitLab OAuth does not work when GitLab’s URL ends with slash

---

packages/rocketchat-integrations/server/processWebhookMessage.js
packages/rocketchat-oembed/server/jumpToMessage.js

If you tried to quote a message sent by: 
* integration
* anything that touched: processWebHookMessage (so both message sending endpoints)
and those messages didn't have attachments and the attachment property was null... you'd get this exception:
```
TypeError: Cannot read property 'map' of null
at recursiveRemove (/app/bundle/programs/server/packages/rocketchat_oembed.js:589:24)
at msg.urls.forEach.item (/app/bundle/programs/server/packages/rocketchat_oembed.js:609:29)
at Array.forEach (<anonymous>:null:null)
at RocketChat.callbacks.add.msg (/app/bundle/programs/server/packages/rocketchat_oembed.js:600:12)
at /app/bundle/programs/server/packages/rocketchat_lib.js:1157:27
at Array.reduce (<anonymous>:null:null)
at Object.RocketChat.callbacks.run …
```

[FIX] Messages can't be quoted sometimes

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/v1/permissions.js
packages/rocketchat-api/server/v1/users.js
tests/end-to-end/api/01-users.js
tests/end-to-end/api/11-permissions.js

[NEW] API to fetch permissions & user roles

---

packages/rocketchat-lib/server/models/Rooms.js

[FIX] API to retrive rooms was returning empty objects

---

packages/rocketchat-livechat/.app/client/views/register.js
packages/rocketchat-livechat/server/hooks/leadCapture.js
packages/rocketchat-livechat/server/hooks/sendToCRM.js
packages/rocketchat-livechat/server/lib/QueueMethods.js

- Fix department typo
- Fix lead capture depending on Facebook integration
- Fix external queue not using pre-selected agent

[FIX] Livechat issues on external queue and lead capture

---

packages/rocketchat-livechat/.app/client/lib/chatMessages.js
packages/rocketchat-livechat/.app/client/views/messages.js

Currently if a livechat is started by visitor when there is no registration form or via a trigger, after visitor sends a message it does not receive messages back due the move of livechat visitors from users to its own collection.

[FIX] Livechat conversation not receiving messages when start without form

---

packages/rocketchat-ui-flextab/client/tabs/userInfo.html
packages/rocketchat-ui-flextab/client/tabs/userInfo.js

Fix: Custom fields not showing on user info panel

---

packages/rocketchat-ui/client/lib/notification.js

Closes #9760 #9565 #7292 
The agents were not receiving sound notifications when new livechat conversations arrived.

[FIX] Not receiving sound notifications in rooms created by new LiveChats

---

.snapcraft/snapcraft.yaml

Since we flattened things a bit that folder didn't exist any more.
This will fix the snap build.
https://launchpad.net/~rocket.chat.buildmaster/+snap/candidate/+build/155010 build that succeeded after these changes.

[FIX] Snap build was failing

---

packages/rocketchat-ui-account/client/accountPreferences.html

Closes #9882
Looks like all the other dropdowns in Rocket.Chat again :)
**Before:**
**After:**

Regression: Misplaced language dropdown in user preferences panel

---

packages/rocketchat-message-attachments/client/messageAttachment.html

Improve link handling for attachments

---

packages/rocketchat-i18n/i18n/fr.i18n.json

Correcting the typo "Ouvrerture" to "Ouverture"which is the correct french word :)

[FIX] Typo on french translation for "Open"

---

packages/rocketchat-cors/cors.js
packages/rocketchat-cors/package.js
packages/rocketchat-lib/server/functions/deleteUser.js

Meteor 1.6.1 [introduced](https://github.com/meteor/meteor/pull/7277) a new default setting to MongoDB driver `ignoreUndefined: true` which can remove fields with `undefined` values from the query, that execute a different behavior than expected when deleting users without usernames executing the deletion agains all direct rooms with the query:
```javascript
{
t: 'd'
}
```
rather than
```javascript
{
t: 'd',
usernames: undefined
}
```
This PR rollback that MongoDB option and does not tries to remove data for users without username cuz they can't have message, subscriptions, rooms, etc before set their username.

[FIX] Delete user without username was removing direct rooms of all users

---

tests/chimp-config.js
tests/end-to-end/ui/06-messaging.js

I skipped our API test when I was testing UI stuff and committed by mistake.
Now I'm reactivating API tests and we have some errors, @MarcosSpessatto can you fix these erros?

[OTHER] Reactivate API tests

---

packages/rocketchat-ui-flextab/client/tabs/userEdit.html

@RocketChat/core @rafaelks @karlprieb 
Closes #9925
I think this little snip should do all the magic, but I really struggle to reproduce the issues behavior in my dev environment .. @rafaelks can you jump in?

[FIX] Browser was auto-filling values when editing another user profile

---

packages/rocketchat-ui-account/client/accountPreferences.js

Closes #10049
Closes #10001 
Fixed issue that caused user preferences to not be saved when roles are hidden in the admin settings

[FIX] User preferences can't be saved when roles are hidden in admin settings

---

imports/message-read-receipt/server/hooks.js

Editing a message with read receipts enabled are throwing this error on server's console:
```
E11000 duplicate key error index: rocketchat.rocketchat_message_read_receipt.$roomId_1_userId_1_messageId_1 dup key: { : \"aTXykw9Dkk7zb3bXXrocket.cat\", : \"aTXykw9Dkk7zb3bXX\", : \"utDHRDAdAempTqbGp\" }"
```

[FIX] Message editing is crashing the server when read receipts are enabled

---

packages/rocketchat-api/server/v1/channels.js

Fix channels.list endpoint, that wasn't returning the list of public channels correctly.
Closes #9895.

[FIX] REST API: Can't list all public channels when user has permission `view-joined-room`

---

packages/rocketchat-importer/server/classes/ImporterBase.js

And fix slack import error
Closes #10050

[FIX] Slack Import reports `invalid import file type` due to a call to BSON.native() which is now doesn't exist

---

packages/rocketchat-api/server/v1/misc.js
tests/end-to-end/api/00-miscellaneous.js

Closes #8519.
Added endpoint to get the list of available oauth services.

[NEW] Added endpoint to get the list of available oauth services

---

packages/rocketchat-custom-oauth/server/custom_oauth_server.js

This is the [schema](https://docs.nextcloud.com/server/13/developer_manual/client_apis/OCS/index.html) of the response (you can ask json instead of xml).

[FIX] Nextcloud as custom oauth provider wasn't mapping data correctly

---

packages/rocketchat-theme/client/imports/forms/switch.css

Closes #10057 
Switch button border-color same as that of its background.
Earlier:
Now:

[FIX] Wrong switch button border color

---

packages/rocketchat-autolinker/client/client.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/9485 
Closes https://github.com/RocketChat/Rocket.Chat/issues/9976
Earlier when we tried to send the url like ```https://foo.com/t='a'&s=1```, it wasnt getting detected properly.
Now it gets detected correctly:

[FIX] Apostrophe-containing URL misparsed

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-sidenav/client/sidebarHeader.js
packages/rocketchat-ui-sidenav/client/userStatus.html
packages/rocketchat-ui/client/components/header/header.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/9547

[FIX] No pattern for user's status text capitalization

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-lib/server/models/Subscriptions.js
packages/rocketchat-push-notifications/server/methods/saveNotificationSettings.js
tests/end-to-end/api/02-channels.js

Added two endpoints: GET/POST channels.notifications, that returns and updates the notification settings from a specific channel. Requested in [this](https://github.com/RocketChat/Rocket.Chat.iOS/issues/288) issue.

[NEW] Added GET/POST channels.notifications

---

packages/rocketchat-autolinker/client/client.js

Reverts RocketChat/Rocket.Chat#9739
Because it is not parsing correctly messages enclosed completely by an HTML element, like the message `_oops_`.. that would be then parsed to `<em>oops</em>` and `htmlDecode` will return an _empty string_ .

Revert "[FIX] Apostrophe-containing URL misparsed"

---

packages/rocketchat-apps/server/converters/rooms.js
packages/rocketchat-apps/server/converters/users.js

These errors were added to ensure the data to the Rocket.Chat Apps system could be guaranteed, however this sadly can not be the case as Rocket.Chat doesn't have internal data verification and ensurations.

Fix: possible errors on rocket.chat side of the apps

---

.snapcraft/resources/preparecaddy

The link previously used requires a license be specified.  So we're grabbing the one built from source so I assume its apache v2.

Fix caddy download link to pull from github

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/helpers/deprecationWarning.js
packages/rocketchat-api/server/v1/misc.js
packages/rocketchat-api/server/v1/users.js
tests/end-to-end/api/00-miscellaneous.js
tests/end-to-end/api/01-users.js

Add user roles and preferences to /me endpoint and removed the endpoint with problems, /users.roles.

[FIX] /me REST endpoint was missing user roles and preferences

---

packages/rocketchat-theme/client/imports/components/contextual-bar.css
packages/rocketchat-theme/client/imports/components/header.css
packages/rocketchat-ui/client/components/header/header.html

Fix: Scroll on content page

---

packages/rocketchat-api/server/v1/chat.js
packages/rocketchat-reactions/setReaction.js
tests/end-to-end/api/05-chat.js

Closes #10286
This happened because verification was added which checked if the emoji passed actually is one. However, this verification did not account for missing colons which has a very high chance to break existing systems.

Fix: chat.react api not accepting previous emojis

---

packages/rocketchat-ui-message/client/popup/messagePopup.js

Closes #10021 
Fixes inability to use all mentions(user, channel, slash commands) after newline.

[FIX] Unable to mention after newline in message

---

packages/rocketchat-emoji-custom/server/models/EmojiCustom.js

@RocketChat/core The issue was that enforcing the colons only worked for regular emojis but custom emojis search requires no colons in the name passed.
Closes #10286 (again)

Fix: Reaction endpoint/api only working with regular emojis

---

packages/rocketchat-i18n/i18n/de.i18n.json

Closes #10338 
I've also fixed the translation in the LingoHub Project :)

[FIX] Incorrect german translation of user online status

---

packages/meteor-accounts-saml/saml_server.js
packages/meteor-accounts-saml/saml_utils.js

Closes #10056 
SAML broke with 0.62.1 and throws a TypeError while validating a token from the IdP. As observed by @chrosey in #10056, adding '.value' in two locations of the SAML package fixes the issue.

[FIX] Add '.value' in the SAML package to fix TypeErrors on SAML token validation

---

.snapcraft/snapcraft.yaml

8.11.1 causes segfault https://github.com/RocketChat/Rocket.Chat/issues/10331 so we had to revert to 8.9.4
For some reason just switching node-engine causes issues with the snap build.  The work around is to just install from tar

[FIX] Snaps crashing due to Node v8.11.1 Segfault

---

.eslintrc
packages/rocketchat-ui-account/client/accountPreferences.js

[FIX] fixing deprecated Meteor._reload.reload method
Closes #10330

[FIX] fixing deprecated Meteor._reload.reload method

---

.github/bot-config.yml

Update allowed labels for bot

---

packages/rocketchat-integrations/server/api/api.js

Right now an incoming integration can be triggered with a regular `GET` request and if there is no script to trigger then the result is an empty message which is undesirable.

[FIX] Incoming integrations being able to trigger an empty message with a GET

---

packages/rocketchat-api/server/api.js

Closes #10401 - regular users won't see that property on the users endpoints anymore, but administrator users will.
Detail: After we added the property `settings` to the users, we forgot to include this property in our array of fields that should not go out to regular users except for when they view their own data via the rest api. The reason this is considered breaking is because we have removed a property that was added, so if you are expecting this property to be there it won't show up. Usually we deprecate these type of things, however, due to the privacy concerns we have immediately removed it.

[BREAK] The property "settings" is no longer available to regular users via rest api
