app/file-upload/server/lib/FileUpload.js, app/lib/server/functions/deleteUser.js
Introduced by https://github.com/RocketChat/Rocket.Chat/pull/17057
=> Regression: Files were been deleted when deleting users as last members of private rooms

app/ui-flextab/client/tabs/membersList.js, server/methods/getUsersOfRoom.js
this bug was introduced after the pagination, before we were used to fetch all the users than filter on the client side..
=> [FIX] Member's list only filtering users already on screen

app/apps/server/bridges/activation.js, app/apps/server/communication/websockets.js, app/models/server/raw/Users.js
=> [IMPROVE] Apps Engine: Reduce some stream calls and remove a find user from the app's status changes

app/federation/server/hooks/beforeDeleteRoom.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/15823
=> [FIX] Federation delete room event not being dispatched

app/api/server/lib/rooms.js, app/ui-admin/client/rooms/adminRooms.html, app/ui/client/views/app/components/Directory/ChannelsTab.js, app/ui/client/views/app/components/Directory/DirectoryTable.js, app/ui/client/views/app/components/Directory/UserTab.js, server/methods/browseChannels.js
=> Regression: fix design review of Directory

app/ui-admin/client/users/adminUsers.js
'Bug' introduced here: https://github.com/RocketChat/Rocket.Chat/pull/17072/files
=> Regression: Admin create user button

app/api/server/lib/users.js, app/models/server/models/Users.js, app/models/server/raw/Users.js
Raw models have to be pure and cannot depend on anything from outside.
=> Regression: Fix users raw model

app/meteor-accounts-saml/server/saml_server.js, client/routes.js
=> [FIX] SAML login errors not showing on UI

app/meteor-accounts-saml/client/saml_client.js
=> [FIX] Random errors on SAML logout

app/ui-utils/client/lib/openRoom.js, client/reactAdapters.js, package-lock.json
It fix a React tree crash when the `main` Blaze template is directly handled via DOM APIs.
=> [FIX] Unsafe React portals mount/unmount 

app/theme/client/imports/general/variables.css, packages/rocketchat-i18n/i18n/en.i18n.json, private/client/imports/general/variables.css
This will help out with white-labeling and theming, since we were sharing the same color for fonts and the background of the sidebar
=> [NEW] Add Color variable to left sidebar

app/ui-master/client/main.js
=> [FIX] Global event click-message-link not fired

app/ui/client/views/app/room.js
=> [FIX] 404 error when clicking an username

app/ui-message/client/message.html, app/ui-message/client/message.js
Super-duper small change to remove code duplication.
=> Apply $and helper to message template

app/lib/lib/roomTypes/direct.js
closes https://github.com/RocketChat/Rocket.Chat/issues/17104
closes https://github.com/RocketChat/Rocket.Chat/issues/17243
=> [FIX] Avatar on sidebar when showing real names

app/lib/server/startup/settings.js, app/models/server/models/Users.js, server/startup/migrations/v183.js
=> [FIX] User search on directory not working correctly

app/ui/client/views/app/components/Directory/ChannelsTab.js, app/ui/client/views/app/components/Directory/UserTab.js, app/ui/client/views/app/components/Directory/index.js, client/components/pageNotFound/PageNotFound.js, client/components/setupWizard/SetupWizardRoute.js, client/components/setupWizard/SetupWizardState.js, client/contexts/RouterContext.js, client/providers/RouterProvider.js, ee/app/engagement-dashboard/client/components/EngagementDashboardRoute.js, package-lock.json, package.json
It enhances the separation of components from FlowRouter.
=> New hooks for RouterContext

.storybook/mocks/meteor.js
Storybook stopped working.
Thanks to @tassoevan for the fix.
=> Regression: Storybook

app/ui-admin/client/components/mailer/Mailer.js
=> Mailer Scrollbar

app/livechat/client/views/app/livechatCurrentChats.css, app/livechat/client/views/app/livechatCurrentChats.html, app/livechat/client/views/app/livechatCurrentChats.js
Closes https://github.com/RocketChat/feature-requests/issues/318
=> [IMPROVE] Add possibility to sort the Omnichannel current chats list by column

app/lib/server/functions/saveUser.js
=> [FIX] New user added by admin doesn't receive random password email

app/importer-slack/server/importer.js
=> [FIX] Import slack's multiple direct messages as direct rooms instead of private groups

app/ui/client/lib/codeMirror/codeMirrorComponent.js
closes https://github.com/RocketChat/Rocket.Chat/issues/17313
=> [FIX] Empty Incoming webhook script field 

app/emoji-emojione/lib/rocketchat.js
Add a missing `cacheKey` as added by https://github.com/RocketChat/Rocket.Chat/pull/17391
=> Regression: Add missing cacheKey to mem

.storybook/babel.config.js, .storybook/mocks/meteor.js, ee/app/authorization/client/index.ts, package-lock.json, package.json
Added `@babel/plugin-proposal-nullish-coalescing-operator` to storybook config and updated a Meteor mockup. Added 2 type definitions that were missing.
=> regression: Fix storybook

app/utils/server/lib/normalizeMessagesForUser.js
When changing usernames the reactions became outdated since it's not possible to update the usernames stored there, so when the server users Real Name setting enabled the system process all messages before return to the clients and get the names of the usernames to show since the usernames are outdated the names will not be found. Now the usernames will be displayed when the name can't be found as a temporary fix until we change the architecture of the data to fix the issue.
=> [FIX] Reactions may present empty names of who reacted when using Real Names

app/theme/client/imports/general/base_old.css
=> [FIX] Increasing highlight time in 3 seconds

app/livechat/client/views/app/livechatDepartmentForm.js
=> [FIX] Omnichannel departments are not saved when the offline channel name is not defined

README.md
[FIX] #17039
Signed-off-by: Ry Jones <ry@linux.com>
Closes #17039
=> DPlatform is deprecated and the replacement does not support rocket.chat

app/channel-settings-mail-messages/client/views/mailMessagesInstructions.js
=> [FIX] Mail Messages > Cannot mail own user

server/methods/registerUser.js
=> [FIX] Secret Registration not properly validating Invite Token

app/ui/client/views/app/components/Directory/UserTab.js
=> [FIX] Directory search user placeholder

app/ui-message/client/blocks/index.js
- [x ] Bugfix (non-breaking change which fixes an issue)expected)
=> [FIX] UI KIT Modal Width

app/threads/client/flextab/threads.js
=> Regression: Threads list was fetching all threads

app/apps/server/converters/rooms.js
Server failed to create direct rooms with more than two users when the app-engine was turned on.
=> Regression: Fix error preventing creation of group DMs

app/theme/client/imports/components/sidebar/sidebar.css, app/ui-sidenav/client/sideNav.html
=> Regression: Force unread-rooms bar to appears over the room list

app/theme/client/imports/general/base_old.css, app/theme/client/imports/general/theme_old.css
=> Regression: Removed status border on mentions list

app/theme/client/imports/general/base_old.css
=> Regression: Adjusting spaces between OAuth login buttons

app/theme/client/imports/components/sidebar/rooms-list.css, app/theme/client/imports/components/sidebar/sidebar.css, app/ui-sidenav/client/sideNav.html
=> Regression: Fix Unread bar design

client/admin/users/UsersTable.js
=> [FIX] Administration User page blank opening users without email

app/lib/server/lib/sendNotificationsOnMessage.js
The `rid` field is missing from the subscription data used to form the message link sent via email notification
Closes #17007
=> [FIX] Omnichannel message link is broken in email notifications

app/meteor-accounts-saml/server/saml_server.js
=> [FIX] SAML LogoutRequest sending wrong NameID

.github/workflows/build_and_test.yml
Always initialize `CIRCLE_BRANCH` env var on CI to fix release cut.
=> Always initialize CIRCLE_BRANCH env var on CI

app/lib/server/methods/refreshOAuthService.js
Refreshing the OAuth services would remove every login button but only cause the regular OAuth ones to be refreshed.
Closes #12511
=> [FIX] Some Login Buttons disappear after refreshing OAuth Services

client/admin/settings/Setting.js
=> [FIX] Missing className prop in Settings Field component

server/stream/streamBroadcast.js
There was a missing spread on the value emitted, so clients were receiving an array instead of multiple values.
=> [FIX] StreamCast stream to server only streamers

packages/rocketchat-i18n/i18n/en.i18n.json
Don't have a typo
There was a typo in the word _corresponding_, it was spelled "coorosponding"
Fix typo on English LDAP page
=> Fix typo "coorosponding"

app/theme/client/imports/general/base_old.css
=> [FIX] Discussion List paddings

app/apps/client/RealAppsEngineUIHost.js
https://app.asana.com/0/633285093795758/1177305720214377/f
N/A
- Install any of apps [here](https://github.com/RocketChat/frvr-apps) (private repo)
- Turn on `Game Center` experimental feature in the Admin -> General -> Apps
- Open the game in the game center
- Check `Admin -> View Logs` or logs from terminal to see if `avatarUrl`'s value correct
=> [FIX] double slashes in avatar url

.github/workflows/stale.yml
Since we have too many stale issues I think we can run more frequently, so I'm proposing to run every 6 hours doing 50 items per run (up to 200 items per day), instead of running once a day and 30 items.
Once it doesn't find anymore stale issues we can switch back to run once a day.
=> Update stale bot to v3 and run every 6 hours

client/components/SortList.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/17621
=> [FIX] Discussion sort option even with discussions disabled

client/admin/users/CustomFieldsForm.js
Fix an issue where the page was not rendering after opening the user edit screen.
As an admin, try to edit an user data when there's no custom fields configured.
=> [FIX] UI is not rendering when trying to edit an user

app/file-upload/ufs/AmazonS3/server.js
Regressions introduced by https://github.com/RocketChat/Rocket.Chat/pull/10372
=> Regression: Fix AWS S3 file retrieval

client/hooks/useFileInput.js
=> Regression: Image Upload not working

client/admin/users/CustomFieldsForm.js
Trying to open the user edit panel causes the whole UI to stop rendering.
=> Regression: Admin User Edit panel is broken

client/admin/users/EditUser.js, client/hooks/useEndpointUpload.js
=> Regression Admin: uploading foreign profile image changes own image

client/admin/users/EditUser.js
=> Regression: Cannot save avatar change on admin

packages/rocketchat-i18n/i18n/en.i18n.json
=> [FIX] Missing i18n key for setting: Verify Email for External Accounts

app/lib/server/functions/processWebhookMessage.js
Incoming WebHook messages were saved with an empty tmid
=> Regression - Incoming WebHook messages not showing up on the channel

client/admin/rooms/EditRoom.js
=> Regression: Favorite and Featured fields not triggering changes

client/admin/users/EditUser.js
The "Status Message" field is not loading or saving it's value to the user document.
=> Regression - Unable to edit status on the Edit User panel of the admin

app/ui-message/client/message.js
Inside threads the first message was always grouping
=> Regression: Fix wrong message grouping inside threads

app/ui-message/client/message.js
Reverts RocketChat/Rocket.Chat#18039
=> Revert "Regression: Fix wrong message grouping inside threads"

app/utils/lib/roomExit.js
=> Regression: Fix exit-room on livechat

app/ui-message/client/message.js, app/ui-message/client/messageThread.js
=> Regression: Fix mentions on thread preview

app/models/server/models/Messages.js
=> Regression: Fix update last message on delete

app/utils/server/functions/getDefaultUserFields.js
=> [FIX] Avatar ETag missing from User

server/startup/migrations/v185.js, server/startup/migrations/v187.js
=> [FIX] Old Data Migrations breaking upgrades

package-lock.json, package.json
Update Apps-Engine version dependency
=> [NEW] Update Apps-Engine version

client/lib/meteorCallWrapper.ts
=> [FIX] Application not loading due to reverse proxy decoding API calls unnecessarily

app/meteor-accounts-saml/server/lib/Utils.ts, app/meteor-accounts-saml/tests/server.tests.ts
=> [FIX] SAML login crashing when receiving an array of roles

client/admin/apps/AppsWhatIsIt.js
Administrators look at the page "Apps: What Are They?" will see a link to https://go.rocket.chat/i/developing-an-app.
=> [FIX]Update link URL at AppsWhatIsIt

client/hooks/useForm.ts
Removes `console.time()` calls in `useForm` hook.
=> Regression: Remove calls to Console API in useForm hook

app/theme/client/imports/components/messages.css
=> Regression: Message actions under "unread messages" warning

client/account/AccountProfilePage.js, client/account/AccountRoute.js, client/account/preferences/PreferencesMyDataSection.js, client/account/tokens/AccountTokensPage.js, client/account/tokens/AccountTokensTable.js, client/account/tokens/AddToken.js, client/account/tokens/InfoModal.js, client/hooks/useEndpointDataExperimental.js
=> [NEW] Personal Access Tokens rewritten

client/account/AccountProfilePage.js
=> Regression - Profile page crashing for users without password

package-lock.json, package.json
Update Apps-Engine to the current Beta (1.16) that will be released along with Rocket.Chat v3.5
=> Update Apps-Engine to Beta version

app/ui-utils/client/lib/SideNav.js, app/utils/lib/roomExit.js
=> [FIX] Closing the admin does not return to last opened room

client/admin/users/UserInfoActions.js, client/providers/MeteorProvider.js
=> [FIX] Delete user warning message undefined

app/livechat/server/lib/Helper.js, ee/app/canned-responses/client/startup/responses.js, ee/app/canned-responses/server/hooks/onRemoveAgentDepartment.ts, ee/app/canned-responses/server/hooks/onSaveAgentDepartment.ts, ee/app/canned-responses/server/index.js, ee/app/models/server/models/CannedResponse.js
- Logged in as an agent, open the `Canned responses` list (Omnichannel room)
- Logged in as a manager, open a Livechat Department that has at least one `Canned Response` (scope department)
- Add the agent to the department
**Current version:**
- Nothing happens on the Agent's Canned Responses List
**After this implementation:**
- The Department`s Canned Response(s) will be displayed and available automatically
=> [FIX][ENTERPRISE] Canned Responses not available to agents after they are added to departments

app/ui/client/views/app/room.js
The "Join" button currently appears in the messageBox on threads when the room is readonly, even though the user has a subscription already.
=> [FIX] "Join" button on thread when room is read only

app/models/server/raw/BaseRaw.js, app/models/server/raw/LivechatDepartment.js, ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.html, ee/app/livechat-enterprise/client/views/app/customTemplates/livechatDepartmentCustomFieldsForm.js, ee/app/livechat-enterprise/server/business-hour/Custom.ts
- Remove from the database a business hour associated with a department
- Open the department
- Look at the Network/XHR Tab on your browser console
=> [FIX] Error when fetching a nonexistent business hour from the server

.meteor/versions
Closes https://github.com/RocketChat/Rocket.Chat/issues/17815
=> [FIX] SlackBridge error

client/admin/users/UserForm.js, client/admin/users/UserInfoActions.js, client/components/basic/avatar/UserAvatarEditor.js
This fixes: 
BEFORE:
AFTER
BEFORE:
AFTER:
BEFORE:
AFTER:
=> Regression: Admin User password 

client/components/basic/UserInfo.js
On certain resolutions the image on the user view tab can misalign, this fixes it
=> Regression: Userinfo center avatar image

README.md
=> Broken link on readme

app/threads/client/flextab/thread.js
Open thread, close thread, try to edit the thread's main message. It'll try to edit the message in the closed messageBox.
=> Regression: Edit messages after opening thread

client/contexts/UserContext.ts
=> Regression: useUserContext

package-lock.json, package.json
=> Update Apps Engine

.github/workflows/build_and_test.yml
Make sure there is no type script error before building.
=> Add type checking to CI

app/videobridge/client/views/videoFlexTab.js
closes https://github.com/RocketChat/Rocket.Chat/issues/18140
=> [FIX] Appending 'false' to Jitsi url

app/livechat/imports/server/rest/inquiries.js
The `livechat/inquiries.take` was checking a permission design to be assigned to `admins` and `managers` only, so `agents` weren't able to take inquiries from other clients other than the web client, which is still using the `livechat:takeInquiry` meteor method.
Since the endpoint calls the same `livechat:takeInquiry` meteor method, there is no reason to check additional permission.
CLOSES #18440
- As a user who have the `livechat-agent` role, try to take an omnichannel Inquiry through the `livechat/inquiries.take` REST endpoint;
- The request won't be accepted due to the wrong/unecessary permission checked
=> [FIX] Omnichannel Take Inquiry endpoint checking wrong permission

app/ui/client/lib/recorderjs/audioEncoder.js, server/startup/migrations/index.js, server/startup/migrations/v202.js
`audio/mp3` is not a [valid MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), the correct MIME type for this extension is `audio/mpeg`.
This is the reason we're facing issues when sharing files with external applications, the `Content-type` header parameter isn't recognized as a valid MIME type.
=> [FIX] Invalid MIME type when uploading audio files

packages/rocketchat-i18n/i18n/en.i18n.json
Correct typo.
Typo in message.
- [x ] Documentation Update (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x ] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ x] I have added necessary documentation (if applicable)
- [ x] Any dependent changes have been merged and published in downstream modules
=> Fix typo in setting description

app/lib/server/functions/saveUser.js, app/lib/server/lib/PasswordPolicyClass.js
Try to generate a random password containing all the possible required options of the policy.
Closes #17785
Generates a password with all the possible requirements of the Password Policy and matching the size limitations when enabled.
=> [FIX] Random generated password not matching the Password Policy

client/channel/UserCard/index.js, client/components/basic/UserCard.js
=> [FIX] UserCard avatar cache (avatarETag)

client/omnichannel/appearance/AppearanceForm.js
=> Add missing fields

app/cloud/server/index.js, app/version-check/server/index.js
Defer some startup checks to prevent rocket.chat from being stuck on start up.
Closes #18496
=> Defer startup checks

app/lib/server/startup/oAuthServicesUpdate.js
=> [FIX] Enabling Apple OAuth crashes other OAuth services

client/admin/users/UserInfo.js
=> [FIX] Users page in admin not working for inactive user joining

client/account/sidebarItems.js, client/admin/sidebarItems.js, client/components/basic/Sidebar.js, client/helpers/createSidebarItems.js
=> [FIX] React being loaded on the main bundle

app/e2e/client/rocketchat.e2e.js, client/startup/startup.js, packages/rocketchat-i18n/i18n/en.i18n.json
=> [NEW] Banner for servers in the middle of the registration process

client/omnichannel/triggers/EditTriggerPage.js, client/omnichannel/triggers/NewTriggerPage.js, client/omnichannel/triggers/TriggersTable.js
=> [FIX] Omnichannel triggers

client/components/basic/UserCard.js, client/components/basic/UserCard.stories.js, client/components/basic/UserInfo.js, client/components/basic/UserInfo.stories.js
=> [IMPROVE] UserCard and UserInfo Show Real Names Setting

app/ui-sidenav/client/userPresence.js, imports/startup/client/listenActiveUsers.js
=> Improve performance of client presence monitor

app/ui/client/lib/notification.js
closes https://github.com/RocketChat/Rocket.Chat/issues/18441
=> Regression: Revert silent: true

app/version-check/server/index.js
=> Regression: Update checker not being disabled properly.

client/admin/users/UserForm.js, client/channel/ExportMessages/index.js, client/components/basic/Buttons/ActionButton.js, client/components/basic/PlanTag.js, client/components/basic/Sidebar.js
=> Regression: Margins on Export Messages

ee/client/omnichannel/tags/EditTag.js, ee/client/omnichannel/tags/TagsRoute.js, ee/client/omnichannel/units/EditUnit.js, ee/client/omnichannel/units/UnitsRoute.js
=> Regression: Omnichannel Tags and Units issues

app/ui-flextab/client/tabs/userActions.js, client/channel/hooks/useUserInfoActions.js
=> Regression: Toast Messages

imports/client/hepburn
The web client breaks on Internet Explorer 11 🤮 because, after updating `limax`, a package called [`hepburn`](https://github.com/lovell/hepburn) was included adding some arrow functions to the final bundle.
See the web client on Internet Explorer 11 🤢
=> Regression: Bundle the package `hepburn`

client/omnichannel/businessHours/EditBusinessHoursPage.js, ee/client/omnichannel/BusinessHoursTable.js, ee/client/omnichannel/additionalForms/BusinessHoursMultiple.js
=> Regression: Omnichannel Business Hours Issues

client/omnichannel/customFields/CustomFieldsTable.js, packages/rocketchat-i18n/i18n/en.i18n.json
=> Regression: Add remove popup to omnichannel custom fields

client/channel/ExportMessages/index.js
=> Regression: Split date fields on export messages contextual bar

client/channel/ExportMessages/index.js
=> Regression: Use user autocomplete on export messages

app/ui/client/views/app/room.js
=> [FIX] e.sendToBottomIfNecessaryDebounced is not a function

app/webdav/server/methods/uploadFileToWebdav.js
=> Fix: Missing WebDav upload errors logs

package-lock.json, package.json
=> [FIX] IE11 support livechat widget

client/account/AccountProfilePage.js
=> [FIX] Can't change password

client/admin/users/UserInfo.js
=> [FIX] Admin user

ee/app/livechat-enterprise/server/startup.js
The status of the Agents' Omnichannel service was changing to offline whenever the server was started. This was happening because the `Livechat_enable_business_hours` setting wasn't being checked properly.
=> [FIX][ENTERPRISE] Omnichannel service status switching to unavailable

app/lib/server/functions/addUserToRoom.js, app/livechat/lib/LivechatRoomType.js, app/livechat/server/startup.js, app/tokenpass/server/startup.js, packages/rocketchat-i18n/i18n/en.i18n.json
Omnichannel users(admins) weren't able to invite other agents to join the chat. This is a very useful feature, so community, and also customers were complaining about the issue.
Closes https://github.com/RocketChat/Rocket.Chat/issues/18023
- Access an Omnichannel Chat
- Use the `/invite` command to invite other agents to join the chat
- Nothing happens
=> [FIX] User can't invite or join other Omnichannel rooms

client/omnichannel/currentChats/CurrentChatsRoute.js
The filter "Status" was using a wrong value to filter open conversations: `open` instead of `opened`.
=> [FIX] Omnichannel Current Chats open status filter not working

app/videobridge/server/methods/jitsiSetTimeout.js
Not faking a `@here` mention when starting a Jitsi call to prevent it from updating all subscriptions for a room.
=> [FIX] Jitsi call start updating subscriptions

app/slashcommands-inviteall/server/server.js
This closes the issue [ #18413](https://github.com/RocketChat/Rocket.Chat/issues/18413).
[ #18413](https://github.com/RocketChat/Rocket.Chat/issues/18413)
Fix slash commands (invite-all-from and invite-all-to) to accept  multi-byte room names.
=> [FIX] invite-all-from and invite-all-to commands don't work with multibyte room names

imports/message-read-receipt/server/hooks.js
=> [FIX] Read receipts showing blank names and not marking messages as read

app/file-upload/server/lib/proxy.js
Change UFS proxy middleware to avoid catching non-upload requests.
This closes the issue [#16174](https://github.com/RocketChat/Rocket.Chat/issues/16174)
Avoid non-upload request to be caught by UFS proxy middleware.
=> [FIX] Non-upload requests being passed to UFS proxy middleware

app/version-check/server/index.js
Fixes versionCheckJob by wrapping it in Meteor environment
Resolves #18915
=> [FIX] Version update check cron job

client/channel/hooks/useUserInfoActions.js
=> [FIX] Ignore User action from user card

app/lib/server/functions/validateCustomFields.js, client/components/CustomFieldsForm.js
=> [FIX] Custom fields required if minLength set and no text typed.

app/message-attachments/client/messageAttachment.js
=> [FIX] PDF not rendering

app/discussion/server/permissions.js
The present MR removes spurious 'expert' role that is part of the startup data. The 'expert' role is no longer a valid startup role but is still assigned as initial data for two permissions.
=> [FIX] Spurious expert role in startup data

app/reactions/client/init.js, app/ui-message/client/message.html, app/ui-message/client/message.js
Now both "Add Reaction" buttons should behave the same (the one on the side of the message, and the one on the message actions).
closes #18133
=> [FIX] Reaction buttons not behaving properly

client/account/preferences/PreferencesMyDataSection.js
=> [FIX] "Download my data" popup showing HTML code.

app/ldap/server/sync.js
=> [FIX] Errors in LDAP avatar sync preventing login

app/apps/server/bridges/listeners.js, app/livechat/server/lib/Livechat.js, package-lock.json, package.json
Triggers events when information related to a livechat's guest or room gets updated.
https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/270
=> [NEW][Apps] Add support for new livechat guest's and room's events

client/admin/users/UserInfo.js, client/admin/users/UserInfoActions.js, client/components/basic/UserInfo.js
* Display emails correctly
* Display name/username correctly
*Fixed alignment
* `Make Admin` action now appears only when user has username, as it's required in the backend.
=> [FIX] User Info: Email and name/username display, alignment on big screens, make admin action

app/api/server/v1/users.js, imports/users-presence/server/activeUsers.js
Notify logged users via WebSockets message when a user changes status via REST API.
[#18587](https://github.com/RocketChat/Rocket.Chat/issues/18587)
Notify logged users via WebSockets message when a user changes status via REST API.
=> [FIX] API call users.setStatus does not trigger status update of clients

app/models/server/models/Settings.js, app/settings/server/functions/settings.ts, client/views/setupWizard/steps/SettingsBasedStep.js, server/publications/settings/index.js
[NEW] Option to require settings on wizard UI via ENV variables
=> [NEW] Option to require settings on wizard UI via ENV variables

app/theme/client/imports/general/base_old.css
=> [FIX] Scrollbar mention ticks always rendering as white

app/ldap/server/sync.js
=> [FIX] LDAP avatar upload

app/authorization/server/streamer/permissions/emitter.js, server/publications/settings/emitter.js
=> Obbey to settings properties

app/apps/server/bridges/http.js, package-lock.json, package.json
This PR allows apps to specify `encoding` option while performing an HTTP request.
In this way, apps can download binary data (Buffer) from an URL instead of `utf8` string only.
Forward `encoding` option into `npmRequestOptions`.
https://open.rocket.chat/group/t9xgtnadgqwf3xkzh?msg=x5EsHiqtzv7rJj3qR (Private)
```js
import { IAppAccessors, IHttp, ILogger, IModify, IPersistence, IRead } from '@rocket.chat/apps-engine/definition/accessors';
import { App } from '@rocket.chat/apps-engine/definition/App';
import { ILivechatRoom } from '@rocket.chat/apps-engine/definition/livechat';
import { IMessage, IPostMessageSent } from '@rocket.chat/apps-engine/definition/messages';
import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';
import { RoomType } from …
```
=> [NEW][Apps] Add support to the "encoding" option in http requests from Apps

package-lock.json, package.json
Update Apps-Engine to latest release.
The code is already inside the repo, this is just a version bump.
=> [NEW] Apps-Engine v1.18.0

client/admin/apps/AppSettings.js
Pass the `values` of app settings to `InputComponent`
https://open.rocket.chat/group/t9xgtnadgqwf3xkzh?msg=niZBFrrzm9edCdfqC (Private)
```js
import {
IAppAccessors, IConfigurationExtend, IConfigurationModify, IEnvironmentRead, IHttp, ILogger, IRead,
} from '@rocket.chat/apps-engine/definition/accessors';
import { App } from '@rocket.chat/apps-engine/definition/App';
import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';
import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';
export class AppSettingsApp extends App {
constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
super(info, logger, accessors);
}
public async initialize(configurationExtend: IConfigurationExtend, environmentRead: IEnvironmentRead): Promise<void> { …
```
=> Regression: Elements select & multiSelect not rendered correctly in the App Settings

app/lib/server/functions/getFullUserData.js
Closes #18821
Mentioned in the issue linked above.
=> [FIX] Missing "Bio" in user's profile view (#18821)

client/omnichannel/triggers/TriggersTable.js
=> [FIX] Omnichannel: triggers page not rendering.

ee/client/audit/VisitorAutoComplete.js
`VisitorAutoComplete` component was using a wrong property as `value` and this is causing issues on important features, such as `Auditing`, as shown below:
- Open Auditing panel
- Go to `Omnichannel` tab
- Filter any conversations
- Error `Room doesn`t exist` is raised
=> [FIX] VisitorAutoComplete component

client/account/sidebarItems.js, client/admin/sidebarItems.js, client/components/basic/Sidebar.js, client/omnichannel/routes.js
=> [FIX] Admin Sidebar overflowing

app/integrations/client/streamer.js, client/admin/integrations/edit/OutgoingWebhookHistoryPage.js
=> [FIX] Integrations history page not reacting to changes.

ee/client/omnichannel/units/EditUnit.js, ee/client/omnichannel/units/UnitsRoute.js
[FIX] Selecting the same department for multiple units
=> [FIX] Selecting the same department for multiple units

ee/client/omnichannel/priorities/EditPriority.js
[FIX] Error when editing priority and required description
=> [FIX] Error when editing priority and required description

app/threads/server/functions.js
=> [FIX] Thread view in a channel user haven't joined (#19008) 

client/omnichannel/appearance/AppearancePage.tsx, client/omnichannel/sidebarItems.js
[FIX] Appearance label and reset button
=> [FIX] Livechat Appearance label and reset button

client/components/CustomFieldsForm.js
=> [FIX] Adding missing custom fields translation in my account's profile

ee/client/omnichannel/tags/EditTag.js
[FIX] Remove requirements to tag description and department
=> [FIX] Remove requirements to tag description and department

.github/issue-close-app.yml
This PR updates the comment of @issue-close-app to include all section that are being checked within the proposed PR body.
`Version of Rocket.Chat Server` was missing here.
Not related to RC releases
=> Update comment of "issue-close-app"

app/ui/client/components/header/headerRoom.html, app/ui/client/components/header/headerRoom.js
channel avatar was not appearing in the top bar unlike direct message
#19083 
display channel avatar in top bar
=> [IMPROVE] Display channel avatar on the Header

app/lib/server/functions/notifications/mobile.js
Don't add the room name to notification payload if the setting `Show Channel/Group/Username in Notification` is turned off.
Closes #17135
=> [FIX] Don't send room name on notification

client/lib/userData.ts, definition/IUser.ts
=> Regression: Reassessment of client helpers 'XYZ key should not contain .'

app/meteor-accounts-saml/server/loginHandler.ts
Return the SAML login error to the user instead of undefined error..
#18648
1. Enable SAML auth on the admin panel settings
2. Choose user without 'email' field provided by the SAML auth
3. Try to login with this user
Fixed the SAML login undefined error message
=> [FIX] SAML login undefined error message

app/api/server/v1/rooms.js, client/startup/contextualBar/exportMessages.js
=> [FIX] "Export Messages" only works for global roles 

app/ldap/server/syncUsers.js
=> [FIX] LDAP Sync Error Dup Key

app/metrics/server/lib/collectMetrics.js, app/metrics/server/lib/metrics.js, app/statistics/server/lib/getAppsStatistics.js, app/statistics/server/lib/statistics.js
=> [NEW] Apps prometheus metrics

client/admin/users/UserInfo.js, client/components/CustomFieldsForm.js, client/lib/getUserEmailAddress.ts
Also small fix to custom fields
closes https://github.com/RocketChat/Rocket.Chat/issues/18435
[FIX] Broken user info when a user don't have an email
=> [FIX] Broken user info when a user don't have an email

client/components/basic/UserInfo.js
=> [FIX] Use etag on user info

app/api/server/v1/autotranslate.js, app/autotranslate/client/lib/autotranslate.js, app/ui-message/client/message.js, client/startup/startup.js
Closes #19260
Closes #19027 
Closes #18662 
Closes #18782
=> [FIX] Server Errors on new Client Connections

client/channel/Threads/ContextualBar/List.js, client/polyfills/index.js
Sometimes after changing the filter subscribed -> unread we can see some wrong items
=> [FIX] Thread List showing wrong items

client/admin/permissions/PermissionsTable.js
=> Regression: GenericTable.HeaderCell does not accept on click anymore

app/statistics/server/lib/statistics.js, ee/app/license/server/getStatistics.ts, ee/app/license/server/index.ts
Add enterprise data to rocket.chat statistics represented by the following type:
```typescript
type ENTERPRISE_STATISTICS = {
modules: string[];
tags: string[];
}
```
=> [NEW] Add enterprise data to statistics

app/apps/server/communication/methods.js
It was already required since they call `settings.set` (which internally calls `saveSetting` method that requires 2FA) but since it was not explicitly requiring it, it was falling because when calling the underlying method the 2FA data was not being passed along.
This was causing an issue preventing apps from being enabled from the "Apps" screen on admin.
=> [FIX] Require 2FA to enable/disable apps

client/omnichannel/currentChats/CurrentChatsPage.js
Fixing a typo error on omnichannel - current chats page.
Omnichannel panel > current chats, you'll see a label with the bug.
=> [FIX] Omnichannel - typo error label at current chats page

client/lib/userData.ts, definition/IUser.ts
When converting `client/lib/userData.ts` to TypeScript, a change introduced in #18237 was reverted.
=> Regression: Pass `unset` parameter of updated `userData` notification

app/threads/client/components/ThreadComponent.js, app/threads/client/components/ThreadComponent.tsx, app/threads/client/components/ThreadView.tsx, definition/IMessage.ts, package-lock.json
- Does NOT ignore that the initial state of `message` could be `undefined`;
- Convert `message._updatedAt` type from REST API from `string` to `Date`;
- Checks `_id` and `_updatedAt` to bail-out re-renderings;
- Pass data to the `thread` template without reactivity.
=> Regression: Thread component not updating its message list

server/modules/listeners/listeners.module.ts
The data being emitted to the streamer was changed by mistake during micro services rewrites.
=> Regression: Fix stream-room-data payload

package-lock.json, server/modules/watchers/publishFields.ts
The `visitor` field was missing on the subscript schema sent to the client.
=> Regression: Fix visitor field missing on subscription payload

client/omnichannel/agents/AgentInfo.js
=> Regression: Agent Status leading to broken page

client/sidebar/RoomList.js, client/sidebar/RoomMenu.js
=> Regression: unable to mark room as read

client/sidebar/RoomList.js
=> Regression: Sidebar message preview escaping html

ee/server/broker.ts, ee/server/services/ddp-streamer/DDPStreamer.ts, server/sdk/lib/LocalBroker.ts, server/sdk/types/IBroker.ts
Implement an interface for services to register metrics.
`metrics` property is optional to interface `IBroker` for now, so it was implemented only on `NetworkBroker` that is currently using it.. `LocalBroker` doesn't have it, we can figure something out later the better way to implement in both brokers.
=> Micro Services: Add metrics capability to Services

client/sidebar/RoomList.js
=> Regression: Sidebar reactivity when read last messages

app/apps/server/bridges/messages.js, ee/server/services/ddp-streamer/DDPStreamer.ts, server/sdk/lib/Events.ts
For some reasons we had two events, but one of them was not supposed to be there =P
=> Unify ephemeral message events

client/sidebar/RoomMenu.js
=> Regression: `Leave Room` modal not closing

package-lock.json, package.json
Update livechat dependency to [1.7.6](https://github.com/RocketChat/Rocket.Chat.Livechat/releases/tag/v1.7.6).
=> Bump Livechat widget 

client/channel/Threads/ContextualBar/List.js
Tested with unloaded messages as well
- [] Improvement (non-breaking change which improves a current function)
- [] New feature (non-breaking change which adds functionality)
Regression: Fix Thread List order
=> Regression: Fix Thread List order

package-lock.json, package.json
Update Apps-Engine dependency to the `@latest` version.
This is simply a promotion from the last beta version, all the new code is already merged to this repo.
=> Update Apps-Engine to latest release

server/modules/listeners/listeners.module.ts
The new micro services code were using the wrong streamer (`notify-logged` instead of `notify-user`) for sending ephemeral message causing them to not work at all (first saw happening to Apps trying to use `notifyUser`).
- You can try using the command `/invite` to invite an invalid user, it should generate an ephemeral message saying the user doesn't exist.
=> Regression: Fix ephemeral message stream

app/ui/client/views/app/createChannel.html
=> [FIX] Channel creation not working on IE

app/emoji-custom/server/startup/emoji-custom.js
=> [FIX] Custom Emojis PNGs on IE11

package-lock.json, package.json
=> [FIX] Update Polyfills and fix directory in IE

ee/app/engagement-dashboard/client/components/MessagesTab/MessagesPerChannelSection.js, ee/app/engagement-dashboard/client/components/UsersTab/NewUsersSection.js
Made a few adjustments to the engagement dashboard graphs.
=> [FIX] Engagement dashboard: graphs adjustment

client/account/AccountProfilePage.js
Since today we ask the TOTP verification to any small change in the user profile, I've made necessary to verify when changing an avatar too.
Closes https://github.com/RocketChat/Rocket.Chat/issues/17981
[FIX] TOTP Being ignored when changing our own avatar
=> [FIX] TOTP Being ignored when changing our own avatar

client/account/preferences/PreferencesMessagesSection.js
[FIX] Restore Message View Mode Preference
=> [FIX] Restore Message View Mode Preference

client/views/setupWizard/steps/AdminUserInformationStep.js
If a user inserts a invalid username, he cannot proceed with the wizard.
The way it was being done was creating conflicts with the default form validation and the validation on `onSubmit()`
If it fixes a bug or resolves a feature request, be sure to link to that issue below. -->
Closes https://github.com/RocketChat/Rocket.Chat/issues/19476
[FIX] Setup Wizard User Creation Locking up
=> [FIX] Setup Wizard User Creation Locking up

client/admin/apps/AppDetailsPageContent.tsx, client/components/basic/avatar/UserAvatarEditor.js
=> Regression: Fix Avatar x40

app/ui/client/views/app/photoswipe.html, app/ui/client/views/app/photoswipe.js
This also fixes the invisible element on top of the screen
=> REGRESSION: Photoswipe not working 

app/ui/client/views/app/photoswipe.js
=> Regression: Fix wrong template on photoswipe

app/models/server/raw/LivechatVisitors.js
A quick fix in order to search correctly a visitor via "livechat/visitors.search" endpoint.
=> [FIX] Regex was not working properly on visitors.search endpoint

app/channel-settings/client/views/channelSettings.js
=> Regression: Room Info Edit action

client/components/basic/RoomInfo.js
@ggazzo Maybe we could improve the time information here: "30 ... what?"
=> Regression: Room Info maxAgeDefault variable

app/models/server/models/_oplogHandle.ts
While we don't currently use this operation from our models, external tools (like Robo 3T) can perform this operation, and even more important, this is supported by the oplog implementation, so it makes totally sense to support it when using change streams as well.
This is the event triggered to [processOplogRecord](https://github.com/RocketChat/Rocket.Chat/blob/ae87fe533922d5cd6e5de07e77dd17ef775297ff/app/models/server/models/_BaseDb.js#L210) when using **oplog** and changing a field on `users` collection:
```
I20201117-20:55:39.878(-3)? processOplogRecord rocket.cat {
I20201117-20:55:39.878(-3)?   ts: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1605657339 },
I20201117-20:55:39.878(-3)?   t: 4,
I20201117-20:55:39.879(-3)?   h: 0,
I20201117-20:55:39.879(-3)?   v: 2, …
```
=> [IMPROVE] Add support to `replace` operation when using Change Stream

app/models/server/raw/Messages.js, app/models/server/raw/Users.js, ee/app/engagement-dashboard/server/lib/messages.js, ee/app/engagement-dashboard/server/lib/users.js
If you're Community version with using Mongo 3.x and then upgrade to Enterprise version, you'll probably get the following error:
```
=== UnHandledPromiseRejection === 
MongoError: Unrecognized expression '$toInt'
rocketchat-server.rocketchat-server[4584]: at Connection.<anonymous> (/snap/rocketchat-server/1442/programs/server/np
m/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:450:61)
...
```
=> [FIX] Engagement dashboard on old Mongo versions

.docker-mongo/Dockerfile
Looks like latest Mongo ubuntu package depends on `systemctl` which is not included on Docker image `node:12.18.4-buster-slim` which was causing the build to fail. I'm now sticking to Mongo 4.2.10 that works fine (btw, latest official Docker image of Mongo is using 4.2.10 too https://github.com/docker-library/mongo/blob/cd315c60d63f034cf9556dc947b90a92eb535f09/4.2/Dockerfile )
I'm following Mongo tutorial on how to install a specific release https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/#install-the-mongodb-packages
=> Fix Docker preview image build

app/ui/client/views/app/room.js
=> [FIX] Issue with drag and drop

app/oembed/server/server.js
Give a max-width style for embed Youtube iframe.
=> [FIX] Size of embed Youtube on threads for small screens

app/theme/client/imports/components/header.css, app/ui/client/components/header/headerRoom.js
=> [FIX] Prevent headerRoom's click to open room/direct info

app/autotranslate/server/autotranslate.js, app/autotranslate/server/deeplTranslate.js, app/autotranslate/server/googleTranslate.js, app/autotranslate/server/methods/getProviderUiMetadata.js, app/autotranslate/server/methods/getSupportedLanguages.js, app/autotranslate/server/methods/translateMessage.js, app/autotranslate/server/msTranslate.js
Since we are rewriting the frontend, we need to test the tool, then we realize that it just doesn't work! There are some ways to activate it (changing the current provider a few times) but this is a feature ... not desired ... In addition to correcting the problem, I brought or little more meaning to the life of `TranslationProviderRegistry`
=> [FIX] Auto Translate

app/settings/server/functions/settings.tests.ts, app/settings/server/functions/settings.ts
When adding new settings, make sure the cache is up to date.
[FIX] settings may not update immediately
=> [FIX] Settings may not update internal cache immediately

app/models/server/models/Messages.js, server/startup/migrations/index.js, server/startup/migrations/v210.js
I checked that a query to mongo `Messages.find({slackTs: 'value'})` doesn't use an index and it checks all documents in the collection. This PR updates the index for `slackTs` field
=> [IMPROVE] SlackBridge threads performance improvement

app/api/server/v1/users.js, tests/end-to-end/api/01-users.js
When operating Rocket.Chat via API (e. g. in ChatOps), the technical user needs to authenticate in order to interact with the system. If the API consumer does not log out, new session tokens are acquired but never destroyed. Practically, those are all open session with a pending log out. Up to now, there is no option to terminate sessions via API without utilizing the origin login token.
This exposes the already existing function to log users out from other clients via API.
Automated tests are included in this PR
=> [NEW] REST endpoint to log user out from other clients

app/theme/client/imports/general/base_old.css, client/components/basic/RoomInfo.js
=> Regression: Collapsed messages container in safari

client/channel/Discussions/ContextualBar/List.js, client/channel/Threads/ContextualBar/List.js
=> Regression: Verticalbar size

client/reactAdapters.js
=> Regression: Fix multiple react blazed template rendering at the same time

app/models/server/models/Sessions.js, app/models/server/models/Sessions.tests.js, app/models/server/raw/Sessions.js, app/statistics/server/lib/SAUMonitor.js, app/statistics/server/lib/getMostImportantRole.js, app/statistics/server/lib/getMostImportantRole.tests.js, server/startup/migrations/index.js, server/startup/migrations/v211.js
Returns Daily/Monthly Active Users by role within the current report.
=> Report DAU and MAU by role

app/authorization/server/startup.js
=> Fix permission duplicated error on startup causing CI to halt

app/oembed/server/server.js
The URL preview doesn't work when "copy-paste" at chat. A optional chaining was required as a solution to avoid javascript exception error.
=> Regression: URL preview problem

app/lib/server/functions/setRoomAvatar.js
When broadcasting room avatar update events provide room id through the _id key as the IRoom interface suggests.
[Rocket Chat home screen] -> Administration -> Rooms -> *select any room* -> *upload new avatar* -> save
[FIX] Room avatar update event doesn't properly broadcast room id
=> [FIX] Room avatar update event doesn't properly broadcast room id

app/lib/server/lib/validateEmailDomain.js
Add defensive null checks before consuming data from settings.
Closes #19644
[FIX] Crash on setting email whitelist and blacklist
=> [FIX] Server crash while reading settings for allowed and blocked email domain lists

client/views/blocks/index.js
=> [FIX] UIKit Modal not scrolling

client/sidebar/RoomList.js
=> [FIX] Sidebar UI disappearing

client/routes.js
Update import location for Account Route
*click on profile picture* -> My Account
=> Regression:  "My Account" page doesn't load

app/models/server/models/_oplogHandle.ts, app/models/server/models/_oplogUrlParser.js
Looks like the URL parser we were importing from `mongodb/lib/url_parser` is the legacy URL parser, the new one is the default since driver version 3.3.3 (https://github.com/mongodb/node-mongodb-native/commit/52d76e33af895261c869cd29486097506ada0806) so we should use it, as this is the parser used to create connections everywhere else.
The main issue with the legacy parser is that it doesn't support encoded characters like `P%24ssw0rd%21`, showing an error like this on startup:
```
Error parsing database URL (mongodb://rctestuser:P%24ssw0rd%21@mongo:27017/local?authSource=admin)
```
Using the new parser fixes that.
=> [FIX] Startup error when using MongoDB with a password containing special characters

app/oembed/server/server.js, tests/end-to-end/api/05-chat.js
Add a null check to prevent an exception to stop the image preview workflow.
Closes #19714
1. Go to any channel or DM
2. Paste an image url
[FIX] Image previews not working
=> [FIX] Image preview for image URLs on messages

client/components/burger/BurgerIcon.js, client/hooks/useIsReducedMotionPreferred.js, client/sidebar/Item/Condensed.js, client/sidebar/Item/Extended.js, client/sidebar/Item/Medium.js, client/sidebar/hooks/usePrefersReducedMotion.js
=> [IMPROVE] Replace usePrefersReducedMotion

.docker-mongo/Dockerfile, .docker/Dockerfile
The command `chown` used after adding the bundle files to the container was causing Docker to store a new layer with all the data again, so the image was getting double it's "correct" size.
Thanks to @geekgonecrazy who found this, the `ADD` command accepts a `--chown` option which works the same way and then prevents us from adding an additional layer, the result is a drastically smaller image size, going from `1.62GB` to ` 922MB`.
This also explains why the Official Docker image is that small, since it doesn't has the `ADD` command, it was not doubling the size.
=> Improve Docker container size by adding chown to ADD command

app/ui-message/client/message.html, app/ui-message/client/message.js
=> [FIX] Custom Avatar

app/ui-flextab/client/tabs/membersList.js, client/views/room/contextualBar/UserInfo/index.js
=> Regression: fix broken members list

ee/app/auditing/server/methods.js
=> [FIX] 'Not Allowed' in message auditing

client/views/admin/users/UserInfoActions.js
=> Regression: User Info Context bar breaking.

app/autolinker/client/client.js, client/startup/renderMessage/autolinker.js, client/startup/renderMessage/autotranslate.js, client/startup/renderMessage/emoji.js, client/startup/renderMessage/googlevision.js, client/startup/renderMessage/hexcolor.js, client/startup/renderMessage/highlightWords.js, client/startup/renderMessage/issuelink.js, client/startup/renderMessage/katex.js, client/startup/renderMessage/markdown.js, client/startup/renderMessage/mentionsMessage.js, client/startup/renderNotification/markdown.js, client/startup/streamMessage/autotranslate.js, client/startup/streamMessage/googlevision.js
=> Regression: Failed autolinker and markdown rendering

.github/PULL_REQUEST_TEMPLATE.md
Improve the template of Pull Requests in order to make it clear reducing duplicated information and removing the visible checklists that were generating noise and misunderstanding with the PR progress.
- Moved the checklists to inside comments
- Merge the changelog and proposed changes sections to have a single source of description that goes to the changelog
- Remove the screenshot section, they can be added inside the description
- Changed the proposed changes title to incentivizing the usage of images and videos
No issue to close
- Open a new PR
=> Chore: Update Pull Request template

app/api/server/v1/users.js, server/methods/sendForgotPasswordEmail.js, tests/end-to-end/api/01-users.js
- respond with status 200 for account not found
- change tests
forgot password endpoint responds with 200 even if user was not found.
post a non existent user to the users.forgotPassword endpoint
=> [IMPROVE] Forgot password endpoint return status to return as success regardless if email was found or not

tests/end-to-end/api/05-chat.js
Seems that Youtube has changed the iframe size it returns to embed players, which was causing our tests to fail (see https://github.com/RocketChat/Rocket.Chat/runs/1556994039?check_suite_focus=true#step:12:2722), so I changed the test to not validate the full iframe HTML but instead test only what we enforce when embedding an iframe which is the `style="max-width: 100%"`.
=> Chore: Change Youtube test to verify if has an iframe with max-width

client/views/room/contextualBar/RoomMembers/List/RoomMembers.js
=> Regression: RoomMembers Permission

client/lib/getUserEmailAddress.ts, client/lib/getUserEmailVerified.ts, client/views/room/contextualBar/UserInfo/index.js
=> [FIX] User email showing [object Object]

client/views/room/contextualBar/RoomFiles/hooks/useFileList.js
=> Regression: Fix Room Files for DMs

app/version-check/server/addSettings.js, packages/rocketchat-i18n/i18n/en.i18n.json
=> [NEW] Update Checker Description

app/oembed/client/oembedFrameWidget.html
=> [FIX] Issue with oembed

client/views/room/contextualBar/UserInfo/index.js
[fix]Fix the translation keyword,so the local time will be translated automatically
=> [FIX] User Info 'Local Time' translation keyword

client/components/RoomForeword.js
=> [FIX] RoomForeword

README.md
Now that mlab is completely shutdown.  Heroku is no longer a possible deployment method.  So we need to remove it from our readme
https://devcenter.heroku.com/changelog-items/1823
=> Remove Heroku from readme

.snapcraft/resources/preparecaddy
Not sure why the redirect GitHub had stopped working.  But this was needed to build 3.9.3
=> Chore:  Fix Caddy download URL in Snaps

app/models/server/models/Sessions.js, app/models/server/models/Sessions.tests.js, app/statistics/server/lib/SAUMonitor.js, app/statistics/server/lib/statistics.js
Add the fields `uniqueUsersOfLastWeek`, `uniqueDevicesOfLastWeek` and `uniqueOSOfLastWeek` to the statistics report among the daily and monthly already reported.
=> Improve: Report Weekly Active Users to statistics

app/theme/client/imports/general/base.css
=> [IMPROVE] Show all screen when printing screen

app/api/server/api.d.ts, app/api/server/index.js, app/api/server/v1/instances.ts, server/stream/streamBroadcast.js
Returns an array of instances on the cluster.
=> [NEW] REST Endpoint `instances.get`

client/views/omnichannel/routes.js
The Omnichannel `Custom Fields` form is not working anymore after some refactorings on client-side.
When the user clicks on `Custom Field` in the Omnichannel menu, a blank page appears.
- Just click on the `Custom Fields` item on Omnichannel Menu, a blank page will appear.
=> Regression: Omnichannel Custom Fields Form no longer working after refactoring

app/ui-utils/client/lib/openRoom.js
=> [FIX] Room scrolling to top after returns to a opened room

client/sidebar/search/SearchList.js
=> [FIX] Status on searchlist

app/oembed/client/oembedFrameWidget.html, app/oembed/server/providers.js, app/oembed/server/server.js
=> Regression: Fix oembed

client/views/admin/users/UsersTable.js
This was not working when clicking, the arrows were not highlighting.
Now it does work :D
=> Regression: Fix sorting indicators on Admin Users page

client/components/ScrollableContentWrapper.tsx, client/views/room/contextualBar/Discussions/index.js, client/views/room/contextualBar/Threads/index.js
=> Regression: Double Scrollbars on tables

app/apps/server/bridges/livechat.js
While using `modify.getCreator().getLivechatCreator().createRoom(visitor, targetAgent)` I was getting following error
> Match error: Missing key 'username'
=> [FIX] Creation of Omnichannel rooms not working correctly through the Apps when the agent parameter is set

server/methods/saveUserPreferences.js
=> [FIX] User Audio notification preference not being applied

app/models/server/raw/LivechatDepartmentAgents.js, ee/app/livechat-enterprise/server/business-hour/Multiple.ts, ee/app/models/server/index.js, ee/app/models/server/raw/LivechatDepartmentAgents.ts, ee/server/services/stream-hub/StreamHub.ts
`LivechatDepartmentAgentsRaw` importing meteor dependencies inappropriately and this was breaking the micro services build.
=> [FIX] Omnichannel raw model importing meteor dependency

ee/client/omnichannel/cannedResponses/CannedResponseAdd.js, ee/client/omnichannel/cannedResponses/CannedResponseDetails.js, ee/client/omnichannel/cannedResponses/CannedResponseEdit.js
=> chore: Change return button

client/sidebar/search/SearchList.js
=> [FIX] Search list filter

client/components/avatar/UserAvatarEditor.js, client/views/account/AccountProfileForm.js, client/views/admin/users/EditUser.js
=> [FIX] Profile picture changing with username

app/utils/client/lib/handleError.js
=> [FIX] Meteor errors not translating for toast messages

packages/rocketchat-i18n/i18n/en.i18n.json
=> Update password policy English translation

client/views/room/index.js
=> [FIX] Tabbar is opened

app/lib/server/functions/saveUserIdentity.js
=> [FIX] User registration updating wrong subscriptions

client/components/UserStatusMenu.js
The Status Circle in status message text input is now centered vertically.
closes #20015 
Go to my account section.
=> [FIX]  Status circle in profile section

client/views/room/Header/Header.js
With the new 3.10.0 version update the Links in topic section below room name were not working, for more info refer issue #20018 
closes #20018 
Steps explained on issue.
=> [FIX] Markdown added for Header Room topic

client/components/GenericTable/index.js, client/views/admin/apps/AppLogsPage.js, client/views/admin/import/PrepareChannels.tsx, client/views/admin/import/PrepareUsers.tsx, client/views/admin/integrations/edit/OutgoingWebhookHistoryPage.js, ee/app/engagement-dashboard/client/components/ChannelsTab/TableSection.js, packages/rocketchat-i18n/i18n/en.i18n.json
Change translation keyword in order to allow the translation of `Showing results %s - %s of %s` in tables.
=> [FIX] Translate keyword for 'Showing results of' in tables

client/views/room/Header/ToolBox/ToolBox.tsx
Added the missing Tooltip for kebab menu on chat header.
fixes #20115 
Given on issue
For Now I am adding Tooltip as "Options". "More Options" would be more relevant but "Options" has translations available. If we want "More Options" I would be happy to provide translations for all languages.
=> [IMPROVE] Tooltip added for Kebab menu on chat header

client/components/avatar/UserAvatarEditor.js
Made user avatar change buttons to be descriptive of what they do.
Closes Issue #20082
=> [IMPROVE] Title for user avatar buttons

app/videobridge/server/methods/jitsiSetTimeout.js
The video call action link and sidebar message are in server side and therefore the language should be specified.
In addition, the video call system message from the message type should not be translated (it happens after..)
#18720 
1. Go to direct chat or private group
2. Click on the phone icon in order to start a new video call (and press 'OK')
Current behavior:
Fixed behavior:
Fixed video call message not translated.
=> [FIX] Video call message not translated

client/views/room/Header/icons/Favorite.js
=> [FIX] Change header's favorite icon to filled star

client/views/room/MemberListRouter.js
- Open the UserInfo tab of your own profile
=> [FIX] Wrong userId when open own user profile

client/components/SortList.js
=> Regression: Change sort icon

ee/app/auditing/server/methods.js
Change `console.warning()` (**not a function**) to  `console.warn()`.
=> Chore: Change console.warning() to console.warn()

app/ui-message/client/message.html, app/ui-message/client/messageBox/messageBox.js, app/ui-utils/client/lib/messageContext.js, app/ui/client/views/app/lib/getCommonRoomEvents.js, client/adapters.js, client/components/Message/Metrics/Broadcast.tsx
=> Rewrite Broadcast

app/ui-master/client/main.js
*  I have added tests that prove my fix is effective or that my feature works (if applicable)
*  I have added necessary documentation (if applicable)
*  Any dependent changes have been merged and published in downstream modules
Fixes an import statement and also takes `email2fa` service into account when checking for 2FA requirements.
Fixes #20166
=> [FIX] White screen after 2FA code entered

client/components/UserStatusMenu.js
Added Margins between status bullet and status label
fixes #20198 
Given on issue
For some reason Margins tag is not working, so Provided a Box tag with inline Margin.
=> [FIX] Added Margin between status bullet and status label

client/views/admin/viewLogs/ViewLogs.js
Fix `View Logs` title translation keyword to enable translation of the title
=> [FIX] ViewLogs title translation keyword

client/views/room/hooks/useUserInfoActions.js
Different messages for ignoring/unignoring will be displayed.
https://user-images.githubusercontent.com/55157259/103310307-4241c880-4a3d-11eb-8c6c-4c9b99d023db.mp4
Closes #19995
=> [FIX] Changed success message for ignoring member.

client/views/admin/rooms/EditRoom.js
Room avatar has been aligned properly in room-info
Fixes #20231
=> [FIX] Aligned room avatar properly.

client/views/admin/customSounds/AddCustomSound.js
Changed success message to Custom_Sound_Saved_Successfully which is already translated in different languages.
https://user-images.githubusercontent.com/55157259/105151351-daf2d200-5b2b-11eb-8223-eae5d60f770d.mp4
Closes #20271
=> [FIX] Changed success message for adding custom sound.

app/ui/client/views/app/room.js, client/views/room/Announcement/Announcement.js
=> Regression: Announcement bar not showing properly Markdown content

app/theme/client/imports/general/base_old.css, client/views/room/Announcement/Announcement.js
=> Regression: Unread superposing announcement.

server/cron/statistics.js
Fixes the TypeError on server restart caused by the missing `logger` parameter to `generateStatistics`.
Closes #20342
=> Regression: Fix Cron statistics TypeError

client/components/MarkdownText.js
=> Regression: Bio page not rendering

app/custom-sounds/client/lib/CustomSounds.js, app/ui-utils/client/lib/RoomHistoryManager.js, app/ui-utils/client/lib/openRoom.js
=> [FIX] RoomManager validation broken on IE

client/sidebar/hooks/useSidebarPaletteColor.js
=> [FIX] Sidebar palette color broken on IE

client/components/FilterByText.tsx, client/views/directory/ChannelsTab.js, client/views/directory/UserTab.js
=> [IMPROVE] Autofocus on directory

app/cloud/server/functions/syncWorkspace.js, server/services/banner/service.ts
=> Regression: Fix banners sync data types

app/message-star/server/starMessage.js
Changed the method from pinMessage to starMessage
NA
NA
NA
=> Wrong method used while starring

client/views/admin/users/AddUser.js, client/views/admin/users/EditUser.js, client/views/admin/users/UserForm.js, client/views/admin/users/UserInfo.js
=> [IMPROVE] Add visual validation on users admin forms

client/views/room/Header/ToolBox/ToolBox.tsx
Removed tooltip as it was not needed.
https://user-images.githubusercontent.com/55157259/106246146-a53ca000-6233-11eb-9874-cbd1b4331bc0.mp4
Closes #20111
=> [FIX] Removed tooltip in kebab menu options.

client/sidebar/header/UserDropdown.js
Removes warnings listed on the issue
fixes #20472
=> [IMPROVE] Added key prop, removing unwanted warnings

client/components/UserCard.js, client/sidebar/header/UserDropdown.js
Added markdown links to user's custom status.
fixes #20469 
I don't know if this is needed with custom status or not. If this is needed, this pr takes care of userStatus on userDropdown and userCard.
=> [IMPROVE] Added Markdown links to custom status.

client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js
All selected hide system messages are now in vertical Bar.
https://user-images.githubusercontent.com/55157259/105642624-d5411780-5eb0-11eb-8848-93e4b02629cb.mp4
Closes #20357
=> [FIX]Selected hide system messages would now be viewed in vertical bar.

client/views/admin/users/InviteUsers.js
Added Disable check for send invite button. If the text field is empty button would be disabled, and after any valid email is filled, button would get enabled
fixes #20336 
Check issue
=> [IMPROVE] Added disable button check for send invite button

app/statistics/server/lib/statistics.js
Modifies user statuses in admin info panel based on their actual status instead of their `statusConnection`. This enables correct and consistent change in user statuses. 
Also, bot users having status as online were classified as offline, with this change they are now correctly classified based on their corresponding statuses.
https://user-images.githubusercontent.com/28918901/105624438-b8bcc500-5e47-11eb-8d1e-3a4180da1304.mp4
Closes #20340
1. Go to Adminstration.
2. Login with an alternate account.
3. Change status of that account to busy/away.
=> [FIX] User statuses in admin user info panel

client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js
Password field would be secured with asterisks in edit room info
https://user-images.githubusercontent.com/55157259/105641758-cad04f00-5eab-11eb-90de-0c91263edd55.mp4
.
Closes #20355
=> [FIX] Changed password input field for password access in edit room info.

client/components/CustomFieldsForm.js
Added the required dep (`label`) in `useMemo` to fix eslint warning `react-hooks/exhaustive-deps`.
On the terminal (in the rocketchat folder), run command `npm run jslint`
=> [FIX] ESLint Warning - react-hooks/exhaustive-deps

server/modules/watchers/watchers.module.ts
=> Chore: Improve performance of messages’ watcher

app/message-mark-as-unread/server/unreadMessages.js, packages/rocketchat-i18n/i18n/en.i18n.json, packages/rocketchat-i18n/i18n/pt-BR.i18n.json, tests/end-to-end/api/10-subscriptions.js
Fixes https://github.com/RocketChat/Rocket.Chat/issues/19765
=> Chore: Change error message when marking empty chat as unread

app/models/server/models/Rooms.js
Channel mention shows user subscribed channels twice.
https://user-images.githubusercontent.com/55157259/106183033-b353d780-61c5-11eb-8aab-1dbb62b02ff8.mp4
Closes #20483
=> [FIX] Channel mentions showing user subscribed channels twice

client/sidebar/header/UserDropdown.js
When changing status, the status type was being sent as the custom status. The now correct behavior is to just erase it.
=> [FIX] Regular status mutating custom status

client/views/omnichannel/triggers/TriggersPage.js
=> [FIX]  List of Omnichannel triggers is not listing data

client/views/account/preferences/AccountPreferencesPage.js
Able to Empty the highlighted text field in preferences
fixes #20328 
The spelling of highlights was wrong due to which error was coming
=> [FIX] Fix Empty highlighted words field

app/markdown/lib/parser/marked/marked.js
Fixes issue with links opening in the same page.
=> [FIX] Links not opening in new tabs

package-lock.json, package.json
Update to latest patch version of the Apps-Engine with a fix for the Livechat bridge, as seen in https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/379
=> [FIX] Livechat bridge permission checkers

app/markdown/lib/parser/marked/marked.js
This stops errors from occurring whenever the marked parser need to be used on the server. Should resolve the issues with the autotranslate feature.
Closes #20598
=> [FIX] Server-side marked parsing

client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js
Fixes issue when changing "Hide system messages" on channels for the second time consecutively.
=> [FIX] Hide system messages not working on second save

client/views/room/contextualBar/RoomFiles/RoomFiles.js
Added toast message after successfully deleting a file.
https://user-images.githubusercontent.com/55157259/107410849-d1a9c380-6b33-11eb-8d10-3d225dc7a9db.mp4
Closes #20660
=> Added toast message after deleting file.

app/ui-cached-collection/client/models/CachedCollection.js
The proposed change fixes a bug when updates the cached records on Internet Explorer and it breaks the sidebar as shown on the screenshot below:
=> [FIX] Room's last message's update date format on IE

package-lock.json, package.json
=> Chore: update RC with the latest fuselage-polyfills

app/otr/client/index.js, app/otr/client/stylesheets/otr.css
=> [FIX] Icon for OTR messages

client/startup/loginViaQuery.js
Do not redirect to `/home` anymore after logging in with `resumeToken`.
=> [FIX] Sending user to home after logging in from resume token query param

.github/workflows/build_and_test.yml
As they started failing recently: https://github.com/RocketChat/Rocket.Chat/runs/1879570988?check_suite_focus=true
=> Chore: Push correct Docker tag of service images

package-lock.json, package.json
=> [IMPROVE] Update rc-scrollbars

app/message-mark-as-unread/client/actionButton.js
Added threads to mark unread action button.
This PR closes #20705
=> [FIX] Mark messages inside a thread as unread

client/views/account/tokens/AccountTokensTable.js
Unset the modal when waiting for the token to regenerate.
=> [FIX] Regenerate token modal on top of 2FA modal

client/components/DeleteWarningModal.tsx, client/components/withDoNotAskAgain.tsx, client/sidebar/RoomMenu.js
=> [FIX] Don't ask again not rendering

app/theme/client/imports/general/base_old.css
Changed the values of `margin-top` and `margin-bottom` for *first* and *last* childs in blockquotes to increase readability.
Closes #20748 
Mentioned in #20478
=> [IMPROVE] Better Presentation of Blockquotes

client/components/Message/Attachments/DefaultAttachment.tsx
A large amount of unnecessary margin which existed in the **Field Attachments inside the `DefaultAttachments`** has been fixed.
Related to #20556
Described more on the  [issue on PR #20569 (comment)](https://github.com/RocketChat/Rocket.Chat/pull/20569#issuecomment-772945441)
As mentioned in #20556
=> [FIX] Default Attachments - Remove Extra Margin in Field Attachments

app/threads/client/flextab/thread.js, app/ui-utils/client/lib/RoomHistoryManager.js, client/views/room/contextualBar/Discussions/index.js, client/views/room/contextualBar/RoomFiles/RoomFiles.js, client/views/room/contextualBar/Threads/index.js
Fixed readMessage being called even if the thread is not opened
and a regression introduced by the virtuoso implementation
=> [FIX] Threads Issues

client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.js
use correct permissions to check if room owner can override global retention policy
Closes #19678
=> [FIX] Room owner not being able to override global retention policy

ee/app/livechat-enterprise/server/api/lib/inquiries.js
Due to a wrong property name, external applications were not able to change the priority of Omnichannel Inquires.
=> [FIX] External systems not being able to change Omnichannel Inquiry priorities 

app/notification-queue/server/NotificationQueue.ts
Introduced by https://github.com/RocketChat/Rocket.Chat/pull/20605
=> Regression: Fix notification worker not firing

app/discussion/client/views/creationDialog/CreateDiscussion.html
Adding back accidentally deleted tag Template.
fixes #20771 
closes #20777
PR #20617 ports previously written meteor templates to React, it also deletes a template `tag` being used by other templates which causes an error while creating discussions and direct messages.
This pr solves this by adding back tag template.
=> [FIX] Adding the accidentally deleted tag template, used by other templates

app/ui-utils/client/lib/RoomHistoryManager.js
=> Regression: Fix loadHistory method being called multiple times

client/views/omnichannel/departments/DepartmentEdit.js
=> [FIX] height prop on departments agents table

app/2fa/server/loginHandler.js
=> [FIX] CAS login failing due to TOTP requirement

app/2fa/client/TOTPCrowd.js, app/2fa/client/index.js
=> [FIX] Atlassian Crowd login with 2FA enabled

package-lock.json, package.json
Update Livechat version to `1.8.0` .
=> Bump Livechat Widget

app/lib/server/startup/oAuthServicesUpdate.js
There are no booleans from env.
I think it would be cleaner to use `settings.get` as I suspect it is already implementing such a logic.
Also using `_` instead of `-` is a bit nasty ;) But hey, code is the doc :)
=> [FIX] Custom OAuth provider creation from env vars

app/apps/server/bridges/bridges.js, app/apps/server/bridges/cloud.ts, app/apps/server/orchestrator.js, app/cloud/server/functions/getWorkspaceAccessToken.js, app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js, app/cloud/server/index.js, package-lock.json, package.json
Adds the new CloudWorkspace functionality.
It allows apps to request the access token for the workspace it's installed on, so it can perform actions with other Rocket.Chat services, such as the Omni Gateway.
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/382
=> [NEW] Cloud Workspace bridge

client/sidebar/header/UserDropdown.js
=> Regression: Keep user custom status after change presence

app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
#20838 changed the getter.. didn't test full register process and missed this.
=> Regression: Fix scopes not being provided to getWorkspaceAccessToken

.snapcraft/snap/snapcraft.yaml
Added network-observe plug.  Should squash errors found in #14562 according to: https://forum.snapcraft.io/t/how-to-connect-to-localhost-mongodb-in-snap-apparmor-prevents/7793/3
closes #14562
=> Fix: Add network observe plug to snap

client/components/Page.tsx
=> [FIX] Admin Panel pages not visible in Safari

app/api/server/v1/users.js, tests/end-to-end/api/01-users.js
=> [FIX] Add missing `unreads` field to `users.info` REST endpoint

client/components/Message/Attachments/DefaultAttachment.tsx
=> [FIX] Missing spaces on attachment 

app/api/server/v1/teams.ts, server/sdk/types/ITeamService.ts, server/services/team/service.ts
move some logic from teams.list to a new teams.listAll endpoint
=> [NEW] list all endpoint

server/services/authorization/canAccessRoom.ts, server/services/authorization/service.ts
=> Prevent users from outside team to access team & team channels

app/api/server/v1/teams.ts, server/sdk/types/ITeamService.ts, server/services/team/service.ts
=> [NEW] teams.info endpoint

app/api/server/v1/teams.ts, app/models/server/raw/Team.ts, server/sdk/types/ITeamService.ts, server/services/team/service.ts
=> [NEW] teams.delete endpoint

app/api/server/v1/channels.js, server/sdk/types/IRoomService.ts, server/sdk/types/ITeamService.ts, server/services/team/service.ts
=> [NEW] channels.convertToTeam endpoint

app/api/server/v1/groups.js, app/models/server/raw/Rooms.js, server/services/team/service.ts
Adds a new endpoint to convert a private group to a team.
=> [NEW] add groups.convertToTeam endpoint

app/api/server/v1/teams.ts, app/models/server/raw/Rooms.js, server/sdk/types/ITeamService.ts, server/services/team/service.ts
=> [New][Teams] Implement pagination for teams.listRooms

ee/app/license/server/bundles.ts, ee/app/teams-mention/server/index.js
=> Chore: add teams-mention enterprise module

app/models/server/models/Rooms.js
- Filter rooms/get endpoint to remove teams the user is not part of
=> [New][Teams] Filter out teams from rooms/get endpoint

server/services/team/service.ts
=> [FIX] teams.create is not returning the roomId

app/models/server/raw/TeamMember.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
- Prevent last owners from being removed or leaving their teams (checks if an user is the last owner of a team before removing);
- Applies the changes to the `teams.removeMembers` and `teams.leave` endpoints.
[Task - ClickUp](https://app.clickup.com/t/3q5caj)
1. Create a team;
2. Attempt to remove the team's creator from the team using the `teams.leave` or `teams.removeMembers` endpoints (the `last-owner-can-not-be-removed` error is expected to be thrown).
=> [FIX] Last owner is allowed to leave a team

app/api/server/v1/groups.js, tests/end-to-end/api/02-channels.js, tests/end-to-end/api/03-groups.js
=> Chore: Add tests for convertToTeam and fix groups.convertToTeam

app/api/server/v1/teams.ts, app/models/server/raw/Rooms.js, server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
improved teams.delete to include other requirements.
=> [NEW] remove rooms from team on teams.delete endpoint

app/api/server/v1/groups.js, app/api/server/v1/teams.ts, app/models/server/models/Rooms.js, app/models/server/raw/Rooms.js, app/models/server/raw/TeamMember.ts, app/statistics/server/lib/statistics.js, definition/ITeam.ts, server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/02-channels.js, tests/end-to-end/api/03-groups.js, tests/end-to-end/api/25-teams.js
- Remove the `_id`, `teamId`, `_updatedAt` and `userId` fields from each member entry;
- Add an `user` field to each member entry, containing the `_id`, `username`, `name` and `status`.
[Task - ClickUp](https://app.clickup.com/t/3k4fca)
Use the `teams.members` endpoint, as described in the feature's document.
=> [FIX] Incorrect teams.members endpoint results' structure

app/models/server/models/Subscriptions.js, server/publications/subscription/index.js
- Add team's info to subscriptions/get
=> [New][Teams] Add team's info to subscriptions/get

app/api/server/v1/teams.ts, app/models/server/raw/Rooms.js, server/sdk/types/ITeamService.ts, server/services/team/service.ts
- Allow private teams to be marked as default
- Apply permissions filtering to list/update/remove channels from teams
- Other fixes
=> [Teams][New] Allow private teams to be marked as default

server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
=> [NEW] Add number of rooms in each team to the teams.list endpoint

app/api/server/lib/rooms.js, app/models/server/raw/Rooms.js
=> [NEW] include teams on admin.listRooms endpoint

app/api/server/v1/users.js, app/models/server/raw/Team.ts, app/models/server/raw/TeamMember.ts, server/services/team/service.ts, tests/end-to-end/api/01-users.js
=> [NEW] users.listTeams endpoint

app/livechat/client/views/app/tabbar/visitorInfo.js, app/livechat/server/lib/Helper.js, app/livechat/server/lib/Livechat.js, app/livechat/server/lib/RoutingManager.js, ee/app/livechat-enterprise/server/hooks/afterForwardChatToAgent.ts, ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.js, ee/app/livechat-enterprise/server/hooks/afterOnHoldChatResumed.ts, ee/app/livechat-enterprise/server/hooks/afterReturnedRoomAsInquiry.ts, ee/app/livechat-enterprise/server/hooks/index.js, ee/app/livechat-enterprise/server/hooks/onCloseLivechat.js, ee/app/livechat-enterprise/server/methods/resumeOnHold.ts
NOTE: This PR is to be merged after PR #20945 since it's built on top of it
Here we're handling following events which were getting impacted by this new on-hold feature
- Returning chat to the queue
- Forwarding chats
- Closing chats
For each of the above events, we're making sure that recent changes to Routing mechanism for on-hold feature isn't changing the existing behaviour of these events.
Additionally we're making sure that if any of the above events are triggered from a chat which is already On Hold, then we cleanup all the OnHold chat related properties.
=> [Regression] Omnichannel On hold Queue

app/api/server/lib/rooms.js
=> Include fname on the results of 'rooms.autocomplete.channelAndPrivate'

app/api/server/v1/teams.ts, app/models/server/raw/Rooms.js, server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
=> [NEW] teams.addRooms endpoint

app/models/server/models/Subscriptions.js
=> [FIX] subscriptions/get team data

client/sidebar/search/SearchList.js
The search list now also properly shows the last channel 
Before  :
After : 
Closes #21159 
Go to the search list and check the last channel
=> [FIX] Fix the search list showing the last channel

.github/PULL_REQUEST_TEMPLATE.md
There are some minor grammatical errors in the pull request template which makes it hard to understand the meaning of sentences.
Made some correction in the grammar.
no
[Check this](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.github/PULL_REQUEST_TEMPLATE.md)
=> [IMPROVE]  grammatical typos in pull request template

client/hooks/useRoomIcon.tsx, client/sidebar/hooks/useRoomList.ts, definition/IRoom.ts, definition/ISubscription.ts
=> [NEW] Team icon and sidebar section

app/api/server/v1/teams.ts, app/models/server/models/Rooms.js, app/models/server/models/Subscriptions.js, app/models/server/models/Users.js
=> [NEW] Teams.leave endpoint improvements

app/lib/lib/MessageTypes.js, packages/rocketchat-i18n/i18n/en.i18n.json
Closes https://github.com/RocketChat/Rocket.Chat/issues/11213
=> [NEW] Ability to hide 'Room topic changed' system messages

app/theme/client/imports/general/base_old.css
Modified the CSS to not affect the ignored sequential messages exactly like the non-ignored messages, which is what was causing the second and further ignored message o appear weirdly when unhidden one by one.
https://user-images.githubusercontent.com/38764067/109400547-53d91b00-796f-11eb-9c65-c0f3aca2738d.mp4
https://user-images.githubusercontent.com/38764067/109400540-4cb20d00-796f-11eb-8e03-9a122ae2a104.mp4
Closes #20927
=> [FIX] Correct ignored message CSS

packages/rocketchat-i18n/i18n/en.i18n.json
The text says the share button will be on the left of the messagebox once enabled. However, it actually is on the right.
1. Administration -> Message -> Google Maps. Label under toggle
Will have to be corrected in other languages too. Not sure if Google Translate should be used. So, didn't update others for now.
=> [FIX] Correct direction for admin mapview text

client/views/room/contextualBar/PruneMessages/PruneMessages.js
Fix undefined in Prune Messages in direct
=> [FIX] undefined in PruneMessages deleting DM

client/views/room/contextualBar/OTR/OTR.js
Set establishing false if OTR timeouts.
https://user-images.githubusercontent.com/55157259/111617086-b30cab80-8808-11eb-8740-3b4ffacfc322.mp4
Closes #21121
=> [FIX] Set establishing to false if OTR timeouts

client/components/Message/Attachments/Attachment.tsx
Correct the spelling of _donwload_ to _download_ in `TitleLink` of Attachments.
Thanks to @OneTwoBarbecue for pointing this out in Issue #21075 :smiley: .
=> [FIX] Correct Typo - donwload to download

server/services/room/service.ts
=> [FIX] typescript error

app/models/server/raw/Rooms.js, server/services/team/service.ts
=> [FIX] convertToTeam endpoints not saving team data on room

client/components/avatar/UserAvatarEditor.js
A margin has been added for a better aesthetic and even spacing.
Before:
After:
Closes #20741
=> [IMPROVE] Add spacing between elements in Profile Page

app/ui-message/client/messageBox/messageBoxAudioMessage.js
A modal box will be displayed so that users can change the filename and add description.
**Before**
https://user-images.githubusercontent.com/55157259/105687301-4e2a8880-5f1e-11eb-873d-dc8a880a2fc8.mp4
**After**
https://user-images.githubusercontent.com/55157259/105687342-597db400-5f1e-11eb-8b61-8f9d9ebad0c4.mp4
Closes #20369
=> [IMPROVE] Added modal-box for preview after recording audio.

client/views/room/contextualBar/UserInfo/index.js
Truncating text in profile view was making some information completely inaccessible. Removed it from the user status and the custom fields where if the information is longer, the user would actually want to see all of it.
Closes #19259 
1. Set a very long status. [Example: "I am here to check if this is being cut off in which case I will have to do something about the fields to make this work"]
2. Look at it in the profile view. No one can actually see the complete status message.
=> [FIX] Removing truncation from profile

client/startup/e2e.js
=> Regression: Fix non encrypted rooms failing sending messages

client/views/teams/info/TeamsInfo.js
=> Regression: View Channels button in Team info

client/views/room/contextualBar/UserInfo/index.js
=> Regression: user actions in admin

client/views/teams/contextualBar/TeamChannelItem.js
=> Regression: Add BreadCrumbs tag into auto-join items

app/models/server/models/Subscriptions.js, app/ui-sidenav/client/roomList.js, client/sidebar/RoomList.js, server/publications/subscription/index.js
=> regression: Sidebar reactivity

app/api/server/lib/rooms.js, app/models/server/raw/Rooms.js
=> Regression: When only 'teams' type is provided, show only rooms with teamMain on `rooms.adminRooms` endpoint

app/api/server/v1/groups.js
=> Regression: Channel owner can't convert it into a team.

app/api/server/helpers/getUserFromParams.js, app/api/server/v1/channels.js, app/api/server/v1/groups.js, app/models/server/models/Users.js
- channels.invite now supports passing an array as a param (either with usernames or userIds) via `usernames` or `userIds` properties.
- You can still use the endpoint to invite only one user via the old params `userId`, `username` or `user`.
- Same changes apply to groups.invite
- Pending unit tests
=> Regression: Update .invite endpoints to support multiple users at once

server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
=> Regression: Add number of team members to teams.list and teams.listAll

app/api/server/v1/teams.ts
- Replace `removeById` by `eraseRoom` method's call (which not only deletes the room, but also erases its subscriptions and triggers some apps-engine events).
[Task - ClickUp](https://app.clickup.com/t/3z4ccr)
Create and delete a new team -- the user who created the team should not be subscribed to it after the team's deletion.
=> Regression: Add call to eraseRoom method

app/api/server/v1/teams.ts, client/views/room/hooks/useUserInfoActions.js
=> Regression: Delete team member from related team's rooms

client/views/room/Header/Header.js
=> Regression: Headers icon breaking DMs

app/api/server/v1/teams.ts, app/models/server/raw/Rooms.js, client/contexts/ServerContext/endpoints/v1/teams/listRooms.ts, client/views/room/hooks/useUserInfoActions.js, client/views/teams/contextualBar/TeamAutocomplete.js, client/views/teams/contextualBar/channels/hooks/useTeamsChannelList.ts, server/methods/browseChannels.js, server/sdk/types/ITeamService.ts, server/services/team/service.ts, tests/end-to-end/api/25-teams.js
=> Regression: General improvement to Teams

client/components/Header/Header.tsx
=> Regression: header title tag style

client/views/directory/TeamsTab.js, packages/rocketchat-i18n/i18n/en.i18n.json
=> regression: Directory - teams tab search

client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js, client/views/room/contextualBar/Info/index.js, client/views/teams/contextualBar/channels/TeamsChannels.js
=> Regression: rooms breaking after deleting a room from a team

client/views/teams/contextualBar/channels/TeamsChannels.js
=> Regression: Error clicking on non joined channels on team channel list

client/views/room/contextualBar/RoomMembers/List/RoomMembers.js, client/views/room/lib/Toolbox/defaultActions.ts
=> Regression: Fix Members List Icon

client/omnichannel/chats/contextualBar/ChatRoomForm.js
=> [FIX] Tag component is no longer rendering on Chat Room Information panel

client/components/Omnichannel/modals/CloseChatModal.js, client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
=> [FIX] Add tag input to Closing Chat modal

client/views/room/lib/QuickActions/defaultActions.ts, ee/app/livechat-enterprise/lib/QuickActions/defaultActions.ts
=> [FIX] Make Omnichannel's closing chat button the last action in the toolbox

app/livechat/server/lib/QueueManager.js
The Omnichannel Queue Manager is returning outdated room object when delegating the chat to an agent, hence, our Livechat widget is affected and the agent assigned to the chat is not displayed on the widget, only after refreshing/reloading.
- Set `Auto Selection` as Omni Routing System
- Start a new livechat session
- The agent is assigned to the chat, but the information is not displayed on the widget
=> [FIX] Omnichannel queue manager returning outdated room object

app/api/server/v1/users.js
- Fix Administration/Users pagination
Fixes #21458
=> [FIX] Admin Users list pagination

app/models/server/models/Rooms.js
=> Chore: Remove control character from room model operation

app/apps/server/tests/mocks/orchestrator.mock.js, app/lib/tests/server.tests.js
=> Chore: Increase testing coverage on password policy class

app/ui-message/client/message.html
Reactions should come before reply button.
=> [FIX] Message Block ordering 

app/markdown/lib/parser/original/markdown.js
Stops the original markdown rendered from rendering empty bold, italic and strike text. Stops `_ _`, `* *` and `~ ~`
closes https://github.com/RocketChat/Rocket.Chat/issues/10683
=> [FIX] Don't allow whitespace on bold, italic and strike

client/views/room/contextualBar/Info/EditRoomInfo/EditChannel.js
=> [FIX] Archive permissions for room moderator

client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
Just a few checks before show the data
=> [FIX]  Omnichannel room information panel breaking due to lack of data verification

.github/workflows/build_and_test.yml, ee/server/services/package-lock.json, ee/server/services/package.json
- Fix error when running micro services after version 3.12
- Fix build of docker image version latest for micro services
=> Fix: Missing module `eventemitter3` for micro services

client/views/admin/users/UsersPage.js
=> Regression: Edit user in admin breaking

client/views/omnichannel/agents/AgentEdit.js, client/views/omnichannel/agents/AgentsRoute.js, client/views/omnichannel/currentChats/CurrentChatsRoute.js
https://user-images.githubusercontent.com/2493803/115088235-1eb86600-9ee6-11eb-9ca1-97d5f9ddd48a.mp4
https://user-images.githubusercontent.com/2493803/115087901-828e5f00-9ee5-11eb-9c24-e6aa0a5dd074.mp4
=> [FIX] Omnichannel current chats and agents grid aren't sorting by status properly

app/livechat/server/methods/loadHistory.js
=> [FIX] Fix livechat:loadHistory cannot retrieve messages

app/theme/client/imports/general/base_old.css
=> [FIX] Change margin size for quote messages

client/views/room/contextualBar/Info/EditRoomInfo/EditChannel.js
=> [FIX] Change team private info text

app/e2e/client/tabbar.ts
=> regression: Cannot enable e2e in direct room.

client/views/teams/contextualBar/channels/RoomActions.js
=> [FIX] Use async await in TeamChannels delete channel action

client/views/banners/LegacyBanner.tsx, client/views/root/BlazeTemplate.tsx
=> Regression: Legacy Banner Position

client/views/teams/contextualBar/info/Delete/ChannelDeletionTable.js
Fixed: Channels on selection won't be displayed while deleting a team
Before:
https://user-images.githubusercontent.com/23723464/115390921-79123900-a1fc-11eb-870a-7ff343767b91.mov
After:
https://user-images.githubusercontent.com/23723464/115390959-84fdfb00-a1fc-11eb-99a4-6fa0be20bb2e.mov
=> [FIX] Selected channels are not showing in Teams

client/views/omnichannel/directory/ContactContextualBar.js
=> [FIX] Wrong title on Omnichannel contact information panel

app/api/server/v1/rooms.js
=> [Fix] Add support for ignoreDiscussion param on room.cleanHistory endpoint

client/components/Message/Attachments/Files/GenericFileAttachment.tsx
=> [FIX] Generic Attachment broken somehow

client/components/UserStatus/ReactiveUserStatus.js, client/lib/presence.ts, client/views/room/UserCard/index.js, client/views/room/contextualBar/RoomMembers/List/components/MemberItem.js, client/views/room/contextualBar/UserInfo/UserInfoWithData.js
=> [FIX] User status out of sync

app/oembed/server/server.js
- Send `Accept-Language` header on oembed requests
=> [IMPROVE] OEmbed details by requesting using the accept language header on the request

client/components/Message/Attachments/Item.tsx
Additional checks on message_link field before rendering message contents
Closes #20972
=> [FIX] Message link null corrupts message rendering

client/views/admin/info/DeploymentCard.js
=> Add ')' after Date and Time in DB migration

app/apps/README.md
In app/apps/README.md: There is a spelling mistake. 'Hence' is incorrectly spelt as 'hince'. It had to be corrected in order to give a correctful meaning to any user who is reading the README.
This is my first PR, just wanted to see whether everything works fine or not and of course there was a genuine typo in the README file.
=> Fix typo in app/apps/README file

package-lock.json, package.json
=> Bump Livechat Version

.github/workflows/build_and_test.yml
There was no `GIT_TAG` defined, so `RELEASE` was not being defined as well, causing the following commands to fail.
=> Regression: Fix services Docker image build

app/ui-utils/client/lib/SideNav.js, app/utils/lib/roomExit.js, client/lib/RoomManager.ts, client/views/room/providers/RoomProvider.tsx
=> Regression: Fix room not returning to the previous room after directory

app/markdown/lib/parser/original/markdown.js
Modified regex to avoid spaces between the marked text and the symbols. Also made it possible to apply the three markings at the same time, independing of order.
```
_  test  _
* test *
~ test ~
```
These should not be parsed.
=> Regression: Bold, italic and strike render (Original markdown)

app/channel-settings/client/tabBar.ts, app/discussion/client/tabBar.ts, app/threads/client/flextab/threadlist.tsx, app/videobridge/client/tabBar.tsx, client/views/room/lib/Toolbox/defaultActions.ts
=> [FIX] Toolbox icons order

app/ui/client/views/app/room.js, client/lib/RoomManager.ts
Since we are no longer keeping the rooms opened behind the scenes, behaviors like scrolling to bottom after receiving a new message x keep the last scroll position were not working as expected.
=> Regression: Fix scroll to bottom

app/api/server/default/info.js, client/types/meteor.d.ts, ee/client/ecdh.ts, ee/server/services/ecdh-proxy/lib/server.ts, packages/rocketchat-ddp/client/index.js
The ECHD Proxy implements a delay on websocket connection, the first implementation lost the reference to auto reconnect functionality.
=> Regression: Reconnection not working properly due to changes on ECHD Proxy

package-lock.json, package.json
=> Regression: Update fuselage for icons fix

.github/workflows/build_and_test.yml
Now that the `npm install` step is running on EE folder too, we need to add it to the cache as well, otherwise it will fail every time the case is used.
=> Chore: Cache EE node_modules on CI

app/meteor-accounts-saml/server/lib/Utils.ts
=> Chore: fix invalid type name on TS file

app/lib/server/methods/removeOAuthService.js
custom OAuth is partially deleted after clicking **delete custom oauth** button in admin settings.
https://user-images.githubusercontent.com/63258524/115160796-cdf86700-a0b7-11eb-9442-bbcb8c6b1fc5.mp4
https://user-images.githubusercontent.com/63258524/115160845-fd0ed880-a0b7-11eb-85bf-00c8217c2dfe.mp4
#21280
check issue page
=> [FIX] Custom OAuth not being completely deleted

client/components/Omnichannel/modals/CloseChatModal.js
Fixes issue with the setting `Livechat_request_comment_when_closing_conversation` not working as intended
Closes https://github.com/RocketChat/Rocket.Chat/issues/21468
=> [FIX] When closing chats a comment is always required

server/services/nps/getAndCreateNpsSurvey.ts, server/services/nps/sendNpsResults.ts
Previously if got 400 / 404 / 502 basically anything but a 20x error it would break
=> [FIX] Handle NPS errors instead of throwing them

app/lib/server/functions/sendMessage.js
=> Regression: Fix send message validation

app/oembed/server/server.js
=> [FIX] iFrame size on embedded videos

client/components/Header/HeaderLink.tsx, client/components/Header/HeaderTagIcon.tsx
=> [FIX] Header Tag Visual Issues

client/views/teams/contextualBar/channels/TeamsChannelItem.js
=> [FIX] Auto-join Tags misalignment 

app/ui-message/client/message.js, client/views/room/hooks/useUserInfoActions.js
=> [FIX] errors when viewing a room that you're not subscribed to

client/sidebar/header/CreateChannel.js
=> [FIX] Label's disabled color on Create New Modal

client/views/room/contextualBar/RoomMembers/List/RoomMembersWithData.js, client/views/room/contextualBar/UserInfo/UserInfoWithData.js, client/views/room/contextualBar/UserInfo/actions/UserActions.js, client/views/room/hooks/useUserInfoActions.js, client/views/teams/contextualBar/members/TeamsMembers.js
=> [FIX] Redirect on remove user from channel by user profile tab

client/views/room/contextualBar/Threads/components/Message.js
=> [FIX] Wrong color and size, thread list Metrics

server/methods/browseChannels.js
fixes: #21700
fixes: #21325 
https://user-images.githubusercontent.com/23723464/115544827-b2ac7800-a2c0-11eb-8984-fc6948753876.mov
=> [FIX] Unable to get channels, sort by most recent message

client/views/account/preferences/PreferencesSoundSection.js
**Before Tooltip pointer blocking text:**
**After:**
Visit account-preference (/account/preferences). and select "sounds". You can see the tooltip arrow blocking the text.
=> [FIX] Tooltip pointer is blocking Text

client/components/Header/HeaderLink.tsx, client/components/Header/HeaderTag.tsx, client/views/room/Header/RoomHeader.tsx
=> [FIXf] Parent Room Tag Overlapping

client/views/room/contextualBar/UserInfo/UserInfo.js, client/views/room/contextualBar/UserInfo/UserInfoWithData.js
=> regression: UserInfoTab Broken

app/authorization/server/startup.js, server/startup/migrations/index.js, server/startup/migrations/v224.js
The new impersonate permission was missing to `app` role causing Apps to not be able to create some messages.
=> Regression: Add impersonate permission to app role

app/message-pin/client/views/pinnedMessages.js
=> [FIX] Unpin message reactivity

app/authorization/client/startup.js, app/ui-master/client/main.js, package-lock.json
=> [FIX] Scenarios where 2FA enforcement was not working properly

client/views/room/contextualBar/Info/ChannelToTeamModal/StepOne.js
=> regression: Select Team Modal margin

ee/app/livechat-enterprise/server/lib/Department.js, ee/client/omnichannel/units/UnitEdit.js
=> regression: fix departments with empty ancestors not being returned

client/components/GenericModal.tsx, client/components/Page/PageScrollableContent.tsx, package-lock.json, package.json
=> regression: bump Rocket.Chat.Fuselage package with paginated selects

client/views/teams/contextualBar/channels/TeamsChannels.js
Allow moderators and owners to add or create channels on Teams Channels
- Create a team as admin
- Add a normal user on this team
- Log as this normal user
- Check that this user won't be able to add or create channels on Teams Channels
- As admin, set this user as owner or moderator
- Now the normal user will be able to add or create channels on Teams Channels
=> [FIX] Permission's scope on Teams Channels

README.md, docker-compose.yml
This change updates the Docker installation instructions to use the new registry.rocket.chat endpoint to pull the rocketchat/rocket.chat container. This is part of the rollout described here: https://rocket.chat/blog/product/docker-images-change/
No issues have been created for this, but have been discussed on the open.rocket.chat server with @geekgonecrazy, @Sing-Li, and @johncrisp.  I can certainly make one if that's preferred, let me know.
This does update the docker-compose file - following instructions to run via Docker compose can test that side of the change.
This is bundled with https://github.com/RocketChat/docs/pull/1983
=> Chore: Update Docker container references to use registry.rocket.chat endpoint

client/views/teams/contextualBar/info/TeamsInfoWithLogic.js
=> [FIX] Incorrect Team's Info spacing

app/ui-master/server/inject.js
Should fix #3860
Should fix #10876
=> [FIX] Remove referer header when requesting attachment data

server/startup/migrations/v225.js
=> regression: Misspelled property in migration 225

app/models/server/models/Subscriptions.js
Fixes permanent unread messages when admin prune at least two different thread messages in the room that were unread by some user.
Fixes #21154
- Open a thread with at least two users
- Open another thread with the same two users
- One user sends a message on both threads to create unread messages
- Prune only one thread with its messages
=> [FIX] Prune messages not cleaning up unread threads

app/authorization/server/methods/saveRole.js, packages/rocketchat-i18n/i18n/en.i18n.json
Now whenever the user tries to create roles with the same name it prompts the user about it and stops from making the new Role
Closes #21272
Go to admin panel-> permissions->add a button to create a role with the same existing name
This pull request was made to incorporate the changes requested in #21274
=> [FIX] Creating roles with same name

package-lock.json, package.json
=> Chore: update fuselage && icons

app/ui-utils/client/lib/openRoom.js
Adapts the `openRoom` function to the new signature of `createDirectMessage`.
1 - Search a name in the spotlight you never talked before
2 - Click on that name
=> [FIX] Open a new DM throwing  error 404

server/startup/migrations/v225.js
=> Regression: Improve migration 225

client/views/admin/permissions/EditRolePage.js, client/views/admin/permissions/NewRolePage.js, client/views/admin/permissions/PermissionsContextBar.js, client/views/admin/permissions/PermissionsTable.js, packages/rocketchat-i18n/i18n/en.i18n.json
=> [IMPROVE] Missing modal on deleting a role

app/lib/server/functions/sendMessage.js, app/lib/server/functions/updateMessage.js, package-lock.json, package.json
=> Chore: Bump message parser

server/startup/migrations/v225.js
=> regression: Migration 225 setting not being fetched correctly

client/lib/presence.ts
=> [FIX] Presence.get method

client/components/SortList/SortListItem.js
=> Regression: Visual issue on sort list item 

client/sidebar/hooks/useRoomList.ts
=> Regression: discussions display on sidebar

client/views/room/MemberListRouter.js, client/views/teams/contextualBar/channels/RoomActions.js, client/views/teams/contextualBar/channels/TeamsChannelItem.js
=> Regression: Missing room scope on teams channels permission

app/authorization/server/methods/saveRole.js, client/views/admin/permissions/EditRolePage.js
introduced by https://github.com/RocketChat/Rocket.Chat/pull/21905
=> Regression: not allowed to edit roles due to a new verification

app/lib/server/functions/createRoom.js
Allow discussions overwrite the `fname` property of a room.
=> [FIX] Discussion names showing a random value

app/ui-utils/client/lib/messageContext.js
=> [FIX] Not possible accept video call if "Hide right sidebar with click" is enabled

ee/app/api-enterprise/server/canned-responses.js, ee/app/api-enterprise/server/lib/canned-responses.js
=> [FIX] Canned response endpoint isn't filtering by text

.github/workflows/build_and_test.yml
We're still having issues with an old cached node_modules, changing the key should invalidate all previously stored cache files, hopefully fixing the issue.
This seems to affect other repos as well, see https://github.com/maidsafe/brb_node_qp2p/pull/25/files  thx @KevLehman for letting me know about this
=> Chore: Bump node_modules cache key

app/livechat/client/lib/stream/queueManager.js
When a new chat arrives in the Omnichannel queue(Manual selection algoritm), a sound notification is emitted, but when the chat is forwarded from one department queue to another, the sound notification is not emitted.
=> [FIX] Sound notification is not emitted when the Omnichannel chat comes from another department

client/sidebar/header/CreateDirectMessage.tsx
- open the create direct messages modal 
- select multiple users
=> Regression: Missing flexDirection on select field

app/videobridge/server/methods/jitsiGenerateToken.js, client/lib/getUserEmailAddress.ts, client/views/account/AccountProfileForm.js, client/views/account/AccountProfilePage.js, client/views/admin/permissions/UserRow.js, client/views/admin/users/UserInfo.js, client/views/omnichannel/agents/AgentEdit.js, client/views/room/contextualBar/UserInfo/UserInfoWithData.js, lib/getUserEmailAddress.ts
=> [FIX] Error generating Jitsi Token

client/views/omnichannel/realTimeMonitoring/charts/ChatDurationChart.js, client/views/omnichannel/realTimeMonitoring/charts/ResponseTimesChart.js
Corresponding Clickup task: https://app.clickup.com/t/5999h0
=> [Fix] Omnichannel Real Time Monitoring charts not displaying all data

tests/end-to-end/api/13-roles.js
=> Regression: Api tests not running

client/views/omnichannel/realTimeMonitoring/charts/ChatsPerAgentChart.js, client/views/omnichannel/realTimeMonitoring/charts/ChatsPerDepartmentChart.js
=> [Fix] Real Time Monitoring charts - chats-per-agent and chats-per-department - not visible

sfu/config.ts, sfu/methods/createProducer.ts, sfu/methods/room.ts
- Existing peer consumes produce from new peer
- Get peer method to get peer details
=> [IMPROVE] SFU server config and consumers for new peers

client/components/AutoCompleteDepartment.js, client/components/Omnichannel/hooks/useDepartmentsList.ts, client/contexts/ServerContext/endpoints/v1/livechat/department.ts
=> [FIX] Bugs in AutoCompleteDepartment

client/components/AutoCompleteDepartment.js, client/components/AutoCompleteDepartmentMultiple.js, ee/client/omnichannel/units/UnitEdit.js
Dependencies: https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/475
=> [FIX] Put title into AutocompleteDepartment components

client/components/AutoCompleteDepartmentMultiple.js, ee/client/omnichannel/units/UnitEdit.js
=> [FIX] Sort AutocompleteDepartmentsMultiple

client/startup/routes.ts
=> [FIX] Setup wizard infinite loop when on subfolder.

client/startup/index.ts, client/startup/oauth.ts
=> [FIX] OAuth login not working on electron app with temp sessions.

client/components/AutoCompleteAgent.js, client/components/Omnichannel/hooks/useAgentsList.ts, client/views/omnichannel/currentChats/FilterByText.tsx, client/views/omnichannel/departments/EditDepartment.js
=> [FIX] haveAll prop in options of useAgentList

app/apps/server/communication/websockets.js, package-lock.json, package.json
FIxes erros where, on HA setups, instances that DID NOT originate the action of uninstalling and updating an app would maintain the wrong status of apps when they received the notification of these events via Streamer. 
*The error is only reproducible on HA/Cluster setups*
1. Update an existing app in one of the instances in the Cluster
2. The update will not be propagated to other instances
OR
1. Uninstall an existing app from one of the instances of the Cluster
2. The app is still visible on the other instances
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/428
=> [FIX] Apps not syncing status correctly on HA setups

app/channel-settings/server/methods/saveRoomSettings.js, app/lib/lib/MessageTypes.js, app/message-pin/client/index.js, app/message-pin/client/messageType.js, app/models/server/models/Messages.js, app/models/server/models/Rooms.js, client/sidebar/RoomList/normalizeSidebarMessage.js, packages/rocketchat-i18n/i18n/en.i18n.json, packages/rocketchat-i18n/i18n/pt-BR.i18n.json, packages/rocketchat-i18n/i18n/pt.i18n.json, tests/end-to-end/api/02-channels.js, tests/end-to-end/api/03-groups.js
Reverts RocketChat/Rocket.Chat#22018
=> Revert: [IMPROVE] Update system messages' behavior in rooms

app/theme/client/imports/general/react-root.css
=> Regression: Block-size property on firefox

app/voice-channel/client/index.ts, client/views/room/VoiceRoom/VoicePeer.tsx, client/views/room/VoiceRoom/VoiceRoom.tsx, client/views/room/hooks/useVoiceRoom.ts, definition/IVoiceRoomPeer.ts, packages/rocketchat-i18n/i18n/en.i18n.json, sfu/methods/room.ts
- Peer view improved to handle connecting/disconnecting of peers while they are in IDLE state ( i.e to view a room without joining ) or connected to a room. 
- Peer view for rounded avatars fixed to default
- Modal when user tries to join a different room while staying connected to one.
=> [IMPROVE] Peer Connections & Peer views

.meteor/packages, .meteor/versions, app/cors/server/cors.js, app/livechat/server/livechat.js, app/ui-master/server/index.js
=> Regression: CSP for external Media and Frames

client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
=> [FIX] Visitor info screen being updated multiple times

README.md
=> [IMPROVE] Update README.md

app/cors/server/cors.js
=> Chore: Remove JSON parse middleware

app/ui/client/lib/chatMessages.js
- Try to delete a message
- Try to delete a message that is a discussion
(The text between those change)
- Try to delete a message by editing it and then erasing all content and hitting send.
- Try to delete a message by editing and then cancel or close the modal.
(In both those cases the messagebox should be reset)
=> [IMPROVE] Message deletion modal

package-lock.json, package.json
Updated Apps-Engine version fixes errors with apps using livechat features.
=> [FIX] Livechat apps permission error

client/views/room/contextualBar/RoomMembers/List/RoomMembers.js
=> [FIX] Unnecessary space on members list footer

.meteor/versions
=> Regression: observe-sequence version syntax broken on IE

ee/server/services/package-lock.json, ee/server/services/package.json, package-lock.json, package.json
=> Chore: Upgrade Micro Services NPM dependencies

app/otr/client/rocketchat.otr.room.js
=> [IMPROVE] Rewrite accept OTR modal

app/otr/client/rocketchat.otr.room.js
- Start an OTR in a direct message
- Cancel this OTR and check the modal on the peer side
=> [IMPROVE] Rewrite OTR end modal

app/otr/client/rocketchat.otr.room.js
- Start an OTR in a direct message
- Do not accept the request on the peer side
- Check the modal where you sent the request for OTR
=> [IMPROVE] Rewrite Deny OTR Modal

package-lock.json, package.json
Update the Apps-Engine with a fix for the permission check on the `getLivechatDepartmentByNameOrId` method
=> [FIX] Error in permission check for getLivechatDepartmentByNameOrId method in Apps

ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.js
=> Regression: Change the name of called methods in Users model

README.md
=> Chore: Create README.md

app/models/server/raw/Users.js
In the other PR, i modified other files too, but some of the base models were having issues with the projection option.
=> Chore: Use projection instead of fields to avoid error log

app/ui-cached-collection/client/models/CachedCollection.js
=> [FIX] Channels or Teams deleted are not removed from the sidebar.

client/sidebar/header/CreateChannelWithData.js, client/views/room/VoiceRoom/VoiceRoom.tsx
Fixing peer views while peer disconnects from one voice room to another
=> [FIX] Peer views in voice rooms

client/views/admin/info/DescriptionListEntry.js
=> [FIX] Info page - Instances card modal table width

app/theme/client/imports/components/sidebar/sidebar.css, app/ui-sidenav/client/sideNav.html, app/ui-sidenav/client/sideNav.js, client/sidebar/footer/SidebarFooter.tsx, client/sidebar/footer/index.ts, client/templates.ts
=> [IMPROVE] Rewrite sidebar footer as React Component

ee/server/services/package-lock.json, ee/server/services/package.json
=> Regression: Fix ee microservices build

app/livechat/server/config.js
=> Chore: Enable Omnicahnnel by default

ee/app/livechat-enterprise/server/lib/Helper.js
@renatobecker 
Resolves issue: https://github.com/RocketChat/Rocket.Chat/issues/22696
=> [FIX] Use room's last message time when visitor did not send any message

ee/app/api-enterprise/server/canned-responses.js, ee/app/api-enterprise/server/lib/canned-responses.js, ee/app/canned-responses/server/methods/saveCannedResponse.js, ee/app/canned-responses/server/permissions.js
=> Chore: Use permissions instead of roles to check for canned responses

client/components/MarkdownText.tsx, client/components/Message/Attachments/DefaultAttachment.tsx, package-lock.json
I've incorrectly enforcing the newline character in attachment fields, resulting in "&lt;br /&gt;" text being rendered.
=> Regression: Properly force newline in attachment fields

client/templates.ts
=> Regression: Prevent custom status from being visible in sequential messages

app/statistics/server/lib/getServicesStatistics.ts
=> Regression: Rocket.Chat crashes on startup if there's a Custom OAuth service configured

ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx, ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/PreviewText.tsx
=> Regression: Check for text before parse preview in create canned response form

packages/meteor-jalik-ufs/ufs-store.js
=> Regression: Internal Error when saving files using GridFS

app/livechat/server/api/lib/users.js, ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx, ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx, ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/SharingOptions.tsx
=> Regression: Fix canned responses permissions for monitors & managers

packages/meteor-jalik-ufs/ufs-store.js
=> Regression: Replaced manual state control with a .once event

ee/app/engagement-dashboard/client/components/UsersTab/BusiestChatTimesSection.js
- Fix tooltip in the Engagement Dashboard's "Busiest Chat Times" chart (Hours).
**Expected behavior:**
[Task - ClickUp](https://app.clickup.com/t/61b03k)
Access **Administration > Engagement Dashboard**.
=> Regression: Fix tooltip style in the "Busiest Chat Times" chart

app/api/server/v1/roles.js, app/authorization/server/methods/addUserToRole.js, app/models/server/models/Roles.js, app/models/server/raw/Roles.js, tests/end-to-end/api/13-roles.js
=> Regression: roles.removeUserFromRole API not working with scoped roles.

client/views/admin/info/FederationCard/components/FederationModal/FederationModal.tsx, client/views/admin/info/FederationCard/components/FederationModal/styles.css
=> [FIX] Tab margin style

app/authorization/server/functions/canSendMessage.js, app/lib/server/lib/processDirectEmail.js, app/videobridge/client/actionLink.js
- Add check to `room.muted` array so as to cover the case in which it is `undefined`;
[Task - ClickUp](https://app.clickup.com/t/1axcwpx)
Fixes #22845 
Start a call in a room and, logged in as another user, press the "Click to Join!" button (system message) which has been sent in the room. No errors should be thrown in the console.
=> [FIX] "Click to Join" button is not working if there are no muted users in the room

client/views/room/Room/Room.js, client/views/room/VoiceRoom/VoiceRoom.tsx
When changing rooms, joined voice channel audio is now audible.
=> [FIX] Voice channel audio in background when changing channels/rooms

app/apps/server/orchestrator.js, app/apps/server/storage/AppGridFSSourceStorage.ts, server/startup/migrations/index.js, server/startup/migrations/v229.js
=> [NEW] Migration: apps new storage strategy

server/lib/isPresenceMonitorEnabled.ts, server/modules/watchers/watchers.module.ts, server/services/meteor/service.ts, server/startup/presence.js, server/stream/streamBroadcast.js
Closes https://github.com/RocketChat/Rocket.Chat/issues/22503
=> [FIX] User presence being processes even if presence monitor was disabled

app/webrtc/client/tabBar.tsx, definition/IRoom.ts
Call button is not rendered when the chat is queued. It will only show up after an agent takes it up.
=> [FIX] Call button visible even when chat is queued

app/ui-utils/client/lib/readMessages.js
=> Regression: readNow blocked by a invalid condition

app/livechat/server/api/lib/livechat.js
=> [NEW] add callStatus attribute in room object

.github/workflows/no-new-js-files.yml
=> Regression: no-js-action bump version

ee/server/api/licenses.ts
=> [NEW] licenses.maxActiveUsers endpoint

app/api/server/v1/im.js, server/methods/createDirectMessage.js, tests/end-to-end/api/04-direct-message.js
- Added a new param to `createDirectMessage` to identify who is calling it, instead of calling `Meteor.userId()` within the function, since it could be empty depending on the context
- Added a test case for self-DM
introduced by https://github.com/RocketChat/Rocket.Chat/pull/18022
=> Regression: Fix creation of self-DMs

app/videobridge/server/methods/jitsiSetTimeout.js, app/webrtc/client/WebRTCClass.js
=> [IMPROVE] Attach jitsi link to message object for Livechat 

app/models/server/models/Settings.js, server/startup/migrations/index.js, server/startup/migrations/v231.ts
Add a banner to inform admins about future authentication changes. This banner targets servers that use some sort of authentication service since they're the ones which this update concerns the most.
=> [NEW] Banner for the updates regarding authentication services

app/apps/server/orchestrator.js
=> Chore: Environmental variable for marketplace url

app/api/server/api.js, app/lib/server/lib/debug.js
Change log level of HTTP and Method requests to INFO level and use a more standard and easy to read format. Additionally add an env var to also log request payloads.
This will be superseded by #22975
=> [IMPROVE] Change HTTP and Method logs to level INFO

package-lock.json, package.json
Upgrades `limax` for faster slugify algorithm.
=> Chore: Upgrade limax

.github/workflows/build_and_test.yml
=> Chore: Change Ubuntu version to 20.04 on all GitHub Actions

app/ui-message/client/message.html
=> Regression: `renderEmoji` helper referred as a template

client/UIKit/hooks/useUIKitHandleAction.tsx
=> [IMPROVE] Throw error if no appId is provided to useUIKitHandleAction

ee/app/license/server/license.ts
=> [NEW] Remove license downgrade if exceeding seats cap

docker-compose.yml
With not set registration will just hang
`docker-compose up -d` - with no changes
=> Chore: Make SMTP empty on docker-compose so registration won't hang out of the box

client/views/teams/CreateTeamModal/CreateTeamModal.tsx
Fuselage Dependency: [543](https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/543)
=> [FIX] Modals is cutting pixels of the content

packages/rocketchat-i18n/i18n/en.i18n.json
=> Regression: Missing i18n key

app/settings/server/functions/settings.ts
auto-sorter not grouping settings by section and not p…rioritizing the ones without any section.
=> Regression: wrong settings order

ee/server/startup/seatsCap.ts
=> Regression: Seats Cap banner not being disabled if not enterprise

server/features/EmailInbox/EmailInbox.ts, server/features/EmailInbox/EmailInbox_Incoming.ts
=> Regression: Change some logs to new format

app/integrations/server/api/api.js, app/integrations/server/lib/triggerHandler.js, app/lib/server/functions/processWebhookMessage.js
Remove deprecated behavior added by https://github.com/RocketChat/Rocket.Chat/pull/18024 that accepts webhook integrations sending messages even if the user is not part of the channel.
Starting from 4.0.0 the webhook request will fail with `error-not-allowed` error:
```
{"success":false,"error":"error-not-allowed"}
```
=> [BREAK] Webhook will fail if user is not part of the channel

ee/app/license/server/getSeatsRequestLink.ts
=> Regression: Request seats url

app/api/server/helpers/isWidget.ts
=> Regression: Add default value when no cookies are present

app/ui-message/client/messageBox/messageBox.js
=> Regression: "Join" button not working

client/views/room/contextualBar/Call/Jitsi/CallJitsiWithData.js, client/views/room/contextualBar/Call/Jitsi/index.ts
- Fix Jitsi calls being disposed even when "Open in new window" setting is disabled;
- Fix misspelling on `CallJitsWithData.js` file name.
[Task - ClickUp](https://app.clickup.com/t/1e4ewa3)
Fixes #23038
Fixes #22954
Start a Jitsi Call in a room. **_Expected behavior:_** the call's frame should be displayed in the sidebar.
=> [FIX] Blank screen in Jitsi video calls

app/meteor-accounts-saml/tests/server.tests.ts
=> Regression: Removed exclusive tests statement

app/e2e/client/rocketchat.e2e.js, app/e2e/client/rocketchat.e2e.room.js, app/ui-message/client/messageBox/messageBoxNotSubscribed.js
=> Regression: invalid `call` import

app/api/server/v1/banners.ts
Describes endpoints for banners on REST API using a JSDoc annotation compatible with OpenAPI spec.
=> Chore: Document REST API endpoints (banners)

server/startup/migrations/index.ts
=> [FIX] imported migration v240

app/bigbluebutton/server/bigbluebutton-api.js
Add missing import to bigbluebutton-api.js
Fixes BigBlueButton integration
#23365 
Try to start a BBB Meeting. Without this fix, the call fails.
=> [FIX] BigBlueButton integration error due to missing file import

app/lib/server/functions/getFullUserData.js
=> [FIX] unwanted toastr error message when deleting user

client/startup/loginViaQuery.ts
Closes https://github.com/RocketChat/Rocket.Chat/issues/23363
=> [FIX] resumeToken not working

server/restapi/README.md
Removes the elderly `server/restapi/README.md`.
=> Chore: Remove dangling README file

server/startup/serverRunning.js
=> [FIX] MongoDB deprecation link

app/apps/server/bridges/scheduler.ts, app/apps/server/orchestrator.js
If a job is scheduled and the server restarted, said job won't be executed, giving the impression it's been lost.
What happens is that the scheduler is only started when some app tries to schedule an app - if that happens, all jobs that are "late" will be executed; if that doesn't happen, no job will run.
This PR starts the apps scheduler right after all apps have been loaded
=> [FIX] Apps scheduler "losing" jobs after server restart

ee/server/lib/ldap/Manager.ts
=> [FIX] LDAP users not being re-activated on login

app/livechat/server/business-hour/AbstractBusinessHour.ts, app/livechat/server/lib/Livechat.js, app/livechat/server/startup.js, app/models/server/models/Users.js, app/models/server/raw/Users.js
=> [FIX] Omnichannel status being changed on page refresh

app/utils/lib/getURL.tests.js, client/views/omnichannel/departments/EditDepartment.js, client/views/omnichannel/departments/EditDepartmentWithAllowedForwardData.js, client/views/omnichannel/departments/EditDepartmentWithData.js
Overhauls all places where eslint's `complexity` rule is disabled.
=> [IMPROVE] Reduce complexity in some functions

.storybook/mocks/meteor.js, .storybook/preview.ts, client/hooks/useCallbacks.js, client/methods/updateMessage.js, client/providers/UserProvider.tsx, client/sidebar/header/UserDropdown.js, client/startup/renderMessage/autolinker.ts, client/startup/renderMessage/autotranslate.ts, client/startup/renderMessage/emoji.ts, client/startup/renderMessage/hexcolor.ts, client/startup/renderMessage/highlightWords.ts, client/startup/renderMessage/issuelink.ts, client/startup/renderMessage/katex.ts, client/startup/renderMessage/markdown.ts, client/startup/renderMessage/mentionsMessage.ts, client/startup/renderNotification/markdown.ts, client/startup/streamMessage/autotranslate.ts, client/startup/userStatusManuallySet.ts, client/views/setupWizard/steps/AdminUserInformationStep.js
=> Chore: Remove useCallbacks

app/models/server/raw/Analytics.ts, app/models/server/raw/Sessions.ts
=> Regression: Improve AggregationCursor types

app/livechat/imports/server/rest/sms.js, app/models/server/models/LivechatRooms.js, packages/rocketchat-i18n/i18n/en.i18n.json
-  Allow override of default department for SMS Livechat sessions
- Current implementation searches for room for SMS sessions using just visitor tokens, updated it to use department ID as well so that a user can have different rooms open with different departments.
- Updated admin settings description for SMS endpoint
https://github.com/RocketChat/feature-requests/issues/527
Modify the post endpoint URL in twilio WhatsApp configuration as **https://<SERVER_URL>/api/v1/livechat/sms-incoming/twilio?departmentName=<departmentName>** to test.
=> [IMPROVE] Allow override of default department for SMS Livechat sessions

client/views/omnichannel/businessHours/BusinessHoursRouter.js, client/views/omnichannel/businessHours/EditBusinessHoursPage.js
Resolved the issue for having Business hour screen.
Removed the dependency on context and type inside useEffect in BusinessHoursRouter.
Before:
https://user-images.githubusercontent.com/50165440/139543577-2fc91ecb-5b16-4663-8316-3417e2833f38.mp4
After:
https://user-images.githubusercontent.com/50165440/139847507-efd90639-0b77-474b-b13d-40d01f621864.mp4
#23349 
Mentioned in the Issue
<!-- If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc... --
>
=> [FIX] Omnichannel business hours page breaking navigation

app/livechat/server/methods/saveIntegration.js
Solved the Issue of not able to save webhook URL.
https://user-images.githubusercontent.com/50165440/140527811-7463e09b-a01c-4b15-ba38-3bf2d8ed2787.mp4
https://user-images.githubusercontent.com/50165440/140527826-b88d060d-8ad6-4787-a759-338e3f6e6879.mp4
#23630 
Mentioned in the issue
=> [FIX] Omnichannel webhooks can't be saved

client/components/MarkdownText.tsx
=> [FIX] Horizontal rule render for inline marked options

ee/app/canned-responses/server/hooks/onMessageSentParsePlaceholder.ts
=> [FIX][ENTERPRISE] Replace all occurrences of a placeholder on string instead of just first one

packages/rocketchat-i18n/i18n/fr.i18n.json
=> [FIX] Fix typo in FR translation

.eslintrc, package-lock.json, package.json
https://krebsonsecurity.com/2021/11/trojan-source-bug-threatens-the-security-of-all-code/
=> Chore: add `no-bidi` rule

app/ui/client/lib/UserAction.ts, client/lib/RoomManager.ts, client/views/room/contexts/RoomContext.ts, client/views/room/providers/RoomProvider.tsx
When you take an Omnichannel chat from queue, the guest's typing information will appear.
=> [FIX] Prevent UserAction.addStream without Subscription

client/components/avatar/UserAvatarEditor/UserAvatarEditor.js
The Content-Security-Policy for img-src is `img-src * data:` this allows only data URI, but `URL.createObjectURL(file)` return a blob URI `'blob:http://localhost:3000/5b9558d9-2de9-4959-90bc-8ddd7ff15210'` so it need to be converted to data URI.
https://user-images.githubusercontent.com/50165440/140659865-a9e91482-40d9-4b7c-9fe9-4426c516791e.mp4
https://user-images.githubusercontent.com/50165440/140659744-73fdad05-30a8-40ac-ab27-d11ebc44de10.mp4
#23105 
Mentioned in the issue
=> [FIX] broken avatar preview when changing avatar

app/discussion/client/createDiscussionMessageAction.js, app/discussion/client/discussionFromMessageBox.js, app/discussion/server/methods/createDiscussion.js, app/ui-message/client/messageBox/messageBox.js
=> [FIX] Discussions created inside discussions

client/views/admin/users/EditUser.js, client/views/admin/users/UserInfo.js
=> [FIX] Missing user roles in edit user tab

app/livechat/server/lib/Livechat.js, app/livechat/server/lib/stream/agentStatus.ts
=> [FIX] Await promise to handle error when attempting to transfer a room

app/ui-utils/client/lib/SideNav.js
Removed "generic" autofocus on sidenav template.
=> [FIX] Autofocus on search input in admin

app/api/server/helpers/deprecationWarning.ts, definition/ILivechatBusinessUnit.ts, definition/IOmnichannelBusinessUnit.ts, ee/app/livechat-enterprise/server/api/business-hours.ts, ee/app/livechat-enterprise/server/api/lib/monitors.js, ee/app/livechat-enterprise/server/api/lib/units.js, ee/app/livechat-enterprise/server/api/units.js, ee/app/livechat-enterprise/server/api/units.ts, ee/definition/rest/index.ts, ee/definition/rest/v1/omnichannel/businessUnits.ts, ee/definition/rest/v1/omnichannel/index.ts
Basic documentation about endpoints can be found at https://www.postman.com/kaleman960/workspace/rocketchat-public-api/request/3865466-71502450-8c8f-42b4-8954-1cd3d01fcb0c
=> [NEW] REST endpoints to manage Omnichannel Business Units

app/cloud/server/index.js
You can provide the REG_TOKEN environment variable containing a registration token and it will automatically register to your cloud account.  This simplifies the registration flow
=> [NEW] Allow registering by REG_TOKEN environment variable

package-lock.json, package.json
=> Chore: Bump Rocket.Chat@livechat to 1.10

app/api/server/api.d.ts, app/api/server/api.js, client/lib/2fa/utils.ts, client/views/admin/settings/groups/LDAPGroupPage.tsx, ee/server/api/api.ts, ee/server/api/index.ts, ee/server/api/ldap.ts
Open the Enterprise LDAP API that executes background sync to be used without any Enterprise License and enforce 2FA requirements.
=> [NEW] Enable LDAP manual sync to deployments without EE license

app/lib/server/startup/rateLimiter.js
Replace the old "RateLimiter" logs with possibly duplicated `name` field
```
{"level":30,"time":"2021-11-22T22:09:14.898Z","pid":28992,"hostname":"xxx","name":"RateLimiter","msg":"DDP RATE LIMIT: 'limit by connectionId per method'"}
{"level":30,"time":"2021-11-22T22:09:14.898Z","pid":28992,"hostname":"xxx","name":"RateLimiter","allowed":false,"timeToReset":26506,"numInvocationsLeft":0,"userId":"EdmuWN4oACP78BZoJ","clientAddress":"127.0.0.1","type":"subscription","name":"stream-user-presence","connectionId":"PvEgDQ9pTZKHi5QPX","broadcastAuth":false}
```
by a single log entry with all details in separate fields:
```
{"level":30,"time":"2021-11-22T22:02:51.631Z","pid":28849,"hostname":"xxx","name":"RateLimiter","msg":"limit by connectionId per …
```
=> Chore: Remove duplicated 'name' key from rate limiter logs

app/authentication/server/lib/restrictLoginAttempts.ts
=> [FIX] Registration not possible when any user is blocked for multiple failed logins

client/startup/routes.ts, client/views/meet/MeetPage.tsx
=> Regression: Fix incorrect API path for livechat calls

client/components/Omnichannel/hooks/useAgentsList.ts, client/components/Omnichannel/hooks/useDepartmentsList.ts, client/views/admin/customEmoji/CustomEmoji.tsx, definition/rest/helpers/PaginatedRequest.ts
=> Regression: Fix sort param on omnichannel endpoints

.github/workflows/build_and_test.yml, ee/server/services/tsconfig.json
Using only `"include": ["../../../definition"]` on EE's `tsconfig.json` file was actually building **only** definitions, the source code must be included as well.
=> Regression: Include files on EE services build

ee/server/services/package-lock.json, ee/server/services/package.json
=> Regression: Add @rocket.chat/emitter to EE services

client/views/omnichannel/currentChats/CurrentChatsPage.tsx, client/views/omnichannel/currentChats/FilterByText.tsx
I've decided to move the logic that set the `setParams` to the filter component, instead of the generic table
=> Regression: Current Chats not Filtering

client/views/room/Header/ToolBox/ToolBox.tsx
=> Chore: Change Menu props to accept next fuselage version

app/cors/server/cors.js
Add the hash of the JS inside the page that won't close ( window.close(); )
#22525
=> [FIX] Add CSP to authorize auto-close of CAS login window

app/livechat/server/api/lib/livechat.js, app/livechat/server/config.ts, app/livechat/server/lib/Livechat.js, app/livechat/server/methods/getInitialData.js, packages/rocketchat-i18n/i18n/en.i18n.json
Include setting to handle with and clear the localStorage on Livechat widget. 
This behavior is only possible to happen when https://github.com/RocketChat/Rocket.Chat.Livechat/pull/666 merged and released.
=> [NEW] Create new setting to clean local storage at end of chats

app/theme/client/imports/components/popover.css, app/ui-utils/client/lib/popover.html
Added the hover effect on the item in the kebab menu.
https://user-images.githubusercontent.com/50165440/141688133-fee7550a-a996-49e7-a55d-f3e32fc930b0.mp4
https://user-images.githubusercontent.com/50165440/141687910-3c4949ec-7730-4f6c-ba3c-f2cfa345b8b8.mp4
Closes #23708 
Mentioned in the issue
=> [FIX] No hover effect for items in kebab menu.

app/authentication/server/startup/index.js
- Fix `usersInRole` array used to send email to activate a user.
Go to **Administration > Users > New** and create a new user (enable "Set random password and send by email"). No error should be displayed while creating the user.
=> [FIX] Error when creating an inactive user in admin panel

app/apps/client/orchestrator.js, client/views/admin/apps/helpers.js, client/views/admin/apps/types.ts, client/views/room/Header/ToolBox/ToolBox.tsx
This PR solves a bug on the marketplace that was happening with WhatsApp where it was displaying a trial button even though it didn't have a free trial period. The new verification I've added checks if the app is subscription-based and then checks if it has 0 trial days in all of its tiers. If it does, it shows a subscribe button. If it doesn't, it displays a trial button. Also, I've exposed the itsEnterpriseOnly flag as an extra measure in the case of apps like Facebook Messenger that are enterprise-only and consequently should show the subscribe button.  
Before:
After:
1. Open Marketplace
2. Search for Whatsapp on marketplace
3. Hover over the app and the wrong button will show
=> [FIX] Wrong button for non trials apps
