server/modules/watchers/watchers.module.ts
Previously when any data changed on subscriptions or rooms we were getting fresh data from database, to also remove undesired fields, but sometimes the data that changed was not relevant so we were sending the whole object everytime **without** the fields that actually changed. This change aims to reduce this overhead and also send less data to clients.
=> [IMPROVE] Send only relevant data via WebSocket

app/livechat/server/lib/Helper.js
Revert invalid check introduced here -> https://github.com/RocketChat/Rocket.Chat/pull/22154
Cursors don't have length property, so it always returns false and, hence, notifications are no longer being sent to online agents.
=> [FIX] Remove invalid check before sending notifications to Omnichannel online agents

app/api/server/v1/teams.ts
If the user is trying to list his own channels, the permission check is skipped.
- Try to leave a team with a user that has no privileges (eg. is not owner/leader nor admin)
- The users joined channels should be displayed even if he does not has the `view-all-team-channels` permission.
PS.: If the user has not joined any additional rooms inside the team, the first step of the modal is not displayed.
=> [FIX] Permission check for teams.listRoomsOfUser

.github/pr-title-checker-config.json, .github/workflows/pr-title-checker.yml
We just need to define the list of Prefixes to use, and if we will do any other validation (the action supports using regexes to validate PR titles, but, i don't think we need it 😬)
=> Chore: Check PR Title on every submission

app/models/server/models/LivechatDepartment.js, app/models/server/models/LivechatTrigger.js, ee/app/models/server/models/LivechatUnitMonitors.js
=> [IMPROVE] Add new indexes for omnichannel-related collections

app/api/server/v1/channels.js, app/api/server/v1/groups.js, app/api/server/v1/im.js, app/lib/server/functions/loadMessageHistory.js, app/lib/server/lib/getHiddenSystemMessages.ts, app/lib/server/methods/getChannelHistory.js, app/models/server/models/Messages.js, definition/IRoom.ts, definition/ISetting.ts
=> [FIX] `channels.history`, `groups.history` and `im.history` REST endpoints not respecting hide system message config

app/lib/server/methods/getUserRoles.js, server/services/authorization/service.ts
Moving this code to a service to make it re-usable and also adding a small cache since this info doesn't change very often.
=> Chore: Move getUserRoles to service and add cache

app/lib/server/methods/sendMessage.js
This fix email notifications not using user's real name, even though the setting "Use Real Name" was enabled. There is an interesting bug going on as well, that if the Apps framework was enabled, this bug doesn't happen.
- Disable Apps framework
- Enable Use Real Name
- Send a message that triggers a email notification to someone (the receiver user must have the email address verified)
- Check out the email it will have only the sender's username
=> [FIX] Notifications not using user's name

app/models/server/models/LivechatDepartment.js
This error is happening when visitor is sending the first message:
```
Exception on find errorClass [Error]: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
at check (packages/check/match.js:36:17)
at ns.Collection._getFindOptions (packages/mongo/collection.js:295:7)
at ns.Collection.find (packages/mongo/collection.js:336:12)
at BaseDb.find (app/models/server/models/_BaseDb.js:177:21)
at LivechatDepartment.find (app/models/server/models/_Base.js:106:29)
at LivechatDepartment.findEnabledWithAgents (app/models/server/models/LivechatDepartment.js:100:15)
at Object.getRequiredDepartment (app/livechat/server/lib/Livechat.js:125:42)
at app/livechat/server/lib/Livechat.js:152:29
at /home/chinello/.meteor/packages/promise/.0.11.2.j40ifr.9pr39++os+web.browser+web.browser.l …
```
=> Regression: Fix livechat find departments

app/api/server/v1/rooms.js, client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.js
The issue was that `rooms.cleanHistory` endpoint receives a param called `users` but frontend was passing a param called `fromUsers` instead, causing it to ignore the selected users from the UI.
=> [FIX] Prune messages from particular user(s)

app/lib/server/functions/insertMessage.js, app/lib/server/functions/parseUrlsInMessage.js
If a message lists the same URL twice, the URL would be previewed twice.
This includes Markdown code explicitly using the URL as the link text.
e.g.
```
[http://example.com/](http://example.com/)
```
Strip out duplicate URLs when parsing them out, so we only show a single preview.
=> [IMPROVE] Preview message URLs only once

app/authorization/client/startup.js
=> Regression: Client crashing on startup

client/components/ConfirmOwnerChangeWarningModal.tsx, client/views/account/AccountProfilePage.js, client/views/account/ActionConfirmModal.tsx, packages/rocketchat-i18n/i18n/en.i18n.json
=> [FIX] Confirm owner change process when deleting own account

app/lib/server/methods/getChannelHistory.js
There is a typo in the 56 line. I've added 'hiddenMessageTypes'.
How to reproduce:
- call getChannelHistory method with 'oldest' param.
=> [FIX] crush in the getChannelHistory method

app/api/server/v1/chat.js, server/methods/messageSearch.js, tests/end-to-end/api/05-chat.js
=> Chore: added pagination to search msg endpoint

app/livechat/server/lib/Livechat.js
=> [IMPROVE] Refactor `livechat.registerGuest` function

ee/app/livechat-enterprise/server/lib/Helper.js
This PR reverts a previous fix for visitor abandonment.  The original fix did not handle the use case where the room is empty.  We will make a new PR that handles all cases and resubmit.
=> revert the lastMessage fix for visitor abandonment

app/lib/server/methods/getChannelHistory.js, app/models/server/models/Users.js, app/settings/client/lib/settings.ts, app/settings/lib/settings.ts, app/statistics/server/lib/getServicesStatistics.ts, app/statistics/server/lib/statistics.js
=> [NEW] Collect data about LDAP, SAML, CAS and OAuth usage.

app/api/server/v1/teams.ts, client/views/room/contextualBar/Info/ChannelToTeamModal/StepOne.js
- Enter a room
- Open Room Info
- Click on the kebab-menu (or if visible, directly on the Move to Team button)
- Click the Move to Team button
- The modal shouldn't allow to continue before selecting a team
=> [FIX] Channel is automatically getting added to the first option in move to team feature

ee/client/omnichannel/hooks/useCannedResponseList.ts
=> Regression: Allow users to search canned responses based on shortcut or content

ee/app/api-enterprise/server/lib/canned-responses.js, ee/client/omnichannel/cannedResponses/CannedResponseFilter.tsx, ee/client/omnichannel/hooks/useCannedResponseList.ts
=> Regression: Filter of canned responses in contextual-bar

client/views/admin/info/FederationCard/components/FederationModal/FederationModal.tsx
fix some linting warnings on federation modal
=> Regression: Federation warnings on ci

ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
=> Regression: Translate scope on canned responses dashboard

app/apps/server/bridges/livechat.ts, app/livechat/server/lib/Livechat.js, server/features/EmailInbox/EmailInbox_Incoming.ts
=> [FIX] Support ID param on createVisitor method

app/livechat/server/api/v1/visitor.js
At livechat widget side, when visitor click on accept or decline button, with the updateCallStatus function, I am making a post request with updated call status value and update the status of call at rc-core. Below I attach sdk and livechat widget pr, which all together will be needed to make this work.
I create function updateCallStatus at sdk to communicate with rc-core. PR => RocketChat/Rocket.Chat.js.SDK#142
Livechat.updateCallStatus is used at livechat to update the call status PR => RocketChat/Rocket.Chat.Livechat#624
=> [NEW] update call status

app/models/server/raw/Subscriptions.ts, app/notifications/client/lib/Notifications.js, app/webrtc/client/WebRTCClass.js, app/webrtc/client/actionLink.tsx, client/startup/routes.ts, client/views/meet/CallPage.js, client/views/meet/MeetPage.js, definition/ISubscription.ts, packages/rocketchat-i18n/i18n/en.i18n.json, server/modules/notifications/notifications.module.ts
Allowing a visitor and agent to establish P2P webrtc connection and call.
Note: The user needs to increase the limit by a connection from 10 to 15 in the DDP rate limiter section.
1. Enable `webrtc` settings in the `Administration > WebRTC`.
2. Set STUN/TURN server config. Please make sure those credentials are active and work fine.
3. Select `WebRTC` as the call provider from the `Video and Audio Call` section in the `Administration > Omnichannel`.
4. Agent should see a call button above in the action bar with the label as `WebRTC Call`.
5. Set the value of `Limit by Connection per Method: requests allowed` to `15` in the `Administration > Rate Limiter`.
6. Start a new LiveChat conversation.
7. Click on the call button to initiate a call with the visitor.
8. You will be redirected to a …
=> [NEW] P2P WebRTC Connection Establishment

app/lib/server/functions/notifications/mobile.js, app/ui/client/views/app/burger.js, client/startup/unread.ts
Removing a Chat Room lead to an unzero-able "unread messages" count,
since users couldn’t access the archived room to mark it as read.
I considered zeroing out the count when archiving the room,
however if a room would be accidentally archived and then unarchived,
state would be lost.  Archiving should really just put the room to
the side without otherwise changing it.
I also considered adding an index for `archived`.  A sparse index
shouldn’t be so expensive, but on the other hand, there will probably
not be so many room subscriptions for a given user.  Leaving it out
for now.
=> [IMPROVE] Exclude archived rooms from unread-message count

server/lib/logger/Logger.ts
=> Regression: Log Sections not respecting Log Level setting

package-lock.json, package.json, server/startup/migrations/v238.ts
The previous version of this migration didn't take into consideration apps that were installed prior to [Rocket.Chat@3.8.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.8.0), which [removed the typescript compiler from the server](https://github.com/RocketChat/Rocket.Chat/pull/18687) and into the CLI. As a result, the zip files inside each installed app's document in the database had typescript files in them instead of the now required javascript files.
As the new strategy of source code storage for apps changes the way the app is loaded, those zip files containing the source code are read everytime the app is started (or [in this particular case, updated](https://github.com/RocketChat/Rocket.Chat/pull/23286/files#diff-caf9f7a22478639e58d6514be039140a42ce1ab2d999c3efe5678c38ee3 …
=> Regression: Fix app storage migration

server/lib/logger/Logger.ts, server/lib/logger/getPino.ts, server/lib/migrations.ts
After startup, when the settings are all cached, new loggers were being created with `INFO` level, because that's the pino's default level, even though the server setting was set to `ERROR`. This commit fix that https://github.com/RocketChat/Rocket.Chat/commit/21d73a318e43611429b8e78d9fdc01051c9dc208
[The other commit](https://github.com/RocketChat/Rocket.Chat/commit/1993a1835a5e66ca45db96529d762603e557762f) basically creates a startup level, so startup message can always be shown, even if `ERROR` is the default log level.
[Changing the default log level to warn](https://github.com/RocketChat/Rocket.Chat/pull/23297/commits/214e066e9022d48dac53b5ed728f5e8c2cdcb5d3) will kinda restore the old behavior as before pino was introduced.
=> Regression: Create new loggers based on server log level

app/importer/server/classes/ImportDataConverter.ts, app/lib/server/functions/saveUserIdentity.js, client/views/admin/settings/groups/LDAPGroupPage.tsx, server/lib/ldap/Connection.ts, server/lib/ldap/Manager.ts
=> Regression: LDAP User Data Sync not always working

server/lib/ldap/Connection.ts
When AD requires TLS the auth crashes the server if StartTLS is not set, the error shows at the end because the code was not waiting on this operation.
=> Regression: LDAP: Handle base authentication and prevent crash

app/lib/server/functions/setUserActiveStatus.js
user admin check  at setUserActiveStatus
#23622
check issue #23622
=> [FIX] #23622 - Cannot deactive a regular user if there's only one admin

app/api/server/v1/voip/extensions.ts, app/api/server/v1/voip/queues.ts, client/views/voip/VoIPLayout.tsx, definition/IVoipConnectorResult.ts, definition/IVoipExtension.ts, server/sdk/types/IVoipService.ts, server/services/voip/connector/asterisk/CommandHandler.ts, server/services/voip/connector/asterisk/ami/AMIConnection.ts, server/services/voip/connector/asterisk/ami/PJSIPEndpoint.ts, server/services/voip/service.ts
Clickup Task : https://app.clickup.com/t/7qeq76
Description :
Some background :
Issue#1 : CommandHandler class is an entry point to a connector to Asterisk. This command handler had hardcoded values till the APIs and database for the management API was getting ready.
Once it got ready there was a need to change it and use the database values. This design change is triggered by this need.
The aim for the re-design was that all the API access should happen via voip service. It was realised that |CommandHandler| gets created (Because it is declared globally in REST APIs) before the Voip service gets initialised. And because of this fact, CommandHandler does not get to read the values as the service has not yet started and initialised |VoipServerConfiguration|.
To fix this issue, …
=> [NEW] Making connector as a part of VoipService and removing earlier hardcoding for management server

app/livechat/imports/server/rest/sms.js, packages/rocketchat-i18n/i18n/en.i18n.json
Since the endpoint supports both, department ID and department Name, so we're renaming it to reflect the same. `departmentName` -> `department`
https://github.com/RocketChat/feature-requests/issues/527
=> [IMPROVE] Re-naming department query param for Twilio

.mocharc.api.js, app/api/server/api.d.ts, app/api/server/api.js, ee/server/api/api.ts, ee/server/api/ldap.ts, tests/end-to-end/api/26-LDAP.js, tests/end-to-end/api/26-LDAP.ts
=> Regression: Fix LDAP sync route

app/livechat/server/config.ts, packages/rocketchat-i18n/i18n/en.i18n.json
=> Regression: Mark Livechat WebRTC video calling as alpha

app/apps/server/bridges/livechat.ts, package-lock.json, package.json
Add an optional param named `closer` into `LivechatBridge.closeRoom` so that it will be possible to close the room and send a close room message with the correct room closer.
If the param is not passed, use the room visitor as the room closer.
closes RocketChat/Rocket.Chat.Apps-Engine#373
Apps-Engine's PR: RocketChat/Rocket.Chat.Apps-Engine#391
=> [NEW][APPS] Possibility to set room closer via Apps LivechatBridge.closeRoom

app/apps/server/communication/uikit.js, app/ui-message/client/ActionButtonSyncer.ts, app/ui-message/client/ActionManager.js, app/ui-message/client/actionButtons/lib/applyButtonFilters.ts, app/ui-message/client/actionButtons/messageAction.ts, app/ui-message/client/actionButtons/messageBox.ts, app/ui-message/client/actionButtons/tabbar.ts, definition/IRoom.ts
=> Show buttons in contexts

app/livechat/server/lib/Livechat.js, server/email/IMAPInterceptor.ts, server/features/EmailInbox/EmailInbox_Incoming.ts
Due to a missing condition in the e-mail input processing, Rocket.Chat was unable to receive e-mails from e-mail channels that did not have a default department.
The following error is raised when an email message is sent to an email account without default department
W20211206-13:46:39.202(-3)? (STDERR) === UnHandledPromiseRejection ===
W20211206-13:46:39.204(-3)? (STDERR) errorClass [Error]: Provided department does not exists [invalid-department]
W20211206-13:46:39.204(-3)? (STDERR)     at Object.setDepartmentForGuest (app/livechat/server/lib/Livechat.js:332:10)
W20211206-13:46:39.204(-3)? (STDERR)     at getGuestByEmail (server/features/EmailInbox/EmailInbox_Incoming.ts:46:13)
W20211206-13:46:39.204(-3)? (STDERR)     at server/features/EmailInbox/EmailInbox_Incoming.ts:134:16 …
=> [IMPROVE] Allow e-mail channel to be used without default department.

app/ui-message/client/messageBox/messageBox.js, client/views/room/modals/FileUploadModal/FileUploadModal.tsx, lib/getImageExtensionFromMime.ts
=> [FIX] Add missing .png to clipboard uploaded file name

app/user-data-download/server/exportDownload.js
When using the export message tool when trying to download the file using the link sent via email if the feature "Export User Data" is disabled an error was being thrown causing the request to halt.
This is the error shown in the logs:
```
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (_http_outgoing.js:530:11)
at ServerResponse.res.setHeader (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/lib/patch.js:134:22)
at app/user-data-download/server/exportDownload.js:14:7
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
code: 'ERR_HTTP_HEADERS_SENT'
} …
```
=> [FIX] Headers already sent error when user data download is disabled

app/api/server/lib/users.js
=> Chore: added last login to users.list

app/chatpal-search/client/template/admin.js, app/lib/server/lib/validateEmailDomain.js, app/livechat/server/lib/Helper.js, app/mailer/server/api.ts, client/views/setupWizard/steps/AdminUserInformationStep.js, lib/emailValidator.ts, server/startup/initialData.js
- Create lib for validating emails
- Modify places that validate emails to use the new central function
=> Chore: Centralize email validation functionality

client/views/room/contextualBar/Call/Jitsi/CallJitsiWithData.js
- Fix Jitsi timeout update -- which caused the "Jitsi call already ended" error when trying to join a call some time after its creation;
https://user-images.githubusercontent.com/50165440/145302813-02e5bddb-3cf5-4236-9e8d-61d097efebad.mp4
https://user-images.githubusercontent.com/50165440/145302063-97830dbe-1b96-4b5b-9767-7875b4c92e55.mp4
Fix #23903 
Mentioned in the issue
=> [FIX] Jitsi call already ended

app/ui-message/client/actionButtons/tabbar.ts
Currently, action buttons registered by apps to appear in the ROOM_ACTION context show in the first position of the list, but since they don't have an icon they are effectively invisible in the tab bar.
Here we change the order configuration of the button so we make sure it only shows inside the room menu
=> Regression: Ensure room action buttons only appear inside menu

app/importer/server/startup/setImportsToInvalid.js
During a mutli-instance startup, if there is more than one instance being started at the same time, they will all try to execute the same drop command, but just a single one would succeed and the other ones would show the error below:
```
MongoError: ns not found
at MessageStream.messageHandler (/.../.meteor/packages/npm-mongo/.3.9.1.gjvjg.whtjk6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:272:20)
at MessageStream.emit (events.js:314:20)
at MessageStream.EventEmitter.emit (domain.js:483:12)
at processIncomingData (/.../.meteor/packages/npm-mongo/.3.9.1.gjvjg.whtjk6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
...
```
So instead of dropping the …
=> [FIX] MongoError during startup saying "ns not found"

ee/client/lib/getFromRestApi.ts
- Remove trailing slashes from Engagement Dashboard API requests;
Go to Administration > Engagement Dashboard. Open **DevTools > Network** and check one the API requests related to the ED:
**_Before:_** `http://localhost:3000/api//v1/engagement-dashboard/users/...`
**_After:_** `http://localhost:3000/api/v1/engagement-dashboard/users/...`
=> [FIX][ENTERPRISE] Leading slashes in Engagement Dashboard API requests

definition/IVoipExtension.ts, server/services/voip/connector/asterisk/ami/PJSIPEndpoint.ts
Before this fix, connector has been parsing the devicestate parameter incorrectly. This parameter comes as a response to command |pjsipshowendpoints| which is used for getting the list of the endpoints from the server. Parsing error happens in function getState. This function has been fixed. devicestate hold few values such as |unavailable|, |not in use|, |ringing|, |busy|. Out of these unavailable represents unregistered endpoint and "not in use" represents the endpoint which is just logged in. Rest of the values are self-explanatory. This fix returns following values based on the device state
|unavailable|  : UNREGISTERED
|not in use|: REGISTERED
|ringing| : RINGING
|busy| : BUSY
Anythingelse : UNKNOWN
https://app.clickup.com/t/1y2pz2p
1. Register the endpoint with the server.
2. Call …
=> [FIX] Return correct registration state in connector.extension.list API

packages/rocketchat-i18n/i18n/en.i18n.json
Fixed links of Terms and Privacy Policy in Setup Wizard cloud info,as it contains <a> tag.
Closes #24246 
1. Go to Admin 
2. Go to Setup Wizard
3. Cloud Info
=> [FIX] Fixed broken links in setup wizard

app/apps/server/bridges/http.ts
HTTP GET and HEAD requests made with an empty object as `data` were breaking, as the bridge converted this to the request's body as `'{}'` but meteor's new lib doesn't allow for body content on either of this request methods.
To maintain compatibility, we forced an empty body whenever we have a GET or HEAD request. This was probably the case previously, with the body of requests made with this methods being ignored either before being sent or in the third party server receiving the request
=> Regression: Fix incompatibility of apps http requests

client/lib/oauthRedirectUri.ts, client/main.ts, client/startup/oauth.ts, definition/externals/meteor/oauth.d.ts
On Meteor 2.3 release, they've removed a deprecated behavior of adding `?close` to callback URL of OAuth clients. This PR is just adding the same logic back.
We need to think of a migration path for our costumers as well.
Closes #24355
=> [FIX] Add ?close to OAuth callback url

client/main.ts, lib/oauthRedirectUri.ts, server/main.ts
Issue partially fixed on #24381 but it was missing the workaround to be used on server side as well.
The previous fix was allowing users to fill their login credentials on OAuth screen but then failing to complete the log in process.
Closes #23613
=> [FIX] OAuth mismatch redirect_uri error

client/lib/voip/Stream.ts, client/lib/voip/VoIPUser.ts, client/providers/CallProvider/CallProvider.tsx
The audio was not rendered because of re-rendering of react element based on
queueCounter and roomInfo. queueCounter and roomInfo cause the dom to re-render when call gets accepted
because after accepting call, queueCounter changes or a room gets created.
The audio element gets recreated. But VoIP user probably holds the old one.
The behaviour is not predictable when such case happens. If everything gets cleanly setup,
even if the audio element goes headless, it still continues to play the remote audio.
But in other cases, it is unreferenced the one on dom has its srcObject as null.
This causes no audio.
This fix provides a way to re-initialise the rendering elements in VoIP user
and calls this function on useEffect() if the re-render has happen.
https://app.clickup.com/t/22hy1k4
The …
=> Regression: No audio when call comes from Skype/IP phone

client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx, packages/rocketchat-i18n/i18n/en.i18n.json
this fixes:
- Wrap-up and tags fields are not displayed
- Don't use humanize() to display time fields, they should be displayed as regular time fields.
=> Regression: Fix time fields and wrap up in Voip Room Contexual bar

app/api/server/v1/voip/queues.ts, client/lib/voip/QueueAggregator.ts, client/lib/voip/VoIPUser.ts, client/providers/CallProvider/CallProvider.tsx, client/providers/CallProvider/hooks/useVoipClient.ts, definition/IVoipConnectorResult.ts, definition/IVoipExtension.ts, definition/rest/v1/voip.ts, definition/voip/ICallerInfo.ts, definition/voip/IQueueInfo.ts, definition/voip/WorkflowTypes.ts, server/modules/listeners/listeners.module.ts, server/sdk/types/IVoipService.ts, server/services/voip/connector/asterisk/ami/CallbackContext.ts, server/services/voip/service.ts
Description : Agent could be a part of multiple queues. When such a case happens,
agent's console should be able to show the consolidated calls for the queue that he/she is serving.
TO achieve this, following changes have been done.
1. Added Queue aggregator class. This class is responsible for managing the subscriptions, updating it if agent gets added/removed
from the queue. It also maintains the history of call served by the agent in current login session. This class is applicable
only for contact center agent and not for any simple voip user.
2. useVoipClient hook now initialises the aggregater with login time membership subscription.
3. Voip user contains a member variable of QueueAggregator type which will be used by CallProvider to
populate the information when the it receives call …
=> Regression: Queue counter aggregator for incoming/hanged calls

client/views/admin/settings/groups/voip/AssignAgentButton.tsx, client/views/admin/settings/groups/voip/AssignAgentModal.tsx, client/views/admin/settings/groups/voip/RemoveAgentButton.tsx, client/views/admin/settings/groups/voip/VoipExtensionsPage.tsx, definition/IVoipExtension.ts, packages/rocketchat-i18n/i18n/en.i18n.json, server/services/omnichannel-voip/service.ts
List of UI improvements:
- The Remove Association tooltip is not correct (Remove)  
- The button for agent-association is missing on the extension row  
- The Agent Name first letter to be displayed in colored box.  
- Add placeholder for unregister extension as Free.
=> Regression: Extension List panel UI not aligned with designs

app/lib/server/startup/settings.ts, app/voip/server/startup.ts, server/sdk/types/IVoipService.ts, server/services/voip/connector/asterisk/CommandHandler.ts, server/services/voip/service.ts
=> Regression: Refresh server connection when MI server settings change

client/lib/isE2EEMessage.ts, client/views/room/MessageList/components/Message.tsx, client/views/room/MessageList/components/MessageIndicators.tsx, client/views/room/MessageList/components/MessageReaction.tsx, client/views/room/MessageList/components/MessageReactionsList.tsx, client/views/room/MessageList/components/MessageReadReceipt.tsx, client/views/room/MessageList/components/MessageRolesList.tsx, client/views/room/MessageList/components/UrlPreview/PreviewList.tsx, client/views/room/MessageList/contexts/MessageListContext.tsx, client/views/room/MessageList/providers/MessageListProvider.tsx, client/views/room/components/BlazeTemplate.tsx
=> [IMPROVE] Message rewrite code structure

app/apps/server/bridges/livechat.ts
In `app/apps/server/bridges/livechat.ts:114`, we converted the user to app interface and the use that user for Rocket.Chat method. Due to the unmatch interface, this cause some troubles.
We should use method `convertToRocketChat` instead
=> [FIX] no id of room closer in livechat-close message

app/api/server/v1/teams.ts, client/views/teams/ConvertToChannelModal/ConvertToChannelModal.tsx, definition/rest/v1/teams/index.ts
- Fix "Match error"  when trying to convert a channel to a team;
1. Create a team and add some rooms to it;
2. Go to **Room Information > Convert to Channel**. No errors should be displayed and the list of rooms should be shown.
=> [FIX] "Match error" when converting a team to a channel

ee/app/license/server/license.internalService.ts, server/sdk/lib/Events.ts
=> Chore: Skip local services changes when shutting down duplicated services

client/lib/voip/VoIPUser.ts, client/sidebar/sections/components/OmnichannelCallToggleReady.tsx, packages/rocketchat-i18n/i18n/en.i18n.json
=> [FIX] Disable voip button when call is in progress

client/views/root/MainLayout/MainLayout.tsx, client/views/root/MainLayout/UsernameCheck.tsx, client/views/root/MainLayout/useCustomScript.ts
=> [FIX] Custom script not being fired

server/services/voip/connector/asterisk/ami/ACDQueue.ts
In ACDQueue.ts, when there is no queue available on asterisk, onQueueSummary never gets executed. It directly calls onQueueSummaryComplete. Because of this, result.queueSummary never got initialised, result is undefined.
This causes getQueueDetails fails as it assumes that there will be a valid queue summary. To fix this, set result.queueSummary to empty array if it does not already exist in onQueueSummaryComplete of ACDQueue.ts
https://app.clickup.com/t/29gujj8
Tests:
To test this, all the queues on asterisk needs to be disabled. 
1. Modify queues.conf,  From sales to Sales_FeaturesAndPricing. You can use multiline comment (;-- and --;)
2. Reload queue module module reload app_queue.so
3. On Rocket.chat Go to Administration -> Call Center -> Extensions. 
4. Verify that all the extensions …
=> [FIX] Error is raised when there's no Asterisk queue available yet

client/views/admin/permissions/NewRolePage.js, client/views/admin/permissions/RoleForm.js, client/views/admin/users/AddUser.js, client/views/admin/users/UserRow.js
=> Regression: Custom roles displaying ID instead of name on some admin screens

app/ui-message/client/message.html, packages/rocketchat-i18n/i18n/en.i18n.json
Added tooltip 'Options' to message menu.
https://user-images.githubusercontent.com/76220055/152799719-7f73a7c6-cf46-4a10-87de-32aad6f32585.mp4
Closes #24430 
Mention in issue
=> [IMPROVE] Added tooltip options for message menu

server/services/nps/sendNpsResults.ts, server/services/nps/service.ts
There were two issues:
- the `findOneAndUpdate` operation was not returning the `_id` , that was being used to update the votes to `sent`, thus votes were never marked as `sent`
- there was a missing `await` to wait updating votes to `sent` before performing the query to make sure all votes were actually sent
=> [FIX] NPS never finishing sending results

client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx, definition/IRoom.ts
`callEndedAt` is not a existing property on `IVoipRoom`
=> [FIX] Use correct room property for call ended at

.github/workflows/build_and_test.yml, .gitignore, apps/meteor/package.json, package.json, turbo.json
=> Regression: Fix CI monorepo build

.github/workflows/build_and_test.yml, apps/meteor/package.json, yarn.lock
=> Regression: CI playwright

.github/workflows/build_and_test.yml
=> Regression: Fix services Docker build on CI

app/models/server/raw/Analytics.ts, app/models/server/raw/Avatars.ts, app/models/server/raw/Banners.ts, app/models/server/raw/BannersDismiss.ts, app/models/server/raw/BaseRaw.ts, app/models/server/raw/CredentialTokens.ts, app/models/server/raw/CustomSounds.ts, app/models/server/raw/CustomUserStatus.ts, app/models/server/raw/EmailInbox.ts, app/models/server/raw/EmailMessageHistory.ts, app/models/server/raw/EmojiCustom.ts, app/models/server/raw/ExportOperations.ts, app/models/server/raw/FederationServers.ts, app/models/server/raw/IntegrationHistory.ts, app/models/server/raw/Integrations.ts, app/models/server/raw/LivechatTrigger.ts, app/models/server/raw/NotificationQueue.ts, app/models/server/raw/Nps.ts, app/models/server/raw/NpsVote.ts, app/models/server/raw/OEmbedCache.ts, app/models/server/raw/PbxEvents.ts, app/models/server/raw/ReadReceipts.ts, app/models/server/raw/ServerEvents.ts, app/models/server/raw/Sessions.ts, app/models/server/raw/Statistics.ts, app/models/server/raw/Team.ts, app/models/server/raw/TeamMember.ts, app/models/server/raw/Uploads.ts, app/models/server/raw/UserDataFiles.ts, app/models/server/raw/WebdavAccounts.ts
Indexes from raw models using the property `indexes` were not being created due to an issue on OOP works in JS.
=> [FIX] Database indexes not being created

apps/meteor/client/views/room/contextualBar/Discussions/withData.js, apps/meteor/client/views/room/contextualBar/ExportMessages/MailExportForm.tsx, apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditChannelWithData.js, apps/meteor/client/views/room/contextualBar/Threads/withData.tsx, apps/meteor/client/views/room/hooks/useUserInfoActions.js, apps/meteor/client/views/room/hooks/useUserRoom.js, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> Chore: Remove duplicated useUserRoom

apps/meteor/client/components/ErrorBoundary.tsx, apps/meteor/client/views/room/MessageList/MessageList.tsx, apps/meteor/client/views/room/MessageList/MessageListErrorBoundary.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Not crash the whole application if something goes wrong in the MessageList component.
=> Chore: Add error boundary to message component

apps/meteor/app/notifications/server/lib/Notifications.ts, apps/meteor/server/modules/notifications/notifications.module.ts
On some recent changes done on #24831 , I thought `streamLocal` was not being used anymore, but it is still required in multi-instance environments, to properly spread broadcast streamer events.
Closes #25163
Closes #25194
=> [FIX] Desktop notification on multi-instance environments

apps/meteor/app/lib/server/functions/saveUser.js
added above mentioned constants to remove magic numbers in a simple manner
closes #24968
=> [IMPROVE] Added MaxNickNameLength and MaxBioLength constants

apps/meteor/app/voip/server/startup.ts, apps/meteor/client/providers/CallProvider/hooks/useVoipClient.ts, apps/meteor/server/modules/listeners/listeners.module.ts, apps/meteor/server/sdk/lib/Events.ts, apps/meteor/server/services/voip/service.ts
Initially it was thought that the issue occurs because of the race condition while changing the client settings vs those settings reflected on server side. So a natural solution to solve this is to wait for setting change event 'private-settings-changed'. Then if 'VoIP_Enabled' is updated and it is true, set voipEnabled  to true in useVoipClient.ts (on client side)
It was realised that the race does not happen because of the database or server noticing the changes late. But because of the time taken to establish the AMI connection with Asterisk.
Solution:
1. Change apps/meteor/app/voip/server/startup.ts. When VoIP_Enabled is changed, await for Voip.init() to complete and then broadcast connector.statuschanged  with changed value.
2. From …
=> [FIX] VoIP disabled/enabled  sequence puts voip agent in error state

apps/meteor/client/views/room/MessageList/components/MessageContent.tsx, apps/meteor/client/views/room/MessageList/components/MessageReadReceipt.tsx, apps/meteor/client/views/room/MessageList/contexts/MessageListContext.tsx, apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
The read receipts were hidden before the user read, but the correct behavior is with gray color.
=> [FIX] Read receipts show with color gray when not read yet

apps/meteor/app/ui-utils/client/lib/openRoom.js
fix avatar not loading on a first direct message
The room avatar component depends on the `Subscription` object to load the avatar URL. But the subscription is updated in an asynchronous way, sometimes when a room is created the `Subscription` was not set yet. Adding a `loadFromServerAndPopulate` function redirect to a room will ensure that the `Subscription` object will be updated before creating a room.
=> Regression: Avatar not loading on first direct message

apps/meteor/app/federation-v2/server/bridge.ts, apps/meteor/app/federation-v2/server/config.ts, apps/meteor/app/federation-v2/server/index.ts, apps/meteor/app/federation-v2/server/matrix-client/user.ts, apps/meteor/app/federation-v2/server/settings.ts, apps/meteor/app/federation-v2/server/startup.ts, apps/meteor/app/federation-v2/server/tools.ts, apps/meteor/package.json, yarn.lock
I was getting this error during startup:
```
@rocket.chat/meteor:dev: W20220422-13:55:13.189(-3)? (STDERR) === UnHandledPromiseRejection ===
@rocket.chat/meteor:dev: W20220422-13:55:13.190(-3)? (STDERR) TypeError: Cannot read property 'includes' of undefined
@rocket.chat/meteor:dev: W20220422-13:55:13.190(-3)? (STDERR)     at app/federation-v2/server/settings.ts:85:17
@rocket.chat/meteor:dev: W20220422-13:55:13.190(-3)? (STDERR)     at /Users/diegosampaio/.meteor/packages/promise/.0.12.0.1uvcsxa.vq0s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
@rocket.chat/meteor:dev: W20220422-13:55:13.190(-3)? (STDERR) ---------------------------------
@rocket.chat/meteor:dev: W20220422-13:55:13.191(-3)? (STDERR) Errors like this can cause oplog …
```
=> Regression: Fix federation Matrix bridge startup

apps/meteor/client/views/admin/customSounds/AdminSoundsRoute.tsx, apps/meteor/client/views/admin/mailer/Mailer.tsx, apps/meteor/client/views/admin/mailer/MailerRoute.tsx, apps/meteor/client/views/room/contextualBar/ExportMessages/MailExportForm.tsx
NOTE: Federation files were left with warnings to avoid creating conflicts with other fixes
=> Chore: Fix return type warnings

apps/meteor/.dockerignore, apps/meteor/.eslintignore, apps/meteor/.gitignore, apps/meteor/package.json
- data and test-failure should be ignored
- ensure scripts use cross-env
=> Chore: ensure scripts use cross-env and ignore some dirs (ROC-54)

apps/meteor/ee/server/services/authorization/service.ts, apps/meteor/ee/server/services/mongo.ts
#25301 added error check for MongoDB connections but only for `authorization` service, this one adds to every service using `getConnection` or `getCollection` .
=> Regression: Better MongoDB connection management for micro services

packages/rest-typings/README.md
=> Chore: Create README.md for Rest Typings

apps/meteor/package.json, yarn.lock
React's `use-subscription` package had a new minor update with breaking changes that caused Rocket.Chat app to stop working.
=> Regression: Rocket.Chat Webapp not loading.

apps/meteor/app/lib/server/startup/rateLimiter.js, apps/meteor/server/lib/logger/logQueue.ts, apps/meteor/server/stream/stdout.ts
=> Chore: Add options to debug stdout and rate limiter

apps/meteor/client/hooks/useFileInput.ts
=> Chore: Convert useFileInput to TS

apps/meteor/app/models/server/raw/BaseRaw.ts, apps/meteor/app/models/server/raw/NpsVote.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v262.ts
=> [FIX] Change NPS Vote identifier + nps index to unique

apps/meteor/app/api/server/api.d.ts, apps/meteor/app/api/server/api.js
=> Chore: Chore add validation option to rest endpoints

apps/meteor/app/lib/server/functions/sendMessage.js, apps/meteor/app/lib/server/functions/updateMessage.ts, apps/meteor/lib/callbacks.ts, apps/meteor/server/hooks/index.ts, apps/meteor/server/hooks/messages/markdownParser.ts, apps/meteor/server/modules/listeners/listeners.module.ts
Moving to a callback will bring the following benefits:
- The main benefit are metrics. We have metrics for each `callback` so this will show much time it takes to parse markdown from a message
- We'll not test on every message sent if the parser is disabled
- Better parser coverage since `beforeSaveMessage` is being called in many other places where we were not parsing markdown before.
=> Chore: Move markdown message parser to a `callback`

apps/meteor/ee/server/lib/ldap/Manager.ts
=> [FIX] LDAP sync removing users from channels when multiple groups are mapped to it

apps/meteor/server/startup/migrations/v262.ts, apps/meteor/server/startup/migrations/v264.ts
=> Chore: Reorder unreleased migrations

apps/meteor/client/views/notFound/NotFoundPage.tsx
=> Chore: Migrate NotFoundPage to TS

apps/meteor/client/views/admin/settings/GroupPageSkeleton.tsx, apps/meteor/client/views/admin/settings/ResetSettingButton.tsx, apps/meteor/client/views/admin/settings/SectionSkeleton.tsx, apps/meteor/client/views/admin/settings/SettingSkeleton.tsx
GroupPageSkeleton, ResetSettingButton, SectionSkeleton, SettingSkeleton to tsx
=> Chore: Convert apps/meteor/client/views/admin/settings

apps/meteor/server/startup/initialData.js
If injecting initial user.  The user wasn’t added to the default General channel
=> [FIX] Initial User not added to default channel

apps/meteor/client/components/Omnichannel/Tags.tsx, apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
This should fix the error `useCurrentChatTags is not a function` when trying to close a livechat conversation
=> [FIX] useCurrentChatTags is not a function

apps/meteor/client/lib/voip/VoIPUser.ts, packages/core-typings/src/voip/VoIPUserConfiguration.ts
Code Improvements for #25391
Also some typo fixes on comments
(Initially they were part of a review, but someone merged the PR before I could post the review)
=> Chore: Code Improvements for #25391

apps/meteor/client/lib/voip/VoIPUser.ts
=> Regression: Change logic to check if connection is online on unstable networks

.yarnrc.yml, apps/meteor/client/views/room/MessageList/components/Message.tsx, apps/meteor/client/views/room/MessageList/components/MessageContent.tsx, apps/meteor/client/views/room/MessageList/components/MessageHeader.tsx, apps/meteor/package.json, yarn.lock
=> [FIX] Fix max-width message block

apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.stories.tsx, apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessages.tsx, apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesDateTimeRow.tsx, apps/meteor/client/views/room/contextualBar/PruneMessages/PruneMessagesWithData.tsx, packages/rest-typings/src/v1/rooms.ts
=> Chore: Prune Messages contextualBar rewrite

apps/meteor/app/statistics/server/lib/SAUMonitor.ts
1. 1 Login with your account
1.1. Check collection rocketchat_sessions and there we found 2 documents related to this session started.
2. Click on logout button
3. Login again
3.1. Check rocketchat_sessions again and there is 1 document related to this session started. 
Why do we need 2 documents?
1st sends the object resume with a username and password
2nd sends the object resume with token only after processed login with success.
*both documents are sent by Meteor.Account
**This token is an important key to filtering all opened sessions.
=> [FIX] Session with loginToken not being saved after login

apps/meteor/app/ui/client/index.ts, apps/meteor/client/startup/routes.tsx
=> [FIX] Homepage import and template

apps/meteor/app/metrics/server/lib/collectMetrics.ts, apps/meteor/definition/externals/meteor/facts-base.d.ts, apps/meteor/definition/externals/meteor/mongo.d.ts, apps/meteor/package.json, yarn.lock
Looks like the update of de dep had breaking changes and now uses promises at some calls. This PR fixes those promise usages and converts the file to TS (hopefully it helps us to spot the error in the future)
=> [FIX] Fix prom-client new promise usage

apps/meteor/app/api/server/v1/misc.ts, apps/meteor/app/apps/client/@types/IOrchestrator.ts, apps/meteor/app/apps/client/orchestrator.ts, apps/meteor/client/lib/meteorCallWrapper.ts, apps/meteor/client/lib/userData.ts, apps/meteor/client/providers/ServerProvider.tsx, apps/meteor/client/views/admin/apps/AppDetailsPage.tsx, apps/meteor/client/views/admin/apps/hooks/useCategories.ts, packages/core-typings/src/IUser.ts, packages/rest-typings/src/apps/index.ts, packages/rest-typings/src/v1/me.ts, packages/rest-typings/src/v1/misc.ts
=> Regression: fix apps path

apps/meteor/app/livechat/client/lib/stream/queueManager.js, apps/meteor/app/livechat/client/views/app/dialog/closeRoom.js, apps/meteor/app/livechat/client/views/app/livechatReadOnly.js, apps/meteor/app/livechat/client/views/app/tabbar/contactChatHistory.js, apps/meteor/app/oauth2-server-config/client/oauth/oauth2-client.js
=> Chore: use params instead of URL building on livechat endpoints

apps/meteor/app/lib/server/functions/deleteUser.ts, apps/meteor/app/livechat/server/api/v1/contact.js, apps/meteor/app/livechat/server/lib/Contacts.js, apps/meteor/app/livechat/server/lib/Livechat.js, apps/meteor/app/models/server/models/LivechatVisitors.js, apps/meteor/app/models/server/raw/LivechatVisitors.ts, apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js, packages/core-typings/src/ILivechatVisitor.ts
=> [FIX] allow only livechat-agents to be contact manager for any omnichannel contact 

apps/meteor/client/views/room/MessageList/components/MessageReaction.tsx, apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
=> [FIX] `You and @yourUsername reacted with`title on reactions

apps/meteor/app/utils/client/lib/RestApiClient.ts, packages/api-client/src/index.ts
=> Regression: TOTP Modal with new rest api package

_templates/package/new/package.json.ejs.t, package.json, packages/api-client/package.json, packages/core-typings/package.json, packages/livechat/package.json, packages/rest-typings/package.json, packages/ui-contexts/package.json, turbo.json
With the current `dev` pipeline, whenever we modify a package (e.g. `api-client`), we have to kill the meteor proccess and run `yarn dev` again in order for the changes to be compiled and the new output to be used by meteor.
This has the drawback of taking a little longer to run the dev environment, since we can't cache a watched buid. In the other hand, it reduces the friction of modifying internal packages since we don't need to rebuild the project for changes to take effect.
This will enable us to move more things to separate packages without affecting the dev experience too much.
=> Chore: Watch for package changes

apps/meteor/app/models/server/raw/Users.js, apps/meteor/server/services/team/service.ts, apps/meteor/tests/end-to-end/api/25-teams.js
=> [NEW] Create Team with a member list of usernames

apps/meteor/client/sidebar/RoomMenu.tsx
=> Chore: Convert RoomMenu

apps/meteor/client/components/voip/modal/WrapUpCallModal.tsx, apps/meteor/client/providers/CallProvider/CallProvider.tsx, apps/meteor/client/providers/MeteorProvider.tsx
This PR revises the usage of the modal inside the call provider, by moving the modal provider a little bit up the three.
=> Chore: Remove Imperative Modal from context 

apps/meteor/client/views/home/DefaultHomePage.tsx, apps/meteor/client/views/home/HomepageGridItem.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
- Add workspace title based on setting
=> [NEW] Homepage workspace name

packages/rest-typings/src/v1/chat.ts
=> Regression: Set `offset` and `count` optional on `ChatGetThreadsListSchema`

apps/meteor/app/api/server/v1/voip/omnichannel.ts, apps/meteor/client/views/admin/settings/groups/voip/RemoveAgentButton.tsx, packages/rest-typings/src/v1/voip.ts
I've noted that our extensions api was not using the same pattern that we use for a lot of `GET`s and `DELETE`s.
This will fix an issue when trying to remove an agent from a voip extension.
=> [BREAK] use urlParams on omnichannel/agent/extension/

apps/meteor/client/providers/RouterProvider.tsx
When `Tracker.autorun()` calls are nested, it's possible that an invalidation at the parent render the children non-reactive due to synchronous calls. To avoid that under the callback given by `useSyncExternalStore`, we schedule an `onStoreChange` callback call to not make it reside at the same backtrace.
=> Regression: Non-reactive routes

apps/meteor/client/hooks/useEndpointAction.ts, apps/meteor/client/views/account/security/TwoFactorEmail.js, apps/meteor/client/views/admin/integrations/edit/EditIncomingWebhook.js, apps/meteor/client/views/admin/integrations/edit/EditOutgoingWebhook.js, apps/meteor/client/views/admin/integrations/new/NewIncomingWebhook.js, apps/meteor/client/views/admin/integrations/new/NewOutgoingWebhook.js
While creating an webhook integration, it was missing the **v1/**. Also, the toast was not properly displaying error messages
Try creating an Integration Webhook in Admin > Integrations. 
The payload will be sent to: http://localhost:3000/api/integrations.create
Edit a user, and set it's email the same email as an existing user: the toast message will not display the correct message
=> Regression: Webhook Integration Creation + string error toast msg

apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.js, apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts, apps/meteor/ee/app/livechat-enterprise/server/api/tags.js, apps/meteor/ee/server/models/raw/LivechatTag.ts, apps/meteor/server/services/omnichannel-voip/service.ts, packages/model-typings/src/models/ILivechatTagModel.ts
=> Regression: Fix voip call wrap-up model not working

apps/meteor/app/api/server/v1/users.ts
=> [FIX] Error "numRequestsAllowed" property in rateLimiter for REST API endpoint when upgrading

.kodiak.toml
=> Chore: Make kodiak merge message empty

apps/meteor/app/lib/server/functions/createDirectRoom.ts, yarn.lock
This pull request removes the duplicated property `_USERNAMES` from `apps/meteor/app/lib/server/functions/createDirectRoom.ts`, using only the existing property `roomInfo.usernames`.
=> [FIX] Remove duplicated property _USERNAMES from createDirectRoom.ts

apps/meteor/app/livechat/server/roomAccessValidator.internalService.ts, apps/meteor/server/sdk/types/IAuthorization.ts, apps/meteor/server/sdk/types/IAuthorizationLivechat.ts, apps/meteor/server/services/authorization/canAccessRoom.ts
=> Chore: Room access validation may be called without user information

apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
Fixes https://github.com/RocketChat/Rocket.Chat/issues/25954
=> [FIX] Unable to close chats when comments is disabled

apps/meteor/client/sidebar/footer/SidebarFooterWatermark.tsx
Changed the name of useQuery hook to prevent conflict of queries with same name.
1. Admin using an Enterprise server
2. Open the Admin Settings
3. Close the Admin Settings
4. Community Watermark start to appear
=> Regression: Changing isEnterprise useQuery name to prevent conflict of queries

apps/meteor/client/lib/userData.ts
=> Regression: Users on new sessions are forced to re-configure 2fa

apps/meteor/app/apps/server/communication/uikit.ts
We get the following error when clicking on the close button on modals created via apps
This happens because the `api-client` package only accepts [JSON as a response](https://github.com/RocketChat/Rocket.Chat/blob/b09a0385461023d25bba27e482c04f6563cc984d/packages/api-client/src/index.ts#L144) however right now it is getting a non-JSON response hence its not able to parse it and thus resulting in this error
=> Regression: Close button on modals created via apps not working

apps/meteor/client/providers/CallProvider/CallProvider.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> Regression: Add better error messages when call fails

apps/meteor/client/components/Card/Col.tsx, apps/meteor/client/views/admin/info/FederationCard/FederationCard.tsx, apps/meteor/client/views/admin/info/InformationPage.tsx
=> Chore: Info page

apps/meteor/client/views/admin/apps/AppDetails.tsx
Fixed two styling problems on the AppDetails markdown. The first one was a misuse of flex and the second was the fact that the withRichContent flag was missing on the box that received the markdown.
Demo images:
Before:
After:
Clickup task: https://app.clickup.com/t/2rwq0q7
=> Regression: Fix rendered markdown styling on app info page details section

apps/meteor/app/importer/server/startup/setImportsToInvalid.js, apps/meteor/app/livechat/server/lib/QueueManager.js, apps/meteor/app/models/server/models/LivechatDepartmentAgents.js, apps/meteor/app/models/server/models/LivechatRooms.js, apps/meteor/app/models/server/models/Settings.js, apps/meteor/app/models/server/models/Users.js, apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js, apps/meteor/server/methods/browseChannels.js, apps/meteor/server/models/raw/LivechatRooms.js, apps/meteor/server/models/raw/Users.js, apps/meteor/server/services/banner/service.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
Fixed things:
- Omnichannel Directory
- Omnichannel Current Chats
- Auto Selection Algo
- Load Balance Algo
- Manual Selection Algo
- Livechat New Conversations
Other fixed things:
- Warning on fields deprecation
- Warning on "remove" deprecation
- Remove findAndModify usage
=> Regression: Fix Omnichannel not working after meteor update

apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx, apps/meteor/client/providers/DeviceProvider/lib/isSetSinkIdAvailable.tsx, apps/meteor/client/providers/MeteorProvider.tsx, apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
This PR disables device changes in browsers that not support the `setSinkId` method, and therefore does not support device changes directly from the browser
I've decided to test if the `setSinkId` is available instead of listing browsers that supported or not, this way if a browser starts/stops supporting it, we don't have to do anything, and there is also firefox, where you can enable it as an optional feature.
=> Regression: Unavailable devices in unsupported browsers

apps/meteor/app/authorization/server/functions/upsertPermissions.ts, apps/meteor/ee/app/authorization/server/resetEnterprisePermissions.ts
This was happening on startup for EE or whenever a new license was applied, causing all permissions to be updated without changing anything. The fix was to add to the query the value being pulled, so only affected permissions will be updated, which should be none most of the times.
=> Chore: Avoid unneeded permission updates when EE license is applied

apps/meteor/ee/client/views/admin/engagementDashboard/channels/useChannelsList.ts, apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessageOrigins.ts, apps/meteor/ee/client/views/admin/engagementDashboard/messages/useMessagesSent.ts, apps/meteor/ee/client/views/admin/engagementDashboard/messages/useTopFivePopularChannels.ts, apps/meteor/ee/client/views/admin/engagementDashboard/users/useActiveUsers.ts, apps/meteor/ee/client/views/admin/engagementDashboard/users/useHourlyChatActivity.ts, apps/meteor/ee/client/views/admin/engagementDashboard/users/useNewUsers.ts, apps/meteor/ee/client/views/admin/engagementDashboard/users/useUsersByTimeOfTheDay.ts, apps/meteor/ee/client/views/admin/engagementDashboard/users/useWeeklyChatActivity.ts, apps/meteor/ee/definition/rest/v1/engagementDashboard.ts
Parameters for GET requests are *not* serialized as for other methods, therefore sending `Date` objects is not viable due to  the way `Date.prototype.toString` works. This PR uses `Date.prototype.toISOString` explicitly to serialize dates.
=> Regression: REST API calls at Engagement Dashboard

apps/meteor/app/api/server/v1/im.ts, apps/meteor/server/lib/findUsersOfRoom.ts, apps/meteor/server/methods/browseChannels.js, apps/meteor/tests/end-to-end/api/02-channels.js
=> Regression: Search on Member List

apps/meteor/ee/app/canned-responses/server/hooks/onMessageSentParsePlaceholder.ts
Canned responses placeholders were not being replaced properly after we changed to the new md parser. 
This fix changes the priority so that the canned responses replace logic runs before the parser, thus bringing back this functionality.
Before:
After:
=> Regression: Adjusted priority to run canned responses replace before new parser

apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
=> Regression: Clear user selection filter after selecting desired user.

apps/meteor/app/lib/server/functions/getFullUserData.ts
=> Regression: Fix get myself user data

apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.js, apps/meteor/server/email/IMAPInterceptor.ts, apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts
If an omnichannel chat is placed on hold & it receives a new message from the guest then the system should automatically resume this chat from on hold. However, for the email channel, the chat wasn't getting resumed automatically, which should be fixed by this PR
=> [FIX] Onhold auto chat resume feature not working for email channel

apps/meteor/package.json, apps/meteor/tsconfig.typecheck.json
On local, this run under 2G of ram, which was a surprise, but on pipe, it needs 4G at least
=> Chore: Exclude private/public folders from typecheck

apps/meteor/client/views/admin/apps/AppRow.tsx, apps/meteor/client/views/admin/apps/AppStatus.js
Fixed a problem where the AppStatus component would show a unwanted margin when an app was installed and had an update.
Before:
After:
=> Regression: Fix spacing problem on AppStatus component

apps/meteor/app/api/server/v1/im.ts, apps/meteor/tests/end-to-end/api/04-direct-message.js, packages/rest-typings/src/v1/dm/im.ts
=> [FIX] Empty results on `im.list` endpoint

apps/meteor/tests/end-to-end/api/00-miscellaneous.js
=> Chore: Add end-to-end tests to teams listing in the `directory` endpoint

apps/meteor/client/providers/CallProvider/CallProvider.tsx
In theory terminated requests should not throw an error since usually request terminated is a response to a `CANCEL` request.
=> [FIX] Don't give errors on outbound voip call Request Terminated

apps/meteor/playwright.config.ts, apps/meteor/tests/e2e/administration.spec.ts, apps/meteor/tests/e2e/file-upload.spec.ts
=> Chore: Tests intermitences

apps/meteor/client/providers/DeviceProvider/DeviceProvider.tsx, apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json, packages/ui-contexts/src/DeviceContext.ts, packages/ui-contexts/src/hooks/useAvailableDevices.ts, packages/ui-contexts/src/hooks/useDeviceConstraints.ts, packages/ui-contexts/src/hooks/useIsDeviceManagementEnabled.ts, packages/ui-contexts/src/hooks/useSelectedDevices.ts, packages/ui-contexts/src/hooks/useSetInputMediaDevice.ts, packages/ui-contexts/src/hooks/useSetOutputMediaDevice.ts, packages/ui-contexts/src/index.ts
=> [FIX] Undefined MediaDevices error on HTTP

apps/meteor/server/models/raw/PushToken.ts, apps/meteor/server/services/meteor/service.ts, apps/meteor/server/services/push/service.ts, apps/meteor/tests/end-to-end/api/01-users.js, packages/model-typings/src/models/IPushTokenModel.ts
=> [FIX] Clear push token on save user password

apps/meteor/app/api/server/v1/users.ts, apps/meteor/tests/end-to-end/api/01-users.js
Requests `status` and/or `message` fields on `/v1/users.setStatus` request payload.
The successful response of `/v1/users.setStatus` without any of the supported payload fields sent appears to be misleading, as it can be seen at #19001.
=> [FIX] Request at least one field in the payload of `/v1/users.setStatus`

apps/meteor/tests/e2e/channel-management.spec.ts, apps/meteor/tests/e2e/emojis.spec.ts, apps/meteor/tests/e2e/file-upload.spec.ts, apps/meteor/tests/e2e/message-actions.spec.ts, apps/meteor/tests/e2e/messaging.spec.ts, apps/meteor/tests/e2e/permissions.spec.ts, apps/meteor/tests/e2e/utils/create-target-channel.ts, apps/meteor/tests/e2e/utils/test.ts
- create a api fixture
- update create-target-channel and tests to use api fixture
=> Chore: Refactor create-target-channel util

apps/meteor/client/views/admin/apps/AppInstallPage.js, apps/meteor/client/views/admin/apps/AppPermissionsReviewModal.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> Chore: Migrate AppPermissionsReviewModal from JS to TS

apps/meteor/app/theme/client/imports/general/variables.css, apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts, apps/meteor/client/views/setupWizard/SetupWizardRoute.tsx, apps/meteor/package.json, yarn.lock
=> Chore: update fuselage rounded edition 

apps/meteor/client/views/teams/CreateTeamModal/useCreateTeamModalState.ts
=> Regression: Team name validation failing always.

.github/workflows/build_and_test.yml
This issue was caused by #25556 and since then Docker image for micro services are not being published with the correct tag. That means all 5.0.x releases don't have a published Docker image with the version tag.
The main was using `$IMAGE_TAG` instead of `$DOCKER_TAG` to publish the correct tag to DockerHub. I've changed the workflow do make the services publish to look similar to official one. Ideally they could be in a new action file.
=> Chore: Fix services image publish do DockerHub

apps/meteor/app/ui-utils/client/lib/RoomManager.ts, apps/meteor/app/ui-utils/client/lib/openRoom.tsx, apps/meteor/client/startup/banners.ts
=> Regression: Banner - Room not found - Omnichannel room

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx, apps/meteor/client/views/omnichannel/currentChats/CustomFieldsVerticalBar.tsx, apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx
This fixes:
Reset button:
- Write anything on the current chat's filters
- Go to the `...` menu
- Select Clear Filters
Sorting
- Click on any table headers
=> Regression: Fix Current Chats Page Issues

apps/meteor/app/livechat/server/lib/Livechat.js, apps/meteor/app/livechat/server/methods/saveInfo.js
=> Regression: Custom fields not being saved for room

apps/meteor/package.json, yarn.lock
=> Chore: Update Apps-Engine

apps/meteor/client/hooks/useReactiveValue.ts, apps/meteor/client/providers/CallProvider/CallProvider.tsx
This PR adds a check to the `createRoom` method, responsible for creating VoIP rooms. It checks whether the visitor already exists before creating a new one, if one is found it uses it instead of overwriting existing visitors.
=> Regression: Visitor being overwritten on call end

apps/meteor/app/ui/client/views/app/lib/roomHelpers.ts
Fixed `messagesHistory` function, it was filtering messages only with existing threads.
https://github.com/RocketChat/Rocket.Chat/issues/26801
Switch My Preferences > Global > Use legacy message template
=> [FIX] Fix broken legacy message view

apps/meteor/app/apple/lib/handleIdentityToken.ts, apps/meteor/app/apple/server/AppleCustomOAuth.ts, apps/meteor/app/apple/server/appleOauthRegisterService.ts, apps/meteor/app/apple/server/index.ts, apps/meteor/app/apple/server/loginHandler.ts, apps/meteor/definition/externals/meteor/accounts-base.d.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Our mobile app uses a different method to log in that was removed at #24879 .
You can also make it available only on mobile:
Removes the "Sign in with Apple" text from the log in button. This was something we thought were required by Apple, but it is actually allowed to have just the logo as all others OAuth we have. Source: https://developer.apple.com/design/human-interface-guidelines/technologies/sign-in-with-apple/buttons/#creating-a-custom-sign-in-with-apple-button
=> [FIX] Sign in with Apple on mobile

apps/meteor/client/views/modal/ModalRegion.tsx, apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx, apps/meteor/package.json, yarn.lock
- Prevents users from opening modals and get focused on other areas
- Tells screen readers to ignore other areas that are not part of the form
=> Chore: add aria hidden if modal is open

apps/meteor/app/ui-cached-collection/client/models/CachedCollection.js
The CachedCollection Class was assuming that the passed parameter would be modified, instead of using the callback return.
=> Regression: Sidebar Room List not working properly.

apps/meteor/client/components/Sidebar/SidebarNavigationItem.tsx, yarn.lock
Fix the behavior of the admin sidebar, it didn't activate its options properly on pages that had sub-routes.
Demo gif:
=> [FIX] Admin sidebar navigation

apps/meteor/app/lib/server/functions/updateMessage.ts
An empty `$unset` object was being used and causes exceptions in some mongo versions.
=> Regression: Cannot edit messages in some environments.

apps/meteor/app/livechat/server/lib/Helper.js, apps/meteor/app/models/server/models/LivechatInquiry.ts, apps/meteor/client/providers/OmnichannelProvider.tsx, apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.js, apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js, apps/meteor/ee/app/models/server/models/LivechatInquiry.js, apps/meteor/server/models/raw/LivechatInquiry.ts, packages/core-typings/src/IInquiry.ts
=> [BREAK] Deprecate `queueOrder` property from routing/sorting

apps/meteor/app/ui/client/views/app/photoswipeContent.ts, apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedCollapsible.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedHtmlPreview.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedImagePreview.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedLinkPreview.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/OEmbedPreviewContent.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/UrlImagePreview.tsx, apps/meteor/client/views/room/MessageList/components/UrlPreview/UrlPreview.tsx, apps/meteor/client/views/room/MessageList/lib/isValidLink.ts, apps/meteor/client/views/room/contexts/MessageContext.ts, apps/meteor/client/views/room/providers/MessageProvider.tsx, apps/meteor/tests/unit/client/views/room/MessageList/lib/buildImageURL.spec.ts, apps/meteor/tests/unit/client/views/room/MessageList/lib/isValidLink.spec.ts, packages/fuselage-ui-kit/src/blocks/PreviewBlock.tsx, yarn.lock
- Add message generic cover image preview component to OEmbed Links
- Add new functionalities to URL Image preview, like click to open preview and arrows to move between images in the current chat
- Design changes to keep the original aspect ratio of the image to prevent loss of important image pieces of information 
- Add fallback to common issues related to meta tags like `og:image` and others
closes https://github.com/RocketChat/Rocket.Chat/issues/26838
TC-29 TC-95
Send links with previews to see the behavior of the messages.
**Image URL preview:**
**Current Behavior**
Images being cropped and not able to click to preview
**Expected Behavior**
Images with the original aspect ratio without cropping anything and it can be clicked to preview the image
--
**URL preview:**
**Current …
=> Chore: Update Image and link previews

apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
Message headers do not follow the UI_Use_Real_Name setting when on mobile (<768px width), therefore only usernames are shown on mobile.
Removed the mobile requirement for allowing real names to be used in message headers.
Fixes #26967
1. Set server setting `Use Real Name` to `Enabled`
2. Use a browser with a width <768px
3. All message headers will now use the username
=> [FIX]  Removed mobile requirement for showing real name

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/release.md
fixed 2 small grammatical errors
=> Chore: docs grammar fix

packages/livechat/package.json, packages/livechat/tsconfig.json, packages/livechat/tsconfig.typecheck.json, packages/livechat/webpack.config.js, yarn.lock
We were having issues using jsx files on the livechat package, due the way we are using preact + storybook.
This should fix the issue with the jsx files and allow us to proceed with the conversion of livechat to Typescript
=> Chore: Improve configurations related to Typescript in Livechat

apps/meteor/app/slashcommand-asciiarts/lib/shrug.ts, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, packages/core-typings/package.json, packages/gazzodown/package.json, packages/rest-typings/package.json, yarn.lock
Previously the escape character `\` was escaping everything.
To avoid unexpected text formatting errors it was restricted to only escape curtains chars like: * _ ~ ` # . 
Doing so the Shrug had to change in the code to display the correct ASCII Art
closes https://github.com/RocketChat/Rocket.Chat/issues/26907
closes https://github.com/RocketChat/Rocket.Chat/issues/26800
1. Create a message using `/shrug`.
The kaomoji being rendered looks as follows: ` ¯\_(ツ)_/¯ `
The kaomoji is missing an arm: ` ¯_(ツ)_/¯ `
The Shrug issue will be fixed after this Pull Request and https://github.com/RocketChat/fuselage/pull/899 are released
TC-99
=> [FIX] Shrug missing backslash character

apps/meteor/app/apps/server/communication/rest.js, apps/meteor/app/cloud/server/functions/getUserCloudAccessToken.ts, apps/meteor/app/cloud/server/functions/retrieveRegistrationStatus.ts, apps/meteor/client/lib/userData.ts, packages/core-typings/src/IUser.ts
The main change of this PR is to consider a workspace registered only if it has both `Cloud_Workspace_Client_Id` and `Cloud_Workspace_Client_Secret` settings saved on the server's cache [here](https://github.com/RocketChat/Rocket.Chat/pull/27229/files#diff-af33d520e198acd8dde76a05e8cb811179e281752df4d130c712d68dd1fb41ccR14).
The problem was it was checking only for `Cloud_Workspace_Client_Id` but was also using the secret to perform requests afterwards, and due to some race conditions on how settings are saved in cache, it was happening some times the `clientId` was in cache but the secret was not, so now with this additional check it will prevent those cases.
The other changes are due to TS conversion.
ARCH-84
=> Chore: Check for Cloud client secret to check if workspace is registered

apps/meteor/client/lib/lists/RecordList.ts
Sort items in the Files sidebar in *reverse* chronological order (newest at top, oldest at bottom), as it did _before_ RC v3.11.0.  
Fixes #27185
See Issue
RecordList is a generic widget for use in several parts of the codebase.  It remains to be seen whether Date DESC is the correct sort order for all of them, although it does seem reasonable that it ought to be.
=> [FIX] Sort RecordList items in REVERSE chronological order, not FORWARD

apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx
[27172](https://github.com/RocketChat/Rocket.Chat/issues/27172)
Open any chat or channel in Safari it will return a gray screen.
The look behind assertion is not compatible with safari, the only solution is to avoid it. So I just replace the regex for one compatible with safari.
We already have unit tests for this function.
=> [FIX] Replace regex not compatible with safari

apps/meteor/app/livechat/imports/server/rest/visitors.ts, apps/meteor/server/models/raw/Messages.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, packages/model-typings/src/models/IMessagesModel.ts, packages/rest-typings/src/v1/omnichannel.ts
=> [IMPROVE] Add searchTerm support for livechat/rid/messages API

apps/meteor/app/ui-message/client/messageBox/messageBox.ts, apps/meteor/app/ui-message/client/messageBox/messageBoxAutogrow.ts, apps/meteor/app/ui-utils/client/lib/readMessages.ts
It fixes some problems introduced/exposed after refactoring the `ChatMessages` API.
=> Regression: message box issues

_templates/service/new/.eslintrc.json.ejs.t, _templates/service/new/package.json.ejs.t, _templates/service/new/service.ejs.t, _templates/service/new/servicesClass.ejs.t, _templates/service/new/tsconfig.json.ejs.t
=> Chore: Create service template

apps/meteor/client/components/GenericModal.tsx, apps/meteor/client/components/TwoFactorModal/TwoFactorEmailModal.tsx, apps/meteor/client/components/TwoFactorModal/TwoFactorPasswordModal.tsx, apps/meteor/client/components/TwoFactorModal/TwoFactorTotpModal.tsx
=> Chore: TwoFactorPass Modals icon misalignment

apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
=> Regression: Add tshow to composer params

apps/meteor/server/sdk/types/IQueueWorkerService.ts, ee/apps/queue-worker/package.json, ee/apps/queue-worker/src/QueueWorker.ts, ee/apps/queue-worker/src/externals/mongo-message-queue.d.ts, ee/apps/queue-worker/src/service.ts, ee/apps/queue-worker/tsconfig.json
=> [NEW] Implement Queue service

apps/meteor/server/models/raw/Uploads.ts, apps/meteor/tests/data/uploads.helper.ts, apps/meteor/tests/end-to-end/api/02-channels.js, apps/meteor/tests/end-to-end/api/03-groups.js, apps/meteor/tests/end-to-end/api/04-direct-message.js
It's now also performing all tests that were previously only running for `channels.files` endpoint to `groups.files` and `im.files` as well.
I've changed the index to better support the queries, I'm will create another PR to delete the old indexes.
=> [FIX] `*.files` endpoints returning hidden files

apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx
It also replace `useEndpointData` in favor of `useQuery`
=> Chore: Custom emoji empty state

apps/meteor/client/views/room/contextualBar/Threads/hooks/useGoToThreadList.ts
=> Regression: Fix go to ThreadList hook

apps/meteor/client/views/room/components/body/RoomBody.tsx, apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx
It hotfixes two issues:
1. user card not opening on clicking in user mentions;
2. slash commands inside threads sending results to the main room.
=> Regression: Broken room and message composer events

apps/meteor/client/views/room/components/body/RoomBody.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/tests/e2e/message-actions.spec.ts
=> Regression: fix close flextab on click outside the container

apps/meteor/tests/end-to-end/api/05-chat.js
=> Chore: Do not rely on external service on tests

apps/meteor/client/views/room/providers/RoomProvider.tsx
Whenever something changed the room subscription, it would trigger a re-subscription to `notify-room/user-activity`.
=> [FIX] Reduce re-subscription on `notify-room/user-activity` stream event

packages/livechat/src/routes/ChatFinished/component.js
Clear chat listeners when the conversation is closed.
=> [FIX] Hide generated PDF on Livechat upon chat close 

apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts, apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts
This one should get rid of "grey" (temporary) messages.
=> Regression: upserting data into cached collections

apps/meteor/client/sidebar/header/UserDropdown.tsx, apps/meteor/client/sidebar/sections/StatusDisabledSection.tsx, apps/meteor/client/views/admin/customUserStatus/CustomUserStatusService.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
- Add Service cap contextualBar for Enterprise
- Differ Modal text for non admin users
- Add external links
=> Chore: Service cap

apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/ActionsToolbarDropdown.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/AudioMessageAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/CreateDiscussionAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/ShareLocationAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/WebdavAction.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/index.ts, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/FormattingToolbarDropdown.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/MessageBoxFormattingToolbar.tsx, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxFormattingToolbar/index.ts
[DSA-19]
[DSA-19]: https://rocketchat.atlassian.net/browse/DSA-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Refactor Composer Collapsed Formatters and Actions

apps/meteor/client/views/room/components/body/composer/hooks/useMessageComposerMergedRefs.ts, apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
unfortunately useMergedRefs use a stable as dependency and if the functions are invalidated it doesn't do anything about it. In this particular case, it is important that the invalidations happen, so I created a special hook for this use.
=> Regression: Fix missing Formatting items

apps/meteor/tests/e2e/config/global-setup.ts
=> Chore: improve global setup e2e

apps/meteor/client/components/GenericTable/V2/GenericTable.tsx, apps/meteor/client/views/omnichannel/departments/ArchivedDepartmentsPageWithData.tsx, apps/meteor/client/views/omnichannel/departments/DepartmentsPageWithData.tsx, apps/meteor/client/views/omnichannel/departments/DepartmentsTable.tsx, apps/meteor/tests/e2e/omnichannel-departaments.spec.ts, packages/rest-typings/src/v1/omnichannel.ts
=> Chore: fix e2e Omnichannel tests

ee/apps/ddp-streamer/src/Streamer.ts
The old code was causing wrong counts on metrics of connected users while also keeping the "subscription" alive, keeping it on the `subscription` `Set`, causing this code to be executed on every message.
=> Regression: Gracefully stop DDP Streamer publication and close WS

apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v292.ts
Previously merged migration files ended up in a faulty migration
=> Regression: Re-add app signature migration to fix the faulty previous one

apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx, apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts, apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopupQueries.ts
=> Regression: Fix slash command with preview

apps/meteor/tests/e2e/omnichannel-auto-onhold-chat-closing.spec.ts, apps/meteor/tests/e2e/omnichannel-auto-transfer-unanswered-chat.spec.ts, apps/meteor/tests/e2e/omnichannel-changing-room-priority-and-sla.spec.ts, apps/meteor/tests/e2e/omnichannel-close-chat.spec.ts, apps/meteor/tests/e2e/omnichannel-send-transcript.spec.ts, apps/meteor/tests/e2e/omnichannel-takeChat.spec.ts, apps/meteor/tests/e2e/omnichannel-transfer-to-another-agents.spec.ts
=> Chore: e2e omnichannel tests - Close every opened page after the test

apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts
=> Regression: Client is not loading new settings from server

apps/meteor/client/views/marketplace/AppsProvider.tsx
Fixed a bug in which the AppsProvider would not handle the marketplace, installed, and private apps lists correctly when running the install, update, and delete listeners. This also solved related bugs of app duplication during installation and loss of reactivity during uninstalls and status changes(private apps only).
Demo gif: ![apps-provider-behavior](https://user-images.githubusercontent.com/43561537/222833328-1d9836c0-738c-41d5-ac17-a5d86452ea83.gif)
[MKP-272]: https://rocketchat.atlassian.net/browse/MKP-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Regression: Apps provider not handling apps lists correctly

apps/meteor/client/views/marketplace/AppMenu.js
Grandfathered apps will not follow the new enabling flow and it should always be possible to enable them
MKP-273
=> Regression: Disabled grandfathered apps must have the option to be enabled

apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx
User is not able to create a custom status from the admin section. Workspace > User Status > New
The SAVE button is not performing any action
1. Open the client as an ADMIN
2. Go to WORKSPACE > USER STATUS
3. Click on New button
4. Try to add a new custom status
TC-519
=> Regression: Creating Custom status 

apps/meteor/app/oauth2-server-config/server/admin/functions/addOAuthApp.ts
- Fix OAuthApps added to the database with a empty string `_id` field.
Introduced in #28085
Go to Workspace > OAuthApps > New Application. Adding a first application works, but its added in the database with a empty string `_id` field. No other OAuthApp can be added later since RC throws a "duplicated key" error (it attempts to insert all OAuthApps with a empty string idd)
TC-517
=> Regression: OAuthApps are added with empty string `_id` field

apps/meteor/server/services/apps-engine/service.ts
This is affecting monolith deployments. Events are being broadcasted from [listeners.module.ts](https://github.com/RocketChat/Rocket.Chat/blob/14e8569c834823beddf4b476f5d7b618c563c134/apps/meteor/server/modules/listeners/listeners.module.ts#L386) already, the code removed was actually "duplicated".
=> Regression: Remove duplicated broadcast App events

apps/meteor/app/apps/server/bridges/rooms.ts
Currently only the room is removed when we delete the room by Apps.
After this PR, we will remove all of the related data of the room when removing it by Apps Engine
=> [FIX] room data is not erased after deleting rooms by app

apps/meteor/app/api/server/v1/assets.ts, apps/meteor/app/api/server/v1/autotranslate.ts, apps/meteor/app/api/server/v1/channels.ts, apps/meteor/app/api/server/v1/chat.ts, apps/meteor/app/api/server/v1/commands.ts, apps/meteor/app/api/server/v1/custom-user-status.ts, apps/meteor/app/api/server/v1/e2e.ts, apps/meteor/app/api/server/v1/emoji-custom.ts, apps/meteor/app/api/server/v1/groups.ts, apps/meteor/app/api/server/v1/im.ts, apps/meteor/app/api/server/v1/integrations.ts
ARCH-568
ARCH-569
ARCH-571
ARCH-572
ARCH-573
ARCH-574
ARCH-575
ARCH-576
ARCH-577
ARCH-578
ARCH-579
=> refactor: Remove `Meteor.call` in favor of `Meteor.callAsync` - 1

apps/meteor/definition/externals/meteor/meteor.d.ts
=> chore: Add types for `Meteor.userAsync`

apps/meteor/client/views/home/cards/CustomContentCard.tsx
- The default text (if there is no content or the admin just adds text without style) color in the homepage custom content block was blue (due to `color="info"`), but should actually be black
Before:
After:
=> fix: change default text color in homepage custom content block

.github/workflows/ci.yml
Due to a change in Variable Setup action, external contributors PR fails because the branch reference is not found, revert will make to use the default branch as reference
=> ci: revert Variable Setup changes

apps/meteor/app/2fa/server/code/EmailCheck.ts, apps/meteor/app/2fa/server/functions/resetTOTP.ts, apps/meteor/app/authentication/server/startup/index.js, apps/meteor/app/integrations/server/lib/triggerHandler.js, apps/meteor/app/invites/server/functions/sendInvitationEmail.ts, apps/meteor/app/lib/server/functions/saveUser.js, apps/meteor/app/lib/server/functions/setEmail.ts, apps/meteor/app/lib/server/methods/sendSMTPTestEmail.ts, apps/meteor/app/livechat/server/lib/Livechat.js, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/mail-messages/server/functions/sendMail.ts, apps/meteor/app/mailer/server/api.ts, apps/meteor/app/notification-queue/server/NotificationQueue.ts, apps/meteor/app/slackbridge/server/SlackAdapter.js, apps/meteor/ee/server/lib/deviceManagement/session.ts, apps/meteor/server/lib/dataExport/processDataDownloads.ts, apps/meteor/server/lib/dataExport/sendEmail.ts, apps/meteor/server/lib/dataExport/sendFile.ts, apps/meteor/server/lib/dataExport/sendViaEmail.ts, apps/meteor/server/lib/resetUserE2EKey.ts
=> refactor: Remove more promise awaits

apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.js
=> regression: `fetch` call in `getWorkspaceAccessTokenWithScope`

apps/meteor/app/apps/server/bridges/users.ts
Fixing a bug in the app bridge where the user prop was not being considered on the user reactive change regarding the user status. 
The app bridge was not correctly handling changes to the user status when the user prop was updated. This led to inconsistencies in the app's UI, where the user status would not be properly reflected in certain cases.
To fix this issue, I updated the app bridge to properly consider changes to the user prop when handling user status changes. This ensures that the app's UI accurately reflects the user's current status at all times.
Basically, you only need to create a simple app that changes the user status and status text by any trigger. Now the user status will change instantly.
=> fix: Fixing the user status change by app

apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx
When a user typed "heart" wrapped in ":" the Emoji Suggestion Popup did not suggest :heart: . This was because the emoji list is sliced to show only 10 emojis in ComposerPopupProvider (apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx).
After:
[heart.webm](https://user-images.githubusercontent.com/79307894/232035111-9d920620-d22f-4e9b-8221-8127322c727a.webm)
Closes #28842 
I added scores based on exact/partial matches and used that for sorting the list of emojis
If emoji is in "recents" it will get a higher priority (i.e. top of the list)
[with_frequently_use.webm](https://user-images.githubusercontent.com/79307894/232035593-a2c7dc51-7106-4f79-ba1a-d97b25e17f8a.webm)
But if there is an exact match available it will get higher priority than the emoji in "recents", so that …
=> fix: missing suggestions from list of suggested emojis in Emoji Popup

apps/meteor/app/api/server/v1/moderation.ts
=> regression: Escape regex for moderation dashboard filters

apps/meteor/ee/app/livechat-enterprise/server/lib/query.helper.js
OC-939
Notes: 
The ideal solution is to move that query override logic outside of the models, like we do for departments. This way, we would be able to remove the `Promise.await` on this PR
=> regression: Fix monitor validation logic for rooms & departments

apps/meteor/app/apps/server/bridges/activation.ts, apps/meteor/ee/server/apps/communication/rest.js, apps/meteor/ee/server/apps/communication/websockets.ts, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, apps/meteor/server/services/apps-engine/service.ts, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
App status inconsistencies between multiple instances in a cluster boil down to the fact that the Apps-Engine is currently responsible for orchestrating when these events are triggered and is overly verbose in doing so.
Upon analysis, the framework itself _should not_ have the concept of "other instances" - this is a deployment detail of the host system, and as such should be controlled by the host. The correct solution for this problem is to review this notification system, potentially removing it from the framework and leaving the responsibility solely for Rocket.Chat.
However, this is hindering the current app management experience for workspaces, so this PR cuts the control of some notifications that come from the framework (the more problematic ones) and moves the control over to RC …
=> [FIX] app status inconsistencies when running multiple instances in a cluster

apps/meteor/server/database/DatabaseWatcher.ts
[SUP-23]
I flagged as a breaking change since now it will halt the process after 5 retries.
ARCH-1093
[SUP-23]: https://rocketchat.atlassian.net/browse/SUP-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: improve change stream error handler

apps/meteor/app/push/server/push.js
=> regression(push): fix error when adding headers to send push notification

.changeset/mean-bottles-work.md, apps/meteor/app/livechat/server/livechat.ts
This PR fixes the Livechat CSP validation, which was incorrectly blocking access to the widget for all non whitelisted domains.
[SUP-235](https://rocketchat.atlassian.net/browse/SUP-235)
[SUP-235]: https://rocketchat.atlassian.net/browse/SUP-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Livechat `CSP` whitelist validation

apps/meteor/client/providers/LayoutProvider.tsx, yarn.lock
=> regression: `Contextualbar` size

.changeset/modern-terms-jump.md, packages/agenda/src/Agenda.ts
https://rocketchat.atlassian.net/browse/OC-1032
=> fix: Saving Business hour throws an alert

.changeset/rude-islands-clap.md, apps/meteor/server/lib/rooms/roomTypes/direct.ts
=> fix:  Direct message notification

apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
=> test: omnichannel departaments flaky test

.changeset/hip-hornets-fail.md, apps/meteor/client/views/room/hooks/useOpenRoom.ts
Run this event every time the room is changed.
[SUP-251](https://rocketchat.atlassian.net/browse/SUP-251)
[SUP-251]: https://rocketchat.atlassian.net/browse/SUP-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(meteor): `room-opened` event not dispatching when navigating cached rooms

apps/meteor/client/views/omnichannel/currentChats/FilterByText.tsx, apps/meteor/client/views/omnichannel/directory/chats/contextualBar/RoomEdit/RoomEdit.tsx, apps/meteor/ee/client/hooks/useTagsList.ts, apps/meteor/ee/client/omnichannel/tags/AutoCompleteTagsMultiple.js, apps/meteor/ee/client/omnichannel/tags/CurrentChatTags.tsx
[OC-1132](https://rocketchat.atlassian.net/browse/OC-1132)
[OC-1138](https://rocketchat.atlassian.net/browse/OC-1138)
[OC-1132]: https://rocketchat.atlassian.net/browse/OC-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Current Chats tags filter not showing department tags

packages/mock-providers/.eslintrc.json, packages/mock-providers/package.json, packages/mock-providers/src/MockedAuthorizationContext.tsx, packages/mock-providers/src/MockedServerContext.tsx, packages/mock-providers/src/MockedSettingsContext.tsx, packages/mock-providers/src/MockedUserContext.tsx, packages/mock-providers/src/index.ts, packages/mock-providers/tsconfig.json, yarn.lock
The package aims to reduce friction to create providers to help unit tests
=> test: create mock package

.github/workflows/publish-release.yml, packages/release-action/src/bumpNextVersion.ts, packages/release-action/src/publishRelease.ts, packages/release-action/src/startPatchRelease.ts
Adding `[no ci]` to the commit message makes it possible to use only the `master` branch without having to worry about the automation running more than once.. doing so there is no need to use the `release-automation` to run the automation.
=> ci: skip ci on release publish

apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
Update Apps-Engine version from 1.40.0 alpha to latest - https://github.com/RocketChat/Rocket.Chat.Apps-engine/releases/tag/v1.40.0
=> chore: Bump up apps-engine

.changeset/shaggy-beans-poke.md, apps/meteor/app/lib/server/startup/filterATAllTag.ts, apps/meteor/app/lib/server/startup/filterATHereTag.ts
- Run `@all` and `@here` mentions callbacks verifications only after mentions are parsed.
Insert a regular user (which has only the `user` role assigned to it) "A" in a room. Then, as an admin, remove the `mention-all` and `mention-here` permissions from the user role.
Logged in as user "A", try to send a message tagging `@all` and `@here`.
**Current behavior:** the message is sent.
**Expected behavior:** an error is thrown and the message is not sent. An ephemeral message is also sent in the room, informing that tagging `@all` and `@here` is not allowed.
**Note:** this works the same with room scoped roles (eg Moderator, Leader, Owner). If the user has global **OR** room permission to mention `@all` and `@here`, then the message will be accepted.
SUP-294
=> fix: Users can mention `here` and `all` even without permission

ee/packages/ui-theming/src/paletteHighContrast.ts
- update button-primary colors on high-contrast palette
=> chore: high-contrast button-primary colors

.changeset/red-windows-admire.md, apps/meteor/app/apps/server/bridges/http.ts
Previously there was no timeout configured for HTTP requests made by apps via the Apps-Engine bridge, however the underlying library that handled this was changed and introduced a timeout of 20s - breaking compatibility to some extent. 
Here we set the timeout to 3m as it seems to be an appropriate balance.
https://github.com/RocketChat/Rocket.Chat/issues/30111
=> fix: HTTP timeout too short on Apps-Engine bridge

.changeset/slow-lizards-breathe.md, apps/meteor/app/authentication/server/startup/index.js
Apps-engine event `IPostUserCreated` was being triggered right _before_ the user was created
Kudos to @pierre-lehnen-rc for spotting this one out
=> fix: Trigger app post user created event correctly

.changeset/real-pets-visit.md, apps/meteor/server/models/raw/Rooms.ts, apps/meteor/tests/end-to-end/api/02-channels.js, packages/core-typings/src/IRoom.ts
- Do not remove the `default` field from rooms when it's set to `false` (since this would cause a breaking change in the `.setDefault` endpoints).
Introduced in #28260
Use the `channels.setDefault` endpoint to make a room default in the workspace. Then use it again to _unset_ it as default.
**Current behavior:** the `default` field is not returned in the response when setting it to `false`.
**Expected behavior:** the `default` field should be returned (with `false` as its value)
TC-930
It'd be a nice change not to store the default field with `false` value, though (since we never check for a `false` value in this field). Let's keep this a to-do for the next major release.
=> fix: `default` field is not returned from the `setDefault` endpoint when setting to false

ee/apps/ddp-streamer/src/DDPStreamer.ts, ee/apps/ddp-streamer/src/Server.ts, packages/core-services/src/types/IBroker.ts
I chose the name `rocketchat_subscription` for the metric instead of `rocketchat_meteor_subscriptions` used on monolith because they're actually different, I had to use histogram for the new one since `moleculer` doesn't support summary.
Here is an example of the metrics that will be provided by `ddp-streamer`:
```
rocketchat_subscription{namespace="",nodeID="node",subscription="stream-notify-all",quantile="0.5"} 0.08320799999999999
rocketchat_subscription{namespace="",nodeID="node",subscription="stream-notify-all",quantile="0.9"} 0.373125
rocketchat_subscription{namespace="",nodeID="node",subscription="stream-notify-all",quantile="0.95"} 0.373125
rocketchat_subscription{namespace="",nodeID="node",subscription="stream-notify-all",quantile="0.99"} 0.373125 …
```
=> chore: add subscription metrics to ddp-streamer

.changeset/strong-laws-pump.md, apps/meteor/app/statistics/server/lib/SAUMonitor.ts, apps/meteor/server/models/raw/Sessions.ts, packages/model-typings/src/models/ISessionsModel.ts
It changes the filter for the cronjob that runs daily to calculate the workspace MAU to fetch sessions only from 3 days ago.
This change is will only have an impact in case the cronjob has been skipped for quite a few days and will prevent large workspace from having the database hammered when it runs again.
=> fix: Consider only sessions from last few days for SAU/MAU

.changeset/slimy-cheetahs-heal.md, apps/meteor/client/components/Omnichannel/hooks/useDepartmentsList.ts, apps/meteor/client/views/omnichannel/departments/EditDepartmentWithData.tsx, apps/meteor/ee/client/omnichannel/additionalForms/DepartmentForwarding.tsx
[SUP-357](https://rocketchat.atlassian.net/browse/SUP-357)
[SUP-357]: https://rocketchat.atlassian.net/browse/SUP-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: selected departments not being displayed due to pagination

apps/meteor/client/views/admin/rooms/RoomsTable.tsx
Fixed a bug in which the rooms page table would not show teams and also removed some unnecessary old filter related code.
Demo gif:
[WM-175]: https://rocketchat.atlassian.net/browse/WM-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Fix rooms table not showing teams

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx, apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
=> regression: custom fields not showing in current chats

.github/workflows/ci.yml
=> ci: Add step to notify external services about a new release after Docker image publish

apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx
Fixed a bug in which the rooms page filters would not behave correctly due to the production React strict mode in conjunction with some poorly writen code.
Demo gif with --production flag:
[WM-181]: https://rocketchat.atlassian.net/browse/WM-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: multiselect

.changeset/brave-snakes-scream.md, apps/meteor/ee/server/local-services/instance/service.ts
=> fix: do not broadcast events from the local node to the local service (duplicated event)

apps/meteor/ee/app/license/server/settings.ts, apps/meteor/ee/app/license/server/startup.ts, apps/meteor/ee/server/lib/EnterpriseCheck.ts, ee/packages/license/__tests__/MockedLicenseBuilder.ts, ee/packages/license/__tests__/emitter.spec.ts, ee/packages/license/__tests__/setLicense.spec.ts, ee/packages/license/babel.config.json, ee/packages/license/package.json, ee/packages/license/src/events/deprecated.ts, ee/packages/license/src/events/emitter.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.spec.ts, ee/packages/license/src/license.ts, ee/packages/license/src/token.ts, ee/packages/license/src/v2/convertToV3.ts, ee/packages/license/src/validation/getCurrentValueForLicenseLimit.ts, ee/packages/license/src/validation/runValidation.spec.ts, ee/packages/license/src/validation/runValidation.ts, ee/packages/license/src/validation/validateFormat.ts, ee/packages/license/src/validation/validateLicensePeriods.ts, packages/jwt/src/index.ts, yarn.lock
=> chore: Add mocked license

apps/meteor/app/cloud/server/functions/buildRegistrationData.ts, apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts, apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/announcementSync.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/handleCommsSync.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/legacySyncWorkspace.ts, ee/packages/license/package.json, ee/packages/license/src/definition/ILicenseV3.ts, ee/packages/license/src/index.ts, packages/core-typings/src/cloud/WorkspaceSyncPayload.ts, packages/core-typings/src/cloud/index.ts, packages/server-cloud-communication/package.json, packages/server-cloud-communication/src/index.ts, yarn.lock
=> chore: add the new endpoints to sync with cloud

ee/packages/license/src/pendingLicense.ts
=> regression: unmarked dangling promise on license validation

.changeset/brown-comics-cheat.md, apps/meteor/app/cloud/server/functions/buildRegistrationData.ts, apps/meteor/app/statistics/server/lib/statistics.ts, apps/meteor/client/views/admin/info/DeploymentCard.stories.tsx, apps/meteor/client/views/admin/info/InformationPage.stories.tsx, apps/meteor/client/views/admin/info/UsageCard.stories.tsx, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/LivechatVisitors.ts, packages/core-typings/src/IStats.ts, packages/core-typings/src/omnichannel/index.ts, packages/core-typings/src/omnichannel/mac.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts, packages/model-typings/src/models/ILivechatVisitorsModel.ts
=> chore: Calculate & Store MAC stats

apps/meteor/ee/app/license/server/startup.ts, ee/packages/license/__tests__/MockedLicenseBuilder.ts, ee/packages/license/__tests__/emitter.spec.ts, ee/packages/license/package.json, ee/packages/license/src/definition/LicenseBehavior.ts, ee/packages/license/src/definition/LicenseValidationOptions.ts, ee/packages/license/src/definition/LimitContext.ts, ee/packages/license/src/definition/events.ts, ee/packages/license/src/events/emitter.ts, ee/packages/license/src/events/listeners.ts, ee/packages/license/src/index.ts, ee/packages/license/src/isItemAllowed.ts, ee/packages/license/src/license.ts, ee/packages/license/src/modules.ts, ee/packages/license/src/v2/convertToV3.ts, ee/packages/license/src/validation/getCurrentValueForLicenseLimit.ts, ee/packages/license/src/validation/getResultingBehavior.ts, ee/packages/license/src/validation/runValidation.spec.ts, ee/packages/license/src/validation/runValidation.ts, ee/packages/license/src/validation/validateLicenseLimits.ts, ee/packages/license/src/validation/validateLicensePeriods.ts, ee/packages/license/src/validation/validateLicenseUrl.spec.ts, ee/packages/license/src/validation/validateLicenseUrl.ts, yarn.lock
=> chore: License v3 - behavior and limited reached triggers

apps/meteor/client/sidebar/header/CreateDirectMessage.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
[DSAR-279]
[DSAR-279]: https://rocketchat.atlassian.net/browse/DSAR-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `CreateDirectMessage` a11y form improvements

apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/announcementSync.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts, apps/meteor/ee/app/license/server/startup.ts
=> regression: test license from cloud

apps/meteor/app/cas/server/cas_server.js, apps/meteor/app/irc/server/irc-bridge/peerHandlers/joinedChannel.js, apps/meteor/app/slackbridge/server/RocketAdapter.js
=> regression: failing to create rooms in some integrations

apps/meteor/ee/server/api/licenses.ts, apps/meteor/tests/end-to-end/api/20-licenses.js, ee/packages/license/src/definition/LicenseInfo.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.ts, packages/rest-typings/src/v1/licenses.ts
=> fix: licenses.info endpoint only available for admins

apps/meteor/tests/end-to-end/api/09-rooms.js
Fix the flaky test where sometimes the name update wasn't finished before the test ran
=> test: wait for the name update finish

apps/meteor/packages/rocketchat-mongo-config/server/index.js, apps/meteor/server/cron/userDataDownloads.ts, apps/meteor/server/lib/dataExport/uploadZipFile.ts
=> test: fix API test flakiness 

apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts, apps/meteor/app/version-check/server/functions/buildVersionUpdateMessage.ts, apps/meteor/app/version-check/server/functions/checkVersionUpdate.ts, apps/meteor/app/version-check/server/functions/getNewUpdates.ts, packages/server-cloud-communication/src/definitions/index.ts
=> chore: allow supported versions throughout envvar

apps/meteor/client/hooks/useWorkspaceInfo.ts, apps/meteor/client/views/admin/workspace/WorkspacePage.tsx, apps/meteor/client/views/admin/workspace/WorkspaceRoute.tsx
We were loading the endpoint `v1/statistics` without using the cache provided by the server, this causes a huge delay on bigger workspaces. 
This was fixed by implementing the correct usage of the parameter `refresh` to get the latest stats from the server
=> regression: workspace stats cache loading

apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/Rooms.ts, apps/meteor/server/models/raw/Subscriptions.ts, apps/meteor/server/models/raw/Users.js
the indexes removed are actually redundant and are prefixes of other compound indexes.
Unused indexes consume storage space and increase write latency.
=> chore: remove redundant indexes

apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts, apps/meteor/client/hooks/useIsEnterprise.ts, apps/meteor/client/hooks/useLicense.ts, apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.spec.tsx, apps/meteor/ee/client/hooks/useHasLicenseModule.ts, apps/meteor/ee/server/startup/engagementDashboard.ts, apps/meteor/server/models/raw/Analytics.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v304.ts, ee/packages/license/src/events/emitter.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.spec.ts
=> regression: adjust license

.changeset/dirty-rings-fry.md, apps/meteor/app/api/server/v1/groups.ts, apps/meteor/tests/end-to-end/api/02-channels.js, apps/meteor/tests/end-to-end/api/03-groups.js
- Throw meteor error instead of `internalError` on `groups.create`.
Introduced by #30499
Use the [groups.create](https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/groups-endpoints/create) endpoint to add a group named `general`.
TC-1031
=> fix: creating group with the name of an already existing room throws `internalError`

apps/meteor/app/cloud/server/functions/buildRegistrationData.ts, apps/meteor/client/views/setupWizard/providers/SetupWizardProvider.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/server/cron/statistics.ts, apps/meteor/server/settings/general.ts
=> fix: Registration  Data

apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
[TC-1057](https://rocketchat.atlassian.net/browse/TC-1057)
Send an image
Create a new thread on that image
Inside the thread view, click the image.
It should open the gallery
[TC-1057]: https://rocketchat.atlassian.net/browse/TC-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Gallery not working inside threads

apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx, apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx, apps/meteor/client/views/omnichannel/agents/AgentInfoAction.tsx, apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx, apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx, apps/meteor/client/views/omnichannel/agents/hooks/useRemoveAgent.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
[OC-1366](https://rocketchat.atlassian.net/browse/OC-1366)
[OC-1366]: https://rocketchat.atlassian.net/browse/OC-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: improved agents e2e tests

apps/meteor/client/components/Omnichannel/modals/ReturnChatQueueModal.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-manual-selection.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts, apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
[OC-1370](https://rocketchat.atlassian.net/browse/OC-1370)
[OC-1370]: https://rocketchat.atlassian.net/browse/OC-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: implemented e2e tests for manual selection

.changeset/violet-pears-cry.md, apps/meteor/server/models/raw/Uploads.ts
=> fix: file type filter not working on room's file list

apps/meteor/client/views/admin/settings/inputs/BooleanSettingInput.tsx
=> regression: `ResetButton` misaligned on `BooleanSettingInput`

.changeset/tame-drinks-yell.md, apps/meteor/app/2fa/server/loginHandler.ts, apps/meteor/client/main.ts, apps/meteor/client/startup/accounts.ts, apps/meteor/client/startup/index.ts
The `Accounts.onEmailVerificationLink` and `Accounts.verifyEmail` was not working as expected.
The `Accounts.onEmailVerificationLink` needs to be called in the top level of the application, but instead, it was being called thought a dynamic import. 
I changed to a static import and changed the behavior after the verification, now the user is being logged in after the email is verified.
**Expected Behavior**
The email of the newly registered user should be verified since the verification link was clicked.
**Actual Behavior**
The user’s email is still not verified and requires the admin to manually verify the email address from the User’s profile.
fix https://github.com/RocketChat/Rocket.Chat/issues/30890
fix https://github.com/RocketChat/Rocket.Chat/issues/30811
fix …
=> fix: account verify email

apps/meteor/app/lib/server/startup/mentionUserNotInChannel.ts
Moved the recently added code from #30464 to an `afterSaveMessage` callback, which doesn't change anything from a feature point of view..
I've also improved the code a little bit removing unnecessary calls to DB.
=> chore: move `mention-user-not-in-channel` to afterSaveMessage

.changeset/sour-kids-heal.md, apps/meteor/ee/app/authorization/server/callback.ts, apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
[SUP-436]
[SUP-436]: https://rocketchat.atlassian.net/browse/SUP-436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix wrong callback usage on after/before user actions

ee/packages/ddp-client/src/DDPSDK.ts, ee/packages/ddp-client/src/types/Account.ts
=> refactor: SDK reconnection resume login attempt

.changeset/chilled-cooks-end.md, apps/meteor/client/views/account/preferences/AccountPreferencesPage.tsx, apps/meteor/client/views/account/preferences/useAccountPreferencesValues.ts
BEFORE THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/0fdc1b0f-4e42-4546-87b8-3968e56e1c9c
AFTER THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/ca4c6cc2-f121-4561-a6ff-5ba1d93a819f
REASON BEHIND CHANGES
The type of 'language'  field  in default values was string | undefined. When undefined it wont show anything, so we need to use correct type for 'language' which is only 'string' and also if language is undefined(when useUserPreference returns undefiend) we should assign it with blank ''
This should close issues :-
fix #31307
1. Go to Account
2. Click on Preferences
3. See language selection box
=> fix: Language selection box is empty which should be default

.changeset/lemon-shrimps-draw.md, apps/meteor/client/lib/chats/flows/uploadFiles.ts
Proposed changes (including videos or screenshots)
BEFORE THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/68e9d8d0-3ef5-411a-93e5-d009ff97c331
AFTER THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/73c161a2-3658-4b76-8276-e38dbfc6f177
REASON BEHIND CHANGES
If the type of file which we want to upload is not clear then we should not allow it to be uploaded in the server
Issue(s)
This should close issues :-
closes https://github.com/RocketChat/Rocket.Chat/issues/27924
Steps to test or reproduce
1. Login to rocket chat.
2. Set "Accepted Media Types" setting in "File Upload" section. For example image/*,application/pdf,text/plain,application/msword
3. Try sending a rare file type like .har
4. The file is not loaded into the chat, and there is no error …
=> fix: No error message when uploading a file that is not allowed

apps/meteor/client/components/ImageGallery/ImageGallery.tsx
Proposed changes (including videos or screenshots)
BEFORE THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/c3948a9b-21c0-40f9-8f4c-97e79909a698
AFTER THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/c7a48b70-4951-43e3-9e35-a879107d61de
REASON BEHIND CHANGES
There are far better ways to implement this but with this configuration,this is the best way to implement this feature
Issue(s)
This should close issues :-
closes https://github.com/RocketChat/Rocket.Chat/issues/31341
Steps to test or reproduce
Login to rocket chat.
Go to any Community chat.
Click on any media
=> fix: close image gallery on backdrop click

.changeset/bump-patch-1703700471583.md, .changeset/three-moles-look.md, .changeset/tiny-glasses-help.md, .github/workflows/pr-update-description.yml, apps/meteor/app/cloud/server/functions/buildRegistrationData.ts, apps/meteor/app/livechat/client/lib/stream/queueManager.ts, apps/meteor/client/providers/OmnichannelProvider.tsx, packages/release-action/src/index.ts, packages/release-action/src/updatePRDescription.ts, yarn.lock
*   a075950e23: Bump @rocket.chat/meteor version.
*   84c4b0709e: Fixed conversations in queue being limited to 50 items
*   886d92009e: Fix wrong value used for Workspace Registration
*   @rocket.chat/core-typings@6.5.2
*   @rocket.chat/rest-typings@6.5.2
*   @rocket.chat/api-client@0.1.20
*   @rocket.chat/license@0.1.2
*   @rocket.chat/omnichannel-services@0.1.2
*   @rocket.chat/pdf-worker@0.0.26
*   @rocket.chat/presence@0.1.2
*   @rocket.chat/core-services@0.3.2
*   @rocket.chat/cron@0.0.22
*   @rocket.chat/gazzodown@3.0.2
*   @rocket.chat/model-typings@0.2.2
*   @rocket.chat/ui-contexts@3.0.2
*   @rocket.chat/server-cloud-communication@0.0.1
* …
=> Release 6.5.2

apps/meteor/client/views/marketplace/AppsList/AppRow.tsx
=> regression: `AppRow` bundleIn verification

apps/meteor/app/statistics/server/lib/statistics.ts, apps/meteor/ee/server/NetworkBroker.ts, apps/meteor/ee/server/local-services/instance/service.ts, apps/meteor/server/services/authorization/service.ts, ee/apps/ddp-streamer/src/DDPStreamer.ts, ee/apps/ddp-streamer/src/configureServer.ts, packages/core-services/src/LocalBroker.ts
=> chore: services changes on lifecycle methods + throw if svc is not available

apps/meteor/app/statistics/server/lib/getAppsStatistics.js, apps/meteor/ee/lib/misc/formatAppInstanceForRest.ts, apps/meteor/ee/server/apps/communication/endpoints/appsCountHandler.ts, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/ee/server/apps/cron.ts, apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/package.json, apps/meteor/server/services/apps-engine/service.ts, yarn.lock
=> fix: async operations

.changeset/fresh-maps-rhyme.md, apps/meteor/server/models/raw/BaseRaw.ts, apps/meteor/server/startup/migrations/v304.ts
=> fix: multiple indexes creations during migrations

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts
=> test: fix flaky setGuestName test

apps/meteor/tests/e2e/messaging.spec.ts
=> test: fix messaging flaky test

apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts, apps/meteor/client/meteorOverrides/login/saml.ts, apps/meteor/tests/e2e/saml.spec.ts
SAML's Single Sign Out feature operated based on the login service configurations data and this data is no longer updated automatically in the client when it changes in the server. This PR changes the single sign out to check the SAML settings directly so it'll always respect the current server configuration.
=> chore: change SAML single sign out to access workspace settings directly

apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx
[TC-1094](https://rocketchat.atlassian.net/browse/TC-1094?atlOrigin=eyJpIjoiMjk2MjM3ZDcwYjU0NGVmZjk4NzM3N2NmNWIwMzM1YmQiLCJwIjoiaiJ9)
[TC-1094]: https://rocketchat.atlassian.net/browse/TC-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Engagement dashboard crashing 

apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx
- We've improved the handling of the `attachments[]` and `files[]` arrays in our message processing logic. Previously, there were edge cases where the `attachments[]` array was present but empty, and the `files[]` array was not present. This could lead to unexpected behavior. With this update, we've added checks to ensure that the `attachments[]` array not only exists, but also contains at least one element before attempting to access the `files[]` array. This makes our reported message processing more robust and prevents potential issues caused by these edge cases.
[WM-221](https://rocketchat.atlassian.net/browse/WM-221)
[WM-221]: https://rocketchat.atlassian.net/browse/WM-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: empty attachments leads to a Moderation Console GUI crash 

apps/meteor/client/components/message/uikit/UiKitMessageBlock.tsx
The UiKitMessage was blinking/refreshing the room page due to an action that it was triggering the Suspense, to fix it I've added an inner suspense before the UiKitMessage 
[TC-1099](https://rocketchat.atlassian.net/browse/TC-1099)
[TC-1099]: https://rocketchat.atlassian.net/browse/TC-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: UiKitMessage refreshing room

.changeset/polite-donkeys-cheer.md, apps/meteor/app/slashcommands-archiveroom/server/server.ts, apps/meteor/app/slashcommands-unarchiveroom/server/server.ts, apps/meteor/tests/end-to-end/api/16-commands.js, apps/meteor/tests/end-to-end/api/16-commands.ts
=> fix: missing slashcommand permissions

.changeset/config.json, packages/release-changelog/.eslintrc.json, packages/release-changelog/package.json, packages/release-changelog/src/getGitHubInfo.ts, packages/release-changelog/src/index.ts, packages/release-changelog/tsconfig.json, yarn.lock
This is actually a "fork" from [@changesets/changelog-github](https://github.com/changesets/changesets/blob/main/packages/changelog-github/src/index.ts) with some key changes to be more suitable for us.
There are two main changes:
- Adds the PR number to the change
- Update dependencies are groups and collapsed by default
Below you can see a comparison of the current changelog for 6.6.0 and the new one:
=> ci: Improve release changelog by adding the PR to items as well as the username of the contributor

apps/meteor/ee/client/voip/components/modals/WrapUpCallModal.tsx
[OC-1451](https://rocketchat.atlassian.net/browse/OC-1451)
[OC-1451]: https://rocketchat.atlassian.net/browse/OC-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Opening WrapUpCallModal crashes the GUI

apps/meteor/client/providers/UserProvider/hooks/useClearRemovedRoomsHistory.ts, apps/meteor/server/modules/watchers/watchers.module.ts, ee/packages/ddp-client/src/types/streams.ts, packages/core-services/src/events/Events.ts
=> regression: Exclude clearRemovedRoomsHistory from L rooms

apps/meteor/tests/end-to-end/api/24-methods.js
=> test: make api methods test fully independent

.changeset/lucky-ducks-join.md, apps/meteor/client/startup/customOAuth.ts, apps/meteor/tests/e2e/config/global-setup.ts, apps/meteor/tests/e2e/fixtures/addCustomOAuth.ts, apps/meteor/tests/e2e/oauth.spec.ts, apps/meteor/tests/e2e/page-objects/auth.ts
=> fix: Custom OAuth not working if other login services are also enabled

apps/meteor/client/views/room/hooks/useMessageListNavigation.ts, apps/meteor/tests/e2e/messaging.spec.ts
=> regression: Prevent storing lastFocused message by click event

apps/meteor/ee/server/configuration/saml.ts, apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/authsources.php, apps/meteor/tests/e2e/fixtures/userStates.ts, apps/meteor/tests/e2e/saml.spec.ts, apps/meteor/tests/e2e/utils/custom-role.ts
=> test: saml login custom role

.changeset/shy-bananas-repeat.md, apps/meteor/ee/server/local-services/federation/service.ts, apps/meteor/server/services/federation/service.ts
- fix: make lifecycle methods part of inherited class in federation services
- chore: add changeset
=> fix: make lifecycle methods part of inherited class in federation services

.changeset/bump-patch-1709141264352.md, .changeset/shy-bananas-repeat.md, .changeset/strange-lamps-taste.md, .changeset/young-doors-bathe.md, apps/meteor/app/notifications/client/lib/Presence.ts, apps/meteor/ee/server/local-services/federation/service.ts, apps/meteor/server/modules/listeners/listeners.module.ts, apps/meteor/server/modules/notifications/notifications.module.ts, apps/meteor/server/services/federation/service.ts, ee/apps/ddp-streamer/package.json, ee/packages/ddp-client/src/types/streams.ts, yarn.lock
*   ([#31844](https://github.com/RocketChat/Rocket.Chat/pull/31844)) Fixed Federation not working with Microservice deployments
*   ([#31823](https://github.com/RocketChat/Rocket.Chat/pull/31823)) Revert unintentional changes real time presence data payload
*   ([#31833](https://github.com/RocketChat/Rocket.Chat/pull/31833)) Fix web UI not showing users presence updating to offline
*   @rocket.chat/ui-contexts@4.0.2
*   @rocket.chat/ui-theming@0.1.2
*   @rocket.chat/fuselage-ui-kit@4.0.2
*   @rocket.chat/gazzodown@4.0.2
*   @rocket.chat/ui-client@4.0.2
* …
=> Release 6.6.2

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadChat.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx, apps/meteor/client/views/room/hooks/useDateScroll.ts
=> chore: remove hardcoded position for message date

apps/meteor/client/components/message/variants/RoomMessage.tsx, apps/meteor/client/components/message/variants/ThreadMessage.tsx, apps/meteor/client/views/room/MessageList/hooks/useJumpToMessage.ts
=> chore: improve useJumpToMessage

.changeset/bump-patch-1709669273957.md, .changeset/wicked-months-laugh.md, apps/meteor/ee/server/startup/presence.ts, apps/meteor/tests/end-to-end/api/01-users.js, yarn.lock
*   ([#31895](https://github.com/RocketChat/Rocket.Chat/pull/31895)) Fix users presence stuck as online after connecting using mobile apps
*   @rocket.chat/core-typings@6.6.3
*   @rocket.chat/rest-typings@6.6.3
*   @rocket.chat/api-client@0.1.25
*   @rocket.chat/license@0.1.7
*   @rocket.chat/omnichannel-services@0.1.7
*   @rocket.chat/pdf-worker@0.0.31
*   @rocket.chat/presence@0.1.7
*   @rocket.chat/core-services@0.3.7
*   @rocket.chat/cron@0.0.27
*   @rocket.chat/gazzodown@4.0.3
*   @rocket.chat/model-typings@0.3.3
*   @rocket.chat/ui-contexts@4.0.3
* …
=> Release 6.6.3

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
=> chore: move store scroll position to useRestoreScrollPosition (#31902)

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts
=> chore: create Roombody useLeaderBanner hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useHasNewMessages.ts, apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
fix: `New Messages` on scroll bottom not disappearing
- add scroll listener on `useHasNewMessages`
fix: `Unread Messages` on scroll counter not working
- switch refs
=> regression: `RoomBody` unread and new messages behavior

apps/meteor/client/views/room/Header/icons/Favorite.tsx, packages/i18n/src/locales/en.i18n.json
Reverts RocketChat/Rocket.Chat#31934
=> Revert "regression: Favorite action announcement"

.changeset/afraid-mugs-priest.md, packages/livechat/src/lib/hooks.ts, packages/livechat/src/routes/Register/index.tsx, packages/livechat/src/store/index.tsx
CORE-50
REQUIRES https://github.com/RocketChat/Rocket.Chat/pull/31268
=> fix: setDepartment Livechat API call overriding triggers

.changeset/chatty-horses-peel.md, apps/meteor/ee/app/settings/server/settings.ts
Added a license callbacks `onRemoveLicense` and `onInvalidateLicense` to update enterprise settings values when a license is removed/invalid. 
This solves a specific scenario where in case of a downgrade (license removal), `settings.get` would continue to return `value` for enterprise settings instead of `invalidValue` as it should. This would remain the case until the workspace was restarted.
[PROSVC-73](https://rocketchat.atlassian.net/browse/PROSVC-73)
[PROSVC-73]: https://rocketchat.atlassian.net/browse/PROSVC-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: enterprise settings value not being updated when license is removed/invalid

apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-open-by-visitor.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-time-on-site.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts, packages/livechat/src/lib/triggers.js
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/31268
[PROSVC-37](https://rocketchat.atlassian.net/browse/PROSVC-37)
[PROSVC-37]: https://rocketchat.atlassian.net/browse/PROSVC-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: triggers being scheduled when user is already registered

packages/livechat/src/lib/room.js
it seems that in extreme conditions (low cpu x slow network)
It is possible to call close chat more than once,
one caused by user interaction and the other by the message received via websocket. causing some navigation problems.
=> chore(livechat): stop calling twice closeChat 

.changeset/bump-patch-1710772454766.md, .changeset/cyan-countries-impress.md, .changeset/moody-ghosts-add.md, .changeset/slimy-clocks-argue.md, .gitignore, apps/meteor/app/search/server/search.internalService.ts, apps/meteor/ee/server/NetworkBroker.ts, apps/meteor/ee/server/startup/services.ts, apps/meteor/ee/tests/unit/server/NetworkBroker.tests.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts, apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Settings.ts, apps/meteor/tests/mocks/server/BrokerMocked.ts, apps/meteor/tests/unit/server/services/messages/hooks/BeforeSaveCheckMAC.tests.ts, packages/core-services/src/LocalBroker.ts, packages/core-services/src/lib/Api.ts, packages/core-services/src/types/IApiService.ts, packages/core-services/src/types/IBroker.ts, yarn.lock
*   ([#31700](https://github.com/RocketChat/Rocket.Chat/pull/31700)) Fixed matrix homeserver domain setting not being visible in admin panel
*   ([#32012](https://github.com/RocketChat/Rocket.Chat/pull/32012)) Don't use the registration.yaml file to configure Matrix Federation anymore.
*   ([#31927](https://github.com/RocketChat/Rocket.Chat/pull/31927)) `stopped` lifecycle method was unexpectedly synchronous when using microservices, causing our code to create race conditions.
*   <details><summary>Updated dependencies [c2872a93f2]:</summary>
*   @rocket.chat/core-services@0.3.8
*   @rocket.chat/omnichannel-services@0.1.8
* …
=> Release 6.6.4

.changeset/polite-cars-love.md, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts, packages/livechat/src/i18n/en.json, packages/livechat/src/i18n/pt-BR.json, packages/livechat/src/routes/LeaveMessage/index.tsx
[SUP-478]
[SUP-478]: https://rocketchat.atlassian.net/browse/SUP-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Livechat): Livechat_Display_Offline_Form not working correctly 

.changeset/bump-patch-1710964059521.md, .changeset/empty-hounds-jog.md, .changeset/thin-keys-impress.md, .changeset/tough-doors-juggle.md, apps/meteor/server/services/omnichannel/queue.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/unit/server/services/omnichannel/queue.tests.ts, ee/packages/ddp-client/src/livechat/LivechatClientImpl.ts, packages/livechat/src/lib/hooks.js, packages/livechat/src/lib/room.js, yarn.lock
*   ([#31998](https://github.com/RocketChat/Rocket.Chat/pull/31998)) Introduced a new step to the queue worker: when an inquiry that's on an improper status is selected for processing, queue worker will first check its status and will attempt to fix it.
For example, if an inquiry points to a closed room, there's no point in processing, system will now remove the inquiry
If an inquiry is already taken, the inquiry will be updated to reflect the new status and clean the queue.
This prevents issues where the queue worker attempted to process an inquiry *forever* because it was in an improper state.
*   <details><summary>Updated …
=> Release 6.6.5

apps/meteor/app/livechat/server/statistics/LivechatAgentActivityMonitor.ts
CORE-215
Add projection and change promise calls to Promise.all on LivechatAgentActivityMonitor. This should reduce the time for processing promises sequentially & reduce the data received from Mongo
=> refactor: Add `projection` and change promise calls to `Promise.all` on LivechatAgentActivityMonitor

.changeset/thirty-ducks-smell.md, .changeset/twenty-dolls-obey.md, .vscode/settings.json, packages/models/jest.config.ts, packages/models/package.json, packages/models/src/proxify.spec.ts, packages/models/src/proxify.ts
Fix proxified model props were missing context before attribution
it fixes the error during migration 304. Throwing `Cannot read property 'finally' of undefined` error.
closes https://github.com/RocketChat/Rocket.Chat/issues/31635
=> fix: proxified model props were missing context before attribution

.changeset/clean-cars-teach.md, apps/meteor/app/assets/server/assets.ts, apps/meteor/app/livechat/server/api/lib/livechat.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/ee/app/livechat-enterprise/server/settings.ts, apps/meteor/server/settings/omnichannel.ts, packages/core-typings/src/IRocketChatAssets.ts, packages/i18n/src/locales/en.i18n.json, packages/i18n/src/locales/pt-BR.i18n.json, packages/livechat/src/components/Screen/ChatButton.tsx, packages/livechat/src/components/Screen/ScreenProvider.tsx, packages/livechat/src/components/Screen/index.js, packages/livechat/src/store/index.tsx
This PR adds two new Livechat settings:
| Name                                             | Type        | Description |
|---------------------------------|---------|------------------|
| Hide "powered by Rocket.Chat" | boolean | Hides Rocket.Chat's watermark in Livechat. |
| Livechat logo                                |  asset     | Changes the Livechat widget logo |
ℹ️ **Tests for both settings will be implemented in separate tasks : [PROSVC-80](https://rocketchat.atlassian.net/browse/PROSVC-80) and [PROSVC-81](https://rocketchat.atlassian.net/browse/PROSVC-81)**
[PROSVC-48](https://rocketchat.atlassian.net/browse/PROSVC-48)
[PROSVC-48]: https://rocketchat.atlassian.net/browse/PROSVC-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> feat(livechat): hide or change logo

.changeset/good-baboons-shop.md, apps/meteor/app/livechat/imports/server/rest/appearance.ts, apps/meteor/app/livechat/server/api/lib/appearance.ts, apps/meteor/client/views/omnichannel/appearance/AppearanceFieldLabel.tsx, apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx, apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts, packages/rest-typings/src/v1/omnichannel.ts
**Added Livechat's new theming settings to Appearance page (available for Premium workspaces)**
Newly added settings are:
- `Livechat widget position on the screen`:  Changes the widget position between left or right of the viewport
- `Livechat background`: Changes the message list background. Receives the same value as the CSS's background property.
- `Hide system messages`: Changes the visibility of system messages displayed on the widget.
- `Hide "powered by Rocket.Chat"`: Changes the visibility of Rocket.Chat's watermark on the widget.
[PROSVC-33](https://rocketchat.atlassian.net/browse/PROSVC-33)
[PROSVC-78](https://rocketchat.atlassian.net/browse/PROSVC-78)
[PROSVC-33]: https://rocketchat.atlassian.net/browse/PROSVC-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> feat: added Livechat's new theming settings to Appearance page

.changeset/bump-patch-1711139853086.md, .changeset/chatty-suits-dance.md, .changeset/thirty-ducks-smell.md, .changeset/twenty-dolls-obey.md, .vscode/settings.json, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/models/jest.config.ts, packages/models/package.json, packages/models/src/proxify.spec.ts, packages/models/src/proxify.ts, packages/rest-typings/package.json, yarn.lock
- Apps-Engine: `^1.41.1`
*   ([#32064](https://github.com/RocketChat/Rocket.Chat/pull/32064)) Fix an issue affecting Rocket.Chat Apps utilizing the OAuth 2 library from Apps Engine, ensuring that apps like Google Drive and Google Calendar are operational once more.
*   ([#32056](https://github.com/RocketChat/Rocket.Chat/pull/32056)) Fix error during migration 304. Throwing `Cannot read property 'finally' of undefined` error.
*   <details><summary>Updated dependencies [ada096901a]:</summary>
*   @rocket.chat/models@0.0.34
*   @rocket.chat/omnichannel-services@0.1.10
*   @rocket.chat/presence@0.1.10
*   @rocket.chat/core-services@0.3.10
* …
=> Release 6.6.6

apps/meteor/client/views/omnichannel/directory/ContextualBar.tsx, apps/meteor/client/views/omnichannel/directory/OmnichannelDirectoryPage.tsx
[CORE-223]
[CORE-223]: https://rocketchat.atlassian.net/browse/CORE-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `ContextualbarDialog` being displayed without route param on Omnichannel directory

.changeset/great-yaks-dream.md, ee/apps/ddp-streamer/src/Publication.ts
=> fix: internal server error when connecting to publication with backward compatibility flag

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
Some contexts were not being closed on the livechat api tests
=> test(Livechat): Clean up after registerGuest() test

apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
Introduced here: #31978
Due to some changes in the semantics of `Contextualbar` the discussion list wasn't using the proper component so it lost the style. 
Adding the proper component for the title fixes the issue!
[CORE-226]
[CORE-226]: https://rocketchat.atlassian.net/browse/CORE-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: DiscussionsList title missing style

apps/meteor/app/cors/server/cors.ts, apps/meteor/packages/rocketchat-livechat/assets/demo.html, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts
Some tests fail because of changes in CPS and race conditions. This means there is no need to keep changing the value, the test will stop failing, but the problem still exists
=> test: allow csp for livechat tests

.changeset/nine-houses-reply.md, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, packages/livechat/src/lib/hooks.ts
introduced here:
https://github.com/RocketChat/Rocket.Chat/pull/30993
When calling the method of register/setToken, when the value is the same, it loads the configs again (with the list of empty messages). As the room and department were the same, the application did not react to the change.
Now whenever a "sensitive" value changes, it will load the config and then the list of messages.
closes #32042 
https://rocketchat.atlassian.net/browse/SUP-526
=> fix(livechat): registering guest multiple times cause message loss

.changeset/sweet-books-trade.md, apps/meteor/client/sidebar/search/SearchList.tsx
the key to invalidate clearly only uses the `_id`, when the name changes it does not invalidate and keeps rendering the old name
=> fix: search room not reactive after room name changes

apps/meteor/client/views/root/SAMLLoginRoute.tsx
Meteor 3 accounts package changed the login workflow to only call the login callbacks after all user data is loaded. This affected the SAML login that relied on a callback to run when the login is successful. This PR changed that to no longer rely on this callback.
=> chore: changes to SAML login in anticipation of meteor 3

.changeset/wild-keys-obey.md, packages/livechat/src/lib/room.js
Part of [SUP-485]
This stops a situation that could open two different rooms on the same Livechat session
[SUP-485]: https://rocketchat.atlassian.net/browse/SUP-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/RocketChat/Rocket.Chat/assets/20868078/fc4926c4-bf76-4264-947d-81c6a953ffa2
=> fix: livechat room desync on different windows

.github/actions/build-docker/action.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml
[ARCH-1282](https://rocketchat.atlassian.net/browse/ARCH-1282)
because of a missing variable, we were building the images more than once
[ARCH-1282]: https://rocketchat.atlassian.net/browse/ARCH-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: fix services container not building in build step

.changeset/strange-rivers-live.md, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/RoutingManager.ts, apps/meteor/app/livechat/server/methods/saveDepartment.ts, apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx, apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts, apps/meteor/tests/data/livechat/department.ts, apps/meteor/tests/data/livechat/users.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/10-departments.ts, packages/core-typings/src/ILivechatDepartment.ts, packages/i18n/src/locales/en.i18n.json
This PR introduces a feature for Rocket.Chat, enabling agents to forward inquiries to offline departments. It includes department-specific settings, allowing for efficient queue management and automatic assignment of inquiries to agents upon their availability. The implementation required modifications across multiple packages to ensure seamless integration and functionality that included a new flag in the department collection `allowReceiveForwardOffline`.
This update aims to enhance user experience by streamlining the inquiry management process, especially in scenarios involving offline department engagement.
https://rocketchat.atlassian.net/browse/SUP-242
=> feat: allowing forward to offline dep

apps/meteor/server/database/watchCollections.ts
When using `DISABLE_DB_WATCHERS=true` to ignore changes from change streams, we were still receiving all the data from MongoDB and then ignoring them by just not broadcasting.. With this change we'll not even ask MongoDB to send those changes.
=> chore: remove collections when db watcher is disabled

apps/meteor/packages/autoupdate/autoupdate_client.js, apps/meteor/packages/autoupdate/autoupdate_server.js, apps/meteor/packages/autoupdate/client_versions.js, apps/meteor/packages/autoupdate/package.js, apps/meteor/packages/flow-router/client/_init.js, apps/meteor/packages/flow-router/client/group.js, apps/meteor/packages/flow-router/client/modules.js, apps/meteor/packages/flow-router/client/route.js, apps/meteor/packages/flow-router/client/router.js, apps/meteor/packages/flow-router/client/triggers.js, apps/meteor/packages/flow-router/lib/router.js, apps/meteor/packages/flow-router/server/group.js, apps/meteor/packages/flow-router/server/route.js, apps/meteor/packages/flow-router/server/router.js, apps/meteor/packages/linkedin-oauth/linkedin-server.js, apps/meteor/packages/meteor-cookies/cookies.js, apps/meteor/packages/meteor-cookies/package.js, apps/meteor/packages/meteor-run-as-user/lib/collection.overwrites.js, apps/meteor/packages/meteor-run-as-user/lib/common.js, apps/meteor/packages/meteor-run-as-user/lib/pre.1.0.3.js
just change quotes and spacing, better now than later, as soon as we have some real modification the diff will be easier to visualize
=> chore(meteor/packages): apply code style

apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
… mistake
This pull request fixes a failing test where Playwright unintentionally unselected options during test execution. The solution involves explicitly clicking on the element's edge (rather than the default center) to open the list without accidentally clicking a chip.
**Before:** 
**After:**
=> test: Prevent playwright from unselecting options by mistake

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-watermark.spec.ts, apps/meteor/tests/e2e/page-objects/index.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts, apps/meteor/tests/e2e/page-objects/omnichannel-settings.ts, packages/livechat/src/components/Footer/index.tsx
This PR adds integration tests for the newly created setting `Hide "powered by Rocket.Chat"` (`Livechat_hide_watermark`). 
It covers checking the correct default state, changing the setting in the workspace and confirming the watermark was hidden.
**Setting:** 
**Watermark:**
[PROSVC-80](https://rocketchat.atlassian.net/browse/PROSVC-80)
[PROSVC-80]: https://rocketchat.atlassian.net/browse/PROSVC-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: added e2e tests for Livechat's hide watermark setting

apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-background.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-appearance.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts, packages/livechat/src/components/Messages/MessageList/index.js
This PR adds integration tests for the key `background` from Livechat's setTheme API method as well as the workspace setting.
**Test Flow**
**Workspace setting:** _(Admin > Settings > Omnichannel > Livechat)_
**API flow:**     
[PROSVC-84](https://rocketchat.atlassian.net/browse/PROSVC-84)
There's also a small test for the Livechat Appearance page. Just to make sure the background value is being saved correctly, since we've had similar regressions before.
[PROSVC-84]: https://rocketchat.atlassian.net/browse/PROSVC-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: added e2e tests for Livechat's background setting

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-fileupload.spec.ts
This was supposed to be a part of  [CORE-216] but maybe it got missing on a rebase
Removes test.fail from fileupload test and fix a small issue with a string assertion
[CORE-216]: https://rocketchat.atlassian.net/browse/CORE-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: remove test.fail from livechat fileupload

apps/meteor/ee/server/api/sessions.ts, apps/meteor/server/lib/resetUserE2EKey.ts, apps/meteor/server/modules/listeners/listeners.module.ts, apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/saml.spec.ts, ee/apps/ddp-streamer/src/Client.ts, ee/apps/ddp-streamer/src/DDPStreamer.ts, packages/core-services/src/events/Events.ts
Only counting on client to logout is a weak strategy, so now we are closing the connections properly on microservices
Introduced here: https://github.com/RocketChat/Rocket.Chat/pull/31958
[E2EE-10]
[E2EE-10]: https://rocketchat.atlassian.net/browse/E2EE-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Force logout live clients on E2EE keys reset changes

apps/meteor/app/oembed/server/providers.ts
Twitter/X links can be both twitter.com and/or x.com 
Rocket.Chat was only checking twitter.com to embed the post with our OEmbedProvider. 
I've fixed this by changing the regex responsible to do this match.
**Before:** 
**After:**
Since it's a `chore` and didn't create a test case for that, since it does not exist too
=> chore: including x.com hostname to Twitter oembed

.changeset/bump-patch-1714490920088.md, .changeset/yellow-lies-judge.md, apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx, apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx, apps/meteor/tests/e2e/administration.spec.ts, yarn.lock
- Apps-Engine: `^1.42.1`
*   ([#32315](https://github.com/RocketChat/Rocket.Chat/pull/32315) by [@dionisio-bot](https://github.com/dionisio-bot)) fixed Engagement Dashboard and Device Management admin pages loading indefinitely
*   @rocket.chat/core-typings@6.7.2
*   @rocket.chat/rest-typings@6.7.2
*   @rocket.chat/api-client@0.1.31
*   @rocket.chat/license@0.1.13
*   @rocket.chat/omnichannel-services@0.1.13
*   @rocket.chat/pdf-worker@0.0.37
*   @rocket.chat/presence@0.1.13
*   @rocket.chat/apps@0.0.4
*   @rocket.chat/core-services@0.3.13
*   @rocket.chat/cron@0.0.33
* …
=> Release 6.7.2

apps/meteor/app/file-upload/server/methods/sendFileMessage.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/threads.spec.ts
When the user uploads an image to a thread, it gets sent to the channel instead.
Introduced here: #32324
1. Open a channel
2. Send a message
3. Hover the message → Start a thread
4. Send a message inside the thread
5. Inside the thread, send an image
[CORE-421](https://rocketchat.atlassian.net/browse/CORE-421)
[CORE-421]: https://rocketchat.atlassian.net/browse/CORE-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Thread file upload

apps/meteor/app/api/server/v1/users.ts, apps/meteor/tests/end-to-end/api/01-users.js
- Improve permissions check on `users` endpoints by using the `permissionsRequired` property.
[CORE-349](https://rocketchat.atlassian.net/browse/CORE-349)
[CORE-349]: https://rocketchat.atlassian.net/browse/CORE-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on users endpoints

.changeset/plenty-turkeys-move.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
[rocketchat.atlassian.net/browse/CORE-401](https://rocketchat.atlassian.net/browse/CORE-401)
Fixes an issue with some apps that didn't implement executeViewCloseHandler. This causes opened modals to be open forever on UI. This is because when the UI attempts to close it, it calls the aforementioned handler, and since it didn't exist, apps engine errored out.
This returned an empty response to the UI, which ignored the response and continued to show the view.
=> fix: Modals opened by apps won't close when `executeViewCloseHandler` is not implemented

.github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml, docker-compose-ci.yml
We're slowly moving towards making `DISABLE_DB_WATCHERS=true` the default behavior, so the intent of this PR is to have tests running using the setting enabled so we can make sure we're covering all test cases while we migrate the code.
https://github.com/RocketChat/Rocket.Chat/pull/32403 needs to be merged first so the tests can pass.
[SCA-4]
[SCA-4]: https://rocketchat.atlassian.net/browse/SCA-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: add UI tests with DB watchers disabled

apps/meteor/tests/e2e/channel-management.spec.ts, apps/meteor/tests/e2e/messaging.spec.ts
Fixes the test: `should focus the latest message when moving the focus on the list and theres no previous focus`
=> test: Fix messaging flaky e2e test

apps/meteor/tests/end-to-end/api/04-direct-message.js
- Fix failing `im.messages.others` enpoint end-to-end test introduced by #32333
=> test: Fix `im.messages.others` endpoint end-to-end tests

apps/meteor/app/channel-settings/server/functions/saveRoomName.ts, apps/meteor/app/integrations/server/lib/triggerHandler.js, apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/incoming/deleteIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/outgoing/addOutgoingIntegration.ts, apps/meteor/app/integrations/server/methods/outgoing/deleteOutgoingIntegration.ts, apps/meteor/app/integrations/server/methods/outgoing/updateOutgoingIntegration.ts, apps/meteor/app/lib/server/functions/deleteUser.ts, apps/meteor/app/lib/server/lib/notifyListener.ts, apps/meteor/server/database/watchCollections.ts, apps/meteor/server/models/raw/Integrations.ts, packages/model-typings/src/models/IIntegrationsModel.ts
As per the updates mentioned in [PROJ-7](https://rocketchat.atlassian.net/browse/PROJ-7) [SCA-4] and [ADR #74](https://adr.rocket.chat/0074), **this pull request focuses on relocating Integration entity out of DB Watcher service.**
In essence, this modification empowers RocketChat's app to directly call listeners through the `api.broadcast` global function, eliminating the reliance on MongoDB Change Stream data propagation
Why is this beneficial? It provides better control over notifying users by enabling more precise use-case management. Unlike Change Streams, which notify every action on Mongo's documents and sometimes might result in unnecessary duplicate notifications. Moreover, it contributes to the future removal of the DB Watcher deployment, thereby optimizing resource utilization. …
=> refactor: Integration entity out of db watcher

.changeset/smooth-knives-turn.md, apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts, apps/meteor/app/utils/client/lib/SDKClient.ts, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-manual-selection-logout.spec.ts
It seems that by optimizing to avoid multiple subscriptions to the same stream, the listeners were not being removed when the subscription was canceled (due to factors like logout), thus remaining cached and never being executed again.
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/31345
[SUP-581]
[SUP-581]: https://rocketchat.atlassian.net/browse/SUP-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Re-login same browser tab issues

apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx, apps/meteor/client/views/teams/contextualBar/info/TeamsInfoWithData.js, apps/meteor/tests/e2e/retention-policy.spec.ts
=> regression: Incorrect retention policy banner's display rule for teams

apps/meteor/app/integrations/server/lib/updateHistory.ts, apps/meteor/app/integrations/server/methods/clearIntegrationHistory.ts, apps/meteor/app/integrations/server/methods/outgoing/deleteOutgoingIntegration.ts, apps/meteor/app/lib/server/lib/notifyListener.ts, apps/meteor/server/database/watchCollections.ts, apps/meteor/server/models/raw/IntegrationHistory.ts, packages/model-typings/src/models/IIntegrationHistoryModel.ts
As per the updates mentioned in [PROJ-7], [SCA-10] and [ADR #74], **this pull request focuses on relocating `IntegrationHistory` model out of DB Watcher service.**
This modification enhances RocketChat's app by allowing it to directly call listeners through the `api.broadcast` global function, bypassing the need for MongoDB Change Stream data propagation.
This change offers better control over user notifications via Web Sockets, enabling more precise management of use-cases. Instead of notifying every database change, we can now send an `api.broadcast` call only when necessary, reducing overall network messages. Additionally, this contributes to the future removal of the DB Watcher deployment, optimizing resource utilization.
Key changes include:
- Conditionally incorporating …
=> refactor: IntegrationHistory out of DB Watcher

apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx, apps/meteor/tests/e2e/retention-policy.spec.ts
Showing the retention policy section on edit room panel for users without permission are throwing error not allowing users editing room at all
[CORE-478]
[CORE-478]: https://rocketchat.atlassian.net/browse/CORE-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Hide prune section based on permission

apps/meteor/client/components/ImageGallery/ImageGallery.tsx
- Fixed image gallery  not working on Electron app due to the use of the `toReversed` js function (not supported in older "browers" such as in the Electron app)
- Decrease image gallery transition effect duration on pagination
[CORE-490](https://rocketchat.atlassian.net/browse/CORE-490)
Introduced by #32106
[CORE-490]: https://rocketchat.atlassian.net/browse/CORE-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Fixed image gallery not working on Electron app

apps/meteor/client/components/ImageGallery/ImageGallery.tsx
- Avoid animation on image gallery pagination transition (so that there's no "glitch" when loading new images)
Introduced by #32106
**Before:**
[before-transition.webm](https://github.com/RocketChat/Rocket.Chat/assets/36537004/749a924e-7a92-47e9-8857-bc96d05c8331)
**After:**
[after-transition.webm](https://github.com/RocketChat/Rocket.Chat/assets/36537004/f48097ef-66ad-4345-a4db-5cde1529cf36)
[CORE-492](https://rocketchat.atlassian.net/browse/CORE-492)
[CORE-492]: https://rocketchat.atlassian.net/browse/CORE-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Disable animation on image gallery pagination transition

.changeset/fuzzy-readers-bake.md, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-enterprise-menus-logout.spec.ts
Fixes issues with loading license modules when loading the page while logged out
Fixes `Error getting modules i {revert: undefined, silent: true}` error
[SUP-595]
[SUP-595]: https://rocketchat.atlassian.net/browse/SUP-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Run QueryClient.clear() on logout

.changeset/bump-patch-1718743154258.md, .changeset/dry-shoes-tap.md, .changeset/nervous-wolves-collect.md, apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsChooseLatest.ts, apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts, apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomInitialValues.ts, apps/meteor/jest.config.ts, apps/meteor/packages/rocketchat-version/plugin/compile-version.js, apps/meteor/tests/e2e/retention-policy.spec.ts, yarn.lock
- Apps-Engine: `1.42.2`
*   ([#32621](https://github.com/RocketChat/Rocket.Chat/pull/32621) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes the supported versions problem, where in most cases the data chosen was the oldest
*   ([#32622](https://github.com/RocketChat/Rocket.Chat/pull/32622) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes the issue not allowing users without edit-room-retention-policy permission try to edit the room with the retention policy enabled
*   @rocket.chat/core-typings@6.9.2
*   @rocket.chat/rest-typings@6.9.2
*   @rocket.chat/api-client@0.1.35
* …
=> Release 6.9.2

.changeset/hungry-waves-lick.md, apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
- This issue was causing the following end-to-end test case to fail: `settings-assets.spec.ts:19:6 › settings-assets › expect upload and delete logo asset and label should be visible` ;
Since the client used to incorrectly send the asset type as the filename, we couldn't succesfully extract the MIME type from the uploaded file. That is, when uploading a `jpeg` file as a `logo` asset, the client would use `logo` as the filename, which is mapped to the default `application/octet-stream` MIME type (that is not accepted for assets, so it throws an error).
This error started happening after the changes in #32471
=> fix: Client sends incorrect file name when uploading assets

yarn.lock
Implementation reference https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/769
The problem happens with apps that use the message events and tried to read the usernames from the message room via `message.room.usernames`. To test it, you can deploy any app that implements a message event (e.g. `IPostMessageSent`) and uses that same API
=> regression: Incorrect translation of room data on listeners of message events

.changeset/nasty-windows-reply.md, apps/meteor/client/components/message/content/attachments/QuoteAttachment.tsx, apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx, apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx, apps/meteor/client/views/admin/moderation/helpers/ContextMessage.tsx, apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessage.tsx
Moves the quotes to be on top of the message for better readability 
Closes https://github.com/RocketChat/feature-requests/issues/688
Closes https://github.com/RocketChat/feature-requests/issues/721
[CORE-501]
[CORE-501]: https://rocketchat.atlassian.net/browse/CORE-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Change Quote Position

.changeset/spotty-seals-whisper.md, apps/meteor/package.json, packages/uikit-playground/package.json, yarn.lock
[CORE-523]
[CORE-523]: https://rocketchat.atlassian.net/browse/CORE-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Upgrade `fuselage-toastbar` adding RTL support

apps/meteor/client/lib/convertTimeUnit.ts, apps/meteor/client/views/room/hooks/useRetentionPolicy.ts, apps/meteor/tests/e2e/retention-policy.spec.ts
=> regression: fix retention flaky test

apps/meteor/app/emoji/client/emojiParser.js, apps/meteor/app/markdown/lib/markdown.js, apps/meteor/app/markdown/lib/parser/filtered/filtered.js, apps/meteor/client/lib/utils/renderMessageEmoji.ts, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadTitle.tsx
This PR tightens some function signatures from functions that used to receive complete `IMessage` objects but now only operate on message's text content. The goal of it is to improve type-safety a little bit.
=> refactor: Widen types for message rendering helpers

apps/meteor/client/components/FilterByText.tsx, apps/meteor/client/views/omnichannel/managers/AddManager.tsx, apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts, apps/meteor/tests/e2e/page-objects/omnichannel-business-hours.ts, apps/meteor/tests/e2e/page-objects/omnichannel-custom-fields.ts, apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts, apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts, apps/meteor/tests/e2e/page-objects/omnichannel-monitors.ts, apps/meteor/tests/e2e/page-objects/omnichannel-sla-policies.ts, apps/meteor/tests/e2e/page-objects/omnichannel-tags.ts, apps/meteor/tests/e2e/page-objects/omnichannel-units.ts
=> test: improve selectors specificity

.changeset/rare-penguins-hope.md, apps/meteor/app/apps/server/bridges/livechat.ts, apps/meteor/app/apps/server/bridges/rooms.ts, apps/meteor/app/livechat/server/api/lib/livechat.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.ts, apps/meteor/lib/callbacks.ts, packages/core-typings/src/IRoom.ts
https://rocketchat.atlassian.net/browse/OPI-10
https://rocketchat.atlassian.net/browse/SUP-566
=> feat(apps-engine): add `customFields` on livechat creation

.changeset/bump-patch-1719457341149.md, .changeset/funny-snails-promise.md, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts, packages/livechat/src/components/Form/CustomFields/index.tsx, packages/livechat/src/components/Form/SelectInput/index.tsx, packages/livechat/src/lib/hooks.ts, packages/livechat/src/routes/Chat/container.js, packages/livechat/src/routes/Register/index.tsx, packages/livechat/src/store/index.tsx, yarn.lock
- Apps-Engine: `1.42.2`
*   ([#32683](https://github.com/RocketChat/Rocket.Chat/pull/32683) by [@dionisio-bot](https://github.com/dionisio-bot)) livechat `setDepartment` livechat api fixes:
*   Changing department didn't reflect on the registration form in real time
*   Changing the department mid conversation didn't transfer the chat
*   Depending on the state of the department, it couldn't be set as default
*   @rocket.chat/core-typings@6.9.3
*   @rocket.chat/rest-typings@6.9.3
*   @rocket.chat/api-client@0.1.36
*   @rocket.chat/license@0.1.18
*   @rocket.chat/omnichannel-services@0.1.18
* …
=> Release 6.9.3

yarn.lock
Updating the Apps-Engine with fixes for the following regressions:
- The new runtime was throwing errors that previously would be swallowed - https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/f54ca4e8536abe1b835468a9b58eb3798e6efda2
- The Notifier accessor was not correctly implemented in the Deno Runtime - https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/deeede9fd724f62fada753ac866037a0dac32cc6
=> regression: Notifier accessor proxy and not rethrowing internal JSON-RPC errors

apps/meteor/app/statistics/server/lib/getAppsStatistics.ts, yarn.lock
Added a try/catch to prevent errors and also memoized the function result since it should not change that often.
```
Error: Request "jdqmnf7icud" for method "app:getStatus" timed out
at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/runtime/deno/AppsEngineDenoRuntime.js:241:24)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/statistics/server/lib/getAppsStatistics.ts:33:16
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at …
```
=> regression: prevent unhandled exception from apps statistics

.changeset/witty-penguins-rush.md, apps/meteor/app/api/server/api.ts, apps/meteor/app/livechat/server/api/v1/message.ts, apps/meteor/app/livechat/server/methods/loadHistory.ts, apps/meteor/app/livechat/server/methods/loginByToken.ts, apps/meteor/app/slashcommands-inviteall/server/server.ts, apps/meteor/server/models/raw/Team.ts, apps/meteor/tests/data/api-data.js, apps/meteor/tests/end-to-end/api/01-users.js, apps/meteor/tests/end-to-end/api/16-commands.js, apps/meteor/tests/end-to-end/api/25-teams.js, apps/meteor/tests/end-to-end/api/livechat/20-messages.ts, apps/meteor/tests/end-to-end/api/livechat/methods/loadHistory.ts, apps/meteor/tests/end-to-end/api/livechat/methods/loginByToken.ts, yarn.lock
=> fix: imported fixes

apps/meteor/client/components/InfoPanel/RetentionPolicyCallout.spec.tsx, apps/meteor/client/components/InfoPanel/RetentionPolicyCallout.tsx, apps/meteor/client/components/withErrorBoundary.tsx, apps/meteor/client/hooks/usePruneWarningMessage.spec.ts, apps/meteor/client/views/room/body/RetentionPolicyWarning.spec.tsx, apps/meteor/client/views/room/body/RetentionPolicyWarning.tsx, apps/meteor/jest.config.ts, apps/meteor/tests/mocks/client/mockRetentionPolicySettings.ts, apps/meteor/tests/mocks/mockDate.ts
If the Advanced cron timer is invalid, the cron will not run, so the message was removed for this case.
[CORE-534](https://rocketchat.atlassian.net/browse/CORE-534)
[CORE-534]: https://rocketchat.atlassian.net/browse/CORE-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Room breaking if advanced cron timer is invalid

yarn.lock
- Limit timeout of "Pre" listener events to 1s - https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/775
- Preventing `ProxiedApp.call` from throwing all errors broke the handling of events that had a "check" counterpart (e.g. `checkPreMessageSentPrevent`) - https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/a1000ddc8eadc82772f82398b3d82f1fbbe3a339
- Remove unnecessary microtask from runtime controller - https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/d7224fd15d32f568751d487b908e365565aada64
=> regression: Apps-engine update batch

apps/meteor/client/components/CustomScrollbars/CustomScrollbars.tsx, apps/meteor/client/components/Page/PageScrollableContent.tsx
Introduced here: #32625
In order to fix the above issue related to the coded mirror we added back the `willChange` prop which caused the emoji picker to be opened on an undesired place.
This fix, removes this prop and adds a `translateZ` prop on the very first child of `CustomScrollbars` inside the `PageScrollableContent` which fixes the original issue and opens the emoji on the right place.
[CORE-530]
[CORE-530]: https://rocketchat.atlassian.net/browse/CORE-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: EmojiPicker not being displayed correctly

packages/ui-kit/jest.config.js, packages/ui-kit/package.json, packages/ui-kit/src/blocks/BlockElementType.spec.ts, packages/ui-kit/src/blocks/BlockElementType.ts, packages/ui-kit/src/blocks/LayoutBlock.spec.ts, packages/ui-kit/src/blocks/LayoutBlockType.spec.ts, packages/ui-kit/src/blocks/LayoutBlockType.ts, packages/ui-kit/src/blocks/TextObjectType.spec.ts, packages/ui-kit/src/blocks/TextObjectType.ts, packages/ui-kit/src/blocks/layout/PreviewBlock.ts, packages/ui-kit/src/jest-setup.ts, packages/ui-kit/tsconfig.cjs.json, packages/ui-kit/tsconfig.esm.json, packages/ui-kit/tsconfig.json
UIKit types are *not open for extension*, therefore we can't use `interface` declarations nor enjoy the advantage of the `extends` construct for them. This pull request add types for assert type shapes in compilation type.
=> refactor(ui-kit): Add tests for types

apps/meteor/app/lib/server/lib/notifyListener.ts
This refactor introduces a middleware function, `withDbWatcherCheck`, to handle the `dbWatchersDisabled` check uniformly across various notification functions. By applying this middleware, we ensure that the flag checks are consistently managed, reducing redundancy and potential errors.
The primary changes involve:
- Creation of the `withDbWatcherCheck` middleware to wrap notification functions.
- Direct export of each notification function with the `withDbWatcherCheck` wrapper applied.
=> refactor: create middleware to handle dbWatchersDisabled check

apps/meteor/app/livechat/server/hooks/sendToCRM.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/app/livechat/server/lib/RoutingManager.ts, apps/meteor/app/livechat/server/methods/takeInquiry.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTakeInquiry.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/autoCloseQueued.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts, apps/meteor/ee/app/livechat-enterprise/server/methods/resumeOnHold.ts, apps/meteor/lib/callbacks.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/services/omnichannel/queue.ts
[OPI-14](https://rocketchat.atlassian.net/browse/OPI-14)
https://rocketchat.atlassian.net/browse/CORE-440
[OPI-14]: https://rocketchat.atlassian.net/browse/OPI-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(omnichannel): `afterTakeInquiry` room as required param

apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts, apps/meteor/lib/callbacks.ts, apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts
Changing the order in which things happen can help avoid testing the same things multiple times.
Previously, we would test if the system had an agent online, then find who was online, and then assign once again. These actions end up being repetitive, making the system difficult to understand and consuming CPU.
We also avoid calling the same collection multiple times to update different fields on the same document, thus optimizing messages sent to the database.
Database operations( find/update) `GET http://localhost:3000/api/v1/livechat/room?token=${visitor.token}`
88 versus 76
With that, the order of events has changed a bit, but I believe it's not something problematic.
old:
```
run livechat.applyRoomRestrictions 
run livechat.onCheckRoomApiParams 
run livechat.checkDefaultAgentOnNewRoom …
```
=> refactor(omnichannel): spare few Room.find on requestRoom method

apps/meteor/app/apps/server/bridges/rooms.ts, apps/meteor/package.json, yarn.lock
=> chore: Bump apps engine 1.44-alpha

apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts
=> refactor(omnichannel): replace create and find by findAndUpdate

.changeset/afraid-guests-jog.md, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, packages/livechat/src/lib/hooks.ts, packages/livechat/src/widget.ts
[SUP-577]
Created a `transferChat` Livechat API endpoint for transferring chats programmatically, the endpoint has all the limitations & permissions required that transferring via UI has
[SUP-577]: https://rocketchat.atlassian.net/browse/SUP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Livechat): `transferChat` Livechat api endpoint

.changeset/selfish-emus-sing.md, apps/meteor/client/sidebar/hooks/useRoomList.ts, apps/meteor/server/settings/accounts.ts, apps/meteor/tests/end-to-end/api/miscellaneous.ts, packages/i18n/src/locales/en.i18n.json
[SIDE-81]
[SIDE-81]: https://rocketchat.atlassian.net/browse/SIDE-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add accounts setting to reorganize sections

apps/meteor/app/e2e/client/rocketchat.e2e.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-auto-onhold-chat-closing.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-auto-transfer-unanswered-chat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-changing-room-priority-and-sla.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-close-inquiry.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-avatar-visibility.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-department.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-fileupload.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-logo.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-tab-communication.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-watermark.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-manual-selection.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-tags.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-transfer-to-another-agents.spec.ts
=> test: close pages after page spec

apps/meteor/app/settings/server/SettingsRegistry.ts, apps/meteor/app/settings/server/functions/settings.mocks.ts, apps/meteor/tests/unit/app/settings/server/functions/settings.tests.ts
=> fix: incorrect cache set review

.changeset/large-vans-attack.md, apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx, apps/meteor/tests/e2e/threads.spec.ts
There's 2 ways to attach an event listener to a component, using react props (onClick, onKeyDown, etc) or directly to the node (using a callbackRef or getting the element directly from the dom). Attaching events using both ways changes how event propagation works due to react's synthetic event handlers.
The issue was resolved by adding the composer keydown event using a callbackRef instead of as a prop.
[CORE-529]
[CORE-529]: https://rocketchat.atlassian.net/browse/CORE-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Pressing esc whilst editing a message closes the contextual bar

apps/meteor/app/livechat/server/startup.ts, apps/meteor/client/meteorOverrides/login/saml.ts, apps/meteor/ee/server/startup/presence.ts, apps/meteor/server/hooks/sauMonitorHooks.ts
During the user deletion, if the user is logged in, the server will throw an error
=> chore: prevent destructuring _id of deleted users

apps/meteor/client/views/room/composer/hooks/useComposerBoxPopup.ts, apps/meteor/tests/e2e/message-composer.spec.ts
The way events were being attached changed and affected the popup and messagebox behaviour. When tagging or selecting another suggestion, it's currently filling the messagebox with the suggestion and sending the message at the same time.
This PR fixes this and adds tests to ensure this behaviour doesn't happen again.
Introduced here: #32861
=> regression: Messagebox sending message instead of just selecting popup suggestion

apps/meteor/app/models/client/models/Users.ts, apps/meteor/app/ui-cached-collection/client/models/CachedCollectionManager.ts, apps/meteor/client/startup/startup.ts, apps/meteor/client/views/root/SAMLLoginRoute.tsx, apps/meteor/tests/unit/client/views/root/SAMLLoginRoute.spec.tsx
After a change in Meteor (meteor 3.0.0), where `Accounts.callLoginMethod`  trusts that `Accounts.user.find`  is still there to call the login callbacks, it became clear that it is not healthy to rewrite internal framework objects.
...
...
But no one has proof that adding extra methods causes problems :)
=> chore(client): stop replacing  `Meteor.user`

apps/meteor/app/api/server/v1/users.ts, apps/meteor/server/lib/resetUserE2EKey.ts
=> regression: notify user properly on logout

apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/31118
=> test: fix flaky test `Archive department`

.changeset/brown-crabs-chew.md, apps/meteor/package.json, ee/packages/ui-theming/package.json, packages/fuselage-ui-kit/package.json, packages/gazzodown/package.json, packages/ui-avatar/package.json, packages/ui-client/package.json, packages/ui-composer/package.json, packages/ui-video-conf/package.json, packages/uikit-playground/package.json, yarn.lock
When there is not enough space for the menu popover to be placed above/below its trigger, it will overlap the trigger. This causes the popover to be immediately closed and whatever item is underneath the pointer will be selected.
The issue is caused by conflicting event handlers. This PR bumps the package `@rocket.chat/fuselage` with the necessary fix.
=> fix: `Menu` onPointerUp event behavior

apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts, apps/meteor/app/livechat/server/hooks/leadCapture.ts, apps/meteor/app/livechat/server/hooks/markRoomNotResponded.ts, apps/meteor/app/livechat/server/hooks/markRoomResponded.ts, apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts, apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts, apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.ts, apps/meteor/app/livechat/server/hooks/sendToCRM.ts, apps/meteor/app/livechat/server/index.ts, apps/meteor/app/livechat/server/sendMessageBySMS.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/scheduleAutoTransfer.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/setPredictedVisitorAbandonmentTime.ts, apps/meteor/lib/callbacks.ts
The idea is exactly that: a chore, to accommodate future code improvements in a less confusing way.
[OPI-9](https://rocketchat.atlassian.net/browse/OPI-9)
Basically, the event will only run for omnichannel rooms, making the code simpler and giving us more confidence.
[OPI-15]: https://rocketchat.atlassian.net/browse/OPI-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OPI-9]: https://rocketchat.atlassian.net/browse/OPI-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: create `afterOmnichannelSaveMessage`

apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
=> regression: fix dispatchInquiryPosition not being fired on room creation

apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts, apps/meteor/server/models/raw/LivechatRooms.ts, packages/core-typings/src/IRoom.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
As per [OPI-24](https://rocketchat.atlassian.net/browse/OPI-24), this PR modifies `saveAnalyticsData` hook to work with updater accumulator. This marks the initial implementation of the updater in practice. Additionally, this change will facilitate the integration of all `afterOmnichannelSaveMessage` calls into the accumulator in the near future.
Also related with #32948 and #32970.
[OPI-24]: https://rocketchat.atlassian.net/browse/OPI-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: saveAnalyticsData with accumulator

apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts, apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts, apps/meteor/lib/callbacks.ts, apps/meteor/server/models/raw/LivechatRooms.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
This pull request addresses the requirements of [OPI-12](https://rocketchat.atlassian.net/browse/OPI-12) by adding updater support to the `afterOmnichannelSaveMessage` hook - that aims to optimize performance by reducing database calls related to omnichannel rooms.
[OPI-12]: https://rocketchat.atlassian.net/browse/OPI-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: move afterOmnichannelSaveMessage hook to work with updater

apps/meteor/client/views/admin/settings/GroupPage.tsx, apps/meteor/client/views/admin/settings/GroupSelector.tsx, apps/meteor/client/views/admin/settings/SettingsRoute.tsx, apps/meteor/client/views/admin/settings/groups/AssetsGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/GenericGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/LDAPGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/OAuthGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/TabbedGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/VoipGroupPage.tsx, apps/meteor/tests/e2e/administration-settings.spec.ts, apps/meteor/tests/e2e/administration.spec.ts
This PR proposes to render the back button in `GroupPage` through `onClickBack` prop. It will allow to use this page outside the route without displaying the button that move back to the settings page
=> chore: Renders back button through prop in admin settings

.github/workflows/ci-test-e2e.yml
=> ci: only rebuild docker if event is pull request and is from outside

apps/meteor/app/livechat/server/hooks/markRoomResponded.ts, apps/meteor/server/models/raw/LivechatRooms.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
=> chore: create getVisitorActiveForPeriodUpdateQuery

apps/meteor/app/livechat/server/hooks/markRoomNotResponded.ts, apps/meteor/server/models/raw/LivechatRooms.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
This pull request addresses the requirements of [OPI-27](https://rocketchat.atlassian.net/browse/OPI-27) by adding updater support to the `afterOmnichannelSaveMessage.markRoomNotResponded` hook - that aims to optimize performance by reducing database calls related to omnichannel rooms.
[OPI-27]: https://rocketchat.atlassian.net/browse/OPI-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: create getNotResponseByRoomIdUpdateQuery method

apps/meteor/app/federation/server/endpoints/dispatch.js, apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts, apps/meteor/server/models/dummy/BaseDummy.ts, apps/meteor/server/models/raw/BaseRaw.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/Rooms.ts, packages/model-typings/src/models/IBaseModel.ts, packages/model-typings/src/models/IRoomsModel.ts
This pull request addresses the requirements of [OPI-26](https://rocketchat.atlassian.net/browse/OPI-26) by adding updater support to the `afterSaveMessage.notifyUsersOnMessage` hook - that aims to optimize performance by reducing database calls related to omnichannel rooms.
[OPI-26]: https://rocketchat.atlassian.net/browse/OPI-26
=> chore: add roomUpdater on notifyUsersOnMessage

packages/fuselage-ui-kit/src/blocks/InputBlock.tsx, packages/fuselage-ui-kit/src/elements/ChannelsSelectElement/ChannelsSelectElement.tsx, packages/fuselage-ui-kit/src/elements/ChannelsSelectElement/MultiChannelsSelectElement.tsx, packages/fuselage-ui-kit/src/elements/MultiStaticSelectElement.tsx, packages/fuselage-ui-kit/src/elements/StaticSelectElement.tsx, packages/fuselage-ui-kit/src/elements/UsersSelectElement/MultiUsersSelectElement.tsx, packages/fuselage-ui-kit/src/elements/UsersSelectElement/UsersSelectElement.tsx, packages/fuselage-ui-kit/src/surfaces/createSurfaceRenderer.tsx, packages/gazzodown/src/elements/Timestamp/ErrorBoundary.tsx, packages/ui-client/src/components/CustomFieldsForm.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx, packages/uikit-playground/src/Components/FlowContainer/FlowContainer.tsx, packages/uikit-playground/src/Components/SurfaceSelect/SurfaceSelect.tsx, packages/web-ui-registration/src/components/LoginSwitchLanguageFooter.tsx
It ensures some function parameters are properly typed instead of implicitly resolved with the `any` type.
This issues were discovered by bumping `@types/react` and `@types/react-dom` in a PoC. Changing them in advance will ease the upgrade to React 18.
=> refactor: Cover implicit `any` types

apps/meteor/app/federation/server/endpoints/dispatch.js, apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts, apps/meteor/app/livechat/server/hooks/afterSaveOmnichannelMessage.ts, apps/meteor/server/models/dummy/BaseDummy.ts, apps/meteor/server/models/raw/BaseRaw.ts, packages/model-typings/src/models/IBaseModel.ts, packages/model-typings/src/updater.ts, packages/models/src/updater.spec.ts, packages/models/src/updater.ts
following the decisions described in the adr https://adr.rocket.chat/0099
https://rocketchat.atlassian.net/browse/OPI-20
=> chore: remove `persists` from updater

.changeset/large-geese-ring.md, apps/meteor/app/theme/client/imports/general/base_old.css, apps/meteor/client/views/room/body/RetentionPolicyWarning.tsx, apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/RoomBodyV2.tsx
[CORE-576]
[CORE-576]: https://rocketchat.atlassian.net/browse/CORE-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Replaces outdated retention policy warning in favor of `Bubble`

apps/meteor/server/routes/avatar/middlewares/auth.js, apps/meteor/server/settings/accounts.ts
As part of a security by default approach, we should deny unauthenticated access to avatars by default. This PR changes the default value from `false` to `true`.
EDIT: in order to properly handle anonymous access, instead of returning `403` and `Forbidden`, this PR alters the logic to return an avatar with the user / room initials.
N/A
N/A
N/A
=> chore: change 'Accounts_AvatarBlockUnauthenticatedAccess' default value from false to true

.changeset/chilled-boats-sip.md, apps/meteor/app/api/server/v1/channels.ts, apps/meteor/app/api/server/v1/groups.ts, apps/meteor/app/api/server/v1/im.ts, apps/meteor/app/api/server/v1/rooms.ts, apps/meteor/app/api/server/v1/teams.ts, apps/meteor/server/lib/eraseRoom.ts, apps/meteor/server/methods/eraseRoom.ts, apps/meteor/server/methods/index.ts
This PR removes the eraseRoom to use the room.delete endpoint
[CORE-350](https://rocketchat.atlassian.net/browse/CORE-350)
[CORE-350]: https://rocketchat.atlassian.net/browse/CORE-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated meteor eraseRoom method

.changeset/gold-knives-sparkle.md, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v306.ts
Introduced here: #32485
While introducing this new possibility in retention policy overriding feature, old channels were not being affected, because it was missing the `ignoreThreads` parameter. So we decide to add a migration to add the missing parameter in all channels with retention policy override. 
Closes #32794
[CORE-613]
[CORE-613]: https://rocketchat.atlassian.net/browse/CORE-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Missing retention's `ignoreThreads` param for old channels

.changeset/tiny-rice-train.md, apps/meteor/app/api/server/v1/chat.ts, apps/meteor/client/lib/lists/ThreadsList.ts, apps/meteor/client/views/room/contextualBar/Threads/ThreadList.tsx, apps/meteor/tests/end-to-end/api/chat.ts, packages/rest-typings/src/v1/chat.ts
- Remove `meteor/check` from `chat` endpoints by using the `validateParams` property.
[CORE-316](https://rocketchat.atlassian.net/browse/CORE-316)
**The intention for this PR is to improve code readability and make invalid params errors more standardized. No side effects are expected. We're considering this a breaking change since invalid params errors are being changed to follow the same standard when possible.**
[CORE-316]: https://rocketchat.atlassian.net/browse/CORE-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove `meteor/check` from `chat` endpoints

packages/core-services/src/index.ts
Starting from https://github.com/RocketChat/Rocket.Chat/pull/32589 there is no way to run local but still using the "old" MongoDB change streams, with this change you'll be able to set `DISABLE_DB_WATCHERS=no` and have the old behavior. 
The defaults haven't changed though:
- In production it still uses MongoDB change streams by default (you should set `DISABLE_DB_WATCHERS=yes` to disable change streams)
- In local environment DB watchers are disabled by default
=> chore: allow using db watchers in localhost

apps/meteor/client/providers/VoiceCallProvider/VoiceCallProvider.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/index.ts, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCall.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallAPI.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallClient.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallDialer.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallEffect.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallEvent.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallSession.tsx, apps/meteor/client/providers/VoiceCallProvider/hooks/useVoiceCallState.tsx, apps/meteor/client/providers/VoiceCallProvider/index.ts
This PR adds the mais React hooks used by the UI for voice calls. Each hook has it's own responsibility and informations is extracted from the `VoIPClient`. 
Here's a description of each hook and it's responsibilities:
Provides information is regards to the state of the `VoIPClient` and `VoiceCallSession`. Ex.: `isReady`, `isRegistered`, `isError`, `isIncoming`, `isOngoing`, `isOutgoing` 
Provides access to `VoIPClient` actions not necessarily related to the current `VoiceCallSession`. Ex.: `register`, `unregister`, `transferCall`, `makeCall`, `endCall`.
Provides access to the state and actions available for the established voice call. 
A `VoiceCallSession` can be `INCOMING`, `ONGOING`, `OUTGOING` and `ERROR`. Each session type provides a group of methods (Ex.: `mute`; `hold`) and …
=> feat: VoIP freeswitch UI hooks

.changeset/kind-drinks-joke.md, apps/meteor/client/components/MarkdownText.tsx
Reverts RocketChat/Rocket.Chat#32574 from community since there are some scenarios where it is making channels to break where the MarkdownComponent is used.
Task: [SUP-537](https://rocketchat.atlassian.net/browse/SUP-537) [CORE-651](https://rocketchat.atlassian.net/browse/CORE-651)
[SUP-537]: https://rocketchat.atlassian.net/browse/SUP-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-651]: https://rocketchat.atlassian.net/browse/CORE-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "fix: Inconsistent Markdown Formatting in Custom Status Field"

apps/meteor/client/startup/accounts.ts
Meteor recently developed a way to choose the client storage location between local storage and session storage.
We recently started configuring meteor to choose between both location options based on our setting `Accounts_ForgetUserSessionOnWindowClose`.
There was a small issue, we are handling these updates in a `Tracker.autorun` which runs everytime any dependency changes. In this case, it wasn't handling this setting change on a live user session.
We shouldn't change the client storage location in the middle of an active session, so this PR fixes it by stopping the autorun and which stops the listening of live setting update, essentially just configuring the client storage location just once in a session.
[CORE-653](https://rocketchat.atlassian.net/browse/CORE-653)
[CORE-653]: …
=> regression: Handle live setting forget user session on window close update

apps/meteor/client/views/teams/contextualBar/channels/TeamsChannels.tsx, apps/meteor/client/views/teams/contextualBar/info/TeamsInfo.tsx, apps/meteor/tests/e2e/channel-management.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-channels.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/home-channel.ts, apps/meteor/tests/e2e/retention-policy.spec.ts, apps/meteor/tests/e2e/team-management.spec.ts
=> test: Add e2e tests for teams multi-step modals

apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.js, apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.stories.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterRow.js
Reverts RocketChat/Rocket.Chat#33166
=> Revert "refactor: Realtime Monitoring Counters to TS"

.changeset/wise-avocados-taste.md, apps/meteor/client/components/GenericModal/GenericModal.tsx, apps/meteor/client/components/GenericModal/GenericModalSkeleton.tsx, apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptsModal.tsx, apps/meteor/client/views/teams/ConvertToChannelModal/ConvertToChannelModal.tsx, apps/meteor/client/views/teams/contextualBar/info/DeleteTeam/DeleteTeamModalWithRooms.tsx, apps/meteor/client/views/teams/contextualBar/info/LeaveTeam/LeaveTeamWithData.tsx, apps/meteor/client/views/teams/contextualBar/members/RemoveUsersModal/RemoveUsersModal.js, apps/meteor/tests/e2e/team-management.spec.ts
Introduced here: #32482
With the introduction of the `onClose` call in the `useEffect` cleanup function in `GenericModal`, multi-step modals using `GenericModal` started to close unexpectedly. This PR aims to remove the usage of the `GenericModal` in favor of `GenericModalSkeleton` to solve this issue and keep the loading consistency. 
[CORE-660]
[CORE-660]: https://rocketchat.atlassian.net/browse/CORE-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Multi-step modals closing unexpectedly

.changeset/smart-baboons-allow.md, apps/meteor/app/file-upload/server/lib/FileUpload.ts, apps/meteor/tests/end-to-end/api/rooms.ts
- Assure encrypted files use the generic `application/octet-stream` media type before validating it
Introduced by #33003
#33003 has caused RC (server side) to throw an error when an encrypted file is uploaded without the generic `application/octet-stream` media type. Our mobile app uploads encrypted files using their original media type, so the server would always block file uploads in this case
[CORE-666](https://rocketchat.atlassian.net/browse/CORE-666)
[CORE-666]: https://rocketchat.atlassian.net/browse/CORE-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Encrypted file upload throws an error on mobile

apps/meteor/server/startup/cloudRegistration.ts
This PR addresses a specific issue where the `no broker set to broadcast: watch.settings` error would occur for certain users, particularly during the dry run initialization of the development environment.
It's important to note that while this fix resolves this particular error, similar issues could arise in other parts of the code. These will need to be addressed in future updates as they are identified.
=> chore: remove notifyListener call that was causing startup issues

.changeset/brown-singers-appear.md, apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx, packages/i18n/src/locales/en.i18n.json, packages/ui-client/src/hooks/useFeaturePreviewList.ts
[SIDE-148](https://rocketchat.atlassian.net/browse/SIDE-148)
This PR prepares the feature preview configuration for the sidepanel navigation
- add `sidepanelNavigation` to feature preview list
- for now, this feature should not appear on the list, so it's set to `enabled: false` 
[SIDE-148]: https://rocketchat.atlassian.net/browse/SIDE-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add `sidepanelNavigation` to Feature preview list

.changeset/tame-mayflies-press.md, apps/meteor/app/apps/server/bridges/bridges.js, apps/meteor/app/apps/server/bridges/email.ts, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
Implement a new bridge that allow apps to send email using the SMTP server configured for the RC application.
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/790
[SCI-50](https://rocketchat.atlassian.net/browse/SCI-50)
[SCI-50]: https://rocketchat.atlassian.net/browse/SCI-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: email bridge

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-queue-management.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts
This task adds pending e2e tests for the Queue Management on Omnichannel.
Qase:
[RC-2937 - Verify that the Waiting Queue message is correctly displayed when there are users waiting.](https://app.qase.io/case/RC-2937)
[RC-2939 - Verify that the Waiting Queue message is updated when a user joins the queue.](https://app.qase.io/case/RC-2939)
[RC-2940 - Verify that the Waiting Queue message is updated when a user leaves the queue.](https://app.qase.io/case/RC-2940)
Relates to:
[CORE-661](https://rocketchat.atlassian.net/browse/CORE-661)
[CORE-661]: https://rocketchat.atlassian.net/browse/CORE-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: create tests for omnichannel queue management

.changeset/cool-actors-sin.md, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
The results should be the same but the pipeline structure is better for consuming less memory between stages.
Although the commits don't show it, I have added a few test cases for the endpoints that uses the query. I have then ran the tests against the old query and the new query.
=> chore: improve omni queue metrics query

.changeset/bump-patch-1724077277110.md, .changeset/gentle-bugs-think.md, .changeset/orange-clocks-wait.md, .changeset/strong-rings-rush.md, .changeset/two-bikes-crash.md, .changeset/wise-avocados-taste.md, apps/meteor/app/lib/server/functions/getModifiedHttpHeaders.ts, apps/meteor/app/lib/server/lib/debug.js, apps/meteor/app/livechat/server/api/v1/room.ts, apps/meteor/app/livechat/server/api/v1/visitor.ts, apps/meteor/app/livechat/server/hooks/processRoomAbandonment.ts, apps/meteor/client/components/GenericModal/GenericModal.tsx, apps/meteor/client/components/GenericModal/GenericModalSkeleton.tsx, apps/meteor/client/omnichannel/units/UnitEdit.tsx, apps/meteor/client/startup/accounts.ts, apps/meteor/client/views/omnichannel/realTimeMonitoring/RealTimeMonitoringPage.js, apps/meteor/client/views/room/modals/ReadReceiptsModal/ReadReceiptsModal.tsx, apps/meteor/client/views/teams/ConvertToChannelModal/ConvertToChannelModal.tsx, apps/meteor/client/views/teams/contextualBar/info/DeleteTeam/DeleteTeamModalWithRooms.tsx, apps/meteor/client/views/teams/contextualBar/info/LeaveTeam/LeaveTeamWithData.tsx, apps/meteor/client/views/teams/contextualBar/members/RemoveUsersModal/RemoveUsersModal.js, apps/meteor/definition/externals/meteor/accounts-base.d.ts, apps/meteor/tests/e2e/account-forgetSessionOnWindowClose.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-units.ts, apps/meteor/tests/end-to-end/api/miscellaneous.ts, apps/meteor/tests/unit/app/lib/server/functions/getModifiedHttpHeaders.tests.ts, packages/ui-client/src/components/TooltipComponent.tsx, yarn.lock
- Apps-Engine: `1.44.0`
*   ([#33084](https://github.com/RocketChat/Rocket.Chat/pull/33084) by [@dionisio-bot](https://github.com/dionisio-bot)) Prevent `processRoomAbandonment` callback from erroring out when a room was inactive during a day Business Hours was not configured for.
*   ([#33153](https://github.com/RocketChat/Rocket.Chat/pull/33153) by [@dionisio-bot](https://github.com/dionisio-bot)) Security Hotfix (https://docs.rocket.chat/docs/security-fixes-and-updates)
*   ([#33185](https://github.com/RocketChat/Rocket.Chat/pull/33185) by [@dionisio-bot](https://github.com/dionisio-bot)) Restored tooltips to the unit edit department field selected …
=> Release 6.11.2

.changeset/rich-toes-bow.md, apps/meteor/client/hooks/useAppUiKitInteraction.ts
debugging the meteor migration https://github.com/RocketChat/Rocket.Chat/pull/31438 I found some cases where this subscription happens multiple times, just because the callback function changes
=> fix: prevent uiInteraction to invalidate multiple times

.changeset/rotten-rabbits-brush.md, apps/meteor/app/autotranslate/server/autotranslate.ts, apps/meteor/app/integrations/server/triggers.ts, apps/meteor/app/irc/server/irc-bridge/index.js, apps/meteor/ee/server/lib/engagementDashboard/startup.ts
After upgrading from Rocket.Chat version 6.9.0 to 6.12.0, outgoing integrations stopped functioning. The root cause was traced to a change in the parameter order passed by the `afterSendMessage` callback to the `sendMessage` event from the integrations app triggers. Specifically, the room parameter was not forwarded correctly, resulting in errors when searching for outgoing webhook triggers.
This issue was introduced by [PR #33034](https://github.com/RocketChat/Rocket.Chat/pull/33034), which modified the `afterSaveMessage` parameter signature but did not update the corresponding integration logic.
As outlined in [SUP-665](https://rocketchat.atlassian.net/browse/SUP-665), this malfunction blocked the propagation of certain actions due to the callback failing to forward the correct …
=> fix: correct parameter order in afterSaveMessage to restore outgoing webhooks and related features

apps/meteor/app/lib/server/functions/isTheLastMessage.ts, apps/meteor/server/services/messages/hooks/BeforeFederationActions.ts, apps/meteor/server/services/messages/service.ts, packages/core-services/src/types/IMessageService.ts
- Removes the need of a full IRoom object on `beforeReaction` callbacks
- Updates the types of `isLastMessage` to accept a room with only `lastMessage` prop instead of full room object
Separated from #32994
=> chore: Update typings on callbacks to accept less than a full room object

.changeset/strong-grapes-brake.md, apps/meteor/app/utils/client/getUserAvatarURL.ts, apps/meteor/app/utils/server/getUserAvatarURL.ts, apps/meteor/client/providers/AvatarUrlProvider.tsx, apps/meteor/server/routes/avatar/user.js
It removes remaining direct references to external user avatar URLs, mainly correcting the behavior of E2E encryption messages and desktop notifications.
Also fixed the priority for external provider URL. Before #32824 all avatars fetches when the external url was configured would point directly to the external URL. With the changes made in the aforementioned PR we started proxying those request through Rocket.Chat's server, but the local (uploaded by the user to rocket.chat directly) avatars were having priority over the external provider.
https://github.com/RocketChat/Rocket.Chat/pull/32824#issuecomment-2352407114
It needs to be applied to 6.12.x too.
[CORE-692](https://rocketchat.atlassian.net/browse/CORE-692)
[CORE-692]: https://rocketchat.atlassian.net/browse/CORE-692?atlOrigin=eyJpIj …
=> fix: Local avatars prioritized over external avatar provider and remove remnant references on client of `Accounts_AvatarExternalProviderUrl`

.changeset/witty-lemons-type.md, apps/meteor/app/api/server/v1/rooms.ts, apps/meteor/client/components/FeaturePreviewSidePanelNavigation.tsx, apps/meteor/client/hooks/useRoomInfoEndpoint.ts, apps/meteor/client/hooks/useSidePanelNavigation.ts, apps/meteor/client/lib/RoomManager.ts, apps/meteor/client/sidebarv2/header/CreateTeamModal.tsx, apps/meteor/client/sidebarv2/header/SearchSection.tsx, apps/meteor/client/views/room/RoomOpener.tsx, apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx, apps/meteor/client/views/room/Sidepanel/RoomSidepanelListWrapper.tsx, apps/meteor/client/views/room/Sidepanel/RoomSidepanelLoading.tsx, apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx, apps/meteor/client/views/room/Sidepanel/SidepanelItem/index.ts, apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx, apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts, apps/meteor/client/views/room/Sidepanel/index.ts, apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx, apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/useEditRoomInitialValues.ts, apps/meteor/client/views/room/layout/RoomLayout.tsx, apps/meteor/client/views/room/providers/RoomProvider.tsx, apps/meteor/lib/publishFields.ts, apps/meteor/server/services/team/service.ts, packages/core-typings/src/IRoom.ts, packages/i18n/src/locales/en.i18n.json, packages/rest-typings/src/v1/rooms.ts, packages/ui-client/src/components/FeaturePreview/FeaturePreview.tsx, packages/ui-client/src/hooks/useFeaturePreviewList.ts
=> feat: `RoomSidepanel`

.github/workflows/release-candidate.yml
=> ci: auto candidate releases

.changeset/sweet-nails-grin.md, apps/meteor/client/components/MarkdownText.spec.tsx, apps/meteor/client/components/MarkdownText.tsx
This PR solves an inconsistency between the markdown parser used in the composer and the parser used in the rest of the application that was causing different outputs in both sides when using bold and italics. 
- Added some tests for different markdown elements.
[https://rocketchat.atlassian.net/browse/SUP-537](https://rocketchat.atlassian.net/browse/SUP-537)
related to https://github.com/RocketChat/Rocket.Chat/pull/32574
Closes https://github.com/RocketChat/Rocket.Chat/issues/32544
Closes https://github.com/RocketChat/Rocket.Chat/issues/32081
=> fix: markdown inconsistency with bold and italics

apps/meteor/package.json, apps/uikit-playground/package.json, ee/packages/ui-theming/package.json, packages/fuselage-ui-kit/package.json, packages/gazzodown/package.json, packages/ui-avatar/package.json, packages/ui-client/package.json, packages/ui-composer/package.json, packages/ui-video-conf/package.json, yarn.lock
=> regression: `Sidepanel` color highlight 

apps/meteor/app/e2e/client/rocketchat.e2e.ts, apps/meteor/app/ui-master/server/scripts.ts, apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts, apps/meteor/app/ui-utils/server/Message.ts, apps/meteor/app/utils/client/lib/RestApiClient.ts, apps/meteor/client/meteorOverrides/login/saml.ts, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/client/startup/accounts.ts, apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx, apps/meteor/definition/externals/meteor/accounts-base.d.ts
Backported from https://github.com/RocketChat/Rocket.Chat/pull/31438
We noticed that the workarounds we implemented to allow forget session become unstable in newer versions of Meteor, so this refactor improves usability and prevents future issues.
=> chore: replace Meteor._localStorage -> Accounts.storageLocation

packages/release-action/action.yml
Uses node20 for release action
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> ci: use node20 for release action

.changeset/heavy-carrots-reflect.md, apps/meteor/client/views/marketplace/AppInstallPage.tsx, apps/meteor/client/views/marketplace/hooks/useInstallApp.tsx, apps/meteor/ee/server/apps/communication/rest.ts, packages/rest-typings/src/apps/index.ts
Removes a deprecated method of uploading apps using URLs 
[PASLR-8](https://rocketchat.atlassian.net/browse/PASLR-8)
[PASLR-8]: https://rocketchat.atlassian.net/browse/PASLR-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove deprecated URL App installation

apps/meteor/client/views/room/Sidepanel/RoomSidepanel.tsx, apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx, apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts
=> chore(Sidepanel): uses only local channels and discussions

.changeset/eighty-items-behave.md, apps/meteor/ee/server/startup/apps/trialExpiration.ts
- Apply CE restriction regarding private  apps on license removal, and not only on server restart.
**Demo:**
[demo-downgrade-apps.webm](https://github.com/user-attachments/assets/4edbc2e8-198e-41f5-9112-c4591dd7fb1a)
[PASLR-5](https://rocketchat.atlassian.net/browse/PASLR-5)
[PASLR-24](https://rocketchat.atlassian.net/browse/PASLR-24)
[PASLR-5]: https://rocketchat.atlassian.net/browse/PASLR-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Private apps restrictions are not applied on license removal

.changeset/eighty-items-behave.md, apps/meteor/ee/server/startup/apps/trialExpiration.ts
Reverts RocketChat/Rocket.Chat#33400 due to a a business rule change decision
=> Revert "fix: Private apps restrictions are not applied on license removal"

apps/meteor/client/components/UrlChangeModal.tsx, apps/meteor/client/views/setupWizard/SetupWizardRoute.tsx
It fixes two distinct issues:
- the translation keys are not correctly referenced if the `<ModalRegion />` is under `<SetupWizardProvider />` i.e. at the Setup Wizard pages;
- the `Do_you_want_to_change_to_s_question` translation's positional parameters were not handled by i18next.
=> regression: Broken translation in `UrlChangeModal` at setup wizard

packages/ui-voip/src/components/VoipPopup/views/VoipOngoingView.spec.tsx
`Jest.useFakeTimers()` was added to guarantee the UI information for `VoipOngoingPopup` is consistent. This change prevents the test from failing sporadically if the call timer changes while the test is running.
=> test: fake timers to prevent voip unit tests failing sporadically

.changeset/selfish-experts-develop.md, apps/meteor/ee/server/apps/communication/websockets.ts, apps/meteor/server/services/apps-engine/service.ts, apps/meteor/tests/e2e/apps/private-apps-upload.spec.ts, apps/meteor/tests/e2e/page-objects/marketplace.ts, packages/apps-engine/src/server/AppManager.ts
- Stop auto-enabling private apps when they are updated. Instead, only try to startup the updated app (and consequently, auto-enable it) when it was already in an enabled status before the update.
Go to **Marketplace > Private apps** and try updating a disabled private app in CE (eg by uploading its file once again).
**Current behavior:** the updated app will be enabled after the update, regardless of any condition.
**Expected behavior:** the app should only be enabled if it was already enabled before the update (so that license restriction are also followed accordingly)
[PASLR-25](https://rocketchat.atlassian.net/browse/PASLR-25)
[PASLR-25]: https://rocketchat.atlassian.net/browse/PASLR-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix!: Private apps are always auto enabled when updated

packages/ui-voip/src/providers/VoipProvider.tsx
Users should now be warned when trying to leave or reloading the page during calls.
[VOIP-98](https://rocketchat.atlassian.net/browse/VOIP-98)
- Open the application
- Configure Voip for team collab and user extension
- Start a call
- Try to leave or reload page
[VOIP-98]: https://rocketchat.atlassian.net/browse/VOIP-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: page warning before leave/reload while a call is ongoing

packages/ui-client/src/components/GenericMenu/GenericMenu.tsx
[SIDE-206](https://rocketchat.atlassian.net/browse/SIDE-206)
`className` and `button` props were not being forwarded inside `GenericMenu`
bug was introduced on #33007 on [this commit](https://github.com/RocketChat/Rocket.Chat/pull/33007/commits/74913754e0b8d018907851c8477cdfa9e8f44e31)
[SIDE-206]: https://rocketchat.atlassian.net/browse/SIDE-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: add `GenericMenu` missing props

apps/meteor/ee/server/settings/voip.ts, packages/i18n/src/locales/en.i18n.json, packages/i18n/src/locales/pt-BR.i18n.json
Added a beta disclaimer to the 'Team voice calls (VoIP)' settings page.
N/A
- Access the workspace
- Go to workspace > settings > Team voice calls (VoIP)
- Disclaimer should be visible
[VOIP-110](https://rocketchat.atlassian.net/browse/VOIP-110)
[VOIP-110]: https://rocketchat.atlassian.net/browse/VOIP-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added beta disclaimer to voip settings

apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessagesList.tsx, apps/meteor/client/views/omnichannel/contactHistory/MessageList/useHistoryMessageList.ts, apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx
=> chore: Adds reactivity to contact history message list

.changeset/sixty-vans-grab.md, apps/meteor/app/api/server/v1/oauthapps.ts, apps/meteor/ee/server/configuration/ldap.ts, apps/meteor/package.json, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v308.ts, yarn.lock
- Validate LDAP sync intervals before setting up their corresponding cron jobs;
- Use LDAP sync interval setting's `packageValue`s as the fallback value in case the provided value is invalid;
- Add a migration to update LDAP sync interval setting's `packageValue`s (from cron description to actual cron expressions, which is the type of value expected by RC since 6.3).
Go to **Settings > LDAP > Premium** and set an invalid Avatar Background Sync Interval or Auto Logout Interval.
**Current behavior:** cron jobs are triggered successively (there is no interval between them).
**Expected behavior:** cron jobs intervals should follow each setting's default value instead.
[CORE-273](https://rocketchat.atlassian.net/browse/CORE-273)
[CORE-273]: …
=> fix!: LDAP sync triggers multiple cron jobs in case an invalid sync interval is provided

packages/ui-voip/src/hooks/useVoipClient.tsx
Fixes voip endpoints being called even when the voip feature was disabled in the workspace settings.
=> regression: unable to disable voip client query

.changeset/fair-bees-wash.md, apps/meteor/app/api/server/v1/misc.ts, apps/meteor/tests/end-to-end/api/miscellaneous.ts, packages/rest-typings/src/v1/misc.ts
Removed deprecated endpoint `pw.getPolicyReset`. Moving forward, use the `pw.getPolicy` endpoint.
[CORE-395](https://rocketchat.atlassian.net/browse/CORE-395)
[CORE-395]: https://rocketchat.atlassian.net/browse/CORE-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated endpoint pw.getPolicyReset

packages/ui-voip/src/providers/VoipProvider.tsx
Fixes a mistake causing the `beforeunload` event listener to be added on useEffect clean up instead of being removed as intended.
=> regression: voip beforeunload listener being added instead of removed

apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/hooks/useUserMenu.tsx, apps/meteor/client/NavBarV2/NavBarSettingsToolbar/UserMenu/hooks/useVoipItemsSection.tsx, apps/meteor/client/sidebar/header/hooks/useUserMenu.tsx, apps/meteor/client/sidebar/header/hooks/useVoipItemsSection.tsx
This PR fixes an empty section being displayed in the user menu when voip is disabled.
=> regression: disabled voip leaves empty section in the user menu

apps/meteor/app/e2e/client/rocketchat.e2e.room.js
This forces the user to set the E2EE key for its own subscription before starting the process of propagating the key to other users, which will avoid users providing keys to themselves. 
https://rocketchat.atlassian.net/browse/E2EE2-80
=> chore: Set own group key when creating an E2EE group

.changeset/soft-planets-cross.md, apps/meteor/app/e2e/client/rocketchat.e2e.room.js
- Checks that `room.u._id` is the same as the user requesting. Currently anyone invited to the room can set the roomKeyID (and the E2EE key) before the owner gets the key, which can cause race conditions and leave the room in a bad state.
- 
https://rocketchat.atlassian.net/browse/E2EE2-79
=> fix!: Only room creator can set the E2EE room key for the first time

apps/meteor/client/views/omnichannel/directory/chats/useChatsQuery.ts
It fixes an incorrect else statement that's preventing to filter the agents properly in order to get livechat rooms
=> chore: Get livechat rooms rooms properly on chats table

packages/i18n/src/index.mjs
`rmdirSync` is soon to be deprecated
=> chore: Use `rmSync` instead of `rmdirSync`

.changeset/rare-hats-lie.md, apps/meteor/server/settings/e2e.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v311.ts, apps/meteor/tests/e2e/e2e-encryption.spec.ts
Change the default value of `E2E_Enabled_Mentions` to true to always accept mentions in E2EE messages
https://rocketchat.atlassian.net/browse/E2EE2-71
=> chore!: e2ee mention setting update

apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v311.ts
Complement to #30914 for next major version
=> chore: migration to remove redundant indexes

apps/meteor/app/e2e/client/rocketchat.e2e.ts
=> fix: Remove decryption step from E2EE and leave it only on room's ready event

apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx, apps/meteor/client/views/omnichannel/directory/contacts/hooks/useCurrentContacts.ts
=> feat: Get contacts from `contacts.search` endpoint

packages/livechat/package.json, packages/message-parser/package.json, yarn.lock
=> chore: Replace `webpack` with `webpack-cli` in npm scripts

apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx
This pull request addresses [CORE-729](https://rocketchat.atlassian.net/browse/CORE-729) and it's parent [CORE-718](https://rocketchat.atlassian.net/browse/CORE-718) by removing the query param `fields` sent to `/v1/livechat/users/manager` endpoint.
[CORE-729]: https://rocketchat.atlassian.net/browse/CORE-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-718]: https://rocketchat.atlassian.net/browse/CORE-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: make ManagersTable component stop to use fields query param

apps/meteor/package.json, yarn.lock
=> chore: replace esl fork targeted at node14 with the regular esl package

.changeset/modern-trees-draw.md, apps/meteor/app/lib/server/functions/checkUrlForSsrf.ts
The regex in the `isValidDomain` function doesn't take hyphens into consideration. This PR changes the regex in order to fix it and accept them.
https://github.com/RocketChat/Rocket.Chat/issues/33584
N/A
N/A
=> fix: alter the regex in the isValidDomain function to accept hyphens

apps/meteor/app/api/server/helpers/parseJsonQuery.ts, apps/meteor/app/api/server/v1/custom-user-status.ts, apps/meteor/client/views/admin/customUserStatus/CustomUserStatusFormWithData.tsx, apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusTable.tsx, apps/meteor/tests/end-to-end/api/custom-user-status.ts, packages/rest-typings/src/index.ts, packages/rest-typings/src/v1/customUserStatus.ts
This pull request addresses [CORE-721](https://rocketchat.atlassian.net/browse/CORE-721) by updating the `/api/v1/custom-user-status.list` endpoint.
- The `name` and `_id` attributes have been moved out of the query parameter and are now placed directly at the root of the query parameters.
- For backward compatibility, the query parameter will still be supported when the environment variable `ALLOW_UNSAFE_QUERY_AND_FIELDS_API_PARAMS` is set, but this should only be used in exceptional cases, not as part of the standard usage.
[CORE-721]: https://rocketchat.atlassian.net/browse/CORE-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: make custom user status pages stop to use query param

.changeset/swift-penguins-help.md, apps/meteor/server/settings/e2e.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v314.ts
We introduced a new E2EE settings with 6.x release - `E2E_Allow_Unencrypted_Messages`. Earlier their default value was kept in a way to not change the default behavior.
We decided to change this default behavior in the major 7.0.0 release and now by default users shouldn't be allowed to send un-encrypted messages in encrypted rooms.
[E2EE2-69](https://rocketchat.atlassian.net/browse/E2EE2-69)
[E2EE2-69]: https://rocketchat.atlassian.net/browse/E2EE2-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Update default E2EE settings behavior

apps/meteor/app/api/server/helpers/parseJsonQuery.ts, apps/meteor/app/api/server/v1/misc.ts, apps/meteor/client/views/directory/hooks/useDirectoryQuery.ts, apps/meteor/tests/end-to-end/api/miscellaneous.ts, packages/rest-typings/src/v1/directory.ts
This pull request addresses [CORE-724](https://rocketchat.atlassian.net/browse/CORE-724) by updating the `/api/v1/directory` endpoint.
- The `text`, `type`, and `workspace` attributes have been moved out of the query parameter and are now placed directly at the root of the query parameters.
- For backward compatibility, the query parameter will still be supported when the environment variable `ALLOW_UNSAFE_QUERY_AND_FIELDS_API_PARAMS` is set, but this should only be used for exceptional cases and not as part of the standard usage.
[CORE-724]: https://rocketchat.atlassian.net/browse/CORE-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: make get directory stop to use query param

apps/meteor/app/api/server/helpers/parseJsonQuery.ts, apps/meteor/app/api/server/v1/custom-sounds.ts, apps/meteor/client/views/admin/customSounds/CustomSoundsTable/CustomSoundsTable.tsx, apps/meteor/tests/end-to-end/api/custom-sounds.ts, packages/rest-typings/src/index.ts, packages/rest-typings/src/v1/customSounds.ts, packages/rest-typings/src/v1/voip.ts
This pull request addresses [CORE-719](https://rocketchat.atlassian.net/browse/CORE-719) by updating the `/api/v1/custom-sounds.list` endpoint.
- The `name` attribute has been moved out of the query parameter and is now placed directly at the root of the query parameters.
- For backward compatibility, the query parameter will still be supported when the environment variable `ALLOW_UNSAFE_QUERY_AND_FIELDS_API_PARAMS` is set, but this should be reserved for exceptional cases, not standard usage.
[CORE-718]: https://rocketchat.atlassian.net/browse/CORE-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-719]: https://rocketchat.atlassian.net/browse/CORE-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> chore!: make custom sounds page stop to use query param

apps/meteor/app/e2e/client/rocketchat.e2e.room.js
This makes the new UI a bit more forgiving with older clients.
=> fix: Try to decrypt even if keyIDs don't match

.changeset/shiny-falcons-vanish.md, apps/meteor/app/importer/server/classes/converters/UserConverter.ts, apps/meteor/server/lib/ldap/Manager.ts, apps/meteor/server/settings/ldap.ts, packages/core-typings/src/import/IImportUser.ts, packages/i18n/src/locales/en.i18n.json
[VOIP-36](https://rocketchat.atlassian.net/browse/VOIP-36)
[VOIP-36]: https://rocketchat.atlassian.net/browse/VOIP-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add setting to map an ldap attribute to the user's voice extension

.changeset/real-plants-mix.md, apps/meteor/client/views/room/E2EESetup/RoomE2EESetup.tsx
Added the check for displaying the RoomBody from feature preview to E2EE rooms
https://rocketchat.atlassian.net/browse/E2EE2-86
=> fix: E2EE not rendering new navigation feature preview

.changeset/khaki-boxes-suffer.md, apps/meteor/client/sidebarv2/RoomList/RoomList.tsx, apps/meteor/client/sidebarv2/hooks/useCollapsedGroups.ts, apps/meteor/client/sidebarv2/hooks/useRoomList.ts, apps/meteor/package.json, apps/uikit-playground/package.json, ee/packages/ui-theming/package.json, packages/fuselage-ui-kit/package.json, packages/gazzodown/package.json, packages/ui-avatar/package.json, packages/ui-client/package.json, packages/ui-composer/package.json, packages/ui-video-conf/package.json, packages/ui-voip/package.json, yarn.lock
[SIDE-178](https://rocketchat.atlassian.net/browse/SIDE-178)
- add collapsible groups to sidebar 
- save to localStorage collapsed groups - keeps state after reload
[SIDE-178]: https://rocketchat.atlassian.net/browse/SIDE-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: collapse sidebar groups

apps/meteor/ee/server/models/startup.ts, apps/meteor/server/models/WorkspaceCredentials.ts, apps/meteor/server/models/raw/WorkspaceCredentials.ts, apps/meteor/server/models/startup.ts
Migration 316 breaks community edition, the migration tries to use some models which are only present in EE, which crashes the server.
Fixing it by moving the required models to CE
=> regression: Move WorkspaceCredentials models to CE

.changeset/five-suns-tickle.md, apps/meteor/client/sidebarv2/header/SearchList.tsx, apps/meteor/client/sidebarv2/header/SearchSection.tsx, packages/i18n/src/locales/en.i18n.json
[SIDE-175](https://rocketchat.atlassian.net/browse/SIDE-175)
[SIDE-175]: https://rocketchat.atlassian.net/browse/SIDE-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: show Recent chats on the new sidebar

.changeset/perfect-wolves-impress.md, apps/meteor/app/api/server/helpers/parseJsonQuery.ts, apps/meteor/app/api/server/v1/emoji-custom.ts, apps/meteor/client/views/admin/customEmoji/EditCustomEmojiWithData.tsx, apps/meteor/tests/end-to-end/api/emoji-custom.ts, packages/rest-typings/src/v1/emojiCustom.ts
=> chore!: remove query field on custom emojis listing

apps/meteor/app/api/server/helpers/parseJsonQuery.ts
As per  [CORE-748](https://rocketchat.atlassian.net/browse/CORE-748), due to the removal of the query parameters, the mobile app is not able to retrieve settings from the workspace. This prevents users to log into the app. 
The three endpoints below were adapted so they can deliver the information required by the mobile app (with 'query' param attribute):
- settings.public
- directory
- channels.messages | groups.messages | dm.messages | im.messages
[CORE-748]: https://rocketchat.atlassian.net/browse/CORE-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: allow specific routes to receive query attr

.changeset/fuzzy-pans-share.md, apps/meteor/app/apps/server/bridges/livechat.ts, apps/meteor/app/apps/server/converters/visitors.js, apps/meteor/app/livechat/imports/server/rest/sms.ts, apps/meteor/app/livechat/imports/server/rest/upload.ts, apps/meteor/app/livechat/server/api/lib/livechat.ts, apps/meteor/app/livechat/server/api/v1/message.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/livechat/server/methods/sendMessageLivechat.ts, apps/meteor/app/livechat/server/sendMessageBySMS.ts, apps/meteor/ee/server/apps/communication/uikit.ts, apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts, apps/meteor/server/models/raw/LivechatVisitors.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts, apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts, packages/apps/src/converters/IAppVisitorsConverter.ts, packages/core-typings/src/ILivechatVisitor.ts, packages/model-typings/src/models/ILivechatVisitorsModel.ts
This reverts #33569 (which will only be kept in the feature branch and should not be included in 7.0 without the remaining parts of the SCI feature)
=> regression: Revert changes that restrict livechat visitors to their source type scope

apps/meteor/ee/server/sdk/index.ts, apps/meteor/server/services/authorization/canAccessRoomLivechat.ts, apps/meteor/server/services/authorization/canAccessRoomVoip.ts, apps/meteor/tests/mocks/server/BrokerMocked.ts, ee/packages/network-broker/src/NetworkBroker.ts, ee/packages/omnichannel-services/src/QueueWorker.ts, packages/core-services/src/LocalBroker.ts, packages/core-services/src/index.ts, packages/core-services/src/lib/Api.ts, packages/core-services/src/lib/proxify.ts, packages/core-services/src/types/IApiService.ts, packages/core-services/src/types/IBroker.ts
The usage of `proxifyWithWait` was not as good as intended. The idea was to add a delay in case a service was not yet initialized, but in fact this should by accomplished by adding a dependency between services, just like every service depends on the `license` service, so a service won't be initiated before the other one is there.
In case a service was not spun up at all adding a 10s delay had no effect since the call would fail nonetheless.
=> chore: remove `proxifyWithWait` and `waitAndCall`

apps/meteor/client/sidebarv2/RoomList/RoomList.tsx, apps/meteor/client/sidebarv2/RoomList/useSidebarListNavigation.ts, apps/meteor/client/sidebarv2/hooks/useCollapsedGroups.ts
[SIDE-217](https://rocketchat.atlassian.net/browse/SIDE-217)
- add keys (`Enter` and `Space`) to `handleKeyDown` on groups collapser
- add verifier `isCollapseGroup` to  `useSidebarListNavigation` 
[SIDE-217]: https://rocketchat.atlassian.net/browse/SIDE-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix Sidebar collapsers keyboard navigation

apps/meteor/client/sidebarv2/hooks/useRoomList.ts
[SIDE-222](https://rocketchat.atlassian.net/browse/SIDE-222)
- add missing `hideUnreadStatus`
[SIDE-222]: https://rocketchat.atlassian.net/browse/SIDE-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: room with `hideUnreadStatus` showing on unread list

.changeset/smart-radios-reflect.md, apps/meteor/app/livechat/server/lib/RoutingManager.ts, apps/meteor/app/livechat/server/startup.ts, apps/meteor/server/services/omnichannel/service.ts, packages/core-services/src/types/IOmnichannelService.ts
[ARCH-1307](https://rocketchat.atlassian.net/browse/ARCH-1307)
backport from https://github.com/RocketChat/Rocket.Chat/pull/33596
running microservices very often you will find `cannot call shouldStart from undefined` or something pretty close.
the reason is because we are calling `getQueueWorker` from a proxy and the return undefined.
dont ask me why its working fine on CI, but locally it fails 100% local
[ARCH-1307]: https://rocketchat.atlassian.net/browse/ARCH-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(omnichannel): stop calling an object through proxy

apps/meteor/.docker/Dockerfile.debian
=> chore: npm install as rocketchat user

apps/meteor/client/views/account/security/EndToEnd.tsx, apps/meteor/client/views/room/E2EESetup/RoomE2EESetup.tsx
Due to Meteor recently added [Account session storage](https://docs.meteor.com/api/accounts.html#accounts-session-storage) and the setting `Accounts_ForgetUserSessionOnWindowClose`, when enabled Meteor uses the session storage instead of local storage.
This was added in: https://github.com/RocketChat/Rocket.Chat/pull/33356
The solution is to use the method `Accounts.storageLocation` to get the storage location
https://rocketchat.atlassian.net/browse/E2EE2-90
=> regression: Fix meteor dynamic storage for E2EE client

packages/core-services/src/LocalBroker.ts
Adds OPTL instrumentation on LocalBroker as per [OPI-48](https://rocketchat.atlassian.net/browse/OPI-48).
[OPI-48]: https://rocketchat.atlassian.net/browse/OPI-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: add tracing instrumentation on LocalBroker

apps/meteor/client/views/omnichannel/contactInfo/EditContactInfo.tsx
[SCI-126]
[SCI-126]: https://rocketchat.atlassian.net/browse/SCI-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Add multiple fields validation

apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
changes the `sendMessage` locator on omnichannel to avoid it catching other elements that have the characters `send` like in this case
=> test: fix flaky omnichannel send

apps/meteor/client/views/setupWizard/SetupWizardRoute.tsx, apps/meteor/client/views/setupWizard/steps/AdminInfoStep.tsx, apps/meteor/client/views/setupWizard/steps/CloudAccountConfirmation.tsx, apps/meteor/client/views/setupWizard/steps/OrganizationInfoStep.tsx, apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx, yarn.lock
It fixes missing translations in Setup Wizard's forms.
It wraps the `<I18nextProvider />` element with the `onboarding` namespace only around `@rocket.chat/onboarding-ui` elements, leaving the `useTranslation()` calls outside still consuming the `core` namespace of translations.
=> regression(i18n): Broken translations in Setup Wizard

.changeset/pretty-ladybugs-sneeze.md, apps/meteor/app/authentication/server/startup/index.js, apps/meteor/app/ui-cached-collection/client/models/CachedCollection.ts, apps/meteor/client/startup/startup.ts, ee/apps/ddp-streamer/src/DDPStreamer.ts, ee/apps/ddp-streamer/src/configureServer.ts
=> fix: prevent loading page on reconnect

apps/meteor/tests/e2e/administration.spec.ts
Sometimes when the room information was closing, the tests tried to open a new room information sidebar, but since the one before was closing, nothing happened. This adds an assertion to wait for the sidebar to be properly closed
https://rocketchat.atlassian.net/browse/FLAKY-1090
=> test: fix flaky `should mark target default channel as "favorite by default"` test

.changeset/eleven-chefs-grin.md, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/VoipRoom.ts
[OPI-41]
[OPI-41]: https://rocketchat.atlassian.net/browse/OPI-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: add indexes for servedBy

packages/tracing/src/index.ts
Adds `BatchSpanProcessor` to improve the efficiency of span transportation.
> The batch processor accepts spans, metrics, or logs and places them into batches. Batching helps better compress the data and reduce the number of outgoing connections required to transmit the data. [Source](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md#batch-processor)
=> chore: add batch span processor

.changeset/shaggy-timers-warn.md, apps/meteor/app/api/server/v1/settings.ts, apps/meteor/tests/end-to-end/api/settings.ts, packages/rest-typings/src/v1/settings.ts
Per [CORE-765](https://rocketchat.atlassian.net/browse/CORE-765), this update shifts the `_id` query parameter directly to the root level in **GET** `/api/v1/settings.public` and removes the query attribute.
- `_id` can now be passed directly at the root level and supports a comma-separated list of setting IDs (e.g., `_id=Site_Url` or `_id=Site_Url,LDAP_Enable`).
- The query attribute is removed, aligning with the new structure outlined in [CORE-718](https://rocketchat.atlassian.net/browse/CORE-718).
- For continued query use, set the `ALLOW_UNSAFE_QUERY_AND_FIELDS_API_PARAMS` environment variable to `true` when initializing the server.
- [CORE-765](https://rocketchat.atlassian.net/browse/CORE-765) and [CORE-764](https://rocketchat.atlassian.net/browse/CORE-764)
**Note to Mobile Team** – …
=> regression: remove query field on settings public listing

.changeset/clean-flies-collect.md, apps/meteor/app/lib/server/functions/notifications/index.ts, apps/meteor/app/lib/server/functions/notifications/messageContainsHighlight.ts, apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts, apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts, apps/meteor/tests/unit/app/lib/server/functions/notifications/messageContainsHighlight.tests.ts
created some unit tests to illustrate what was the issue with the previous code
=> fix: user highlights matching just part of words

.changeset/quiet-jokes-add.md, apps/meteor/app/api/server/v1/channels.ts, apps/meteor/tests/data/chat.helper.ts, apps/meteor/tests/end-to-end/api/channels.ts, packages/rest-typings/src/v1/channels/ChannelsMessagesProps.ts
Per [CORE-767](https://rocketchat.atlassian.net/browse/CORE-767), this update shifts the `mentions._id`, `starred._id`, and `pinned` query parameters directly to the root level in **GET** `/api/v1/channels.messages` and removes the query attribute.
- `mentions._id` should now be passed as `mentionIds` directly at the root level and supports a comma-separated list of setting IDs (e.g., `mentionIds=foo` or `mentionIds=foo,bar`).
- `starred._id` should now be passed as `starredIds` directly at the root level and supports a comma-separated list of setting IDs (e.g., `starredIds=foo` or `starredIds=foo,bar`).
- `pinned` should now be passed directly at the root level as a boolean or string. 
- The query attribute is removed, aligning with the new structure outlined in …
=> regression: remove query field on messages listing

apps/meteor/app/livechat/server/lib/contacts/ContactMerger.ts, apps/meteor/app/livechat/server/lib/contacts/updateContact.ts, apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ContactInfo.tsx, apps/meteor/ee/server/patches/verifyContactChannel.ts, packages/apps-engine/src/definition/livechat/ILivechatContact.ts, packages/core-typings/src/ILivechatContact.ts
Fixes the problem where the info used to verify a contact was case sensitive, resulting in a contact not being merged for similar contacts with different string cases.
(e.g. `johndoe@example.com`was not merged with `JOHNDOE@EXAMPLE.COM`)
[SCI-116]
[SCI-116]: https://rocketchat.atlassian.net/browse/SCI-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: contact not merging for same email

apps/meteor/tests/e2e/feature-preview.spec.ts, apps/meteor/tests/e2e/page-objects/account-profile.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/fragments/index.ts, apps/meteor/tests/e2e/page-objects/fragments/navbar.ts, apps/meteor/tests/e2e/page-objects/home-channel.ts
[SIDE-219](https://rocketchat.atlassian.net/browse/SIDE-219)
[SIDE-218](https://rocketchat.atlassian.net/browse/SIDE-218)
- tests for the features added on #33489 and #33592 
[SIDE-219]: https://rocketchat.atlassian.net/browse/SIDE-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE-218]: https://rocketchat.atlassian.net/browse/SIDE-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: add `feature-preview` tests for `Enhanced navigation`

apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
[ARCH-1308](https://rocketchat.atlassian.net/browse/ARCH-1308)
after the first run:
I can conclude we have a few unhandled cases under development which is bad :s
[ARCH-1308]: https://rocketchat.atlassian.net/browse/ARCH-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: exit if unhandledRejection during `TEST_MODE`

apps/meteor/packages/meteor-run-as-user/lib/collection.overwrites.js, apps/meteor/packages/meteor-run-as-user/package.js
There is an issue in the latest mongo release that broke some minimongo queries. When removing or updating multiple local records with a query that matches using operators ($in, $eq, etc) it would match only the first record and then bailout.
This was noticed because the `bulkMessageDelete` stream would not remove all messages provided in the query.
[CORE-786](https://rocketchat.atlassian.net/browse/CORE-786)
[CORE-786]: https://rocketchat.atlassian.net/browse/CORE-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Minimongo queries with operator matching only first found _id

apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
This PR changes the `getQueuedChat` selector to be exact. This prevents tests failing by selecting the incorrect room with similar name.
[FLAKY-515](https://rocketchat.atlassian.net/browse/FLAKY-515)
- Create a conversation for `user1` with a visitor named "Connie Willians" _(example name)_
- Run the test with a visitor named "Connie"
- Playwright will find "Connie Willians" instead of "Connie"
- Test will fail
[FLAKY-515]: https://rocketchat.atlassian.net/browse/FLAKY-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: fix flaky e2e test omnichannel-takeChat

apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
Subsequent tests were not waiting for the sidebar to close, this could cause some operations to be realised in a previous sidebar that was about to close
[FLAKY-579](https://rocketchat.atlassian.net/browse/FLAKY-579)
[FLAKY-579]: https://rocketchat.atlassian.net/browse/FLAKY-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: fix flaky omnichannel-units tests

apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx, apps/meteor/client/sidebarv2/hooks/useUnreadDisplay.spec.tsx, apps/meteor/client/sidebarv2/hooks/useUnreadDisplay.ts, apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx, apps/meteor/lib/getSubscriptionUnreadData.ts
refactor the way unread titles and variants are handled so `useUnreadDisplay`  can be reused when unread counter is implemented on the sidebar collapse group.
=> chore: refactor sidebar unread handler

apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/app/livechat/server/lib/contacts/createContactFromVisitor.ts, apps/meteor/app/livechat/server/lib/contacts/migrateVisitorToContactId.ts, apps/meteor/app/livechat/server/lib/contacts/updateContact.ts, apps/meteor/ee/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/tests/end-to-end/api/livechat/contacts.ts, apps/meteor/tests/unit/app/livechat/server/lib/migrateVisitorToContactId.spec.ts, apps/meteor/tests/unit/app/livechat/server/lib/updateContact.spec.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
[SCI-114](https://rocketchat.atlassian.net/browse/SCI-114)
[SCI-114]: https://rocketchat.atlassian.net/browse/SCI-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use contact's name on as omnichannel rooms' display name

.changeset/light-terms-ring.md, apps/meteor/server/services/team/service.ts
This PR addresses the issue described in [CORE-800](https://rocketchat.atlassian.net/browse/CORE-800) where newly created teams are mistakenly displayed as channels in the sidebar when the DISABLE_DB_WATCHERS environment variable is enabled.
https://github.com/user-attachments/assets/97852c44-846c-493b-ac44-b7805b5dd6fc
- [CORE-800](https://rocketchat.atlassian.net/browse/CORE-800)
- Set `DISABLE_DB_WATCHERS` to `true`.
- Create a new team – it will initially appear as a channel.
- Refresh the page – the team should now display correctly as a team.
[CORE-800]: https://rocketchat.atlassian.net/browse/CORE-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-800]: https://rocketchat.atlassian.net/browse/CORE-800?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> fix: newly created teams displayed as channels in sidebar with DISABLE_DB_WATCHERS enabled

.changeset/sweet-needles-melt.md, apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx, apps/meteor/client/sidebarv2/hooks/useRoomList.ts
There's an edge case where a room with thread unread is not being added to the unread group because `alert` is false. 
This PR adds `tunread` to the condition of adding the room to `unread` list
=> fix: Thread unread not in unread group

apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx, apps/meteor/client/sidebarv2/hooks/useRoomList.ts
- fix: unread condition for `tunread` needs to check for its length, otherwise it will be truthy and will keep the room on unread group
- add test case
=> regression: fix not removing room from unread group

.changeset/tricky-trees-destroy.md, apps/meteor/app/irc/server/methods/resetIrcConnection.ts
backport from https://github.com/RocketChat/Rocket.Chat/pull/33935
=> fix: `resetIrcConnection` not requiring user logged

apps/meteor/app/livechat/server/lib/contacts/ContactMerger.ts, apps/meteor/server/models/raw/LivechatContacts.ts, packages/core-typings/src/ILivechatContact.ts
=> chore: improve indexes of the livechat contacts collection

apps/meteor/app/api/server/definition.ts, apps/meteor/app/importer/server/classes/converters/UserConverter.ts, apps/meteor/app/livechat/server/lib/localTypes.ts, apps/meteor/app/push/server/push.ts, apps/meteor/app/statistics/server/lib/getAppsStatistics.ts, apps/meteor/client/apps/@types/IOrchestrator.ts, apps/meteor/client/contexts/ImageGalleryContext.ts, apps/meteor/client/lib/cachedCollections/CachedCollection.ts, apps/meteor/client/lib/minimongo/types.ts, apps/meteor/client/views/admin/mailer/MailerPage.tsx, apps/meteor/client/views/admin/subscription/components/InfoTextIconModal.tsx, apps/meteor/client/views/admin/subscription/components/UsagePieGraph.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx, apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx, apps/meteor/client/views/room/contexts/UserCardContext.ts, apps/meteor/client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.tsx
It removes type declarations and type exports that became obsolete and forgetten in the codebase.
It was extracted from to simplify review.
=> chore: Drop unused type declarations and type exports

apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts, apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
- Add missing `lastChat` property to contact channel on visitor migration
[SCI-182]
[SCI-182]: https://rocketchat.atlassian.net/browse/SCI-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `lastChat` property missing on contact channel migrated from visitor

apps/meteor/app/livechat/server/lib/contacts/createContact.ts, apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts, apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
- Skip custom fields validation on contact migration (since it has already been applied when mapping a visitor to a contact). Keeping this validation causes RC to throw an error in case the legacy visitor doesn't contain a field that is now required (which is unintended for this specific flow).
On visitor to contact migration, we shouldn't throw errors in any of these cases:
- A custom field has been made required after updating to 7.1;
- A custom field has been removed after updating to 7.1;
#34030 has only partially fixed this issue (the second item has been addressed, but not the first one). In order to not throw errors on visitor to contact migration, we should skip the whole repeated validation process so that missing required fields do not generate an error.
[SCI-179]
[SCI-179]: …
=> regression: Do not throw an error when a required custom field is missing on visitor to contact migration

apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
Backport of changes to increase stability of subprocesses under load. Changes have been made on the Core monorepo but need to be published via the old Apps-Engine repo as this version of Rocket.Chat did not include it.
Apps-Engine branch ref: https://github.com/RocketChat/Rocket.Chat.Apps-engine/commits/release/1.43.3-candidate
Original PRs:
- https://github.com/RocketChat/Rocket.Chat/pull/33997
- https://github.com/RocketChat/Rocket.Chat/pull/33690
=> fix: Apps-engine subprocess handling

apps/meteor/server/models/raw/Avatars.ts, apps/meteor/server/models/raw/BaseUploadModel.ts
As per [ARCH-1393](https://rocketchat.atlassian.net/browse/ARCH-1393), this PR resolves the [issue](https://github.com/RocketChat/Rocket.Chat/issues/34132) where a duplicate index key error was triggered on application startup starting with Rocket.Chat 7.1.0.
After investigation, it was identified that the userId index was defined twice on the `rocketchat_user_data_files` collection:
- Initially defined in the `UserDataFiles` model
- Since version 7.1.0 within the `BaseUpload` model, which `UserDataFiles` extends - https://github.com/RocketChat/Rocket.Chat/pull/33214
This duplication caused index creation conflicts when the application started.
To fix that, we removed the `userId` index specification from `BaseUpload`, ensuring that it is only defined in the `UserDataFiles` model.
- …
=> fix: remove redundant index specs in UserDataFile inherited from BaseUpload

apps/meteor/ee/server/local-services/voip-freeswitch/service.ts, apps/meteor/ee/server/startup/services.ts, apps/meteor/tests/unit/server/lib/freeswitch.tests.ts
=> chore: Stop injecting settings' getter on FreeSwitch service

.changeset/violet-pets-attend.md, apps/meteor/client/views/account/featurePreview/AccountFeaturePreviewPage.tsx, packages/ui-client/src/hooks/useFeaturePreviewList.ts
- `AccountFeaturePreviewPage.tsx` was sending the whole feature on save payload - it should be only `name` and `value`
- it's necessary then to overwrite these values from DB with the default values so it can be changed without a migration
This fix is needed to allow changing the rules of `enableQuery` that is currently depending on the value of a feature that is going to be official (Enhanced navigation)
=> fix: `featuresPreview` wrong DB structure

.changeset/blue-items-raise.md, .changeset/gold-comics-taste.md, .changeset/proud-planets-applaud.md, apps/meteor/app/statistics/server/lib/getAppsStatistics.ts, packages/apps-engine/deno-runtime/deno.lock, packages/apps-engine/deno-runtime/lib/metricsCollector.ts, packages/apps-engine/deno-runtime/lib/parseArgs.ts, packages/apps-engine/deno-runtime/main.ts, packages/apps-engine/src/server/AppManager.ts, packages/apps-engine/src/server/ProxiedApp.ts, packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts, packages/apps-engine/src/server/runtime/deno/LivenessManager.ts
- Fix wrong stats for total apps failed metric
- Prevent error being thrown if request to app:getStatus fails
=> fix(apps): runtime orchestration fixes 

apps/meteor/app/livechat/server/api/v1/contact.ts, apps/meteor/tests/end-to-end/api/livechat/contacts.ts, packages/rest-typings/src/v1/omnichannel.ts
=> regression: not use visitor prop for omnichannel endpoint

apps/meteor/app/lib/server/methods/sendMessage.ts, apps/meteor/client/components/message/MessageHeader.tsx, apps/meteor/tests/end-to-end/api/methods.ts, packages/core-typings/src/IMessage/IMessage.ts
Change the validation of the `bot` field to make it compatible with our js.SDK: https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/master/src/lib/message.ts#L17
=> fix: validation on bot field used by js.sdk

apps/meteor/app/api/server/v1/roles.ts, apps/meteor/app/authorization/server/methods/addUserToRole.ts, apps/meteor/app/authorization/server/methods/removeUserFromRole.ts, apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts, apps/meteor/app/lib/server/functions/relinquishRoomOwnerships.ts, apps/meteor/server/lib/roles/addUserRoles.ts, apps/meteor/server/lib/roles/removeUserFromRoles.ts, apps/meteor/server/methods/afterVerifyEmail.ts, apps/meteor/server/models/raw/Roles.ts, packages/model-typings/src/models/IRolesModel.ts
Moved business logic out of the Roles model to proper functions. This will also remove the dependency of `notifyListener` from the Roles model.
Extracted from #34154
[ARCH-1356]
=> refactor: Move add and remove role code out of Roles model

apps/meteor/server/models/raw/FederationRoomEvents.ts
Use hardcoded queries instead of relying on `contextDefinitions` which is an external dependency since they're known from the context of the rooms model. This is also from a deprecated implementation of federation, so this code should be removed anytime soon.
=> refactor: remove deps from FederationRoomEvents model

apps/meteor/server/models/raw/Messages.ts, packages/core-typings/src/IMessage/IMessage.ts
=> refactor: remove deps from Messages model

.changeset/twelve-pumas-behave.md, apps/meteor/.mocharc.js, apps/meteor/app/file-upload/server/lib/FileUpload.spec.ts, apps/meteor/app/file-upload/server/lib/FileUpload.ts, apps/meteor/tests/mocks/data.ts
- Use `files` (array) field from messages instead of deprecated `file` field when checking all uploads related to a message that should be deleted with it.
Upload an image in a room, then delete the whole room.
**Expected behavior:** all uploads related to the uploaded image should be deleted after the room is deleted. Check the `rocketchat_uploads` collection to make sure both documents related to the image have been deleted (the image itself and the thumbnail).
**Current behavior:** the image itself is deleted, but RC keeps the thumbnail in the `rocketchat_uploads` collection and in the selected storage type.
[SUP-715]
[SUP-715]: https://rocketchat.atlassian.net/browse/SUP-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Thumbnails are not deleted on room deletion

apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts, apps/meteor/client/views/room/RoomOpenerEmbedded.tsx, apps/meteor/client/views/room/hooks/useOpenRoom.ts
[CORE-907](https://rocketchat.atlassian.net/browse/CORE-907)
[CORE-907]: https://rocketchat.atlassian.net/browse/CORE-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: DMs not working properly in embedded layout

apps/meteor/client/apps/gameCenter/GameCenterList.tsx, apps/meteor/client/providers/CallProvider/CallProvider.tsx, apps/meteor/client/sidebar/header/hooks/useCreateRoomModal.tsx, apps/meteor/client/sidebarv2/header/hooks/useCreateRoomModal.tsx, apps/meteor/client/views/account/profile/AccountProfilePage.tsx, apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx, apps/meteor/client/views/admin/customSounds/EditSound.tsx, apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx, apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx, apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeModeratorAction.tsx, apps/meteor/client/views/room/hooks/useUserInfoActions/actions/useChangeOwnerAction.tsx
=> refactor: Correct call of `setModal`

.changeset/silent-numbers-love.md, .changeset/silent-numbers-love2.md, .changeset/silent-numbers-love3.md, .changeset/silent-numbers-love4.md, .changeset/silent-numbers-love5.md, .changeset/silent-numbers-love6.md, .changeset/silent-numbers-love7.md, .changeset/silent-numbers-love8.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
Backport of several fixes in the Apps-Engine.
Fixes published with Apps-Engine patch version 1.43.5 https://github.com/RocketChat/Rocket.Chat.Apps-engine/releases/tag/v1.43.5
The changes as listed on the Apps-Engine release:
- fix: app subprocess restart on error and better reporting https://github.com/RocketChat/Rocket.Chat/pull/34106 [(43393)](https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/43393eb15c974d92ca82c82b565af52f2f27d046)
- fix: runtime orchestration fixes https://github.com/RocketChat/Rocket.Chat/pull/34205 [(480fb)](https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/480fb95f21d145dabe7b968d1ade1db6993e3b86)
- fix: decoder error preventing succesfull app subprocess restart https://github.com/RocketChat/Rocket.Chat/pull/34858 …
=>  fix: Apps-engine reliability fixes

.changeset/kind-ducks-thank.md, apps/meteor/client/views/room/Header/RoomToolbox/RoomToolbox.tsx, apps/meteor/client/views/room/Header/RoomToolbox/hooks/useRoomToolboxActions.spec.ts, apps/meteor/client/views/room/Header/RoomToolbox/hooks/useRoomToolboxActions.ts, apps/meteor/client/views/room/HeaderV2/RoomToolbox/RoomToolbox.tsx, apps/meteor/client/views/room/HeaderV2/RoomToolbox/hooks/useRoomToolboxActions.spec.ts, apps/meteor/client/views/room/HeaderV2/RoomToolbox/hooks/useRoomToolboxActions.ts
Apps actions usually don't have an icon.
After removing an item from the omnichannel header toolbar, the limit of 6 items before adding to `Options` menu was resulting in app actions showing on the toolbar without an icon.
This PR adds:
- condition to only show app actions inside the menu, even if there are less then 6 items on the toolbar
- test cover for this case
before:
after:
[CONN-450](https://rocketchat.atlassian.net/browse/CONN-450)
[CONN-450]: https://rocketchat.atlassian.net/browse/CONN-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: app actions showing in room toolbar without icon

apps/meteor/client/hooks/menuActions/useLeaveRoom.tsx, apps/meteor/client/hooks/menuActions/useToggleFavoriteAction.ts, apps/meteor/client/hooks/menuActions/useToggleReadAction.ts, apps/meteor/client/hooks/useRoomMenuActions.ts, apps/meteor/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx, apps/meteor/client/omnichannel/priorities/PriorityIcon.tsx, apps/meteor/client/sidebar/Item/Condensed.tsx, apps/meteor/client/sidebar/Item/Extended.tsx, apps/meteor/client/sidebar/Item/Medium.tsx, apps/meteor/client/sidebar/RoomMenu.spec.tsx, apps/meteor/client/sidebar/RoomMenu.tsx, apps/meteor/client/sidebarv2/Item/Condensed.tsx, apps/meteor/client/sidebarv2/Item/Extended.tsx, apps/meteor/client/sidebarv2/Item/Medium.tsx, apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx, apps/meteor/client/sidebarv2/RoomMenu.tsx, apps/meteor/client/views/account/profile/ActionConfirmModal.tsx, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts, packages/ui-client/src/components/GenericMenu/GenericMenuItem.tsx
[ARCH-1405]
[ARCH-1405]: https://rocketchat.atlassian.net/browse/ARCH-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Replace `Menu` in favor of `GenericMenu` in RoomMenu

.changeset/bump-patch-1736433994910.md, .changeset/fifty-apricots-clean.md, .changeset/thirty-vans-fry.md, apps/meteor/package.json, ee/packages/omnichannel-services/src/QueueWorker.ts, yarn.lock
- Node: `20.18.0`
- Apps-Engine: `1.48.1`
*   ([#34946](https://github.com/RocketChat/Rocket.Chat/pull/34946) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes SlackBridge service failing to connect to multiple slack workspaces
*   <details><summary>Updated dependencies [a78e4f4e6c30f20109652915da8df34c7cdf2dba]:</summary>
*   @rocket.chat/omnichannel-services@0.3.9
*   @rocket.chat/core-typings@7.2.1
*   @rocket.chat/rest-typings@7.2.1
*   @rocket.chat/license@1.0.3
*   @rocket.chat/pdf-worker@0.2.9
*   @rocket.chat/presence@0.2.12
*   @rocket.chat/api-client@0.2.12
*   @rocket.chat/apps@0.2.3
*   @rocket.chat/core-services@0.7.4
*   @rocket.chat/cron@0.1.12 …
=> Release 7.2.1

.changeset/four-pugs-move.md, apps/meteor/app/statistics/server/lib/SAUMonitor.ts, packages/model-typings/src/models/ISessionsModel.ts, packages/models/src/models/Sessions.ts
[CORE-944]
[CORE-944]: https://rocketchat.atlassian.net/browse/CORE-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Prevent invalid sessions update

.changeset/three-insects-roll.md, apps/meteor/ee/app/livechat-enterprise/server/api/tags.ts, apps/meteor/tests/end-to-end/api/livechat/13-tags.ts
Fixes a missconception about `/v1/livechat/tags/:tagId` 
the type definition doesnt consider null/empty results
```
'/v1/livechat/tags/:tagId': {
GET: () => ILivechatTag;
};
```
the code returns `ILivechatTag | { body: null }` which is weird/wrong.
now if we cannot find the tag returns a 404 result
[CORE-949]
[CORE-949]: https://rocketchat.atlassian.net/browse/CORE-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: tag endpoint empty result

apps/meteor/client/hooks/usePruneWarningMessage.spec.ts
It stabilizes a fragile unit test due to async mutations.
Related to [ARCH-1285](https://rocketchat.atlassian.net/browse/ARCH-1285)
[ARCH-1285]: https://rocketchat.atlassian.net/browse/ARCH-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: Wait for hook mutation

apps/meteor/client/components/GenericModal/GenericModal.tsx, apps/meteor/client/lib/imperativeModal.tsx, apps/meteor/client/views/admin/subscription/components/cards/AppsUsageCard/AppsUsageCard.spec.tsx, apps/meteor/client/views/modal/ModalRegion.tsx
The change is about skipping some state mutations whenever a `GenericModal` element is dismissed aiming for React 18 compatibility.
Related to [ARCH-1285](https://rocketchat.atlassian.net/browse/ARCH-1285)
[ARCH-1285]: https://rocketchat.atlassian.net/browse/ARCH-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `GenericModal` dismissing strategy

.github/workflows/ci.yml
=> ci: remove broken job

apps/meteor/app/statistics/server/lib/SAUMonitor.ts, packages/models/src/models/Sessions.ts
Regression for https://github.com/RocketChat/Rocket.Chat/pull/35010 which was causing an issue when the same session was logging in and out multiple times.
The problem was that if the new log in was using the same `sessionId` as a previous one, that was probably logged out already, it was not creating a new session, so when the code was trying to to log out the session it couldn't find it, causing the error to be thrown.
I also changed to not throw an error if the session is not found.
```
W20250127-13:22:58.343(-3)? (STDERR) === UnHandledPromiseRejection ===
W20250127-13:22:58.344(-3)? (STDERR) Error: Session not found
W20250127-13:22:58.344(-3)? (STDERR)     at app/statistics/server/lib/SAUMonitor.ts:151:11
W20250127-13:22:58.344(-3)? (STDERR)     at processTicksAndRejections …
```
=> regression: do not update logged out sessions

apps/meteor/client/views/hooks/useMemberList.spec.tsx, apps/meteor/client/views/hooks/useMembersList.ts, apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx, apps/meteor/server/lib/findUsersOfRoomOrderedByRole.ts, apps/meteor/tests/end-to-end/api/rooms.ts
- **Fix**: When assigning an Owner/Moderator to a channel, the correct user now appears in the "Owners" list immediately (no longer shows the first user in the list by mistake).
- **Fix**: Restore sorting by status (online/busy/away/offline), ensuring members are ordered by `rolePriority`, then `status`, and finally `username/name`.
- [CORE-937](https://rocketchat.atlassian.net/browse/CORE-937) – Adding a new Owner/Moderator shows incorrect user on the list
- [CORE-951](https://rocketchat.atlassian.net/browse/CORE-951) – Missing sorting by status in `rooms.membersOrderedByRole`
[CORE-937]: https://rocketchat.atlassian.net/browse/CORE-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: sorting irregularities in new members list

apps/meteor/client/components/RoomIcon/OmnichannelRoomIcon/provider/OmnichannelRoomIconProvider.tsx
It compensates DOMPurify sanitization process, which wipes out SVG elements **not contained** in a `<svg>` root element.
[CONN-485](https://rocketchat.atlassian.net/browse/CONN-485)
[CONN-485]: https://rocketchat.atlassian.net/browse/CONN-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: SVG sanitization of Omnichannel rooms' icons

apps/meteor/client/sidebarv2/RoomMenu.tsx, apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts
Remove class from the sidebar item menu button, as it is already present on its parent element. The style rules of this class was causing a horizontal scroll on the sidebar of the new navigation.
=> regression: sidebar scrolling horizontally

.changeset/bump-patch-1738597514712.md, .changeset/old-schools-build.md, .changeset/silly-emus-remain.md, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts, apps/meteor/server/services/omnichannel/queue.ts, apps/meteor/tests/end-to-end/api/livechat/24-routing.ts, apps/meteor/tests/unit/server/services/omnichannel/queue.tests.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts, packages/models/src/models/LivechatInquiry.ts, yarn.lock
- Node: `22.11.0`
- Apps-Engine: `1.48.2`
*   ([#35112](https://github.com/RocketChat/Rocket.Chat/pull/35112) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes the queue processing of Omnichannel's waiting queue focusing on 3 main areas:
*   Changes the way we fetch the queue list to not append the public queue by default. This makes the server to not run the public queue always (as it is now) even if there was no work to be done.
*   Changes how the queue executes: previously, it was executed in a kind of chain: We fetched a list of "queues", then we took one, processed it, and after that we scheduled the next run, which could take some time. Now, every …
=> Release 7.3.1

apps/meteor/app/api/server/v1/users.ts
=> regression: change `API_Enable_Rate_Limiter_Limit_Time_Default` value from `600000` to `60000`

apps/meteor/app/api/server/v1/channels.ts, apps/meteor/tests/end-to-end/api/channels.ts
This PR has already received approvals here: [760](https://github.com/RocketChat/Rocket.Chat-private-security-fork/pull/760)
=> fix: imported fixes 2025-02-17

.changeset/green-rules-cover.md, apps/meteor/client/components/ImageGallery/ImageGallery.tsx
This PR improves the color contrast of icon buttons in the image gallery to ensure compliance with WCAG guidelines. The issue was present in all icon buttons when an image was opened from the chat.
The changes are according to the [design](https://www.figma.com/design/CcKhUgDMecW1xvlAtV86o1/Design-system---Web-%26-desktop?node-id=24546-13583)
https://github.com/user-attachments/assets/850d1582-0717-47c8-8d14-0fa62f9b92c8
[CORE-816](https://rocketchat.atlassian.net/browse/CORE-816)
[CORE-816]: https://rocketchat.atlassian.net/browse/CORE-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improve color contrast in image gallery for WCAG compliance  

apps/meteor/package.json, yarn.lock
The following PR (https://github.com/RocketChat/Rocket.Chat/pull/35135) updated `slack/bolt` to fix vulnerabilities related to the dependency. However, our currently implementation of `SlackBridge` breaks multi-workspace integrations when on v4. This PR downgrades `slack/bolt` to prevent the following: https://github.com/RocketChat/Rocket.Chat/pull/34933.
@pierre-lehnen-rc is currently working on converting `SlackBridge` to Typescript and he should also add the necessary changes so it can work with bolt's v4: https://github.com/RocketChat/Rocket.Chat/pull/35196.
=> regression: downgrade `slack/bolt` version to prevent `SlackBridge` from breaking

apps/meteor/client/components/Omnichannel/hooks/useUnitsList.ts
Basically, `RecordList` was sorting the units from the backend by its `_updatedAt` property. After removing the prop, it should keep the original sorting (by name)
Introduced by: https://github.com/RocketChat/Rocket.Chat/pull/35147
After fix:
=> regression: Preserve backend sort for `units` list

apps/meteor/client/views/omnichannel/directory/providers/ChatsProvider.tsx
The problem is: since we store the current query on the local storage, old installations will have some data that's no longer compatible with the new version. For example, fields that have been converted to be an array instead of an string will fail to be processed.
The work to support both, or to make the old compatible with the new is greater than what we get from them (after the first use, the code to support old stored value would become legacy as a new payload will be stored, rendering the code useless from that point). So, quickest solution: change the key where we store, allowing new installations to set new data, and old installations to not fail :)
Introduced here: #35147
=> regression: Old stored query conflicting with new filters applied

README.md
Review  and update the official GitHub Readme.
=> docs: Review README.md

apps/meteor/app/apps/server/bridges/livechat.ts, apps/meteor/app/lib/server/functions/closeLivechatRoom.ts, apps/meteor/app/lib/server/functions/closeOmnichannelConversations.ts, apps/meteor/app/livechat/server/api/v1/room.ts, apps/meteor/app/livechat/server/api/v1/transcript.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/livechat/server/lib/closeRoom.ts, apps/meteor/app/livechat/server/lib/sendTranscript.ts, apps/meteor/app/livechat/server/lib/stream/agentStatus.ts, apps/meteor/app/livechat/server/methods/closeRoom.ts, apps/meteor/ee/app/livechat-enterprise/server/api/lib/contacts.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts, apps/meteor/ee/tests/unit/apps/livechat-enterprise/lib/AutoCloseOnHold.tests.ts, apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/QueueInactivityMonitor.spec.ts, apps/meteor/tests/unit/app/lib/server/functions/closeLivechatRoom.tests.ts
=> refactor: Break big `livechatTyped` into smaller files

apps/meteor/package.json, packages/gazzodown/package.json
The issue was traced to the use of Unicode property escapes (`\p{S}` and `\p{P}`) in the Haskell grammar definition of `highlight.js`, as detailed in [highlight.js#4013](https://github.com/highlightjs/highlight.js/issues/4013).  
The issue only occurred in production, likely due to differences in how the build process handles regex.  
So, I have rolled back to version `11.8.0` as hotfix, which resolves the issue.
[CORE-1005](https://rocketchat.atlassian.net/browse/CORE-1005)
[CORE-1005]: https://rocketchat.atlassian.net/browse/CORE-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix regex error when sending multi-line code  

apps/meteor/app/apps/server/bridges/livechat.ts, apps/meteor/app/livechat/server/api/v1/message.ts, apps/meteor/app/livechat/server/hooks/offlineMessage.ts, apps/meteor/app/livechat/server/hooks/sendToCRM.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/app/livechat/server/lib/logger.ts, apps/meteor/app/livechat/server/lib/messages.ts, apps/meteor/app/livechat/server/lib/tracking.ts, apps/meteor/app/livechat/server/lib/webhooks.ts, apps/meteor/tests/unit/app/livechat/server/hooks/sendToCRM.tests.ts
=> refactor: Break down `LivechatTyped` into smaller components

apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/ee/server/apps/marketplace/fetchMarketplaceApps.ts, apps/meteor/ee/server/apps/marketplace/fetchMarketplaceCategories.ts, apps/meteor/ee/server/apps/marketplace/marketplaceErrors.ts
Since the changes introduced in: https://github.com/RocketChat/Rocket.Chat/pull/35059 we changed how the errors are returned to the client, abstracting away marketplace errors with our own errors. But, since we used to match on the string value of the error (returned by marketplace) we broken this screen.
The fix is really simple since it is a regression and I don't think we should do major refactorings, but as the backend goes through a more standardized version of throwing marketplace errors, we should look into handling it in the marketplace more gracefully.
[CONN-550](https://rocketchat.atlassian.net/browse/CONN-550)
[CONN-550]: https://rocketchat.atlassian.net/browse/CONN-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull …
=> regression: show message asking for updating workspace when unsupported version

.changeset/green-panthers-poke.md, .changeset/popular-boats-poke.md, apps/meteor/app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts, ee/packages/omnichannel-services/src/OmnichannelTranscript.ts, ee/packages/pdf-worker/src/worker.fixtures.ts, yarn.lock
- Node: `22.11.0`
- Apps-Engine: `1.48.2`
*   Add a retry mechanism to get supported versions from Cloud
*   ([#35353](https://github.com/RocketChat/Rocket.Chat/pull/35353) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes omnichannel transcript filename breaking download links
*   <details><summary>Updated dependencies [b2d71461a6a73157024e4594cc1228419a34673e]:</summary>
*   @rocket.chat/omnichannel-services@0.3.13
*   @rocket.chat/pdf-worker@0.2.13
*   @rocket.chat/core-typings@7.3.3
*   @rocket.chat/rest-typings@7.3.3
*   @rocket.chat/license@1.0.7
*   @rocket.chat/presence@0.2.16
*   @rocket.chat/api-client@0.2.16
*   @rocket.chat/apps@0.2.7
*   @rocket.chat/core-services@0.7.8
* …
=> Release 7.3.3

apps/meteor/app/apps/server/bridges/settings.ts
[CONN-555]
Introduced in: https://github.com/RocketChat/Rocket.Chat/pull/35199/files#diff-c48428c180d5e7580869c8c23cfa09514ef1428da2e29a252a4c2ed66a09590dR63-R67
[CONN-555]: https://rocketchat.atlassian.net/browse/CONN-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: not allowing apps with default permissions to read settings

apps/meteor/client/hooks/useSafeRefCallback.spec.tsx, apps/meteor/client/hooks/useSafeRefCallback.ts, apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx
Whenever a callbackRef reference (e.g. pointer to the function) changes, the callbackRef runs again.
In the MessageBox component it is expected that the callbackRef's references can change at any given time, but attached event listeners are never removed, thus duplicating events in certain occasions.
In order to solve this issue in an elegant manner, a new hook is being introduced, called `useSafeCallbackRef`. This hook allows a `cleanup` callback to be returned from the callbackRef, and will run such callback whenever the callbackRef is called after the first time. The `cleanup` callback is optional, in case some condition inside the callback is not required.
If a callbackRef never requires a cleanup effect, there's no need to use it.
PS.: This PR is labaled as `chore` because currently …
=> chore: Deduplicate keyboard event in MessageBox

.changeset/neat-dingos-smoke.md, apps/meteor/client/views/room/composer/messageBox/hooks/useMediaPermissions.ts
Each time the hook was called, a new instance of `PermissionStatus` was created with an `onchange` listener that was never cleaned up.
This PR leverages `useQuery` in order to maintain a single listener per permission type during the lifecycle of the application.
=> fix: Duplicate `PermissionStatus` event

apps/meteor/client/lib/VideoConfManager.ts, apps/meteor/client/views/root/AppLayout.tsx, apps/meteor/client/views/root/hooks/useUpdateVideoConfUser.ts
Removed Meteor.startup and Tracker.autorun from the VideoConfManager updateUser flow and implemented a startup useEffect that runs the function.
Demo gif:
1. Open the `useUpdateVideoConfUser.ts` hook and add some console logs to it;
- My recommendation:
```
export const useUpdateVideoConfUser = () => {
const [ userId , isLoggingIn , isConnected ] = [ Meteor.userId(), Meteor.loggingIn(), Meteor.status().connected ];
console.log('[useUpdateVideoConfUser] Initial values:', {
userId,
isLoggingIn,
isConnected,
});
useEffect(() => {
console.log('[useUpdateVideoConfUser] Effect triggered with:', {
userId,
isLoggingIn,
isConnected,
});
VideoConfManager.updateUser(userId , isLoggingIn , isConnected);
}, [userId, isLoggingIn, isConnected]);
};
```
3. Login as the first user (admin user);
4. Install …
=> refactor: Remove meteor functions from VideoConfManager

apps/meteor/client/lib/toast.ts, apps/meteor/client/providers/ToastMessagesProvider.tsx, apps/meteor/package.json, apps/uikit-playground/package.json, packages/ui-contexts/src/ToastMessagesContext.ts, yarn.lock
when using `useToastMessageDispatch`, you can now pass a `ReactNode` as the `message` on the payload
=> chore: accept `ReactNode` as toast message

apps/meteor/client/views/composer/EmojiPicker/CategoriesResult.tsx, apps/meteor/tests/e2e/emojis.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
Introduced here: #33796
When replacing `rc-scrollbars` we've created a separated implementation for virtualized lists but we didn't replaced in the EmojiPicker
- open a room
- open the emoji picker
- scrollbar should be visible
=> regression: `EmojiPicker` not displaying scrollbar properly

.changeset/selfish-toes-lay.md, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, packages/livechat/src/lib/hooks.ts
This PR resolves an issue where Livechat would lose connection when `registerGuest` was called multiple times with the same token via the Livechat API.
The problem occurred because `Livechat.unsubscribeAll` was being called on every `registerGuest` call, regardless of whether the guest token had actually changed.
- Moved unsubscribeAll to a more appropriate place within createOrUpdateGuest.
- Added validation to ensure the guest token has changed before unsubscribing.
[CTZ-7](https://rocketchat.atlassian.net/browse/CTZ-7)
- Embed the livechat widget to a page
- Via Livechat API call the method registerGuest providing a token, name and email
- Start a conversation
- Call registerGuest again with the same token
- Try to send a message
- Connection should have been severed
[CTZ-7]: …
=> fix: Calling registerGuest multiple times causes loss of communication

.changeset/sour-spiders-pay.md, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/tests/data/apps/apps-data.ts, apps/meteor/tests/e2e/fixtures/insert-apps.ts, apps/meteor/tests/end-to-end/apps/installation.ts
=> fix: apps endpoint not returning app's data

apps/meteor/client/omnichannel/securityPrivacy/SecurityPrivacyRoute.tsx, apps/meteor/client/providers/SettingsProvider.tsx, apps/meteor/client/sidebar/Sidebar.stories.tsx, apps/meteor/client/sidebarv2/Sidebar.stories.tsx, apps/meteor/client/views/account/AccountSidebar.tsx, apps/meteor/client/views/admin/AdministrationRouter.tsx, apps/meteor/client/views/admin/featurePreview/AdminFeaturePreviewRoute.tsx, apps/meteor/client/views/admin/settings/SettingsPage.tsx, apps/meteor/client/views/admin/sidebar/AdminSidebar.tsx, apps/meteor/client/views/marketplace/MarketplaceSidebar.tsx, apps/meteor/client/views/omnichannel/sidebar/OmnichannelSidebar.tsx, packages/mock-providers/src/MockedAppRootBuilder.tsx, packages/mock-providers/src/MockedSettingsContext.tsx, packages/ui-client/src/components/Header/Header.stories.tsx, packages/ui-client/src/components/HeaderV2/Header.stories.tsx, packages/ui-contexts/src/SettingsContext.ts, packages/ui-contexts/src/hooks/useIsSettingsContextLoading.ts, packages/ui-contexts/src/index.ts
https://rocketchat.atlassian.net/browse/ARCH-1505
It suspends the rendering of `SettingsProvider` until the settings are loaded.
Might be interesting in the future to make the `SettingsContext` consumers themselves suspend components.
=> chore: Suspend `SettingsProvider`

apps/meteor/app/models/client/models/CachedChatRoom.ts, apps/meteor/app/models/client/models/CachedChatSubscription.ts, apps/meteor/app/models/client/models/Permissions.ts, apps/meteor/client/lib/cachedCollections/CachedCollection.ts, apps/meteor/client/lib/cachedCollections/index.ts, apps/meteor/client/lib/settings/PrivateSettingsCachedCollection.ts, apps/meteor/client/lib/settings/PublicSettingsCachedCollection.ts
It does a small change in the `CachedCollection` API to split behaviors that depend on the authenticated user.
=> chore: Subclasses of `CachedCollection`

apps/meteor/app/ui/client/lib/KonchatNotification.ts, apps/meteor/client/hooks/useNotifyNewRoom.ts, apps/meteor/client/hooks/useNotifyUser.ts, apps/meteor/client/providers/OmnichannelProvider.tsx
[ARCH-1504](https://rocketchat.atlassian.net/browse/ARCH-1504)
[ARCH-1504]: https://rocketchat.atlassian.net/browse/ARCH-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: remove KonchatNotification `newRoom` from meteor

apps/meteor/.scripts/replaceTranslationSprintfParams.ts, apps/meteor/package.json
Inside `/apps/meteor/` run:
`yarn translation-replace-sprintf-params "<TRANSLATION_KEY">`
The script will identify all `%s` tokens and prompt for names to replace it. Example:
```
yarn translation-replace-sprintf-params "Leave_Private_Warning"
Found 67 translation files
Found translation key "Leave_Private_Warning" with value: "Are you sure you want to leave the discussion with "%s"?"
This string contains 1 "%s" tokens
Please provide 1 parameter names (comma-separated): roomName
Updated /Users/gabriellsh/dev/Rocket.Chat/packages/i18n/src/locales/af.i18n.json
Updated /Users/gabriellsh/dev/Rocket.Chat/packages/i18n/src/locales/ar.i18n.json
[...]
All translation files have been updated
```
=> chore: Helper script to replace sprintf tokens `%s` on translation strings

.changeset/fifty-moles-boil.md, apps/meteor/ee/server/apps/startup.ts, packages/model-typings/src/models/IAppLogsModel.ts, packages/models/src/models/AppLogsModel.ts, packages/models/src/models/BaseRaw.ts
**Refactor AppsLogsModel to remove `_updatedAtIndexOptions` and use `modelIndexes`**
This change removes the `_updatedAtIndexOptions` parameter and instead uses the `modelIndexes` method to determine the updated index options.
Without overwriting `modelIndexes` to return a value, `_updatedAtIndexOptions` is never added.
The current implementation check on `Apps.isInitialized()` which is `false` during the first attempt, but you can seethe problem  when the TTL setting is changed.
=> fix: Add Apps log TTL index

apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-department.spec.ts
This PR fixes a bug where the unit field in the EditDepartment page becomes disabled immediately after selecting a unit. The field should only become disabled after a unit has been set **and** saved. 
Now, the field remains editable until the department is saved, ensuring users can freely change the business unit while creating a department.
[CTZ-22](https://rocketchat.atlassian.net/browse/CTZ-22)
- Access Enterprise workspace
- Go Omnichannel > Department
- New department
- Field "Unit" should be visible
- Select a unit
- Field should remain enabled
- Save and edit
- Unit field should be disabled
Introduced here: #35370
[CTZ-22]: https://rocketchat.atlassian.net/browse/CTZ-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Department's unit field becomes disabled after selecting a unit

apps/meteor/client/omnichannel/additionalForms/AutoCompleteUnit.tsx, apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-department.spec.ts, apps/meteor/tests/e2e/utils/omnichannel/units.ts
This PR adds error state to the Unit field within the EditDepartment page.
[CTZ-23](https://rocketchat.atlassian.net/browse/CTZ-23)
- Access Enterprise workspace
- Go Omnichannel > Department
- New department
- Field "Unit" should be visible
- Select a unit
- Select none as a unit
- Should display error message "Unit required"
Introduced here: #35370
[CTZ-23]: https://rocketchat.atlassian.net/browse/CTZ-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Department's unit field missing error state

apps/meteor/client/views/admin/EditableSettingsContext.ts, apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx, apps/meteor/client/views/admin/settings/SettingsRoute.tsx, apps/meteor/package.json, yarn.lock
It uses a Zustand store to replace a Minimongo collection + useSyncExternalStore.
[ARCH-1521](https://rocketchat.atlassian.net/browse/ARCH-1521)
[ARCH-1521]: https://rocketchat.atlassian.net/browse/ARCH-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Replace collection with Zustand store in `EditableSettingsProvider`

apps/meteor/client/views/room/body/RoomTopic.tsx, apps/meteor/tests/e2e/feature-preview.spec.ts
[CORE-1032]
[CORE-1032]: https://rocketchat.atlassian.net/browse/CORE-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Empty topic being displayed in direct messages

apps/meteor/client/views/room/Header/RoomTitle.tsx, apps/meteor/client/views/room/Header/icons/Favorite.tsx, apps/meteor/client/views/room/HeaderV2/RoomTitle.tsx, apps/meteor/client/views/room/HeaderV2/icons/Encrypted.tsx, apps/meteor/client/views/room/HeaderV2/icons/Favorite.tsx, apps/meteor/tests/e2e/channel-management.spec.ts, packages/ui-client/src/components/Header/HeaderState.tsx, packages/ui-client/src/components/HeaderV2/HeaderState.tsx
`HeaderState` is receiving some props that it shouldn't, so this PR aims to fix the types in order to avoid wrong and unnecessary props to be passed
- Open an encrypted room
- Check if the key icon is properly rendered 
- It should not throw any error in the console
[CORE-1047]
[CORE-1047]: https://rocketchat.atlassian.net/browse/CORE-1047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `HeaderState` receiving invalid prop

apps/meteor/client/views/omnichannel/directory/chats/ChatInfo/RoomEdit/RoomEdit.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-chat-history.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts, apps/meteor/tests/e2e/page-objects/home-omnichannel.ts, apps/meteor/tests/e2e/page-objects/omnichannel-room-info.ts
Introduced here: #33796
Theres a `ContextualbarScrollabeContent` being used incorrectly in a loading state when editing a omnichannel room. As we recently changed how we handle our scrollbars, the GUI is crashing when accessing it.
- Open a Omnichannel Room
- Try to edit the room information
- The GUI should not crash
[CORE-1049]
[CORE-1049]: https://rocketchat.atlassian.net/browse/CORE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: GUI crashing when editing a OC room

apps/meteor/client/hooks/notification/useDesktopNotification.ts, apps/meteor/client/hooks/notification/useNewMessageNotification.ts, apps/meteor/client/hooks/notification/useNewRoomNotification.ts, apps/meteor/client/hooks/notification/useNotification.ts, apps/meteor/client/hooks/notification/useNotificationPermission.ts
[ARCH-1517](https://rocketchat.atlassian.net/browse/ARCH-1517)
replace `useCallback` with `useEffectEvent` on appropriated places in `hooks/notification` files
[ARCH-1517]: https://rocketchat.atlassian.net/browse/ARCH-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: replace `useCallback` with `useEffectEvent`

apps/meteor/app/api/server/v1/calendar.ts, apps/meteor/server/services/calendar/service.ts
=> regression: outlook imported events not syncing presence status

.github/workflows/ci-code-check.yml, .github/workflows/ci-deploy-gh-pages.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci-test-unit.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/new-release.yml, .github/workflows/pr-title-checker.yml, .github/workflows/pr-update-description.yml, .github/workflows/publish-release.yml, .github/workflows/release-candidate.yml, .github/workflows/stale.yml, .github/workflows/update-version-durability.yml
https://rocketchat.atlassian.net/browse/ARCH-1532
> This is a scheduled Ubuntu 20.04 brownout.
=> chore: bump ubuntu

.changeset/popular-pumpkins-relax.md, packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyCreator.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyCreator.test.ts
[CTZ-33]
[CTZ-33]: https://rocketchat.atlassian.net/browse/CTZ-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: throws errors for apps properly

apps/meteor/app/emoji-emojione/client/hooks/useEmojiOne.ts, apps/meteor/app/emoji/client/helpers.ts, apps/meteor/client/views/composer/EmojiPicker/EmojiCategoryRow.tsx, packages/ui-client/src/components/EmojiPicker/EmojiPickerNotFound.tsx
=> regression: Emoji Picker recent list and load more not working

.github/workflows/ci.yml
=> ci: fix matrix sdk native build 

.changeset/heavy-boats-mix.md, apps/meteor/app/livechat/server/lib/RoutingManager.ts, apps/meteor/app/livechat/server/lib/rooms.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts, packages/models/src/models/LivechatInquiry.ts
This endpoint is called every time a message is sent by an omnichannel agent. On every message we used update the inquiry's `lastMessage`, which caused an invalidation on the frontend so it mistakenly thought it would need to fetch the room data again (since something changed).
The proposal is that we update the inquiry's last message only if it has not been taken yet. Once it is taken we update only the room's last message property. If it happens to the room to be sent back to the queue, then we update the inquiry's last message so it can reflect the latest state. A test was added to cover this exact behavior.
This is chart of a production workspace that uses inquiries, showing how massive the amount of calls to the endpoint is:
[CTZ-28]
[CTZ-28]: …
=> fix: Omnichannel making a request for room data after every message sent

packages/models/src/models/AppLogsModel.ts
Due to how TS works, the property default value defined in the class' constructor is actually after calling `super()`, so when `modelIndexes()` is called from `BaseRaw` the value of `this.expireAfterSeconds` is still `undefined`.
introduced by https://github.com/RocketChat/Rocket.Chat/pull/35497
```
(STDERR) Some indexes for collection 'rocketchat_apps_logs' could not be created:
(STDERR) 	. Index spec: { expireAfterSeconds: null, name: "_updatedAt_1", key: { _updatedAt: 1 } } :: caused by :: TTL index 'expireAfterSeconds' option must be numeric, but received a type of 'null
```
=> regression: fix apps logs expire as `undefined`

apps/meteor/app/api/server/router.ts, apps/meteor/app/integrations/server/api/api.js, apps/meteor/tests/end-to-end/api/incoming-integrations.ts
Introduced by #35078 
---
This pull request addresses a regression issue where incoming integrations were not functioning correctly with the new hono router in the Rocket.Chat application. The changes are made in the following files:
1. **apps/meteor/app/api/server/router.ts**: 
- Modifications are made to the body parameter parsing logic within the Router class. The focus is on handling override parameters and cases where the body is empty.
2. **apps/meteor/app/integrations/server/api/api.js**: 
- Updates are implemented for webhook request handling, emphasizing asynchronous body parsing using modern JavaScript features.
- URL construction is improved using the standard URL API and the `x-forwarded-proto` header.
- Refinements are made to the header and body data passed to integration …
=> regression: incoming integration not working with new hono router

apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
Changing the queue to run every 3 seconds should make the waits more predictable. Tried with 2 and 4 seconds and 3 was a sweet spot.
Problem with test is that for some slowliness, the server was taking a bit more than 5s to assign the chat, which made the server request the room just before it was assigned.
(Note: not that i like playing with timers & waits... but since waiting queue is based on time we have to sadly wait to test it works...)
=> test: `Chat limits` flaky test 

apps/meteor/app/notification-queue/server/NotificationQueue.ts
The way the notification queue works depends on the user's status, if the user was idle/offline there is no delay to send the notification, so `schedule` is `undefined` and previously (before #31497) it was being ignored and not added to the record, so queries like `schedule: { $exists: false }` would work.. but since then the code was saving `schedule: undefined` which caused that query to not work as expected, causing the notification issue.
Introduced by https://github.com/RocketChat/Rocket.Chat/pull/31497
=> regression: fix notifications not being sent if user is idle or offline

apps/meteor/client/components/Page/PageHeaderNoShadow.tsx, apps/meteor/client/providers/LayoutProvider.tsx, apps/meteor/client/providers/MeteorProvider.tsx, apps/meteor/client/views/room/NotSubscribedRoom.tsx, apps/meteor/client/views/room/RoomNotFound.tsx, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/sidebar.spec.ts
Introduced here: #35807
[SIDE2-66]
[SIDE2-66]: https://rocketchat.atlassian.net/browse/SIDE2-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Sidebar should collapse in tablet view under feature preview only

apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/EditInviteLink.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteLink.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.spec.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.stories.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersEdit.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersError.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersLoading.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersWithData.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsersWrapper.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/__snapshots__/InviteUsers.spec.tsx.snap
[ARCH-1579](https://rocketchat.atlassian.net/browse/ARCH-1579)
In dev mode, invite links were being generated 2 times due to useEffect
- replace endpoint call in `useEffect` in favor of `useQuery`
- handle error state
- handle loading state
- handle success state
[ARCH-1579]: https://rocketchat.atlassian.net/browse/ARCH-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request focuses on refactoring the `InviteUsers` functionality within the Rocket.Chat application. The main change involves applying `useQuery` for data fetching in the `InviteUsers` component. The update includes the removal of existing error handling and the Callout component, which may affect error visibility and user experience. To address error handling, a …
=> chore: apply `useQuery` on `InviteUsers`

packages/apps-engine/src/server/AppManager.ts
The changes introduced [here](https://github.com/RocketChat/Rocket.Chat/pull/31497) ended up modifying the object reference sent to the `create` function that inserts a new app document in the database, but that function counted on modifying the object it received to assign the inserted id.
This caused routines that relied on the inserted id of the app storage record to stop working - namely private api endpoint registration
[CONN-625]
[CONN-625]: https://rocketchat.atlassian.net/browse/CONN-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix app installation

apps/meteor/tests/e2e/feature-preview.spec.ts, apps/meteor/tests/e2e/message-mentions.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts
https://rocketchat.atlassian.net/browse/ARCH-1584
https://rocketchat.atlassian.net/browse/FLAKY-1196
https://rocketchat.atlassian.net/browse/FLAKY-1156
=> test: flaky feature preview tests

.changeset/warm-steaks-fetch.md, apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ReviewContactModal.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-contact-conflict-review.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts, apps/meteor/tests/e2e/page-objects/omnichannel-contact-review-modal.ts, apps/meteor/tests/e2e/utils/omnichannel/custom-field.ts
This PR fixes a small bug that caused the API to return an error during contact's custom field conflict resolution, the issue was caused  by a payload being incorrectly built and sent to the API.
[CTZ-97](https://rocketchat.atlassian.net/browse/CTZ-97)
1. Create a custom field (visitor scope)
2. Call  setCustomField widget API method with overwrite: false (this.setCustomField('fieldName2', 'A value set just once', false))
3. Go to Contact Info Panel
4. Click See Conflicts
5. Chose an option and click Save
6. Error message is raised right away
[CTZ-97]: https://rocketchat.atlassian.net/browse/CTZ-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request addresses a bug in the Rocket.Chat repository, specifically in the …
=> fix: Contact's custom fields are now properly sent to api

apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
https://rocketchat.atlassian.net/browse/ARCH-1586
https://rocketchat.atlassian.net/browse/FLAKY-1296
https://rocketchat.atlassian.net/browse/FLAKY-1294
=> test(flaky): ensure agent info is saved before reopening tab

apps/meteor/client/hooks/useIdleConnection.ts, apps/meteor/client/providers/UserProvider/UserProvider.tsx
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/35787
https://rocketchat.atlassian.net/browse/ARCH-1587
---
This pull request addresses a regression issue in the Rocket.Chat repository by modifying the logic used to determine when to close idle connections. Specifically, the change is made in the `useIdleConnection.ts` file within the `apps/meteor/client/hooks` directory. The updated logic now checks if the connection status is not 'offline' before disconnecting from the server, improving the condition for handling idle connections. The source branch for this change is `regression/useIdleConnection`, and it targets the `develop` branch.
=> regression: close idle connections

apps/meteor/client/lib/chats/readStateManager.ts, apps/meteor/client/views/room/providers/hooks/useChatMessagesInstance.spec.ts, apps/meteor/client/views/room/providers/hooks/useChatMessagesInstance.ts
https://rocketchat.atlassian.net/browse/ARCH-1585
found during https://github.com/RocketChat/Rocket.Chat/pull/35880
---
This pull request aims to address an issue in the Rocket.Chat repository by preventing multiple `listener.once` calls to `updateSubscription`. The changes are made in two files:
1. **readStateManager.ts**: A new method has been added to subscribe to message loading events and update the first unread record ID.
2. **useChatMessagesInstance.ts**: A `useEffect` hook is introduced to manage message subscriptions using `chatMessages.readStateManager`. The hook utilizes optional chaining to avoid runtime errors when `subscription` or `chatMessages` are temporarily undefined.
These updates are intended to enhance the management of message subscriptions and improve the stability …
=> chore: prevent multiple listener.once `updateSubscription`

.changeset/proud-rocks-destroy.md, apps/meteor/app/markdown/lib/hljs.js, apps/meteor/client/startup/startup.ts, apps/meteor/client/views/root/lib/codeBlockStyles.ts, apps/meteor/package.json, apps/meteor/tests/unit/app/markdown/client.tests.js, yarn.lock
Stops using two different versions of highlight.js, instead uses only the latest one
https://rocketchat.atlassian.net/browse/CORE-1031
Send messages with code quotes with code from different languages
---
This pull request updates the highlight.js library in the Rocket.Chat repository from version 9 to 11.8.0. The changes include updating the import paths and language registration logic in `apps/meteor/app/markdown/lib/hljs.js` to improve maintainability and compatibility with the latest version of highlight.js. Additionally, the import statement for highlight.js styles in `apps/meteor/client/startup/startup.ts` is updated from 'hljs9/styles/github.css' to 'highlight.js/styles/github.css' to ensure correct dependency usage.
=> chore: use only highlight.js 11.8.0

apps/meteor/app/api/server/router.spec.ts, apps/meteor/app/api/server/router.ts
[CORE-1135](https://rocketchat.atlassian.net/browse/CORE-1135)
---
This pull request addresses an issue in the Rocket.Chat repository where API endpoint query parameter validation was not functioning correctly for nested properties. The changes are made in the `apps/meteor/app/api/server/router.ts` file. The update involves modifying the router class to handle query parameters by parsing them, rather than accessing them directly from the request. This adjustment aims to improve the validation process for nested query parameters. The source branch for this fix is `fix/routerQuery`, and it is targeted to be merged into the `develop` branch.
[CORE-1135]: https://rocketchat.atlassian.net/browse/CORE-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> regression: API endpoints query parameter validation not working for nested properties

apps/meteor/client/views/admin/EditableSettingsContext.spec.tsx, apps/meteor/client/views/admin/EditableSettingsContext.ts, apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx, apps/meteor/client/views/admin/settings/Setting/Setting.tsx
[CORE-1134](https://rocketchat.atlassian.net/browse/CORE-1134)
[CORE-1134]: https://rocketchat.atlassian.net/browse/CORE-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Admin settings with `enableQuery` and `displayQuery` do not react to changes

apps/meteor/app/apps/server/converters/rooms.js
https://rocketchat.atlassian.net/browse/CTZ-24
Caused by https://github.com/RocketChat/Rocket.Chat/pull/31497
=> regression: Passing `servedBy` instead of `servedBy.id` to `findOne` call when converting a room from app

apps/meteor/app/api/server/helpers/parseJsonQuery.ts
[CORE-1142]
Introduced in https://github.com/RocketChat/Rocket.Chat/pull/35078
Apparently, the other place we had to do this check was updated already, but this one was left on `request.route` instead of `api.path`.
Typings says `request.route` should be defined tho, but that's maybe because we're using `global.Request` instead of a Hono/Express custom one 👀 
[CORE-1142]: https://rocketchat.atlassian.net/browse/CORE-1142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `Cannot read properties of undefined` when running `request.route.includes`

.changeset/curly-teachers-sort.md, apps/meteor/app/cors/server/cors.ts, apps/meteor/server/configuration/configureBoilerplate.ts, apps/meteor/tests/end-to-end/api/cors.ts
https://rocketchat.atlassian.net/browse/ARCH-1601
After we saved the `meteorRuntimeConfigHash` value once, this value was persisted forever.
It works fine between redeploys, but if we change settings (like Site_url) we will end up in a state where the API always returns 404
* Updated the logic in `WebAppInternals.staticFilesMiddleware` to include the `ROOT_URL` in the runtime configuration hash. This ensures that the hash changes when the `ROOT_URL` changes, improving the consistency and accuracy of the runtime configuration validation.
* Added a new test suite in `apps/meteor/tests/end-to-end/api/cors.ts` to validate the behavior of `/meteor_runtime_config.js`. The tests include scenarios for missing, invalid, and matching hashes, as well as ensuring the hash updates correctly when the …
=> fix: change site url  breaks `meteor_runtime_config`

.changeset/cuddly-feet-clap.md, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml, packages/models/src/index.ts
https://rocketchat.atlassian.net/browse/ARCH-1602
---
This pull request updates the Rocket.Chat repository by modifying the default behavior of database watchers. The changes are made in the `packages/models/src/index.ts` file. The logic is adjusted so that database watchers are now disabled by default in more scenarios, particularly in production environments where the `DISABLE_DB_WATCHERS` environment variable is not set or is not explicitly set to 'no' or 'false'. Additionally, a console warning is introduced to alert users when watchers are active, highlighting their deprecation. The source branch for this change is `chore/deprecate-streamhub-oplog-changestreams`, and it targets the `develop` branch.
=> chore: deprecates dbWatchers  and set default value to false

.changeset/gold-keys-compare.md, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml, apps/meteor/server/startup/serverRunning.js
https://rocketchat.atlassian.net/browse/ARCH-1459
=> chore!: remove mongo 5/6 support

.changeset/polite-islands-try.md, apps/meteor/app/api/server/definition.ts, apps/meteor/app/api/server/middlewares/honoAdapter.ts, apps/meteor/app/api/server/router.spec.ts, apps/meteor/ee/server/apps/communication/rest.ts
https://rocketchat.atlassian.net/browse/ARCH-1607
The following error was being thrown when showing an app's icon like `http://localhost:3000/api/apps/c33fa1a6-68a7-491e-bf49-9d7b99671c48/icon`
```
W20250515-19:02:28.315(-3)? (STDERR) TypeError: v is not iterable
W20250515-19:02:28.315(-3)? (STDERR)     at Context.#newResponse (/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/packages/modules.js:24348:26)
W20250515-19:02:28.315(-3)? (STDERR)     at Context.body (/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/packages/modules.js:24361:55)
W20250515-19:02:28.315(-3)? (STDERR)     at app/api/server/router.ts:277:13
W20250515-19:02:28.315(-3)? (STDERR)     at processTicksAndRejections (node:internal/process/task_queues:105:5)
W20250515-19:02:28.315(-3)? (STDERR) …
```
=> fix: buffer as response from API

apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx, apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx, apps/meteor/client/views/e2e/SaveE2EPasswordModal.tsx, apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/fixtures/inject-initial-data.ts, apps/meteor/tests/e2e/page-objects/account-security.ts, apps/meteor/tests/e2e/page-objects/encrypted-room.ts, apps/meteor/tests/e2e/page-objects/fragments/e2ee.ts, apps/meteor/tests/e2e/page-objects/fragments/file-upload-modal.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/fragments/message.ts, apps/meteor/tests/e2e/page-objects/fragments/modal.ts, apps/meteor/tests/e2e/page-objects/fragments/toast-messages.ts, apps/meteor/tests/e2e/page-objects/login.ts
https://rocketchat.atlassian.net/browse/ARCH-1610
It:
- splits tests related to E2E password setup and basic functionality;
- makes the tests non-sequentially dependent;
- employs the Page Object Model pattern more heavily.
---
This pull request focuses on enhancing the end-to-end encryption (E2EE) testing framework within the Rocket.Chat repository. The key changes include:
1. **Refactoring in RoomHistoryManager**: The `getMore` method in `RoomHistoryManagerClass` has been refactored to improve robustness. The core logic is now encapsulated within a `try...finally` block to ensure the `isLoading` state is managed correctly and `waitAfterFlush` is consistently called. The method signature has also been updated to accept an options object, enhancing clarity and extensibility.
2. …
=> test: Decouple E2E encryption tests

.changeset/serious-trees-whisper.md, apps/meteor/client/components/MarkdownText.spec.tsx, apps/meteor/client/components/MarkdownText.tsx, apps/meteor/client/views/admin/settings/Setting/Setting.tsx
Closes https://github.com/RocketChat/Rocket.Chat/issues/32911
[CORE-580]
---
This pull request addresses an issue in the Rocket.Chat repository where external links in settings were not being modified to open in new tabs. The changes include adding a changeset entry to ensure that these links are correctly set to open in new tabs, enhancing user experience by preventing navigation away from the current page. The changes are made in the `fix/i18n-external-links` branch and are intended to be merged into the `develop` branch.
[CORE-580]: https://rocketchat.atlassian.net/browse/CORE-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: External links without target not being modified

.changeset/tricky-fishes-hope.md, apps/meteor/app/livechat/server/lib/sendTranscript.ts, packages/gazzodown/src/elements/LinkSpan.tsx, packages/gazzodown/src/elements/sanitizeUrl.spec.ts, packages/gazzodown/src/elements/sanitizeUrl.ts
The necessary approvals can be seen in our private repository. This PR is a port from the private repo to the public one. Also, as these are improvements, there's no need to backport these changes.
[756](https://github.com/RocketChat/Rocket.Chat-private-security-fork/pull/765)
[766](https://github.com/RocketChat/Rocket.Chat-private-security-fork/pull/766)
=> fix: imported fixes 2025-05-16

.changeset/rotten-pianos-serve.md, apps/meteor/client/components/AutoCompleteDepartmentMultiple.spec.tsx, apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx, apps/meteor/client/omnichannel/additionalForms/BusinessHoursMultiple.tsx, apps/meteor/client/omnichannel/tags/TagEdit.tsx, apps/meteor/client/views/omnichannel/directory/chats/ChatsFiltersContextualBar.tsx
This PR fixes the property `withCheckbox` not working on the `AutoCompleteDepartmentMultiple` component. A checkbox should be rendered for each option when `withCheckbox` is `true`. This was not happening due to a missing `return`.
[CTZ-157](https://rocketchat.atlassian.net/browse/CTZ-157)
Can be found in:
- Business Hours page
- Create/edit tags page
- Create/edit unit page
- Create/edit department page
Introduced here #35282
[CTZ-157]: https://rocketchat.atlassian.net/browse/CTZ-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AutoCompleteDepartmentMultiple `withCheckbox` property not working

apps/meteor/server/services/settings/service.ts, apps/meteor/server/settings/misc.ts
https://rocketchat.atlassian.net/browse/ARCH-1616
Updated the updateFingerprint function to invoke notifyOnSettingChangedById for the Deployment_FingerPrint_Hash and Deployment_FingerPrint_Verified settings, ensuring listeners are notified of changes
Since https://github.com/RocketChat/Rocket.Chat/pull/35981 we no longer use oplog, so in this case ui/backend wont realize the changes
introduced "around" here: https://github.com/RocketChat/Rocket.Chat/issues/31527
=> fix: add notification on setting changes for Deployment FingerPrint

apps/meteor/client/components/MarkdownText.spec.tsx, apps/meteor/client/components/MarkdownText.tsx
Implements more test cases to ensure behaviour is correct.
Changes the regex that matches the URI schemes to not have the "global" property.
The issue was introduced here: https://github.com/RocketChat/Rocket.Chat/pull/32917
For some reason, the change to the `inlineMarked` return is what broke the links. I did not find why that was the case, but reading domPurify's documentation and types, the default regex was found to not have the `global` property. Given the whole context, it was inferred that the issue happened due to regexes with the "global" flag set keeping an internal index after matching the text. If the same regex was being used to try to match multiple strings, some of them would not match due to the Regexe's dirty state. …
=> regression: Broken links in the UI when multiple links are used

.changeset/odd-beds-dream.md, apps/meteor/app/api/server/router.ts, apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
- Added support in hono router to `x-www-form-urlencoded` content type (twilio sends payload in this format)
- Updated tests to use this content type (since they were using JSON, they didn't catch the problem earlier)
https://rocketchat.atlassian.net/browse/CTZ-176
=> fix: `x-www-form-urlencoded` support on bodyParams

.changeset/silent-shoes-repeat.md, apps/meteor/app/api/server/api.ts, apps/meteor/app/api/server/middlewares/metrics.spec.ts, apps/meteor/app/api/server/middlewares/metrics.ts
https://rocketchat.atlassian.net/browse/ARCH-1620
The metrics will be sent like this:
```
rocketchat_rest_api_count{status="200",method="post",version="v1",entrypoint="method.call/permissions:get"} 1
rocketchat_rest_api_count{status="200",method="get",version="v1",entrypoint="me"} 3
rocketchat_rest_api_count{status="200",method="get",version="v1",entrypoint="roles.list"} 5
rocketchat_rest_api_count{status="200",method="get",version="v1",entrypoint="livechat/agents/:agentId/departments"} 2
```
Before the fix they were not being grouped as shown below, creating multiple entries for the same route:
```
rocketchat_rest_api_count{method="GET",version="v1",entrypoint="/v1/livechat/agents/DMqFRxxxdXm9R/departments",status="200"} 4471
rocketchat_rest_api_count{method="GET",version="v1",entrypoint= …
```
=> fix: prometheus' REST API metrics

apps/meteor/app/livechat/imports/server/rest/sms.ts, apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts, apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts, apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts, apps/meteor/tests/unit/server/services/omnichannel-integrations/providers/twilio.spec.ts, packages/core-typings/src/omnichannel/sms.ts
https://rocketchat.atlassian.net/browse/CTZ-178
(Note: 2 issues in one as one fix is not enough for the feature to work)
For some reason, Hono defaults to `localhost` in req.url (or it's using the localhost domain instead of the public site url)
For example, on candidate:
```
{"level":35,"time":"2025-05-26T16:21:11.617Z","pid":1,"hostname":"rocketchat-candidate-55c86cb5c-hnqdb","name":"API","method":"POST","url":"http://localhost/api/v1/livechat/message","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0","length":"115","host":"candidate.qa.rocket.chat","referer":"https://candidate.qa.rocket.chat/livechat","remoteIP":"122.161.242.36","status":200,"responseTime":93} 
```
Since twilio assumed this …
=> regression: Twilio failing signature check

.changeset/fuzzy-bottles-unite.md, apps/meteor/app/api/server/middlewares/cors.spec.ts, apps/meteor/app/api/server/middlewares/cors.ts
This pull request addresses an issue with CORS (Cross-Origin Resource Sharing) headers not being properly sent for GET requests in the Rocket.Chat API. It includes changes to the middleware logic and updates to the associated test cases to reflect the new behavior.
* [`apps/meteor/app/api/server/middlewares/cors.ts`](diffhunk://#diff-4c33ca87d09ed4135e9a887f0d0a3378cbf8120f1b800291b268380d51a9453dL15-L19): Updated the middleware to always set the `Access-Control-Allow-Origin` header to `*` for GET requests, regardless of whether CORS is enabled in the settings.
* `apps/meteor/app/api/server/middlewares/cors.spec.ts`: 
- Modified test descriptions and assertions to validate that the `Access-Control-Allow-Origin` header is included for GET requests, both when CORS is enabled and disabled. …
=> fix: CORS headers incorrectly set for GET

packages/ui-voip/src/components/VoipPopupDraggable/DraggableCore.ts, packages/ui-voip/src/components/VoipPopupDraggable/useDraggable.stories.tsx
There was no limit to which buttons were allowed to drag the element, and right clicking a page opens the context menu. This makes the mechanism unable to identify that the click was released, so the element would still move around with the mouse even if no button is pressed.
Since we expect the right click to always open the context menu, the popup should now ignore right clicks.
[CORE-1170]
Right click the popup then close the context menu. The popup will follow the cursor despite no buttons being held.
[CORE-1170]: https://rocketchat.atlassian.net/browse/CORE-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Dragging the VoIP popup handle with right click keeps moving the element after release

apps/meteor/client/sidebarv2/RoomList/RoomList.tsx, apps/meteor/client/sidebarv2/RoomList/RoomListFilters.tsx, apps/meteor/client/sidebarv2/RoomList/RoomListFiltersItem.tsx, apps/meteor/client/sidebarv2/hooks/useTemplateByViewMode.ts, apps/meteor/client/sidepanel/SidePanel.tsx, apps/meteor/client/sidepanel/SidePanelRouter.tsx, apps/meteor/client/sidepanel/index.ts, apps/meteor/client/views/navigation/contexts/RoomsNavigationContext.ts, apps/meteor/client/views/navigation/hooks/useCollapsedGroups.ts, apps/meteor/client/views/navigation/hooks/useSidePanelFilters.ts, apps/meteor/client/views/navigation/providers/RoomsNavigationProvider.tsx, apps/meteor/client/views/room/RoomOpener.tsx, apps/meteor/client/views/room/Sidepanel/SidepanelItem/RoomSidepanelItem.tsx, apps/meteor/client/views/root/MainLayout/LayoutWithSidebarV2.tsx, apps/meteor/client/views/root/MainLayout/MainLayoutStyleTags.tsx, apps/meteor/tests/e2e/feature-preview.spec.ts
[SIDE2-8]
[SIDE2-79]
[SIDE2-83]
[SIDE2-92]
[SIDE2-8]: https://rocketchat.atlassian.net/browse/SIDE2-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE2-79]: https://rocketchat.atlassian.net/browse/SIDE2-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE2-83]: https://rocketchat.atlassian.net/browse/SIDE2-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE2-92]: https://rocketchat.atlassian.net/browse/SIDE2-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: New sidebar filters categories

.changeset/popular-games-dress.md, apps/meteor/app/livechat/imports/server/rest/appearance.ts, apps/meteor/app/livechat/server/api/lib/appearance.ts, apps/meteor/app/livechat/server/api/lib/livechat.ts, apps/meteor/app/livechat/server/lib/settings.ts, apps/meteor/client/views/omnichannel/appearance/AppearanceFieldLabel.tsx, apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx, apps/meteor/ee/app/livechat-enterprise/server/settings.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-hide-expand-chat.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-appearance.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts, packages/i18n/src/locales/en.i18n.json, packages/livechat/src/components/Screen/Header.tsx, packages/livechat/src/components/Screen/ScreenProvider.tsx, packages/livechat/src/components/Screen/index.js, packages/livechat/src/store/index.tsx
This PR adds:
- `hideExpandChat` option to the Livechat widget API's `setTheme` method to allow disabling the 'Expand chat' feature when needed.
- New setting "Hide 'Expand chat'" to Livechat Appearance page
https://github.com/user-attachments/assets/a0fc0740-9d91-418c-a962-f0f515802408
[CTZ-156](https://rocketchat.atlassian.net/browse/CTZ-156)
[CTZ-205](https://rocketchat.atlassian.net/browse/CTZ-205)
- With the livechat widget embeded
- Use:
```js
window.RocketChat.livechat.setTheme({ hideExpandChat: true });
// OR
window.RocketChat(function() {
this.setTheme({ hideExpandChat: true });
});
```
- Expand chat should be visible (or not) depending on the value set
[CTZ-156]: https://rocketchat.atlassian.net/browse/CTZ-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> feat: Allow hiding 'Expand chat' button via Livechat widget API

packages/release-action/src/publishRelease.ts
https://rocketchat.atlassian.net/browse/ARCH-1625
=> ci: Update publishRelease logic for patch and pre-release handling

apps/meteor/tests/end-to-end/api/livechat/07-queue.ts
https://rocketchat.atlassian.net/browse/CTZ-232
=> test: Flaky `livechat/queue` API test

apps/meteor/app/authorization/client/hasPermission.ts, apps/meteor/app/models/client/models/Permissions.ts, apps/meteor/client/views/admin/permissions/hooks/useFilteredPermissions.ts
[ARCH-1686](https://rocketchat.atlassian.net/browse/ARCH-1686)
Replace the Minimongo collection for Permissions with the Zustand store.
[ARCH-1686]: https://rocketchat.atlassian.net/browse/ARCH-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `Permissions` store

.changeset/fast-dolphins-run.md, ee/apps/ddp-streamer/src/service.ts
https://rocketchat.atlassian.net/browse/ARCH-1693
=> fix: improve error handling no ddp-streamer

apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts, apps/meteor/tests/e2e/threads.spec.ts
When you create a brand-new channel and immediately reply to your own message in a thread, the unread-messages banner was showing up even though you hadn’t missed anything. This happened because the baseline timestamp (lastMessageDate) stayed undefined until an off-screen message was detected, so every reply looked like “new” content. Now, on first load—when the message count goes from zero to some number—we set lastMessageDate to the newest message’s timestamp, giving the unread-count logic a proper anchor and preventing self-sent thread replies from ever triggering the banner.
[CORE-1214](https://rocketchat.atlassian.net/browse/CORE-1214)
[CORE-1214]: https://rocketchat.atlassian.net/browse/CORE-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> regression: unread banner appears for thread messages after channel creation

.changeset/weak-cobras-fry.md, packages/apps-engine/deno-runtime/lib/accessors/formatResponseErrorHandler.ts, packages/apps-engine/deno-runtime/lib/accessors/http.ts, packages/apps-engine/deno-runtime/lib/accessors/mod.ts, packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyCreator.ts, packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyExtender.ts, packages/apps-engine/deno-runtime/lib/accessors/modify/ModifyUpdater.ts, packages/apps-engine/deno-runtime/lib/accessors/notifier.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyCreator.test.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyExtender.test.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/ModifyUpdater.test.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/formatResponseErrorHandler.test.ts, packages/apps-engine/deno-runtime/lib/accessors/tests/http.test.ts, packages/apps-engine/deno-runtime/lib/roomFactory.ts
Deno runtime was inconsistently handling the propagation of error objects when it received an error response from JsonRPC.
Now apps will _always_ receive instances of `Error` if their accessor method calls fail.
[SUP-823]
[SUP-823]: https://rocketchat.atlassian.net/browse/SUP-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: properly throw error objects to apps on runtime

apps/meteor/.eslintrc.json, apps/meteor/client/views/audit/components/AppInfoField.spec.tsx, apps/meteor/client/views/audit/components/SecurityLogDisplayModal.spec.tsx, apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/AppLogsItem.spec.tsx, apps/meteor/client/views/room/contextualBar/RoomMembers/InviteUsers/InviteUsers.spec.tsx, ee/packages/pdf-worker/.storybook/preview.tsx, packages/eslint-config/standard/index.js, packages/gazzodown/src/Markup.stories.tsx, packages/storybook-config/src/preview.tsx, packages/ui-composer/.storybook/preview.tsx, packages/ui-video-conf/.storybook/preview.tsx, packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.stories.tsx, packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.stories.tsx, packages/ui-voip/src/components/VoipActionButton/VoipActionButton.stories.tsx, packages/ui-voip/src/components/VoipActions/VoipActions.stories.tsx, packages/ui-voip/src/components/VoipContactId/VoipContactId.stories.tsx, packages/ui-voip/src/components/VoipDialPad/VoipDialPad.stories.tsx, packages/ui-voip/src/components/VoipPopup/VoipPopup.stories.tsx
It allows parameter name `Story`, commonly used in Storybook decorators.
[ARCH-1699](https://rocketchat.atlassian.net/browse/ARCH-1699)
[ARCH-1699]: https://rocketchat.atlassian.net/browse/ARCH-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(eslint): Relax naming convention for Storybook's `Story` parameter

.changeset/angry-years-learn.md, apps/meteor/app/lib/server/functions/setUsername.ts, apps/meteor/server/methods/saveUserProfile.ts
https://rocketchat.atlassian.net/browse/ARCH-1701
While replacing methods to use endpoints (https://github.com/RocketChat/Rocket.Chat/pull/36146) , I noticed that some rest apis use slightly different methods, which end up not informing the UI 
This pull request includes changes to improve user management functionality by refining the `setUsername` and `saveUserProfile` methods. The changes focus on removing unused imports, simplifying code, and adding a notification mechanism for user updates.
* Removed the `RateLimiter` wrapper and associated permissions check from the `setUsername` function to simplify its implementation. (`apps/meteor/app/lib/server/functions/setUsername.ts`, [apps/meteor/app/lib/server/functions/setUsername.tsL154-L160](diffhunk://#diff-db49866fbf450aa9c5a6701188130fc …
=> fix: `executeSaveUserProfile` does not trigger username stream

apps/meteor/app/api/server/ApiClass.ts, apps/meteor/app/api/server/default/openApi.ts, apps/meteor/app/api/server/v1/custom-sounds.ts, apps/meteor/app/api/server/v1/federation.ts, apps/meteor/app/api/server/v1/invites.ts, apps/meteor/app/api/server/v1/webdav.ts, apps/meteor/app/livechat/server/ajv.ts, apps/meteor/app/livechat/server/index.ts, apps/meteor/ee/app/livechat-enterprise/server/api/outbound.ts, packages/core-typings/package.json, packages/core-typings/src/Ajv.ts, packages/core-typings/src/index.ts, packages/core-typings/tsconfig.json, packages/livechat/package.json, packages/rest-typings/src/index.ts, packages/rest-typings/src/v1/Ajv.ts, yarn.lock
The idea is to automatically convert our most commonly used entities, avoiding repetition and errors. This way, the endpoints can use $ref, reducing the implementation size and speeding up the development process.
https://rocketchat.atlassian.net/browse/ARCH-1707
=> feat: export core type as schema

apps/meteor/tests/e2e/containers/saml/Dockerfile
backported from https://github.com/RocketChat/Rocket.Chat/pull/36324
=> chore: update PHP and SimpleSAMLphp versions in Dockerfile

.changeset/cold-insects-guess.md, apps/meteor/app/lib/server/functions/cleanRoomHistory.ts, apps/meteor/app/ui-utils/client/lib/LegacyRoomManager.ts, apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts, apps/meteor/client/lib/utils/modifyMessageOnFilesDelete.spec.ts, apps/meteor/client/lib/utils/modifyMessageOnFilesDelete.ts, apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/prune-messages.spec.ts, packages/core-services/src/events/Events.ts, packages/ddp-client/src/types/streams.ts
This PR resolves a regression where the UI fails to update reactively after pruning only files using the “Prune messages” feature. Users must currently reload the page manually to see the deleted files disappear, a behavior that deviates from version 7.6.0, where the UI responded automatically.
The issue is caused from the lack of an explicit broadcast when `filesOnly` is true—unlike full message pruning, which uses the `deleteMessageBulk` event to notify clients. To address this, a new `deleteFilesBulk` event has been added to handle these cases and ensure client-side updates.
A contributing factor to this regression was a recent [change](https://github.com/RocketChat/Rocket.Chat/pull/35981) that disables DB watchers by default in production environments. This change, most probably, …
=> fix: ui does not update after pruning only files

.changeset/sweet-dingos-decide.md, apps/meteor/app/lib/server/lib/notifyListener.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/closeRoom.ts, apps/meteor/app/livechat/server/lib/rooms.ts, apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts, apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts, apps/meteor/ee/app/livechat-enterprise/server/api/lib/sla.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/SlaHelper.ts, apps/meteor/server/services/omnichannel/queue.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts, packages/models/src/models/LivechatInquiry.ts
https://rocketchat.atlassian.net/browse/CTZ-279
=> fix: Missing notifiers for priorities & some inquiry changes

apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/AppLogsFilter.tsx, apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.spec.tsx, apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.stories.tsx, apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/ExportLogsModal.tsx
The checks for the 'All' option was missing on the Logs export Modal, causing the export to fail. This PR fixes that and adds a test for the specific issue
[ALT-26](https://rocketchat.atlassian.net/browse/ALT-26)
[ALT-26]: https://rocketchat.atlassian.net/browse/ALT-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: add missing check for 'all' in app logs export

apps/meteor/app/ui-utils/client/lib/MessageAction.ts, apps/meteor/client/components/message/toolbar/MessageToolbarActionMenu.tsx, apps/meteor/client/components/message/toolbar/MessageToolbarStarsActionMenu.tsx, apps/meteor/client/components/message/toolbar/useDeleteMessageAction.ts, apps/meteor/client/components/message/toolbar/useReportMessageAction.tsx
[ARCH-1722](https://rocketchat.atlassian.net/browse/ARCH-1722)
[ARCH-1722]: https://rocketchat.atlassian.net/browse/ARCH-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove deprecated flag of `MessageActionConfig`

apps/meteor/ee/server/apps/communication/endpoints/appLogsExportHandler.ts
Workaround the `API_Upper_Count_Limit` setting in the logs export endpoint to increase the max count of records to 2000
[ALT-28]
[ALT-28]: https://rocketchat.atlassian.net/browse/ALT-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: logs export endpoint limited to 100 records

.changeset/silly-laws-act.md, packages/http-router/src/Router.spec.ts, packages/http-router/src/Router.ts
**Description**
This PR fixes a bug in the HTTP route validation method where it was returning the wrong error message. Previously, it returned `'error-invalid-params'` instead of the expected `'invalid-params'`.
**Changes**
- Updated the HTTP route validation method to return `'invalid-params'` as intended.
**Motivation**
Returning the correct error message ensures consistency with our error handling standards and prevents potential issues in clients relying on specific error codes.
**Run OAuthApps Tests**
```bash
yarn testapi -f '[OAuthApps]'
[OAuthApps]
[/oauth-apps.list]
✔ should return an error when the user does not have the necessary permission (254ms)
✔ should return an array of oauth apps (201ms)
[/oauth-apps.create]
✔ should return an error when the user does not have the …
```
=> fix: update error type for invalid parameters in Router class

.changeset/eleven-buses-return.md, apps/meteor/app/livechat/server/lib/RoutingManager.ts
=> fix: Remove room assignment before queueing the conversation again when transfering

.changeset/strange-worms-smoke.md, apps/meteor/app/api/server/v1/oauthapps.ts, packages/rest-typings/src/v1/oauthapps.ts
https://rocketchat.atlassian.net/browse/ARCH-1730
**Description:**  
This PR integrates OpenAPI support into the `Rocket.Chat API`, migrate of `Rocket.Chat API` endpoints to the new OpenAPI pattern. The update includes improved API documentation, enhanced type safety, and response validation using AJV.
**Key Changes:**  
- **Implemented the new pattern** and added AJV-based JSON schema validation for API.  
- **Uses the ExtractRoutesFromAPI utility** from the TypeScript definitions to dynamically derive the routes from the endpoint specifications.
- **Enabled Swagger UI** integration for this API.
- **This does not introduce any breaking changes** to the endpoint logic.
**Issue Reference:**  
Relates to #34983, part of the ongoing OpenAPI integration effort.
**Testing:**
- Verified that …
=> feat: Add OpenAPI Support to oauth-apps.list API

.changeset/seven-donuts-confess.md, apps/meteor/app/api/server/v1/users.ts, apps/meteor/client/sidebar/header/EditStatusModal.tsx, apps/meteor/client/sidebar/header/UserMenuHeader.tsx, apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/index.ts, apps/meteor/tests/e2e/page-objects/modal.ts, apps/meteor/tests/e2e/presence.spec.ts, apps/meteor/tests/e2e/sidebar.spec.ts, apps/meteor/tests/e2e/user-required-password-change.spec.ts
This PR aims to fix an issue where the user custom status text doesn't update in real-time
- Open a DM with user A
- Change the custom status text of user A
- Check the changed custom status text of user A
[SUP-816]
[SUP-816]: https://rocketchat.atlassian.net/browse/SUP-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: User custom status text being overwritten

.changeset/bump-patch-1754921568025.md, .changeset/proud-drinks-crash.md, apps/meteor/ee/server/apps/storage/AppRealStorage.ts, yarn.lock
- Node: `22.16.0`
- Deno: `1.43.5`
- Apps-Engine: `1.54.0`
*   ([#36680](https://github.com/RocketChat/Rocket.Chat/pull/36680) by [@dionisio-bot](https://github.com/dionisio-bot)) fixes an issue where some apps that don't need permission would have grantedPermissions as null making it impossible to activate the app
*   @rocket.chat/core-typings@7.9.2
*   @rocket.chat/rest-typings@7.9.2
*   @rocket.chat/license@1.0.26
*   @rocket.chat/omnichannel-services@0.3.32
*   @rocket.chat/pdf-worker@0.3.14
*   @rocket.chat/presence@0.2.35
*   @rocket.chat/api-client@0.2.35
*   @rocket.chat/apps@0.5.14
* …
=> Release 7.9.2

apps/meteor/client/views/navigation/sidepanel/hooks/useChannelsChildrenList.spec.ts, apps/meteor/client/views/navigation/sidepanel/hooks/useChannelsChildrenList.ts, apps/meteor/tests/mocks/utils/createMockGlobalStore.ts, apps/meteor/tests/mocks/utils/index.ts
Introduced here: #36049
[SIDE2-126]
[SIDE2-131]
[SIDE2-126]: https://rocketchat.atlassian.net/browse/SIDE2-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE2-131]: https://rocketchat.atlassian.net/browse/SIDE2-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: SidePanel unread toggle not considering all types of unread

apps/meteor/client/views/navigation/sidepanel/tabs/SidePanelRooms.tsx
Introduced here: #36049
[SIDE2-132]
[SIDE2-132]: https://rocketchat.atlassian.net/browse/SIDE2-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Sidepanel being empty when no subscription

.changeset/popular-cars-float.md, apps/meteor/app/livechat/server/lib/RoutingManager.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts, packages/models/src/models/LivechatInquiry.ts
=> fix: enhance inquiry locking mechanism with timeout and error handling

apps/meteor/client/lib/cachedStores/CachedStore.ts
It correctly fails initialization of `CachedStore` instances i.e. mark them as _ready_ despite errors. It prevents suspend-and-remount loops over `SettingsProvider`.
[ARCH-1781](https://rocketchat.atlassian.net/browse/ARCH-1781)
This is critical for older versions of the desktop app, since they miss modern JavaScript features like `Set.prototype.difference`.
[ARCH-1781]: https://rocketchat.atlassian.net/browse/ARCH-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(desktop-app): Handle failure in `CachedStore` initialization

.changeset/polite-students-lick.md, packages/apps-engine/src/server/AppManager.ts
Fixes an unhandled promise rejection crash that would happen during server startup if any of the apps installed had a compile error.
```
Error while compiling the App "Poll (c33fa1a6-68a7-491e-bf49-9d7b99671c48)":
MongoRuntimeError: FileNotFound: file 68ae1211d4fb1c07f2a25c7e was not found
at handleReadResult (/home/douglas-gubert/.meteor/packages/npm-mongo/.6.10.2.1c1ehc0jglx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/src/gridfs/download.ts:318:19)
at processTicksAndRejections (node:internal/process/task_queues:105:5) {
code: 'ENOENT',
[Symbol(errorLabels)]: Set(0) {}
}
TypeError: this.appRuntime.on is not a function
at new ProxiedApp (/work/RocketChat/Rocket.Chat/packages/apps-engine/src/server/ProxiedApp.ts:27:19)
at …
```
=> fix: prevent unhandled promise rejection if app has compiler error on startup

apps/meteor/client/views/navigation/providers/RoomsNavigationProvider.tsx, apps/meteor/tests/e2e/feature-preview.spec.ts
Introduced here: #36049
[SIDE2-157]
[SIDE2-157]: https://rocketchat.atlassian.net/browse/SIDE2-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Avoid room filters redirect when opening a room

.changeset/old-meals-pull.md, apps/meteor/client/hooks/useAppSlashCommands.spec.tsx, apps/meteor/client/hooks/useAppSlashCommands.ts, packages/apps-engine/src/server/AppManager.ts, packages/apps-engine/src/server/managers/AppSlashCommandManager.ts, packages/apps-engine/tests/server/managers/AppSlashCommandManager.spec.ts
This PR modifies the app slash command registration method to improve the lifecycle management of slash commands during app initialization, disabling, and purging operations.
Changes Overview
1. **Client-side Hook Updates** (`useAppSlashCommands.ts`)
• Removed command/disabled from the event listener array - this prevents unnecessary command cleanup when apps are disabled, allowing commands to remain available during temporary app states
2. **App Manager Lifecycle Improvements** (`AppManager.ts`)
• Moved command registration from app enabling to app initialization phase
• Modified app disabling process to preserve slash commands (keepSlashcommands: true)
• Only remove commands upon uninstalling
[ARCH-1787]
[ARCH-1787]: https://rocketchat.atlassian.net/browse/ARCH-1787?atlOrigin=eyJpIjoiNWR …
=> fix: less strict slash command registration condition

apps/meteor/client/components/Omnichannel/OutboundMessage/components/AutoCompleteDepartmentAgent.tsx
**Before:**
**After:**
[CTZ-320](https://rocketchat.atlassian.net/browse/CTZ-320)
- Create new > Outbound message
- Fill out Recipient step, then next
- Fill out Message step, then next
- Select a department
- Click agent field
- Agent avatars should be correctly displayed
[CTZ-320]: https://rocketchat.atlassian.net/browse/CTZ-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(outbound): agent autocomplete displaying incorrect avatar

.changeset/two-pets-knock.md, apps/meteor/app/api/server/v1/roles.ts, apps/meteor/client/views/admin/permissions/UsersInRole/UsersInRolePage.tsx, apps/meteor/tests/end-to-end/api/roles.ts, packages/rest-typings/src/v1/roles.ts
Removes the deprecated `roleName` parameter from `/api/v1/roles.addUserToRole` and `/api/v1/roles.removeUserFromRole`
Removes the ability to pass a role name to the `role` parameter type from `/api/v1/roles.getUsersInRole`
[ARCH-1743](https://rocketchat.atlassian.net/browse/ARCH-1743)
[ARCH-1743]: https://rocketchat.atlassian.net/browse/ARCH-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove the ability to use role names as parameters on `/api/v1/roles.*` endpoints

.changeset/tidy-laws-wink.md, apps/meteor/client/views/marketplace/hooks/useAppMenu.tsx, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/tests/data/apps/apps-data.ts, apps/meteor/tests/data/apps/helper.ts, packages/rest-typings/src/apps/index.ts
Removes the deprecated `GET` Method from `/api/v1/apps`
[ARCH-1765](https://rocketchat.atlassian.net/browse/ARCH-1765)
[ARCH-1765]: https://rocketchat.atlassian.net/browse/ARCH-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove `GET` method from `/api/v1/apps`
