RocketChat/Rocket.Chat

app/theme/client/imports/components/popover.css
app/ui-utils/client/lib/popover.html

Regression: Missing padding in popover with custom template

---

app/livechat/server/methods/sendMessageLivechat.js

[FIX] Fix no message size limit for method sendMessageLivechat

---

app/api/server/api.d.ts
app/api/server/v1/voip/extensions.ts
app/api/server/v1/voip/logger.ts
app/api/server/v1/voip/queues.ts
app/api/server/v1/voip/server-config.ts
app/models/server/raw/VoipServerConfiguration.ts

Chore: Fixing merge related issues with develop branch.

---

client/views/room/hooks/useUserInfoActions.js
definition/rest/v1/teams/TeamsRemoveMemberProps.spec.ts
tests/end-to-end/api/25-teams.js

[FIX] teams.removeMembers client usage

---

client/views/admin/apps/AppSetting.js

Derived from PR https://github.com/RocketChat/Rocket.Chat/pull/19238
Fixes https://github.com/RocketChat/Rocket.Chat/issues/19237

[FIX] Translations for App Select Settings not working

---

app/ui-utils/client/lib/popover.js

Closes #23599
- change the RC language to some arabic language.
- Userdrop down goes out of the screen on rightside

[FIX] Popover position for arabic languages

---

server/features/EmailInbox/EmailInbox_Incoming.ts

[FIX] Transferring to wrong department for incoming emails

---

app/threads/client/flextab/thread.js
app/ui/client/lib/chatMessages.js

Removing edit message from messageBox and local storage on messageBox destroyed.
1 - Start editing a message
2 - Select another room before sending the edit message
3 - Return to the original room

[FIX] Removing Edit message from messageBox on room changed

---

app/threads/client/threads.css

[FIX] Missing edit icon in sequential thread messages

---

app/ui-message/client/actionButtons/messageAction.ts
app/ui-message/client/actionButtons/messageBox.ts
app/ui-message/client/actionButtons/tabbar.ts

The names registered by the buttons weren't being translated

Handle translation of the buttons names

---

server/modules/notifications/notifications.module.ts

A rule on the user notification streamer was changed recently, and the check for writing on the streamer was wrong. Changed it to allow all logged users.
Closes #23874
Closes #20791

[FIX] OTR not working

---

client/views/admin/integrations/OutgoiongWebhookForm.js
client/views/admin/integrations/edit/EditOutgoingWebhook.js

Fixes #23900
https://user-images.githubusercontent.com/76481696/145239914-85e19632-d034-42ad-bd13-7c1fe85fad7a.mp4
https://user-images.githubusercontent.com/76481696/145241855-006db6a8-c8df-4594-9cd1-6dcd726b45b6.mp4
Fixes #23900

[FIX] broken `Word Placement Anywhere` and `Run on edits` toggles in integration page

---

packages/rocketchat-i18n/i18n/af.i18n.json
packages/rocketchat-i18n/i18n/ar.i18n.json
packages/rocketchat-i18n/i18n/az.i18n.json
packages/rocketchat-i18n/i18n/bg.i18n.json
packages/rocketchat-i18n/i18n/bs.i18n.json
packages/rocketchat-i18n/i18n/cy.i18n.json
packages/rocketchat-i18n/i18n/da.i18n.json
packages/rocketchat-i18n/i18n/de-AT.i18n.json
packages/rocketchat-i18n/i18n/de-IN.i18n.json
packages/rocketchat-i18n/i18n/el.i18n.json
packages/rocketchat-i18n/i18n/eo.i18n.json
packages/rocketchat-i18n/i18n/fi.i18n.json
packages/rocketchat-i18n/i18n/id.i18n.json
packages/rocketchat-i18n/i18n/ku.i18n.json
packages/rocketchat-i18n/i18n/lo.i18n.json
packages/rocketchat-i18n/i18n/mn.i18n.json
packages/rocketchat-i18n/i18n/ms-MY.i18n.json
packages/rocketchat-i18n/i18n/ro.i18n.json
packages/rocketchat-i18n/i18n/sl-SI.i18n.json
packages/rocketchat-i18n/i18n/sq.i18n.json
packages/rocketchat-i18n/i18n/ta-IN.i18n.json
packages/rocketchat-i18n/i18n/th-TH.i18n.json
packages/rocketchat-i18n/i18n/vi-VN.i18n.json
packages/rocketchat-i18n/i18n/zh-HK.i18n.json

I checked all the links and found that only the link in the RetentionPolicyRoom_ReadTheDocs was broken in some languages.

[FIX] Broken links present in some languages

---

app/authorization/server/functions/upsertPermissions.ts
packages/rocketchat-i18n/i18n/ca.i18n.json
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/es.i18n.json
packages/rocketchat-i18n/i18n/fr.i18n.json
packages/rocketchat-i18n/i18n/nl.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
server/startup/migrations/index.ts
server/startup/migrations/v250.ts

- Remove the `mobile-download-file` permission and its descriptions.
Searching for the `mobile-download-file` permission in **Administration > Permissions** should return no results.

Chore: Remove the `mobile-download-file` permission

---

app/push-notifications/client/tabBar.ts
client/contexts/UserContext.ts
client/views/room/contextualBar/NotificationPreferences/NotificationPreferencesWithData.js

Before, when you look at the notification rules of a room in which you are not a member the app crashed, i corrected this problem.
Indeed, there was a not check if the subscription was undefined
https://user-images.githubusercontent.com/45966964/117164748-35572c00-adc5-11eb-83fa-314dc2490940.mp4
Closes #21964

[FIX] Prevent the app from crashing when you look at the notification preferences of a room in which you are not a member

---

client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelCoreSourceRoomIcon.tsx
client/hooks/useRoomIcon.tsx
client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
definition/IRoom.ts

Regression: Fix omnichannel empty source usage

---

server/startup/migrations/index.ts
server/startup/migrations/v252.ts

Add a migration to add source property to all the omnichannel rooms which don't have it yet. All these rooms will have source type as `other`

Regression: Add migration for omni rooms with no source

---

app/lib/client/startup/settingsOnLoadSiteUrl.ts
client/startup/absoluteUrl.ts

Regression: Let Meteor.absoluteUrl.defaultOptions.rootUrl as baseURI

---

app/push-notifications/client/tabBar.ts
app/ui/client/lib/chatMessages.js

Regression: addAction verification breaking rooms

---

app/ui-message/client/ActionButtonSyncer.ts

A empty array have been printed to console due to a promise chained to `console.log` and `console.error` calls, probably for debugging purposes.

Regression: Remove dangling console.log

---

app/ui/client/lib/chatMessages.js
app/ui/client/views/app/room.js

Regression: Add optional chaining to possibly undefined fields

---

package-lock.json
package.json

Update Apps-Engine version to latest. This is just a bump, no code has been changed in the package.

Chore: Update Apps-Engine to latest

---

app/oembed/server/server.js

fixes #19188
Appends Rocket.Chat/{version-info} into the user-agent header.
@geekgonecrazy @sampaiodiego please have a look at the PR and suggest for required changes.
#19188

[IMPROVE] Add Rocket.Chat version to User-Agent header for oembed requests

---

app/livechat/server/lib/Livechat.js
app/settings/server/CachedSettings.ts
packages/rocketchat-i18n/i18n/en.i18n.json

Turn off Omnichannel from Admin -> Omnichannel
The start an omnichannel conversation from anywhere like LiveChat, API, app, etc. The simplest way would be to go to `{serverUrl}/livechat` and send a message.
**Before:** The conversation will be started
**Expected Behaviour:** An error should be thrown stating that omnichannel is disabled

[FIX] Omnichannel enabled setting not working when creating rooms

---

package-lock.json
package.json

It:
- Adds `Firefox ESR` to `browserslist`;
- Upgrades `@rocket.chat/fuselage-hooks` to overcome a bug related to Firefox implementation of `ResizeObserver` API.
Closed #24062

[FIX] Ensure Firefox 91 ESR support

---

app/mailer/server/api.ts

Introduction of new event `IPreEmailSent` was breaking the email function when the Apps-Engine framework was disabled in the administration
* Disable the "Enable the App Framework" option in `Admin > General`
* Send an email via `Admin > Mailer`

[FIX][APPS] Prevents emails from being sent when apps framework is disabled

---

app/apps/client/communication/websockets.js
app/ui-utils/client/lib/MessageAction.js
package-lock.json
package.json

Fixes a problem where action buttons registered by any app would not be removed if the app was disabled or uninstalled

[FIX][APPS] Action buttons not removed when app is disabled or uninstalled

---

.houston/metadata.js

Chore: Fix Houston `getNodeNpmVersions` regex to correctly get Node and Npm complete versions

---

app/api/server/api.js

Reverts RocketChat/Rocket.Chat#24053

Revert: "[IMPROVE] Throw 404 error in invalid endpoints"

---

docker-compose.yml

Including like this lets us do: `REG_TOKEN={token} docker-compose up -d` and it will insert it into the file.
I know we have at least two others working on the docker-compose file.  I'll modify / propose there too.  But this one is being actively used and we'd like to get this in so it can start to be used. 🙏

Chore: Include REG_TOKEN in docker-compose

---

app/apps/server/communication/methods.js

Switched to use the raw settings model.  Using the cachedSettings was causing an infinite loop while checking to see if the setting value was changed yet or not.  This way ensures that it is persisted.
https://forums.rocket.chat/t/stuck-with-enabling-apps-system-for-marketplace/12985

[FIX] App Framework Enable hanging indefinitely

---

client/components/UserCard/UserCard.js
client/sidebar/header/UserDropdown.tsx
client/views/room/Header/RoomHeader.tsx
client/views/room/contextualBar/UserInfo/UserInfo.js

This PR adds the possibility to use emoji on the custom status, below there are some examples of where the emoji will appear:

[NEW] Enabling emoji on custom status

---

package-lock.json
package.json

Chore: Update Apps-Engine to 1.29.2

---

app/emoji/client/lib/EmojiPicker.js

Limits the recent emoji list to a maximum of 3 rows instead of listing every emoji you've used so far.

[IMPROVE] Limit recent emojis to 27

---

ee/app/models/server/models/CannedResponse.js

[FIX] Change canned response model index to match other definition

---

client/sidebar/header/actions/Search.tsx
client/sidebar/search/SearchList.js

It migrates `client/sidebar/header/actions/Search` component to TypeScript and mitigates a invalid call to `Array.prototype.every`:

Regression: Remove extra call to `useOutsideClick` hook not following the function signature

---

definition/IVoipServerConfig.ts
server/services/voip/service.ts

This is a workaround for us to swiftly be able to use the default settings collection and system.
This will allow us to use the default settings ui for now, after the MVP we will discuss again a better way to maintain traceability.

[FIX] Workaround for use of the default settings collection

---

app/ui-utils/client/lib/MessageAction.js

After resolving issue #24261  :
https://user-images.githubusercontent.com/53515714/150629459-5f0a9cf6-9b0e-417f-8fc1-44c810bd5428.mp4
Issue Number: #24261 
Mention in issue number #24261

[FIX] Solved Report Message Blank 

---

app/models/server/models/LivechatDepartment.js
ee/app/models/server/models/LivechatDepartment.js

Fixes a bug introduced in https://github.com/RocketChat/Rocket.Chat/pull/24162 where inactive departments were also visible on the registration form if the business unit was set on Livechat

Regression: Fix Inactive Departments still visible on Livechat

---

app/api/server/v1/voip/extensions.ts
app/lib/server/startup/settings.ts
client/providers/CallProvider/hooks/useVoipClient.ts
definition/rest/v1/voip.ts

1. useVoipClient hook had hardcoded value for the extension. It was always using single extension regardless of what user is logging in. This has been fixed. Now it fetches the registration information based on the userId.
2. To support above, a new API has been added to app/api/server/v1/voip/extensions.ts which returns registrationinfo when userId is passed. Throws error if the agent is not associated with extension.
3. Removed user's personal account from app/lib/server/startup/settings.ts. Instead used organization specific account name for Voip Management Server.
1. When you have no agent-extension association, you would always see an error when you hover over "make agent available" phone button on top left of side bar. 
Testing Notes :
1. Test that proper registration information is …

[FIX] Cleaning up some hard coding in the Voip code.

---

client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelAppSourceRoomIcon.tsx
client/views/room/Header/HeaderIconWithRoom.js

Regression: Align Omni-Source icon sizes with designs

---

.meteor/packages
.meteor/versions

Regression: Update tap-i18n package

---

server/methods/loadHistory.js

[FIX] Discussions not loading message history if not joined

---

client/views/setupWizard/providers/SetupWizardProvider.tsx
client/views/setupWizard/steps/RegisterServerStep.tsx
client/views/setupWizard/steps/StandaloneServerStep.tsx

Regression: Standalone register path failing when saving data

---

client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelAppSourceRoomIcon.tsx
client/components/RoomIcon/OmnichannelRoomIcon/OmnichannelRoomIcon.tsx

Regression: Fix OmnichannelAppSourceRoomIcon sizes

---

package-lock.json
package.json

This is just a bump to the latest Apps-Engine release

Chore: Update Apps-Engine version

---

app/api/server/v1/voip/extensions.ts

[FIX] Test if extension exists

---

server/startup/migrations/index.ts
server/startup/migrations/v254.ts

Fix `bio` and `prid` startup index creation errors.
Closes #24347

[FIX] Startup errors creating indexes

---

app/integrations/server/lib/triggerHandler.js

[FIX] Outgoing webhook without scripts not saving messages

---

packages/rocketchat-i18n/i18n/en.i18n.json

1. Start the Setup wizard and complete until step 3
2. Hover the mouse over the icon next "Cloud account email" label.
Before:
After:

[FIX] typo on register server tooltip of setup wizard

---

app/authentication/server/startup/index.js
app/blockstack/server/userHandler.js
app/models/server/models/Users.js

[FIX] Create `findOneByRolesAndType` function

---

client/components/modal/ModalBackdrop.tsx
client/components/modal/ModalPortal.tsx
client/providers/ModalProvider.tsx

This is a QUICK change in order to close modals pressing Esc button and clicking outside of it **intentionally**.

[IMPROVE] Close modal on esc and outside click

---

.github/workflows/build_and_test.yml

Chore: Remove storybook build job from CI

---

app/models/server/raw/VoipRooms.ts
client/providers/CallProvider/CallProvider.tsx
definition/voip/IEvents.ts
server/modules/watchers/watchers.module.ts
server/services/omnichannel-voip/service.ts
server/services/voip/connector/asterisk/ami/ContinuousMonitor.ts

[NEW] Listen and broadcast hangup event

---

app/2fa/server/code/EmailCheck.ts
app/2fa/server/code/ICodeCheck.ts
app/2fa/server/code/index.ts
client/lib/2fa/process2faReturn.ts

[FIX] 2FA via email when logging in using OAuth

---

app/apps/server/converters/rooms.js
app/apps/server/converters/visitors.js

We're getting these types of errors on app's incoming webhook
I think it got introduced after this PR was merged: https://github.com/RocketChat/Rocket.Chat/pull/24305

Regression: Fix room not getting created due to null visitor status

---

ee/server/startup/broker.ts

This will essentially allow micro services from different deployments to share the same transporter.

Regression: Add support to namespace within micro services

---

app/lib/server/startup/settings.ts
client/providers/CallProvider/CallProvider.tsx

VoIP service button shouldn't be rendered if VoIP is not active on admin panel.

Regression: VoIP service button displayed when VoIP is disabled

---

app/ui-sidenav/client/sideNav.html

Regression: Admin Sidebar colors inverted.

---

packages/rocketchat-i18n/i18n/en.i18n.json

Regression: Fix translation for call started message

---

client/components/modal/ModalBackdrop.tsx

Regression: Mark all rooms as read modal closing instantly.

---

client/providers/CallProvider/CallProvider.tsx
client/views/admin/settings/GroupPage.tsx

Regression: Do not show toast on incoming voip calls

---

app/livechat/client/views/app/livechatReadOnly.html

While clicking on chat in queue, a message is displayed for a fraction of second at the bottom of room- "This conversation is already closed". After few seconds, it gets updated to "You are in preview mode of this chat - Take it!".

Regression: Fix in-correct room status shown to agents

---

server/services/voip/service.ts

If voip credentials are in-valid, then the server was crashing. This PR fixes this issue

Regression: Server crashing if Voip credentials are invalid

---

app/lib/server/startup/settings.ts
client/views/admin/settings/groups/VoipGroupPage.tsx

The existing `Tab name` for VoIP settings doesn't meet the expected/original design.
Before:
After:

Regression: Fix wrong tab name for VoIP settings

---

client/lib/voip/VoIPUser.ts
client/sidebar/sections/components/OmnichannelCallToggleReady.tsx

Regression: Prevent button from losing state when rerendering

---

server/lib/logger/getPino.ts

Production logs (in JSON format) had a duplicated `name` key. While this is ignored in JS it may be a problem for different JSON parsers.
Before:
```
I20220223-00:10:38.662(-3)? {"level":51,"time":"2022-02-23T03:10:38.662Z","pid":13033,"hostname":"Diegos-MacBook-Pro.local","name":"","name":"Migrations","msg":"Not migrating, already at version 256"}
```
After:
```
I20220223-00:10:38.662(-3)? {"level":51,"time":"2022-02-23T03:10:38.662Z","pid":13033,"hostname":"Diegos-MacBook-Pro.local","name":"Migrations","msg":"Not migrating, already at version 256"}
```

[FIX] Duplicated 'name' log key

---

app/importer/server/classes/ImportDataConverter.ts

- Fix missing sender's username on messages imported from Slack.
Before:
After:

[FIX] Missing username on messages imported from Slack

---

app/lib/server/functions/insertMessage.js

- Fix rooms' message counter not being incremented on message import.
1. Go to **Administration > Import** and complete the import process;
2. Go to **Administration > Rooms** and check if the Message counter has been updated accordingly in every imported room.

[FIX] Room's message count not being incremented on import

---

client/lib/voip/Stream.ts

[IMPROVE] Fixing LGTM error. Extra |=| got added in a statement causing LGTM to fail.

---

app/nextcloud/lib/common.js

Recent changes removed the callback parameter from CachedSettings.get, this changes use to CachedSettings.watch instead.
Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>
Closes https://github.com/RocketChat/Rocket.Chat/issues/22821

[FIX] Nextcloud OAuth for incomplete token URL

---

app/lib/server/functions/saveUser.js
tests/end-to-end/api/01-users.js

Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>

[FIX] API Error preventing adding an email to users without one (like bot/app users)

---

server/lib/logger/Logger.ts

Chore: Improve logger to allow log of `unknown` values

---

client/views/room/MessageList/components/Toolbox/MessageActionMenu.tsx
client/views/room/MessageList/components/Toolbox/ToolboxDropdown.tsx
client/views/room/MessageList/components/Toolbox/ToolboxDropdownDesktop.tsx
client/views/room/MessageList/components/Toolbox/ToolboxDropdownMobile.tsx

[FIX] Toolbox on close behavior

---

.mocharc.js
ee/server/services/presence/actions/updateUserPresence.ts
ee/server/services/presence/lib/processConnectionStatus.tests.ts
ee/server/services/presence/lib/processConnectionStatus.ts

The presence micro service was not computing user's status correctly, so I added a few unit tests to ensure they're being handled correctly.

[FIX][ENTERPRISE] Presence micro service logic

---

ee/server/services/ddp-streamer/Server.ts
ee/server/services/ddp-streamer/configureServer.ts
server/modules/streamer/streamer.module.ts
server/sdk/errors.ts
server/services/meteor/service.ts

[FIX] DDP streamer errors

---

app/api/server/v1/voip/omnichannel.ts
app/models/server/raw/Users.js
client/components/AutoCompleteAgentWithoutExtension.tsx
client/components/Omnichannel/hooks/useAvailableAgentsList.ts
client/views/admin/settings/groups/voip/AssignAgentModal.tsx
definition/rest/v1/voip.ts
server/sdk/types/IOmnichannelVoipService.ts
server/services/omnichannel-voip/service.ts

[FIX] Show only available agents on extension association modal

---

ee/server/services/ddp-streamer/Publication.ts
ee/server/services/ddp-streamer/Streamer.ts
ee/server/services/package-lock.json

[FIX][ENTERPRISE] DDP streamer not sending data to all clients

---

server/lib/isPresenceMonitorEnabled.ts

[IMPROVE][ENTERPRISE] Don't start presence monitor when running micro services

---

app/lib/server/functions/createRoom.js
server/services/team/service.ts

- Do not send system messages when adding or removing a new or existing _group_ from a team.
1. Create a new team;
2. Go to Channels and add a new channel (public room) to the team. A system message should be sent when using any option ("Create new" or "Add existing");
3. Go to Channels and add a new group (private room) to the team. No system messages should be sent (neither using the "Create new" option, nor "Add existing");

[FIX] System messages are sent when adding or removing a group from a team

---

CODE_OF_CONDUCT.md

Chore: Fix grammatical errors in Code of Conduct

---

CODE_OF_CONDUCT.md
FEATURES.md

Chore: fix grammatical errors in Features

---

client/views/login/AppleOauth/AppleOauthButton.tsx

[FIX] Apple login script being loaded even when Apple Login is disabled.

---

client/views/room/MessageList/MessageList.tsx
client/views/room/MessageList/components/Message.tsx
client/views/room/MessageList/components/MessageContent.tsx
client/views/room/MessageList/components/MessageContentIgnored.tsx
client/views/room/MessageList/components/MessageHeader.tsx
client/views/room/MessageList/components/ThreadMessage.tsx
client/views/room/MessageList/components/ThreadMessagePreview.tsx
definition/IMessage/IMessage.ts
definition/ISubscription.ts

[NEW] Add Message ignored component

---

client/views/room/MessageList/components/Message.tsx
client/views/room/contexts/MessageContext.ts
client/views/room/providers/MessageProvider.tsx

[FIX] Reply broadcast

---

client/views/admin/settings/groups/VoipGroupPage.tsx
packages/rocketchat-i18n/i18n/en.i18n.json

[IMPROVE] Voip Extensions disabled state

---

ee/server/services/ddp-streamer/DDPStreamer.ts
ee/server/services/ddp-streamer/configureServer.ts
ee/server/services/ddp-streamer/lib/Autoupdate.ts
server/sdk/lib/Events.ts
server/sdk/types/IMeteor.ts
server/services/meteor/service.ts
server/services/startup.ts

[FIX][ENTERPRISE] Auto reload feature of ddp-streamer micro service

---

app/dolphin/lib/common.js
app/drupal/lib/common.js
app/github-enterprise/lib/common.js
app/gitlab/lib/common.js
app/tokenpass/lib/common.js

Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>
Closes #24704
- GitHub
- GitLab
- Drupal
- Dolphin
- Tokenpass

[FIX] Broken multiple OAuth integrations

---

client/views/admin/settings/groups/VoipGroupPage.tsx

[FIX] VoipExtensionsPage component call

---

app/ui-message/client/message.html
app/ui-message/client/message.js
app/ui/client/lib/chatMessages.js

[FIX] Edit not working in old template.

---

client/views/room/MessageList/MessageList.tsx
client/views/room/MessageList/lib/isMessageSequential.spec.ts
client/views/room/MessageList/lib/isMessageSequential.ts

[FIX] Sequential messages

---

server/services/startup.ts

Turned out other parts of the code are calling some services before `Meteor.startup` , which were failing because services were not yet registered.
A better solution to services lifecycle should be put in place before moving register services to `Meteor.startup`.

Regression: Register services right away

---

client/sidebar/sections/components/OmnichannelCallToggleReady.tsx
definition/voip/VoIpCallerInfo.ts

[FIX] Prevent call button toggle when user is on call

---

app/livechat/server/api/lib/livechat.js
app/livechat/server/api/v1/videoCall.js

We're getting the following error when calling the `livechat/webrtc.call` endpoint.
`TypeError: Cannot destructure property 'businessUnit' of 'undefined' as it is undefined.`

[FIX] "livechat/webrtc.call" endpoint not working

---

app/livechat/server/lib/Livechat.js

**Prerequisite:**  Server with the Facebook app installed and set up. Plus the FB account should have at least 2 page.
1. Customer sends a message to a FB Page.
2. RC displays it on the Queue 
3. RC Agent takes it and a room is started
4. Another customer sends another message from a different FB Page.
5. RC displays it on the Queue 
6. The new customer goes to the same room previously created
7. RC Agent sends a message and only the first customer gets it.
Expected Behavior:
FB App should create an individual room for any new customer from any FB Page.
Actual Behavior:
FB App creates a single room for all customers from any FB Page associated with the FB

[FIX] Critical: Incorrect visitor getting assigned to a chat from apps

---

definition/rest/v1/settings.ts

Created typing for endpoint definitions on `settings.ts`.

Chore: added settings endpoint types

---

client/views/room/Header/ParentRoomWithEndpointData.tsx

Regression: Fix ParentRoomWithEndpointData in loop

---

app/livechat/client/views/app/tabbar/visitorForward.js
client/components/Omnichannel/hooks/useDepartmentsList.ts
client/components/Omnichannel/modals/ForwardChatModal.js

[FIX] Show only enabled departments on forward

---

server/services/voip/service.ts

[FIX] Wrong param usage on queue summary call

---

app/livechat/client/lib/stream/queueManager.js
app/livechat/imports/server/rest/inquiries.js
app/livechat/server/api/lib/inquiries.js
package-lock.json

[IMPROVE] Standarize queue behavior for managers and agents when subscribing

---

client/providers/CallProvider/hooks/useVoipClient.ts

2 PRs were touching the same file, one removed a declaration and the other file was using that declaration, this caused develop to have a file using an undeclared variable.

[FIX] Broken build caused by PRs modifying same file differently

---

.houston/metadata.js

Fix changelog from looking like this:
- Node: `14.18.3`
- NPM: `6.14.15`
- MongoDB: `&#x27;3.6&#x27;, &#x27;4.0&#x27;, &#x27;4.2&#x27;, &#x27;4.4&#x27;, &#x27;5.0&#x27;`
- Apps-Engine: `1.31.0`
To look like this
- Node: `14.18.3`
- NPM: `6.14.15`
- MongoDB: `3.6, 4.0, 4.2, 4.4, 5.0`
- Apps-Engine: `1.31.0`

Chore: Fix MongoDB versions on release notes

---

client/providers/CallProvider/CallProvider.tsx

[FIX] Missing dependency on useEffect at CallProvider

---

app/models/server/raw/LivechatBusinessHours.ts
ee/app/livechat-enterprise/server/business-hour/Multiple.ts

Pre Condition- Enable multiple Business Hours (BH)
1. Make sure a default BH is created and BH is active.
2. Associate an agent with ONLY a department that doesn't have any BH connected to it. 
3. As an agent, click on omnichannel icon.
Expected Behaviour:  Since the default BH is active & this agent isn't connected to any department that has a BH linked to it, the default BH should be applied to this agent & he should be able to turn the status on
Current Behaviour: Agent is getting a message saying "Business Hour is Closed"

[FIX] Wrong business hour behavior

---

packages/rocketchat-i18n/i18n/ar.i18n.json
packages/rocketchat-i18n/i18n/ca.i18n.json
packages/rocketchat-i18n/i18n/de.i18n.json
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/es.i18n.json
packages/rocketchat-i18n/i18n/fr.i18n.json
packages/rocketchat-i18n/i18n/ja.i18n.json
packages/rocketchat-i18n/i18n/nl.i18n.json
packages/rocketchat-i18n/i18n/pl.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/ru.i18n.json
packages/rocketchat-i18n/i18n/zh-TW.i18n.json

[FIX] DDP Rate Limiter Translation key

---

ee/server/services/account/Account.ts
ee/server/services/account/lib/utils.ts
ee/server/services/ddp-streamer/configureServer.ts

Regression: Fix account service login expiration

---

app/meteor-accounts-saml/server/lib/Utils.ts
app/meteor-accounts-saml/server/lib/parsers/Response.ts

If its ever anything but a string.  Like an array for example It breaks every location that loads in a user list because of the aggregations done to bring in users. 
When running one of our typical aggregations to load user list like:
```
db.users.aggregate([ { $match: {"$or":[{"emails.address":{"$regex":"","$options":"i"}},{"username":{"$regex":"","$options":"i"}}, {"name":{"$regex":"","$options":"i"}}]}, }, { $project: { name: 1, username: 1, emails: 1, roles: 1, status: 1, active: 1, avatarETag: 1, lastLogin: 1, }, }, { $addFields: { nameInsensitive: { $toLower: '$name', }, }, }, { $facet: { sortedResults: [ { $sort: { nameInsensitive: 1, name: 1 }, }, { $skip: 0, }, ], totalCount: [{ $group: { _id: null, total: { $sum: 1 } } }], }, }, ]);
```
And if we haven't force this to string and …

[FIX] Force name to string

---

app/ui-login/client/login/form.js
client/views/invite/SecretURLPage.tsx

Fixes #24444 
Fixes #24853
Fixes #24719
- Go to `Administration` -> `Accounts` -> `Registration`
- Get your `Registration Form Secret URL` and change the `Registration Form` option to "Secret URL"
- Now, try to open the link as configured (e.g. [https://chat.mydomain.de/register/[secret_hash]]

[FIX] Register with Secret URL

---

definition/IUser.ts
definition/rest/index.ts
definition/rest/v1/channels.ts
definition/rest/v1/chat.ts
definition/rest/v1/directory.ts
definition/rest/v1/e2e.ts
definition/rest/v1/groups.ts
definition/rest/v1/im.ts
definition/rest/v1/omnichannel.ts

On the [mobile client](https://github.com/RocketChat/Rocket.Chat.ReactNative), we made an effort to collect more `REST API` definitions that are missing on the server side during our migration to TypeScript. Since we're both migrating to TypeScript, we thought it would be a good idea to share those so you guys can benefit from our initiative.
If there is anything else needed (tests, comments, etc) please let me know 🙈

Chore: add some missing REST definitions

---

app/lib/lib/MessageTypes.js
app/lib/server/functions/archiveRoom.ts
app/lib/server/functions/unarchiveRoom.ts

- Send the "Room archived" and "Room unarchived" system messages when editing room settings (and not only when rooms are archived/unarchived with the slash-command);
- Fix the "Hide System Messages" option for the "Room archived" and "Room unarchived" system messages;
1. Create a room, then go to **Room Information > Edit**, toggle the "Archived" setting and hit "Save". A system message should be sent ("_This room has been archived by @/user_");
2. Toggle the "Archived" setting again and hit "Save". A system message should be sent ("_This room has been unarchived by @/user_");
3. The "Hide System Messages" option should also work for both system messages.

[FIX] Room archived/unarchived system messages aren't sent when editing room settings

---

package-lock.json
package.json

Chore: Update Livechat

---

app/lib/server/functions/createDirectRoom.ts
app/ui-utils/client/lib/RoomManager.js
app/ui-utils/client/lib/openRoom.js
client/sidebar/search/UserItem.js
lib/rooms/coordinator.ts

When the room object is searched for the first time, it does not exist on the front object yet (subscription), adding a fallback search for room list will guarantee to search the room details.
before:
https://user-images.githubusercontent.com/9275105/160223241-d2319f3e-82c5-47d6-867f-695ab2361a17.mp4
after:
https://user-images.githubusercontent.com/9275105/160223244-84d0d2a1-3d95-464d-8b8a-e264b0d4d690.mp4
Create a direct message to a user that has never chatted before. It should not open the chat room details.
Screenshot:
The room detail only appears after page refresh:
This is an intermittent issue.

[FIX] room message not load when is a new message

---

client/views/room/MessageList/components/MessageHeader.tsx
client/views/room/MessageList/components/MessageSystem.tsx
client/views/room/contexts/MessageContext.ts
client/views/room/providers/MessageProvider.tsx

[FIX] Add title with date and time

---

app/models/server/models/Rooms.js
app/statistics/server/functions/otrStats.ts
app/statistics/server/lib/statistics.ts

Regression: Add createdOTR index

---

client/components/UserAutoComplete/UserAutoComplete.js

[FIX] UserAutoComplete not rendering UserAvatar correctly

---

client/views/admin/sidebar/AdminSidebarPages.tsx

[FIX] Upgrade Tab showing for a split second

---

.github/workflows/build_and_test.yml

Co-authored-by: Thassio Victor <tvmcarvalho@gmail.com>
Signed-off-by: Debdut Chakraborty <debdut.chakraborty@rocket.chat>

Chore: Cancel running jobs if PR is updated

---

app/theme/client/imports/general/base_old.css

[FIX] Prevent sequential messages edited icon to hide on hover

---

client/hooks/useEndpointUpload.ts
client/hooks/useMethodData.ts

[FIX] FormData uploads not working

---

client/views/room/MessageList/components/MessageHeader.tsx
client/views/room/MessageList/components/MessageRolesList.tsx
client/views/room/MessageList/hooks/useMessageRoles.ts

[FIX] Roles not displaying

---

client/views/invite/InvitePage.tsx

Closes #24719 
Closes #24853 
- Goto Channel members list.
- click on invite link and copy the invite link
- open this link in a new incognito window
- No registration form shown

[FIX] Invitation links don't redirect to the registration form

---

client/sidebar/footer/voip/VoipFooter.tsx

[FIX] End call button disappearing when on-hold

---

client/views/admin/sidebar/UpgradeTab.tsx
client/views/admin/upgrade/UpgradePage/UpgradePage.tsx
lib/getUpgradeTabType.ts
tests/unit/lib/getUpgradeTabType.spec.ts

Change 'upgrade tab' routes names from camelCase ('goFullyFeatured') to kebab-case ('go-fully-featured') due to URL naming consistency. Changed types, main function and test.

[IMPROVE] Rename upgrade tab routes

---

apps/meteor/app/api/server/api.d.ts
apps/meteor/app/oauth2-server-config/server/oauth/oauth2-server.ts
apps/meteor/definition/externals/meteor/oauth2server.d.ts

Chore: Migrate oauth2server to typescript

---

client/components/Page/PageHeader.tsx
client/views/admin/apps/AppDetailsPage.tsx

Changed the design for the page header of the app details page from a title on the left with a save and back button on the right to an back arrow icon on the left side of the title with the save button still on the right. Also changed the title of the page from App details to Back.
Demo gif:

[NEW] :sparkles: New page header app details page marketplace

---

apps/meteor/app/ui/client/views/app/lib/getCommonRoomEvents.js

[FIX] Message menu action not working on legacy messages.

---

apps/meteor/client/components/Message/Metrics/Thread.tsx
apps/meteor/client/components/Message/NotificationStatus/All.tsx
apps/meteor/client/components/Message/NotificationStatus/Me.tsx
apps/meteor/client/components/Message/NotificationStatus/NotificationStatus.js
apps/meteor/client/components/Message/NotificationStatus/NotificationStatus.tsx
apps/meteor/client/components/Message/NotificationStatus/Unread.tsx
apps/meteor/client/views/room/contextualBar/Threads/components/Message.js

Chore: Convert NotificationStatus to TS

---

apps/meteor/docker-compose.yml
apps/meteor/tests/e2e/09-channel.spec.ts
apps/meteor/tests/e2e/utils/mocks/channel.ts
apps/meteor/tests/e2e/utils/mocks/checks.ts
apps/meteor/tests/e2e/utils/mocks/interations.ts
apps/meteor/tests/e2e/utils/pageobjects/FlexTab.ts
apps/meteor/tests/e2e/utils/pageobjects/Global.ts
apps/meteor/tests/e2e/utils/pageobjects/SideNav.ts

Chore: Tests with Playwright (task: ROC-28, 09-channels)

---

package.json

Regression: yarn dev triggers build dependencies

---

apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
apps/meteor/client/views/room/MessageList/contexts/MessageListContext.tsx
apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
packages/core-typings/src/IMessage/IMessage.ts

The read receipts were not checking if the message was read or not.

[FIX] Read receipts showing before message read

---

apps/meteor/client/views/room/MessageList/components/Toolbox/ToolboxDropdownDesktop.tsx

[FIX] Toolbox hiding under contextual bar

---

apps/meteor/app/api/server/v1/voip/omnichannel.ts
apps/meteor/app/models/server/raw/Users.js
apps/meteor/client/components/AutoCompleteAgentWithoutExtension.tsx
apps/meteor/client/views/admin/settings/groups/voip/AssignAgentModal.tsx
packages/rest-typings/src/v1/voip.ts

[IMPROVE] Add support for filters on omnichannel/extensions endpoint

---

apps/meteor/app/models/server/raw/IntegrationHistory.ts

Adds an index to expire after 30 days integration history items.  With out it if you have a particularly failure heavy integration you could end up with terabytes worth of failure logs.  
Lets save hard drives and clean up logs. :)

[NEW] Add expire index to integration history

---

apps/meteor/app/lib/server/functions/createRoom.ts

[FIX] room creation fails if app framework is disabled

---

apps/meteor/client/views/room/MessageList/components/MessageHeader.tsx
apps/meteor/client/views/room/MessageList/components/MessageSystem.tsx

Show username and real name on the message system and also add cursor pointer to username and real name label.

Regression: Show username and real name on the message system

---

apps/meteor/package.json
yarn.lock

Chore: Update Livechat to the last version

---

apps/meteor/app/livechat/lib/Assets.js

[FIX] Incorrect websocket url in livechat widget

---

package.json

Houston config in the `package.json` file still mentioned `package-lock.json`, but it doesn't exist anymore

Chore: Remove package-lock.json from houston files

---

package.json

Chore: Add root package.json to houston files

---

apps/meteor/ee/server/services/Dockerfile

The new yarn plugin to check node version was failing as you can see at:
https://github.com/RocketChat/Rocket.Chat/runs/6135689148?check_suite_focus=true#step:5:1003

Regression: Use exact Node version on micro services Docker images

---

apps/meteor/ee/server/services/authorization/service.ts

Regression: Shows error if micro service cannot connect to Mongo

---

apps/meteor/client/views/room/MessageList/components/Message.tsx
packages/core-typings/src/IMessage/IMessage.ts

Add pending status to message template

Regression: Add `isPending` status to message

---

apps/meteor/package.json
yarn.lock

Regression: Revert Bugsnag version

---

.github/workflows/build_and_test.yml
apps/meteor/ee/server/services/Dockerfile

Since the step to build Docker images for microservices only runs **after** it is merged to `develop`, I've created a new step so it will try to build `ddp-streamer` when Opening a PR as well, so we can see if it is going to succeed.

Regression: Add eslint package to micro services Dockerfile

---

apps/meteor/client/components/Message/Metrics/Thread.tsx
apps/meteor/client/views/room/contexts/MessageContext.ts
apps/meteor/client/views/room/providers/MessageProvider.tsx

The reply button is not working in workspace with the configuration hideFlexTab enabled. Because the onClick is bubbling to room template and triggering the close of the thread view.

Regression: Fix reply button not working when hideFlexTab is enabled

---

apps/meteor/client/views/room/MessageList/hooks/useMessages.ts

Regression: Messages in new message template Crashing.

---

apps/meteor/server/modules/listeners/listeners.module.ts

This will fix a bug when the user receives some notifications. The message was not formatted.
before:
after:

Regression: Parser message when notify ephemeral message

---

apps/meteor/client/views/setupWizard/contexts/SetupWizardContext.tsx
apps/meteor/client/views/setupWizard/providers/SetupWizardProvider.tsx
apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
apps/meteor/package.json
yarn.lock

- Bump to 'next' the onboarding-ui package from fuselage.
- Update from 'companyEmail' to 'email' adminData usage types
Related to https://github.com/RocketChat/Rocket.Chat/pull/25260

Regression: bump onboarding-ui version

---

apps/meteor/client/views/admin/apps/AppDetailsPage.tsx
apps/meteor/client/views/admin/apps/AppDetailsPageContent.tsx
apps/meteor/client/views/admin/apps/types.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json

Implemented markdown on the description section of the app details page, now the description will show the detailedDescription.rendered (as rendered JSX) information in case it exists and show the description (a.k.a. short description) information in case it doesn't. Unfortunately, as of right now no app has a visual example of a markdown description and because of that, I will not be able to provide a demo image/gif for this PR.

[NEW] Description tab marketplace

---

apps/meteor/app/ui-utils/client/lib/openRoom.js
apps/meteor/app/ui/client/views/app/room.js

Fix: livechat room not opening.

Regression: Fix clicking on visitor's chat in the sidebar does not display the chat window

---

apps/meteor/client/contexts/ServerContext/methods.ts
apps/meteor/client/views/admin/federationDashboard/FederationDashboardPage.tsx
apps/meteor/client/views/admin/federationDashboard/OverviewSection.tsx
apps/meteor/client/views/admin/federationDashboard/ServersSection.tsx

Chore: Convert federationDashboard folder to ts

---

apps/meteor/ee/server/services/package.json
apps/meteor/package.json
package.json

[Volta](https://volta.sh/) need some extra configuration to work on monorepos.

Chore: Update Volta configuration

---

apps/meteor/app/ui-utils/client/lib/SideNav.ts
apps/meteor/client/views/admin/sidebar/AdminSidebar.tsx
apps/meteor/client/views/omnichannel/components/Field.js
apps/meteor/client/views/omnichannel/components/Field.tsx
apps/meteor/client/views/omnichannel/components/Label.js
apps/meteor/client/views/omnichannel/components/Label.tsx
packages/rest-typings/src/v1/customUserStatus.ts

Chore: Convert AdminSideBar to ts

---

apps/meteor/client/hooks/useUpdateAvatar.ts
packages/rest-typings/src/v1/users.ts

Chore: Convert useUpdateAvatar to TS and type avatar endpoints

---

apps/meteor/package.json
yarn.lock

some are having difficulties when they have a github_token set, yarn tries to use the token and generates a new checksum and fails the installation

Chore: solve yarn issues from env var

---

apps/meteor/server/startup/migrations/index.ts
apps/meteor/server/startup/migrations/v263.ts

[FIX] Failure to update Integration History index

---

.github/workflows/build_and_test.yml
apps/meteor/app/settings/server/startup.ts

Regression: Fix services-image-build-check

---

apps/meteor/client/startup/userSetUtcOffset.ts

Chore: User set UTC offset

---

.github/workflows/build_and_test.yml

Regression: CI services build

---

packages/livechat/src/components/App/App.js
packages/livechat/src/lib/triggers.js
packages/livechat/src/routes/TriggerMessage/component.js
packages/livechat/src/routes/TriggerMessage/container.js
packages/livechat/tsconfig.json

The chat opened by user trigger was not working properly, it was hooked on the wrong event.
**Will be ready to review as soon as https://github.com/RocketChat/Rocket.Chat/pull/25312 is merged**

[FIX] One of the triggers was not working correctly

---

apps/meteor/client/sidebar/header/CreateChannel.tsx

Chore: Convert Create Channel

---

apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslate.tsx

Chore: Convert AutoTranslate

---

apps/meteor/app/lib/server/functions/deleteUser.ts
apps/meteor/app/models/server/models/LivechatVisitors.js
apps/meteor/ee/app/models/server/models/LivechatUnitMonitors.js

https://app.clickup.com/t/23tt12m

[FIX] Removing user also removes them from Omni collections

---

apps/meteor/client/views/room/Room/Room.tsx

[FIX] Fixing app contextual bar functionality

---

apps/meteor/client/views/room/MessageList/components/Toolbox/ToolboxDropdownMobile.tsx

[FIX] Message menu dropdown not working on Mobile Web

---

apps/meteor/client/views/admin/apps/AppDetailsHeader.tsx
apps/meteor/client/views/admin/apps/AppMenu.js
apps/meteor/client/views/admin/apps/AppRow.tsx
apps/meteor/client/views/admin/apps/MarketplaceRow.tsx
packages/core-typings/src/Apps.ts

Fixed a problem on which the AppMenu component did not appear for apps that had an active subscription but weren't installed, now the rendering of the component is also based on the isSubscribed flag, and the appearance of the uninstall and enable/disable options are based on the app.installed flag so that the correct options appear on all the edge cases.
Demo gif:

Regression: Subscription menu not appearing for non installed but subscribed apps

---

apps/meteor/app/integrations/server/api/api.js
apps/meteor/app/integrations/server/lib/triggerHandler.js
apps/meteor/package.json
yarn.lock

Replace internal VM implementation with VM2 which implements many more mechanisms to ensure timeout, security and allow easier configuration for future improvements on the integrations' feature.

Chore: Increase performance and security of integrations’ scripts

---

apps/meteor/client/components/Omnichannel/Tags.tsx
apps/meteor/client/providers/CallProvider/CallProvider.tsx
apps/meteor/client/sidebar/footer/voip/VoipFooter.stories.tsx
apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
apps/meteor/client/sidebar/footer/voip/index.tsx

This PR fixes a bug preventing the wrap up call modal from being displayed after caller or agent ends the call.

Regression: VoIp wrap up modal not opening after call disconnect

---

apps/meteor/app/federation-v2/server/matrix-client/user.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json

[FIX] Prevent federation crash on invite users as a non-owner user

---

apps/meteor/app/api/server/helpers/insertUserObject.ts
apps/meteor/app/api/server/v1/im.ts
packages/rest-typings/src/v1/dm/DmFileProps.ts
packages/rest-typings/src/v1/dm/DmMembersProps.ts
packages/rest-typings/src/v1/dm/DmMessagesProps.ts

Regression: Fix sort field files.list

---

apps/meteor/app/api/server/lib/getUploadFormData.js

since [mscdex/busboy](https://github.com/mscdex/busboy) 1.5.0, new option named `defParamCharset` for form body parameter encoding is added with default value `latin1`, so unicode filenames are broken since 4.7.0.
#25456 
Just upload any files that has non-ascii filename.
(You can get some UTF-8 characters from https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html)

[FIX] Change form body parameter charset to UTF-8 to fix issue #25456

---

apps/meteor/app/authentication/server/startup/index.js
apps/meteor/app/lib/server/functions/saveUser.js
apps/meteor/app/reactions/server/setReaction.js
apps/meteor/app/utils/server/functions/safeGetMeteorUser.ts
apps/meteor/server/methods/saveUserProfile.js

Some event listeners triggered by Apps were calling `Meteor.user()` in functions that could run outside of Meteor environment

Regression: App event listeners broke Slackbridge integration and importers

---

apps/meteor/package.json
yarn.lock

Version bump of the Apps-Engine and Fuselage

Chore: Update Apps-Engine and Fuselage

---

apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
apps/meteor/client/sidebar/header/CreateDirectMessage.tsx

Chore: Convert UserAutoCompleteMultiple

---

apps/meteor/client/views/teams/contextualBar/channels/BaseTeamsChannels.js

[FIX] Unnecessary padding on teams channels footer

---

.yarnrc.yml

Chore: Remove duplicate checksumBehavior key from yarn file

---

yarn.lock

Chore: Fix incorrect checksum for agenda package (cause of breaking develop builds)

---

apps/meteor/package.json

Chore: Update package.json update tsc memory 

---

.gitignore
apps/meteor/app/api/server/v1/im.ts
apps/meteor/app/models/server/raw/Messages.ts
apps/meteor/server/modules/watchers/watchers.module.ts

Chore: Messages raw model rewrite to ts

---

apps/meteor/app/mentions/server/methods/getUserMentionsByChannel.js

[FIX] getUserMentionsByChannel method room permission

---

apps/meteor/app/markdown/lib/parser/marked/marked.js

[FIX] Sanitize styles in message

---

.kodiak.toml

Chore: Testing Kodiak feature

---

package.json

Since these snap files were recently removed [here](https://github.com/RocketChat/Rocket.Chat/pull/25790), we'd need to update out release CLI accordingly

Chore: Remove snap files from Houston config

---

apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx

[FIX] AgentsPage pagination

---

apps/meteor/app/apps/client/orchestrator.ts
packages/rest-typings/src/apps/index.ts

Regression: Fix apps wrong typing

---

apps/meteor/.docker/Dockerfile.rhel
apps/meteor/app/utils/rocketchat.info
apps/meteor/package.json
package.json

Chore: Fix version on develop branch 

---

apps/meteor/client/components/Sidebar/SidebarItemsAssembler.tsx
apps/meteor/client/views/room/Room/Aside.js
apps/meteor/client/views/room/Room/Body.js
apps/meteor/client/views/room/Room/Footer.js
apps/meteor/client/views/room/Room/RoomWithData.tsx

Chore: Rewrite RoomWithData

---

apps/meteor/app/models/server/raw/Users.js
apps/meteor/server/services/team/service.ts

- Do not add deactivated users to auto-join rooms.
1. Create a new team and add a team member to it;
2. Go to **Administration > Users** and deactivate one of the team members;
3. Return to the team and add an auto-join channel/group. **_Expected behavior:_** the deactivated user should not be added to the room.

[BREAK] Deactivated team members are added to auto-join rooms

---

apps/meteor/.mocharc.api.js

Chore: Fix correct unit test to api files

---

apps/meteor/app/apps/server/bridges/videoConferences.ts
apps/meteor/package.json
apps/meteor/server/sdk/types/IVideoConfService.ts
apps/meteor/server/services/video-conference/service.ts
yarn.lock

[NEW] [VideoConference] Allow apps to create new video conferences

---

apps/meteor/app/importer-csv/server/importer.js
apps/meteor/app/importer-slack-users/server/importer.js

This PR updates the importing of `csv-parse` because the used method wasn't working anymore, we were receiving the following error:
`error: "this.csvParser is not a function"`

[FIX] Update import from `csv-parse`

---

apps/meteor/ee/app/license/server/bundles.ts
apps/meteor/ee/server/configuration/index.ts
apps/meteor/ee/server/configuration/videoConference.ts
apps/meteor/server/lib/videoConfTypes.ts
apps/meteor/server/sdk/types/IVideoConfService.ts
apps/meteor/server/services/video-conference/service.ts

[NEW] [VideoConference] Split EE and CE features

---

apps/meteor/app/settings/server/SettingsRegistry.ts

[FIX] Settings not being overwritten to their default values

---

apps/meteor/app/api/server/v1/videoConference.ts
apps/meteor/app/apps/server/bridges/videoConferences.ts
apps/meteor/package.json
apps/meteor/server/lib/videoConfProviders.ts
apps/meteor/server/sdk/types/IVideoConfService.ts
apps/meteor/server/services/video-conference/service.ts
packages/core-typings/src/VideoConferenceCapabilities.ts
packages/core-typings/src/index.ts
packages/rest-typings/src/v1/videoConference/index.ts
yarn.lock

[NEW] [Video Conference] Capabilities Endpoint

---

apps/meteor/app/videobridge/client/tabBar.tsx
apps/meteor/tests/e2e/04-main-elements-render.spec.ts

[FIX] [Video Conference] Action Order

---

apps/meteor/package.json
package.json
turbo.json

Chore: Keep the option to run only the meteor app

---

.github/actions/build-docker-image-service/action.yml
.github/actions/build-docker-image/action.yml
.github/workflows/build_and_test.yml

Regression: Docker image publish

---

apps/meteor/server/email/IMAPInterceptor.ts
apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts

Chore: Avoid using console logs for email feature

---

apps/meteor/client/views/admin/apps/AppMenu.js

Re-added the view logs button to the appMenu component so that the user can go directly from the marketplace list of apps to the app info page with the logs tab already open.
Demo gif:

Regression: Re-add view logs button

---

apps/meteor/app/models/server/raw/Sessions.ts
apps/meteor/ee/server/api/sessions.ts

Regression: Send param logoutBy when admin logout an user

---

apps/meteor/playwright.config.ts
apps/meteor/tests/e2e/11-admin.spec.ts
turbo.json

Regression: Fix e2e CI

---

apps/meteor/app/api/server/v1/voip/omnichannel.ts
apps/meteor/client/views/admin/settings/groups/voip/RemoveAgentButton.tsx
packages/rest-typings/src/v1/voip.ts

Reverts RocketChat/Rocket.Chat#25874

Revert "[BREAK] use urlParams on omnichannel/agent/extension/"

---

apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx

[FIX] Sort by scope or creation date not working on canned responses list

---

apps/meteor/client/components/UserAutoComplete/UserAutoComplete.tsx
apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultiple.tsx
apps/meteor/client/sidebar/header/CreateChannelWithData.tsx

[FIX] Initial members value on Create Channel Modal

---

apps/meteor/package.json
yarn.lock

Chore: Fuselage update

---

apps/meteor/client/components/Header/ToolBoxAction.tsx
apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
apps/meteor/client/views/room/contextualBar/RoomMembers/List/RoomMembers.js
apps/meteor/tests/e2e/00-wizard.spec.ts
apps/meteor/tests/e2e/03-login.spec.ts
apps/meteor/tests/e2e/04-main-elements-render.spec.ts
apps/meteor/tests/e2e/05-channel-creation.spec.ts
apps/meteor/tests/e2e/06-messaging.spec.ts
apps/meteor/tests/e2e/07-emoji.spec.ts
apps/meteor/tests/e2e/08-resolutions.spec.ts
apps/meteor/tests/e2e/09-channel.spec.ts
apps/meteor/tests/e2e/10-user-preferences.spec.ts
apps/meteor/tests/e2e/11-admin.spec.ts
apps/meteor/tests/e2e/12-settings.spec.ts
apps/meteor/tests/e2e/13-permissions.spec.ts
apps/meteor/tests/e2e/14-setting-permissions.spec.ts
apps/meteor/tests/e2e/15-message-popup.spec.ts
apps/meteor/tests/e2e/16-discussion.spec.ts
apps/meteor/tests/e2e/omnichannel-agents.spec.ts
apps/meteor/tests/e2e/omnichannel-departaments.spec.ts
apps/meteor/tests/e2e/pageobjects/Agents.ts
apps/meteor/tests/e2e/pageobjects/ChannelCreation.ts
apps/meteor/tests/e2e/pageobjects/Departments.ts
apps/meteor/tests/e2e/pageobjects/Discussion.ts
apps/meteor/tests/e2e/pageobjects/FlexTab.ts
apps/meteor/tests/e2e/pageobjects/LoginPage.ts
apps/meteor/tests/e2e/pageobjects/SideNav.ts

Chore: Fixes e2e playwright intermittences

---

apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfCancelProps.spec.ts
apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfInfoProps.spec.ts
apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfJoinProps.spec.ts
apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfListProps.spec.ts
apps/meteor/tests/unit/definition/rest/v1/video-conference/VideoConfStartProps.spec.ts

[NEW] [VideoConference] API Definition Tests

---

apps/meteor/.mocharc.api.js
apps/meteor/tests/data/apps/apps-data.js
apps/meteor/tests/end-to-end/apps/00-installation.js
apps/meteor/tests/end-to-end/apps/05-video-conferences.ts

https://github.com/RocketChat/Apps.RocketChat.Tester/pull/5

[NEW] [VideoConference] API Tests

---

apps/meteor/server/startup/migrations/v270.ts
packages/core-typings/src/IVoipExtension.ts

Chore: suggestions for PR #25993

---

apps/meteor/app/models/server/raw/Sessions.ts
apps/meteor/app/utils/client/lib/RestApiClient.ts

Chore: MDM Session sort by loginAt

---

.github/workflows/build_and_test.yml
.github/workflows/no-new-js-files.yml

Chore: test turbo params

---

apps/meteor/app/models/server/models/LivechatRooms.js

Query to be used:
```
{ t: 'l', "source.type": 'widget',  open: true, "v.status": {$ne: 'offline'} } 
```
- Prometheus metric

Chore: Introduce new index to query active livechat conversations for cloud scaling

---

apps/meteor/client/lib/utils/mapMessageFromApi.ts

Regression: Fix threads list

---

apps/meteor/definition/externals/meteor/meteor.d.ts
apps/meteor/definition/externals/meteor/rocketchat-streamer.d.ts
apps/meteor/ee/server/services/package.json
apps/meteor/ee/server/services/tsconfig.json
apps/meteor/server/modules/listeners/listeners.module.ts
apps/meteor/server/services/voip/lib/Helper.ts
ee/apps/ddp-streamer/package.json
ee/apps/ddp-streamer/tsconfig.json

This will also make it break during build.

Regression: Fix micro services

---

apps/meteor/client/views/home/CustomHomePage.tsx

HomePageHeader to CustomHomePage 
Customize Button not appearing when the homepage is enabled to `Use custom homepage content `
1. As admin log in the [rocket.chat](http://rocket.chat/)
2. Should be displayed a new home page, with the items:
3. Click on the button customize
4. Should be open the Settings/Layout
5. Click on content
6. Enable the Use custom home page  option
7. Return to the home page

[FIX] Add HomePageHeader to CustomHomePage

---

apps/meteor/client/providers/CallProvider/hooks/useVoipClient.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/server/services/voip/lib/Helper.ts
apps/meteor/server/services/voip/service.ts
packages/core-typings/src/IVoipServerConfig.ts
packages/core-typings/src/voip/IRegistrationInfo.ts

One of the settings removed here https://github.com/RocketChat/Rocket.Chat/pull/25993 was still getting used for getting the asterisk server URL causing this issue

Regression: Invalid Voip host issue preventing agents connecting to asterisk

---

apps/meteor/app/lib/server/functions/loadMessageHistory.ts
apps/meteor/app/utils/server/lib/normalizeMessagesForUser.ts

Chore: Convert normalizeMessagesForUser

---

apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts
apps/meteor/package.json
packages/ui-contexts/src/SettingsContext.ts
yarn.lock

Chore: Convert useSidebarPaletteColor

---

apps/meteor/client/providers/TooltipProvider.tsx

Chore: Close tooltip on click

---

_templates/package/new/package.json.ejs.t
packages/favicon/package.json
packages/favicon/tsconfig.json
packages/gazzodown/package.json
packages/gazzodown/tsconfig.json
packages/model-typings/tsconfig.json
packages/models/tsconfig.json
packages/ui-client/package.json
packages/ui-client/tsconfig.json
tsconfig.json

Regression: `yarn dev` not working

---

apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.js
apps/meteor/ee/client/omnichannel/additionalForms/ContactManager.js

Regression: Contact manager endpoint usage

---

apps/meteor/client/providers/CallProvider/CallProvider.tsx
apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx

Right now all calls are being marked as inbound, even the outbound ones

Regression: Fix call direction

---

apps/meteor/client/contexts/CallContext.ts
apps/meteor/client/sidebar/footer/SidebarFooter.tsx
apps/meteor/client/sidebar/footer/SidebarFooterDefault.tsx
apps/meteor/client/sidebar/footer/SidebarFooterWatermark.tsx
apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
apps/meteor/client/sidebar/footer/voip/index.tsx
apps/meteor/client/views/hooks/useUpgradeTabParams.ts

Chore: Improve footer Template

---

apps/meteor/app/api/server/api.d.ts
apps/meteor/app/api/server/api.js
apps/meteor/ee/server/api/licenses.ts

Chore: Allow endpoints to optionally require authentication

---

packages/gazzodown/package.json
packages/gazzodown/src/Markup.tsx
packages/gazzodown/src/PreviewMarkup.tsx
packages/gazzodown/src/elements/InlineElements.tsx
packages/gazzodown/src/elements/PreviewInlineElements.tsx
packages/gazzodown/src/katex/KatexErrorBoundary.tsx
packages/ui-client/src/components/ErrorBoundary.tsx
yarn.lock

Regression: Add Error boundary to katex render component

---

packages/api-client/src/index.ts

[FIX] Undefined headers on API Client

---

apps/meteor/client/sidebar/footer/SidebarFooterWatermark.tsx

Chore: fix watermark condition

---

apps/meteor/server/services/video-conference/service.ts

Regression: [VideoConference] If the caller loses connection, direct calls are never canceled

---

apps/meteor/server/cron/statistics.js

Chore: Change stats to daily

---

apps/meteor/client/views/admin/apps/AppDetails.tsx

Solved a problem that showed an unwanted zero in place of the APIs section for apps that weren't installed/did not have an APIs section.
Before:
After(non installed app):
After(installed app)

Regression: Fix marketplace app apis visibility problem

---

apps/meteor/app/discussion/client/tabBar.ts
apps/meteor/app/federation-v2/server/infrastructure/rocket-chat/slash-commands/index.ts
apps/meteor/app/livestream/client/tabBar.tsx
apps/meteor/app/message-pin/client/tabBar.ts
apps/meteor/app/threads/client/flextab/threadlist.tsx
apps/meteor/app/ui-clean-history/client/lib/tabBar.ts
apps/meteor/app/videobridge/client/tabBar.tsx
apps/meteor/app/webrtc/client/tabBar.tsx
apps/meteor/client/views/room/lib/Toolbox/defaultActions.ts

Regression: Do not show federated tooltip on non-federated rooms

---

apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/MemberItem.tsx

Regression: All users in members list showing as federated

---

apps/meteor/client/hooks/useEndpointActionExperimental.ts

This PR changes the way we show an error message to the user on the `useEndpointActionExperimental` hook, previously for `Object` error messages it was being shown as undefined

[FIX] Update error message on `useEndpointActionExperimental`

---

apps/meteor/app/assets/server/assets.ts

Regression: Fix assets format

---

apps/meteor/app/api/server/middlewares/authentication.ts

You get the following error when you click on any action buttons on either message or modals
To reproduce this issue, you may use any app that uses UIKit action buttons like Whatsapp, Poll, etc

Regression: Unable to click on UiKit buttons provided by apps

---

packages/livechat/src/routes/Chat/component.js

Clickup: https://app.clickup.com/t/2hcpn1p

Regression: Broken emoji picker on Livechat

---

packages/gazzodown/src/emoji/Emoji.tsx

Regression: Emojis displaying as `:undefined:`

---

apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfo.tsx
apps/meteor/client/views/omnichannel/directory/calls/contextualBar/VoipInfoCallButton.tsx
apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.js

Regression: Added missing call button in the contact info contextual bar

---

apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/server/services/video-conference/service.ts

[NEW] When ending a call, add a message saying that it has ended.

---

apps/meteor/app/api/server/v1/videoConference.ts
apps/meteor/app/authorization/server/functions/upsertPermissions.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/server/startup/migrations/index.ts
apps/meteor/server/startup/migrations/v278.ts

[NEW] Add "Ring other users when calling" permission

---

_templates/package/new/package.json.ejs.t
packages/agenda/package.json
packages/cas-validate/package.json
yarn.lock

Some places were still referring to TypeScript 4.3.4 instead of 4.5.5, so this PR targets it.

Regression: Align TypeScript version across workspaces

---

apps/meteor/client/sidebar/header/EditStatusModal.tsx

Chore: Remove setUserStatus method call

---

apps/meteor/client/views/admin/customUserStatus/CustomUserStatusForm.tsx

Chore: Remove custom user status method calls

---

apps/meteor/app/ui-utils/client/lib/AccountBox.ts
apps/meteor/client/sidebar/header/UserDropdown.tsx

Replace meteor call to APIClient on AccountBox.
Also fix the type of UserStatus on setStatus function.

Chore: Remove meteor call on AccountBox

---

apps/meteor/packages/rocketchat-version/plugin/compile-version.js

Now that we're using `yarn`, the version stored in the `package.json` is no longer the resolved one, but it matches the input. This means that when we ran `yarn add @rocket.chat/apps-engine@alpha`, yarn saves `"alpha"` as the version of the package, while NPM added the resolved version for the tag, e.g. `"1.33.0-alpha.6507"`. This ends up breaking a few places where we need the Apps-Engine version for communication with the Marketplace.
With this PR we change the source of that info so the problem doesn't happen anymore.

Chore: Change Apps-Engine version source for info

---

apps/meteor/app/apps/client/communication/websockets.js
apps/meteor/client/startup/slashCommands.ts

Fixes slash command previews not being showed

Regression: Fix command previews

---

apps/meteor/app/theme/client/imports/general/base_old.css

Regression: Inline code and copyonly tag styles

---

apps/meteor/app/models/server/models/_oplogHandle.ts
apps/meteor/packages/rocketchat-mongo-config/server/index.js
apps/meteor/server/services/meteor/service.ts

Chore: Check for env var values and not just if they are set

---

apps/meteor/app/integrations/server/api/api.js
apps/meteor/app/integrations/server/lib/triggerHandler.js

Chore: Do not log integrations using `name` key

---

apps/meteor/server/services/meteor/service.ts

Regression: Meteor uses `projection` for its observes

---

apps/meteor/client/sidebar/sections/OmnichannelSection.tsx

Replace contact center icon:
Before:
After:

Regression: Replace contact center icon

---

apps/meteor/client/views/admin/users/EditUser.js

The endpoint was not using the `/v1/`prefix, this cause an 405 error (Method not allowed)

Regression:  Admin Avatar Edit endpoint fix

---

apps/meteor/app/apps/server/communication/uikit.ts

this behavior was changed by #25937 and #26171

Regression: get user from `req` on `ui.interaction` endpoints

---

apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts

Chore: Disabled icon colors on sidebar

---

apps/meteor/app/api/server/helpers/parseJsonQuery.ts
apps/meteor/app/api/server/v1/commands.ts
apps/meteor/app/lib/server/startup/settingsOnLoadDirectReply.ts
apps/meteor/server/methods/browseChannels.js
apps/meteor/server/models/raw/BaseRaw.ts

Chore: Hide deprecation query log on production

---

apps/meteor/client/contexts/CallContext.ts
apps/meteor/client/providers/CallProvider/CallProvider.tsx
apps/meteor/client/sidebar/sections/actions/OmnichannelCallToggleReady.tsx

This PR brings back the network disconnection state to the voip call toggle button

Regression: Call toggle missing network disconnection state

---

apps/meteor/client/views/admin/users/UserInfoActions.js
apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js
apps/meteor/client/views/room/contextualBar/RoomMembers/List/components/UserActions.js
apps/meteor/client/views/room/contextualBar/UserInfo/UserInfo.js
apps/meteor/client/views/room/contextualBar/UserInfo/actions/UserActions.js

**note**: next fuselage's version needed

Regression: UserInfo/RoomInfo Menu

---

apps/meteor/client/sidebar/header/CreateChannelWithData.tsx

Regression: disable readonly on channel fed creation

---

apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx

Regression: Federated username detection failing every other time

---

apps/meteor/tests/end-to-end/api/livechat/agents.js

Regression: Fix breaking omnichannel tests

---

apps/meteor/client/views/admin/permissions/hooks/usePermissionsAndRoles.ts

I was not aware the `.count()` changes to MongoDB driver were also applied to MiniMongo on client (it makes sense though), so this page was also affected, as now `count()` takes into consideration `limit` and `skip` options.

Regression: Fix permissions page pagination

---

apps/meteor/client/views/admin/info/OfflineLicenseModal.js

Regression: Add v1 to licenses.add endpoint

---

apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx
apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactInfo.js
apps/meteor/client/views/room/Header/Omnichannel/VoipRoomHeader.tsx
apps/meteor/ee/client/lib/voip/parseOutboundPhoneNumber.ts

Affect:
- Voip room header
- Contacts table
- Contact info

Regression: Use fname instead real unique name for Voip

---

apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleFederated.tsx
apps/meteor/client/components/UserAutoCompleteMultiple/UserAutoCompleteMultipleOptions.tsx

Regression: Options overlapping input in Users Autocomplete

---

apps/meteor/client/views/admin/apps/AppSecurity.tsx

Regression: Fix app privacy links opening in desktop client instead of browser

---

apps/meteor/server/models/raw/BaseRaw.ts

I found this while I was doing some refactorings on the federation side. 😬

Chore: Options in BaseRaw model could possibly be undefined

---

apps/meteor/app/livechat/imports/server/rest/departments.ts
apps/meteor/app/livechat/server/api/lib/departments.ts
apps/meteor/app/livechat/server/lib/Helper.js
packages/rest-typings/src/v1/omnichannel.ts

Chore: Sugggestions on PR #26357

---

apps/meteor/app/livechat/imports/server/rest/inquiries.js
apps/meteor/app/livechat/server/api/lib/inquiries.js
apps/meteor/server/models/raw/LivechatRooms.js

Chore: Suggestions on PR #26376

---

.github/workflows/build_and_test.yml

Chore: Cache playwright 

---

apps/meteor/ee/client/voip/modal/DialPad/DialPadModal.tsx

[FIX] DialPad call button from end to center

---

codecov.yml

adjust the threshold not to break flaky tests

Chore: Codecov threshold

---

apps/meteor/app/settings/server/CachedSettings.ts
apps/meteor/app/voip/server/startup.ts
apps/meteor/server/services/voip/connector/asterisk/CommandHandler.ts
apps/meteor/server/services/voip/lib/Helper.ts
docker-compose-ci.yml

Chore: Exit process on `unhandledRejection` on CI

---

apps/meteor/client/hooks/useEndpointData.ts

Chore: useEndpointData deprecation

---

turbo.json

Skips cache for building `@rocket.chat/ui-contexts`, avoiding Turborepo issues with a symlink.

Chore: Bypass turbo cache on `ui-contexts`

---

apps/meteor/server/services/voip/connector/asterisk/ami/AMIConnection.ts

[FIX] Prevent VoIP issues during disconnection when network failed

---

apps/meteor/app/otr/client/OTR.ts
apps/meteor/app/otr/client/OTRRoom.ts
apps/meteor/app/otr/lib/IOTR.ts
apps/meteor/app/otr/lib/functions.ts
apps/meteor/app/otr/server/methods/updateOTRAck.ts

#24757 was an old PR and was recently auto-merged, it was not following our latest eslint rules, so now there are some lint issues on the develop.

Chore: Fix lint issues

---

packages/livechat/package.json
yarn.lock

Chore: Fix UiKit dependency issue for Livechat

---

apps/meteor/app/models/server/models/Users.js

Matrix federated (external) users were being counted as a valid EE seat.

[FIX] Do not count Matrix federated users as a valid EE seat

---

apps/meteor/app/lib/server/functions/getFullUserData.ts
apps/meteor/app/lib/server/functions/saveUser.js
apps/meteor/client/views/admin/users/AdminUserInfoActions.tsx
apps/meteor/client/views/admin/users/AdminUserInfoWithData.tsx
apps/meteor/client/views/admin/users/EditUserWithData.tsx
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json

I haven't added tests for this endpoint change since we don't have a way to create a federated user (unless set up the whole federation) and simulate the behavior.

[FIX] Do not allow admin users edit other federated users

---

apps/meteor/app/federation-v2/server/application/sender/RoomInternalHooksValidator.ts
apps/meteor/app/lib/server/functions/createRoom.ts
apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsersWithData.tsx
apps/meteor/tests/unit/app/federation-v2/server/unit/application/sender/RoomInternalHooksValidator.spec.ts

[FIX] Do not allow add external users(string) to regular rooms

---

apps/meteor/app/api/server/v1/im.ts
apps/meteor/tests/end-to-end/api/04-direct-message.js

[FIX]  Endpoints `im.list` not working with Use Real Name setting

---

apps/meteor/ee/server/models/raw/CannedResponse.ts
apps/meteor/ee/server/models/raw/LivechatInquiry.ts
apps/meteor/ee/server/models/raw/LivechatPriority.ts
apps/meteor/ee/server/models/raw/LivechatTag.ts
apps/meteor/ee/server/models/raw/LivechatUnitMonitors.ts
apps/meteor/server/models/raw/LivechatDepartment.ts
packages/model-typings/src/models/ICannedResponseModel.ts

Chore: Some suggestions on PR #26544

---

.github/CODEOWNERS

Chore: Add translations code owner

---

apps/meteor/app/api/server/api.helpers.ts
apps/meteor/app/api/server/api.js
apps/meteor/app/livechat/imports/server/rest/appearance.js
apps/meteor/app/livechat/imports/server/rest/businessHours.js
apps/meteor/app/livechat/imports/server/rest/queue.js
apps/meteor/app/livechat/imports/server/rest/rooms.js
apps/meteor/app/livechat/imports/server/rest/triggers.js
apps/meteor/app/livechat/imports/server/rest/users.js
apps/meteor/app/livechat/imports/server/rest/visitors.js
apps/meteor/app/livechat/server/api/lib/departments.ts
apps/meteor/app/livechat/server/api/lib/users.js
apps/meteor/app/livechat/server/api/v1/customField.js
apps/meteor/app/livechat/server/api/v1/transfer.js
apps/meteor/tests/unit/app/api/server/v1/lib/checkPermissionsForInvocation.spec.ts

Chore: Suggestions on PR #26419

---

.github/CODEOWNERS

Chore: Remove translation owners

---

apps/meteor/client/providers/TooltipProvider.tsx

Chore: Prevent tooltip from opening after click

---

apps/meteor/tests/e2e/channel-management.spec.ts
apps/meteor/tests/e2e/page-objects/fragments/home-flextab-notificationPreferences.ts
apps/meteor/tests/e2e/page-objects/fragments/home-flextab.ts

Our menu is quite wild and its closing somehow given no chances to playwright click on the items

Chore: skipping tests that are based on kebab menu

---

.github/workflows/build_and_test.yml

Chore: Fix services Docker build

---

apps/meteor/app/lib/server/methods/getMessages.ts
apps/meteor/server/methods/loadHistory.js
apps/meteor/server/methods/loadSurroundingMessages.js

Reverts RocketChat/Rocket.Chat#25981

Revert: [FIX] Users can access public discussions inside private channels they are not members of

---

apps/meteor/app/livechat/client/views/admin.js
apps/meteor/app/livechat/client/views/app/livechatDashboard.html

I've not added tests since I cannot find any place where this was used
closes https://github.com/RocketChat/Rocket.Chat/issues/26591

Chore: Remove Livechat Dashboard Templates

---

apps/meteor/app/ui-utils/client/lib/RoomManager.js

Chore: Fix CI intermittent

---

apps/meteor/client/views/room/UserCard/UserCardWithData.tsx

Regression: Custom status loading forever in Usercard

---

.github/workflows/build_and_test.yml
apps/meteor/tests/e2e/omnichannel-voip-footer.spec.ts
docker-compose-ci.yml

Chore: Suggestions on PR #26334

---

apps/meteor/server/stream/streamBroadcast.js

Regression: "Cache size is not a function" error when booting

---

apps/meteor/client/startup/banners.ts

Regression: Remove log from banners.ts

---

apps/meteor/server/models/raw/LivechatInquiry.ts
apps/meteor/server/modules/listeners/listeners.module.ts

[FIX] Omnichannel inquiries being updated even if not needed

---

apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
apps/meteor/ee/server/lib/registerServiceModels.ts
apps/meteor/ee/server/services/authorization/service.ts
apps/meteor/ee/server/services/mongo.ts
apps/meteor/ee/server/services/package.json
apps/meteor/ee/server/services/stream-hub/StreamHub.ts
apps/meteor/ee/server/services/stream-hub/service.ts
apps/meteor/server/modules/listeners/listeners.module.ts
apps/meteor/server/sdk/lib/Events.ts
ee/apps/ddp-streamer/src/streams.ts

Putting a temp release branch as placeholder for now, Fix was taken from 5.0.4

[FIX][ENTERPRISE] Omnichannel real time data on micro services

---

apps/meteor/client/hooks/useReactiveValue.ts

Regression: Workaround to handle auto stopped computations 😞 

---

apps/meteor/app/api/server/v1/e2e.ts
apps/meteor/tests/end-to-end/api/01-users.js

Regression: REST setUserPublicAndPrivateKeys

---

apps/meteor/app/autotranslate/client/lib/autotranslate.ts

Regression: AutoTranslate is disabled error

---

apps/meteor/client/views/admin/apps/AppSetting.tsx

Regression: Select settings options not visible on Apps Setting panel

---

apps/meteor/client/sidebar/search/SearchList.tsx

Regression: Sidebar Search list local data cache and keyboard navigation

---

apps/meteor/app/livechat/imports/server/rest/rooms.js
apps/meteor/server/models/raw/LivechatRooms.js

Clickup: https://app.clickup.com/t/2r65yjw

Regression: Empty custom-fields filter on Current Chats causing issues

---

.github/workflows/build_and_test.yml

Chore: Fix docker latest tag push

---

apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json

i18n: pt-BR translation typo

---

packages/ui-composer/src/MessageComposer/MessageComposer.stories.tsx
packages/ui-composer/src/MessageComposer/MessageComposerDisabled.tsx
packages/ui-composer/src/MessageComposer/MessageComposerDisabledAction.tsx
packages/ui-composer/src/MessageComposer/MessageComposerDisplay.tsx
packages/ui-composer/src/MessageComposer/index.ts

[NEW] Composer  variations

---

apps/meteor/tests/e2e/omnichannel-currentChats.spec.ts

Chore: fix wrong `test.step` usage

---

apps/meteor/client/components/message/Attachments/Files/VideoAttachment.tsx
apps/meteor/client/lib/utils/userAgentMIMETypeFallback.ts
apps/meteor/client/views/room/modals/FileUploadModal/MediaPreview.tsx
yarn.lock

TC-67
Some browsers don't support the MIME type for QuickTime video encoder (.mov), so we had to create a fallback to 'video/mp4'. There are other fallbacks for other browsers, but this is the only one we need for now.
The fallback func was used in the MediaPreview and VideoAttachments components

[FIX] MIME Type fallback for .mov File Extensions

---

apps/meteor/tests/e2e/omnichannel-livechat.spec.ts

Chore: Refactor omnichannel livechat tests

---

apps/meteor/package.json
yarn.lock

Chore: Bump vm2 to 3.9.11

---

packages/gazzodown/src/elements/LinkSpan.tsx

TC-89 | TC-90 | TC-91 | TC-97
1. The link parser was not parsing Emphasis elements (bold, italic, and strike). - TC-91
**Current behavior:**  
**Expected behavior**
This Pull Request needs to be tested with the fuselage PR: https://github.com/RocketChat/fuselage/pull/855

[FIX] Message Parser - Emphasis highlight in Links/URLs

---

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx
apps/meteor/client/views/omnichannel/currentChats/RemoveChatButton.tsx

Regression: Double Table Cell Causing extra padding on Current Chats

---

apps/meteor/client/sidebar/RoomList/RoomList.tsx
apps/meteor/client/sidebar/RoomList/RoomListRow.tsx
apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx

Jira Issue: [VC-10]
[VC-10]: https://rocketchat.atlassian.net/browse/VC-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Regression: VideoConf Actions Reactivity in SidebarItem

---

apps/meteor/package.json
yarn.lock

Bump Apps-Engine version to latest stable

Chore: Bump Apps-Engine version

---

apps/meteor/app/livechat/client/lib/stream/queueManager.js

[FIX] Warning about livechat/inquiries.queuedForUser

---

apps/meteor/ee/app/livechat-enterprise/server/settings.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json

[NEW] Add "Sorting Mechanism" setting

---

apps/meteor/client/components/UserCard/UserCard.tsx

Regression: Remove margin-bottom inside UserCard actions

---

packages/ui-client/src/components/Header/ToolBox/ToolboxDivider.tsx

Regression: Toolbox Divider Color

---

apps/meteor/client/components/message/Attachments/QuoteAttachment.tsx
yarn.lock

Regression: Quote colors

---

apps/meteor/server/database/DatabaseWatcher.ts
apps/meteor/server/startup/watchDb.ts
ee/apps/stream-hub-service/src/service.ts
yarn.lock

Regression: Unify `isLastDocDelayed` logic

---

apps/meteor/app/theme/client/imports/components/message-box.css
apps/meteor/client/templates.ts

Aligned microphone icon to its respective position on  screen widths <= 500 (mobile screens)
Fixes #27073

[FIX] Microphone icon alignment issue (# 27073)

---

.github/workflows/pr-title-checker.yml

Chore: Enable PR Title Checker for forks

---

apps/meteor/app/custom-sounds/server/methods/uploadCustomSound.js

[FIX] Uploading Custom Sound files not working, but showing success

---

apps/meteor/client/views/room/contextualBar/Discussions/components/Message.js

[FIX] Discussions list divider on contextualBar

---

apps/meteor/app/channel-settings/server/methods/saveRoomSettings.js
apps/meteor/client/views/room/contextualBar/Discussions/Row.js

https://github.com/RocketChat/Rocket.Chat/pull/21389
https://github.com/RocketChat/Rocket.Chat/pull/20845
Closes #19038
Closes #21388

[FIX] Discussion list timestamp and Edit room system messages

---

apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx

If you deactivated the permission to send links, the button was always there and led to an error message.
Before: 
https://user-images.githubusercontent.com/45966964/115801057-23948280-a3dc-11eb-83c2-b3e16f66ddd5.mp4
After:
https://user-images.githubusercontent.com/45966964/115801253-956ccc00-a3dc-11eb-95d0-9baa69410fe1.mp4
Closes #21759

[FIX] Add condition to invite user if user doesn't have permission

---

.github/workflows/build_and_test.yml

Chore: Remove turborepo if env is not set

---

apps/meteor/client/components/message/Attachments/Attachment/AttachmentDescription.tsx

[FIX] AttachmentDescription color token

---

apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditChannel.js

[FIX] Display Edit Team instead of Edit Room when in a team

---

apps/meteor/app/apps/server/bridges/scheduler.ts

[FIX] Next schedule check for Apps

---

apps/meteor/client/views/admin/info/InformationPage.tsx
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
apps/meteor/server/startup/instance.ts
apps/meteor/server/stream/streamBroadcast.js

[ARCH-88]
[ARCH-88]: https://rocketchat.atlassian.net/browse/ARCH-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Multi instance error message

---

apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx

In the sidebar, choose extended mode.
I'll use the channel GENERAL as the example.
With user one, join GENERAL.
With another user, join GENERAL.
On the first user, click the homepage button, or open another room, so that the room GENERAL is NOT open.
With user 2, send a message to channel GENERAL.
Now, send a different message.
On user 1, in the sidebar, the preview message should be the last sent message, which is not the case.

[FIX] Sidebar Room list extended preview not updating on new messages.

---

apps/meteor/ee/app/livechat-enterprise/server/api/priorities.ts
apps/meteor/ee/server/models/raw/LivechatPriority.ts
apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
packages/model-typings/src/models/ILivechatPriorityModel.ts
packages/rest-typings/src/v1/omnichannel.ts

[NEW] Endpoints and model functions to reset priorities

---

.github/workflows/build_and_test.yml

Chore: Fix missing license for forks

---

apps/meteor/app/lib/server/lib/deprecationWarningLogger.ts
apps/meteor/server/modules/notifications/notifications.module.ts

Chore: Deprecation warning on 'typing' stream event.

---

apps/meteor/app/threads/client/flextab/thread.html
apps/meteor/app/threads/client/flextab/thread.ts
apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
apps/meteor/tests/e2e/thread-actions.spec.ts

Error deleting the first message when initializing a thread returns a black screen. (the thread should have only the main message)
1. Write a message in a group
2. Click "Reply In Thread" in message actions
3. Click "Delete" in the message actions for the first message within the thread view
The thread template was rendering the message component without checking if the data exist. 
Also added a new behavior to close the threads when doesn't exist messages in the thread anymore.

[FIX] Delete first message when initializing thread returns black screen

---

apps/meteor/app/livechat/server/api/rest.ts
apps/meteor/app/livechat/server/api/v1/webhooks.ts
apps/meteor/app/livechat/server/methods/webhookTest.js
apps/meteor/client/views/omnichannel/webhooks/WebhooksPage.js
apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts

[OC-408]
[OC-408]: https://rocketchat.atlassian.net/browse/OC-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Create new endpoint for test webhooks and deprecate meteor method

---

apps/meteor/client/components/MarkdownText.tsx

Fixes #24358
Respect Markdown Link Schemes setting in places that accept markdown (e.g custom fields.)

[FIX] MarkdownText component not respecting `Markdown_SupportSchemesForLink` setting

---

apps/meteor/client/sidebar/header/CreateChannel.tsx

[FIX] Adjust read only toggle on create channel based on permissions

---

apps/meteor/client/providers/UserProvider.tsx

Regression: Fix custom oauth undefined clientConfig

---

apps/meteor/app/ui-message/client/message.js

Chore: Fixed typo in a comment

---

apps/meteor/package.json
yarn.lock

Chore: change apps-engine version

---

apps/meteor/package.json
yarn.lock

Regression: Restore fuselage-ui-kit version

---

packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx

Regression: videoconf block showing a zero when no user has joined the call

---

apps/meteor/client/sidebar/hooks/useSidebarPaletteColor.ts

Regression: Fix sidebar token highlighted usage

---

apps/meteor/app/lib/lib/MessageTypes.ts
apps/meteor/server/services/video-conference/service.ts
packages/core-typings/src/IMessage/IMessage.ts

[NEW] Custom MessageType for video conference messages

---

apps/meteor/client/sidebar/header/CreateTeam/CreateTeamModal.tsx

Regression: Team name validation on Create Team Modal

---

apps/meteor/app/ui-utils/client/lib/MessageAction.ts
apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
apps/meteor/client/views/room/MessageList/components/Toolbox/Toolbox.tsx

Jira Issue: [VC-8]
[VC-8]: https://rocketchat.atlassian.net/browse/VC-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Regression: Remove actions from VideoConf Message Block

---

packages/ui-video-conf/src/VideoConfMessage/VideoConfMessage.tsx
packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageFooter.tsx
packages/ui-video-conf/src/VideoConfPopup/VideoConfPopup.tsx

Regression: Update VideoConf components colors

---

ee/packages/ui-theming/src/palette.ts
ee/packages/ui-theming/src/paletteDark.ts

Chore: Update badge tokens

---

apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts

[FIX] Thread messages being included in the room history even though they are not displayed

---

apps/meteor/ee/client/omnichannel/priorities/PrioritiesTable.tsx
apps/meteor/ee/client/omnichannel/priorities/PriorityIcon.tsx
apps/meteor/package.json
yarn.lock

[NEW] Priority Icon component

---

apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfList/VideoConfListItem.tsx

Regression: Update VideoConfListItem Color Tokens

---

apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx

Regression: Don't allow empty spaces on priority name

---

apps/meteor/client/views/admin/apps/AppsRoute.tsx
apps/meteor/client/views/admin/routes.tsx

Solved a bug caused by the RC production build steps breaking the flow router triggersEnter event that did some rerouting for marketplace. Removed the cited function from the routes.tsx file, and now the rerouting is done directly inside the AppsRoute file.
Demo gif:
Closes #27346 
1. Enter the admin section through the 'workspace' option of the kebab menu
2. Click on the Apps option

Regression: Admin menu apps option not working

---

apps/meteor/app/theme/client/imports/components/message-box.css
apps/meteor/app/theme/client/imports/general/variables.css

Regression: message-box-editing-color

---

apps/meteor/server/routes/health.ts

[FIX] Fix watch db being started on Micro Services env

---

.github/history-manual.json
.github/history.json
HISTORY.md
apps/meteor/app/apps/server/bridges/scheduler.ts
apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json

Co-authored-by: Filipe Marins <9275105+filipemarins@users.noreply.github.com>
Co-authored-by: gabriellsh <40830821+gabriellsh@users.noreply.github.com>

Bump version to 5.4.0-develop

---

apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx

[FIX] Adjusted priority form to revalidate after reset

---

apps/meteor/ee/client/omnichannel/slaPolicies/SlasPage.tsx
apps/meteor/tests/e2e/omnichannel-sla-policies.spec.ts
apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
apps/meteor/tests/e2e/page-objects/omnichannel-sla-policies.ts

Chore: SLA policies e2e tests

---

apps/meteor/ee/server/models/raw/ServiceLevelAgreements.ts

Chore: Add missing indexes to SLA collection

---

apps/meteor/app/ui/client/lib/ChatMessages.ts

It handles issues regarding editing messages.

Regression: more message box issues

---

packages/web-ui-registration/src/LoginForm.tsx
packages/web-ui-registration/src/LoginServices.tsx
packages/web-ui-registration/src/RegistrationPageRouter.tsx

Fixes https://github.com/RocketChat/Rocket.Chat/issues/27490

[FIX] Fix Login with Show default form disabled

---

apps/meteor/client/sidebar/sections/actions/OmnichannelLivechatToggle.tsx

Chore: Omnichannel Sidebar icons alignment

---

apps/meteor/app/livechat/imports/server/rest/inquiries.ts

Chore: Deprecate unused omnichannel API

---

apps/meteor/client/views/room/Header/Omnichannel/OmnichannelRoomHeader.tsx
apps/meteor/client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx

Before:
After:
Move Omnichannel conversation toolbar to the right and add a divider.

Chore: Move Omnichannel conversation toolbar to the right

---

packages/web-ui-registration/src/LoginForm.tsx
packages/web-ui-registration/src/RegisterForm.tsx

[FIX] Registration and Login placeholders not being used

---

apps/meteor/client/providers/MeteorProvider.tsx
apps/meteor/client/providers/TranslationProvider.tsx

[FIX] Custom languages not being applied to i18next

---

apps/meteor/client/components/MarkdownText.tsx
apps/meteor/client/views/room/Announcement/Announcement.tsx

Channel Announcements that contain links are opening on the same page instead of a new page/tab causing render issues, especially on the desktop client.
The fix was simple to add a hook for the `dompurify` library to add the `target` and `rel` attributes to keep the _blank behavior.
Also, it introduced some parsers settings to `inlineWithoutBreaks` variant to avoid breaking messages at Announcements and other places that uses this variant.
closes https://github.com/RocketChat/Rocket.Chat/issues/27496
closes #27563
closes #27473 
closes https://github.com/RocketChat/Rocket.Chat.Electron/issues/2560
This bug was introduced by this PR: https://github.com/RocketChat/Rocket.Chat/pull/27245 
TC-335

[FIX] Announcement banner link opening in the same page

---

apps/meteor/client/views/admin/emailInbox/EmailInboxTable.tsx
apps/meteor/server/features/EmailInbox/EmailInbox.ts
apps/meteor/tests/e2e/email-inboxes.spec.ts
apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts

Chore: fix EmailInbox intermittent e2e tests

---

apps/meteor/.docker/Dockerfile.rhel
apps/meteor/app/utils/rocketchat.info
apps/meteor/package.json
package.json

Bump version to 6.0.0-develop

---

apps/meteor/client/views/room/contextualBar/KeyboardShortcuts/KeyboardShortcutSection.tsx

Chore: KeyboardShortCut color

---

apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
apps/meteor/client/lib/chats/ChatAPI.ts
apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
apps/meteor/client/sidebar/header/index.tsx
apps/meteor/client/sidebar/search/SearchList.tsx
apps/meteor/client/views/room/components/body/composer/RoomComposer/hooks/useAutoGrow.ts
apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
apps/meteor/package.json
fuselage.sh
packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx
yarn.lock

Chore: Composer Styling

---

apps/meteor/client/views/admin/apps/AppDetailsPage/AppDetailsPageHeader.tsx
apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
apps/meteor/client/views/admin/apps/AppsList/AppRow.tsx
apps/meteor/client/views/admin/apps/AppsList/AppsList.tsx
apps/meteor/client/views/admin/apps/AppsPage/AppsPageContent.tsx
apps/meteor/client/views/admin/apps/AppsPage/FeaturedAppsSections.tsx

Chore: AppsTable UI Tweaks

---

apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx
packages/rest-typings/src/v1/omnichannel.ts

[IMPROVE] Added ability to reset individual priority

---

apps/meteor/client/views/room/contextualBar/Threads/hooks/useGoToThread.ts

Regression: Open Thread

---

apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx

Regression: Fix composer restore

---

apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx

Chore: Composer missing Slash Command preview

---

apps/meteor/client/lib/createRouteGroup.tsx
apps/meteor/client/sidebar/Sidebar.tsx

Regression: Sidebar collapsing on extra small views

---

apps/meteor/client/views/room/components/body/composer/ComposerMessage.tsx

Regression: Composer fix join room action

---

apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx
apps/meteor/client/views/account/security/AccountSecurityPage.tsx
ee/packages/ui-theming/src/palette.ts
ee/packages/ui-theming/src/paletteDark.ts
packages/ui-client/src/components/Header/HeaderIcon.tsx

Chore: Token refactor

---

apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx

Chore: Composer wrapper around the textarea

---

apps/meteor/client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
apps/meteor/client/views/room/Header/Omnichannel/QuickActions/ToolBoxActionOptions.tsx
apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
apps/meteor/client/views/room/lib/QuickActions/defaultActions.ts
apps/meteor/client/views/room/lib/QuickActions/index.tsx
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/tests/e2e/omnichannel-send-transcript.spec.ts
apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
ee/apps/omnichannel-transcript/src/service.ts
packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx
yarn.lock

Add the dropdown menu on chat transcript button.
oc-487
Depends on this [PR](https://github.com/RocketChat/fuselage/pull/939).

[NEW] Add export as PDF and send via email options

---

.github/workflows/build_and_test.yml

(cherry picked from commit b55b4b985763dc0fffc0808bea14c76e79f6fcc3)

Chore: Upgrade EE license for CI

---

apps/meteor/server/lib/dataExport/processDataDownloads.ts

Fix the following error that was preventing the export files to be generated and sent:
```
@rocket.chat/meteor:dsv: W20230103-18:04:00.367(-3)? (STDERR) TypeError: Cannot read property 'closed' of undefined
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at WriteStream.close (internal/fs/streams.js:423:14)
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at internal/util.js:340:30
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at new Promise (<anonymous>)
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at internal/util.js:339:12
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at server/lib/dataExport/processDataDownloads.ts:95:8
@rocket.chat/meteor:dsv: W20230103-18:04:00.371(-3)? (STDERR)     at …
```

Regression: Fix write stream error on user data export

---

apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx

[FIX] Added form error validation for duplicated priority name

---

apps/meteor/client/components/message/content/BroadcastMetrics.tsx
apps/meteor/client/components/message/content/DiscussionMetrics.tsx
apps/meteor/client/components/message/content/ThreadMetrics.tsx
apps/meteor/client/components/message/variants/room/RoomMessageContent.tsx
apps/meteor/client/components/message/variants/thread/ThreadMessageContent.tsx
apps/meteor/client/views/room/components/BlazeTemplate.tsx
apps/meteor/client/views/room/components/VerticalBarOldActions.tsx

It should fixes crashes on starred, pinned, and mentioned messages while those are migrating from Blaze to React.

Regression: Missing contexts on contextual bar

---

apps/meteor/app/livechat/lib/inquiries.ts
apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/models/server/models/LivechatInquiry.ts
apps/meteor/client/definitions/SubscriptionWithRoom.ts
apps/meteor/client/startup/mergeSubscriptionsAndRooms.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewInquiry.ts
apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
apps/meteor/ee/app/livechat-enterprise/server/lib/SlaNPriorityHelper.ts
apps/meteor/ee/server/models/raw/LivechatInquiry.ts
apps/meteor/ee/server/models/raw/LivechatRooms.ts
apps/meteor/server/models/raw/LivechatInquiry.ts
apps/meteor/tests/data/livechat/priorities.ts
apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
packages/core-typings/src/IInquiry.ts
packages/core-typings/src/IOmnichannelServiceLevelAgreements.ts
packages/core-typings/src/IRoom.ts

[OC-559](https://rocketchat.atlassian.net/browse/OC-559)
[OC-559]: https://rocketchat.atlassian.net/browse/OC-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Incorrect sorting policy for conflicts withing priorities and SLA's

---

apps/meteor/ee/app/livechat-enterprise/server/settings.ts

[FIX] Changed sorting mechanism select option from "Service level agreement" to "SLA Policies"

---

apps/meteor/client/components/VerticalBar/VerticalBarActions.tsx
apps/meteor/client/components/message/content/attachments/default/ActionAttachtment.tsx
apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
apps/meteor/client/views/admin/apps/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
packages/ui-client/src/components/Card/CardFooter.tsx
packages/ui-client/src/components/Header/ToolBox/ToolBox.tsx
packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupControllers.tsx
packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupFooterButtons.tsx
packages/web-ui-registration/src/RegisterFormDisabled.tsx
yarn.lock

Chore: Remove medium prop from ButtonGroup 

---

apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx

The room manager wasn't being cleared when the livechat chat was forwarded.

[FIX] Not all messages in chat conversations are available when forwarding between agents or departments.

---

apps/meteor/client/providers/MeteorProvider.tsx
apps/meteor/client/views/root/AppRoot.tsx

Jira Issue [VC-39]
[VC-39]: https://rocketchat.atlassian.net/browse/VC-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: OmnichannelRoomIconProvider order breaking VideoConfPopup

---

apps/meteor/app/apps/lib/misc/transformMappedData.js
apps/meteor/app/apps/server/communication/rest.js
apps/meteor/app/apps/server/communication/uikit.ts
apps/meteor/ee/app/apps/bridges/commands.ts
apps/meteor/ee/app/apps/bridges/listeners.js
apps/meteor/ee/app/apps/bridges/livechat.ts
apps/meteor/ee/app/apps/bridges/messages.ts
apps/meteor/ee/app/apps/bridges/rooms.ts
apps/meteor/ee/app/apps/bridges/settings.ts
apps/meteor/ee/app/apps/bridges/users.ts
apps/meteor/ee/app/apps/converterService.ts
apps/meteor/ee/app/apps/converters/departments.js
apps/meteor/ee/app/apps/converters/messages.js
apps/meteor/ee/app/apps/converters/rooms.js
apps/meteor/ee/app/apps/converters/uploads.js
apps/meteor/ee/app/apps/converters/users.js
apps/meteor/ee/app/apps/converters/visitors.js
apps/meteor/ee/app/apps/service.ts
apps/meteor/server/sdk/types/IAppsConverterService.ts
yarn.lock

[FIX] asyncawaitify app converters

---

apps/meteor/ee/client/omnichannel/additionalForms/PrioritiesSelect.tsx

[IMPROVE] Added PriorityIcon to PrioritiesSelect

---

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx

This PR adds the column priority to the current chats table. 
OC-612

[NEW] Added new priority column to current chats table

---

apps/meteor/client/views/admin/settings/inputs/StringSettingInput.tsx
apps/meteor/ee/client/omnichannel/priorities/PrioritiesPage.tsx
apps/meteor/ee/client/omnichannel/priorities/PriorityEditForm.tsx
apps/meteor/tests/e2e/omnichannel-priorities.spec.ts
apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts
apps/meteor/tests/e2e/page-objects/omnichannel-priorities.ts

Chore: Implemented e2e tests for priorities

---

apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
apps/meteor/client/sidebar/RoomMenu.tsx
apps/meteor/ee/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx

[NEW] Added priorities sidebar menu

---

apps/meteor/ee/app/apps/bridges/internal.ts
apps/meteor/ee/app/apps/bridges/livechat.ts
apps/meteor/server/models/raw/Subscriptions.ts

[FIX] Use fibers on async calls

---

apps/meteor/client/views/root/PageLoading.tsx
apps/meteor/tests/e2e/config/global-setup.ts
apps/meteor/tests/e2e/config/global.d.ts
apps/meteor/tests/e2e/utils/test.ts

Chore: Aria busy indicators

---

apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
apps/meteor/client/views/room/providers/RoomProvider.tsx

Check if the data came from `room.findOne` is truly undefined to prevent redirect while `useReactiveQuery` still fetching.

[FIX] Clicking on view full icon navigates user to Home Screen

---

apps/meteor/client/sidebar/RoomMenu.tsx

[IMPROVE] Changed RoomMenu maxHeight to accommodate priorities

---

apps/meteor/app/livechat/server/api/v1/room.ts
apps/meteor/ee/server/models/raw/LivechatRooms.ts

[OC-645](https://rocketchat.atlassian.net/browse/OC-645)
[OC-645]: https://rocketchat.atlassian.net/browse/OC-645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Transcript email is not sent if chat is closed by visitor

---

apps/meteor/server/startup/migrations/v287.ts
apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts

[FIX] Migration for priorities

---

apps/meteor/client/components/message/variants/RoomMessage.tsx
apps/meteor/tests/e2e/permissions.spec.ts

Chore: Wait message to not be Busy

---

apps/meteor/app/apps/server/settings.ts
apps/meteor/app/apps/server/startup.ts
apps/meteor/ee/app/apps/orchestrator.js
apps/meteor/ee/app/apps/orchestratorFactory.ts
apps/meteor/ee/app/apps/service.ts
apps/meteor/server/main.ts
apps/meteor/server/sdk/types/IAppsService.ts

Remove settings from the apps-engine service to remove Meteor dependencies. The settings were moved to the old apps-engine folder.
[AE-102](https://rocketchat.atlassian.net/browse/AE-102)
[AE-102]: https://rocketchat.atlassian.net/browse/AE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[IMPROVE] Remove settings from apps-engine service

---

packages/livechat/src/lib/room.js
packages/livechat/src/routes/ChatFinished/component.js

Issue pointed out in this comment -> https://rocketchat.atlassian.net/browse/OC-619?focusedCommentId=13383

[FIX] Hide generated PDF on Livechat upon chat close

---

apps/meteor/tests/end-to-end/api/00-miscellaneous.js

Regression: fix api tests

---

apps/meteor/client/components/RoomAutoComplete/RoomAutoComplete.tsx

Chore: RoomAutocomplete Debounce Query

---

ee/packages/pdf-worker/src/templates/ChatTranscript/components/Quotes.tsx

Chore: Refactored Quotes component to use recursiveness

---

apps/meteor/client/components/ScrollableContentWrapper.tsx
apps/meteor/client/sidebar/RoomList/ScrollerWithCustomProps.tsx

Regression: Scroll bars in sidebar

---

apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx

Regression: Video Recorder "record" button alignment

---

.github/workflows/ci-test-e2e.yml

Chore: Fix CI docker publish

---

.github/workflows/ci.yml

Chore: Fix CI Docker Alpine build missing

---

apps/meteor/client/lib/chats/flows/processSlashCommand.ts
yarn.lock

Regression: Slash commands detected at any line

---

.github/workflows/ci-test-e2e.yml
.github/workflows/ci-test-unit.yml

Since we are sharding tests makes no sense failing fast, this can omit errors in other suites

Chore: Remove fail-fast from matrix strategy

---

apps/meteor/client/components/AdministrationList/AdministrationModelList.tsx

[https://rocketchat.atlassian.net/browse/CS-359](https://rocketchat.atlassian.net/browse/CS-359)

Regression: Hide Workspace registration feature for non-admin users

---

.github/workflows/ci.yml

today, the way we run our tests, there is no advantage in running using the debug build. The opposite, it makes the UI slower, and requires more server resources.

Chore: Remove `meteor build --debug` option

---

apps/meteor/server/modules/notifications/notifications.module.ts

[BREAK] Remove support to deprecated typing event

---

yarn.lock

Regression to fix URL parsing issues

Regression: message-parse version update

---

apps/meteor/ee/app/license/server/lib/isUnderAppLimits.ts
apps/meteor/ee/app/license/server/license.ts
apps/meteor/server/services/apps-engine/service.ts
packages/core-services/src/index.ts
packages/core-services/src/types/IAppsEngineService.ts

Makes the apps limitation functionality depend on methods from the Apps Engine's service instead of a dynamic import of the apps orchestrator, making the engine's load process deterministic.
It's an "trial and error" situation. When starting up the server, the apps engine might load or not.

Regression: Fix intermitent apps engine startup

---

apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
apps/meteor/client/views/marketplace/helpers/installApp.ts
apps/meteor/client/views/marketplace/helpers/updateApp.ts
apps/meteor/ee/client/apps/orchestrator.ts
packages/rest-typings/src/apps/index.ts

Installation was failing for apps that did not include a set o permissions required because the process was short circuiting in those cases. However, they are valid as they signify apps that function with the default permission set
AE-107

Regression: Installation of some apps fail

---

apps/meteor/client/components/Omnichannel/modals/EnterpriseDepartmentsModal.tsx

This PR adjusts the logic to display the correct message on the departments upsell modal. This affects users with a trial license, expired expired licence, as well as no licence.
[OC-712](https://rocketchat.atlassian.net/browse/OC-712)
[OC-712]: https://rocketchat.atlassian.net/browse/OC-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Regression: Adjusted departments upsell modal message

---

apps/meteor/tests/e2e/email-inboxes.spec.ts
apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts

Chore: Fix Email Inbox flaky test

---

apps/meteor/client/views/room/contextualBar/Threads/hooks/useGetMessageByID.ts

Regression: Decrypt thread main message for room

---

apps/meteor/client/lib/createRouteGroup.tsx
apps/meteor/ee/app/license/client/index.ts
apps/meteor/ee/client/hooks/useHasLicenseModule.ts

Regression: Fix hasLicense failing due call stack limit reasons

---

apps/meteor/client/views/admin/integrations/new/NewZapier.js

Introduced by https://github.com/RocketChat/Rocket.Chat/pull/27744
[TC-363]
[TC-363]: https://rocketchat.atlassian.net/browse/TC-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Regression: Zapier Callout using wrong props

---

.github/workflows/ci-test-e2e.yml
.github/workflows/ci.yml

According to [GitHub Actions docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow), `secrets: inherit` works only when running code from the same organization, so it doesn't work for PR from external forks.

Chore: Manually define shared secrets to reusable workflows

---

apps/meteor/client/views/room/contextualBar/Apps/AppsWithData.tsx
apps/meteor/ee/server/apps/orchestrator.js
apps/meteor/ee/server/apps/startup.ts
apps/meteor/ee/server/startup/index.ts
apps/meteor/package.json
yarn.lock

* App loading routine was forcing apps to be enabled, even if they were previously disabled
* Isolated Apps startup routine for more granular control
Depends on Apps.engine PR - [#594](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/594)
[AE-109](https://rocketchat.atlassian.net/browse/AE-109)
[AE-109]: https://rocketchat.atlassian.net/browse/AE-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Regression: Apps-Engine startup process was faulty

---

apps/meteor/app/api/server/settings.ts
apps/meteor/app/api/server/v1/users.ts
apps/meteor/app/file-upload/server/lib/FileUpload.js
apps/meteor/app/file-upload/server/lib/requests.js
apps/meteor/app/file-upload/server/startup/settings.ts
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/tests/end-to-end/api/01-users.js
apps/meteor/tests/end-to-end/api/09-rooms.js

This PR creates 2 new settings to limit access of files to room members only and to limit access to the API `users.list` when permission `view-outside-room` is not granted. Those settings are temporary and will be removed once the changes are applied as final during next breaking changes.

Chore: New temporary settings to limit access to files and outside room members

---

apps/meteor/client/views/room/contextualBar/MessageSearchTab/components/MessageSearchForm.tsx
packages/core-typings/src/search/IMessageSearchProvider.ts

The global search toggle was not being shown due to a wrong check:
ARCH-174

Regression: Fix not showing global search option

---

apps/meteor/app/custom-oauth/server/custom_oauth_server.js
apps/meteor/app/lib/server/oauth/facebook.js
apps/meteor/app/lib/server/oauth/google.js
apps/meteor/app/lib/server/oauth/oauth.js
apps/meteor/app/lib/server/oauth/twitter.js

refactor: remove `Promise.await` calls from twitter Oauth implementation

---

apps/meteor/app/api/server/lib/messages.ts
apps/meteor/app/api/server/v1/channels.ts
apps/meteor/app/api/server/v1/groups.ts
apps/meteor/app/lib/server/methods/getMessages.ts
apps/meteor/app/livechat/server/api/v1/room.ts
apps/meteor/app/livechat/server/hooks/sendToCRM.js
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/app/livechat/server/methods/registerGuest.js
apps/meteor/app/livechat/server/methods/setDepartmentForVisitor.js
apps/meteor/app/mentions/server/methods/getUserMentionsByChannel.js
apps/meteor/app/message-mark-as-unread/server/unreadMessages.js
apps/meteor/app/models/server/models/Messages.js
apps/meteor/app/otr/server/methods/deleteOldOTRMessages.ts
apps/meteor/app/threads/server/methods/getThreadMessages.ts
apps/meteor/server/methods/loadMissedMessages.ts
apps/meteor/server/methods/loadNextMessages.ts
apps/meteor/server/methods/loadSurroundingMessages.ts
apps/meteor/server/models/raw/Messages.ts
packages/model-typings/src/models/IMessagesModel.ts

refactor(models): Use Messages Raw model (1/N)

---

apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
apps/meteor/app/livechat/server/methods/registerGuest.ts
apps/meteor/app/livechat/server/methods/saveBusinessHour.ts
apps/meteor/app/statistics/server/lib/statistics.ts
apps/meteor/app/statistics/server/methods/getStatistics.js
apps/meteor/app/threads/server/methods/followMessage.ts
apps/meteor/app/threads/server/methods/unfollowMessage.ts
apps/meteor/app/utils/server/functions/getMongoInfo.js
apps/meteor/app/version-check/server/index.ts
apps/meteor/ee/app/livechat-enterprise/server/methods/removeBusinessHour.ts
apps/meteor/server/methods/createDirectMessage.ts
apps/meteor/server/startup/serverRunning.js

https://rocketchat.atlassian.net/browse/ARCH-512
https://rocketchat.atlassian.net/browse/ARCH-551
https://rocketchat.atlassian.net/browse/ARCH-395
https://rocketchat.atlassian.net/browse/ARCH-465
https://rocketchat.atlassian.net/browse/ARCH-466
https://rocketchat.atlassian.net/browse/ARCH-479
https://rocketchat.atlassian.net/browse/ARCH-480
https://rocketchat.atlassian.net/browse/ARCH-481
https://rocketchat.atlassian.net/browse/ARCH-482
https://rocketchat.atlassian.net/browse/ARCH-483

refactor(promise.await): getMongoInfo.js, versio-check and missing meteor methods

---

apps/meteor/app/importer-csv/server/importer.js
apps/meteor/app/importer-hipchat-enterprise/server/importer.js
apps/meteor/app/importer-pending-avatars/server/importer.js
apps/meteor/app/importer-pending-files/server/importer.js
apps/meteor/app/importer-slack-users/server/importer.js
apps/meteor/app/importer-slack/server/importer.js
apps/meteor/app/importer/server/classes/ImporterBase.js
apps/meteor/app/importer/server/methods/downloadPublicImportFile.ts
apps/meteor/app/importer/server/methods/getLatestImportOperations.ts
apps/meteor/app/importer/server/methods/uploadImportFile.ts

regression: fix CI

---

apps/meteor/app/mentions/server/Mentions.js
apps/meteor/app/mentions/server/server.js
apps/meteor/ee/app/teams-mention/server/EEMentionQueries.js
apps/meteor/ee/app/teams-mention/server/EESpotlight.js
apps/meteor/ee/app/teams-mention/server/index.ts
apps/meteor/server/lib/spotlight.js
apps/meteor/server/publications/spotlight.ts
apps/meteor/tests/unit/app/mentions/server.tests.js

refactor: Remove Promise.await from teams-mention feature

---

.github/workflows/ci.yml

chore: Make CI fail if checks fail

---

apps/meteor/app/federation/server/endpoints/uploads.js
apps/meteor/app/federation/server/hooks/afterAddedToRoom.js
apps/meteor/app/federation/server/hooks/afterCreateDirectRoom.js
apps/meteor/app/federation/server/hooks/afterCreateRoom.js
apps/meteor/app/federation/server/hooks/afterDeleteMessage.js
apps/meteor/app/federation/server/hooks/afterLeaveRoom.js
apps/meteor/app/federation/server/hooks/afterMuteUser.js
apps/meteor/app/federation/server/hooks/afterRemoveFromRoom.js
apps/meteor/app/federation/server/hooks/afterSaveMessage.js
apps/meteor/app/federation/server/hooks/afterSetReaction.js
apps/meteor/app/federation/server/hooks/afterUnmuteUser.js
apps/meteor/app/federation/server/hooks/afterUnsetReaction.js
apps/meteor/app/federation/server/hooks/beforeDeleteRoom.js
apps/meteor/app/importer-slack/server/importer.js
apps/meteor/app/livechat/server/api/v1/visitor.ts
apps/meteor/app/livechat/server/hooks/afterUserActions.ts
apps/meteor/app/livechat/server/hooks/beforeDelegateAgent.js
apps/meteor/app/livechat/server/hooks/processRoomAbandonment.js
apps/meteor/app/livechat/server/hooks/saveAnalyticsData.js
apps/meteor/app/livechat/server/hooks/saveContactLastChat.js
apps/meteor/app/livechat/server/hooks/saveLastMessageToInquiry.ts
apps/meteor/app/livechat/server/hooks/sendEmailTranscriptOnClose.ts
apps/meteor/app/livechat/server/sendMessageBySMS.ts
apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
apps/meteor/app/meteor-accounts-saml/server/loginHandler.ts
apps/meteor/app/retention-policy/server/cronPruneMessages.ts
apps/meteor/app/slackbridge/server/SlackAdapter.js

refactor(promise.await): Low hanging fruits (1/N)

---

apps/meteor/app/api/server/v1/push.ts
apps/meteor/app/notification-queue/server/NotificationQueue.ts
apps/meteor/app/push-notifications/server/lib/PushNotification.ts
apps/meteor/app/push/server/index.ts
apps/meteor/app/push/server/methods.ts
apps/meteor/app/push/server/push.js
apps/meteor/server/lib/pushConfig.ts
apps/meteor/server/models/AppsTokens.ts
apps/meteor/server/models/raw/AppsTokens.ts
apps/meteor/server/models/startup.ts
apps/meteor/server/startup/migrations/v269.ts
apps/meteor/server/startup/migrations/v273.ts
apps/meteor/server/startup/migrations/v276.ts
packages/core-typings/src/AppsTokens.ts
packages/core-typings/src/index.ts
packages/model-typings/src/index.ts
packages/model-typings/src/models/IAppsTokensModel.ts
packages/models/src/index.ts

refactor: Don't use meteor collections on migrations

---

.github/workflows/ci.yml

The new Docker tag will be like `sha-607e6f9`.
I've added logs of all tags published.
This changes can only be tested/seen once it gets merged to `develop` 😬

ci(docker): Push Docker tag for commit hash

---

apps/meteor/client/views/marketplace/AppsList/AppRow.tsx

Changed the typography of the app name and shortDescription in the AppRow component so that it better follows figma specs.
Demo images:
Before:
After :
[AECO-48]: https://rocketchat.atlassian.net/browse/AECO-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Change marketplace AppRow typography

---

apps/meteor/app/api/server/v1/chat.ts
apps/meteor/app/apps/server/bridges/messages.ts
apps/meteor/app/cas/server/cas_server.js
apps/meteor/app/discussion/server/methods/createDiscussion.ts
apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.js
apps/meteor/app/integrations/server/api/api.js
apps/meteor/app/integrations/server/index.ts
apps/meteor/app/integrations/server/lib/triggerHandler.js
apps/meteor/app/integrations/server/methods/outgoing/replayOutgoingIntegration.ts
apps/meteor/app/integrations/server/startup.ts
apps/meteor/app/irc/server/irc-bridge/peerHandlers/sentMessage.js
apps/meteor/app/lib/server/functions/index.ts
apps/meteor/app/lib/server/functions/processWebhookMessage.js
apps/meteor/app/lib/server/functions/sendMessage.js
apps/meteor/app/lib/server/functions/sendMessage.ts
apps/meteor/app/livechat/server/hooks/offlineMessageToChannel.js
apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/livechat/server/lib/LivechatTyped.ts
apps/meteor/app/livechat/server/lib/QueueManager.js
apps/meteor/app/slackbridge/server/RocketAdapter.js
apps/meteor/app/slackbridge/server/SlackAdapter.js
apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts
apps/meteor/server/lib/sendDirectMessageToUsers.ts
apps/meteor/server/lib/sendMessagesToAdmins.ts
apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Message.ts
apps/meteor/server/services/video-conference/service.ts

refactor: convert sendmessage to async

---

apps/meteor/app/slashcommand-asciiarts/lib/gimme.ts
apps/meteor/app/slashcommand-asciiarts/lib/lenny.ts
apps/meteor/app/slashcommand-asciiarts/lib/shrug.ts
apps/meteor/app/slashcommand-asciiarts/lib/tableflip.ts
apps/meteor/app/slashcommand-asciiarts/lib/unflip.ts
apps/meteor/app/slashcommands-archiveroom/server/server.ts
apps/meteor/app/slashcommands-create/server/server.ts
apps/meteor/app/slashcommands-hide/server/hide.ts
apps/meteor/app/slashcommands-invite/server/server.ts
apps/meteor/app/slashcommands-inviteall/server/server.ts
apps/meteor/app/slashcommands-join/server/server.ts
apps/meteor/app/slashcommands-kick/server/server.ts
apps/meteor/app/slashcommands-leave/server/leave.ts
apps/meteor/app/slashcommands-me/server/me.ts
apps/meteor/app/slashcommands-msg/server/server.ts
apps/meteor/app/slashcommands-mute/server/mute.ts
apps/meteor/app/slashcommands-mute/server/unmute.ts
apps/meteor/app/slashcommands-status/server/status.ts
apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
apps/meteor/app/user-status/server/methods/setUserStatus.ts
apps/meteor/ee/app/api-enterprise/server/canned-responses.ts
apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/resumeOnHold.ts

Jira:
ARCH-615
ARCH-616
ARCH-617
ARCH-618
ARCH-619
ARCH-620
ARCH-621
ARCH-622
ARCH-623
ARCH-624
ARCH-625
ARCH-626
ARCH-627
ARCH-628
ARCH-629
ARCH-630
ARCH-631
ARCH-633
ARCH-634
ARCH-635
ARCH-636
ARCH-637

refactor: Convert meteor call to callAsync (2/N)

---

apps/meteor/app/apps/server/bridges/livechat.ts
apps/meteor/app/livechat/server/api/lib/livechat.ts
apps/meteor/app/livechat/server/api/v1/config.ts
apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/app/livechat/server/lib/QueueManager.js
apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts

TODO: Improve testing around these functions. This should have been caught by tests 👀

refactor: Add missing await to online function

---

apps/meteor/app/integrations/server/triggers.js
apps/meteor/app/lib/server/functions/checkUsernameAvailability.ts
apps/meteor/app/lib/server/lib/processDirectEmail.ts
apps/meteor/app/livechat/server/hooks/saveLastVisitorMessageTs.js
apps/meteor/app/livechat/server/hooks/sendToCRM.js
apps/meteor/app/livechat/server/lib/stream/agentStatus.ts
apps/meteor/app/utils/server/functions/getMongoInfo.js
apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
apps/meteor/ee/app/settings/server/settings.ts
apps/meteor/ee/server/apps/orchestrator.js
apps/meteor/server/cron/nps.js

refactor: Remove easy to remove promise.awaits

---

apps/meteor/app/theme/client/imports/general/base_old.css

I had to revert a css deletion to rollback the styles form Upload and Unread indicators
**Current (problem):** 
**Expected: (current changes)**
Probably caused by: https://github.com/RocketChat/Rocket.Chat/pull/28140
- Send a big attachment to see the indicator 
- Go to a channel with several unread message
TC-565

regression: removed css for unread and upload indicators

---

apps/meteor/app/apps/server/bridges/livechat.ts
apps/meteor/app/channel-settings/server/functions/saveReactWhenReadOnly.ts
apps/meteor/app/channel-settings/server/functions/saveRoomSystemMessages.ts
apps/meteor/app/channel-settings/server/methods/saveRoomSettings.ts
apps/meteor/app/lib/lib/MessageTypes.ts
apps/meteor/app/lib/server/functions/archiveRoom.ts
apps/meteor/app/lib/server/functions/index.ts
apps/meteor/app/lib/server/functions/loadMessageHistory.ts
apps/meteor/app/lib/server/functions/unarchiveRoom.ts
apps/meteor/app/lib/server/lib/getHiddenSystemMessages.ts
apps/meteor/app/lib/server/methods/archiveRoom.ts
apps/meteor/app/lib/server/methods/getChannelHistory.ts
apps/meteor/app/lib/server/methods/unarchiveRoom.ts
apps/meteor/app/livechat/server/api/v1/message.ts
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/app/livechat/server/methods/loadHistory.ts
apps/meteor/app/models/server/models/Messages.js
apps/meteor/app/slackbridge/server/SlackAdapter.js
apps/meteor/app/slashcommands-archiveroom/server/server.ts
apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
apps/meteor/server/methods/loadHistory.ts
apps/meteor/server/models/raw/Messages.ts
packages/core-typings/src/IRoom.ts
packages/model-typings/src/models/IMessagesModel.ts

refactor(models): Use Messages Raw model (6/N)

---

apps/meteor/app/api/server/v1/cloud.ts
apps/meteor/app/api/server/v1/roles.ts
apps/meteor/app/authorization/server/functions/hasRole.ts
apps/meteor/app/authorization/server/index.js
apps/meteor/app/bot-helpers/server/index.ts
apps/meteor/app/file-upload/server/lib/FileUpload.js
apps/meteor/app/lib/server/methods/leaveRoom.ts
apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/app/livechat/server/lib/RoutingManager.js
apps/meteor/app/livechat/server/methods/saveAgentInfo.ts
apps/meteor/app/livechat/server/roomAccessValidator.compatibility.ts
apps/meteor/definition/IRoomTypeConfig.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/applyDepartmentRestrictions.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeRoutingChat.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/checkAgentBeforeTakeInquiry.ts
apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
apps/meteor/ee/app/voip-enterprise/server/services/voipService.ts
apps/meteor/server/lib/rooms/roomCoordinator.ts
apps/meteor/server/lib/rooms/roomTypes/livechat.ts
apps/meteor/server/methods/removeUserFromRoom.ts
apps/meteor/server/services/omnichannel-voip/service.ts

refactor: remove hasRole to hasRoleAsync

---

apps/meteor/app/importer-pending-files/server/importer.js
apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
apps/meteor/app/lib/server/functions/deleteUser.ts
apps/meteor/app/lib/server/functions/saveUserIdentity.ts
apps/meteor/app/models/server/models/Messages.js
apps/meteor/app/slackbridge/server/RocketAdapter.js
apps/meteor/app/slackbridge/server/SlackAdapter.js
apps/meteor/ee/server/lib/message-read-receipt/ReadReceipt.js
apps/meteor/server/models/raw/Messages.ts
packages/model-typings/src/models/IMessagesModel.ts

refactor(models): Use Messages Raw model (7/N)

---

apps/meteor/app/api/server/api.js

regression: await `getUserInfo` promise on login

---

apps/meteor/app/lib/server/functions/notifications/desktop.js
apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js

regression: fix notifyDesktopUser

---

apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx

Hide offline workspace registration option for only disconnected workspaces.

fix: hide offline registration option for disconnected workspaces

---

apps/meteor/app/apps/server/bridges/livechat.ts
apps/meteor/app/apps/server/converters/departments.js
apps/meteor/app/apps/server/converters/rooms.js
apps/meteor/app/livechat/imports/server/rest/inquiries.ts
apps/meteor/app/livechat/imports/server/rest/sms.js
apps/meteor/app/livechat/server/api/lib/livechat.ts
apps/meteor/app/livechat/server/api/v1/offlineMessage.ts
apps/meteor/app/livechat/server/hooks/offlineMessageToChannel.js
apps/meteor/app/livechat/server/lib/Helper.js
apps/meteor/app/livechat/server/lib/Livechat.js
apps/meteor/app/livechat/server/methods/sendOfflineMessage.ts
apps/meteor/app/models/server/models/LivechatDepartment.js
apps/meteor/ee/app/canned-responses/server/methods/saveCannedResponse.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/addDepartmentAncestors.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/afterForwardChatToDepartment.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/applySimultaneousChatsRestrictions.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeForwardRoomToDepartment.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/onLoadForwardDepartmentRestrictions.ts
apps/meteor/lib/callbacks.ts
packages/model-typings/src/models/ILivechatDepartmentModel.ts

refactor: `LivechatDepartments` - 1/2

---

apps/meteor/app/theme/client/rocketchat.font.css

fix(client): Fuselage's icon font reloads too often

---

apps/meteor/app/api/server/v1/channels.ts
apps/meteor/app/api/server/v1/groups.ts
apps/meteor/app/api/server/v1/integrations.ts
apps/meteor/app/api/server/v1/teams.ts
apps/meteor/app/authorization/server/functions/hasPermission.ts
apps/meteor/app/authorization/server/index.js
apps/meteor/app/discussion/server/methods/createDiscussion.ts
apps/meteor/app/integrations/server/lib/validateOutgoingIntegration.ts
apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts
apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts
apps/meteor/app/lib/server/methods/saveSetting.ts
apps/meteor/server/lib/spotlight.js
apps/meteor/server/publications/settings/index.ts

refactor: move hasAllPermission to hasAllPermissionAsync

---

apps/meteor/app/channel-settings/server/functions/saveReactWhenReadOnly.ts
apps/meteor/app/channel-settings/server/functions/saveRoomAnnouncement.js
apps/meteor/app/channel-settings/server/functions/saveRoomDescription.js
apps/meteor/app/channel-settings/server/functions/saveRoomEncrypted.ts
apps/meteor/app/channel-settings/server/functions/saveRoomName.js
apps/meteor/app/channel-settings/server/functions/saveRoomReadOnly.ts
apps/meteor/app/channel-settings/server/functions/saveRoomTopic.ts
apps/meteor/app/channel-settings/server/functions/saveRoomType.js
apps/meteor/app/lib/server/functions/archiveRoom.ts
apps/meteor/app/lib/server/functions/setRoomAvatar.ts
apps/meteor/app/lib/server/functions/unarchiveRoom.ts
apps/meteor/app/livechat/server/lib/LivechatTyped.ts
apps/meteor/app/models/server/models/Messages.js
apps/meteor/app/slackbridge/server/SlackAdapter.js
apps/meteor/server/models/raw/Messages.ts
apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
packages/model-typings/src/models/IMessagesModel.ts

refactor(models): Use Messages Raw model (8/N)

---

apps/meteor/client/components/TwoFactorModal/TwoFactorEmailModal.tsx
apps/meteor/packages/rocketchat-i18n/i18n/ar.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/ca.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/cs.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/da.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/es.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/fr.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/hu.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/it.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/ja.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/ka-GE.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/ko.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/nl.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/pl.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/pt-BR.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/ru.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/sv.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/tr.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/zh-TW.i18n.json
apps/meteor/packages/rocketchat-i18n/i18n/zh.i18n.json
yarn.lock

From:
"Verify_your_email_`for`_the_code_we_sent": "Verify your email `for` the code we sent",
To:
"Verify_your_email_`with`_the_code_we_sent": "Verify your email `with` the code we sent",
TC-20

i18n: fix sentence in 2fa email modal text

---

apps/meteor/client/views/banners/hooks/useUserBanners.ts

A bug in `useUserBanners` hooks will generate a infinite loop whenever a new user banner (e.g. new version announcement) is available. This PR fixes it.

fix: Avoid `useEffect` loop

---

.github/workflows/codeql-analysis.yml

chore: Update `codeql` to v2

---

apps/meteor/app/livechat/server/methods/webhookTest.ts
apps/meteor/app/push/server/push.js
apps/meteor/app/version-check/server/functions/getNewUpdates.ts
apps/meteor/ee/server/apps/appRequestsCron.ts
apps/meteor/ee/server/apps/cron.js
apps/meteor/ee/server/apps/marketplace/appInstall.ts
apps/meteor/ee/server/apps/marketplace/appRequestNotifyUsers.ts
apps/meteor/server/cron/statistics.js
apps/meteor/server/services/nps/getAndCreateNpsSurvey.ts
apps/meteor/server/services/nps/sendNpsResults.ts
apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts
apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts

refactor: Use `fetch` instead of `meteor/http`

---

apps/meteor/tests/e2e/omnichannel-agents.spec.ts
apps/meteor/tests/e2e/omnichannel-manager.spec.ts

ci: fix flaky tests

---

apps/meteor/app/integrations/server/api/api.js
apps/meteor/app/lib/server/functions/insertMessage.js
apps/meteor/app/lib/server/functions/sendMessage.js
apps/meteor/app/livechat/server/lib/Analytics.js
apps/meteor/app/livechat/server/lib/analytics/departments.js
apps/meteor/app/livechat/server/startup.ts
apps/meteor/app/livechat/server/statistics/LivechatAgentActivityMonitor.ts
apps/meteor/app/push/server/push.js
apps/meteor/ee/app/livechat-enterprise/server/api/departments.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/afterInquiryQueued.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/autoCloseQueued.ts
apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts
apps/meteor/ee/app/livechat-enterprise/server/startup.ts
apps/meteor/ee/server/apps/appRequestsCron.ts
apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts

refactor: Remove more promise awaits

---

apps/meteor/ee/app/authorization/client/index.ts

regression: invalid callback callAsync

---

apps/meteor/app/federation/server/endpoints/dispatch.js
apps/meteor/app/federation/server/hooks/afterCreateRoom.js
apps/meteor/app/integrations/server/lib/triggerHandler.js
apps/meteor/app/lib/server/functions/deleteRoom.ts
apps/meteor/app/lib/server/functions/setUserAvatar.ts
apps/meteor/app/lib/server/lib/interceptDirectReplyEmails.js
apps/meteor/app/notifications/server/lib/Notifications.ts
apps/meteor/app/slackbridge/server/SlackAdapter.js
apps/meteor/server/methods/eraseRoom.ts

refactor: deleteRoom to async

---

.github/workflows/ci.yml

Testing from a fork since this is required to checkout the correct file version.

ci: add branch config back to checkout action

---

apps/meteor/app/custom-sounds/server/methods/deleteCustomSound.ts
apps/meteor/app/custom-sounds/server/methods/insertOrUpdateSound.ts
apps/meteor/app/custom-sounds/server/methods/uploadCustomSound.ts
apps/meteor/app/custom-sounds/server/startup/custom-sounds.js
apps/meteor/app/emoji-custom/server/methods/deleteEmojiCustom.ts
apps/meteor/app/emoji-custom/server/methods/insertOrUpdateEmoji.ts
apps/meteor/app/emoji-custom/server/methods/uploadEmojiCustom.ts
apps/meteor/app/emoji-custom/server/startup/emoji-custom.js

regression: add missing await for RocketChatFile

---

apps/meteor/app/slashcommands-hide/server/hide.ts
apps/meteor/app/slashcommands-open/client/client.ts
apps/meteor/app/slashcommands-status/client/status.ts
apps/meteor/app/slashcommands-status/server/status.ts
apps/meteor/app/slashcommands-topic/client/topic.ts
apps/meteor/ee/app/livechat-enterprise/server/business-hour/Helper.ts

Introduced by https://github.com/RocketChat/Rocket.Chat/pull/28595

regression: remove callbacks from `Meteor.callAsync`

---

apps/meteor/app/custom-oauth/server/custom_oauth_server.js

refactor: Isolate Promise.await of updateOrCreateUserFromExternalService

---

apps/meteor/app/importer-pending-files/server/importer.js

refactor: Remove Promise.await from importer-pendind-file.js

---

apps/meteor/app/api/server/api.ts
apps/meteor/ee/client/apps/orchestrator.ts
apps/meteor/ee/server/apps/communication/rest.ts
apps/meteor/server/lib/sendMessagesToAdmins.ts
packages/rest-typings/src/apps/index.ts

refactor: convert apps api to ts

---

apps/meteor/app/api/server/v1/settings.ts
apps/meteor/app/apple/server/appleOauthRegisterService.ts
apps/meteor/app/cas/server/cas_rocketchat.js
apps/meteor/app/custom-oauth/client/custom_oauth_client.js
apps/meteor/app/custom-oauth/server/custom_oauth_server.js
apps/meteor/app/dolphin/lib/common.js
apps/meteor/app/lib/server/functions/getAvatarSuggestionForUser.ts
apps/meteor/app/lib/server/methods/refreshOAuthService.ts
apps/meteor/app/lib/server/oauth/oauth.js
apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js
apps/meteor/app/meteor-accounts-saml/client/saml_client.js
apps/meteor/app/meteor-accounts-saml/server/lib/settings.ts
apps/meteor/app/wordpress/lib/common.js
apps/meteor/server/services/meteor/service.ts
apps/meteor/server/startup/migrations/v267.ts

ARCH-979
(Missing: FE refactor)

refactor: `Service Configuration` async on server

---

apps/meteor/app/apps/server/bridges/internal.ts
apps/meteor/app/apps/server/bridges/livechat.ts
apps/meteor/app/authentication/server/startup/index.js
apps/meteor/server/configuration/accounts_meld.js

refactor: Isolate last Promise.await calls on accounts’ code

---

apps/meteor/app/e2e/client/rocketchat.e2e.ts

A field was incorrectly defined as `private` while used as `public` in a JavaScript module.

regression(e2e): Missing private key blocks sending message in encrypted rooms

---

apps/meteor/app/apps/server/bridges/commands.ts
apps/meteor/client/components/Sidebar/SidebarGenericItem.tsx
apps/meteor/client/components/message/notification/MessageNotification.tsx
apps/meteor/client/lib/2fa/process2faReturn.ts
apps/meteor/client/providers/VideoConfProvider.tsx
apps/meteor/client/sidebar/header/UserDropdown.tsx
apps/meteor/client/startup/iframeCommands.ts
apps/meteor/client/views/admin/rooms/RoomsTable.tsx
apps/meteor/ee/client/views/admin/engagementDashboard/dataView/periods.ts
apps/meteor/package.json
packages/core-services/package.json
packages/core-typings/package.json
packages/eslint-config/package.json
packages/fuselage-ui-kit/package.json
packages/instance-status/package.json
yarn.lock

It upgrades and equalizes Prettier versions across packages.
The major difference was the welcome change from `typeof x[Y]` to `(typeof x)[Y]`.

chore(deps): Prettier version

---

apps/meteor/app/lib/server/startup/rateLimiter.js

revert: removal of `Meteor.bindEnvironment` on `DDPRateLimiter.addRule`

---

apps/meteor/package.json
yarn.lock

chore: bump apps-engine version to 1.38.1

---

apps/meteor/package.json
yarn.lock

Bump apps-engine to v1.36.1

---

apps/meteor/package.json
yarn.lock

Bump apps-engine to v1.37.2

---

apps/meteor/app/2fa/server/loginHandler.ts
apps/meteor/app/crowd/server/crowd.js
apps/meteor/app/importer/server/classes/ImportDataConverter.ts
apps/meteor/app/lib/server/functions/saveUser.js
apps/meteor/app/mailer/server/api.ts
apps/meteor/app/meteor-accounts-saml/server/lib/ServiceProvider.ts
apps/meteor/app/slackbridge/server/RocketAdapter.js
apps/meteor/client/providers/UserProvider/UserProvider.tsx
apps/meteor/definition/externals/meteor/accounts-base.d.ts
apps/meteor/package.json
apps/meteor/packages/rocketchat-mongo-config/server/index.js
apps/meteor/server/lib/ldap/Manager.ts
apps/meteor/server/methods/registerUser.ts
apps/meteor/server/methods/saveUserProfile.ts
apps/meteor/server/methods/setUserPassword.ts
apps/meteor/server/startup/initialData.js
ee/apps/ddp-streamer/package.json
packages/ui-contexts/src/UserContext.ts
packages/ui-contexts/src/hooks/useLoginWithPassword.ts
yarn.lock

chore: Update meteor types

---

apps/meteor/app/push/server/push.js

regression:  push gateway response as JSON

---

apps/meteor/client/views/room/providers/RoomProvider.tsx

This PR fixes an issue where an agent can see another agent's conversation with "manual" routing method.
[OC-680](https://rocketchat.atlassian.net/browse/OC-680)
[OC-680]: https://rocketchat.atlassian.net/browse/OC-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fixed join button being displayed for agents without permission

---

README.md

"How can I help?" link under Contributions section of readme was broken.
Before : It lead to https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help which gives page not found error.
After : changed link to https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute
https://github.com/RocketChat/Rocket.Chat/issues/28940
1. Go to readme section of repo https://github.com/RocketChat/Rocket.Chat
2. Scroll to Contributions section
3. Click on [How can I help?](https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help)

docs: how can i help? link broken

---

apps/meteor/app/2fa/server/loginHandler.ts

- Remove TOTP check on login via "Reset Password" link.
Go to **Workspace > Settings > Accounts > Two Factor Authentication** and enable it. Then logout, use the "Forgot my password" option, access the link sent to the registered e-mail and provide a new password. After confirming, the user should be logged in with no TOTP required.
TC-528

fix: Error logging in with TOTP on "reset password" workflow

---

apps/meteor/app/version-check/server/functions/getNewUpdates.ts
apps/meteor/ee/server/apps/appRequestsCron.ts
apps/meteor/ee/server/apps/cron.js
apps/meteor/ee/server/apps/marketplace/appRequestNotifyUsers.ts
apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts

Introduced by https://github.com/RocketChat/Rocket.Chat/pull/28682

regression: `fetch` JSON response doesn't have a `data` property

---

apps/meteor/server/startup/migrations/v267.ts
apps/meteor/server/startup/migrations/v287.ts
apps/meteor/server/startup/migrations/v290.ts

refactor: Remove mongo collections from migrations

---

apps/meteor/app/mailer/server/api.ts

regression: smtp connection error

---

apps/meteor/ee/server/models/AuditLog.ts
apps/meteor/ee/server/models/raw/AuditLog.ts
apps/meteor/server/models/raw/Users.js

regression: Message auditing panel not working

---

apps/meteor/client/components/Emoji.tsx

[TC-640]
[TC-640]: https://rocketchat.atlassian.net/browse/TC-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Emoji fill prop

---

apps/meteor/client/views/room/components/body/RoomBody.tsx
apps/meteor/lib/rooms/roomTypes/livechat.ts

This PR changes the way `room-info` tab is opened in livechat room to avoid race conditions from preventing the rooms from opening
[OC-877](https://rocketchat.atlassian.net/browse/OC-877)
[OC-877]: https://rocketchat.atlassian.net/browse/OC-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Livechat rooms not opening

---

apps/meteor/package.json
yarn.lock

Bump apps-engine to v1.37.3

---

apps/meteor/package.json
yarn.lock

Bump apps-engine to v1.36.2

---

apps/meteor/ee/server/services/package.json
apps/meteor/package.json
ee/apps/ddp-streamer/package.json
ee/packages/presence/package.json
packages/core-services/package.json
packages/core-typings/package.json
packages/fuselage-ui-kit/package.json
packages/rest-typings/package.json
yarn.lock

Bump apps-engine version to 1.38.2

---

apps/meteor/app/utils/server/functions/safeGetMeteorUser.ts

regression: user creation is failing

---

apps/meteor/ee/server/services/package.json
apps/meteor/package.json
ee/apps/ddp-streamer/package.json
ee/packages/presence/package.json
packages/core-services/package.json
packages/core-typings/package.json
packages/fuselage-ui-kit/package.json
packages/rest-typings/package.json
yarn.lock

chore(deps): Bump apps-engine version to 1.38.2

---

apps/meteor/app/lib/server/startup/rateLimiter.js
apps/meteor/app/slackbridge/server/RocketAdapter.js
apps/meteor/lib/utils/sleep.ts
apps/meteor/server/lib/migrations.ts

refactor: Remove _sleepForMs usage

---

apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx

regression: Missing display prop on `ComposerBoxPopupPreview`

---

apps/meteor/app/apple/lib/handleIdentityToken.ts
apps/meteor/app/autotranslate/server/googleTranslate.ts

regression: `fetch` response

---

apps/meteor/client/views/admin/settings/inputs/RoomPickSettingInput.tsx

regression: SlackBridge settings UI crashing

---

apps/meteor/app/custom-sounds/client/lib/CustomSounds.js
apps/meteor/app/emoji-custom/client/lib/emojiCustom.js
apps/meteor/app/emoji/client/emojiPicker.js
apps/meteor/app/emoji/client/lib/EmojiPicker.js
apps/meteor/app/meteor-autocomplete/client/autocomplete-client.js
apps/meteor/app/meteor-autocomplete/client/templates.js
apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts
apps/meteor/app/ui-utils/client/lib/readMessages.ts
apps/meteor/app/ui/client/lib/KonchatNotification.ts
apps/meteor/app/ui/client/views/app/photoswipeContent.ts
apps/meteor/client/lib/errorHandling.ts
apps/meteor/definition/externals/meteor/templating.d.ts
packages/eslint-config/original/index.js

refactor: No reference to jQuery types

---

apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx

[DSAR-120](https://rocketchat.atlassian.net/browse/DSAR-120)
- replace _ghost_ variant in favor of _secondary_ to fix contrast on sidebar notification
from:
to:
[DSAR-120]: https://rocketchat.atlassian.net/browse/DSAR-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Notification badge background

---

fuselage.sh

Improving the `fuselage.sh` bash script helper by:
-  adding detailed information
- add new commands like `next-all`, `latest-all`, `unlink`
- refactor `next` and `latest` actions to handle individual packages
- adding package `message-parser` to the list of packages to update

chore: Improve bash script and add new detailed infos

---

apps/meteor/client/components/Page/PageHeader.tsx

chore: `PageHeader` misaligned

---

apps/meteor/app/ui-message/client/popup/hooks/useComposerBoxPopup.ts

fix: composer slashcommands duplication 

---

apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
apps/meteor/app/ui/client/lib/KonchatNotification.ts
apps/meteor/client/providers/CallProvider/CallProvider.tsx
apps/meteor/client/providers/CustomSoundProvider.tsx
apps/meteor/client/startup/notifications/notification.ts
packages/core-typings/src/ICustomSound.ts
packages/ui-contexts/src/CustomSoundContext.ts
yarn.lock

It also refactors `CustomSounds.js` to typescript

fix: Custom Sounds not being added to the DOM correctly 

---

apps/meteor/app/custom-oauth/server/custom_oauth_server.js

- Fix token request for Custom OAuth services;
- Fix `response.text()` being used as a backup to `response.json()`.
Introduced in #28828
`response.text()` can't be used as a backup to `response.json()` in a try/catch statement since the response's body can't be used twice -- that generates another error. The correct thing to do would be to clone the response before getting its json content OR checking if it's ok before retrieving it (that's the approach I chose).

regression:  "Bad Request" error on custom OAuth token request

---

apps/meteor/app/theme/client/imports/general/reset.css

- reset `<a/>` default color to `font-info` token
e.g.:
to:

fix: reset link color

---

apps/meteor/client/views/home/cards/CustomContentCard.tsx

chore: `Tag` wrong size in home page

---

apps/meteor/app/irc/server/irc-bridge/index.js
apps/meteor/app/smarsh-connector/server/functions/generateEml.js

regression: Model `upsert` doesn't exist anymore

---

apps/meteor/server/models/raw/Messages.ts

chore(ignore): just something for sing.li

---

apps/meteor/client/views/room/hooks/useOpenRoom.ts

Redirect Meteor.Error to RoomNotFoundError to show the correct page
Before:
After:
Steps to reproduce:
- Have two users
- Create a private team/channel with user A
- Copy the link from the channel
- Send the private room link to user B
- Log-in with user B
- Try to access the private room
Expected Behavior:
It should show the message 
“Room not found
The room does not exist or you may not have access permission”
[TC-641]
[TC-641]: https://rocketchat.atlassian.net/browse/TC-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: redirect not authorized and room not found errors

---

apps/meteor/client/views/admin/settings/groups/LDAPGroupPage.tsx

- Fix page reload when submitting text on the "LDAP User Search" modal.
Introduced in #27778
Go to **Workspace > Settings > LDAP** and press the **"Test LDAP Search"** button at the top of the screen. Insert some text and submit it. The page should not be reloaded after that.
TC-674

regression: submitting text in the LDAP User Search modal reloads the page

---

apps/meteor/.meteor/packages
apps/meteor/.meteor/versions

chore: remove reactive-store package

---

.github/workflows/ci.yml

ci: only trigger repo_dispatch on release event

---

packages/ui-video-conf/src/VideoConfPopup/VideoConfPopupInfo.tsx

Jira issue: [VC-98]
[VC-98]: https://rocketchat.atlassian.net/browse/VC-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Videoconf Avatar Popup

---

apps/meteor/client/lib/utils/applyCustomTranslations.ts
apps/meteor/ee/client/apps/i18n.js

regression: Change the apps translation namespace to `core`

---

.github/workflows/ci.yml

Copying #29178 to release-6.2.0

ci: trigger repository_dispatch event on release

---

apps/meteor/client/views/account/tokens/AccountTokensTable/AddToken.tsx

[DSAR-61](https://rocketchat.atlassian.net/browse/DSAR-61)
[DSAR-61]: https://rocketchat.atlassian.net/browse/DSAR-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: replace `useForm` in favor of `RHF` on `AddToken`

---

packages/livechat/src/lib/triggers.js

fix(livechat): trigger not evaluating correct url

---

yarn.lock

chore: Bump fuselage packages

---

apps/meteor/app/file-upload/server/lib/FileUpload.ts
apps/meteor/tests/end-to-end/api/09-rooms.js

[TC-649](https://rocketchat.atlassian.net/browse/TC-649)
[TC-649]: https://rocketchat.atlassian.net/browse/TC-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Room avatar upload not working

---

apps/meteor/server/models/raw/ModerationReports.ts

- Added back the search by-name feature
- Fixed an incorrect Mongo filter key

fix: name search not working in moderation console

---

apps/meteor/server/startup/migrations/v287.ts

fix: Migration error when removing 'snipetted' index

---

apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppDetails/AppDetails.tsx

- add optional chaining verification on `documentationUrl` to avoid crashing when undefined

regression: `AppDetails` crash when `documentationUrl` is undefined 

---

apps/meteor/app/oembed/server/jumpToMessage.ts

regression: Quote message not working for omnichannel visitors

---

apps/meteor/app/ui-utils/client/lib/MessageAction.ts
apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts
apps/meteor/client/components/message/toolbox/MessageActionMenu.tsx

regression: Reply in DM not working with hide_FlexTab

---

apps/meteor/app/apps/server/orchestrator.js

Make listener for setting `Apps_Framework_enabled` check strictly for `false` instead of a falsy value.
This will make rolling upgrades to version 6.x not disable apps in the process
AECO-205

[FIX][APPS] Fix setting listener 

---

apps/meteor/app/custom-sounds/client/lib/CustomSounds.ts
apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.tsx
packages/ui-contexts/src/CustomSoundContext.ts

This one fixes the issue when the call ringing already stopped but the `HTMLAudioElement` keeps loaded on the browser and it's possible to control it again.
While the call is ringing it's still possible to control the sound with media keys, there's no way to intercept media keys action for specific `HTMLAudioElement`. 
[VC-32]
[VC-32]: https://rocketchat.atlassian.net/browse/VC-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Media Keys controlling sounds after call ringing

---

apps/meteor/tests/data/livechat/rooms.ts
apps/meteor/tests/end-to-end/api/livechat/20-messages.ts

test: verify omni-visitors can quote messages

---

apps/meteor/client/views/account/security/TwoFactorTOTP.tsx

refactor: replace `useForm` in favor of `RHF` on `TwoFactorTOTP`

---

apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx
apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppDetails/AppDetails.tsx
apps/meteor/tests/unit/client/components/Omnichannel/modals/TranscriptModal.spec.tsx

[DSAR-49](https://rocketchat.atlassian.net/browse/DSAR-49)
[DSAR-49]: https://rocketchat.atlassian.net/browse/DSAR-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: replace `useForm` in favor of `RHF` on `TranscriptModal`

---

apps/meteor/app/file-upload/server/config/GoogleStorage.ts

fix: Google Cloud Storage not working

---

apps/meteor/ee/server/services/package.json
apps/meteor/package.json
ee/apps/ddp-streamer/package.json
packages/core-typings/package.json
packages/fuselage-ui-kit/package.json
packages/presence/package.json
packages/rest-typings/package.json
yarn.lock

Bump apps engine and vm2

---

apps/meteor/client/views/admin/invites/InvitesPage.tsx
apps/meteor/client/views/root/AppRoot.tsx

regression: fix console warnings 

---

.github/workflows/changesets.yml

ci: skip husky hooks on ci 

---

apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
packages/ui-client/src/components/EmojiPicker/EmojiPickerContainer.tsx

fix: EmojiPicker position on small views

---

apps/meteor/app/livechat/server/livechat.ts
apps/meteor/app/ui-master/server/index.js
apps/meteor/definition/externals/meteor/meteor.d.ts
apps/meteor/server/lib/dataExport/sendViaEmail.ts
apps/meteor/server/lib/getMomentLocale.ts
apps/meteor/server/routes/i18n.ts
apps/meteor/server/startup/initialData.js

chore: Use Assets’ async API

---

apps/meteor/app/notifications/client/lib/Presence.ts
apps/meteor/server/modules/notifications/notifications.module.ts
packages/api-client/__tests__/2fahandling.spec.ts
packages/api-client/src/index.ts
packages/ui-contexts/src/ServerContext/streams.ts

[regression: presence structure](https://github.com/RocketChat/Rocket.Chat/pull/29327/commits/30cbe2a54733b8f354a73eddf3253be17a50e81c)
[regression: fix response.json() being called twice](https://github.com/RocketChat/Rocket.Chat/pull/29327/commits/e9a77096afcf0c7851b9fa6ead5f090bca2c8755)

regression: fix sdk regressions

---

.github/workflows/ci-test-e2e.yml
apps/meteor/tests/end-to-end/api/livechat/06-integrations.ts
docker-compose-ci.yml

test: Fix Omnichannel Webhooks tests

---

apps/meteor/app/notifications/client/lib/Presence.ts
apps/meteor/app/notifications/server/lib/Presence.ts
apps/meteor/server/modules/notifications/notifications.module.ts

regression: Fix secondary presence streamer

---

ee/packages/ui-theming/src/palette.ts
ee/packages/ui-theming/src/paletteDark.ts

[DSAR-165](https://rocketchat.atlassian.net/browse/DSAR-165)
[DSAR-165]: https://rocketchat.atlassian.net/browse/DSAR-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add `badge-level-0` token

---

packages/uikit-playground/vite.config.ts

ci: omit vite log

---

apps/meteor/client/views/marketplace/AppsProvider.tsx

chore: small tricks with keys and invalidations with marketplace page

---

apps/meteor/client/components/LoadingIndicator.tsx
apps/meteor/client/views/room/components/body/LoadingMessagesIndicator.tsx
apps/meteor/client/views/root/PageLoading.tsx
yarn.lock

regression: Missing loading indicator

---

apps/meteor/client/views/room/Header/ToolBox/ToolBox.tsx
packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx

[DSAR-168]
[DSAR-168]: https://rocketchat.atlassian.net/browse/DSAR-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `ToolboxAction` pressed state

---

packages/ui-client/src/components/Header/ToolBox/ToolBoxAction.tsx

regression(ui-client): Toolbox action button badge in the wrong position

---

.changeset/warm-scissors-itch.md
packages/gazzodown/src/mentions/ChannelMentionElement.tsx
packages/gazzodown/src/mentions/UserMentionElement.tsx
yarn.lock

chore(meteor): Update mention style

---

apps/meteor/app/theme/client/imports/components/loading.css
apps/meteor/app/theme/client/imports/general/base.css
apps/meteor/app/theme/client/imports/general/base_old.css
apps/meteor/app/theme/client/imports/general/variables.css
apps/meteor/app/theme/client/main.css
apps/meteor/app/ui-master/server/index.js
apps/meteor/client/components/LoadingIndicator.tsx

[DSAR-171]
[DSAR-171]: https://rocketchat.atlassian.net/browse/DSAR-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Update `LoadingIndicator` colors

---

packages/ddp-client/src/MinimalDDPClient.ts

chore(ddp-client): freeze data emitted by the sdk

---

apps/meteor/client/views/composer/EmojiPicker/EmojiPicker.tsx
apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDesktopDropdown.tsx
apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDropDown.tsx

- fix position on smaller views
- add scroll when height doesn't fit the view

regression: emojiPicker position

---

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsRoute.tsx

[DSAR-199]
[DSAR-199]: https://rocketchat.atlassian.net/browse/DSAR-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `CurrentChats` empty state

---

apps/meteor/client/views/omnichannel/managers/AddManager.tsx
apps/meteor/client/views/omnichannel/managers/ManagersRoute.tsx
apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx

It also replaces `useEndpointData` in favor of `useQuery`
[DSAR-200]
[DSAR-200]: https://rocketchat.atlassian.net/browse/DSAR-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `Managers` empty state

---

apps/meteor/client/views/omnichannel/agents/AgentEdit.tsx
apps/meteor/client/views/omnichannel/agents/AgentInfo.tsx
apps/meteor/client/views/omnichannel/agents/AgentInfoActions.tsx
apps/meteor/client/views/omnichannel/agents/AgentsPage.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTab.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTable/AddAgent.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTableRow.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTable/RemoveAgentButton.tsx
apps/meteor/client/views/omnichannel/agents/AgentsTable/index.ts
apps/meteor/client/views/omnichannel/agents/hooks/useAgentsQuery.ts

It also replace `useEndpointData` in favor of `useQuery`
[DSAR-201]
[DSAR-201]: https://rocketchat.atlassian.net/browse/DSAR-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `Agents` empty state

---

.changeset/heavy-bananas-crash.md
apps/meteor/app/discussion/server/methods/createDiscussion.ts
apps/meteor/app/importer-slack/server/importer.js
apps/meteor/app/lib/server/functions/createRoom.ts
apps/meteor/app/lib/server/functions/insertMessage.ts
apps/meteor/app/lib/server/methods/createChannel.ts
apps/meteor/app/lib/server/methods/createPrivateGroup.ts
apps/meteor/ee/server/lib/ldap/Manager.ts
apps/meteor/ee/server/lib/oauth/Manager.ts
apps/meteor/server/methods/createDirectMessage.ts
apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts
apps/meteor/server/services/room/service.ts

- Fix issue with imported messages not being displayed in the room.
- Fix importer agent being added as a member of every imported room.
Ported from #29416 
Imported messages were added along with a `u._id` field, which caused them not to be displayed (messages would have a `u._id` field  and ALSO the `u`object with the `_id` and `username` fields).
TC-732

fix: Imported messages are not displayed

---

apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
apps/meteor/ee/client/omnichannel/tags/RemoveTagButton.tsx
apps/meteor/ee/client/omnichannel/tags/TagsPage.tsx
apps/meteor/ee/client/omnichannel/tags/TagsRoute.js
apps/meteor/ee/client/omnichannel/tags/TagsTable.tsx

It also refactor some files to typescript and replace `useEndpointData` in favor of `useQuery`
[DSAR-206]
[DSAR-206]: https://rocketchat.atlassian.net/browse/DSAR-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `Tags` empty state

---

.changeset/sixty-owls-shout.md
apps/meteor/server/models/raw/Users.js

fix: Seat counter including apps

---

apps/meteor/ee/client/views/audit/AuditLogPage.tsx
apps/meteor/ee/client/views/audit/components/AuditLogTable.tsx
apps/meteor/ee/client/views/audit/components/AuditResult.tsx

[DSAR-208]
[DSAR-209]
[DSAR-208]: https://rocketchat.atlassian.net/browse/DSAR-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSAR-209]: https://rocketchat.atlassian.net/browse/DSAR-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `Audit` empty state

---

apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx
apps/meteor/client/views/admin/oauthApps/OAuthAppsTable.tsx

[DSAR-160]
[DSAR-160]: https://rocketchat.atlassian.net/browse/DSAR-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: `oauthApps` empty state

---

packages/gazzodown/jest.config.ts
packages/gazzodown/package.json

test: runInBand unit test

---

apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts
apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
packages/core-typings/src/IInquiry.ts

regression: Fix typecheck issues caused by #29261

---

apps/meteor/client/components/FilterByText.tsx

regression: `FilterByText` display

---

packages/gazzodown/src/Markup.spec.tsx

ci: Mock highlight for unit tests

---

.changeset/tricky-tomatoes-sit.md
apps/meteor/client/views/room/contextualBar/Threads/hooks/useThreadMainMessageQuery.ts

fix: Message sent triggering thread subscriptions multiple times

---

.changeset/flat-fireants-itch.md
apps/meteor/client/sidebar/search/SearchList.tsx
apps/meteor/tests/e2e/message-actions.spec.ts

in real life it is not such a serious problem, but it breaks omnichannel tests

fix: spotlight reacts to new rooms

---

.changeset/popular-llamas-notice.md
.changeset/wet-cherries-hunt.md
.github/workflows/new-release.yml
.github/workflows/publish-release.yml
packages/release-action/src/bumpNextVersion.ts
packages/release-action/src/fixWorkspaceVersionsBeforePublish.ts
packages/release-action/src/gitUtils.ts
packages/release-action/src/index.ts
packages/release-action/src/publishRelease.ts
packages/release-action/src/startPatchRelease.ts
packages/release-action/src/utils.ts

ci: Fixes to publish automation

---

apps/meteor/client/providers/LayoutProvider.tsx

regression: `Contextualbar` size on wider screens

---

apps/meteor/client/hooks/useDialModal.tsx
apps/meteor/client/startup/customOAuth.ts

chore: load dialpad modal lazy

---

.github/workflows/ci.yml
packages/uikit-playground/vite.config.ts

ci: uikit loglevel silent

---

apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx

[OC-1045](https://rocketchat.atlassian.net/browse/OC-1045)
[OC-1045]: https://rocketchat.atlassian.net/browse/OC-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Canned responses filter not working

---

apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx

[OC-1045](https://rocketchat.atlassian.net/browse/OC-1045)
[OC-1045]: https://rocketchat.atlassian.net/browse/OC-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: simplified canned response filter query

---

apps/meteor/app/ui-message/client/actionButtons/messageAction.ts
apps/meteor/app/ui-message/client/actionButtons/messageBox.ts
apps/meteor/app/ui-message/client/actionButtons/tabbar.ts
apps/meteor/client/providers/TranslationProvider.tsx
apps/meteor/ee/client/apps/orchestrator.ts

regression: Apps translations not working randomly 

---

apps/meteor/client/hooks/useDialModal.tsx
apps/meteor/ee/client/voip/modal/DialPad/hooks/useDialPad.tsx

[OC-1101](https://rocketchat.atlassian.net/browse/OC-1101)
[OC-1101]: https://rocketchat.atlassian.net/browse/OC-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Opening the dial pad crashes the GUI

---

docker-compose-ci.yml

ci: Add missing `context` property on compose file

---

.changeset/dull-rockets-own.md
apps/meteor/app/livechat/server/business-hour/index.ts

regression: `onLogin` hook not destructuring user prop

---

.github/workflows/ci.yml

ci: update EE license

---

package.json
turbo.json
yarn.lock

chore: bump turbo

---

packages/livechat/src/lib/triggers.js

[OC-1100](https://rocketchat.atlassian.net/browse/OC-1100)
[OC-1100]: https://rocketchat.atlassian.net/browse/OC-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: livechat url triggers only fire when using the widget

---

yarn.lock

[OC-1103](https://rocketchat.atlassian.net/browse/OC-1103)
[OC-1103]: https://rocketchat.atlassian.net/browse/OC-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: upgrading fuselage package

---

apps/meteor/server/modules/listeners/listeners.module.ts
apps/meteor/server/services/video-conference/service.ts
packages/core-services/src/Events.ts

fix: Video Conf information block not updating automatically

---

apps/meteor/server/models/raw/Users.js

chore: Improve performance of getActiveLocalUserCount

---

.changeset/popular-donkeys-laugh.md
apps/meteor/client/views/room/contextualBar/Apps/Apps.tsx
packages/fuselage-ui-kit/src/contexts/SurfaceContext.ts
packages/fuselage-ui-kit/src/contexts/kitContext.ts
packages/fuselage-ui-kit/src/surfaces/ContextualBarSurface.tsx
packages/fuselage-ui-kit/src/surfaces/FuselageContextualBarRenderer.tsx
packages/fuselage-ui-kit/src/surfaces/index.ts
packages/fuselage-ui-kit/src/utils/UiKitComponent.tsx
packages/uikit-playground/package.json
packages/uikit-playground/src/Components/Preview/Display/Surface/ContextualBarSurface.tsx
packages/uikit-playground/src/Components/Preview/Display/Surface/Surface.tsx
packages/uikit-playground/src/Components/SurfaceSelect/options.ts
yarn.lock

Introduce a separated surface renderer to contextualBar, nothing really visual, but important to separate in a better way how things are rendered for apps.
AECO-196

feat: Introduce contextualBar surface renderer for UiKit blocks

---

apps/meteor/server/startup/migrations/index.ts

- Add migration 300 created in #28783 to the index.

chore: Add missing migration to index

---

apps/meteor/app/emoji/client/helpers.ts
apps/meteor/client/components/message/toolbox/Toolbox.tsx
apps/meteor/client/contexts/EmojiPickerContext.ts
apps/meteor/client/providers/EmojiPickerProvider.tsx

chore: Most used emojis as `quickReactions`

---

apps/meteor/app/lib/client/methods/sendMessage.ts

Callback was missing room argument, which was causing this exception.

chore: console warning on sending messages

---

apps/meteor/client/components/message/toolbox/Toolbox.tsx

regression: Omit `quickReactions` based on `MessageContext`

---

apps/meteor/app/error-handler/server/lib/RocketChat.ErrorHandler.ts
apps/meteor/app/lib/server/lib/meteorFixes.js

chore: improve server error handling

---

apps/meteor/client/sidebar/header/hooks/useAccountItems.tsx

regression: Wrong addon usage on account menu itens

---

apps/meteor/client/components/GenericMenu/GenericMenu.tsx
apps/meteor/client/components/GenericMenu/GenericMenuItem.tsx

chore: `GenericMenu` logic to add gap

---

.changeset/kind-coats-worry.md
apps/meteor/client/components/Omnichannel/Tags.tsx
apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js
apps/meteor/client/views/omnichannel/directory/chats/hooks/useTagsLabels.tsx
apps/meteor/ee/app/api-enterprise/server/lib/canned-responses.js
apps/meteor/ee/app/api-enterprise/server/lib/tags.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/afterTagRemoved.ts
apps/meteor/ee/app/livechat-enterprise/server/hooks/index.ts
apps/meteor/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.ts
apps/meteor/ee/client/hooks/useTagsList.ts
apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
apps/meteor/ee/client/omnichannel/components/CannedResponse/modals/CreateCannedResponse/index.tsx
apps/meteor/ee/server/models/raw/CannedResponse.ts
apps/meteor/ee/server/models/raw/LivechatTag.ts
apps/meteor/lib/callbacks.ts
apps/meteor/tests/data/livechat/tags.ts
apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
packages/core-typings/src/IOmnichannelCannedResponse.ts
packages/model-typings/src/models/ICannedResponseModel.ts
packages/model-typings/src/models/ILivechatTagModel.ts

[OC-720](https://rocketchat.atlassian.net/browse/OC-720)
[OC-152](https://rocketchat.atlassian.net/browse/OC-152)
[SUP-47](https://rocketchat.atlassian.net/browse/SUP-47)
[OC-720]: https://rocketchat.atlassian.net/browse/OC-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Canned Response custom tags break the GUI on enterprise

---

apps/meteor/app/emoji/client/helpers.ts
apps/meteor/client/lib/constants.ts
apps/meteor/client/views/admin/cloud/CloudRoute.tsx
apps/meteor/client/views/admin/cloud/CopyStep.tsx
apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx
apps/meteor/client/views/admin/cloud/components/RegisterWorkspaceMenu.tsx
apps/meteor/client/views/admin/cloud/constants.js

chore: `CloudRoute` to typescript

---

README.md

informations is an uncountable  noun and should not be made plural. Consider changing the noun.

 docs: Updated README file

---

apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomMenu.tsx
apps/meteor/client/sidebar/header/actions/hooks/useSortMenu.tsx

regression: add missing translations on MenuV2 replace

---

apps/meteor/app/lib/README.md
apps/meteor/app/livechat/client/ui.js
apps/meteor/app/ui-utils/client/index.ts
apps/meteor/app/ui-utils/client/lib/AccountBox.ts
apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
apps/meteor/client/sidebar/header/actions/hooks/useAdministrationMenu.tsx
apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
apps/meteor/client/sidebar/header/hooks/useStatusItems.tsx
apps/meteor/client/startup/iframeCommands.ts

refactor: Remove Accountbox usage

---

yarn.lock

- update fuselage with `MenuV2` fix

regression: fix `MenuV2` behavior on touch press

---

apps/meteor/ee/app/livechat-enterprise/server/business-hour/Custom.ts

More info on [task](https://rocketchat.atlassian.net/browse/OC-1141)

regression: False live-chat status when using a dept that has already been used for other BH

---

apps/meteor/client/components/GazzodownText.tsx
packages/gazzodown/package.json
packages/gazzodown/src/MarkupInteractionContext.ts
packages/gazzodown/src/mentions/UserMentionElement.tsx
yarn.lock

chore(gazzodown): remove `ui-client` and `ui-contexts` peer deps from `gazzodown`

---

.changeset/stupid-lions-hope.md
packages/release-action/src/bumpNextVersion.ts
packages/release-action/src/gitUtils.ts
packages/release-action/src/publishRelease.ts
packages/release-action/src/startPatchRelease.ts
packages/release-action/src/utils.ts

ci: create bump changeset on publish

---

.changeset/tiny-eyes-swim.md
apps/meteor/client/views/room/components/body/LeaderBar.tsx

regression: Leader Bar chat now link

---

apps/meteor/client/sidebar/header/actions/hooks/useCreateRoomItems.tsx

[TC-828](https://rocketchat.atlassian.net/browse/TC-828)
[TC-828]: https://rocketchat.atlassian.net/browse/TC-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Duplicate `Search federated rooms` option

---

apps/meteor/client/providers/RouterProvider.tsx
apps/meteor/definition/externals/meteor/kadira-flow-router.d.ts

[TC-831](https://rocketchat.atlassian.net/browse/TC-831)
[TC-832](https://rocketchat.atlassian.net/browse/TC-832)
[TC-831]: https://rocketchat.atlassian.net/browse/TC-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

regression: Router not capturing search string parameters

---

apps/meteor/app/cloud/server/methods.ts
apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.tsx
apps/meteor/client/startup/startup.ts
apps/meteor/client/views/admin/cloud/RegisterWorkspace.tsx

chore: Deprecate `cloud:checkRegisterStatus` method

---

apps/meteor/client/sidebar/header/actions/hooks/useGroupingListItems.spec.tsx
apps/meteor/client/sidebar/header/actions/hooks/useSortModeItems.spec.tsx
apps/meteor/client/sidebar/header/actions/hooks/useViewModeItems.spec.tsx

test: Cover `sortMenu`
