- server/startup/migrations/v34.coffee
> Create migration 34

- packages/rocketchat-lib/lib/callbacks.coffee
- packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-push-notifications/server/models/Subscriptions.js
> Improve sendMessage performance by 300%

- packages/rocketchat-cors/cors.coffee
> Add tab-i18n to list of allowed URLs in CORS

- packages/rocketchat-markdown/markdown.coffee
Closes #2125
Support for block quote
```
>>>
Text
<<<
```
> Support for block quote

- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.less
- server/startup/migrations/v35.coffee
Closes #2579
Closes https://github.com/RocketChat/Rocket.Chat.Electron/issues/103
> Add button to download uploaded files

- packages/rocketchat-ui-admin/admin/admin.coffee
> Debounce calls of codemirror changed

- packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/addOutgoingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee
> Only compile scripts if scripts are enabled and filled

- packages/rocketchat-assets/server/assets.coffee
> Fix url for the logo asset

- packages/rocketchat-theme/assets/stylesheets/base.less
Added missing css properties for firefox and the standard format to fix some visual issues with dropdown boxes (select tags)
> Fix for firefox

- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee
- packages/rocketchat-ui-message/package.js
- server/publications/filteredUsers.coffee
1. Get users from room messages in reverse order to suggest last active users first, limit 5
2. Get online users to complete the list if necessary to complete 5
3. Get usernames from room.usernames to complete the list if necessary to complete 5
4. Go to DB to get more users if necessary to complete 5
> Try to be more smart when suggesting usernames

- packages/rocketchat-github-enterprise/startup.coffee
- packages/rocketchat-gitlab/startup.coffee
- packages/rocketchat-lib/server/functions/settings.coffee
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/admin.html
- packages/rocketchat-wordpress/startup.coffee
> Bad Uri generation for Gitlab Oauth profile

- packages/rocketchat-oembed/.npm/package/.gitignore
- packages/rocketchat-oembed/.npm/package/README
- packages/rocketchat-oembed/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-oembed/package.js
- packages/rocketchat-oembed/server/server.coffee
Detect charset from meta tag, and convert to utf-8.
before:
after:
> [oembed] detect charset and convert to utf-8

- packages/rocketchat-oembed/server/providers.coffee
- packages/rocketchat-oembed/server/server.coffee
`URL.format` is not using the `urlObj.path`.
> [oembed] correct url when supply from providers

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui/views/cmsPage.coffee
- packages/rocketchat-ui/views/cmsPage.html
> Add a back button

- packages/rocketchat-reactions/client/stylesheets/reaction.less
@sampaiodiego Check the fix for RTL, I tested it on Firefox and chrome
> Added some CSS rules specefic for RTL to fix "reaction" styling.

- HISTORY.md
- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/pt.i18n.json
- packages/rocketchat-slashcommands-leave/leave.coffee
- packages/rocketchat-ui-sidenav/side-nav/chatRoomItem.coffee
- server/methods/leaveRoom.coffee
> Don't let the last owner leave the room. Warn user.

- client/routes/adminRouter.coffee
- packages/rocketchat-lib/server/functions/setEmail.js
- packages/rocketchat-lib/server/functions/setUsername.coffee
- packages/rocketchat-ui-admin/admin/users/adminUserEdit.coffee
- packages/rocketchat-ui-admin/admin/users/adminUserInfo.coffee
- packages/rocketchat-ui-admin/admin/users/adminUsers.coffee
> Fixes admin create / edit users

- packages/rocketchat-custom-oauth/custom_oauth_server.coffee
Adds a http header that oauth expects :).
> Fix Oauth for django oauth toolkit

- packages/rocketchat-oembed/client/oembedUrlWidget.coffee
- packages/rocketchat-oembed/client/oembedUrlWidget.html
> Show URL attributes after applying Handlebars.SafeString

- packages/rocketchat-markdown/settings.coffee
- packages/rocketchat-theme/assets/stylesheets/base.less
Closes #2656
- Turn preference public
- Fix style for headers
> Markdown Headers do not work

- packages/rocketchat-lib/i18n/en.i18n.json
> Add a description with warning text for Force_SSL

- packages/meteor-streams/lib/client.js
- packages/meteor-streams/lib/server.js
- packages/meteor-streams/lib/stream_permission.js
Closes #2792
Steps to reproduce:
* Create a private group
* Send some messages
* Invite someone with `/invite` command or the "add user" field on the right tab bar
* When the invited user enters the room, send new messages
* The invited user will not receive new messages
> Clear stream read permission cache on subscribe

- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-livechat/server/methods/registerGuest.js
- packages/rocketchat-ui-admin/admin/rooms/adminRooms.coffee
- packages/rocketchat-ui-admin/admin/users/adminUsers.coffee
- server/lib/accounts.coffee
- server/publications/fullUserData.coffee
- server/startup/initialData.coffee
- server/startup/migrations/v40.js
- server/startup/migrations/v41.js
> Hide livechat users and rooms from the admin pages

- packages/rocketchat-message-pin/server/settings.coffee
- server/startup/migrations/v043.js
> Add admin to default list of allowed roles on 'pin-message'

- packages/rocketchat-file-upload/server/config/configFileUploadAmazonS3.js
> Prevent server crash on wrong S3 configuration

- packages/rocketchat-theme/assets/stylesheets/base.less
> Stretch upload icon on multi line messages

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
> UI improvements to mentions popup

- packages/rocketchat-ui-login/login/form.coffee
- server/methods/registerUser.coffee
- server/methods/sendConfirmationEmail.coffee
- server/methods/sendForgotPasswordEmail.coffee
> Trim username and e-mail in login/registration form

- packages/rocketchat-livechat/app/i18n/ar.i18n.json
- packages/rocketchat-livechat/app/i18n/cs.i18n.json
- packages/rocketchat-livechat/app/i18n/el.i18n.json
- packages/rocketchat-livechat/app/i18n/fa.i18n.json
- packages/rocketchat-livechat/app/i18n/he.i18n.json
- packages/rocketchat-livechat/app/i18n/hr.i18n.json
- packages/rocketchat-livechat/app/i18n/hu.i18n.json
- packages/rocketchat-livechat/app/i18n/it.i18n.json
- packages/rocketchat-livechat/app/i18n/km.i18n.json
- packages/rocketchat-livechat/app/i18n/ko.i18n.json
- packages/rocketchat-livechat/app/i18n/ku.i18n.json
- packages/rocketchat-livechat/app/i18n/lo.i18n.json
- packages/rocketchat-livechat/app/i18n/ms-MY.i18n.json
- packages/rocketchat-livechat/app/i18n/pl.i18n.json
- packages/rocketchat-livechat/app/i18n/pt.i18n.json
- packages/rocketchat-livechat/app/i18n/sq.i18n.json
- packages/rocketchat-livechat/app/i18n/sr.i18n.json
- packages/rocketchat-livechat/app/i18n/sv.i18n.json
- packages/rocketchat-livechat/app/i18n/ta-IN.i18n.json
- packages/rocketchat-livechat/app/i18n/tr.i18n.json
- packages/rocketchat-livechat/app/i18n/uk.i18n.json
- packages/rocketchat-livechat/app/i18n/zh-TW.i18n.json
> Auto-translate livechat

- packages/rocketchat-integrations/server/api/api.coffee
> Support for GET method in @integrations

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-oembed/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-oembed/package.js
- packages/rocketchat-oembed/server/server.coffee
> Add setting to ignore hosts or CIDR addresses in Embed.

- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
> Do not notify mentions to people outside of a private group.

- packages/rocketchat-channel-settings/client/views/channelSettings.coffee
> Fix "Private Group Owner Cannot Rename Group #2807"

- packages/rocketchat-lib/i18n/fr.i18n.json
> Fix i18n fr typo

- packages/rocketchat-lib/i18n/de.i18n.json
__username__was_set__role__by__user_by_ misses an underscore at the end.
> Typo fix in variable name

- packages/rocketchat-authorization/server/methods/addUserToRole.coffee
- packages/rocketchat-authorization/server/methods/removeUserFromRole.coffee
- packages/rocketchat-authorization/server/methods/saveRole.coffee
- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-message/message/message.coffee
- packages/rocketchat-ui-message/message/message.html
- server/methods/addRoomModerator.coffee
- server/methods/addRoomOwner.coffee
- server/methods/removeRoomModerator.coffee
- server/methods/removeRoomOwner.coffee
Closes #2950
Add setting to disable displaying role tags
Setting is under Administration / Layout / User Interface
> Setting to disable displaying role tags

- server/startup/initialData.coffee
- server/startup/migrations/v046.js
> Fix admin user creation via env vars

- packages/rocketchat-oembed/server/jumpToMessage.js
> Fix permalink query in oembed

- packages/rocketchat-livechat/app/client/lib/CustomFields.js
- packages/rocketchat-livechat/app/client/lib/hooks.js
- packages/rocketchat-livechat/app/client/startup/customFields.js
- packages/rocketchat-livechat/server/models/Users.js
> Add custom fields queue to livechat

- packages/rocketchat-iframe-login/iframe_client.js
loggin-with-token changed to login-with-token
> fix iframe_client.js "loggin-with-token" typo

- packages/rocketchat-emojione/sprites.css
- packages/rocketchat-ui-message/message/renderMessageBody.js
Closes #2786
Added the ability to create larger emojis by editing sprites.css.
Changed renderMessageBody.js so that if a user's message contained only an emoji, it appears 3x as large.
-edited to to add issue number, oops
> Emoji's by themselves appear 3x as large.

- packages/rocketchat-lib/client/MessageAction.coffee
Closes #2925 
Adding copy to clipboard button to messages.
> Adding copy to clipboard button

- packages/rocketchat-ui-login/login/services.coffee
Just a spelling/grammar fix. GitLab, not Gitlab :)
> Correct GitLab service name

- packages/rocketchat-lib/client/MessageAction.coffee
Closes #164
Adds a quote button to the message cog menu. This button inserts a quote (with timestamp and @mention) in the message input box.
> Added quote button to messages.

- packages/rocketchat-katex/katex.coffee
$...$ and $$...$$ syntax are likely to collide with normal user input like a series of dollar signs ($$$).
This fix makes sure not to render messages like "$$", "$ $", "$$$", "$$   $$", etc. in order to reduce the chance to render what's meant to be regular text
> Don't render empty katex

- packages/rocketchat-integrations/server/api/api.coffee
- packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/addOutgoingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee
- packages/rocketchat-integrations/server/processWebhookMessage.js
- packages/rocketchat-integrations/server/triggers.coffee
Integrations will accept multiple channels or usernames when separated by commas
> Allow inputing multiple channels/users in integrations; comma-separated

- .eslintignore
- packages/rocketchat-cas/cas_client.js
- packages/rocketchat-livechat/app/client/lib/CustomFields.js
- packages/rocketchat-livechat/app/client/lib/hooks.js
- packages/rocketchat-livechat/app/client/startup/customFields.js
- packages/rocketchat-ui-message/message/renderMessageBody.js
> Fix some eslint errors

- packages/rocketchat-ui/lib/chatMessages.coffee
Fix for the bug described by @geekgonecrazy here:
https://github.com/RocketChat/Rocket.Chat/pull/3102
> fix: discarding draft gets up to date content of message

- packages/rocketchat-ldap/server/loginHandler.js
- packages/rocketchat-logger/server.coffee
- server/stream/streamBroadcast.coffee
Suggest changing message text to use _exist_ (rather than _exists_) in messages of the form _does not exist_.
> Fix message typo.

- .meteor/packages
- .meteor/versions
- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-slashcommands-topic/package.js
- packages/rocketchat-slashcommands-topic/topic.js
Add /topic support
If they have permission the result is:
> Add /topic command

- .meteor/packages
- .meteor/versions
- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-slashcommands-shrug/package.js
- packages/rocketchat-slashcommands-shrug/shrug.js
I found my self wanting to use the shrug command a few times, and thought about creating this.  Then discord recently added it.  So I figured why not?
Results in:
> Add /shrug command

- packages/rocketchat-emojione/emojiPicker.html
Rendering emoji category header in a loop instead of listing them one by one.
Refactoring https://github.com/RocketChat/Rocket.Chat/pull/3032
> Refactor: Rendering emoji category header in a loop

- packages/rocketchat-emojione/emojiPicker.html
- packages/rocketchat-emojione/emojiPicker.js
- packages/rocketchat-emojione/lib/EmojiPicker.js
There are still some missing features, like more keyboard shortcuts; these will come later.
I am not sure how to deal with categories when searching, so I just skipped that.
Feedback and suggestions welcome.
> Feature: search input field in emoji picker

- server/lib/cordova.coffee
> Remove invalid push tokens from gateway if status code 406

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-master/server/inject.js
> Add setting to set Google Site Verification id

- packages/rocketchat-custom-oauth/custom_oauth_server.coffee
Closes: external ref GL #20
Please eyeball the different leak cases at GL #20 to ensure coverage before merge-down.  Thanks.
> Remove stale debug logs

- packages/rocketchat-cas/cas_server.js
> Fix error message when CAS validation fail

- packages/rocketchat-message-pin/client/actionButton.coffee
- packages/rocketchat-message-star/client/actionButton.coffee
Closes #3062
Added the permalink button to the cog menu for both pinned messages & starred messages.
> Added permalink button to pinned & starred messages

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/es.i18n.json
> Remove extraneous comma in "no longer moderator, by <user>" message

- packages/rocketchat-lib/i18n/es.i18n.json
> Restore comma as Spanish speakers have corrected me

- packages/rocketchat-theme/assets/stylesheets/base.less
It feels laggy right now, this improves the perceived speed when clicking "More channels", "Add channel", etc.
> Make the sidebar movement transition faster

- client/startup/defaultRoomTypes.coffee
- packages/rocketchat-authorization/server/startup.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-lib/server/models/Subscriptions.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.coffee
- packages/rocketchat-ui-sidenav/side-nav/sideNav.html
- server/methods/channelsList.coffee
- server/methods/createDirectMessage.coffee
- server/publications/channelAutocomplete.coffee
- server/startup/roomPublishes.coffee
> Created guest user permission

- packages/rocketchat-reactions/client/init.js
- packages/rocketchat-reactions/client/methods/setReaction.js
- packages/rocketchat-reactions/setReaction.js
Closes #3226
Would like someone else to test this to verify it is working.
> Prevent someone from reacting if they are muted

- packages/rocketchat-lib/server/methods/insertOrUpdateUser.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/userEdit.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/userEdit.html
> Add role field to user creation form

- packages/rocketchat-lib/i18n/de.i18n.json
Just a little typo in german language property :octocat:
> Fix typo in `de.i18n.json`

- packages/rocketchat-lib/client/MessageAction.coffee
- packages/rocketchat-message-pin/client/actionButton.coffee
- packages/rocketchat-message-pin/client/pinMessage.coffee
- packages/rocketchat-message-pin/server/pinMessage.coffee
- packages/rocketchat-message-star/client/actionButton.coffee
- packages/rocketchat-message-star/client/starMessage.coffee
- packages/rocketchat-message-star/server/starMessage.coffee
- packages/rocketchat-reactions/client/init.js
- packages/rocketchat-reactions/client/methods/setReaction.js
- packages/rocketchat-reactions/setReaction.js
- packages/rocketchat-ui-flextab/flex-tab/tabs/messageSearch.coffee
- packages/rocketchat-ui-message/message/message.coffee
- packages/rocketchat-ui-message/message/message.html
Closes #3224
This now prevents users from doing actions on messages when they are not in a channel.
> Prevent Actions When Not in a Room

- packages/rocketchat-lib/client/MessageAction.coffee
- packages/rocketchat-message-pin/client/actionButton.coffee
- packages/rocketchat-message-star/client/actionButton.coffee
- packages/rocketchat-reactions/client/init.js
> Fix action button validation

- .gitignore
> Add *.sublime-workspace to .gitignore

- server/startup/presence.coffee
- server/stream/streamBroadcast.coffee
The goal is support horizontal scaling with multiple hosts. Currently scaling is limited to multiple processes on the same host.
> Support to broadcast streams to different hosts

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.html
- packages/rocketchat-ui-message/message/message.coffee
- packages/rocketchat-ui-message/message/message.html
> Add role tags to user info in flex tab

- server/restapi/restapi.coffee
- Add `joinedRooms` API
- Add `skip` and `limit` query params for get messages
> Improve REST API

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-oembed/server/server.coffee
Fixes security issues with URLs being hit by the server for previewing
> Add safe ports settings for embed

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-livechat/app/client/views/message.coffee
- packages/rocketchat-livechat/app/i18n/en.i18n.json
- packages/rocketchat-livechat/config.js
- packages/rocketchat-livechat/package.js
- packages/rocketchat-livechat/server/forwardUnclosedLivechats.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/models/Rooms.js
If an agent still has opened live chats, when he goes offline (or become not available for live chats) all opened rooms of that agent will be forwarded to other online agents if he still offline after 60 seconds (the value of the timeout configuration)
> Forward open livechat rooms from agent when he goes offline

- packages/rocketchat-custom-oauth/custom_oauth_server.coffee
Adds basic support for EVE Onlines SSO, by making it support characterid, and charactername
> adding EVE online sso support

- packages/meteor-accounts-saml/saml_client.js
> Fix #2028 SSO redirect issue with iOS native client

- .meteor/versions
Closes #1352
This updates accounts-sandstorm to v0.4.0. This includes new methods for authentication on mobile clients.
> Update accounts-sandstorm to v0.4.0

- packages/rocketchat-spotify/lib/client/oembedSpotifyWidget.html
- packages/rocketchat-spotify/lib/client/widget.coffee
Closes #3428 
It now behaves like specified in https://github.com/RocketChat/Rocket.Chat/pull/904 .
> Fix Spotify rendering

- .meteor/packages
- packages/action-link-test/package.js
- packages/action-link-test/testActionLinks.js
- packages/action-link-test/testUpdateMessage.js
- packages/rocketchat-action-links/README.md
- packages/rocketchat-action-links/client/init.js
- packages/rocketchat-action-links/client/stylesheets/actionLinks.less
- packages/rocketchat-action-links/loadStylesheets.js
- packages/rocketchat-action-links/package.js
- packages/rocketchat-action-links/server/actionLinkHandler.js
- packages/rocketchat-action-links/server/registerActionLinkFuncts.js
- packages/rocketchat-ui-message/message/message.coffee
- packages/rocketchat-ui-message/message/message.html
> Add Action Links, custom javascript functions in messages

- packages/rocketchat-livechat/app/client/lib/_visitor.coffee
- packages/rocketchat-livechat/app/client/views/livechatWindow.html
- packages/rocketchat-livechat/app/client/views/livechatWindow.js
- packages/rocketchat-livechat/app/client/views/main.html
Closes #3012
Gives clients using the livechat app the ability to turn an incoming messages notification sound on and off.
> Livechat client app new message notification

- packages/rocketchat-videobridge/client/views/videoFlexTab.js
> Fix issue with updateTimeout using rid out of context

- README.md
> Add "How it all started"

- README.md
> Update more links to current documentation

- packages/rocketchat-videobridge/client/views/videoFlexTab.js
> Restore watermark

- packages/rocketchat-api/server/routes.coffee
The PR extends the capability of the REST API for listing all users and to delete a user
> REST api extended for listing all users, delete a user, create a private group

- packages/rocketchat-lib/i18n/de-AT.i18n.json
- packages/rocketchat-lib/i18n/de.i18n.json
Closes #3595
Changed hidden url sample text from
Beispiel: https://demo.rocket.chat/registrieren/[geheimer_schluessel] to
Beispiel: https://demo.rocket.chat/register/[geheimer_schluessel]
> Update German language files fix Issue #3595

- README.md
Closes #3637
I've found that a few links in README.md are broken. I fixed it.
> #3637: fix broken links in README

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/ja.i18n.json
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui-account/account/accountPreferences.coffee
- packages/rocketchat-ui-account/account/accountPreferences.html
- packages/rocketchat-ui/views/app/room.coffee
- packages/rocketchat-ui/views/app/room.html
- server/methods/saveUserPreferences.coffee
Hide Avatars preference for user.
> Add hide avatars setting to user preferences

- packages/rocketchat-lib/server/methods/sendMessage.coffee
WebStorm thought the file wasn't alright - so I went ahead and created the PR :)
> Fix CoffeeScript syntax

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/fr.i18n.json
- packages/rocketchat-ui-account/account/accountPreferences.coffee
- packages/rocketchat-ui-account/account/accountPreferences.html
- packages/rocketchat-ui/views/app/room.coffee
- server/methods/saveUserPreferences.coffee
Closes #3713 
I added a preference in user preferences : 
Here is a demo (when the preference above is set to `Yes`) :
> Add auto-closing right sidebar #3713

- packages/rocketchat-ui/views/app/room.coffee
> Closes #3731

- packages/rocketchat-emojione/sprites.css
After the update, the sprite image did not update at all.
This PR fix that.
> Fix emojione cache

- packages/rocketchat-livechat/app/client/lib/chatMessages.coffee
- packages/rocketchat-ui/lib/chatMessages.coffee
- packages/rocketchat-ui/lib/textarea-autogrow.js
I want to insert newline/linebreak with alt+Enter or ctrl+Enter like Slack.
> ctrl key and alt key to insert newline

- packages/rocketchat-theme/assets/stylesheets/base.less
> Fix tabbar icon positioning in Firefox

- packages/rocketchat-livechat/app/client/lib/_livechat.js
- packages/rocketchat-livechat/app/client/lib/hooks.js
- packages/rocketchat-livechat/app/client/views/livechatWindow.js
- packages/rocketchat-livechat/assets/rocket-livechat.js
Adds the ability to change the widget color by the website that is loading the livechat widget.
Docs: https://github.com/RocketChat/Rocket.Chat.Docs/pull/51
> New livechat API setTheme

- .travis.yml
- package.json
> Add eslint to travis

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/pt.i18n.json
- packages/rocketchat-livechat/config.js
- packages/rocketchat-livechat/server/api.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/lib/QueueMethods.js
- packages/rocketchat-livechat/server/models/LivechatDepartmentAgents.js
- packages/rocketchat-livechat/server/models/Users.js
- packages/rocketchat-sms/services/twilio.js
> Add option to accept livechats even if no agents online

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/fr.i18n.json
- packages/rocketchat-lib/i18n/ja.i18n.json
> revert i18n

- packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.html
- packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.js
Always show the livechat buttons for livechat managers:
> Allow livechat managers to manage a livechat session

- packages/rocketchat-livechat/client/collections/LivechatIntegration.js
- packages/rocketchat-livechat/client/views/app/livechatIntegrations.js
- packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.html
- packages/rocketchat-livechat/client/views/app/tabbar/visitorInfo.js
- packages/rocketchat-livechat/package.js
- packages/rocketchat-livechat/server/hooks/markRoomResponded.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/lib/QueueMethods.js
- packages/rocketchat-livechat/server/methods/saveIntegration.js
- packages/rocketchat-livechat/server/methods/takeInquiry.js
- packages/rocketchat-livechat/server/models/Rooms.js
- packages/rocketchat-livechat/server/publications/livechatIntegration.js
- server/methods/canAccessRoom.coffee
- Fix integration page on livechat manager
- Add `responseTime`: time until the first answer by an agent
- Add `chatDuration`: chat duration until it's closed
- Do not show the "leave" button for livechat rooms
- `canAccessRoom` method now returns all data from the room object
- Allow livechat managers to manage a livechat session
> Many livechat improvements and fixes

- packages/rocketchat-theme/assets/stylesheets/base.less
> Changed font-family to use native UI font stack

- packages/rocketchat-ui-login/package.js
Changes to the assets were not getting picked up on the login page.
> rocketchat:ui-login misses dependency to rocketchat:assets

- packages/rocketchat-oembed/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-oembed/package.js
- packages/rocketchat-oembed/server/server.coffee
> decode html entities in link metadata

- packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-oembed/.npm/package/npm-shrinkwrap.json
> Prevent selfmade notifications

- .meteor/versions
- packages/rocketchat-crowd/client/loginHelper.js
- packages/rocketchat-crowd/server/crowd.js
- packages/rocketchat-ldap/client/loginHelper.js
- packages/rocketchat-ldap/server/loginHandler.js
Could not walk LDAP handler and not fallback local password handler.
> Bugfix: Could not login when the CROWD disabled and LDAP enabled

- packages/rocketchat-ui-sidenav/package.js
- packages/rocketchat-ui-sidenav/side-nav/channels.coffee
- packages/rocketchat-ui-sidenav/side-nav/channels.html
- packages/rocketchat-ui-sidenav/side-nav/combined.html
- packages/rocketchat-ui-sidenav/side-nav/directMessages.coffee
- packages/rocketchat-ui-sidenav/side-nav/directMessages.html
- packages/rocketchat-ui-sidenav/side-nav/privateGroups.coffee
- packages/rocketchat-ui-sidenav/side-nav/privateGroups.html
- packages/rocketchat-ui-sidenav/side-nav/starredRooms.coffee
- packages/rocketchat-ui-sidenav/side-nav/starredRooms.html
- packages/rocketchat-ui-sidenav/side-nav/unreadRooms.html
- packages/rocketchat-ui-sidenav/styles/side-nav.less
- Moved "canCreate" into functions, standardized between side-nav modules.
- Added count of rooms in each section.
> Update side-nav with room counts

- packages/rocketchat-markdown/markdown.coffee
Reverts RocketChat/Rocket.Chat#3970
> Revert "Tweaked markdown regex for [text](URI) to ignore close parentheses"

- packages/rocketchat-lib/i18n/pl.i18n.json
leave: zostaw -> opuść
when you are leaving a room
> Fix translation "leave"

- packages/rocketchat-ldap/server/loginHandler.js
- packages/rocketchat-ldap/server/settings.js
- packages/rocketchat-ldap/server/sync.js
- packages/rocketchat-lib/i18n/en.i18n.json
> Ldap merge users

- packages/rocketchat-theme/assets/stylesheets/base.less
> Fix message input flex model

- packages/rocketchat-lib/i18n/en.i18n.json
- packages/rocketchat-lib/i18n/ja.i18n.json
- packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.html
> Add online count in room members list

- client/routes/router.coffee
- packages/rocketchat-authorization/client/lib/ChatPermissions.coffee
- packages/rocketchat-lib/client/lib/cachedCollection.js
- packages/rocketchat-ui/lib/RoomManager.coffee
- packages/rocketchat-ui/lib/collections.coffee
> Load and clear some cache on login

- packages/rocketchat-ui-admin/admin/admin.coffee
> Fix admin option of type select

- packages/rocketchat-lib/server/models/_Base.js
> Allow deletion of records with same id

- packages/rocketchat-importer-slack/server.coffee
- packages/rocketchat-lib/server/models/Messages.coffee
- packages/rocketchat-message-pin/server/pinMessage.coffee
- packages/rocketchat-slackbridge/slackbridge.js
- server/startup/migrations/v057.js
Closes #3993 
Make slackbridge-import import from begin to end;
Suppress message-pinned notification from import;
Fix bug in _id generation for importer;
> Fix slackbridge import

- packages/rocketchat-action-links/client/init.js
- packages/rocketchat-action-links/client/stylesheets/actionLinks.less
- packages/rocketchat-ui-message/message/message.html
- packages/rocketchat-videobridge/client/stylesheets/video.less
Few improvements to actions links:
- Adds a default style to buttons: ![image](https://cloud.githubusercontent.com/assets/8591547/17892673/e904d9e2-6918-11e6-9c5d-4c4dc61c9531.png)
- Remove &lt;meta&gt; tag from message
> Action links improvements

- packages/rocketchat-lib/server/startup/settings.coffee
- server/startup/cron.coffee
- server/startup/migrations/v058.js
> Change push gateway and stats server address

- server/stream/streamBroadcast.coffee
> Improve stream broadcast connection

- packages/rocketchat-lib/server/methods/addOAuthService.coffee
- packages/rocketchat-lib/server/methods/checkRegistrationSecretURL.coffee
- packages/rocketchat-lib/server/methods/deleteUserOwnAccount.js
- packages/rocketchat-lib/server/methods/filterATAllTag.js
- packages/rocketchat-lib/server/methods/filterBadWords.js
- packages/rocketchat-lib/server/methods/getRoomRoles.js
- packages/rocketchat-lib/server/methods/getUserRoles.js
- packages/rocketchat-lib/server/methods/insertOrUpdateUser.coffee
- packages/rocketchat-lib/server/methods/joinDefaultChannels.coffee
- packages/rocketchat-lib/server/methods/removeOAuthService.coffee
- packages/rocketchat-lib/server/methods/robotMethods.coffee
- packages/rocketchat-lib/server/methods/saveSetting.coffee
- packages/rocketchat-lib/server/methods/sendInvitationEmail.coffee
- packages/rocketchat-lib/server/methods/sendMessage.coffee
- packages/rocketchat-lib/server/methods/setAdminStatus.coffee
- packages/rocketchat-lib/server/methods/setEmail.js
- packages/rocketchat-lib/server/methods/setRealName.coffee
- packages/rocketchat-lib/server/methods/setUsername.coffee
add checks in the methods for checking if the data received in the parameters are in their correct type
> Parameter Checks 

- packages/rocketchat-authorization/server/functions/addUserRoles.coffee
- packages/rocketchat-lib/server/functions/addUserToRoom.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-slackbridge/slackbridge.js
> Slackbridge fixes

- packages/rocketchat-lib/server/startup/settings.coffee
> Disable unessary fields on push settings

- packages/rocketchat-ui-message/message/messageBox.coffee
- packages/rocketchat-ui/lib/chatMessages.coffee
> Fix resize of message box on mobile when paste and send using `return` on keyboard

- packages/rocketchat-custom-oauth/custom_oauth_server.coffee
Closes #3821
Fix general 'phid' instead of 'id' from phabricator
> Phabricator support

- packages/rocketchat-ldap/server/loginHandler.js
- packages/rocketchat-ldap/server/settings.js
- packages/rocketchat-lib/i18n/en.i18n.json
> Add setting to disable LDAP fallback to default account system

- packages/rocketchat-authorization/client/views/permissionsRole.coffee
- packages/rocketchat-authorization/client/views/permissionsRole.html
- packages/rocketchat-authorization/server/publications/usersInRole.coffee
> Add load more button to permissions manager

- packages/rocketchat-slashcommands-invite/server.coffee
> Add ability of multiple users invitation to slash command `invite`

- server/lib/cordova.coffee
- server/methods/removeUserFromRoom.coffee
Closes #3965 
Check if the user being removed is the last owner of the room
> check if the user being removed is the last owner of the room

- packages/rocketchat-lib/i18n/en.i18n.json
This is a frequently asked question - what is "keep message history"?
> Clarify keep history setting

- packages/rocketchat-lib/server/methods/setUsername.coffee
This is patch 2/2 that's part of #4229. I'll test shortly but wanted to share this with y'all immediately.
> HTML-escape username when storing in Meteor Errors

- packages/rocketchat-i18n/i18n/de.i18n.json
> Typo-fix de.i18n in No_SuchCommand

- packages/rocketchat-ui-sidenav/side-nav/sideNav.coffee
- packages/rocketchat-ui/views/app/room.coffee
> Fix drag and drop of strings

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui-message/message/popup/messagePopup.coffee
- packages/rocketchat-ui/package.js
- packages/rocketchat-ui/views/app/spotlight/spotlight.coffee
- packages/rocketchat-ui/views/app/spotlight/spotlight.html
- packages/rocketchat-ui/views/app/spotlight/spotlightTemplate.html
- packages/rocketchat-ui/views/app/spotlight/spotlightTemplate.js
Closes #3785
Copy out `improvements/more-stream` implementation to develop
> Improve spotlight to search in subscriptions

- packages/rocketchat-integrations/client/views/integrationsIncoming.html
- packages/rocketchat-integrations/client/views/integrationsOutgoing.html
- packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/addOutgoingIntegration.coffee
- packages/rocketchat-integrations/server/methods/outgoing/updateOutgoingIntegration.coffee
> Fix babel compile error on integration scripts

- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-ui/views/app/spotlight/spotlight.coffee
- server/publications/spotlight.coffee
> Include all public rooms and users on spotlight search

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/functions/saveCustomFields.js
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-login/login/form.coffee
- server/methods/registerUser.coffee
Additionally:
- Remove wrong translation for custom fields
- Move save custom field code to function
> Add option to hide a custom field from the register form

- packages/rocketchat-file/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-file/package.js
Fix for do not work GridFS for Avatar and Custom Emoji storage.
Not fix the file-uplaod issue. However, it probably have same issue on [jalik:ufs-gridfs](https://github.com/jalik/jalik-ufs-gridfs).
> Fix GridFS do not work

- packages/rocketchat-api/server/routes.coffee
- packages/rocketchat-lib/server/functions/saveUser.js
> Add an API endpoint to edit users

- .snapcraft/edge/snapcraft.yaml
- .snapcraft/stable/snapcraft.yaml
Adds imagemagick support in the snap.
> Add imagemagick to the snaps

- docker-compose.yml
> Add replica set to docker-compose

- packages/rocketchat-lib/client/lib/roomTypes.coffee
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
- packages/rocketchat-lib/server/models/Subscriptions.coffee
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui-flextab/flex-tab/tabs/userInfo.html
- packages/rocketchat-ui-message/message/messageBox.coffee
- packages/rocketchat-ui-sidenav/side-nav/chatRoomItem.coffee
- packages/rocketchat-ui-sidenav/side-nav/chatRoomItem.html
- server/methods/createDirectMessage.coffee
- server/methods/setUserActiveStatus.coffee
- server/publications/fullUserData.coffee
- server/publications/spotlight.coffee
- server/publications/userData.coffee
- server/startup/migrations/v061.js
> Set subscriptions archived when user is deactivated;

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui/lib/textarea-autogrow.js
> Limit message box height

- package.json
- tests/test.js
This is the first **acceptance test** implementation
Steps:
```
Basic usage
✓ load page (58ms)
✓ crate user (6567ms)
✓ logout (486ms)
✓ login (2090ms)
✓ open GENERAL (2250ms)
✓ send a message (655ms)
```
Start a Rocket.Chat instance at `localhost:3000` then in another shell:
```
meteor npm run chimp-test
```
> First test! `meteor npm run chimp-test`

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui-master/server/inject.js
> make the CSS for the loading animation inline to avoid blank screen

- packages/rocketchat-lib/client/lib/openRoom.coffee
> Open new direct rooms correctly

- packages/rocketchat-importer/server/startup/setImportsToInvalid.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-lib/server/models/_Base.js
> Prevent update records without query

- packages/rocketchat-theme/assets/stylesheets/rtl.less
- packages/rocketchat-ui/views/app/room.coffee
> Hotfix rtl day divider and unread bar count

- .travis.yml
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/rtl.less
> Fix rtl spotlight and prevent line break

- packages/rocketchat-integrations/server/triggers.coffee
- packages/rocketchat-lib/server/lib/bugsnag.js
- packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
- Send more errors to Bugsnag
- Prevent stop all callbacks when get error on send email
- Add more logs for outgoing webhook
> More error handling and logs

- packages/rocketchat-integrations/server/triggers.coffee
> Prevent dirty in outgoing webhook records

- packages/rocketchat-file-upload/server/config/configFileUploadFileSystem.js
> Only try to auto orient jpeg, png and bmp files

- packages/rocketchat-integrations/server/api/api.coffee
- packages/rocketchat-integrations/server/triggers.coffee
> Improve outgoing/incoming webhook logs

- packages/rocketchat-channel-settings-mail-messages/server/methods/mailMessages.coffee
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/functions/saveUser.js
- packages/rocketchat-lib/server/methods/sendInvitationEmail.coffee
- packages/rocketchat-lib/server/methods/sendSMTPTestEmail.coffee
> Display SMTP error messages instead of Internal Server Error

- client/lib/handleError.js
There is no need to use the `else` since the `if` statement returns implicitly.
> Irrelevant `else`

- packages/rocketchat-oauth2-server-config/oauth/client/oauth2-client.html
Simple typo fix, should this be updated to i18n?
> Fixing typo on Change Channel Topic

- packages/rocketchat-ui/lib/fileUpload.coffee
> Show file type on file upload error.

- server/methods/messageSearch.js
If you were to search on dates now now if would show messages based on UTC timestamps, meaning search results would show messages starting from 02:00 instead of 00:00 if you are in timezone utc+2.
> Use users' timezone when searching on dates

- packages/rocketchat-livechat/livechat.js
The popout of livechat is not working at the moment.
> Fix popout mode for livechat

- .snapcraft/stable/snapcraft.yaml
- .travis/snap.sh
> Add source-type for stable release of snap

- packages/rocketchat-emoji-custom/client/lib/emojiCustom.js
> Update custom emojis in real time

- packages/rocketchat-lib/server/functions/setUsername.coffee
- packages/rocketchat-ui-login/login/form.coffee
- server/methods/registerUser.coffee
- server/methods/sendConfirmationEmail.coffee
- server/methods/sendForgotPasswordEmail.coffee
close https://github.com/RocketChat/Rocket.Chat/issues/4412
Stop user registration and enrollment from halting if e-mail fails
> Catch mail error

- packages/rocketchat-videobridge/client/actionLink.js
- packages/rocketchat-videobridge/client/public/external_api.js
- packages/rocketchat-videobridge/client/tabBar.js
- packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js
> Fix jitsiTimeout errors

- packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee
> Fix auto complete issues with users and emoji

- packages/rocketchat-lib/client/lib/openRoom.coffee
- packages/rocketchat-ui/lib/RoomManager.coffee
Just fire these new events:
- new-message
- opened-room
> Add new global events

- .meteor/packages
- .meteor/versions
- packages/rocketchat-error-handler/package.js
- packages/rocketchat-error-handler/server/lib/RocketChat.ErrorHandler.js
- packages/rocketchat-error-handler/server/startup/settings.js
- packages/rocketchat-i18n/i18n/en.i18n.json
Logs exceptions to a given channel/private group.
> Log exceptions

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui/views/app/videoCall/videoCall.coffee
- packages/rocketchat-ui/views/app/videoCall/videoCall.html
From PR #3384
Closes #3378
I've noticed that my video was not mirrored. This uses CSS transform to flip my video on my preview + on main video if I am shown. It will not flip the video if screen is shared.
> Mhlavac flip user video

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui/views/app/videoCall/videoCall.coffee
- packages/rocketchat-ui/views/app/videoCall/videoCall.html
Closes #3378
I've noticed that my video was not mirrored. This uses CSS transform to flip my video on my preview + on main video if I am shown. It will not flip the video if screen is shared.
> Flip user video

- packages/rocketchat-integrations/server/processWebhookMessage.js
Some times this is needed especially with a lot of bot chatter
> Allow webhook to decide if message is groupable

- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.coffee
- packages/rocketchat-ui-sidenav/side-nav/createChannelFlex.coffee
- packages/rocketchat-ui-sidenav/side-nav/createCombinedFlex.coffee
- packages/rocketchat-ui-sidenav/side-nav/directMessagesFlex.coffee
- packages/rocketchat-ui-sidenav/side-nav/privateGroupsFlex.coffee
Fix exception:
```
Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
at exports.check (/var/www/rocket.chat/bundle/programs/server/packages/check.js:57:15)
at [object Object].Meteor.methods.createChannel (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:8948:5)
at [object Object].methodsMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:964:26)
at [object Object].methodMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/meteorhacks_kadira.js:2730:30)
at maybeAuditArgumentChecks (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1795:12)
at /var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:873:20
at [object …
```
> Prevent create channel with users without username

- packages/rocketchat-error-handler/server/lib/RocketChat.ErrorHandler.js
> Fix Track Error of process uncaughtException

- server/methods/getUsernameSuggestion.coffee
Fix exception:
```
TypeError: Cannot read property 'length' of undefined
at usernameIsAvaliable (/var/www/rocket.chat/bundle/programs/server/app/app.js:4441:15)
at generateSuggestion (/var/www/rocket.chat/bundle/programs/server/app/app.js:4534:7)
at [object Object].Meteor.methods.getUsernameSuggestion (/var/www/rocket.chat/bundle/programs/server/app/app.js:4551:12)
at [object Object].methodMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/meteorhacks_kadira.js:2730:30)
at [object Object].methodsMap.(anonymous function) (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:964:26)
at maybeAuditArgumentChecks (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1795:12)
at …
```
> Prevent empty username suggestion

- packages/rocketchat-lib/server/functions/sendMessage.coffee
Fix exception
```
TypeError: Cannot read property 'match' of undefined
at Object.RocketChat.sendMessage (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:2475:27)
at ErrorHandler.trackError (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_error-handler.js:93:15)
at Object.Meteor._debug (/var/www/rocket.chat/bundle/programs/server/packages/rocketchat_error-handler.js:69:9)
at Object.Meteor._debug (/var/www/rocket.chat/bundle/programs/server/packages/meteorhacks_kadira.js:3636:32)
at wrapInternalException (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1772:14)
at Session._stopSubscription (/var/www/rocket.chat/bundle/programs/server/packages/ddp-server.js:1014:24)
at Subscription.error …
```
> Allow send empty message

- packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee
> Fix list of user auto complete from server

- packages/rocketchat-lib/client/CustomTranslations.js
> Re apply translations if tap language was changed

- packages/rocketchat-importer/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-importer/package.js
- packages/rocketchat-importer/server/classes/ImporterBase.coffee
> Fix Slack Import

- packages/rocketchat-oembed/client/oembedUrlWidget.coffee
> Fix Relative path on og:image meta tag results in broken preview image

- packages/rocketchat-slackbridge/slackbridge.js
- server/methods/registerUser.coffee
> Register imported users

- packages/rocketchat-lib/client/MessageAction.coffee
> Remove colon from reply message

- packages/rocketchat-cas/cas_client.js
- packages/rocketchat-cas/cas_server.js
Closes #3981 
Resolved conflicts from #3981
> CAS: BugFix for service URL when RC running in subdir. Source: #3981

- packages/rocketchat-autolinker/package.js
- packages/rocketchat-livechat/app/package.json
> Update Autolinker to 1.2.0

- FEATURES.md
- README.md
> CAS: Updated README and FEATURES docs

- packages/rocketchat-ui-master/master/main.html
- packages/rocketchat-ui-master/server/inject.js
> Add site name to html meta title via server side inject

- .snapcraft/edge/snapcraft.yaml
- .snapcraft/stable/snapcraft.yaml
> Set babel cache directory for integrations

- README.md
minor README edit:  added Bossie link and corrected stale blackduck link
> Add InfoWorld Bossie award coverage

- .eslintrc
- packages/rocketchat-livechat/server/lib/Livechat.js
> Fix match on livechat department save

- packages/rocketchat-lib/server/functions/saveCustomFields.js
> Fix select custom field validation

- packages/rocketchat-importer-hipchat/server.coffee
- packages/rocketchat-importer-slack/server.coffee
> Fix the slack and hipchat importers on users importing.

- README.md
> Update deployment section to include snaps

- README.md
> Minor tweaks on snap as recommended installation

- packages/rocketchat-livechat/app/client/lib/_livechat.js
- packages/rocketchat-livechat/app/client/lib/_visitor.coffee
- packages/rocketchat-livechat/app/client/lib/chatMessages.coffee
- packages/rocketchat-livechat/app/client/startup/visitor.coffee
- packages/rocketchat-livechat/app/client/views/livechatWindow.js
- packages/rocketchat-livechat/package.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/methods/loginByToken.js
If a visitor comes back to the website where the livechat is installed after a long time, their session will be expired and he will not be able to use it, getting the error "Token already exists", this PR fixes that.
> Fix visitor not being able to use livechat if session expired

- .meteor/versions
- packages/rocketchat-i18n/package.js
- packages/rocketchat-importer-hipchat/package.js
- packages/rocketchat-importer-slack/package.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-smarsh-connector/package.js
I'm trying to use the rocketchat:lib in one of my project. I noticed that there is a lot of missing dependencies and some time meteor install no compatible versions of some packages due to the fact that they was not declared in package.js.
> Fix lib package

- packages/rocketchat-channel-settings/client/views/channelSettings.html
- packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.html
For helping locate some elements in testing
> added classes to spans in flextab

- packages/rocketchat-ui/lib/fireEvent.js
> allow to call custom oauth services using iframe events, refs #4685

- packages/rocketchat-slackbridge/slackbridge.js
> Propagate bot messages through slackbridge

- server/restapi/restapi.coffee
> Added room archive and unarchive api endpoints

- packages/rocketchat-livechat/server/methods/removeDepartment.js
Closes #4720
Thanks to @deep0982
> Fix Livechat Remove Department

- packages/rocketchat-ui/views/app/room.coffee
> Fix drag-and-drop on Safari

- packages/rocketchat-lib/server/lib/bugsnag.js
> Add version and RocketChat.Info to Bugsnag notifications

- lib/fileUpload.coffee
- packages/meteor-accounts-saml/saml_rocketchat.coffee
- packages/rocketchat-authorization/server/models/Permissions.coffee
- packages/rocketchat-cas/cas_rocketchat.js
- packages/rocketchat-github-enterprise/common.coffee
- packages/rocketchat-gitlab/common.coffee
- packages/rocketchat-lib/client/Notifications.coffee
- packages/rocketchat-lib/lib/callbacks.coffee
- packages/rocketchat-lib/lib/settings.coffee
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/functions/Notifications.coffee
- packages/rocketchat-lib/server/functions/sendMessage.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-lib/server/models/Settings.coffee
- packages/rocketchat-lib/server/models/Subscriptions.coffee
- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-lib/server/startup/oAuthServicesUpdate.coffee
- packages/rocketchat-lib/server/startup/statsTracker.js
- packages/rocketchat-lib/startup/defaultRoomTypes.coffee
- packages/rocketchat-livechat/server/models/Rooms.js
- packages/rocketchat-ui-sidenav/side-nav/chatRoomItem.coffee
- packages/rocketchat-wordpress/common.coffee
> Sync from expiremental

- packages/rocketchat-ui/lib/iframeCommands.js
> Add iframe command `login-with-token`

- packages/meteor-accounts-saml/saml_utils.js
Closes #4754
Assign issuer value from tag value instead of incorrect tag object
> Fixes issue #4754

- packages/rocketchat-channel-settings/server/functions/saveRoomName.coffee
- packages/rocketchat-channel-settings/server/functions/saveRoomTopic.coffee
- packages/rocketchat-channel-settings/server/functions/saveRoomType.coffee
- packages/rocketchat-channel-settings/server/methods/saveRoomSettings.coffee
- packages/rocketchat-slackbridge/slackbridge.js
- server/startup/migrations/v064.js
Re-add escape to topic message;
Add option to send or not send message on saving room settings
> Refactor room settings

- packages/rocketchat-ui/lib/iframeCommands.js
> Add iframe command 'logout'

- client/startup/startup.coffee
- packages/rocketchat-ui/lib/accountBox.coffee
> Add iframe events change-status

- tests/pageobjects/side-nav.page.js
- tests/steps/6-channel.js
@rodrigok got the name from the side-nav instead of the flex-tab
> fixed the timeout in the channel name test

- packages/rocketchat-action-links/client/init.js
- packages/rocketchat-action-links/server/actionLinkHandler.js
> Fix action link button

- packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js
Add a check if user exists before running method
> Fix jitsi:updateTimeout error

- packages/rocketchat-api/server/routes.coffee
> Add users to default channels when using REST API

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-master/server/inject.js
> Add setting to Forget user session on window close

- README.md
> Added Hyper.sh

- packages/rocketchat-ui-master/master/main.coffee
> fixes the auto focus while using ctrl commands

- packages/rocketchat-lib/server/functions/Notifications.coffee
- packages/rocketchat-lib/server/models/Subscriptions.coffee
> Fix WebRTC

- package.json
> Fix spelling of email address

- packages/rocketchat-i18n/i18n/en.i18n.json
@marceloschmidt 
resolves : https://github.com/RocketChat/Rocket.Chat/issues/4886#issuecomment-259678245
> change utf8 names validation label

- .snapcraft/edge/snapcraft.yaml
- .snapcraft/stable/snapcraft.yaml
Quick patch to make mongo listen on loop back interface only.
> Quick snap mongo command patch

- packages/rocketchat-sandstorm/package.js
- packages/rocketchat-sandstorm/server/lib.js
> [sandstorm]: monkeypatch UploadFS.Store.GetURL to return a relative URL

- packages/rocketchat-api/.npm/package/.gitignore
- packages/rocketchat-api/.npm/package/README
- packages/rocketchat-api/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-api/package.js
- packages/rocketchat-api/server/routes.coffee
- packages/rocketchat-lib/server/functions/setUserAvatar.js
> Add REST endpoint to set user's avatar

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui/views/app/room.coffee
- server/methods/loadHistory.coffee
> Add option to hide user muted/unmuted messages

- packages/rocketchat-slackbridge/slackbridge.js
> Provide the full avatar url when posting out to Slack

- packages/rocketchat-file-upload/lib/FileUpload.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-ui-message/message/messageBox.coffee
- packages/rocketchat-ui-message/message/messageBox.html
closes: #4493 
Fixed the bug where users could upload files even when file uploads were disabled
> Fixed the bug with file upload

- packages/rocketchat-lib/server/models/Messages.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-slackbridge/slackbridge.js
> Fix slackbridge out to stop re-sending messages that go out

- packages/rocketchat-ui/lib/accounts.coffee
@engelgabriel 
closes #80
What you guys think?
Or maybe use a sweet alert?
> added a verified email toast

- README.md
Nitrous.io has been discontinued hence removing from README
> Nitrous.io has been discontinued

- packages/rocketchat-file-upload/lib/FileUpload.js
It closes #2131
If max file size is set to -1 it will remove the size restriction.
@engelgabriel is this what you wanted?
> added option to remove the filesize restriction

- packages/rocketchat-livechat/server/hooks/sendToCRM.js
> Do not trigger livechat integration if room still open

- packages/rocketchat-bot-helpers/server/index.js
- request() now uses spread operator
- added methods to add/remove users from roles and rooms
> bot-helpers bugfix and new features

- packages/rocketchat-autolinker/package.js
- packages/rocketchat-livechat/app/package.json
> Update Autolinker to 1.3.2

- client/startup/startup.coffee
- packages/rocketchat-livechat/client/views/sideNav/livechat.js
Fix both errors bellow that happens when you logs out:
> Prevent errors related to user status on logout

- packages/rocketchat-cas/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-cas/package.js
- packages/rocketchat-i18n/package.js
Closes #4887 and issue raised here: 0bc84f4029539452cd14443a1f23b62098b798e5
Fixes 2 issues on Windows when starting application using `meteor` command
> Fix windows issues on startup

- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
@RocketChat/core I missed something :/
> Fix bug, flex-tab nested content had no background

- tests/pageobjects/flex-tab.page.js
- tests/pageobjects/main-content.page.js
> updated tests

- tests/pageobjects/main-content.page.js
- tests/steps/3-basic-usage.js
if the app language was not set to english it would fail some tests
> fixed issue with language

- packages/rocketchat-i18n/i18n/da.i18n.json
- packages/rocketchat-livechat/app/i18n/da.i18n.json
Pull request created by LingoHub based on branch develop
> LingoHub based on develop

- packages/rocketchat-livechat/app/client/lib/LivechatVideoCall.js
- packages/rocketchat-theme/server/server.coffee
- packages/rocketchat-ui-login/login/header.coffee
- packages/rocketchat-videobridge/client/tabBar.js
> fix sub dir

- server/restapi/restapi.coffee
> Create public or private group api

- tests/pageobjects/login.page.js
- tests/steps/3-basic-usage.js
- tests/test-data/user.js
it creates a admin user first then creates the normal user and do the tests
> fixes issues with first users in clear databases in tests

- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/functions/isDocker.js
- server/stream/streamBroadcast.coffee
> Do not change the instance IP if running in docker

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
- packages/rocketchat-livechat/app/client/lib/_livechat.js
- packages/rocketchat-livechat/app/client/lib/chatMessages.coffee
- packages/rocketchat-livechat/app/client/lib/hooks.js
- packages/rocketchat-livechat/app/client/views/register.html
- packages/rocketchat-livechat/app/client/views/register.js
- packages/rocketchat-livechat/assets/rocket-livechat.js
- packages/rocketchat-livechat/client/views/app/livechatDepartmentForm.html
- packages/rocketchat-livechat/client/views/app/livechatDepartmentForm.js
- packages/rocketchat-livechat/client/views/app/livechatDepartments.html
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/models/LivechatDepartment.js
- packages/rocketchat-livechat/server/models/LivechatDepartmentAgents.js
- server/startup/migrations/v067.js
Adds the ability to the website choose a deparment for that livechat session.
> Add ability to choose a department from the API to livechat

- packages/rocketchat-ui-sidenav/side-nav/accountBox.coffee
- packages/rocketchat-ui-sidenav/side-nav/accountBox.html
> Change custom account box items to button

- packages/rocketchat-ui-flextab/flex-tab/tabs/uploadedFilesList.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/uploadedFilesList.html
> fixed file list in cordova

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-ui-master/master/main.coffee
- packages/rocketchat-ui-master/master/main.html
- packages/rocketchat-ui-master/server/inject.js
- server/startup/migrations/v068.js
> Inject meta tag via Inject.rawHead (Fix #5075)

- packages/rocketchat-livechat/client/views/sideNav/livechatFlex.html
- packages/rocketchat-livechat/server/models/Users.js
- packages/rocketchat-livechat/server/unclosedLivechats.js
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
> No longer allow invisible agents get livechats

- packages/rocketchat-bot-helpers/server/index.js
Minor fix for code that checks if `userFields` object is empty
> Fixed code that checks for empty object

- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-theme/assets/stylesheets/utils/_mixins.import.less
- packages/rocketchat-theme/server/variables.coffee
- packages/rocketchat-ui-admin/admin/admin.html
- packages/rocketchat-ui-login/login/form.coffee
Closes #5040
This PR fix all issues from #5040
> Fix color issues

- packages/rocketchat-theme/assets/stylesheets/base.less
Compact mode:
Cozy mode:
Fixes #5115
> Fix unread messages bar overlapping

- packages/rocketchat-api/server/routes.coffee
See https://github.com/RocketChat/Rocket.Chat.Docs/pull/137
> Add support to set own avatar from URL on REST API

- packages/rocketchat-ui-message/message/messageBox.coffee
> Fix Geolocation button

- packages/rocketchat-api/server/routes.coffee
- packages/rocketchat-cas/cas_server.js
- packages/rocketchat-crowd/server/crowd.js
- packages/rocketchat-importer-csv/server.js
- packages/rocketchat-importer-hipchat-enterprise/server.js
- packages/rocketchat-importer-hipchat/server.coffee
- packages/rocketchat-importer-slack/server.coffee
- packages/rocketchat-ldap/server/sync.js
- packages/rocketchat-lib/server/functions/saveUser.js
- packages/rocketchat-lib/server/methods/setUsername.coffee
- packages/rocketchat-slackbridge/slackbridge.js
- packages/rocketchat-ui-login/username/username.coffee
- server/lib/accounts.coffee
- server/restapi/restapi.coffee
Closes #2195
Use joinDefaultChannels only in 2 internal APIs to cover all we need
> Join default channels

- packages/rocketchat-ui-admin/admin/adminFlex.coffee
- packages/rocketchat-ui-admin/admin/adminFlex.html
> Add search field in admin

- packages/rocketchat-api/package.js
- packages/rocketchat-api/server/api.coffee
- packages/rocketchat-api/server/default/info.js
- tests/steps/API.js
> Add /api/info back, it’s used by mobile apps

- packages/rocketchat-theme/assets/stylesheets/base.less
> Adjust padding for username mentions

- tests/steps/05-channel-creation.js
> fixes channel creation test failing

- packages/rocketchat-lib/server/models/Messages.coffee
- server/startup/migrations/v071.js
> Remove reactions when messages are removed, fixes #5164

- .scripts/start.js
- .travis.yml
- tests/steps/API.js
- Enable OpLog to prevent more tests failing 
Build time 17 min 50 sec
> Try use the travis build to run tests

- packages/rocketchat-theme/assets/stylesheets/base.less
> fix more unreads overlapping

- packages/rocketchat-channel-settings/client/stylesheets/channel-settings.less
- packages/rocketchat-livechat/app/client/stylesheets/loading.less
- packages/rocketchat-livechat/app/client/views/loading.html
- packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.coffee
- packages/rocketchat-mentions-flextab/client/views/stylesheets/mentionsFlexTab.less
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui-master/master/loading.html
- packages/rocketchat-ui-master/server/inject.js
> rename default loading animation

- .meteor/versions
- packages/rocketchat-api/server/v1/chat.js
- packages/rocketchat-api/server/v1/users.js
- packages/rocketchat-integrations/server/processWebhookMessage.js
- packages/rocketchat-lib/server/functions/getFullUserData.js
- server/startup/migrations/v073.js
@RocketChat/core (ignore the branch name 😆)
* `getFullUserData` now accepts a limit of -1 which will retrieve all of the users, but you only see what you have permission to.
* `processWebhookMessage` now accepts a roomId for rooms or user, that way integrations don't have to know the name of the channel.
* Fixed the `chat.postMessage` being broke for messages that contain more than channel and text...whoops!
> Several changes to allow for easier Integrations from others

- packages/rocketchat-theme/assets/stylesheets/base.less
> Fix rocket-form width

- packages/rocketchat-emoji/emojiPicker.html
Closes #5216
Remove label and change icon to search icon.
> fix emoji search icon and remove label

- packages/rocketchat-authorization/client/hasPermission.coffee
- packages/rocketchat-livechat/client/views/app/tabbar/visitorNavigation.js
- packages/rocketchat-livechat/server/lib/Livechat.js
Fix some errors when navigating from/to a livechat room to/from another with the information tab opened, like:
```
Exception in template helper: TypeError: Cannot read property 'roles' of undefined
at http://localhost:3000/packages/rocketchat_authorization.js?hash=3487f6377692a41e47a3501e0e61fd3a52bdd6b9:223:29
at Array.some (native)
at Function._.some._.any (http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:277:59)
at atLeastOne (http://localhost:3000/packages/rocketchat_authorization.js?hash=3487f6377692a41e47a3501e0e61fd3a52bdd6b9:220:12)
at hasPermission (http://localhost:3000/packages/rocketchat_authorization.js?hash=3487f6377692a41e47a3501e0e61fd3a52bdd6b9:267:10)
at Object.RocketChat.authz.hasAtLeastOnePermission …
```
> Add some variable checks

- packages/rocketchat-livechat/app/client/stylesheets/main.less
> Improve livechat widget elements spacing

- client/routes/router.js
- packages/meteor-accounts-saml/saml_server.js
> Support SAML IDP-initiated login mode

- server/startup/migrations/v071.1.js
> Add missing migration

- packages/rocketchat-custom-oauth/custom_oauth_client.js
- packages/rocketchat-custom-oauth/custom_oauth_server.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/refreshOAuthService.js
- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/admin.html
Closes #5214
Closes #5197
Closes #5222
Closes #5221
> Oauth fixes

- packages/rocketchat-livechat/app/client/views/livechatWindow.js
> Fix livechat offline form not opening

- packages/rocketchat-theme/assets/stylesheets/base.less
> fix unreads

- packages/rocketchat-emoji-emojione/emojiPicker.js
- packages/rocketchat-emoji/emojiPicker.html
- packages/rocketchat-emoji/emojiPicker.js
- packages/rocketchat-emoji/emojiPicker.less
- packages/rocketchat-emoji/lib/EmojiPicker.js
Closes #5279 and partially closes #5281
Move search field to top
Fix the position of emojipicker in the screen:
> Change emoji search field position and fix emojipicker position

- docker-compose.yml
> Update docker-compose to version 2

- client/routes/roomRoute.js
- packages/rocketchat-lib/lib/roomTypesCommon.coffee
- packages/rocketchat-livechat/client/views/sideNav/livechat.js
- packages/rocketchat-slashcommands-open/client.js
- packages/rocketchat-ui/views/app/spotlight/spotlight.coffee
> Prevent add subdir to paths mutiple times

- packages/rocketchat-lib/client/MessageAction.coffee
Closes #5322 
We were not using the plugin call when coping. Adding a call for that.
> Fixes Corcova client copy function

- client/helpers/log.js
- client/helpers/not.js
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-theme/server/variables.coffee
- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/admin.html
- server/startup/migrations/v076.js
Add a discard button on admin settings and change save button to top.
> add discard button

- packages/rocketchat-channel-settings/client/views/channelSettings.html
- packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.html
- packages/rocketchat-message-pin/client/views/pinnedMessages.html
- packages/rocketchat-message-snippet/client/tabBar/views/snippetedMessages.html
- packages/rocketchat-message-star/client/views/starredMessages.html
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui-flextab/flex-tab/tabs/messageSearch.html
- packages/rocketchat-ui-flextab/flex-tab/tabs/uploadedFilesList.html
- packages/rocketchat-ui-master/master/loading.html
- packages/rocketchat-ui-master/server/inject.js
- packages/rocketchat-ui/views/app/room.html
> fix loading colors

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/functions/setUsername.coffee
- packages/rocketchat-lib/server/startup/settings.coffee
> Sets default avatar after setting username for the first time

- packages/rocketchat-lib/server/functions/saveUser.js
> Save user gravatar on insert via admin

- packages/rocketchat-ui-admin/admin/admin.coffee
> fix save changes button

- packages/rocketchat-theme/assets/stylesheets/rtl.less
> fix rtl main-content overlay

- packages/rocketchat-lib/client/views/customFieldsForm.html
- packages/rocketchat-lib/client/views/customFieldsForm.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/functions/getFullUserData.js
- packages/rocketchat-livechat/app/client/lib/_livechat.js
- packages/rocketchat-livechat/app/client/stylesheets/main.less
- packages/rocketchat-livechat/app/client/views/livechatWindow.js
- packages/rocketchat-livechat/app/client/views/message.coffee
- packages/rocketchat-livechat/app/client/views/message.html
- packages/rocketchat-livechat/app/client/views/messages.html
- packages/rocketchat-livechat/app/client/views/messages.js
- packages/rocketchat-livechat/assets/rocket-livechat.js
- packages/rocketchat-livechat/package.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/lib/QueueMethods.js
- packages/rocketchat-livechat/server/methods/getAgentData.js
- packages/rocketchat-livechat/server/methods/getInitialData.js
- packages/rocketchat-livechat/server/methods/takeInquiry.js
- packages/rocketchat-livechat/server/models/Users.js
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-ui-account/account/accountProfile.coffee
- packages/rocketchat-ui-account/account/accountProfile.html
- packages/rocketchat-ui-login/login/form.coffee
- packages/rocketchat-ui-login/login/form.html
- server/methods/saveUserProfile.coffee
- server/publications/userData.coffee
I've moved the "custom fields" form to to it's own template. So now I'm calling it from the register page _and_ on "My Account" page, so users can fill/update the custom fields after registration.
Livechat widget is now bigger (both height and width) to display the agent informantion fixed on the header. It's also showing the agent's **name** on messages.
Now:
Before:
> Livechat new layout

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-i18n/i18n/pt.i18n.json
- packages/rocketchat-livechat/client/views/app/livechatCurrentChats.html
- packages/rocketchat-livechat/client/views/app/livechatCurrentChats.js
- packages/rocketchat-livechat/server/publications/livechatRooms.js
- Use different collection name on DDP
- Fix date filter for different date formats
> Fix livechat current chats screen

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-theme/assets/stylesheets/base.less
- packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less
- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/admin.html
> add reset setting to packageValue button and fix unread badge color

- packages/rocketchat-oauth2-server-config/oauth/client/oauth2-client.html
- packages/rocketchat-theme/assets/stylesheets/base.less
> Adds a separator between Cancel and Authorize OAuth 2 Client

- packages/rocketchat-i18n/i18n/he.i18n.json
- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-theme/client/imports/rtl.less
> fix rtl view

- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
@RocketChat/core Not sure what the best way to actually do this is, so comments and suggestion are welcome.
Closes #5273
> Allow alias, avatar, and emoji in the sendFileMessage.

- packages/rocketchat-theme/client/imports/base.less
> Fix layout embedded layout

- packages/rocketchat-lib/server/models/_BaseCache.js
- packages/rocketchat-lib/server/models/_BaseDb.js
> Cache strategy improvements

- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/getServerInfo.js
@RocketChat/core Adding this so people don't have to fall back to the rest api to get the server information.
> Add getServerInfo meteor method

- packages/rocketchat-authorization/server/startup.coffee
- server/startup/migrations/v078.js
@RocketChat/core This is open for discussion, but this allows users with the role `bot` to create direct messages, channels, and groups.
Closes #5318
> Fix bots not being able to create rooms, closes #5318

- README.md
> Add badge for Npm Dependencies

- .meteor/packages
- .meteor/versions
- package.json
- packages/rocketchat-ui/lib/codeMirror/codeMirror.js
- packages/rocketchat-ui/lib/codeMirror/codeMirrorComponent.html
- packages/rocketchat-ui/lib/codeMirror/codeMirrorComponent.js
- packages/rocketchat-ui/package.js
> Use CodeMirror from Npm

- lib/fileUpload.js
- packages/rocketchat-file-upload/lib/FileUploadBase.js
- packages/rocketchat-ui/lib/getAvatarUrlFromUsername.coffee
- server/startup/avatar.coffee
> Avatar resize

- tests/pageobjects/administration.page.js
- tests/pageobjects/main-content.page.js
- tests/steps/11-admin.js
- tests/steps/12-admin-settings.js
> [WIP] Admin settings tests

- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-ui-account/account/avatar/prompt.html
> fix avatar url input border

- packages/rocketchat-ldap/server/loginHandler.js
> Fixed spelling mistake in loginHandler.js

- packages/rocketchat-file-upload/client/lib/FileUploadAmazonS3.js
- packages/rocketchat-file-upload/client/lib/FileUploadFileSystem.js
- packages/rocketchat-file-upload/client/lib/FileUploadGridFS.js
- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/server/models/Uploads.coffee
- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-ui/lib/fileUpload.coffee
Closes #1279
This PR adds the possibility to rename and add a description to attachments
> Implemented file name and description on file upload

- packages/rocketchat-ui-login/login/form.html
- packages/rocketchat-ui-login/login/layout.html
- packages/rocketchat-ui-sidenav/side-nav/sideNav.html
Remove unnecessary space between {{ and > when calling templates.
> Fix template inconsistency

- packages/rocketchat-lib/server/models/Rooms.coffee
- server/publications/privateHistory.coffee
Typo Correction
`findByContainigUsername` to `findByContainingUsername`
> Typo correction.

- tests/pageobjects/main-content.page.js
- tests/steps/06-messaging.js
added tests to the new file upload screen
> added new file upload tests

- .travis/snap.sh
> Remove snap set -x

- client/notifications/updateAvatar.js
- packages/rocketchat-authorization/client/lib/ChatPermissions.coffee
- packages/rocketchat-authorization/server/methods/addUserToRole.coffee
- packages/rocketchat-authorization/server/methods/removeUserFromRole.coffee
- packages/rocketchat-authorization/server/methods/saveRole.coffee
- packages/rocketchat-authorization/server/publications/permissions.js
- packages/rocketchat-emoji-custom/client/notifications/deleteEmojiCustom.js
- packages/rocketchat-emoji-custom/client/notifications/updateEmojiCustom.js
- packages/rocketchat-emoji-custom/server/methods/deleteEmojiCustom.js
- packages/rocketchat-emoji-custom/server/methods/insertOrUpdateEmoji.js
- packages/rocketchat-emoji-custom/server/methods/uploadEmojiCustom.js
- packages/rocketchat-ldap/server/sync.js
- packages/rocketchat-lib/client/Notifications.coffee
- packages/rocketchat-lib/client/lib/userRoles.js
- packages/rocketchat-lib/server/functions/Notifications.coffee
- packages/rocketchat-lib/server/functions/setUserAvatar.js
- packages/rocketchat-lib/server/publications/settings.coffee
- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/adminFlex.coffee
- server/methods/addRoomModerator.coffee
- server/methods/addRoomOwner.coffee
- server/methods/removeRoomModerator.coffee
- server/methods/removeRoomOwner.coffee
- server/methods/resetAvatar.coffee
> Send notifyAll to all users and create notifyLogged to notify only logged users

- packages/rocketchat-emoji/emojiPicker.js
- packages/rocketchat-emoji/emojiPicker.less
- packages/rocketchat-emoji/keyboardFix.js
- packages/rocketchat-emoji/lib/EmojiPicker.js
- packages/rocketchat-emoji/package.js
- packages/rocketchat-ui/lib/cordova/keyboard-fix.coffee
Closes #5401 
The emoji picker was getting in the way.
Thx @karlprieb!
> Improves emoji picker handling

- packages/rocketchat-ui-message/message/messageDropdown.html
> fix message-dropdown background

- packages/rocketchat-theme/client/imports/base.less
> fix logo in admin

- packages/rocketchat-livechat/livechat.js
- Allow opening from outside the iframe (e.g.: popup)
- Sets the correct value for ALLOW-FROM rule
> Fix livechat whitedomains list

- packages/rocketchat-lib/server/models/_BaseCache.js
> Fix find with $elemMatch

- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-ui-message/message/message.coffee
- packages/rocketchat-ui/views/app/room.coffee
- packages/rocketchat-ui/views/app/room.html
> fix new-message font color

- packages/rocketchat-api/server/v1/channels.js
- packages/rocketchat-api/server/v1/groups.js
> Fix private groups not being able to be unarchived via the rest api

- packages/rocketchat-message-attachments/client/messageAttachment.html
@RocketChat/core This allows the text of attachments to be collapsed as well.
> Allow the text of attachments to be collapsed

- packages/rocketchat-theme/client/imports/base.less
> fix flex-nav z-index

- packages/rocketchat-api/server/v1/groups.js
> API group fixes

- packages/rocketchat-ui-flextab/flex-tab/tabs/userEdit.coffee
> Fix the roles not being respected on user creation

- packages/rocketchat-integrations/server/processWebhookMessage.js
- packages/rocketchat-lib/server/models/Messages.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-lib/server/models/Settings.coffee
- packages/rocketchat-lib/server/models/Uploads.coffee
- packages/rocketchat-lib/server/models/Users.coffee
- packages/rocketchat-lib/server/models/_Base.js
- packages/rocketchat-lib/server/models/_BaseCache.js
- packages/rocketchat-lib/server/models/_BaseDb.js
> Add findOneById and findOneByIds to the models

- README.md
Thanks to community members @jelhouss and Angry Cactus   RocketChat/Rocket.Chat#1921
> Add Drupal 7 and 8 plug-in information

- packages/rocketchat-lib/client/lib/openRoom.coffee
- packages/rocketchat-ui/views/app/room.coffee
> Fix #5619 Cannot set property input of undefined

- packages/rocketchat-theme/client/imports/base.less
> fix flex-tab on cordova

- packages/rocketchat-api/server/v1/integrations.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-integrations/client/views/integrationsOutgoing.html
- packages/rocketchat-integrations/server/lib/validation.coffee
- server/startup/migrations/v080.js
> Change outgoing integration to require channel

- packages/rocketchat-livechat/client/views/app/livechatAppearance.html
- packages/rocketchat-livechat/client/views/app/livechatAppearance.js
- packages/rocketchat-livechat/package.js
- packages/rocketchat-theme/client/imports/rtl.less
> Replace minicolors by jscolor on livechat

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-statistics/package.js
- packages/rocketchat-statistics/server/functions/get.coffee
- packages/rocketchat-ui-admin/admin/adminInfo.html
Closes #5558
Documentation PR: https://github.com/RocketChat/Rocket.Chat.Docs/pull/186
> Show the oplog status on admin and an error alert when necessary

- packages/rocketchat-integrations/server/processWebhookMessage.js
- packages/rocketchat-lib/server/models/_BaseCache.js
> Fix processWebhookMessage and Loki $in/$nin

- client/startup/startup.js
- packages/rocketchat-ui-login/login/form.coffee
> Do not ser userLanguage as undefined

- packages/rocketchat-file-upload/client/lib/FileUploadAmazonS3.js
- packages/rocketchat-ui/lib/fileUpload.coffee
> Fix error preventing showing error on upload to s3

- packages/rocketchat-statistics/server/functions/get.coffee
> Try to count only valid instances

- packages/rocketchat-lib/server/functions/createRoom.js
- packages/rocketchat-lib/server/methods/createPrivateGroup.coffee
- packages/rocketchat-lib/server/models/Rooms.coffee
> Improve PR #5639

- packages/rocketchat-theme/client/imports/base.less
> fix sidenav in window resize

- server/lib/accounts.coffee
> Fix joinDefaultChannels for Custom OAuth

- packages/rocketchat-lib/server/models/_BaseDb.js
> Prevent error with positional operator

- server/methods/getAvatarSuggestion.coffee
> Remove _normal and _bigger from twitter avatar url

- packages/rocketchat-ui-master/master/main.coffee
- packages/rocketchat-ui-master/master/main.html
> Use eval to execute loggedIn and loggedOut scripts

- packages/rocketchat-ui-account/account/accountProfile.coffee
- packages/rocketchat-ui-account/account/accountProfile.html
- server/methods/saveUserProfile.coffee
> Fix users being able to change their passwords when the setting disabled it

- packages/rocketchat-oembed/client/oembedUrlWidget.coffee
- packages/rocketchat-oembed/server/server.coffee
> Add support to msapplication oembed metadata

- packages/rocketchat-ui-admin/admin/rooms/adminRoomInfo.coffee
- packages/rocketchat-ui-admin/admin/rooms/adminRooms.coffee
> Fix room’s info panel at Admin Rooms

- .eslintrc
- client/startup/unread.js
- client/startup/usersObserve.js
- packages/rocketchat-channel-settings/client/startup/trackSettingsChange.js
- packages/rocketchat-emoji-custom/client/lib/emojiCustom.js
Adds RoomManager to .eslintrc globals object.
> Add RoomManager to list of globals

- packages/rocketchat-api/server/api.js
- packages/rocketchat-api/server/v1/helpers/getUserFromParams.js
- packages/rocketchat-oauth2-server-config/oauth/server/default-services.coffee
- server/startup/migrations/v081.js
@RocketChat/core This is required to lessen the amount of manual changes people have to do to get their instance Zapier ready.
> Change Zapier oAuthApp settings to enable it and update the redirectUri

- client/methods/deleteMessage.js
- packages/rocketchat-file-upload/lib/FileUploadBase.js
- packages/rocketchat-ui/lib/chatMessages.coffee
- server/methods/deleteFileMessage.js
> Fix files uploaded by other users not being able to be deleted by uses w/ permission

- packages/rocketchat-lib/server/models/_BaseCache.js
> Fix loki $ne behavior when field is of type array

- packages/rocketchat-i18n/i18n/en.i18n.json
often confused with MD in channel topics
> Clarify purpose of allow MD headers in msg setting

- package.json
- server/startup/serverRunning.coffee
> Show error and exit process when nodejs version is impatible

- packages/rocketchat-file-upload/client/lib/FileUploadFileSystem.js
- packages/rocketchat-file-upload/client/lib/FileUploadGridFS.js
> Prevent create 2 upload bars

- README.md
> Add 2017 Softpedia 100% Free Award

- packages/rocketchat-lib/server/lib/PushNotification.js
- server/lib/cordova.coffee
Closes RocketChat/Rocket.Chat.Cordova#132
> fixes RocketChat/Rocket.Chat.Cordova#132

- packages/rocketchat-message-snippet/client/tabBar/views/snippetMessage.html
- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-ui-message/message/message.html
I think this tag is not used anymore, as we use a CSS rule for that.
> Fix to remove old day voider tag

- packages/rocketchat-integrations/client/views/integrationsIncoming.coffee
> Change curl example for Incoming Integrations

- packages/rocketchat-integrations/server/api/api.coffee
> Return correct error when parsing json on api

- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-ui/views/app/room.coffee
- packages/rocketchat-ui/views/app/room.html
> show loading animation only when room is loading new messages

- packages/rocketchat-ui/lib/notification.coffee
> Enable notification reply when supported

- packages/rocketchat-internal-hubot/settings.coffee
> Internal hubot user name should be lower-case

- packages/rocketchat-authorization/server/models/Roles.coffee
> Activate cache on roles

- packages/rocketchat-livechat/client/views/sideNav/livechat.js
Making the code feel less ... generated. 
Easier to see in split view.
> Refactor livechat sidenav

- server/startup/migrations/v083.js
Closes #5780
@rodrigok I need eyes on this. I'm not up-to-date on what things changed with new cache system, so I need you to review this and let me know if you think I got it all covered.
Thanks.
> Migration for internal hubot username

- packages/rocketchat-ui-message/message/popup/messagePopup.coffee
- packages/rocketchat-ui-sidenav/side-nav/toolbar.js
> Fix toolbar search click

- packages/rocketchat-custom-oauth/custom_oauth_server.js
- packages/rocketchat-oauth2-server-config/oauth/client/oauth2-client.coffee
OAuth Custom Login would not work for Rocket.Chat OAuth App
> OAuth server fix

- packages/rocketchat-ui-admin/admin/admin.coffee
- packages/rocketchat-ui-admin/admin/admin.html
> fix lag when typing on admin inputs

- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-theme/client/imports/rtl.less
- packages/rocketchat-theme/client/imports/variables.less
- packages/rocketchat-theme/server/colors.less
- packages/rocketchat-ui-sidenav/side-nav/sideNav.html
- packages/rocketchat-ui-sidenav/side-nav/toolbar.html
> new toolbar search style

- packages/rocketchat-authorization/server/models/Base.js
> Change var to const authentication/server/models/base.js

- tests/end-to-end/ui/05-channel-creation.js
- tests/end-to-end/ui/13-permissions.js
- tests/pageobjects/main-content.page.js
- tests/pageobjects/side-nav.page.js
Start testing the direct message creation via the spotlight search and add a small fix to make the `mention-all` test more stable
> New direct message creation tests

- packages/rocketchat-file-upload/client/lib/FileUploadAmazonS3.js
- packages/rocketchat-file-upload/client/lib/fileUploadHandler.js
- packages/rocketchat-file-upload/globalFileRestrictions.js
- packages/rocketchat-file-upload/server/config/configFileUploadAmazonS3.js
- packages/rocketchat-file-upload/server/config/configFileUploadFileSystem.js
- packages/rocketchat-file-upload/server/config/configFileUploadGridFS.js
- packages/rocketchat-file-upload/server/lib/FileUpload.js
- packages/rocketchat-file-upload/server/lib/requests.js
- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
> Change var to let/const in Package file-upload

- tests/pageobjects/login.page.js
Hopefully this will stop tests from failing in the start
> Fix for tests failing on start

- packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/membersList.html
Hide the UTC info in the member list if the user is in the same timezone as the current user.
> Hide UTC offset if user is in the same timezone

- packages/rocketchat-ui-sidenav/package.js
- packages/rocketchat-ui-sidenav/side-nav/channels.coffee
- packages/rocketchat-ui-sidenav/side-nav/channels.html
- packages/rocketchat-ui-sidenav/side-nav/listChannelsFlex.html
- packages/rocketchat-ui-sidenav/side-nav/listPrivateGroupsFlex.coffee
- packages/rocketchat-ui-sidenav/side-nav/listPrivateGroupsFlex.html
- packages/rocketchat-ui-sidenav/side-nav/privateGroups.coffee
- packages/rocketchat-ui-sidenav/side-nav/privateGroups.html
Restore channel list removed on #5846
> restore channels list

- tests/chimp-config.js
- tests/end-to-end/ui/04-main-elements-render.js
- tests/end-to-end/ui/05-channel-creation.js
- tests/end-to-end/ui/06-messaging.js
- tests/end-to-end/ui/07-emoji.js
- tests/end-to-end/ui/10-user-preferences.js
- tests/end-to-end/ui/11-admin.js
- tests/end-to-end/ui/12-settings.js
- tests/end-to-end/ui/13-permissions.js
Start entering the general channel via the spotlight search and increase the timeout to 40 seconds
> Increase tests timeout and stability

- packages/rocketchat-lib/server/functions/addUserToDefaultChannels.js
> addUserToDefaultChannels let to const

- packages/rocketchat-reactions/client/init.js
- packages/rocketchat-reactions/client/methods/setReaction.js
> Convert to const in package rocketchat-reactions

- packages/rocketchat-livechat/app/client/stylesheets/utils/_variables.import.less
- packages/rocketchat-theme/server/variables.coffee
Fix merge conflicts and closes #4204
Closes #4204 
Related to #3625
> color change on online status

- packages/rocketchat-theme/client/imports/base.less
> Fix login logo size to max height 150px and remove fixed width

- packages/rocketchat-ui-sidenav/side-nav/toolbar.js
> Accept room type on spotlight

- README.md
highlight little known yet super useful feature
> Add letsencrypt support info

- packages/rocketchat-webrtc/WebRTCClass.coffee
- packages/rocketchat-webrtc/screenShare.coffee
Changes to get webrtc screen sharing working on electron app
> Changes to make screen share work on electron app

- packages/meteor-accounts-saml/package.js
- packages/meteor-accounts-saml/saml_utils.js
Npm.require() take a significant amount of build time. These aren't even being used.
> Remove xml-encryption

- packages/rocketchat-theme/client/imports/base.less
> Add social login buttons wrap

- packages/rocketchat-ui/lib/sideNav.coffee
closes https://github.com/RocketChat/Rocket.Chat/issues/3195
> Go back to last room when close admin view

- packages/rocketchat-theme/client/imports/base.less
> fix search field size

- packages/rocketchat-theme/client/imports/base.less
Closes #5879
Hide message cog on system messages when you are on compact view.
> fix message cog on compact view

- packages/rocketchat-ui-sidenav/side-nav/listChannelsFlex.html
- packages/rocketchat-ui-sidenav/side-nav/listCombinedFlex.html
- packages/rocketchat-ui-sidenav/side-nav/listPrivateGroupsFlex.html
> fix flex-nav select color on windows

- packages/rocketchat-bot-helpers/server/index.js
- packages/rocketchat-lib/server/models/_BaseCache.js
> Add query modifier $all to Loki

- packages/rocketchat-ui-message/message/messageBox.coffee
> show send button on paste

- packages/rocketchat-channel-settings/server/functions/saveRoomType.coffee
- server/startup/migrations/v085.js
> Don’t allow to change type of direct rooms. Add migration

- packages/rocketchat-lib/server/functions/createRoom.js
- packages/rocketchat-piwik/client/trackEvents.js
> Fix Piwik Channel Create Event Having Incorrect Data

- packages/rocketchat-ui-login/login/form.coffee
This maybe a possible fix for #5010. I was not able to make it happen again on local tests.
> Cordova screen state

- server/methods/sendForgotPasswordEmail.js
> Fix #5914, passing the data to the placeholder replacement.

- packages/rocketchat-ui/lib/notification.coffee
- server/startup/migrations/v086.js
- server/startup/migrations/v087.js
> Fix sound issues

- server/methods/setUserActiveStatus.js
> Fix error when activating new users

- packages/rocketchat-lib/server/startup/settings.coffee
- packages/rocketchat-theme/client/imports/base.less
- server/startup/migrations/v088.js
> fix sidenav logo position

- packages/rocketchat-message-attachments/client/messageAttachment.coffee
- packages/rocketchat-ui-flextab/flex-tab/tabs/uploadedFilesList.coffee
> Allow pass inline image (base64) on attachments

- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-theme/client/imports/rtl.less
- packages/rocketchat-ui-sidenav/side-nav/toolbar.html
- packages/rocketchat-ui-sidenav/side-nav/toolbar.js
> open sidenav on cmd + p

- packages/rocketchat-channel-settings/client/views/channelSettings.coffee
- packages/rocketchat-i18n/i18n/en.i18n.json
> change room "code" label to "Room password"

- packages/rocketchat-theme/server/server.coffee
Possible closes #5966
Fix the custom css not updating when set to empty
> Fix for the custom css issue

- packages/rocketchat-ui-message/message/popup/messagePopup.coffee
- packages/rocketchat-ui-sidenav/side-nav/toolbar.js
- packages/rocketchat-ui/views/app/mobileMessageMenu.js
Closes #5968
Reset input field when you enter in any room
> clean toolbar search input on enter

- packages/rocketchat-ui-admin/admin/admin.html
> admin: fix oAuth buttons

- .docker/develop/Dockerfile
- .docker/latest/Dockerfile
> Fix docker builds

- README.md
Add hosting partner layershift Jelastic
> Add layershift Jelastic

- packages/rocketchat-livechat/app/client/lib/CustomFields.js
- packages/rocketchat-livechat/app/client/lib/hooks.js
- packages/rocketchat-livechat/assets/rocket-livechat.js
- packages/rocketchat-livechat/server/methods/setCustomField.js
- packages/rocketchat-livechat/server/models/Rooms.js
- packages/rocketchat-livechat/server/models/Users.js
> Add option to not overwrite livechat custom fields

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-ui-account/account/accountPreferences.coffee
- packages/rocketchat-ui-account/account/accountPreferences.html
- packages/rocketchat-ui-message/message/message.coffee
- server/methods/saveUserPreferences.js
> Add user preference to hide roles

- packages/rocketchat-file-upload/package.js
- packages/rocketchat-file-upload/server/methods/getS3FileUrl.js
> added getS3FileUrl, fixed #5410

- tests/chimp-config.js
- tests/end-to-end/ui/12-settings.js
- tests/pageobjects/administration.page.js
- tests/pageobjects/flex-tab.page.js
- tests/pageobjects/login.page.js
Asked in here https://github.com/RocketChat/Rocket.Chat/issues/5949#issuecomment-278510392
Tests for the manually aprove new users setting
> Manually Aprove New Users test

- packages/rocketchat-ui/views/app/mobileMessageMenu.js
- server/methods/reportMessage.js
> Improve report abuse to pass the message id instead of message object

- README.md
> Update Layershift logo and name

- packages/rocketchat-theme/client/imports/base.less
> Fix codemiror css

- packages/rocketchat-livechat/app/client/lib/_visitor.coffee
- packages/rocketchat-livechat/app/client/lib/chatMessages.coffee
- packages/rocketchat-livechat/app/client/views/offlineForm.js
- packages/rocketchat-livechat/app/client/views/register.js
- packages/rocketchat-livechat/assets/rocket-livechat.js
This adds the ability to websites that are using the livechat widget to listen for some events.
The events added are:
- `onChatMaximized`
- `onChatMinimized`
- `onChatStarted`
- `onChatEnded`
- `onPrechatFormSubmit`
- `onOfflineFormSubmit`
I'll add a documentation page describing how to use :wink:
> Create livechat events

- packages/rocketchat-file-upload/client/lib/FileUploadGoogleStorage.js
- packages/rocketchat-file-upload/globalFileRestrictions.js
- packages/rocketchat-file-upload/server/config/configFileUploadGoogleStorage.js
@RocketChat/core  Fixes the conflict that is happening when you save the settings.
> Fix the directive conflicts for aws and google storage.

- packages/rocketchat-ui/lib/chatMessages.coffee
> Fix the edit message with enter

- .meteor/versions
- client/startup/startup.js
- package.json
- packages/rocketchat-integrations/client/views/integrationsIncoming.js
- packages/rocketchat-integrations/client/views/integrationsOutgoing.js
- packages/rocketchat-integrations/client/views/integrationsOutgoingHistory.js
- packages/rocketchat-integrations/package.js
- packages/rocketchat-markdown/markdowncode.coffee
- packages/rocketchat-markdown/package.js
> Use highlight.js from npm

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-theme/client/imports/base.less
- packages/rocketchat-ui-message/message/message.html
related to https://github.com/RocketChat/Rocket.Chat/issues/4845#issuecomment-261569284
> Add 'Unread Messages' to i18n

- packages/rocketchat-ui-account/account/accountProfile.coffee
- packages/rocketchat-ui-master/master/main.coffee
- packages/rocketchat-ui/lib/fileUpload.coffee
Closes #3136 
This PR was create in order to translate some sweetalert buttons. The changes are being applied to the "send file" modal and "update password" modal.
If you see something is being missed, let me know!
> Translate sweetalert buttons.

- .docker/latest/Dockerfile
> Remove oplog requirement for now

- packages/rocketchat-ldap/server/sync.js
> Fix incorrect isObject check on the ldap server sync

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-lib/client/OAuthProxy.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/oauth/proxy.js
- packages/rocketchat-lib/server/startup/settings.coffee
> Allows proxy OAuth requests

- server/startup/initialData.js
> Allow create user with JSON via env INITIAL_USER

- packages/rocketchat-ui-login/client/login/header.coffee
> Fix Login Logo on subdir

- packages/rocketchat-slashcommands-open/client.js
> slashcommand /open now works event if you never talked with the user

- packages/rocketchat-ui/client/views/app/videoCall/videoCall.html
Closes #5535 
I inserted a test to avoid flip the video, if it is mine and come from screen sharing
> Screen sharing doesn't flip anymore

- packages/rocketchat-videobridge/client/public/external_api.js
> Add missing braces to get the right URL

- packages/rocketchat-integrations/server/lib/triggerHandler.js
> Fix Archived Channel Outgoing Integration Not Firing

- HISTORY.md
- packages/rocketchat-message-attachments/client/messageAttachment.coffee
- packages/rocketchat-message-attachments/client/messageAttachment.html
Closes #6423 
The fix which this code was for sadly didn't work and was breaking more than it was fixing, thus removing it was the best option for a hotfix until another fix can be applied. Questions and concerns? Contact me. ;)
> Fix the image urls not loading except for uploaded files

- packages/rocketchat-authorization/client/lib/models/Roles.js
- packages/rocketchat-channel-settings-mail-messages/package.js
- packages/rocketchat-integrations/client/collections.js
- packages/rocketchat-integrations/package.js
- packages/rocketchat-lib/client/lib/cachedCollection.js
- packages/rocketchat-lib/tests/jasmine/server/unit/models/_Base.spec.coffee
- packages/rocketchat-livechat/app/client/lib/collections.coffee
- packages/rocketchat-logger/client/viewLogs.coffee
- packages/rocketchat-logger/logger.coffee
- packages/rocketchat-logger/package.js
- packages/rocketchat-mentions-flextab/client/lib/MentionedMessage.coffee
- packages/rocketchat-mentions-flextab/package.js
- packages/rocketchat-message-pin/client/lib/PinnedMessage.coffee
- packages/rocketchat-message-pin/package.js
- packages/rocketchat-message-snippet/client/lib/collections.js
- packages/rocketchat-message-snippet/package.js
- packages/rocketchat-message-star/client/lib/StarredMessage.coffee
- packages/rocketchat-message-star/package.js
- packages/rocketchat-oauth2-server-config/admin/client/collection.coffee
- packages/rocketchat-oauth2-server-config/oauth/client/oauth2-client.coffee
- packages/rocketchat-oauth2-server-config/package.js
- packages/rocketchat-ui-admin/client/admin.coffee
- packages/rocketchat-ui-admin/client/rooms/adminRooms.coffee
- packages/rocketchat-ui-admin/package.js
- server/startup/migrations/v009.js
- server/startup/migrations/v015.js
http://stackoverflow.com/questions/25756664/is-it-mongo-collection-or-meteor-collection
> Change all instances of Meteor.Collection for Mongo.Collection

- packages/rocketchat-ui-admin/client/admin.coffee
- packages/rocketchat-ui-admin/client/admin.html
> Do not show reset button for hidden settings

- .sandstorm/launcher.sh
Closes #5883
can @kentonv and/or @engelgabriel please review this? I don't know if the `launcher.sh` is really used on Sandstorm to spin up the rocket.chat
> Hide email settings on Sandstorm

- packages/rocketchat-favico/package.js
> Make favicon package easier to read.

- packages/rocketchat-importer/server/methods/getImportProgress.coffee
- packages/rocketchat-importer/server/methods/getSelectionData.coffee
- packages/rocketchat-importer/server/methods/prepareImport.js
- packages/rocketchat-importer/server/methods/restartImport.coffee
- packages/rocketchat-importer/server/methods/setupImporter.coffee
- packages/rocketchat-importer/server/methods/startImport.coffee
> Add permission check to the import methods and not just the UI

- packages/rocketchat-livechat/app/client/views/options.js
- packages/rocketchat-livechat/server/methods/closeByVisitor.js
- packages/rocketchat-livechat/server/models/Rooms.js
Closes #6416
Now visitor will ask to close only the current room.
> Fix visitor ending livechat if multiples still open

- packages/rocketchat-livechat/assets/rocket-livechat.js
> fix livechat widget on small screens

- lib/fileUpload.js
- packages/rocketchat-file-upload/server/lib/requests.js
Closes #6386
*I'm not sure if this is right*, but it stops the error on my end, and allows server to start up.  ~~My server is still just "spinning" at the blue screen though.~~
> Issue #6386: Add import { Cookies } to fileUpload.js.

- packages/rocketchat-lib/server/models/Rooms.coffee
- packages/rocketchat-livechat/permissions.js
- packages/rocketchat-livechat/server/lib/Livechat.js
- packages/rocketchat-livechat/server/methods/saveInfo.js
> Fix livechat permissions

- .eslintrc
- packages/rocketchat-file-upload/server/config/configFileUploadFileSystem.js
- server/methods/loadHistory.js
> ESLint add rule `no-void`

- packages/rocketchat-channel-settings/client/views/channelSettings.coffee
> 'allow reacting' should be a toggle option.otherwise, the style will display an error

- packages/rocketchat-ui-flextab/package.js
> Remove coffeescript package from ui-flextab

- packages/rocketchat-ui-sidenav/package.js
> Remove coffeescript package from ui-sidenav

- packages/rocketchat-custom-oauth/custom_oauth_server.js
> [FIX] can not get access_token when using custom oauth

- packages/rocketchat-ui-login/client/login/form.js
> Fix recently introduced bug: OnePassword not defined

- .snapcraft/edge/snapcraft.yaml
- .snapcraft/resources/initmongo
- .snapcraft/resources/initmongoreplset.js
- .snapcraft/resources/initreplset.js
- .snapcraft/resources/startRocketChat
- .snapcraft/resources/startmongo
- .snapcraft/stable/snapcraft.yaml
> [New] Switch Snaps to use oplog

- packages/rocketchat-api/server/v1/users.js
> [NEW] 'users.resetAvatar' rest api endpoint

- packages/rocketchat-integrations/client/views/integrationsIncoming.js
> [FIX] Incorrect curl command being generated on incoming integrations

- packages/rocketchat-markdown/markdown.coffee
> [FIX] Do not escaping markdown on message attachments

- packages/rocketchat-lib/server/models/Users.coffee
> [FIX] Make sure username exists in findByActiveUsersExcept

- packages/rocketchat-authorization/server/methods/addUserToRole.js
- packages/rocketchat-lib/server/functions/setEmail.js
- packages/rocketchat-lib/server/functions/setUsername.coffee
> [FIX] Administrators being rate limited when editing users data

- packages/rocketchat-integrations/server/api/api.js
> [NEW] Expose Livechat to Incoming Integrations and allow response

- .meteor/packages
- .meteor/versions
- packages/rocketchat-google-natural-language/.npm/package/npm-shrinkwrap.json
> [FIX] Downgrade email package to from 1.2.0 to 1.1.18

- packages/rocketchat-integrations/server/api/api.js
> [FIX] Error when returning undefined from incoming intergation’s script

- packages/rocketchat-lib/server/functions/settings.coffee
Closes #6161
I guess the one-and-a-half-liner is pretty self-explaining ;)
> Env override initial setting

- packages/rocketchat-lib/server/models/_BaseCache.js
> [FIX] Update server cache indexes on record updates

- packages/rocketchat-channel-settings/client/startup/messageTypes.js
> [FIX] Fix message types

- docker-compose.yml
in order to make preview work out of the box for everyone who is not using a proxy
> disable proxy configuration

- packages/rocketchat-ui-login/client/login/form.html
- packages/rocketchat-ui-login/client/login/form.js
Closes #6255
The bug was caused by a conflict between the value being returned by the helper function and the RocketChat.Button loading/reset calls.
This PR replaces the loading/reset usage in the *Login/Register New Account* button in favour of a reactive solution, since the value for the label was already being set based on the page state.
Also added some small refactoring in some cases where multiple *get* calls were being used.
> [FIX] Login button appending labels

- packages/rocketchat-ui-flextab/client/tabs/membersList.js
- packages/rocketchat-ui-sidenav/client/directMessages.js
Related to #3851 
Sort members list and direct messages list by real name instead of username if use real name setting enabled.
> [FIX] Sort by real name if use real name setting is enabled

- packages/rocketchat-ui-sidenav/client/toolbar.js
Closes #6766
Search for full name and username on client side, as well as server side
> [FIX] Search full name on client side

- packages/rocketchat-oembed/server/jumpToMessage.js
Closes #5832
This only fixes the issue for newly quoted messages.
> [FIX] Quoted and replied messages not retaining the original message's alias

- packages/rocketchat-google-natural-language/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-ui-admin/client/users/adminUsers.html
[NEW] useful fields in admin user list #5110
Closes #5110
> Missing useful fields in admin user list #5110

- packages/rocketchat-api/server/v1/channels.js
- packages/rocketchat-api/server/v1/groups.js
This is nicer and makes it much easier to write a shared API code base for both.
> [NEW] Make channels.info accept roomName, just like groups.info

- packages/rocketchat-theme/client/imports/base.less
> [NEW] Add a pointer cursor to message images

- packages/rocketchat-google-natural-language/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-lib/client/lib/roomTypes.js
> [FIX] Users status on main menu always offline

- packages/rocketchat-slackbridge/slackbridge.js
> [FIX] Slackbridge text replacements

- packages/rocketchat-file-upload/lib/FileUploadBase.js
- packages/rocketchat-slackbridge/slackbridge.js
> [FIX] Allow image insert from slack through slackbridge

- packages/rocketchat-ui/client/lib/fireEvent.js
> [FIX] Not showing unread count on electron app’s icon

- packages/rocketchat-google-natural-language/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-lib/server/startup/settings.js
- packages/rocketchat-lib/server/startup/settingsOnLoadSMTP.js
> [NEW] Add SMTP settings for Protocol and Pool

- server/startup/presence.js
- server/stream/streamBroadcast.js
> [FIX] Remove spaces from env PORT and INSTANCE_IP

- tests/pageobjects/side-nav.page.js
> fix the crashing tests

- tests/pageobjects/main-content.page.js
> [FIX] Fix the other tests failing due chimp update

- packages/rocketchat-integrations/client/views/integrationsIncoming.html
- packages/rocketchat-integrations/client/views/integrationsIncoming.js
- packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.js
@RocketChat/core any reason this was initially disabled on purpose?
Closes #6869
> [FIX] Updating Incoming Integration Post As Field Not Allowed

- packages/rocketchat-api/server/v1/users.js
The request pipe was moved to inside `busboy` event, preventing it to be correctly piped.
> [FIX] Fix avatar upload via users.setAvatar REST endpoint

- server/startup/migrations/v095.js
Add a migration to #7025 changes.
> [NEW] Migration to add <html> tags to email header and footer

- packages/rocketchat-lib/client/MessageAction.js
- packages/rocketchat-message-pin/client/actionButton.js
- packages/rocketchat-message-star/client/actionButton.js
- packages/rocketchat-ui-master/package.js
> [FIX] clipboard (permalink, copy, pin, star buttons)

- packages/rocketchat-postcss/plugin/minify-css.js
- tests/end-to-end/ui/06-messaging.js
- tests/end-to-end/ui/09-channel.js
This issue was introduced by #6982 because the production CSS was being built by using only one minified file. Because of this CSS from external packages were ignored.
> [FIX] Fix missing CSS files on production builds

- packages/rocketchat-channel-settings/client/views/channelSettings.js
> [FIX] edit button on firefox

- packages/rocketchat-api/server/v1/chat.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/getSingleMessage.js
- tests/end-to-end/api/05-chat.js
> [NEW] API method and REST Endpoint for getting a single message by id

- packages/rocketchat-ui/client/views/app/photoswipe.js
> [FIX] fix bug in preview image

- server/methods/getRoomNameById.js
tag:0.56.0
Hubot rocketchat adapter can only access to the news in the room id, and we expect to get room name, because the room id cannot access to the page and not easy to understand,I expect that by adding an interface to implement. [Hubot rocketchat #213](https://github.com/RocketChat/hubot-rocketchat/issues/213)
> add server methods getRoomNameById

- .meteor/packages
- .meteor/versions
- packages/rocketchat-katex/package.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-message-attachments/package.js
- packages/rocketchat-slashcommands-inviteall/package.js
- packages/rocketchat-ui/package.js
Finally removing the last coffeescript dependencies :raised_hands:
> Remove missing CoffeeScript dependencies

- packages/rocketchat-ui-message/client/message.js
> [FIX] Fix all reactions having the same username

- packages/rocketchat-api/server/v1/users.js
> Fix forbidden error on setAvatar REST endpoint

- example-build.sh
kadira has shut down.
Called it quits - https://kadira.io/ 
I'll look at cleaning up whats left like the monitoring package.
https://app.keymetrics.io is great and very similar - They have a free plan, but also quite expensive with their paid plans. (I'm on a paid plan and could not be happier)
> [FIX] Removing the kadira package install from example build script.

- server/startup/avatar.js
> Fix mobile avatars

- packages/rocketchat-oauth2-server-config/admin/client/views/oauthApps.js
> Fix the admin oauthApps view not working

- packages/rocketchat-ui/client/views/app/photoswipe.js
> [FIX] Fix error on image preview due to undefined description|title 

- packages/rocketchat-ui/client/lib/chatMessages.js
> [FIX] Fix editing others messages

- packages/rocketchat-ui-message/client/message.js
> [FIX] Fix oembed previews not being shown

- packages/rocketchat-lib/server/functions/saveUser.js
> [FIX] "requirePasswordChange" property not being saved when set to false

- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
- packages/rocketchat-importer/server/classes/ImporterBase.js
- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-slackbridge/slackbridge.js
Closes #4845
Start rendering the `File Uploaded` text on the client and stop saving in the file title
> [FIX] Use I18n on "File Uploaded"

- packages/rocketchat-ui/client/views/app/secretURL.js
Closes #6918
@rodrigok could you do a cherry pick of this commit to the release candidate?
> [FIX] Fix Secret Url

- packages/rocketchat-ui/client/views/app/photoswipe.js
> [FIX] click on image in a message

- packages/rocketchat-lib/server/models/Rooms.js
- packages/rocketchat-lib/server/models/Users.js
This would benefit CPU performancing on very large instances.
> [NEW] Force use of MongoDB for spotlight queries

- client/methods/deleteMessage.js
- packages/rocketchat-lib/client/MessageAction.js
- packages/rocketchat-lib/server/methods/deleteMessage.js
> [FIX] Fix Block Delete Message After (n) Minutes

- app.json
- packages/rocketchat-postcss/plugin/minify-css.js
> [FIX] Use regular require() for postcss plugins

- server/publications/activeUsers.js
> [FIX] Fix issue #7316 (send real names)

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-ui/client/views/404/roomNotFound.html
- packages/rocketchat-ui/client/views/404/roomNotFound.js
Closes #7226 
New error message displayed when trying to open a direct chat with yourself
> [NEW] New error message when opening a direct chat with yourself

- packages/rocketchat-ui-account/client/accountPreferences.js
- server/methods/loadLocale.js
> [FIX] Fix i18n issue with compound language name 

- packages/rocketchat-theme/client/imports/base.css
> [FIX] sweetalert alignment on mobile

- packages/rocketchat-ui-admin/client/users/adminUsers.js
Closes #7430
This bug was caused by the coffeescript conversions
> [FIX] Fix Emails in User Admin View

- packages/rocketchat-ui/client/lib/readMessages.js
Closes #6967
Closes #5989
This bar was disappearing shortly after opening a room
> [FIX] Fix Unread Bar Disappearing

- packages/rocketchat-importer-slack/server.js
- packages/rocketchat-importer/server/classes/ImporterBase.js
> [FIX] Fix file upload on Slack import

- packages/rocketchat-ui-sidenav/client/listPrivateGroupsFlex.js
Closes #7423
We were not preventing the form submit in the private channels list
> [FIX] Fix Private Channel List Submit

- packages/rocketchat-integrations/client/views/integrationsOutgoing.js
Fix a small ui bug that would not let you change the `Word Placement Anywhere` option to false on outgoing WebHooks.
Closes #7387
> [FIX] Fix Word Placement Anywhere on WebHooks

- packages/rocketchat-slashcommands-create/server.js
Use the setting UTF8_Names_Validation for validating the channel names on the /create slash command
Thanks for pointing that out @d-ushakov
Closes #7391
> [FIX] Use UTF8 setting for /create command

- packages/rocketchat-custom-sounds/admin/soundEdit.html
Fix upload custom sound also from Firefox
Closes #6200
> [FIX] custom soundEdit.html

- packages/rocketchat-lib/startup/defaultRoomTypes.js
- packages/rocketchat-ui-sidenav/client/roomList.html
- packages/rocketchat-ui-sidenav/client/roomList.js
- packages/rocketchat-ui-sidenav/client/sideNav.html
[NEW] Add identifier so the name of the list can be modified (e.g., Channels -> Rooms)
> [NEW] Add room type identifier to room list header

- packages/rocketchat-mentions/Mentions.js
Closes nothing actually, just cleans the console a bit by removing these:
> [FIX] Stop logging mentions object to console

- .meteor/versions
- packages/rocketchat-emoji-emojione/package.js
Closes #7551
The package lib was update by #7287 but is not compatible with current code.
> [FIX] Revert emojione package version upgrade

- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/lib/loginErrorMessageOverride.js
> Improve login error messages

- packages/rocketchat-api/server/v1/users.js
> [FIX] The username not being allowed to be passed into the user.setAvatar

- packages/rocketchat-theme/client/imports/base.css
> [FIX] Message box on safari

- packages/rocketchat-ui-master/client/main.js
> [FIX] Error when acessing settings before ready

- packages/rocketchat-lib/server/methods/updateMessage.js
@RocketChat/core Right now if a message has an empty attachment array and you try to update that message's text you will get an error.
Closes #7459
> [FIX] Error when updating message with an empty attachment array

- packages/rocketchat-theme/client/imports/base.css
- packages/rocketchat-ui/client/lib/chatMessages.js
- packages/rocketchat-ui/client/views/app/room.js
> [FIX] Fix messagebox growth

- packages/rocketchat-message-snippet/client/messageType.js
- packages/rocketchat-message-snippet/client/tabBar/views/snippetMessage.js
> [FIX] Wrong render of snippet’s name

- .docker/Dockerfile
- .sandstorm/sandstorm-pkgdef.capnp
- .scripts/set-version.js
- .travis/snap.sh
- package.json
- packages/rocketchat-lib/rocketchat.info
> Bump version to 0.59.0-develop

- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
- packages/rocketchat-message-attachments/client/messageAttachment.html
- packages/rocketchat-message-attachments/client/messageAttachment.js
> Only use "File Uploaded" prefix on files

- private/node_scripts/unsubscribe_csv/unsubscribe.js
> [FIX] Example usage of unsubscribe.js

- packages/meteor-autocomplete/package.js
- packages/rocketchat-markdown/package.js
> [FIX] Remove references to non-existent tests

- packages/rocketchat-theme/client/imports/base.css
- packages/rocketchat-ui/client/views/app/room.js
> [FIX] Fix flex tab not opening and getting offscreen

- packages/rocketchat-livechat/app/i18n/en.i18n.json
Closes #7808
This is a minor change to two en translations.
Bula from Fiji! 🇫🇯🌴
> [FIX] Remove redundant "do" in "Are you sure ...?" messages.

- README.md
Fixes links to the Snap explorer.
> [FIX] Update Snap links

- packages/rocketchat-i18n/i18n/nl.i18n.json
The word "account" was translated with "bank account"
The word "account" was translated with "bank account"
> [FIX] Fix Dutch translation

- packages/rocketchat-ui-message/client/message.js
- packages/rocketchat-ui/client/views/app/room.js
> [FIX] Fix new-message button showing on search

- packages/rocketchat-channel-settings-mail-messages/server/methods/mailMessages.js
Closes #6179 #5797
Closes #7245
> [FIX] Email message forward error

- server/startup/migrations/v100.js
> [FIX] Fix migration 100

- packages/rocketchat-authorization/server/startup.js
- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-ui-message/client/popup/messagePopupConfig.js
- server/publications/spotlight.js
> [NEW] block users to mention unknow users

- README.md
[NEW] For new features
_Added another way for people to use RC - a SaaS deployment service I've just got running ;)_
> Added RocketChatLauncher (SaaS)

- packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
- packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css
> [FIX] sidebar paddings

- packages/rocketchat-theme/client/imports/components/popover.css
> [FIX] popover position on mobile

- packages/rocketchat-theme/client/imports/components/messages.css
> [FIX] message actions over unread bar

- packages/rocketchat-theme/client/imports/components/popover.css
> [FIX] Makes text action menu width based on content size

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
> [FIX] hyperlink style on sidebar footer

- packages/rocketchat-livechat/client/stylesheets/livechat.less
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
> [FIX] sidebar buttons and badge paddings

- packages/rocketchat-theme/client/imports/general/base_old.css
> Hide flex-tab close button

- packages/rocketchat-markdown/parser/original/code.js
- packages/rocketchat-markdown/parser/original/markdown.js
- packages/rocketchat-ui-master/client/main.js
> [FIX] Window exception when parsing Markdown on server

- client/notifications/notification.js
- packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
> [FIX] Remove break change in Realtime API

- packages/rocketchat-livechat/client/stylesheets/livechat.less
> [FIX] Fix livechat toggle UI issue

- README.md
> [FIX] Fix google play logo on repo README

- README.md
> Update BlackDuck URL

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
- packages/rocketchat-theme/client/imports/general/variables.css
> [FIX] status and active room colors on sidebar

- packages/rocketchat-otr/client/views/otrFlexTab.html
> [FIX] OTR buttons padding

- packages/rocketchat-theme/client/imports/components/message-box.css
- packages/rocketchat-ui-flextab/client/flexTabBar.html
- packages/rocketchat-ui-flextab/client/flexTabBar.js
- packages/rocketchat-ui-message/client/messageBox.html
- packages/rocketchat-ui-message/client/messageBox.js
> [FIX] Broken embedded view layout

- packages/rocketchat-emoji/client/emojiButton.js
- packages/rocketchat-ui-message/client/messageBox.js
> [FIX] Broken emoji picker on firefox

- README.md
…rupal.org.
Signify the fact we now have a Stable and development release for drupal 7 as drupal 8.
This updates the Repository of the source to the repo that actually holds the stabel and development branches (hosted by drupal.org) and adds the fact we have stable releases for both drupal 7 and drupal 8.
> [FIX] Document README.md. Drupal repo out of date

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
> [FIX] username ellipsis on firefox

- package-lock.json
- package.json
- packages/rocketchat-livechat/app/package.json
> npm deps update

- packages/rocketchat-theme/client/imports/components/messages.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
- packages/rocketchat-theme/client/imports/forms/input.css
- packages/rocketchat-theme/client/imports/general/base_old.css
- packages/rocketchat-theme/client/imports/general/variables.css
> [FIX] Small alignment fixes

- packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-theme/client/imports/general/base_old.css
> [FIX] Add padding on messages to allow space to the action buttons

- package-lock.json
- package.json
- packages/rocketchat-livechat/app/package.json
Reverts RocketChat/Rocket.Chat#7969
> Revert "npm deps update"

- package.json
- packages/rocketchat-markdown/parser/marked/marked.js
- packages/rocketchat-markdown/parser/original/markdown.js
- packages/rocketchat-markdown/parser/original/original.js
- packages/rocketchat-markdown/tests/client.mocks.js
- packages/rocketchat-markdown/tests/client.tests.js
> [FIX] Markdown being rendered in code tags

- packages/rocketchat-theme/client/imports/general/base_old.css
> [FIX] Fix the status on the members list

- packages/rocketchat-ui-master/client/main.js
> [FIX] Chat box no longer auto-focuses when typing

- packages/rocketchat-theme/server/colors.less
- packages/rocketchat-ui/client/views/app/createChannel.html
- packages/rocketchat-ui/client/views/app/createChannel.js
- tests/chimp-config.js
- tests/pageobjects/side-nav.page.js
> [FIX] Create channel button on Firefox

- packages/rocketchat-theme/client/imports/components/message-box.css
> [FIX] Textarea on firefox

- packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
- packages/rocketchat-theme/client/imports/general/variables.css
> [FIX] search results height

- packages/rocketchat-theme/client/imports/general/base.css
Closes #8010
This just hides the scrollbar on the login page when it is not necessary.
> [FIX] Hide scrollbar on login page if not necessary

- packages/rocketchat-theme/client/imports/components/main-content.css
- packages/rocketchat-ui/client/views/app/room.html
- packages/rocketchat-ui/client/views/app/room.js
> [FIX] room icon on header

- README.md
> Adding: How to Install in WeDeploy

- README.md
Closes YunoHost-Apps/rocketchat_ynh#17
> [NEW] Add yunohost.org installation method to Readme.md

- packages/rocketchat-ui-master/package.js
- packages/rocketchat-ui-message/client/message.html
> [FIX] copy to clipboard and update clipboard.js library

- packages/rocketchat-theme/client/imports/components/message-box.css
- packages/rocketchat-ui/client/lib/textarea-autogrow.js
> [FIX] message-box autogrow

- packages/rocketchat-autotranslate/server/autotranslate.js
> [FIX] Prevent autotranslate tokens race condition

- packages/rocketchat-theme/client/imports/general/base_old.css
> [FIX] Invisible leader bar on hover

- packages/rocketchat-theme/client/imports/components/message-box.css
- packages/rocketchat-ui/client/lib/textarea-autogrow.js
> [FIX] Scroll on messagebox

- packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
- packages/rocketchat-lib/server/models/Subscriptions.js
> [FIX] Not sending email to mentioned users with unchanged preference

- packages/rocketchat-autotranslate/server/autotranslate.js
- packages/rocketchat-markdown/markdown.js
> [FIX] Settings description not showing

- packages/rocketchat-ui-message/client/messageBox.js
- packages/rocketchat-ui/client/lib/chatMessages.js
> [FIX] Text area lost text when page reloads

- packages/rocketchat-analytics/client/loadScript.js
Loading Piwik tracker script fails #8166
Closes #8166 
Added empty String check and error handling as well
> [FIX] Issue #8166 where empty analytics setting breaks to load Piwik script

- packages/rocketchat-api/server/v1/groups.js
> [FIX] Api groups.files is always returning empty

- packages/rocketchat-ui-account/client/accountFlex.js
- packages/rocketchat-ui-admin/client/adminFlex.js
- packages/rocketchat-ui-sidenav/client/roomList.js
- packages/rocketchat-ui/client/views/app/room.js
> Disable perfect scrollbar

- README.md
the how it all started link was broken.
the blog changed its domain and blog post url
closes: https://github.com/RocketChat/Rocket.Chat.Docs/issues/381
> readme-file: fix broken link

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
> [FIX] sidenav mentions on hover

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
> [FIX] make sidebar item animation fast

- packages/rocketchat-ui/client/views/app/popover.js
- packages/rocketchat-ui/client/views/app/room.js
- packages/rocketchat-ui/package.js
> [FIX] clipboard and permalink on new popover

- packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
> [FIX] RTL on reply

- packages/rocketchat-channel-settings/client/stylesheets/channel-settings.css
> [FIX] "Channel Setting" buttons alignment in RTL

- packages/rocketchat-emoji-custom/server/methods/insertOrUpdateEmoji.js
Closes #8168 
I also:
- removed unused commented code
- disabled commas from custom emojis
> [FIX] Removing pipe and commas from custom emojis (#8168)

- packages/rocketchat-theme/client/imports/general/base_old.css
- packages/rocketchat-theme/client/imports/general/rtl.css
> [FIX] Attachment icons alignment in LTR and RTL

- packages/rocketchat-theme/client/imports/components/modal/full-modal.css
> [FIX] "Cancel button" on modal in RTL in Firefox 55

- packages/rocketchat-emoji/client/emojiPicker.css
- packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
> [FIX] Emoji Picker hidden for reactions in RTL

- packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-theme/client/imports/general/rtl.css
> [FIX] Call buttons with wrong margin on RTL

- packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
- packages/rocketchat-theme/client/imports/general/base_old.css
>  [FIX] Amin menu not showing all items & File list breaking line

- packages/rocketchat-lib/server/functions/Notifications.js
> [FIX] TypeError: Cannot read property 't' of undefined

- packages/rocketchat-file-upload/ufs/AmazonS3/server.js
> [FIX] Wrong file name when upload to AWS S3

- .travis.yml
Closes https://github.com/RocketChat/Rocket.Chat/issues/8263
Closes https://github.com/RocketChat/Rocket.Chat/issues/8267
> [FIX] Execute meteor reset on TRAVIS_TAG builds

- packages/rocketchat-theme/client/imports/components/badge.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
- packages/rocketchat-ui-sidenav/client/sidebarItem.html
> [FIX] Mention unread indicator was removed

- packages/rocketchat-lib/client/MessageAction.js
- packages/rocketchat-theme/client/imports/components/popover.css
- packages/rocketchat-ui/client/views/app/room.js
> [FIX] Put delete action on another popover group

- packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
> [FIX] Email Subjects not being sent

- packages/rocketchat-lib/client/lib/cachedCollection.js
- packages/rocketchat-ui/client/views/app/room.js
- server/publications/room.js
> [FIX] After deleting the room, cache is not synchronizing

- .meteor/packages
- .meteor/release
- .meteor/versions
- packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
- packages/rocketchat-livechat/app/.meteor/packages
- packages/rocketchat-livechat/app/.meteor/release
- packages/rocketchat-livechat/app/.meteor/versions
> Update meteor to 1.5.2.2-rc.0

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
- packages/rocketchat-theme/client/imports/general/variables.css
> [NEW] Smaller accountBox

- packages/rocketchat-theme/client/imports/components/sidebar/rooms-list.css
- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
- packages/rocketchat-ui-sidenav/client/sidebarItem.html
- packages/rocketchat-ui-sidenav/client/sidebarItem.js
> [NEW] make sidebar item width 100%

- packages/rocketchat-message-snippet/client/tabBar/tabBar.js
> Add i18n Title to snippet messages

- packages/rocketchat-ui-message/client/messageBox.js
> [FIX] disabled katex tooltip on messageBox

- packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
> [FIX] Sidebar item menu position in RTL

- packages/rocketchat-ui-sidenav/client/accountBox.js
> Fix: Account menu position on RTL

- packages/rocketchat-2fa/client/accountSecurity.html
- packages/rocketchat-2fa/client/accountSecurity.js
- packages/rocketchat-2fa/server/methods/enable.js
- packages/rocketchat-i18n/i18n/en.i18n.json
> [NEW] Displays QR code for manually entering when enabling 2fa

- packages/rocketchat-i18n/i18n/en.i18n.json
- packages/rocketchat-videobridge/client/views/videoFlexTab.js
Closes #7860 
Adds a Sweet alert prompt before starting a video conference using the flex-tab button, hopefully this will reduce the amount of times that people start a video call by mistake
> [NEW] Add sweet alert to video call tab

- .meteor/versions
- packages/rocketchat-markdown/parser/original/markdown.js
- packages/rocketchat-markdown/tests/client.tests.js
> Improve markdown parser code

- packages/rocketchat-ldap/server/ldap.js
- packages/rocketchat-ldap/server/sync.js
> [FIX] LDAP memory issues when pagination is not available

- packages/rocketchat-autolinker/server/settings.js
> Enable AutoLinker back

- packages/rocketchat-ui/client/lib/RoomManager.js
> [FIX] Uncessary route reload break some routes

- packages/rocketchat-ui-account/client/accountProfile.js
> Fix: Change password not working in new UI

- server/publications/room.js
> Fix high CPU load when sending messages on large rooms (regression)

- .docker/Dockerfile
- .snapcraft/snapcraft.yaml
Had incorrect path in #8515 
Will need to be merged back to develop
> Fix artifact path

- packages/rocketchat-channel-settings/client/stylesheets/channel-settings.css
- packages/rocketchat-channel-settings/client/views/channelSettings.html
- packages/rocketchat-channel-settings/client/views/channelSettings.js
- packages/rocketchat-lib/package.js
- packages/rocketchat-lib/server/methods/getRoomJoinCode.js
- packages/rocketchat-theme/server/colors.less
- server/publications/room.js
- server/startup/roomPublishes.js
The `joinCode` field will be sent to client only when needed/requested on channel settings tab bar.
> [FIX] Do not send joinCode field to clients

- server/startup/migrations/v103.js
> [FIX] Migration 103 wrong converting primrary colors

- packages/rocketchat-ldap/server/ldap.js
Closes #ISSUE_NUMB
Closes #8462
> [FIX] LDAP login error regression at 0.59.0

- server/startup/migrations/v103.js
- server/startup/migrations/v104.js
> [FIX] Wrong colors after migration 103

- packages/rocketchat-livechat/client/views/sideNav/livechat.js
Taking a guest pool inquiry is currently broken.
> [FIX] Fix guest pool inquiry taking

- packages/rocketchat-file-upload/server/methods/sendFileMessage.js
> [FIX] encode filename in url to prevent links breaking

- packages/rocketchat-ldap/server/ldap.js
- packages/rocketchat-ldap/server/loginHandler.js
- packages/rocketchat-ldap/server/sync.js
> [FIX] LDAP not merging existent users && Wrong id link generation

- packages/rocketchat-api/server/v1/channels.js
- packages/rocketchat-api/server/v1/groups.js
> [FIX] API channel/group.members not sorting

- packages/rocketchat-theme/client/imports/components/modal/create-channel.css
- packages/rocketchat-theme/client/imports/components/modal/full-modal.css
> [FIX] Missing scroll at create channel page

- packages/rocketchat-ldap/server/ldap.js
- packages/rocketchat-ldap/server/sync.js
> [FIX] LDAP not respecting UTF8 characters & Sync Interval not working

- packages/rocketchat-theme/client/imports/general/base_old.css
> [FIX] Highlighted color height issue
