.github/workflows/ci-test-unit.yml, apps/meteor/.mocharc.client.js, apps/meteor/client/components/message/content/reactions/useToggleReactionMutation.spec.tsx, apps/meteor/jest.config.ts, codecov.yml, ee/packages/ddp-client/jest.config.ts, turbo.json
=> ci: Report Jest coverage

packages/ui-client/src/hooks/useFeaturePreviewList.ts
=> regression: Remove wrong navigation bar feature preview image

apps/meteor/client/sidebar/header/actions/Directory.tsx, apps/meteor/client/sidebar/header/actions/Home.tsx, ee/packages/ui-theming/src/sidebarPalette.ts, ee/packages/ui-theming/src/sidebarPaletteDark.ts
- adjust press color on sidebar-palette
- add pressed state on directory and home
=> chore: sidebar actions pressed state

.github/workflows/ci-code-check.yml
=> ci: cache eslint

apps/meteor/client/sidebar/Sidebar.stories.tsx, apps/meteor/client/sidebar/Sidebar.tsx, apps/meteor/client/sidebar/SidebarRegion.tsx, apps/meteor/client/sidebar/index.ts, apps/meteor/client/views/modal/ModalRegion.tsx, apps/meteor/client/views/room/Header/Header.tsx, apps/meteor/client/views/root/MainLayout/LayoutWithSidebar.tsx
=> chore: Navbar lvl1 arrangements

apps/meteor/app/authentication/server/startup/index.js, apps/meteor/app/dolphin/server/lib.ts, apps/meteor/app/e2e/server/beforeCreateRoom.ts, apps/meteor/app/integrations/server/triggers.ts, apps/meteor/app/irc/server/irc-bridge/index.js, apps/meteor/app/lib/server/functions/createRoom.ts, apps/meteor/app/lib/server/functions/removeUserFromRoom.ts, apps/meteor/app/livechat/server/startup.ts, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/client/startup/afterLogoutCleanUp/customScriptOnLogout.ts, apps/meteor/client/startup/afterLogoutCleanUp/purgeAllDrafts.ts, apps/meteor/client/startup/afterLogoutCleanUp/roomManager.ts, apps/meteor/client/startup/iframeCommands.ts, apps/meteor/lib/callbacks.spec.ts, apps/meteor/lib/callbacks.ts, apps/meteor/lib/callbacks/afterLeaveRoomCallback.ts, apps/meteor/lib/callbacks/afterLogoutCleanUpCallback.ts, apps/meteor/lib/callbacks/afterRemoveFromRoomCallback.ts, apps/meteor/lib/callbacks/beforeCreateRoomCallback.ts, apps/meteor/lib/callbacks/beforeCreateUserCallback.ts, apps/meteor/lib/callbacks/beforeLeaveRoomCallback.ts, apps/meteor/lib/callbacks/callbacksBase.ts, apps/meteor/server/methods/logoutCleanUp.ts, apps/meteor/server/methods/removeUserFromRoom.ts, apps/meteor/server/services/federation/infrastructure/rocket-chat/hooks/index.ts, apps/meteor/tests/unit/server/federation/infrastructure/rocket-chat/hooks/hooks.spec.ts
nowadays callbacks group ALL types needed for use, forcing various parts of the application to import types that will not be used
the intention is to allow each callback to have its object and its separate types.
=> chore: isolate callbacks and typings

apps/meteor/client/views/room/MessageList/hooks/useLoadSurroundingMessages.ts
=> ci: fix flaky test - Threads hide flextab

apps/meteor/client/views/room/Room/Room.tsx, apps/meteor/client/views/room/layout/RoomLayout.tsx
=> ci: fix flaky tests - mention all here 

.github/workflows/ci-test-e2e.yml
=> ci: Skip HTTPBin container on UI tests

.github/workflows/ci.yml
- allow all the parallel steps to hit `yarn build` and `node-setup` task
- no need to wait for meteor to perform unit tests
=> ci: package build step

apps/meteor/client/views/room/Room/ComposerSkeleton.tsx
=> chore: Improve Composer Skeleton

apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx
Fixed an oversight where the verification process, which checks whether the current client has the device management module, was mistakenly verifying for the engagement dashboard instead.
1. Open the DeviceManagementAdminRoute.tsx file;
2. Look at the line 17;
=> regression: Device management module verification

apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts, apps/meteor/client/startup/routes.tsx, apps/meteor/client/views/home/HomePage.tsx, apps/meteor/client/views/root/SAMLLoginRoute.tsx
- Create a new `/saml` route for logins with SAML, which redirects to the home page on succesful logins.
Introduced in #29507
TC-857
=> regression: Login with SAML not working

.changeset/twelve-grapes-obey.md
[SUP-11](https://rocketchat.atlassian.net/browse/SUP-11)
The actual fix was included on #29935
[SUP-11]: https://rocketchat.atlassian.net/browse/SUP-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: LDAP users' username missing on subscriptions to default rooms

apps/meteor/client/hooks/useExternalLink.ts, apps/meteor/client/lib/errors/InvalidUrlError.ts
=> regression: Missing `useCallback` on `useExternalLink`

apps/meteor/client/components/GenericUpsellModal/GenericUpsellModal.tsx, apps/meteor/client/components/GenericUpsellModal/hooks/useUpsellActions.ts, apps/meteor/client/views/admin/permissions/CustomRoleUpsellModal.tsx, apps/meteor/client/views/admin/permissions/PermissionsContextBar.tsx, apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.tsx, apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx, apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementAdminRoute.tsx, apps/meteor/ee/client/views/admin/engagementDashboard/EngagementDashboardRoute.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/tests/e2e/administration.spec.ts
=> chore: `GenericUpsellModal` adoption on `CustomRoleUpsellModal`

.github/actions/setup-node/action.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml, apps/meteor/.mocharc.api.js
=> ci: Isolate Docker build into steps

.github/actions/setup-node/action.yml, .github/workflows/ci.yml
=> ci: fix build

packages/ui-client/package.json, packages/ui-client/src/components/Card/Card.stories.tsx, packages/ui-client/tsconfig.json
=> chore(ui-client): Missing type checking

apps/meteor/client/views/room/Room/Room.tsx
=> regression: Revert contextual bar slot

packages/livechat/package.json, packages/livechat/src/lib/random.ts, packages/random/tsconfig.build.json, yarn.lock
=> refactor(livechat): `@rocket.chat/random` instead of `crypto-js`

apps/meteor/client/sidebar/SidebarRegion.tsx
=> regression: Sidebar missing default width

apps/meteor/client/views/admin/settings/GroupPage.tsx, apps/meteor/client/views/admin/settings/groups/GenericGroupPage.tsx, apps/meteor/client/views/admin/settings/groups/TabbedGroupPage.tsx
=> regression: Change header buttons location on `GroupPage`

apps/meteor/.meteor/versions, apps/meteor/app/theme/client/main.css, apps/meteor/client/components/Omnichannel/modals/TranscriptModal.tsx, apps/meteor/client/importPackages.ts, yarn.lock
=> chore:  split fuselage js/css  

.changeset/brown-clouds-add.md, apps/meteor/ee/app/license/server/getStatistics.ts, apps/meteor/server/models/raw/Messages.ts
=> fix: Performance issue on Messages.countByType aggregation

.changeset/curly-shoes-burn.md, apps/meteor/app/integrations/server/api/api.js, apps/meteor/app/integrations/server/lib/triggerHandler.js, apps/meteor/app/integrations/server/lib/validateOutgoingIntegration.ts, apps/meteor/app/integrations/server/methods/incoming/addIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/incoming/updateIncomingIntegration.ts, apps/meteor/app/integrations/server/methods/outgoing/addOutgoingIntegration.ts, apps/meteor/app/integrations/server/methods/outgoing/updateOutgoingIntegration.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> feat: ability to freeze or completely disable integration scripts through envvars

.changeset/chatty-parents-switch.md, apps/meteor/ee/app/license/server/getStatistics.ts, apps/meteor/server/models/raw/Messages.ts
=> fix: Performance issue on `Messages.countByType` aggregation

.github/actions/setup-node/action.yml
=> ci: use `node-setup@3.7.0`

apps/meteor/client/hooks/useAppActionButtons.ts
=> refactor(perf): Use infinite stale time on `useAppActionButtons`

ee/packages/ddp-client/.eslintrc.json
=> chore(lint): Ignore `coverage` dir on linting `@rocket.chat/ddp-client`

yarn.lock
=> chore: bump fuselage

.changeset/nine-carrots-listen.md, apps/meteor/client/hooks/useEmbeddedLayout.ts, apps/meteor/client/lib/utils/isLayoutEmbedded.ts, apps/meteor/client/providers/LayoutProvider.tsx, apps/meteor/client/startup/e2e.ts, apps/meteor/client/views/meet/CallPage.tsx, apps/meteor/client/views/meet/MeetPage.tsx
Right now, if the URL is changed by any reason, the embedded layout is lost. This PR aims to make it a "fixed" property once the parameter is added to the URL.
TC-894
=> fix: Keep embedded layout as true once set

apps/meteor/client/hooks/useAppActionButtons.ts
=> regression: add message id back on triggerActionButtonAction

apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts, apps/meteor/app/meteor-accounts-saml/server/lib/Utils.ts, apps/meteor/tests/unit/app/meteor-accounts-saml/server.tests.ts
=> test: add saml unit test

.changeset/witty-feet-warn.md, apps/meteor/client/views/composer/VideoMessageRecorder/VideoMessageRecorder.tsx
=> fix(meteor): Close video recorder if permission denied

.changeset/red-windows-admire.md, apps/meteor/app/apps/server/bridges/http.ts
=> fix: HTTP timeout too short on Apps-Engine bridge

.changeset/tiny-geckos-juggle.md, apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts, apps/meteor/app/meteor-accounts-saml/server/lib/Utils.ts, apps/meteor/tests/unit/app/meteor-accounts-saml/server.tests.ts
Backwards compatibility with mobile app.
Closes #30049
=> fix: SAML login not working on mobile app

apps/meteor/client/views/account/tokens/AccountTokensTable/AccountTokensTable.tsx, apps/meteor/tests/e2e/settings-account-profile.spec.ts
=> test: Personal tokens flaky 2

apps/meteor/tests/e2e/federation/page-objects/account-profile.ts, apps/meteor/tests/e2e/federation/page-objects/admin.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/admin-flextab-users.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-members.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-notificationPreferences.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab-room.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/home-flextab.ts, apps/meteor/tests/e2e/federation/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/account-profile.ts, apps/meteor/tests/e2e/page-objects/admin-email-inboxes.ts, apps/meteor/tests/e2e/page-objects/fragments/admin-flextab-users.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-notificationPreferences.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/fragments/omnichannel-close-chat-modal.ts, apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts, apps/meteor/tests/e2e/page-objects/omnichannel-departments.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts, yarn.lock
- bump fuselage
- improve test button locators
=> chore: improve test button selectors

.github/workflows/ci-test-e2e.yml, apps/meteor/playwright.config.ts, apps/meteor/reporters/rocketchat.ts
https://rocketchat.atlassian.net/browse/ARCH-1136
https://rocketchat.atlassian.net/browse/ARCH-1137
=> ci: start to run reporters on every single pr and add run number

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/layout/RoomLayout.tsx, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/permissions.spec.ts
=> test: flaky tests related to lazy room loading

.changeset/rotten-turtles-agree.md, apps/meteor/client/components/message/list/MessageListSkeleton.tsx, apps/meteor/client/lib/errors/OldUrlRoomError.ts, apps/meteor/client/views/room/RoomOpener.tsx, apps/meteor/client/views/room/RoomRoute.tsx, apps/meteor/client/views/room/hooks/useOpenRoom.ts
=> fix: stop blinking  Room not found before dm creation

apps/meteor/ee/client/apps/communication/websockets.js
=> regression: fix wrong spread props for apps stream

.changeset/yellow-schools-tell.md
Ensures publication of a new set of ESLint rules and configuration.
=> chore(eslint): Update ESLint configuration

.changeset/hip-hounds-ring.md, apps/meteor/client/views/marketplace/AppInstallPage.js, apps/meteor/client/views/marketplace/helpers/handleAPIError.ts, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> feat: Ability to disable private app installation and updates via envvars

.changeset/shiny-garlics-carry.md, apps/meteor/app/cors/server/cors.ts, apps/meteor/tests/end-to-end/api/32-assets.ts
=> fix: CORS not being set for assets

.changeset/unlucky-turtles-search.md, apps/meteor/client/views/account/profile/AccountProfileForm.tsx
=> regression: Accounts profile form name change not working

packages/livechat/src/routes/Chat/container.js
OC-1265
Fixes 
I kinda forgot an await when I changed a function to async 😬
=> regression: Crash in livechat with manual routing

apps/meteor/client/hooks/useAppActionButtons.ts, apps/meteor/client/hooks/useAppSlashCommands.ts, apps/meteor/client/hooks/useAppTranslations.ts, apps/meteor/client/providers/AppsProvider.tsx
=> regression: add deps props for useDebouncedCallback for app stream

packages/fuselage-ui-kit/src/blocks/CalloutBlock.tsx
Keep Fuselage/ui-kit as an agnostic lib!
AECO-362
=> regression(fuselage-ui-kit): remove `ui-kit` icons dependency

apps/meteor/tests/e2e/page-objects/omnichannel-reports.ts
=> chore: removed force click to prevent flaky test

.changeset/forty-hotels-pretend.md, apps/meteor/client/views/room/providers/RoomProvider.tsx
=> fix: Prevent `RoomProvider.useEffect` from subscribing multiple times

apps/meteor/app/oembed/server/server.ts
After the PR [feat: Preview only selected URLs when sending messages #30011](https://github.com/RocketChat/Rocket.Chat/pull/30011) some integrations/bot message stopped showing link previews due to an empty array at `attachments` attribute. It was added a condition to handle that scenario. 
**Before:**
**After:**
1. Go to Rocket.Chat
2. Create a Incoming Webhook integration
3. Send a message trought the webhook that contains a link (e.g: `Example message, link here: [Rocket.Chat website](https://rocket.chat)`)
4. Check if the previews is shown at the desirable channel
TC-946
=> regression: Webhook / bot message without link previews

apps/meteor/tests/e2e/register.spec.ts, packages/ui-client/src/components/CustomFieldsForm.tsx, packages/web-ui-registration/src/RegisterForm.tsx
[DSAR-261]
[DSAR-261]: https://rocketchat.atlassian.net/browse/DSAR-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Registration form a11y improvements

apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx, apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx
This PR adds a debounce of 500ms for both units and custom fields search.
=> fix: added debounce to units and custom fields search

apps/meteor/tests/e2e/utils/test.ts
=> chore: Add `body` on axe scope to avoid false positive results

.github/workflows/ci-test-e2e.yml, .github/workflows/ci-test-unit.yml, .github/workflows/ci.yml, codecov.yml
=> test: codecov flags

packages/fuselage-ui-kit/src/elements/ButtonElement.tsx, packages/fuselage-ui-kit/src/hooks/useUiKitState.ts
Last update on fuselage element `Button` introduces in the inner content of it a `<span>` element. Saying that, it's necessary to change how we handle event target in UiKit button action, passing `currentTarget` instead of `target`.
=> regression: Change UiKit buttons event handler

packages/uikit-playground/src/Payload/callout/index.ts, yarn.lock
=> regression(deps): Bumping Fuselage breaks `uikit-playground`

apps/meteor/package.json
=> chore: increase ts memory

apps/meteor/client/views/account/profile/AccountProfileForm.tsx
=> regression: `AccountProfileForm` not reseting

apps/meteor/tests/e2e/login.spec.ts, apps/meteor/tests/e2e/register.spec.ts, packages/web-ui-registration/src/LoginForm.tsx, packages/web-ui-registration/src/RegisterForm.tsx, packages/web-ui-registration/src/RegisterTemplate.tsx, packages/web-ui-registration/src/components/RegisterTitle.tsx, packages/web-ui-registration/src/template/HorizontalTemplate.tsx
[DSAR-259]
[DSAR-259]: https://rocketchat.atlassian.net/browse/DSAR-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `LoginForm` a11y improvements

.changeset/nine-bottles-press.md, apps/meteor/app/mentions/server/getMentionedTeamMembers.ts, apps/meteor/app/mentions/server/server.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, apps/meteor/server/lib/spotlight.js, apps/meteor/server/settings/troubleshoot.ts
=> feat: Add flag to disable teams mention via troubleshoot

apps/meteor/client/views/admin/info/DeploymentCard.tsx
=> chore: Add commit subject to info panel

packages/web-ui-registration/src/LoginForm.tsx
The callout messages of the login page weren't being passed through a i18n t function, this PR adds it to the code.
Demo images:
[WM-178]: https://rocketchat.atlassian.net/browse/WM-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Login page callout messages

.changeset/three-ants-give.md, packages/cron/src/index.ts
=> fix: increase cron job check delay to 1 min

apps/meteor/client/hooks/useAppTranslations.ts
Introduced here:
https://github.com/RocketChat/Rocket.Chat/pull/30221
=> regression(Apps): Apps translations overriding core translations

apps/meteor/ee/server/models/raw/LivechatRooms.ts
=> regression: `$group` by `alias + type` instead of full `$source` object on reports page

apps/meteor/client/views/omnichannel/contactHistory/ContactHistory.tsx
=> regression: close button not working on contact history

.github/workflows/ci-code-check.yml, apps/meteor/.gitignore, apps/meteor/tsconfig.typecheck.json
=> chore: cache incremental ts check

.yarn/patches/mongodb-npm-4.17.1-a2fe811ff1.patch, apps/meteor/tsconfig.typecheck.json, package.json
=> ci: patch mongo type definitions

apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts, apps/meteor/ee/client/startup/readReceipt.ts
[TC-965](https://rocketchat.atlassian.net/browse/TC-965)
[TC-965]: https://rocketchat.atlassian.net/browse/TC-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Videoconf message actions

apps/meteor/client/components/AutoCompleteDepartmentMultiple.tsx, apps/meteor/ee/client/hooks/useTagsList.ts, apps/meteor/ee/client/omnichannel/tags/AutoCompleteTagsMultiple.js
[OC-1310](https://rocketchat.atlassian.net/browse/OC-1310)
[OC-1310]: https://rocketchat.atlassian.net/browse/OC-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: selected options not being displayed on `PaginatedMultiSelect`

packages/livechat/src/lib/random.ts
=> regression: livechat uiKit actions not working

apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
[SUP-366](https://rocketchat.atlassian.net/browse/SUP-366)
[OC-1321](https://rocketchat.atlassian.net/browse/OC-1321)
[SUP-366]: https://rocketchat.atlassian.net/browse/SUP-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Lazy loading not working on 'Forward to department' field

.changeset/old-colts-wonder.md, apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx
=> fix: Monitors now able to forward a chat without taking it first

apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts, apps/meteor/lib/callbacks/callbacksBase.ts
=> chore: adjust callbacks return type

ee/packages/license/src/token.ts
=> chore: set license public key v3 with v2

apps/meteor/app/ui-message/client/messageBox/createComposerAPI.ts, apps/meteor/client/views/room/composer/messageBox/MessageBox.tsx, apps/meteor/client/views/room/composer/messageBox/hooks/useMessageBoxAutoFocus.ts
=> chore: do not focus messagebox on mobile devices

apps/meteor/ee/server/index.ts, apps/meteor/server/main.ts, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-services/src/lib/Api.ts
=> regression: fix initializing startup order

.github/actions/build-docker/action.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml
=> ci: run tests from forks

.github/actions/build-docker/action.yml
=> ci: fix Docker image build for production

.changeset/tiny-wolves-deliver.md, ee/packages/ui-theming/src/palette.ts
[DSAR-293](https://rocketchat.atlassian.net/browse/DSAR-293)
- change light-theme font-disabled color
[DSAR-293]: https://rocketchat.atlassian.net/browse/DSAR-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: font-disabled color

apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx, apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx
fixes possible timeout in `expect remove "user1" as agent` test
=> chore: fix flaky agents & custom fields tables tests

.changeset/twenty-kids-own.md, apps/meteor/app/livechat/server/lib/Livechat.js, apps/meteor/ee/app/livechat-enterprise/server/hooks/applyDepartmentRestrictions.ts
https://rocketchat.atlassian.net/browse/SUP-382
=> fix: Bad query on departments filter & fix callback when closing chats

apps/meteor/client/components/CreateDiscussion/CreateDiscussion.tsx, apps/meteor/client/components/CreateDiscussion/DefaultParentRoomField.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
It also replaces `useEndpointAction` in favor of `useQuery` on `DefaultParentRoomField`
[DSAR-278]
[DSAR-278]: https://rocketchat.atlassian.net/browse/DSAR-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `CreateDiscussion` a11y improvements

apps/meteor/ee/server/startup/maxRoomsPerGuest.ts, apps/meteor/ee/server/startup/seatsCap.ts, ee/packages/license/__tests__/setLicense.spec.ts, ee/packages/license/src/events/emitter.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.spec.ts, ee/packages/license/src/license.ts, ee/packages/license/src/tags.ts, ee/packages/license/src/validation/filterBehaviorsResult.ts, ee/packages/license/src/validation/getCurrentValueForLicenseLimit.ts, ee/packages/license/src/validation/validateLicenseLimits.ts, packages/rest-typings/src/v1/licenses.ts
=> chore: license v3 invalidation

apps/meteor/lib/callbacks.ts
=> chore: add missing `_id` field to `AtLeast`

.changeset/mean-llamas-decide.md, apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
=> regression: Undefined MAC count on startup cloud sync

.changeset/shiny-pillows-run.md, apps/meteor/app/version-check/server/functions/getNewUpdates.ts
=> fix: cloud alerts

.changeset/heavy-ads-carry.md, apps/meteor/client/views/marketplace/hooks/useFilteredApps.ts
Due to the marketplace don't showing apps when Enterprise category is selected, change category name on filtered apps since a change on the database from all apps from Enterprise to Premium.
=> fix: Change plan name from Enterprise to Premium on marketplace filtering

FEATURES.md
I have fixed a minor grammatical error in the FEATURES.md file.
#30682
=> docs: Fixed typo in FEATURES.md

.changeset/perfect-onions-develop.md, apps/meteor/app/utils/lib/i18n.ts
=> fix: i18n translations using sprintf post processor 

ee/packages/license/src/license.spec.ts
=> test: `ShouldPreventAction`

ee/packages/license/src/license.spec.ts, ee/packages/license/src/license.ts
=> regression: validateLicenseLimits not using the expected limit

ee/packages/license/src/license.spec.ts
=> test: License v3 - add test cases for empty limitations

apps/meteor/client/hooks/useLicense.ts, apps/meteor/client/sidebar/header/actions/hooks/useAdministrationItems.spec.tsx, apps/meteor/client/views/admin/info/LicenseCard.tsx, apps/meteor/client/views/hooks/useUpgradeTabParams.ts, apps/meteor/ee/server/api/licenses.ts, apps/meteor/tests/end-to-end/api/20-licenses.js, packages/rest-typings/src/v1/licenses.ts
=> chore: replace endpoint to licenses.info

apps/meteor/client/hooks/useLicense.ts, apps/meteor/ee/app/license/server/license.internalService.ts, apps/meteor/ee/app/license/server/startup.ts, apps/meteor/server/modules/listeners/listeners.module.ts, ee/packages/ddp-client/src/types/streams.ts, ee/packages/license/__tests__/emitter.spec.ts, ee/packages/license/src/definition/LicenseValidationOptions.ts, ee/packages/license/src/definition/events.ts, ee/packages/license/src/events/listeners.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.ts, packages/core-services/src/Events.ts
Used to synchronise multiple instances
=> feat: License v3 sync event

ee/packages/license/src/license.ts
=> feat: make sure every preventActions contains a value

.changeset/cuddly-ties-run.md, apps/meteor/app/ui-master/server/index.js
=> fix: custom-css injection

apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json
=> i18n: Add accessibility and appearance finnish translation

apps/meteor/client/hooks/useLicense.ts, apps/meteor/client/views/admin/info/LicenseCard.tsx, apps/meteor/client/views/hooks/useUpgradeTabParams.ts
=> chore: simplified useLicense return value

.changeset/quick-cups-sparkle.md, apps/meteor/client/views/admin/AdministrationRouter.tsx, apps/meteor/client/views/admin/routes.tsx, apps/meteor/client/views/admin/sidebarItems.ts, apps/meteor/tests/e2e/administration-menu.spec.ts, apps/meteor/tests/e2e/administration.spec.ts
Cherry peak of this merged PR: https://github.com/RocketChat/Rocket.Chat/pull/30648
=> fix: Rollback admin/workspace route to admin/info

apps/meteor/client/components/InfoPanel/InfoPanelAction.tsx, apps/meteor/client/components/InfoPanel/InfoPanelActionGroup.tsx, apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfo.tsx
- focus borders/shadows were hidden:
&#8594;
=> chore: `InfoPanelActionGroup` UI tweaks

apps/meteor/client/hooks/useLicense.ts, ee/packages/license/src/v2/convertToV3.ts
=> regression: License v3 properly debounce query invalidations

.changeset/serious-cats-fetch.md, apps/meteor/client/providers/AppsProvider.tsx, apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx, apps/meteor/client/views/marketplace/AppsPage/NoAppRequestsEmptyState.tsx, apps/meteor/client/views/marketplace/AppsPage/PrivateEmptyState.tsx, apps/meteor/client/views/marketplace/helpers/handleAPIError.ts, apps/meteor/ee/server/apps/communication/rest.ts
=> fix: Private apps list infinite loading in air-gapped environments

apps/meteor/.docker/Dockerfile
=> chore: update Dockerfile

apps/meteor/.docker/Dockerfile
Reverts RocketChat/Rocket.Chat#30755
=> Revert "chore: update Dockerfile"

apps/meteor/client/views/room/contextualBar/ExportMessages/ExportMessages.tsx, apps/meteor/client/views/room/contextualBar/ExportMessages/FileExport.tsx, apps/meteor/client/views/room/contextualBar/ExportMessages/MailExportForm.tsx, apps/meteor/client/views/room/contextualBar/ExportMessages/useRoomExportMutation.ts
It also adds a11y and validation improvements
[DSAR-66]
[DSAR-67]
[DSAR-66]: https://rocketchat.atlassian.net/browse/DSAR-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSAR-67]: https://rocketchat.atlassian.net/browse/DSAR-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Replace `useForm` in favor of RHF on `ExportMessages`

apps/meteor/.docker/Dockerfile
=> chore: Rebuild isolated vm

.changeset/cuddly-animal-eat.md, .changeset/serious-cats-run.md
=> chore: Add missing changesets

apps/meteor/ee/client/views/admin/users/useSeatsCap.ts, apps/meteor/ee/server/api/licenses.ts, ee/packages/license/__tests__/DefaultRestrictions.spec.ts, ee/packages/license/src/deprecated.ts, ee/packages/license/src/license.ts, ee/packages/license/src/validation/validateDefaultLimits.ts, ee/packages/license/src/validation/validateLicenseLimits.ts, ee/packages/license/src/validation/validateLimit.ts, ee/packages/license/src/validation/validateLimits.ts
=> chore: License v3 - create default restrictions if there is no license

apps/meteor/app/cors/server/cors.ts
=> regression: do not cache the main document

apps/meteor/app/livechat/server/api/lib/livechat.ts, apps/meteor/app/livechat/server/hooks/markRoomResponded.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/client/hooks/omnichannel/useIsRoomOverMacLimit.tsx, apps/meteor/server/models/raw/LivechatInquiry.ts, apps/meteor/server/modules/listeners/listeners.module.ts, apps/meteor/server/services/omnichannel/service.ts, apps/meteor/tests/data/livechat/rooms.ts, apps/meteor/tests/end-to-end/api/livechat/23-mac.ts, ee/packages/ddp-client/src/types/streams.ts, packages/core-services/src/Events.ts, packages/core-typings/src/IInquiry.ts, packages/core-typings/src/IRoom.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts
[NBJ-446](https://rocketchat.atlassian.net/browse/NBJ-446)
[NBJ-446]: https://rocketchat.atlassian.net/browse/NBJ-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Inquiries not showing "over MAC limit" indicator

apps/meteor/client/components/PlanTag.tsx
=> chore: Bring back the Plan tag based on license tag names

apps/meteor/app/api/server/v1/channels.ts, apps/meteor/server/models/raw/Uploads.ts, packages/model-typings/src/models/IUploadsModel.ts, packages/rest-typings/src/v1/channels/ChannelsImagesProps.ts, packages/rest-typings/src/v1/channels/channels.ts, packages/rest-typings/src/v1/channels/index.ts
=> feat: add `channels.images` endpoint

ee/packages/license/src/v2/bundles.ts
Since we still need to support license v2 and the license v2 are going to use bundles, I added the new modules to the enterprise bundle to prevent features to stop working as suppose to.
=> chore: new modules to license v2 enterprise bundle

apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseFilter.tsx, apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesTable.tsx
[DSAR-338]
[DSAR-338]: https://rocketchat.atlassian.net/browse/DSAR-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove unnecessary `useForm` in `CannedResponsesTable`

.changeset/angry-kids-occur.md, apps/meteor/server/models/raw/LivechatVisitors.ts
=> regression: Remove more keys from visitor object

apps/meteor/app/livechat/server/methods/sendTranscript.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/24-routing.ts
=> test: Routing & Transcript tests

apps/meteor/client/hooks/useLicense.ts, apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx, apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx, apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx, apps/meteor/ee/client/sidebar/footer/SidebarFooterWatermark.tsx
=> chore: unify plan name

apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
=> regression: flaky test

apps/meteor/app/api/server/v1/cloud.ts, apps/meteor/app/ui-message/client/ActionManager.ts, apps/meteor/client/hooks/useLicense.ts, apps/meteor/client/views/root/AppLayout.tsx, apps/meteor/client/views/root/hooks/useCloudAnnouncements.ts, apps/meteor/server/models/raw/CloudAnnouncements.ts, apps/meteor/server/modules/core-apps/cloudAnnouncements.module.ts, apps/meteor/server/startup/coreApps.ts, packages/mock-providers/src/MockedAppRootBuilder.tsx, packages/model-typings/src/models/ICloudAnnouncementsModel.ts, packages/rest-typings/src/v1/cloud.ts, packages/ui-contexts/src/ActionManagerContext.ts
=> feat(cloud): Cloud announcements core app

apps/meteor/client/hooks/useShouldPreventAction.ts, apps/meteor/client/providers/OmnichannelProvider.tsx, apps/meteor/client/views/admin/users/AdminUsersPage.tsx, apps/meteor/ee/client/views/admin/users/UserPageHeaderContentWithSeatsCap.tsx, apps/meteor/ee/server/startup/seatsCap.ts, ee/packages/license/src/license.ts
=> regression: adjust user creation limits

apps/meteor/app/cloud/server/license.ts
We need to use 3 here so that when syncing it is clear that using v3 license
=> regression: report as supporting license v3

.changeset/thick-ads-run.md, apps/meteor/packages/autoupdate/autoupdate_client.js, apps/meteor/packages/autoupdate/autoupdate_server.js, apps/meteor/packages/autoupdate/client_versions.js, apps/meteor/packages/autoupdate/package.js, package.json, yarn.lock
Immediate auto reload increases server load on restarts/upgrades and increases the chance of getting 404 on meteor config file blocking the ui on a loading screen
This PR imports the autoupdate package from the Meteor's source code to the internal packages folder and add delays on front and backend codes:
- Front-end, adds a warning message including the old and new hashes and delay in 60 seconds after being notified by the server
- Back-end, delays the client notifications on a random value between 2 and 10 minutes per connection, allowing different clients to reload on different moments and distributing the load along the time.
=> fix: immediate auto reload issues

apps/meteor/app/livechat/server/lib/AnalyticsTyped.ts
=> regression: Disable `mem` for `TEST_MODE` on `analytics/overview` endpoint

.changeset/eighty-tips-knock.md, apps/meteor/client/hooks/useLicense.ts
**Previous**
The plan name was not showing correct because the hook `useLicense` it was using the nulish operator `??` and this ignores the empty string `''` as a falsy value. I replaced with the OR operator `||` this treat all falsy values such as empty strings, 0, null, undefined and booleans
[NBJ-472](https://rocketchat.atlassian.net/browse/NBJ-472)
[NBJ-472]: https://rocketchat.atlassian.net/browse/NBJ-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Broken plan name in Community workspace

.changeset/gentle-suns-own.md, apps/meteor/app/cloud/server/functions/getCheckoutUrl.ts
workspace access token
NBJ-474
=> regression: getCheckoutUrl function to use correct access token with scope

.changeset/rotten-pears-watch.md, apps/meteor/app/assets/server/assets.ts
=> fix: wrong client hash calculation due to race condition on assets

apps/meteor/server/settings/misc.ts
=> regression: UniqueID change detection showing on upgrade

apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx, apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx, ee/packages/license/__tests__/MockedLicenseBuilder.ts, ee/packages/license/src/definition/ILicenseV3.ts, ee/packages/license/src/v2/convertToV3.ts
=> chore: LICENSE v3 make visualExpiration optional

.changeset/selfish-panthers-stare.md, apps/meteor/ee/app/canned-responses/client/startup/responses.js
Same issue as: https://github.com/RocketChat/Rocket.Chat/pull/29869
=> fix: Canned responses stream not working

apps/meteor/packages/rocketchat-livechat/assets/demo.html, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts, packages/livechat/webpack.config.ts
Also adds tests to avoid this happening in the future
OC-1415
=> regression: fix livechat not working when embedded

apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx
Due to an DOMException the page was breaking 
https://rocketchat.atlassian.net/browse/NBJ-487
=> regression: airgaped server breaking workspace page

.changeset/ninety-files-sing.md, apps/meteor/server/settings/misc.ts
=> regression: changed UniqueID modal being displayed wrongly during startup

apps/meteor/app/cloud/server/functions/saveRegistrationData.ts
[NBJ-505]
[NBJ-505]: https://rocketchat.atlassian.net/browse/NBJ-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: call sync cloud after registration

.changeset/honest-socks-sniff.md, apps/meteor/server/settings/message.ts
Some settings were not visible, like this google maps setting
=> fix: Google Maps config settings not visible 

apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx, apps/meteor/client/views/admin/subscription/components/UsagePieGraph.tsx, apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx
https://rocketchat.atlassian.net/browse/NBJ-503
=> chore: remove `required` on subscription page

apps/meteor/server/models/raw/LivechatInquiry.ts, apps/meteor/server/services/omnichannel/queue.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts
…ued infinitely
[NBJ-509](https://rocketchat.atlassian.net/browse/NBJ-509)
- This only happens when an inquiry is left on queue and processed _by the queue_ (auto assignment algos bypass the queue)
- Queue had to be stopped/started (during a reboot of the instances maybe) to trigger the error
[NBJ-509]: https://rocketchat.atlassian.net/browse/NBJ-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Queue start/stop flow causing inquiries to be queued again

apps/meteor/server/services/omnichannel/service.ts
=> regression: Start queue on license invalidation

apps/meteor/ee/app/license/server/startup.ts, ee/packages/license/src/definition/events.ts, ee/packages/license/src/license.ts
=> chore: improve license sync

ee/packages/license/__tests__/emitter.spec.ts, ee/packages/license/src/license.spec.ts, ee/packages/license/src/license.ts
=> chore: License change to trigger `start_fair_policy` events and revalidate only once

apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx, apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx, apps/meteor/client/views/admin/subscription/components/FeatureUsageCard.tsx, apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx, apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/ActiveSessionsPeakCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/AppsUsageCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/MACCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardTrial.tsx, apps/meteor/client/views/admin/subscription/components/cards/SeatsCard.tsx, apps/meteor/client/views/admin/subscription/hooks/useCheckoutUrl.ts
=> chore: add target to subscription action

apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
=> regression: Register offline blinking when form is loading

apps/meteor/ee/app/license/server/maxSeatsBanners.ts, apps/meteor/server/services/nps/notification.ts
=> fix: Ensure `viewId` in UiKit banners

apps/meteor/client/providers/AppsProvider.tsx
After installing an app and going to the Subscription page, the card that shows the usage of apps and its limits don't get updated with the last status. 
After some events, I invalidate the license query to get the last apps count.
https://rocketchat.atlassian.net/browse/NBJ-453
=> regression: Subscription page apps count in Community edition

apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
=> regression: Calculate MAC from DB instead of Statistics

.changeset/sixty-goats-divide.md
=> chore:  #30993 changeset

apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
=> chore: show license with after code sequence

apps/meteor/app/livechat/server/lib/LivechatTyped.ts
=> regression: `saveGuest` triggering app events for invalid visitor ids

apps/meteor/client/views/room/contextualBar/Info/EditRoomInfo/EditRoomInfo.tsx
- Do not send an `archive` param to the `saveRoomSettings` endpoint (this is handled by another endpoint already).
Introduced by #28318
Open the information panel (sidebar) in any room, then edit the room by setting it as archived/unarchived and hit save. An "Invalid settings provided" error is currently thrown.
TC-1032
=> regression: error when archiving rooms in the UI

apps/meteor/app/cloud/server/functions/getWorkspaceAccessToken.ts, apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts, apps/meteor/app/cloud/server/functions/removeWorkspaceRegistrationInfo.ts
=> regression: handle cloud delete registration

apps/meteor/app/api/server/v1/cloud.ts, apps/meteor/app/cloud/server/functions/getWorkspaceAccessTokenWithScope.ts, apps/meteor/app/cloud/server/functions/saveRegistrationData.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts, apps/meteor/ee/app/license/server/startup.ts
[NBJ-531](https://rocketchat.atlassian.net/browse/NBJ-531)
[NBJ-532](https://rocketchat.atlassian.net/browse/NBJ-532)
[NBJ-531]: https://rocketchat.atlassian.net/browse/NBJ-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NBJ-532]: https://rocketchat.atlassian.net/browse/NBJ-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: airgapped

apps/meteor/client/views/omnichannel/currentChats/CurrentChatsPage.tsx
=> chore: Changed over mac limit Banner to Callout

.changeset/great-kings-tickle.md, apps/meteor/app/otr/client/OTRRoom.ts
=> fix: OTR calling a deprecated method

apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx, apps/meteor/client/views/admin/subscription/components/cards/PlanCard.tsx, apps/meteor/client/views/admin/subscription/components/cards/PlanCard/PlanCardPremium.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
[NBJ-549](https://rocketchat.atlassian.net/browse/NBJ-549)
[NBJ-549]: https://rocketchat.atlassian.net/browse/NBJ-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: remove unlimited mac info

apps/meteor/app/api/server/v1/cloud.ts, ee/packages/license/__tests__/MockedLicenseBuilder.ts, ee/packages/license/__tests__/setLicense.spec.ts, ee/packages/license/src/license.ts
=> regression: fix registration sync

apps/meteor/client/views/cloud/CloudAnnouncementHandler.tsx, apps/meteor/client/views/cloud/CloudAnnouncementsRegion.tsx
=> regression:  Cloud communication

apps/meteor/app/api/server/middlewares/authentication.ts, apps/meteor/app/cloud/server/functions/getCheckoutUrl.ts, apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx, apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx, apps/meteor/client/views/admin/subscription/hooks/useCheckoutUrl.ts, apps/meteor/ee/app/license/server/getSeatsRequestLink.ts, apps/meteor/ee/client/views/admin/users/useRequestSeatsLink.ts, apps/meteor/ee/server/requestSeatsRoute.ts
[NBJ-538](https://rocketchat.atlassian.net/browse/NBJ-538)
[NBJ-538]: https://rocketchat.atlassian.net/browse/NBJ-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: unify subscription manage urls

apps/meteor/app/version-check/server/functions/buildVersionUpdateMessage.ts
=> regression: New Release banner showing for pre-releases

apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
=> chore: fix priorities sidebar flaky test

packages/fuselage-ui-kit/package.json, packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
=> regression(fuselage-ui-kit): Handle null text before parsing 

apps/meteor/client/views/banners/hooks/useRemoteBanners.ts, apps/meteor/ee/server/apps/communication/uikit.ts, apps/meteor/server/modules/core-apps/banner.module.ts, apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/fixtures/userStates.ts
[NBJ-504](https://rocketchat.atlassian.net/browse/NBJ-504)
[NBJ-504]: https://rocketchat.atlassian.net/browse/NBJ-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: banners close

apps/meteor/ee/app/authorization/server/callback.ts, apps/meteor/ee/app/authorization/server/validateUserRoles.spec.ts, apps/meteor/ee/app/authorization/server/validateUserRoles.ts, apps/meteor/ee/app/license/server/startup.ts, apps/meteor/ee/server/startup/index.ts, ee/packages/license/src/events/listeners.ts, ee/packages/license/src/index.ts
=> chore: Improve license events

apps/meteor/ee/app/authorization/server/callback.ts
=> regression: user activation events

apps/meteor/ee/app/license/server/settings.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
=> fix: Missing info about license removal

apps/meteor/app/cloud/server/functions/saveRegistrationData.ts, apps/meteor/ee/app/license/server/applyLicense.ts, apps/meteor/ee/app/license/server/startup.ts, packages/core-services/src/lib/Api.ts
=> fix: Prevent process crash when broadcasting before broker set

apps/meteor/client/views/admin/subscription/SubscriptionCalloutLimits.tsx, apps/meteor/ee/app/authorization/server/callback.ts, ee/packages/license/src/license.spec.ts, ee/packages/license/src/validation/validateLimit.ts
=> chore: change trigger logic

apps/meteor/app/cloud/server/functions/buildRegistrationData.ts
=> chore: add license into registration data

apps/meteor/app/api/server/v1/cloud.ts, apps/meteor/app/cloud/server/functions/getWorkspaceLicense.ts, apps/meteor/app/cloud/server/functions/removeLicense.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts, apps/meteor/app/cloud/server/functions/syncWorkspace/syncCloudData.ts, apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx, apps/meteor/client/views/admin/subscription/components/UpgradeButton.tsx, apps/meteor/client/views/admin/subscription/components/UpgradeToGetMore.tsx, apps/meteor/client/views/admin/subscription/components/cards/FeaturesCard.tsx, apps/meteor/client/views/admin/subscription/hooks/useRemoveLicense.ts, apps/meteor/client/views/admin/workspace/VersionCard/VersionCard.tsx, apps/meteor/client/views/admin/workspace/VersionCard/components/VersionTag.tsx, apps/meteor/client/views/admin/workspace/VersionCard/getVersionStatus.spec.ts, apps/meteor/client/views/admin/workspace/VersionCard/getVersionStatus.ts, apps/meteor/ee/app/license/server/applyLicense.ts, apps/meteor/ee/app/license/server/settings.ts, apps/meteor/ee/app/license/server/startup.ts, apps/meteor/lib/callbacks.ts, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json, ee/packages/license/src/definition/ILicenseV3.ts, ee/packages/license/src/definition/events.ts, ee/packages/license/src/events/listeners.ts, ee/packages/license/src/index.ts, ee/packages/license/src/license.ts, packages/core-typings/src/cloud/WorkspaceSyncPayload.ts, packages/rest-typings/src/v1/cloud.ts
https://rocketchat.atlassian.net/browse/NBJ-567
https://rocketchat.atlassian.net/browse/NBJ-568
=> chore: allow to remove license

apps/meteor/ee/server/services/package.json, apps/meteor/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/gazzodown/package.json, packages/livechat/package.json, packages/rest-typings/package.json, yarn.lock
=> chore: bump `message-parser` package version

.github/workflows/ci.yml, apps/meteor/packages/rocketchat-version/plugin/compile-version.js
=> chore: Use draft release on supported versions

.github/workflows/ci.yml
=> chore: Fix notify-draft-services

.github/workflows/ci.yml, apps/meteor/client/lib/utils/isOverLicenseLimits.ts
=> chore: fix invalid auth

apps/meteor/packages/rocketchat-version/plugin/compile-version.js
=> chore: get right type from supported version

apps/meteor/client/components/ImageGallery/ImageGallery.tsx, apps/meteor/client/components/ImageGallery/ImageGalleryLoader.tsx
- change Throbber color
- loading position absolute to prevent displacement on loading heavy images
=> chore: ImageGallery tweaks

apps/meteor/app/autotranslate/server/autotranslate.ts, apps/meteor/app/autotranslate/server/methods/translateMessage.ts
=> chore: add a manual msg stream update for autotranslate

apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx, apps/meteor/client/views/omnichannel/directory/chats/contextualBar/ChatInfo.js, apps/meteor/ee/app/livechat-enterprise/client/components/modals/PlaceChatOnHoldModal.tsx, apps/meteor/ee/client/omnichannel/cannedResponses/components/cannedResponseForm.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-monitor-role.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts, apps/meteor/tests/e2e/page-objects/home-omnichannel.ts, apps/meteor/tests/e2e/page-objects/omnichannel-canned-responses.ts
[OC-1420](https://rocketchat.atlassian.net/browse/OC-1420)
[OC-1420]: https://rocketchat.atlassian.net/browse/OC-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: implemented monitor role e2e tests

apps/meteor/client/components/avatar/RoomAvatarEditor.tsx, apps/meteor/client/components/avatar/UserAvatarEditor/UserAvatarEditor.tsx, apps/meteor/client/hooks/useSingleFileInput.ts, apps/meteor/client/views/admin/customEmoji/AddCustomEmoji.tsx, apps/meteor/client/views/admin/customEmoji/EditCustomEmoji.tsx, apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx, apps/meteor/client/views/admin/customSounds/EditSound.tsx, apps/meteor/client/views/marketplace/AppInstallPage.js
=> chore: Rename useFileInput to useSingleFileInput

apps/meteor/ee/app/livechat-enterprise/server/hooks/applySimultaneousChatsRestrictions.ts
fix: fixed typo error of livechat.applySimultaneousChatRestrictions in livechat-enterprise to apply department simultaneous chat restriction.
=> fix: typo error in livechat.applySimultaneousChatRestrictions hook

.gitignore, .sublime-project
=> chore: Add Project File for Sublime Text

apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-chat-transfers.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-transfer-to-another-agents.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-omnichannel-content.ts, apps/meteor/tests/e2e/page-objects/omnichannel-transfer-chat-modal.ts, apps/meteor/tests/e2e/utils/omnichannel/managers.ts, apps/meteor/tests/e2e/utils/omnichannel/rooms.ts
[OC-1371](https://rocketchat.atlassian.net/browse/OC-1371)
[OC-1371]: https://rocketchat.atlassian.net/browse/OC-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: implemented chat transfer e2e tests

apps/meteor/ee/client/omnichannel/units/UnitEdit.tsx, apps/meteor/ee/client/omnichannel/units/UnitsTable.tsx, apps/meteor/ee/client/omnichannel/units/useRemoveUnit.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/omnichannel-sidenav.ts, apps/meteor/tests/e2e/page-objects/index.ts, apps/meteor/tests/e2e/page-objects/omnichannel-units.ts
[OC-1369](https://rocketchat.atlassian.net/browse/OC-1369)
[OC-1369]: https://rocketchat.atlassian.net/browse/OC-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: implemented e2e tests for units admin page

apps/meteor/tests/e2e/omnichannel/omnichannel-manager-role.spec.ts, apps/meteor/tests/e2e/page-objects/home-omnichannel.ts, apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
[OC-1421](https://rocketchat.atlassian.net/browse/OC-1421)
[OC-1421]: https://rocketchat.atlassian.net/browse/OC-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: implemented manager role e2e tests

.changeset/new-avocados-sort.md, apps/meteor/app/metrics/server/lib/metrics.ts, apps/meteor/server/services/meteor/service.ts
=> fix: Wrong `Message Roundtrip Time` metric

apps/meteor/client/components/ImageGallery/hooks/useImagesList.ts
=> fix: image disappearing with new message

.changeset/gold-stingrays-compete.md, apps/meteor/client/views/cloud/CloudAnnouncementsRegion.tsx
=> fix: stop refetching banner data

apps/meteor/app/metrics/server/lib/collectMetrics.ts, apps/meteor/app/metrics/server/lib/metrics.ts, apps/meteor/package.json, yarn.lock
=> chore: Add slide window config to round trip metric

.github/actions/meteor-build/action.yml, .github/workflows/ci.yml
=> ci: collect coverage in any branch except for releases

apps/meteor/client/views/room/body/hooks/useGoToHomeOnRemoved.ts
An unstable dependency was causing a stream to be unsubscribed and then resubscribed on every message sent.
=> fix: Sending messages triggering stream unsub/sub

apps/meteor/client/components/Page/PageHeader.tsx, apps/meteor/client/views/admin/emailInbox/EmailInboxPage.tsx, apps/meteor/client/views/admin/import/NewImportPage.tsx, apps/meteor/client/views/admin/import/PrepareImportPage.tsx, apps/meteor/client/views/admin/integrations/incoming/EditIncomingWebhook.tsx, apps/meteor/client/views/admin/integrations/outgoing/EditOutgoingWebhook.tsx, apps/meteor/client/views/admin/integrations/outgoing/history/OutgoingWebhookHistoryPage.tsx, apps/meteor/client/views/admin/oauthApps/OAuthAppsPage.tsx, apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx, apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponseEdit.tsx
=> regression: `PageHeader` back button must be an `IconButton`

apps/meteor/app/lib/client/methods/sendMessage.ts, apps/meteor/app/lib/server/functions/sendMessage.js, apps/meteor/app/lib/server/functions/updateMessage.ts, apps/meteor/app/message-pin/server/pinMessage.ts, apps/meteor/client/methods/updateMessage.ts, apps/meteor/lib/callbacks.ts
The callback is not needed anymore since all functionality was moved to Message service.
=> chore: remove `beforeSaveMessage` callback

.changeset/real-items-tan.md, ee/packages/ddp-client/src/DDPSDK.ts, ee/packages/ddp-client/src/types/Account.ts
=> fix: SDK login methods not saving token

.github/PULL_REQUEST_TEMPLATE.md
- Correct outdated information stating that the proposed changes section will be included in the release notes.
=> chore: Update "Proposed changes" PR template's section

.changeset/lucky-apricots-change.md, apps/meteor/client/views/admin/subscription/SubscriptionPage.tsx
=> fix: Remove trial param from checking cancel subscription button

.changeset/popular-beds-heal.md, apps/meteor/app/lib/server/functions/sendMessage.js, apps/meteor/app/lib/server/functions/sendMessage.ts, apps/meteor/app/otr/client/OTR.ts, apps/meteor/app/otr/client/OTRRoom.ts, apps/meteor/app/otr/lib/IOTR.ts, apps/meteor/app/otr/server/methods/updateOTRAck.ts, apps/meteor/client/components/message/StatusIndicators.tsx, apps/meteor/client/hooks/roomActions/useOTRRoomAction.ts, apps/meteor/client/lib/parseMessageTextToAstMarkdown.ts, apps/meteor/client/lib/utils/getUidDirectMessage.ts, apps/meteor/client/startup/otr.ts, apps/meteor/client/views/room/contextualBar/OTR/OTRWithData.tsx, apps/meteor/server/hooks/messages/markdownParser.ts, apps/meteor/server/services/video-conference/service.ts, ee/packages/ddp-client/src/types/streams.ts, packages/core-typings/src/IMessage/IMessage.ts
Whenever a OTR message is received, there is a loop-like cycle of calls to the `updateOTRAck` method until the rate limiter kicks in. This PR aims to fix it.
[SUP-269](https://rocketchat.atlassian.net/browse/SUP-269)
[SUP-269]: https://rocketchat.atlassian.net/browse/SUP-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(otr): exceeding API calls when sending OTR messages

.changeset/lucky-cycles-leave.md, apps/meteor/package.json, yarn.lock
updating package onboarding-ui (fix https://github.com/RocketChat/fuselage/pull/1250 ) that upgrade/fix the select component for country.
fix https://github.com/RocketChat/Rocket.Chat/issues/31200
https://rocketchat.atlassian.net/browse/WM-213
=> fix: country select 

.github/workflows/ci-test-e2e.yml, apps/meteor/package.json, yarn.lock
=> test: bump playwright

apps/meteor/app/metrics/server/lib/collectMetrics.ts, apps/meteor/app/statistics/server/lib/getAppsStatistics.js, apps/meteor/app/statistics/server/lib/statistics.ts, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/ee/server/apps/communication/websockets.ts, apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/server/services/apps-engine/service.ts
Refactor `app.getStatus()` usages to new API
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/698
=> chore: Refactor `app.getStatus()` usages

.changeset/silent-shirts-knock.md
=> chore: Add missing changeset file

packages/i18n/src/index.mjs
=> chore(i18n): prevent error on `./dist` folder deletion

apps/meteor/app/livechat/server/api/v1/room.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts
=> chore: Make room closing process more sequential

apps/meteor/ee/server/startup/services.ts
=> chore: federation startup

apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/ee/server/apps/startup.ts
=> chore:  app startup

apps/meteor/app/lib/server/startup/index.ts, apps/meteor/app/lib/server/startup/oAuthServicesUpdate.js, apps/meteor/server/main.ts
=> chore: server import order

.changeset/witty-dogs-share.md
=> chore: Add missing changeset

apps/meteor/client/lib/VideoConfManager.ts
=> refactor: Replace `Notifications` module in favor of `sdk` for Video Conf

.changeset/angry-llamas-retire.md, packages/eslint-config/package.json, yarn.lock
Publishes the module for configuration of React-related rules on ESLint (`@rocket.chat/eslint-config/react`).
=> chore(eslint-config): Include missing ESLint configuration for React

.changeset/breezy-ladybugs-sip.md
=> chore: Remove unnecessary changeset file

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-widget.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat-embedded.ts, packages/livechat/src/components/Button/index.tsx, packages/livechat/src/components/Screen/index.js
=> chore: fix embedded livechat tests 

.changeset/silent-shirts-knock.md
Reverts RocketChat/Rocket.Chat#31431
=> chore: Revert "chore: Add missing changeset file"

apps/meteor/app/api/server/api.ts, apps/meteor/app/lib/server/lib/RateLimiter.js, apps/meteor/app/lib/server/startup/rateLimiter.js, apps/meteor/definition/externals/meteor/rate-limit.d.ts
=> chore: RateLimiter to async

.changeset/beige-deers-laugh.md, .changeset/bump-patch-1705335886930.md, .changeset/fresh-maps-rhyme.md, apps/meteor/app/2fa/server/methods/validateTempToken.ts, apps/meteor/app/api/server/v1/users.ts, apps/meteor/client/components/TwoFactorModal/TwoFactorModal.tsx, apps/meteor/client/views/account/security/TwoFactorTOTP.tsx, apps/meteor/server/models/raw/BaseRaw.ts, apps/meteor/server/startup/migrations/v304.ts, package.json, yarn.lock
*   b1e72a84d9: Fix user being logged out after using 2FA
*   de2658e874: Bump @rocket.chat/meteor version.
*   2a04cc850b: fix: multiple indexes creation error during 304 migration
*   @rocket.chat/core-typings@6.5.3
*   @rocket.chat/rest-typings@6.5.3
*   @rocket.chat/api-client@0.1.21
*   @rocket.chat/license@0.1.3
*   @rocket.chat/omnichannel-services@0.1.3
*   @rocket.chat/pdf-worker@0.0.27
*   @rocket.chat/presence@0.1.3
*   @rocket.chat/core-services@0.3.3
*   @rocket.chat/cron@0.0.23
*   @rocket.chat/gazzodown@3.0.3
*   @rocket.chat/model-typings@0.2.3
*   @rocket.chat/ui-contexts@3.0.3
*   @rocket.chat/server-cloud-communication@0.0.1
* …
=> Release 6.5.3

.changeset/wicked-pumpkins-walk.md, packages/agenda/src/Agenda.ts
It drops usage of callbacks in `@rocket.chat/agenda`; it improves type safety over nullable values.
=> feat(agenda): Changes in Agenda API

packages/web-ui-registration/src/LoginForm.tsx
=> regression: LoginForm button misalignment

apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.js
Fixes undisclosed issue introduced in #31225
=> regression: Convert emoji shortname to unicode on notification emails

apps/meteor/app/lib/server/functions/notifications/desktop.ts, apps/meteor/app/lib/server/functions/notifications/index.ts, apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts, apps/meteor/app/livechat/server/lib/Helper.ts
=> refactor: convert sendNotification to ts

.kodiak.toml
=> ci: add do not merge label to kodiak

packages/ui-kit/package.json
=> chore: remove prepare script from ui-kit

packages/ui-kit/package.json
=> chore: Restore ui-kit prepare script

packages/release-action/src/bumpNextVersion.ts, packages/release-action/src/publishRelease.ts, packages/release-action/src/updatePRDescription.ts, packages/release-action/src/utils.ts
Now get full release notes even if in "pre release". Also moved some code to utility functions for better code reusability.
=> ci: create better preview release notes for candidates

.changeset/grumpy-eagles-roll.md, apps/meteor/app/mail-messages/server/functions/sendMail.ts, apps/meteor/tests/end-to-end/api/livechat/12-mailer.ts
https://rocketchat.atlassian.net/browse/SUP-446
=> fix: dryrun option sending email to all queried users

apps/meteor/client/components/message/content/Reactions.tsx, apps/meteor/client/components/message/content/reactions/Reaction.tsx
When reactions hovered for the first time, the tooltip shows "true" for a second before showing actual tooltip
Closes #31562 
TC-1091
TC-1104
=> regression: Fix reactions tooltip

apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx, apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUsersTable.tsx, apps/meteor/client/views/admin/moderation/hooks/useDeactivateUserAction.tsx, apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
Fixed a problem with the moderation console translations in which inexistent translation keys were being used to translate the Reports column of the users table tab and the success toast of the deactivate user action.
Demo gif:
[TC-1098](https://rocketchat.atlassian.net/browse/TC-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[TC-1098]: https://rocketchat.atlassian.net/browse/TC-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Moderation console translations

codecov.yml
=> ci: add back carryforward flag

apps/meteor/ee/client/omnichannel/reports/ReportsPage.tsx, apps/meteor/ee/client/omnichannel/reports/sections/AgentsSection.tsx
[OC-1454](https://rocketchat.atlassian.net/browse/OC-1454)
[OC-1454]: https://rocketchat.atlassian.net/browse/OC-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: report page's agents section not taking the full width

.changeset/twenty-yaks-grab.md, apps/meteor/app/lib/server/functions/cleanRoomHistory.ts
=> fix: Messages not updating properly after pruning the room

apps/meteor/tests/end-to-end/api/19-statistics.js, apps/meteor/tests/end-to-end/api/20-licenses.js
=> test: make stats and license tests fully independent

apps/meteor/tests/end-to-end/api/11-permissions.js
=> test: make permission test fully independent

.changeset/blue-files-deny.md, apps/meteor/client/views/admin/rooms/EditRoom.tsx
=> fix: #31722 roomName is not getting update 

.changeset/silver-chicken-learn.md, packages/livechat/src/lib/room.js
[SUP-486](https://rocketchat.atlassian.net/browse/SUP-486)
Go to Admin > Settings > Omnichannel and turn on `Clear guest session when chat ended`
On the same page, change the Livechat background color.
Open a new chat, and finish it. It should not revert to the default color.
[SUP-486]: https://rocketchat.atlassian.net/browse/SUP-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Blinking UI colors when finishing a Livechat conversation.

packages/livechat/src/components/Messages/Message/index.js, packages/livechat/src/components/Messages/MessageList/index.js, packages/livechat/src/components/Screen/ScreenProvider.tsx, packages/livechat/src/lib/hooks.ts, packages/livechat/src/routes/Chat/component.js, packages/livechat/src/routes/Chat/connector.tsx, packages/livechat/src/routes/Chat/container.js, packages/livechat/src/store/index.tsx
[PROSVC-50](https://rocketchat.atlassian.net/browse/PROSVC-50)
[PROSVC-50]: https://rocketchat.atlassian.net/browse/PROSVC-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added hideGuestAvatar and hideAgentAvatar to Livechat API's setTheme

apps/meteor/tests/e2e/fixtures/userStates.ts
=> ci: end-to-end tests breaking

apps/meteor/client/components/message/content/reactions/ReactionTooltip.tsx
=> regression: Reactions loader skeleton color

.github/actions/meteor-build/action.yml, apps/meteor/package.json, turbo.json
=> ci: change arg place to reuse cache

ee/packages/ddp-client/package.json, yarn.lock
=> chore: add missing packages to ddp-client

apps/meteor/app/apps/server/bridges/commands.ts
[VM2-18](https://rocketchat.atlassian.net/browse/VM2-18?atlOrigin=eyJpIjoiMDdlZWZhNmQ5YTZlNDdlODg5Njk5Mjc3YmU3NTFmMmMiLCJwIjoiaiJ9)
[VM2-18]: https://rocketchat.atlassian.net/browse/VM2-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: slashcommand preview

apps/meteor/tests/end-to-end/api/30-calendar.ts
=> test: make calendar api tests fully independent

apps/meteor/app/apps/server/bridges/commands.ts, apps/meteor/app/apps/server/bridges/http.ts, apps/meteor/ee/server/apps/communication/rest.ts, apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/ee/server/apps/storage/AppRealLogStorage.ts
=> fix: deno runtime improvements

.changeset/strange-lamps-taste.md, apps/meteor/app/notifications/client/lib/Presence.ts, apps/meteor/server/modules/listeners/listeners.module.ts, apps/meteor/server/modules/notifications/notifications.module.ts, ee/packages/ddp-client/src/types/streams.ts
=> fix: revert status websocket payload changes

.changeset/kind-lobsters-leave.md, apps/meteor/app/livechat/server/lib/Analytics.js
[CORE-112](https://rocketchat.atlassian.net/browse/CORE-112)
[CORE-112]: https://rocketchat.atlassian.net/browse/CORE-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Omnichannel analytics page (productivity overview)

.changeset/young-doors-bathe.md, apps/meteor/app/notifications/client/lib/Presence.ts, ee/apps/ddp-streamer/package.json
=> fix: client ignoring offline presence updates

packages/message-parser/src/grammar.pegjs, packages/message-parser/src/utils.ts, packages/message-parser/tests/emphasis.test.ts, packages/message-parser/tsconfig.json
=> fix: message parser emphasis black hole

packages/apps/package.json, yarn.lock
=> chore: update ts version on recently merged package

.changeset/cuddly-rocks-fix.md, apps/meteor/app/lib/server/methods/insertOrUpdateUser.ts
- Deprecate `insertOrUpdateUser` Meteor method (planned to be removed on 8.0.0) -- this is part of an initiative for not allowing users upsert on RC.
[CORE-79](https://rocketchat.atlassian.net/browse/CORE-79?atlOrigin=eyJpIjoiN2QwYmYyNGEyYzMwNDAzMmE5OWUzMWM0YjQ2MDc3MjUiLCJwIjoiaiJ9)
[CORE-79]: https://rocketchat.atlassian.net/browse/CORE-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Deprecate `insertOrUpdateUser` method

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useListIsAtBottom.ts, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx
=> chore: create useListIsAtBottom hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useFileUpload.ts
=> chore: create RoomBody useFileUpload hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useQuoteMessageByUrl.ts
=> chore: create RoomBody useQuoteMessageByUrl hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/UnreadMessagesIndicator.tsx, apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts, apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
=> chore: create RoomBody useHandleUnread hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useGetMore.ts
=> chore: create RoomBody useGetMore hook

apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/hooks/useGetMore.ts, apps/meteor/client/views/room/body/hooks/useHasNewMessages.ts, apps/meteor/client/views/room/body/hooks/useLeaderBanner.ts, apps/meteor/client/views/room/body/hooks/useListIsAtBottom.ts, apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts, apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx, apps/meteor/client/views/room/hooks/useDateScroll.ts
=> refactor: RoomBody reorganize props, hooks, callbacks, effects in order

apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
=> chore: remove forgotten console.log from federation

apps/meteor/client/views/room/BubbleDate/BubbleDate.tsx, apps/meteor/client/views/room/BubbleDate/index.tsx, apps/meteor/client/views/room/MessageList/MessageListItem.tsx, apps/meteor/client/views/room/body/RoomBody.tsx, apps/meteor/client/views/room/body/UnreadMessagesIndicator.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageItem.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadMessageList.tsx, apps/meteor/client/views/room/hooks/useDateScroll.ts
- improve transition when bubble meets divider
- position bubble below unread indicator, when visible
- increase z-index to be in front of mentions and message toolbox
- remove data-time from unread divider
=> chore: date scroll improvements

apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/tests/end-to-end/api/livechat/02-appearance.ts
=> refactor: Use `settings` instead of model for fetching initial omnichannel config

apps/meteor/client/views/room/Header/icons/Favorite.tsx, packages/i18n/src/locales/en.i18n.json
=> regression: Favorite action announcement

packages/livechat/src/api.ts, packages/livechat/src/lib/connection.ts, packages/livechat/src/providers/SDKProvider.tsx, packages/livechat/src/store/index.tsx
=> chore: improve connecting procedure

packages/livechat/src/lib/hooks.ts, packages/livechat/src/store/index.tsx
=> regression: undefined guest causing issues

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-livechat.ts, packages/livechat/src/providers/ServerProvider.tsx
Fixes Issue with Livechat not re subscribing to streams after closing the chat, every time it was trying to subscribe using the same token every time
introduced here https://github.com/RocketChat/Rocket.Chat/pull/31919
=> regression: Livechat resubscription

apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
It seems that  opening the page and the unit creation step happened at the same time. As the page does not have the search input if there is no item the test would fail. So it was up to the destiny (network plus cpu) to decide what happened first
=> test: solve flaky edit unit test

apps/meteor/client/views/room/providers/UserCardProvider.tsx
=> regression: `UserCard` alignment

apps/meteor/tests/e2e/administration.spec.ts, apps/meteor/tests/e2e/page-objects/admin.ts
[ARCH-1281](https://rocketchat.atlassian.net/browse/ARCH-1281)
[ARCH-1281]: https://rocketchat.atlassian.net/browse/ARCH-1281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: fix Default rooms flaky

apps/meteor/client/views/composer/EmojiPicker/EmojiPickerDesktopDropdown.tsx
=> regression: `EmojiPicker` wrong placement

apps/meteor/client/views/room/hooks/useMessageListNavigation.ts
[SR-15]
[SR-15]: https://rocketchat.atlassian.net/browse/SR-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Focus the most recent message instead of the first on message list

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
This is an existing issue, so I've added the test on how it should be working, skipped it and when we have the feature working again we unskip it with the fix
=> test: failing registerGuest function when same token is provided

packages/fuselage-ui-kit/src/elements/MarkdownTextElement.tsx
=> regression: Unintentional semi-colon on ui-kit messages

.changeset/chatty-suits-dance.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
=> chore: bump apps engine version

.changeset/nervous-parrots-march.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
=> chore: bump apps engine version to 1.41.1

apps/meteor/app/utils/rocketchat.info, apps/meteor/package.json, package.json, packages/core-typings/package.json, packages/rest-typings/package.json
=> chore: bump to 6.8.0

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts
[CORE-258]
[CORE-258]: https://rocketchat.atlassian.net/browse/CORE-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(Livechat): Fix RegisterGuest Flaky

apps/meteor/tests/e2e/omnichannel/omnichannel-appearance.spec.ts
[CORE-257]
[CORE-257]: https://rocketchat.atlassian.net/browse/CORE-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(Omnichannel): fix Livechat Appearance Flaky

apps/meteor/tests/e2e/utils/test.ts
=> test(e2e): prevent same api context for multiple suites

turbo.json
There is this legacy, where we import some classes from the meteor package directly from other packages, this is terrible. the turbo simply ignores these paths and they can generate several problems. here I try to protect at least one of the packages from this problem
last time we had this problem:
https://github.com/RocketChat/Rocket.Chat/pull/31969
[CORE-244](https://rocketchat.atlassian.net/browse/CORE-244)
[CORE-244]: https://rocketchat.atlassian.net/browse/CORE-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ddp-streamer): fix cache problem from importing files from another package

.changeset/shaggy-yaks-train.md, apps/meteor/server/settings/misc.ts
=> fix: fingerprint auto accepted still asks for admin confirmation

apps/meteor/app/lib/server/functions/addUserToDefaultChannels.ts, apps/meteor/app/lib/server/functions/addUserToRoom.ts, apps/meteor/app/lib/server/functions/createRoom.ts, apps/meteor/server/methods/addAllUserToRoom.ts, apps/meteor/server/models/raw/Subscriptions.ts, apps/meteor/server/services/federation/infrastructure/rocket-chat/adapters/Room.ts, packages/model-typings/src/models/ISubscriptionsModel.ts
=> chore: remove getDefaultSubscriptionPref from Subscription Model

apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts
Trace hint:
I suspect that there might be some sort of race condition between the inputs caused by `input.type()`. That method is deprecated, playwright suggest using `fill` instead, or `pressSequentially` instead.
=> test: Flaky "expect add "user1" as agent" test

.changeset/nice-hounds-enjoy.md
=> chore: Add missing `changeset`

apps/meteor/client/components/FilterByText.tsx, apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx, apps/meteor/client/views/admin/users/UsersTable/UsersTable.tsx
=> regression: Add prop on `FilterByText` to call auto focus conditionally

.changeset/sharp-yaks-turn.md, apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
As the connection always fails in airgapped environments, it ends up never updating the setting. reversing the logic should solve
=> fix: supported versions not being updated

apps/meteor/client/components/FilterByText.tsx, apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-manager-role.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-manager.spec.ts, apps/meteor/tests/e2e/page-objects/omnichannel-agents.ts, apps/meteor/tests/e2e/page-objects/omnichannel-manager.ts
=> test: Flaky "expect add "user1" as monitor" test

apps/meteor/app/cloud/server/functions/syncWorkspace/index.ts
=> chore: better instant to call `getCachedSupportedVersionsToken.reset()`

apps/meteor/app/utils/rocketchat.info, apps/meteor/package.json, package.json, packages/core-typings/package.json, packages/rest-typings/package.json
=> Bump rocket.chat to 6.9

apps/meteor/client/views/omnichannel/departments/EditDepartment.tsx
Move the conversation closing tags field just after the toggle that enables it since there was a "Allow department to receive forwarded inquiries" in the middle of both. 
[https://rocketchat.atlassian.net/browse/CORE-403](https://rocketchat.atlassian.net/browse/CORE-403)
=> regression: move conversation closing tags field after the toggle that enables it

apps/meteor/app/api/server/v1/channels.ts, apps/meteor/tests/end-to-end/api/02-channels.js
- Improve permissions check on `channels` endpoints by using the `permissionsRequired` property.
[CORE-337](https://rocketchat.atlassian.net/browse/CORE-337?atlOrigin=eyJpIjoiNGMzOWM0Yzk4MTUxNDEwYjhjODRhYWEwMGRhZWQ0MDciLCJwIjoiaiJ9)
[CORE-337]: https://rocketchat.atlassian.net/browse/CORE-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on channels endpoints

apps/meteor/app/api/server/v1/cloud.ts
- Improve permissions check on `cloud` endpoints by using the `permissionsRequired` property.
[CORE-338](https://rocketchat.atlassian.net/browse/CORE-338)
End-to-end tests not added in this one since we don't have any yet.
[CORE-338]: https://rocketchat.atlassian.net/browse/CORE-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on cloud endpoints

apps/meteor/app/api/server/v1/instances.ts, apps/meteor/tests/end-to-end/api/00-miscellaneous.js
- Improve permissions check on `instances` endpoints by using the `permissionsRequired` property.
[CORE-341](https://rocketchat.atlassian.net/browse/CORE-339)
[CORE-341]: https://rocketchat.atlassian.net/browse/CORE-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on instances endpoints

apps/meteor/app/api/server/v1/ldap.ts, apps/meteor/tests/end-to-end/api/26-LDAP.ts
- Improve permissions check on `ldap` endpoints by using the `permissionsRequired` property.
[CORE-342](https://rocketchat.atlassian.net/browse/CORE-342)
[CORE-342]: https://rocketchat.atlassian.net/browse/CORE-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on LDAP endpoints

apps/meteor/app/api/server/v1/mailer.ts, apps/meteor/tests/end-to-end/api/livechat/12-mailer.ts
- Improve permissions check on `mailer` endpoints by using the `permissionsRequired` property.
[CORE-343](https://rocketchat.atlassian.net/browse/CORE-343)
[CORE-343]: https://rocketchat.atlassian.net/browse/CORE-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Improve permissions check on mailer endpoints

apps/meteor/app/lib/server/lib/notifyListener.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts, apps/meteor/ee/app/livechat-enterprise/server/services/omnichannel.internalService.ts
Fix issues found while testing with `DISABLE_DB_WATCHERS` flag enabled. This is a blocker for #32397 since tests are not passing.
[SCA-4]
[SCA-4]: https://rocketchat.atlassian.net/browse/SCA-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix notify room functions and add missing omnichannel room data

apps/meteor/server/ee.ts, apps/meteor/server/foss.ts, apps/meteor/server/main.ts, package.json, scripts/fossify.ts, yarn.lock
After several changes to the codebase to ensure that the FOSS code of Rocket.Chat can run independently from the commercial code, this PR adds a script to remove the premium features that are not under a FOSS license.
[FOSS-15](https://rocketchat.atlassian.net/browse/FOSS-15)
[FOSS-16](https://rocketchat.atlassian.net/browse/FOSS-16)
[FOSS-15]: https://rocketchat.atlassian.net/browse/FOSS-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add script to remove all non-FOSS code

apps/meteor/client/views/admin/users/AdminUsersPage.tsx
=> regression: Users tab misaligned

.github/workflows/ci.yml
=> ci: publish missing Omnichannel services to DockerHub

ee/packages/api-client/package.json, ee/packages/ddp-client/package.json, packages/core-typings/package.json, packages/rest-typings/package.json
We stopped publishing those packages during 6.6.0 release cycle ( 87a4e5b89764cc11525152e4f5e3bc2431c2cef3 ) because at that time the version 6.6.0 of those packages was already published due to a previous mistake, now we can publish them again.
=> chore: Publish npm packages again

apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/tests/e2e/omnichannel/omnichannel-manual-selection-logout.spec.ts
=> fix: Clear queries after logout

apps/meteor/app/utils/rocketchat.info, apps/meteor/package.json, package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json
=> Bump to 6.10.0-develop

apps/meteor/tests/end-to-end/api/25-teams.js
- Fixed `teams.listAll` end-to-end tests
Introduced by #31756 and #32351
=> regression: Fix `teams.listAll` end-to-end tests

.changeset/thin-suns-invent.md, apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts, apps/meteor/client/views/room/composer/ComposerOmnichannel/ComposerOmnichannelInquiry.tsx
Issue: [SUP-594](https://rocketchat.atlassian.net/browse/SUP-594)
[SUP-594]: https://rocketchat.atlassian.net/browse/SUP-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Omnichannel): nonstop sound on current chats using continuous notifications

packages/core-services/src/index.ts
Since this will be the new default moving any time soon, it is a good idea to have it configured like this during development, so issues can be easily found during that phase.
=> chore: disable db watchers on local envs

.changeset/bump-patch-1718214302828.md, .changeset/fuzzy-readers-bake.md, .changeset/thin-suns-invent.md, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-enterprise-menus-logout.spec.ts, yarn.lock
- Apps-Engine: `1.42.2`
*   ([#32591](https://github.com/RocketChat/Rocket.Chat/pull/32591) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes issues with loading license modules when loading the page while logged out
*   ([#32588](https://github.com/RocketChat/Rocket.Chat/pull/32588) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes issues causing nonstop sound notification when taking a chat from the `Current Chats` view
*   @rocket.chat/core-typings@6.9.1
*   @rocket.chat/rest-typings@6.9.1
*   @rocket.chat/api-client@0.1.34
*   @rocket.chat/license@0.1.16
* …
=> Release 6.9.1

apps/meteor/tests/data/users.helper.js, apps/meteor/tests/end-to-end/api/25-teams.js
=> test: fix flaky `Team join` api tests

apps/meteor/server/modules/watchers/lib/messages.ts
=> regression: `Error: Model ISettingsModel not found`

apps/meteor/tests/e2e/e2e-encryption.spec.ts
=> test: flaky e2ee tests

apps/meteor/app/livechat/server/startup.ts, apps/meteor/app/settings/server/CachedSettings.ts
=> test: fix canned-response/business hours flaky test

.changeset/red-cheetahs-heal.md, apps/meteor/client/views/composer/EmojiPicker/EmojiPickerCategoryItem.tsx
[CORE-510]
[CORE-510]: https://rocketchat.atlassian.net/browse/CORE-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Emoji picker's object and symbols category icon swapped

apps/meteor/reporters/rocketchat.ts
Current implementation of Playwright reporter is too verbose showing not very relevant data for every test case:
```
Sending test result to Rocket.Chat: {"name":"OC - Livechat - txt Drag & Drop - FileUpload_Enabled=false","status":"passed","duration":2049,"branch":"refs/pull/32607/merge","draft":false,"run":21641}
✓  75 omnichannel/omnichannel-livechat-fileupload.spec.ts:102:7 › OC - Livechat - OC - File Upload - Disabled › OC - Livechat - txt Drag & Drop - Livechat_fileupload_enabled=false (2.0s)
Sending test result to Rocket.Chat: {"name":"OC - Livechat - txt Drag & Drop - Livechat_fileupload_enabled=false","status":"passed","duration":2010,"branch":"refs/pull/32607/merge","draft":false,"run":21641}
✓  76 omnichannel/omnichannel-livechat-fileupload.spec.ts:102:7 › OC - Livechat - OC - …
```
=> test: make playwright reporter less verbose by showing only errors

apps/meteor/tests/e2e/channel-management.spec.ts, apps/meteor/tests/e2e/page-objects/admin.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-room.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
=> test: Rewrite `getByRole` buttons to match exact string

.changeset/nice-zebras-admire.md, apps/meteor/app/api/server/v1/e2e.ts, apps/meteor/app/e2e/client/rocketchat.e2e.ts, apps/meteor/app/e2e/server/methods/setUserPublicAndPrivateKeys.ts, apps/meteor/app/file-upload/client/lib/fileUploadHandler.ts, packages/rest-typings/src/v1/e2e.ts, packages/rest-typings/src/v1/e2e/e2eSetUserPublicAndPrivateKeysParamsPOST.ts
=> fix: Prevent E2EE key reset on startup

apps/meteor/client/lib/chats/flows/uploadFiles.ts
=> regression: Fail to send file in e2ee rooms not ready

packages/ui-kit/src/blocks/layout/PreviewBlock.ts
=> chore: fix uikit `PreviewBlock` typings 

apps/meteor/client/lib/chats/flows/uploadFiles.ts
=> regression: Fix encrypted file upload ignoring enabling setting

apps/meteor/tests/e2e/admin-room.spec.ts, apps/meteor/tests/e2e/channel-management.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-flextab-members.ts
=> test: close pages properly

apps/meteor/client/lib/chats/flows/uploadFiles.ts, apps/meteor/client/main.ts, apps/meteor/client/serviceWorker.ts, apps/meteor/public/enc.js
=> regression(E2EEncryption): Service Worker not installing on first load

apps/meteor/app/lib/server/functions/notifications/email.js, apps/meteor/tests/unit/app/mailer/getEmailContent.spec.ts
Earlier we were storing encrypted message in `msg` property of message so the previous flow for email notifications made sense.
Now, we started storing encrypted message in `content` property, so had to change how email notifications are sent out for e2ee messages.
[CORE-537](https://rocketchat.atlassian.net/browse/CORE-537)
[CORE-537]: https://rocketchat.atlassian.net/browse/CORE-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Email notification for end-to-end encrypted message

apps/meteor/client/components/message/content/attachments/file/GenericFileAttachment.tsx, apps/meteor/client/hooks/useDownloadFromServiceWorker.ts, apps/meteor/client/lib/chats/flows/uploadFiles.ts, apps/meteor/client/views/room/composer/messageBox/MessageBoxReplies.tsx, apps/meteor/client/views/room/modals/PinMessageModal/PinMessageModal.tsx
=> regression(E2EEncryption): Fix PDF preview & download not working on electron/desktop app

apps/meteor/client/lib/chats/flows/sendMessage.ts
=> regression: Edit encrypted file description not working

apps/meteor/app/e2e/client/rocketchat.e2e.room.js, apps/meteor/client/lib/chats/flows/uploadFiles.ts, packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts, packages/core-typings/src/IUpload.ts
=> regression: Not able to check file consistency when encrypted

apps/meteor/client/views/root/AppErrorPage.tsx
=> chore: allow remove cache on application error

apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
- Update the Apps-Engine to latest release v1.43.0
- Automatic restart of Deno subprocess on some situations https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/777
=> regression: Update Apps-Engine version to 1.43.0

.github/workflows/ci.yml
=> ci: force `Tests Done` to fail if `needs` fails

.github/actions/update-version-durability/action.yml, .github/actions/update-version-durability/index.js, .github/actions/update-version-durability/package-lock.json, .github/actions/update-version-durability/package.json, .github/workflows/ci.yml, .github/workflows/update-version-durability.yml
=> chore: Update docs after a release

apps/meteor/tests/e2e/message-mentions.spec.ts
https://rocketchat.atlassian.net/browse/FLAKY-198
=> test: Flaky `mention @all @here` yet again

apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts
=> test: close pages after page spec

apps/meteor/app/apps/server/converters/cachedFunction.ts, apps/meteor/app/apps/server/converters/messages.js, apps/meteor/app/apps/server/converters/threads.ts
=> chore: cache room and users between bridges

apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-auto-onhold-chat-closing.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-auto-transfer-unanswered-chat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-canned-responses-sidebar.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-changing-room-priority-and-sla.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-chat-history.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-close-chat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-close-inquiry.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-contact-info.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-api.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-avatar-visibility.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-background.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-department.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-fileupload.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-message-bubble-color.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-tab-communication.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-watermark.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-livechat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-priorities-sidebar.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-send-pdf-transcript.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-send-transcript.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-after-registration.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-open-by-visitor.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-triggers-time-on-site.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts, apps/meteor/tests/mocks/data.ts
It handles the flakyness of some tests that use fake Omnichannel visitors. Since their names are used to search the chat room, they must be unique.
=> test(e2e): Avoid duplicated visitor names

apps/meteor/tests/e2e/image-gallery.spec.ts, apps/meteor/tests/e2e/messaging.spec.ts, apps/meteor/tests/e2e/omnichannel/omnichannel-takeChat.spec.ts, apps/meteor/tests/e2e/page-objects/home-channel.ts, apps/meteor/tests/e2e/read-receipts.spec.ts, apps/meteor/tests/e2e/retention-policy.spec.ts, apps/meteor/tests/e2e/video-conference-ring.spec.ts
=> test: closing remaining opened pages

.changeset/cuddly-ravens-swim.md, apps/meteor/app/settings/server/SettingsRegistry.ts
This reverts commit 06707d86e14b6ac3122782b3e6ba6ef1ff8cd449.
https://rocketchat.atlassian.net/browse/CORE-545
=> revert: pr 32541

apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
It seems e2e tests that uses `waitForChannel` are causing intermittent results due the assertion to find no skeleton loader in the room, as the gif shows below:
The proposal solution removes the skeleton loader assertion that can be intermitent due some loading conditions, and focus on waiting for the room list element and the assertion of this list not being busy `aria-busy=false` which means the room is ready to locate elements
[FLAKY-202]
[FLAKY-202]: https://rocketchat.atlassian.net/browse/FLAKY-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: flaky tests related to waitForChannel 

apps/meteor/tests/e2e/e2e-encryption.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
=> test: e2e-encryption use fill and restore api session

apps/meteor/app/apps/server/bridges/livechat.ts, apps/meteor/app/apps/server/converters/messages.js, apps/meteor/app/lib/server/lib/sendNotificationsOnMessage.ts, apps/meteor/app/livechat/server/api/v1/room.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/definition/IRoomTypeConfig.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/AutoTransferChatScheduler.ts, apps/meteor/server/lib/rooms/roomCoordinator.ts, apps/meteor/server/lib/rooms/roomTypes/livechat.ts, apps/meteor/server/lib/rooms/roomTypes/voip.ts, packages/core-typings/src/IMessage/IMessage.ts, packages/core-typings/src/omnichannel/routing.ts
=> chore(omnichannel): stop guessing whether you are a user or a visitor for queries

apps/meteor/server/services/messages/hooks/BeforeSaveMarkdownParser.ts
https://rocketchat.atlassian.net/browse/CORE-564
=> regression: error during upload if description is empty

.github/workflows/ci-test-e2e.yml
=> ci: increase kernel limits

.changeset/cold-chairs-wash.md, .changeset/early-trains-bow.md, .changeset/fair-wasps-switch.md, .changeset/soft-toys-invent.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
- fix: optional methods in video conf providers not being handled correctly (http://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/785)
- fix: handler errors no being sent to subprocess (http://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/784)
- fix: errors during updates and uninstallations when runtime or subprocess is invalid (http://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/787)
- feat: improve package installation and deno caching (http://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/786)
=> fix: Apps-Engine patch

packages/ui-composer/package.json, packages/ui-composer/tsconfig.build.json
It removes modules compiled from `*.stories.tsx` files from the final build of `@rocket.chat/ui-composer`.
=> chore: Exclude Storybook stories from the build of `@rocket.chat/ui-composer`

apps/meteor/tests/unit/app/lib/server/lib/checkUrlForSsrf.tests.ts
=> test: Mock `dns.lookup` on `checkUrlForSsrf` tests

.github/workflows/ci-test-e2e.yml
=> ci: remove tmp files

packages/model-typings/src/updater.ts, packages/models/src/updater.spec.ts, packages/models/src/updater.ts
=> chore(models): Filter update accumulator 

.github/actions/meteor-build/action.yml
=> ci: regression `actions/upload-artifact@v4` meteor build production

.github/actions/setup-node/action.yml, .github/workflows/ci-test-e2e.yml
=> ci: fix prs from forks

.changeset/proud-years-buy.md, packages/i18n/src/locales/de.i18n.json, yarn.lock
This PR fixes a translation text typo for German, where **einmal** was written as **einemal**. It also includes the missing hyperlinks for **Resend** and **Change Email**.
[https://rocketchat.atlassian.net/browse/SUP-632](SUP-632)
1. Set language to German
2. Go through the four steps of workspace registration
N/a
=> fix(i18n): fixes onboarding.component.emailCodeFallback translation

.changeset/perfect-dancers-grab.md, apps/meteor/app/api/server/v1/rooms.ts, apps/meteor/app/api/server/v1/users.ts, apps/meteor/app/livechat/imports/server/rest/sms.ts, apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx, apps/meteor/ee/server/lib/audit/methods.ts, apps/meteor/server/lib/ldap/Manager.ts, apps/meteor/server/methods/reportMessage.ts, apps/meteor/server/methods/sendConfirmationEmail.ts, apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts, apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts, apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts, apps/meteor/server/settings/message.ts, apps/meteor/tests/end-to-end/api/methods.ts, apps/meteor/tests/end-to-end/api/rooms.ts, apps/meteor/tests/end-to-end/api/users.ts, apps/meteor/tests/unit/server/services/omnichannel-integrations/providers/twilio.spec.ts, packages/core-typings/package.json, packages/core-typings/src/omnichannel/sms.ts, packages/rest-typings/src/v1/rooms.ts, yarn.lock
=> fix: imported fixes

.changeset/bump-patch-1723645120544.md, .changeset/perfect-dancers-grab.md, apps/meteor/app/api/server/v1/rooms.ts, apps/meteor/app/api/server/v1/users.ts, apps/meteor/app/livechat/imports/server/rest/sms.ts, apps/meteor/app/retention-policy/server/cronPruneMessages.ts, apps/meteor/client/views/admin/oauthApps/EditOauthApp.tsx, apps/meteor/ee/server/lib/audit/methods.ts, apps/meteor/server/lib/ldap/Manager.ts, apps/meteor/server/methods/reportMessage.ts, apps/meteor/server/methods/sendConfirmationEmail.ts, apps/meteor/server/services/omnichannel-integrations/providers/mobex.ts, apps/meteor/server/services/omnichannel-integrations/providers/twilio.ts, apps/meteor/server/services/omnichannel-integrations/providers/voxtelesys.ts, apps/meteor/server/settings/message.ts, apps/meteor/tests/end-to-end/api/methods.ts, apps/meteor/tests/end-to-end/api/rooms.ts, apps/meteor/tests/end-to-end/api/users.ts, apps/meteor/tests/unit/server/services/omnichannel-integrations/providers/twilio.spec.ts, packages/core-typings/package.json, packages/core-typings/src/omnichannel/sms.ts, packages/rest-typings/src/v1/rooms.ts, yarn.lock
- Apps-Engine: `1.44.0`
*   ([#33062](https://github.com/RocketChat/Rocket.Chat/pull/33062)) Security Hotfix (https://docs.rocket.chat/docs/security-fixes-and-updates)
*   @rocket.chat/core-typings@6.11.1
*   @rocket.chat/rest-typings@6.11.1
*   @rocket.chat/api-client@0.2.4
*   @rocket.chat/license@0.2.4
*   @rocket.chat/omnichannel-services@0.3.1
*   @rocket.chat/pdf-worker@0.2.1
*   @rocket.chat/presence@0.2.4
*   @rocket.chat/apps@0.1.4
*   @rocket.chat/core-services@0.5.1
*   @rocket.chat/cron@0.1.4
*   @rocket.chat/fuselage-ui-kit@9.0.1
*   @rocket.chat/gazzodown@9.0.1
* …
=> Release 6.11.1

apps/meteor/app/api/server/v1/assets.ts, apps/meteor/app/assets/server/assets.ts, apps/meteor/app/assets/server/index.ts
Removed setAsset, unsetAsset, refreshClients method as they are now replaced with assets.setAsset and assets.unsetAsset endpoint
[CORE-356](https://rocketchat.atlassian.net/browse/CORE-356)
[CORE-356]: https://rocketchat.atlassian.net/browse/CORE-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: removed setAsset, unsetAsset, refreshClients method

apps/meteor/app/api/server/v1/cloud.ts, apps/meteor/tests/end-to-end/api/34-cloud.ts, apps/meteor/tests/end-to-end/api/cloud.ts, packages/rest-typings/src/index.ts, packages/rest-typings/src/v1/cloud.ts
- Remove `meteor/check` from `cloud` endpoints by using the `validateParams` property.
[CORE-317](https://rocketchat.atlassian.net/browse/CORE-317)
**The intention for this PR is to improve code readability and make invalid params errors more standardized. No side effects are expected. We're considering this a breaking change since invalid params errors are being changed to follow the same standard when possible.**
[CORE-317]: https://rocketchat.atlassian.net/browse/CORE-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove `meteor/check` from `cloud` endpoints

apps/meteor/app/livechat/server/lib/LivechatTyped.ts, apps/meteor/server/models/raw/BaseRaw.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
[do not merge, this is just for testing]
=> chore: Add tx retry mechanism

.github/actions/build-docker/action.yml, .github/actions/meteor-build/action.yml, .github/actions/setup-node/action.yml, .github/workflows/ci-code-check.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci-test-unit.yml, .github/workflows/ci.yml, .github/workflows/new-release.yml, .github/workflows/pr-update-description.yml, .github/workflows/publish-release.yml
=> ci: yarn login

apps/meteor/package.json, yarn.lock
https://rocketchat.atlassian.net/browse/CORE-649
This dep was used by the livestreaming feature which is long time ded
=> chore: Remove `googleapis` package from codebase

.changeset/lazy-icons-draw.md, apps/meteor/app/livechat-enterprise/client/views/livechatSideNavItems.ts, apps/meteor/client/omnichannel/routes.ts, apps/meteor/client/omnichannel/securityPrivacy/SecurityPrivacyPage.tsx, apps/meteor/client/omnichannel/securityPrivacy/SecurityPrivacyRoute.tsx, apps/meteor/ee/app/livechat-enterprise/server/settings.ts, packages/i18n/src/locales/en.i18n.json
Depends on: #32987
TODO:
[SCI-32]
[SCI-32]: https://rocketchat.atlassian.net/browse/SCI-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Omnichannel's security and privacy settings page

apps/meteor/app/apps/server/converters/rooms.js, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
=> feat: add closedBy on apps-engine

apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/AgentsOverview.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ChatsOverview.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ConversationOverview.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/overviews/ProductivityOverview.tsx
Part of https://rocketchat.atlassian.net/browse/CORE-633
=> refactor: Realtime Monitoring Overviews to TS

apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.stories.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterContainer.tsx, apps/meteor/client/views/omnichannel/realTimeMonitoring/counter/CounterRow.tsx
Part of https://rocketchat.atlassian.net/browse/CORE-633
=> refactor: Realtime Monitoring Counters to TS

apps/meteor/client/views/room/body/RetentionPolicyWarning.tsx, apps/meteor/package.json, ee/packages/ui-theming/package.json, packages/fuselage-ui-kit/package.json, packages/gazzodown/package.json, packages/ui-avatar/package.json, packages/ui-client/package.json, packages/ui-composer/package.json, packages/ui-video-conf/package.json, packages/uikit-playground/package.json, yarn.lock
=> regression: Retention policy warning not truncating text

apps/meteor/app/lib/server/lib/notifyUsersOnMessage.ts
If you receive multiple messages on the same DM the counter was not increasing
=> regression: fix subscription counter for DMs

apps/meteor/app/models/client/index.ts, apps/meteor/app/models/client/models/CachedChatRoom.ts, apps/meteor/app/models/client/models/CachedChatSubscription.ts, apps/meteor/app/models/client/models/ChatMessage.ts, apps/meteor/app/models/client/models/ChatRoom.ts, apps/meteor/app/models/client/models/ChatSubscription.ts, apps/meteor/app/models/client/models/Roles.ts, apps/meteor/app/models/client/models/RoomRoles.ts, apps/meteor/app/models/client/models/UserAndRoom.ts, apps/meteor/app/models/client/models/UserRoles.ts, apps/meteor/app/models/client/models/Users.ts
It adds deprecation remarks on Minimongo collections, explaining we're moving away from them. Additionally, it removes an unused collection called `UserAndRoom`.
Motivated by https://github.com/orgs/RocketChat/discussions/32808
=> chore: Add proper deprecation remarks on Minimongo collections

README.md
fix meteor installation link
Previously meteor installation link was giving 404 error.
=> chore: meteor installation link, previously it was giving 404

packages/password-policies/tsconfig.json, packages/uikit-playground/vite.config.ts
=> chore: fix ui-playground build

.github/workflows/ci-preview.yml, .gitignore, _templates/package/new/package.json.ejs.t, apps/uikit-playground/package.json, turbo.json
=> chore: publish preview github pages

.github/actions/meteor-build/action.yml, .github/workflows/ci-test-e2e.yml
=> ci: Include hidden files when uploading artifacts

.changeset/great-humans-live.md, apps/meteor/app/federation/server/hooks/afterUnsetReaction.js
Added a missing await on a hook of afterSetReaction for federation
Separated from #32994
=> fix: Federation callback not awaiting model call

.changeset/cyan-ladybugs-thank.md, apps/meteor/app/lib/client/methods/sendMessage.ts
```
Exception while simulating the effect of invoking 'sendMessage' TypeError: Cannot read properties of undefined (reading 'name')
at eval (useAnalyticsEventTracking.ts:59:43)
at i.runOne (callbacksBase.ts:59:26)
at callbacksBase.ts:68:24
at callbacksBase.ts:76:5
```
=> fix: error on sendmessage stub

apps/meteor/server/models/raw/Users.js
=> feat: added index for user's freeSwitchExtension

apps/meteor/app/utils/rocketchat.info, apps/meteor/package.json, package.json, packages/core-typings/package.json, packages/rest-typings/package.json, yarn.lock
=> Bump rocket.chat to 6.14.0-develop

.gitignore, packages/ui-composer/package.json
=> chore: add ui-composer to storybook

.gitignore, packages/gazzodown/.storybook/main.js, packages/gazzodown/package.json
=> chore: add gazzodown preview

apps/meteor/client/components/MarkdownText.spec.tsx, apps/meteor/client/components/MarkdownText.tsx
[CORE-700](https://rocketchat.atlassian.net/browse/CORE-700)
[CORE-700]: https://rocketchat.atlassian.net/browse/CORE-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: MarkdownText component to parse nested emphasis tokens

apps/meteor/client/views/room/Sidepanel/hooks/useTeamslistChildren.ts
https://rocketchat.atlassian.net/browse/SIDE-201
=> regression: Second sidebar processing loop

apps/meteor/client/providers/AppsProvider/AppsProvider.tsx
- Stop displaying the "Upgrade" option (button and modal) to Premium workspaces when uploading private apps. This should only be presented to CE workspaces (which have a limit of 0 enabled private apps, while Premium workspaces have **-1** specified in their license).
Introduced by #33316
**Current behavior:**
[screen-capture (4).webm](https://github.com/user-attachments/assets/29ae6c06-137d-43a5-8c00-8bef5f113e96)
[PASLR-27](https://rocketchat.atlassian.net/browse/PASLR-27)
[PASLR-27]: https://rocketchat.atlassian.net/browse/PASLR-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Do not display "Upgrade" option to Premium workspaces when uploading private apps

apps/meteor/client/views/room/contextualBar/ExportMessages/ExportMessages.tsx
The translation positional parameter was not handled by i18next, I used `postProcess` to make the interpolation work
https://rocketchat.atlassian.net/browse/CORE-715
=> regression: email subject variable interpolation

apps/meteor/server/lib/i18n.ts
Introduced #33175
[CORE-710](https://rocketchat.atlassian.net/browse/CORE-710)
[CORE-710]: https://rocketchat.atlassian.net/browse/CORE-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: i18n missing fallback language

apps/meteor/ee/server/apps/storage/AppRealStorage.ts, apps/meteor/server/models/raw/AppLogsModel.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v307.ts, packages/apps-engine/src/server/storage/AppMetadataStorage.ts, packages/apps-engine/tests/test-data/storage/storage.ts
- Tag **all** private apps from CE workspaces as `migrated` when moving to 7.0 so that they're exempt from the new CE limitations;
[PASLR-3](https://rocketchat.atlassian.net/browse/PASLR-3)
[PASLR-3]: https://rocketchat.atlassian.net/browse/PASLR-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Tag private apps as migrated (exempt from CE limitations) when moving to the next major

.changeset/olive-dogs-jam.md, apps/meteor/app/api/server/v1/channels.ts, packages/rest-typings/src/v1/channels/channels.ts
Removed deprecated endpoint `channels.images`. Moving forward, use `rooms.images` endpoint.
[CORE-405](https://rocketchat.atlassian.net/browse/CORE-405)
[CORE-405]: https://rocketchat.atlassian.net/browse/CORE-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated endpoint channels.images

.changeset/ten-houses-repair.md, apps/meteor/client/hooks/useIsEnterprise.ts, apps/meteor/ee/server/api/licenses.ts, apps/meteor/tests/end-to-end/api/licenses.ts, packages/mock-providers/src/MockedServerContext.tsx, packages/rest-typings/src/v1/licenses.ts
Removed deprecated endpoints `licenses.isEnterprise` and `licenses.get`. Moving forward use the endpoint `licenses.info.`
[CORE-407](https://rocketchat.atlassian.net/browse/CORE-407)
[CORE-396](https://rocketchat.atlassian.net/browse/CORE-396)
[CORE-407]: https://rocketchat.atlassian.net/browse/CORE-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated endpoints licenses.isEnterprise and licenses.get

.changeset/sixty-moons-walk.md, apps/meteor/app/livechat/imports/server/rest/inquiries.ts, apps/meteor/tests/end-to-end/api/livechat/05-inquiries.ts, packages/rest-typings/src/v1/omnichannel.ts
Removed deprecated `livechat/inquiries.queued` endpoint. Moving forward use the `livechat/inquiries.queuedForUser` endpoint.
[CORE-404](https://rocketchat.atlassian.net/browse/CORE-404)
[CORE-404]: https://rocketchat.atlassian.net/browse/CORE-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated endpoint livechat/inquiries.queued

.changeset/tender-cheetahs-teach.md, apps/meteor/client/views/admin/rooms/RoomsTableFilters.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.spec.tsx, packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustomList.tsx
This PR addresses an issue where the "Filter by room type" option was incorrectly selectable in the Workspace -> Rooms filter. It should only be a title, not a filterable option. Selecting it results in no results being displayed.
1. Go to Workspace → Rooms
2. Click on “All rooms” selector
3. Select the option “Filter by room type”
[CORE-709](https://rocketchat.atlassian.net/browse/CORE-709)
[CORE-709]: https://rocketchat.atlassian.net/browse/CORE-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: "Filter by room type" selectable in Rooms filter

apps/meteor/.gitignore, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, yarn.lock
`pm2` was used in the early days of microservices to help bringing all services up. this is now achieved using `turbo` so `pm2` can be removed.
[ARCH-1288]
[ARCH-1288]: https://rocketchat.atlassian.net/browse/ARCH-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove pm2 dependency

packages/fuselage-ui-kit/package.json, yarn.lock
=> chore: publish @rocket.chat/fuselage-ui-kit storybook preview

packages/fuselage-ui-kit/package.json, yarn.lock
=> regression: fix preview 

packages/i18n/src/locales/se.i18n.json
=> chore: remove unused translations

apps/meteor/server/startup/migrations/v310.ts
=> chore: Fix incorrect version specified in migration 310

apps/meteor/package.json, ee/apps/omnichannel-transcript/package.json, ee/apps/queue-worker/package.json, ee/packages/pdf-worker/jest.config.ts, ee/packages/pdf-worker/package.json, yarn.lock
=> chore: bump `@react-pdf/renderer`

packages/i18n/src/index.mjs, packages/i18n/src/index.spec.mjs
=> chore: Add `force` option to `rmSync` call

.github/workflows/ci.yml
=> ci: add restore cache for `deploy-preview`

apps/meteor/app/2fa/server/code/EmailCheck.ts, apps/meteor/app/2fa/server/functions/resetTOTP.ts, apps/meteor/app/livechat/server/api/v1/room.ts, apps/meteor/server/features/EmailInbox/EmailInbox_Incoming.ts, apps/meteor/server/features/EmailInbox/EmailInbox_Outgoing.ts, apps/meteor/server/lib/resetUserE2EKey.ts, apps/meteor/server/services/omnichannel-analytics/service.ts
=> refactor(i18n): Use i18next API to get a fixed t-function

apps/meteor/client/omnichannel/units/UnitsTable.tsx
=> chore!: make livechat units table component stop to use fields query param

scripts/fossify.ts
=> chore: replace fs+promisify with fs/promises

apps/meteor/app/livechat/server/api/v1/contact.ts
=> fix: contacts.get endpoint returning a successful response even if the contact is not found

apps/meteor/app/livechat/server/hooks/saveContactLastChat.ts, apps/meteor/server/models/raw/LivechatContacts.ts, apps/meteor/tests/end-to-end/api/livechat/contacts.ts, packages/core-typings/src/ILivechatContact.ts, packages/model-typings/src/models/ILivechatContactsModel.ts
=> feat: last chat on channels

packages/core-typings/src/license/LicenseModule.ts
=> chore: add single contact license

apps/meteor/client/providers/UserProvider/UserProvider.tsx
[CORE-735](https://rocketchat.atlassian.net/browse/CORE-735)
[CORE-735]: https://rocketchat.atlassian.net/browse/CORE-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: prevent ui from blink login page during reconnection

apps/meteor/ee/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/tests/end-to-end/api/livechat/09-visitors.ts
=> chore: fix CI tests

apps/meteor/tests/e2e/account-forgetSessionOnWindowClose.spec.ts
Skipping flaky test related to Accounts_ForgetUserSessionOnWindowClose setting, to unblock all PRs and CI.
Will fix this test ASAP.
=> chore: Skip Accounts_ForgetUserSessionOnWindowClose E2E test

packages/livechat/package.json, packages/livechat/webpack.config.ts, yarn.lock
=> chore: bump postcss-loader

apps/meteor/server/models/raw/BaseRaw.ts
=> chore: catch index creation errors

apps/meteor/ee/server/apps/storage/AppRealStorage.ts
`appStorage.update` is used by migrations and sometimes can update the wrong records, for example when there are multiple records with same `id`
=> chore: make sure appStorage.update updates the correct record

apps/meteor/ee/server/apps/orchestrator.js, packages/apps-engine/src/server/AppManager.ts
=> fix: stop app propagation during startup

apps/meteor/ee/server/apps/orchestrator.js, apps/meteor/ee/server/startup/apps/trialExpiration.ts
- Disable all marketplace apps on license removal or downgrade
This behavior has been incorrectly removed by #33439
**Demo:**
[screen-capture (6).webm](https://github.com/user-attachments/assets/d3fc81d8-c6d9-41c9-802d-ebc70f324483)
[PASLR-33](https://rocketchat.atlassian.net/browse/PASLR-33)
[PASLR-33]: https://rocketchat.atlassian.net/browse/PASLR-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Disable marketplace apps on license removal or downgrade

apps/meteor/app/importer/server/classes/converters/UserConverter.ts, apps/meteor/app/importer/server/classes/converters/generateTempPassword.ts, apps/meteor/tests/unit/app/importer/server/userConverter.spec.ts
=> chore: fix failing CI tests

apps/meteor/app/livechat/server/lib/Contacts.ts, packages/rest-typings/src/v1/omnichannel.ts
Adds a new property to remove conflicting fields. The `wipeConflicts: true` should be passed when the update are being performed to solve all conflicts.
=> feat: erase conflict on update

apps/meteor/ee/app/livechat-enterprise/server/api/contacts.ts
Remove unused `contactId` property from `block`/`unblock` endpoint
=> chore: remove unused property

apps/meteor/app/importer-omnichannel-contacts/server/index.ts
=> chore: enable contact importer only after enabling the SCI feature

apps/meteor/app/api/server/helpers/parseJsonQuery.ts, apps/meteor/app/api/server/v1/channels.ts, apps/meteor/tests/end-to-end/api/channels.ts, packages/rest-typings/src/v1/channels/ChannelsOnlineProps.ts, packages/rest-typings/src/v1/channels/channels.ts
=> chore!: remove query field on online channels listing

.yarn/patches/mongodb-npm-4.17.2-40d1286d70.patch, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/account-service/package.json, ee/apps/authorization-service/package.json, ee/apps/ddp-streamer/package.json, ee/apps/omnichannel-transcript/package.json, ee/apps/presence-service/package.json, ee/apps/queue-worker/package.json, ee/apps/stream-hub-service/package.json, ee/packages/omnichannel-services/package.json, ee/packages/presence/package.json, package.json, packages/agenda/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/cron/package.json, packages/instance-status/package.json, packages/model-typings/package.json, packages/rest-typings/package.json, packages/ui-contexts/package.json, yarn.lock
=> chore: patches mongodb to make ts task less expensive

apps/meteor/ee/app/livechat-enterprise/server/settings.ts, apps/meteor/ee/server/configuration/contact-verification.ts, apps/meteor/ee/server/configuration/index.ts, apps/meteor/ee/server/settings/contact-verification.ts
[SCI-103]
[SCI-103]: https://rocketchat.atlassian.net/browse/SCI-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: create SCI settings regardless of license status

apps/meteor/app/importer/server/classes/converters/ContactConverter.ts
=> fix: imported contacts being flagged as unknown

apps/meteor/app/apps/server/bridges/contact.ts, packages/apps-engine/src/definition/accessors/IContactRead.ts, packages/apps-engine/src/server/accessors/ContactRead.ts, packages/apps-engine/src/server/bridges/ContactBridge.ts, packages/apps-engine/tests/test-data/bridges/contactBridge.ts
=> chore: change method call to get by visitor

apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ContactInfo.tsx, apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoDetails/ContactInfoDetailsEntry.tsx
=> chore: Missing text truncation in contact info

apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoHistory/ContactInfoHistoryItem.tsx
=> chore: Missing history item verified icon

apps/meteor/client/components/GenericModal/GenericModal.tsx, apps/meteor/client/omnichannel/additionalForms/ContactManagerInput.tsx, apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ContactInfo.tsx, apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ReviewContactModal.tsx, apps/meteor/client/views/omnichannel/contactInfo/EditContactInfo.tsx, packages/i18n/src/locales/en.i18n.json
=> feat: Omnichannel contacts conflicts

apps/meteor/ee/server/settings/contact-verification.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
=> chore: change default value for verification

.github/workflows/ci.yml
=> ci: don't run workflow when docs are updated

.github/actions/build-docker/action.yml, .github/workflows/ci.yml
=> ci: cache `matrix-rust-sdk-crypto-nodejs`

apps/meteor/ee/app/license/server/index.ts, apps/meteor/ee/app/license/server/startup.ts
=> regression: server randomly failing on startup

apps/meteor/client/meteorOverrides/ddpOverREST.ts
=> regression: subscriptions not being queued during reconnection

apps/meteor/app/api/server/v1/roles.ts, apps/meteor/app/authorization/server/methods/deleteRole.ts, apps/meteor/app/importer-pending-avatars/server/PendingAvatarImporter.ts, apps/meteor/app/lib/server/functions/updateGroupDMsName.ts, apps/meteor/app/lib/server/methods/leaveRoom.ts, apps/meteor/app/slashcommands-inviteall/server/server.ts, apps/meteor/ee/server/configuration/videoConference.ts, apps/meteor/server/methods/browseChannels.ts, apps/meteor/server/methods/removeRoomOwner.ts, apps/meteor/server/methods/removeUserFromRoom.ts, apps/meteor/server/methods/requestDataDownload.ts, apps/meteor/server/models/raw/ExportOperations.ts, apps/meteor/server/models/raw/Roles.ts, apps/meteor/server/models/raw/Rooms.ts, apps/meteor/server/models/raw/Subscriptions.ts, apps/meteor/server/models/raw/Users.js, apps/meteor/server/startup/initialData.js, apps/meteor/tests/unit/server/startup/initialData.tests.ts, packages/model-typings/src/models/IExportOperationsModel.ts, packages/model-typings/src/models/IRolesModel.ts, packages/model-typings/src/models/IRoomsModel.ts, packages/model-typings/src/models/ISubscriptionsModel.ts, packages/model-typings/src/models/IUsersModel.ts, yarn.lock
2/3
https://rocketchat.atlassian.net/browse/CORE-750
=> chore: Replace `cursor.count` with `countDocuments` or `estimatedDocumentCount`

_templates/service/new/service.ejs.t, apps/meteor/server/database/utils.ts, apps/meteor/server/tracing.ts, ee/apps/account-service/src/service.ts, ee/apps/authorization-service/src/service.ts, ee/apps/ddp-streamer/src/service.ts, ee/apps/omnichannel-transcript/src/service.ts, ee/apps/presence-service/src/service.ts, ee/apps/queue-worker/src/service.ts, ee/apps/stream-hub-service/src/service.ts, packages/core-services/src/lib/mongo.ts, packages/tracing/src/index.ts, packages/tracing/src/traceDatabaseCalls.ts
=> regression: init db tracing within tracing package

apps/meteor/client/views/omnichannel/directory/contexts/ChatsContext.ts, apps/meteor/client/views/omnichannel/directory/hooks/useDisplayFilters.ts
[SCI-95]
[SCI-95]: https://rocketchat.atlassian.net/browse/SCI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Tag's `Chip` not being displayed correctly

apps/meteor/client/components/FilterByText.tsx, apps/meteor/client/omnichannel/businessHours/BusinessHoursTable.tsx, apps/meteor/client/omnichannel/monitors/MonitorsTable.tsx, apps/meteor/client/omnichannel/slaPolicies/SlaTable.tsx, apps/meteor/client/omnichannel/tags/TagsTable.tsx, apps/meteor/client/omnichannel/units/UnitsTable.tsx, apps/meteor/client/views/admin/customEmoji/CustomEmoji.tsx, apps/meteor/client/views/admin/customSounds/CustomSoundsTable/CustomSoundsTable.tsx, apps/meteor/client/views/admin/customUserStatus/CustomUserStatusTable/CustomUserStatusTable.tsx, apps/meteor/client/views/admin/deviceManagement/DeviceManagementAdminTable/DeviceManagementAdminTable.tsx, apps/meteor/client/views/admin/integrations/IntegrationsTable.tsx, apps/meteor/client/views/admin/moderation/ModerationConsoleTable.tsx, apps/meteor/client/views/admin/moderation/UserReports/ModConsoleUsersTable.tsx, apps/meteor/client/views/admin/moderation/helpers/ModerationFilter.tsx, apps/meteor/client/views/directory/hooks/useDirectoryQuery.ts, apps/meteor/client/views/directory/tabs/channels/ChannelsTable/ChannelsTable.tsx, apps/meteor/client/views/directory/tabs/teams/TeamsTable/TeamsTable.tsx, apps/meteor/client/views/directory/tabs/users/UsersTable/UsersTable.tsx, apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx, apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx, apps/meteor/client/views/omnichannel/agents/AgentsTable/AgentsTable.tsx, apps/meteor/client/views/omnichannel/agents/hooks/useQuery.ts, apps/meteor/client/views/omnichannel/customFields/CustomFieldsTable.tsx, apps/meteor/client/views/omnichannel/departments/DepartmentsTable/DepartmentsTable.tsx, apps/meteor/client/views/omnichannel/directory/calls/CallTable.tsx, apps/meteor/client/views/omnichannel/directory/chats/ChatTable.tsx, apps/meteor/client/views/omnichannel/directory/contacts/ContactTable.tsx, apps/meteor/client/views/omnichannel/managers/ManagersTable.tsx, apps/meteor/client/views/room/webdav/WebdavFilePickerModal/WebdavFilePickerModal.tsx
Currently `FilterByText` has an unnecessary internal state that blocks us when we want to modify the current value of the input field in parents components. So, this change aims to add this flexibility to manipulate the input's value
=> chore: Removes `FilterByText` internal state

apps/meteor/client/views/omnichannel/contactHistory/MessageList/ContactHistoryMessagesList.tsx
[SCI-96]
[SCI-96]: https://rocketchat.atlassian.net/browse/SCI-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: `ContactHistoryMessagesList` calling endpoint exhaustively

apps/meteor/client/views/omnichannel/directory/chats/ChatsTable/ChatsTableFilter.tsx, apps/meteor/client/views/omnichannel/directory/contexts/ChatsContext.ts, apps/meteor/client/views/omnichannel/directory/providers/ChatsProvider.tsx
[SCI-125]
[SCI-125]: https://rocketchat.atlassian.net/browse/SCI-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Move focus to text input when removing filter

apps/meteor/app/livechat/server/lib/contacts/getContactHistory.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/tests/end-to-end/api/livechat/contacts.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
[SCI-135]
[SCI-135]: https://rocketchat.atlassian.net/browse/SCI-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: return only closed chats on history

apps/meteor/client/views/omnichannel/contactInfo/tabs/ContactInfoHistory/ContactInfoHistoryItem.tsx
[SCI-121]
[SCI-121]: https://rocketchat.atlassian.net/browse/SCI-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Missing closing chat message

packages/i18n/src/locales/en.i18n.json
- Change `AI Actions` -> `AI actions`
- [RCAI-28]
[RCAI-28]: https://rocketchat.atlassian.net/browse/RCAI-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: correct capitalization of "AI Actions"

apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
The marketplace page was not following the guidelines of the `<Page>` component, when we moved some components around, it caused a visual bug. This PR only fixes the visual bug, a proper refactor of the structure will be done in develop
[PASLR-37](https://rocketchat.atlassian.net/browse/PASLR-37)
[PASLR-37]: https://rocketchat.atlassian.net/browse/PASLR-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Marketplace page padding issue

README.md
- Updated the Node.js version in the README's "Local Development" (Prerequisites) section from 14.x (LTS) to 20.x (LTS) version.
- Added a link to the [official Node.js download page](https://nodejs.org/dist/latest-v20.x/) for easy access to the current LTS version.
Closes #33803
=> docs: Update Node.js Version to 20.x (LTS) in Development Environment Setup Instructions

apps/meteor/server/settings/retention-policy.ts, apps/meteor/server/startup/migrations/v319.ts, apps/meteor/server/startup/migrations/xrun.ts
Removes "soft" migration added here: https://github.com/RocketChat/Rocket.Chat/pull/32425/files#diff-d2a5af684ab8c456c39979a1bf9497783b7929d797fafca29ea6fdadde25c8c2
=> chore!: Remove old retention maxAge settings

apps/meteor/app/2fa/server/loginHandler.ts, apps/meteor/app/google-oauth/server/index.js
[CORE-772](https://rocketchat.atlassian.net/browse/CORE-772)
[CORE-772]: https://rocketchat.atlassian.net/browse/CORE-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix Google OAuth

apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx, packages/mock-providers/src/MockedAppRootBuilder.tsx
[SIDE-218](https://rocketchat.atlassian.net/browse/SIDE-218)
[SIDE-218]: https://rocketchat.atlassian.net/browse/SIDE-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: add `useRoomList` tests

apps/meteor/client/views/marketplace/AppsPage/PrivateEmptyStateUpgrade.tsx, apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
Restores a button to the header that was removed by accident on a rebase, also restores the icon to the other upgrade button
[PASLR-38](https://rocketchat.atlassian.net/browse/PASLR-38)
On a community workspace (no premium) and no private apps installed:
- Go to marketplace/private/
- you should see a empty state with a upgrade button
- the same button should exist on the empty state and the header
[PASLR-38]: https://rocketchat.atlassian.net/browse/PASLR-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix private apps upgrade buttons

apps/meteor/app/threads/server/functions.ts
regression originated from this PR: https://github.com/RocketChat/Rocket.Chat/pull/33026
The thread followers was being called before updating the replies, causing the thread unread counter to do not update on the first reply
https://rocketchat.atlassian.net/browse/CORE-785
=> regression: thread unread count

.github/workflows/ci.yml
=> ci: fix image publish

apps/meteor/client/sidebar/sections/AirGappedRestrictionBanner/AirGappedRestrictionWarning.tsx, packages/i18n/src/locales/en.i18n.json
https://rocketchat.atlassian.net/browse/AIR-15
=> regression: adapt text to match the designs

apps/meteor/server/email/IMAPInterceptor.ts
backport from https://github.com/RocketChat/Rocket.Chat/pull/33724
=> chore: handle imap errors

apps/meteor/server/routes/avatar/utils.spec.ts, apps/meteor/server/routes/avatar/utils.ts
Introduced here: https://github.com/RocketChat/Rocket.Chat/pull/33480
[CORE-791](https://rocketchat.atlassian.net/browse/CORE-791)
[CORE-791]: https://rocketchat.atlassian.net/browse/CORE-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fallback avatars provided with incorrect size if size parameter not in the query

apps/meteor/ee/server/patches/mergeContacts.ts, apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/mergeContacts.spec.ts
Update rooms to associate with the new merged contact
[SCI-140]
[SCI-140]: https://rocketchat.atlassian.net/browse/SCI-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update contacts rooms

apps/meteor/app/apps/server/converters/rooms.js, packages/apps-engine/src/definition/livechat/ILivechatRoom.ts
=> fix: apps-engine room converter dropping contactId attribute

apps/meteor/package.json, yarn.lock
=> regression: revert mp3-encoder bump

apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx, apps/meteor/client/sidebarv2/RoomList/SidebarItemTemplateWithData.tsx, apps/meteor/client/views/room/Sidepanel/hooks/useItemData.tsx
improve accessibility of sidebar unread badges
- `role-'status'`
=> chore: improve unread badges a11y

apps/meteor/server/startup/serverRunning.js
=> chore: improve mongo deprecation message

.github/actions/build-docker/action.yml, .github/workflows/ci-test-e2e.yml, .github/workflows/ci.yml
[ARCH-1317]
[ARCH-1317]: https://rocketchat.atlassian.net/browse/ARCH-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: skip docker login for dependabot

apps/meteor/server/models/raw/LivechatContacts.ts
Fixes the query that checks if the current channel is blocked, which would always return true if at least one channel was blocked.
[SCI-146]
[SCI-146]: https://rocketchat.atlassian.net/browse/SCI-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: check if the current channel is blocked

.changeset/thin-dryers-grow.md, .changeset/weak-moons-battle.md, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, ee/apps/ddp-streamer/package.json, ee/packages/presence/package.json, packages/apps/package.json, packages/core-services/package.json, packages/core-typings/package.json, packages/fuselage-ui-kit/package.json, packages/rest-typings/package.json, yarn.lock
- **fix: engine restart process for Deno used wrong status RocketChat/Rocket.Chat#33865**
- **fix: deno runtime controller not handling undefined child process reference correctly RocketChat/Rocket.Chat#33494**
- **Add reason field to restart logs**
=> fix: apps-engine runtime fixes

packages/fuselage-ui-kit/src/contexts/SurfaceContext.ts, packages/fuselage-ui-kit/src/surfaces/index.ts
=> feat(fuselage-ui-kit): export SurfaceRender to allow custom surfaces

.changeset/friendly-ravens-teach.md, apps/meteor/client/sidebarv2/RoomList/RoomList.tsx, apps/meteor/client/sidebarv2/RoomList/RoomListCollapser.tsx, apps/meteor/client/sidebarv2/hooks/useRoomList.spec.tsx, apps/meteor/client/sidebarv2/hooks/useRoomList.ts, apps/meteor/tests/e2e/feature-preview.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/page-objects/fragments/index.ts, apps/meteor/tests/e2e/page-objects/fragments/sidebar.ts, apps/meteor/tests/e2e/page-objects/home-channel.ts
[SIDE-179](https://rocketchat.atlassian.net/browse/SIDE-179)
https://github.com/user-attachments/assets/77d265e5-8c74-4e14-a88b-cf7904831ee8
[SIDE-179]: https://rocketchat.atlassian.net/browse/SIDE-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add unread badge to sidebar collapser

apps/meteor/client/views/oauth/components/AuthorizationFormPage.tsx, packages/i18n/src/locales/da.i18n.json, packages/i18n/src/locales/en.i18n.json, packages/i18n/src/locales/fi.i18n.json, packages/i18n/src/locales/hi-IN.i18n.json, packages/i18n/src/locales/it.i18n.json, packages/i18n/src/locales/nn.i18n.json, packages/i18n/src/locales/no.i18n.json, packages/i18n/src/locales/pl.i18n.json, packages/i18n/src/locales/ru.i18n.json, packages/i18n/src/locales/se.i18n.json, packages/i18n/src/locales/sv.i18n.json
This PR updates the authorization message on the OAuth Apps authorization page to make it clearer to users that the app will have full, unrestricted access to their account. The new message explicitly informs users that the app can perform any action on their behalf, emphasizing the importance of authorizing only trusted applications.
[VLN-24](https://rocketchat.atlassian.net/browse/VLN-24)
[CORE-644](https://rocketchat.atlassian.net/browse/CORE-644)
[VLN-24]: https://rocketchat.atlassian.net/browse/VLN-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: change oauth apps authorize page message

.github/workflows/ci.yml
=> ci: publish "official" Docker tag for PRs

apps/meteor/app/api/server/v1/assets.ts, apps/meteor/app/assets/server/assets.ts, apps/meteor/app/assets/server/index.ts
backport from https://github.com/RocketChat/Rocket.Chat/pull/33935
=> refactor: assets methods

apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.spec.tsx, apps/meteor/client/views/room/modals/FileUploadModal/FileUploadModal.tsx
=> regression: Fix file upload modal not receiving focus on description field

apps/meteor/client/components/message/content/ThreadMetrics.tsx, apps/meteor/client/components/message/content/ThreadMetricsFollow.tsx, apps/meteor/client/views/room/contextualBar/Threads/components/ThreadListMessage.tsx
=> regression: Fix lint in ThreadMetrics

apps/meteor/app/livechat/server/lib/contacts/createContact.ts, apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.spec.ts, apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
- Add missing `lastChat` property to contact on visitor migration
[SCI-182]
[SCI-182]: https://rocketchat.atlassian.net/browse/SCI-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `lastChat` property missing on contact migrated from visitor

apps/meteor/server/models/raw/Settings.ts, packages/model-typings/src/models/ISettingsModel.ts
backported from https://github.com/RocketChat/Rocket.Chat/pull/33935
just found the return type is wrong :)
=> chore: fix `Setting.updateValueById` result type

.github/workflows/ci.yml
=> ci: do not rename test container on forks

apps/meteor/client/views/omnichannel/contactInfo/ContactInfo/ContactInfo.tsx
Since we do have an empty state for the history tab, we don't need this verification to show it anymore.
[SCI-177]
[SCI-177]: https://rocketchat.atlassian.net/browse/SCI-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `ContactInfo` should always display history tab

apps/meteor/client/views/marketplace/AppsPage/AppsFilters.tsx, apps/meteor/client/views/marketplace/AppsPage/AppsPageContent.tsx
=> regression: `AppsFilters` text search freezing when typing

apps/meteor/client/views/admin/EditableSettingsContext.ts, apps/meteor/client/views/admin/settings/EditableSettingsProvider.tsx, apps/meteor/client/views/admin/settings/Setting/Setting.tsx, apps/meteor/client/views/admin/settings/hooks/useHasSettingModule.ts
[SCI-180]
[SCI-180]: https://rocketchat.atlassian.net/browse/SCI-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `Setting` not considering license active modules

.changeset/lucky-mirrors-tickle.md, apps/meteor/client/views/omnichannel/appearance/AppearanceFieldLabel.tsx, apps/meteor/client/views/omnichannel/appearance/AppearanceForm.tsx
=> fix: Premium settings using wrong `Tag` variant in Omnichannel

apps/meteor/app/livechat/server/lib/Helper.ts
https://rocketchat.atlassian.net/browse/CORE-809
=> chore: Remove `lowercasename` and `lowercasefname` props from livechat subs

packages/release-action/src/getMetadata.ts, packages/release-action/src/utils.ts
=> ci: Fix `apps-engine` version showing as undefined

apps/meteor/client/views/room/RoomAnnouncement/AnnouncementComponent.tsx, apps/meteor/client/views/room/body/RoomTopic.tsx, packages/ui-client/src/components/RoomBanner/RoomBanner.tsx, packages/ui-client/src/components/RoomBanner/RoomBannerContent.tsx
[SIDE-226](https://rocketchat.atlassian.net/browse/SIDE-226)
[SIDE-226]: https://rocketchat.atlassian.net/browse/SIDE-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add announcement and topic classNames

.changeset/three-dragons-brush.md, .changeset/weak-trees-exercise.md
=> chore: fix changeset bump type

packages/release-action/src/publishRelease.ts
=> ci: set if a release is latest or not

apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.ts, apps/meteor/server/models/raw/LivechatInquiry.ts, apps/meteor/server/services/omnichannel/queue.ts, packages/model-typings/src/models/ILivechatInquiryModel.ts
=> refactor: remove getOmniChatSortQuery dependency from livechat inquiry model

apps/meteor/app/lib/server/functions/createRoom.ts, apps/meteor/server/models/raw/Subscriptions.ts
=> refactor: remove getDefaultSubscriptionPref dep from Subscriptions model

apps/meteor/app/livechat/server/lib/analytics/departments.ts, apps/meteor/app/livechat/server/lib/departmentsLib.ts, apps/meteor/server/models/raw/LivechatDepartment.ts, apps/meteor/server/models/raw/LivechatRooms.ts, apps/meteor/server/models/raw/LivechatVisitors.ts, packages/model-typings/src/models/ILivechatRoomsModel.ts
=> refactor: remove external deps from omni models

apps/meteor/server/models/raw/Imports.ts, packages/model-typings/src/models/IImportsModel.ts
It turns out `invalidateOperationsNotInStatus` is not used anywhere.
=> refactor: remove deps from Imports model

packages/apps-engine/src/server/ProxiedApp.ts, packages/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts
=> chore: fix lint

apps/meteor/app/utils/rocketchat.info, apps/meteor/package.json, package.json, packages/apps-engine/deno-runtime/deno.lock, packages/core-typings/package.json, packages/rest-typings/package.json
=> chore: bump version to 7.3.0-develop

packages/apps-engine/deno-runtime/lib/metricsCollector.ts, packages/apps-engine/deno-runtime/main.ts
Previously metrics were being sent every 5s to the host process via stderr. However, by using the timer functions, the subprocess was prevented from ending after the parent process shutdown because there were still tasks to be handled by the event loop - and the Node process doesn't actually tries to kill the subprocess automatically.
Now, the subprocess will send the metrics whenever the it receives a "ping" from the parent process. Metrics will still be sent via stderr, so it will not depend on the response queue controlling data that goes through stdout. The major change is that, by using a trigger that was already available to the subprocess, we don't keep the event loop live and the process can finish naturally after the stdio is closed by the parent.
=>  regression: interval for metrics kept subprocess alive

apps/meteor/package.json, apps/meteor/server/services/image/service.ts, yarn.lock
=> chore(deps): bump `fastxml`-related dependencies

apps/uikit-playground/package.json, yarn.lock
=> chore(deps): bump vite from 5.4.11 to 5.4.14

apps/meteor/client/views/room/providers/RoomProvider.tsx, apps/meteor/client/views/room/providers/hooks/useRoomQuery.ts
=> chore: Discard stale effect on `RoomProvider`

apps/meteor/client/sidebar/RoomList/useSidebarListNavigation.ts, apps/meteor/client/sidebarv2/RoomList/useSidebarListNavigation.ts, apps/meteor/client/sidebarv2/header/SearchSection.tsx, apps/meteor/client/views/room/hooks/useMessageListNavigation.ts, apps/meteor/package.json, yarn.lock
[ARCH-1333]
[ARCH-1333]: https://rocketchat.atlassian.net/browse/ARCH-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump `react-aria`

apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts, apps/meteor/tests/e2e/threads.spec.ts
It handles two cases were E2E tests might break due to weak locators.
=> test: Minor E2E test adjustments

package.json, yarn.lock
=> chore(deps): Bump turborepo

apps/meteor/ee/app/livechat-enterprise/server/lib/QueueInactivityMonitor.ts, apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/QueueInactivityMonitor.spec.ts
https://rocketchat.atlassian.net/browse/CORE-264
=> test: OmnichannelQueueInactivityMonitor

README.md
Since #34048 , node 22 is the minimum required version.
Attempting to use node 20 as currently suggested by the README:
```bash
% yarn build                                                                     
The current Node version v20.18.2 does not satisfy the required version 22.11.0.
```
As a side note, the README suggests installing Deno 1.x, but it seems the build works just fine if Deno 2.1.9 (latest) is installed. Edit: build works, server runs fine, but the apps-engine unit tests are broken (in Deno 2).
=> docs: update prerequisite to Node 22 in README.md

development/docker-compose-monitoring.yml
=> chore: Set `tempo` version to `2.6.1`

apps/meteor/ee/server/settings/voip.ts, apps/meteor/server/settings/call-center.ts
This PR improves the app's security by removing client-side access to VoIP credentials settings.
[VLN-93](https://rocketchat.atlassian.net/browse/VLN-93)
[VLN-93]: https://rocketchat.atlassian.net/browse/VLN-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Removed client-side access to VoIP credentials settings

apps/meteor/package.json, yarn.lock
Bumps the `@slack/bolt` library to fix CVEs.
[VLN-96](https://rocketchat.atlassian.net/browse/VLN-96)
N/A
Since this library is important to our Slack bridge, we will need QA to test this PR.
[VLN-96]: https://rocketchat.atlassian.net/browse/VLN-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): bump @slack/bolt dependency

apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfPopups/VideoConfPopups.spec.tsx, apps/meteor/tests/mocks/utils/video-conference.ts
=> test: Mocked incoming call causing unit test intermittence

.github/CODEOWNERS
This should have been updated by https://github.com/RocketChat/Rocket.Chat/pull/34154 but it wasn't.. fixing it now.
=> chore: fix models path on codeowner

packages/gazzodown/package.json, yarn.lock
=> chore(deps): bump `katex` version

apps/meteor/package.json, yarn.lock
=> chore(deps): bump `sanitize-html`

.github/actions/build-docker/action.yml
=> ci: update cache to v4 on docker build

apps/meteor/server/ee.ts, apps/meteor/server/foss.ts, apps/meteor/server/main.ts, apps/meteor/startRocketChat.ts, apps/meteor/startRocketChatFOSS.ts, scripts/fossify.ts
Conflicts between the original FOSS script and the node 20 refactor had reintroduced references to EE code on the Rocket.Chat startup process.
=> chore: restore FOSS startup process

apps/meteor/ee/server/services/package.json, apps/meteor/package.json, yarn.lock
https://rocketchat.atlassian.net/browse/VLN-104
=> chore(deps): bump `express` from `4.21.1` to `4.21.2`

apps/meteor/tests/unit/app/e2e/server/functions/resetRoomKey.spec.ts
Problem is that the test was using `new Date` for creating 10 elements, which could in some cases return the same date for multiple items, causing the internal sorting of the function to be unpredictable.
This adds artificial delays to the timestamps so we can guarantee the order.
=> test: Separate dates a bit more on `replicateMongoSlice` tests

packages/fuselage-ui-kit/.storybook/main.ts, packages/fuselage-ui-kit/.storybook/webpackAddon.ts, packages/gazzodown/.storybook/main.ts, packages/gazzodown/.storybook/webpackAddon.ts, packages/ui-composer/.storybook/main.ts, packages/ui-composer/.storybook/webpackAddon.ts
This most likely started happening because of the bump to the Node version. Here's where I found the suggestion on how to fix the issue https://github.com/storybookjs/storybook/issues/30123#issuecomment-2558170086
=> ci: storybook  build-preview breaking

.changeset/bump-patch-1739553292599.md, .changeset/kind-geckos-heal.md, .changeset/silly-shiny-kiwis.md, .changeset/six-deers-dress.md, .github/actions/build-docker/action.yml, _templates/service/new/service.ejs.t, apps/meteor/client/components/dashboards/getClosedPeriod.spec.ts, apps/meteor/client/components/dashboards/periods.ts, apps/meteor/client/omnichannel/reports/utils/formatPeriodRange.ts, apps/meteor/client/views/room/RoomOpenerEmbedded.tsx, apps/meteor/ee/server/startup/index.ts, apps/meteor/tests/end-to-end/api/channels.ts, ee/apps/account-service/src/service.ts, ee/apps/authorization-service/src/service.ts, ee/apps/ddp-streamer/src/service.ts, ee/apps/omnichannel-transcript/src/service.ts, ee/apps/presence-service/src/service.ts, ee/apps/queue-worker/src/service.ts, ee/apps/stream-hub-service/src/service.ts, ee/packages/network-broker/src/index.ts, packages/rest-typings/src/v1/channels/ChannelsListProps.ts, yarn.lock
- Node: `22.11.0`
- Apps-Engine: `1.48.2`
*   ([#35212](https://github.com/RocketChat/Rocket.Chat/pull/35212) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes incorrect start date on omnichannel reports
*   ([#35222](https://github.com/RocketChat/Rocket.Chat/pull/35222) by [@dionisio-bot](https://github.com/dionisio-bot)) Fixes `channels.list` endpoint from rejecting pagination parameters
*   ([#35251](https://github.com/RocketChat/Rocket.Chat/pull/35251) by [@dionisio-bot](https://github.com/dionisio-bot)) fixes an issue with embedded layout rooms displaying as if the user is not part of the room
* …
=> Release 7.3.2

apps/meteor/client/views/account/security/BackupCodesModal.tsx
Adds `CodeSnippet` to keep ui consistency and also replace `Modal` in favor of `GenericModal`
=> chore: Add `CodeSnippet` to `BackupCodesModal`

.changeset/itchy-teachers-jam.md, apps/meteor/client/sidebar/header/UserMenu.tsx, apps/meteor/client/sidebar/header/actions/Administration.tsx, apps/meteor/client/sidebar/header/actions/CreateRoom.tsx, apps/meteor/client/sidebar/header/actions/Sort.tsx
Updating behavior of sidebar in small screen size like smartphone
Before(sorry it's on youtube, because when i upload it here it stucked at uploading state) : 
https://youtu.be/H0HF-9TWgKg
After : 
https://youtu.be/NJZcgi51hWY
Closes #35304
Mentioned in issue
=> fix: sidebar behavior in lower screen size

.changeset/eighty-meals-rule.md, apps/meteor/client/lib/onToggledFeature.ts
Some features were not being available if you changed plans without reseting your server, we probably changed the query key somewhere along the way and forgot to update this one
[CORE-1007](https://rocketchat.atlassian.net/browse/CORE-1007)
1. Start with a CE server
2. Add an enterprise key with the license to audit messages
3. Reload page (this pr still does not change that)
4. Go to audit messages or logs page
5. The page should load
possibly introduced here https://github.com/RocketChat/Rocket.Chat/pull/30948/files#diff-db7592984a0cf1a2169339268af6bd61cb29f62f0173c3b0ea61126613151a0dL9
[CORE-1007]: https://rocketchat.atlassian.net/browse/CORE-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Some EE features not available after changing plans

apps/meteor/client/components/connectionStatus/ConnectionStatusBar.stories.tsx, apps/meteor/client/providers/ConnectionStatusProvider.tsx, packages/mock-providers/src/MockedAppRootBuilder.tsx, packages/ui-contexts/src/ConnectionStatusContext.ts
Added Meteor.isLoggingIn to ConnectionStatusContext/Provider to replace code that still uses Meteor.IsLoggingIn and facilitate a future removal of Meteor
=> chore: Add isLoggingIn to ConnectionStatusContext

apps/meteor/tests/e2e/sidebar.spec.ts
=> test: Intermittent sidebar e2e test

apps/meteor/client/views/room/composer/hooks/useComposerBoxPopupQueries.ts
useQuery results should not be undefined.
This error should no longer appear in the console.
=> chore: ensure `useComposerBoxPopupQueries` returns valid value

apps/meteor/client/components/CustomScrollbars/BaseScrollbars.tsx
introduced here https://github.com/RocketChat/Rocket.Chat/pull/33796
=> regression: Scroll List not visible

apps/meteor/server/startup/watchDb.ts
The boolean was inverted but since disabling DB watchers is only under a environment variable it is not critical because it is not generally available at this point, so I'm considering this a chore.
=> chore: fix healthy logic when db watchers are disabled

apps/meteor/app/api/README.md, apps/meteor/app/api/server/api.ts, apps/meteor/app/api/server/definition.ts
https://rocketchat.atlassian.net/browse/ARCH-1497
https://rocketchat.atlassian.net/browse/ARCH-1498
=> chore: add instructions about open api + deprecations

apps/meteor/client/views/room/body/RoomTopic.spec.tsx, apps/meteor/client/views/room/body/RoomTopic.tsx
Introduced here: #35417
This PR fixes an issue which causes topic to render in DMs in new navigation.
[CORE-1032](https://rocketchat.atlassian.net/browse/CORE-1032)
[CORE-1035]
[CORE-1032]: https://rocketchat.atlassian.net/browse/CORE-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-1035]: https://rocketchat.atlassian.net/browse/CORE-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: topic rendering in DMs in new navigation

.changeset/hungry-wasps-remember.md, apps/meteor/client/views/room/HeaderV2/HeaderSkeleton.tsx, apps/meteor/client/views/room/HeaderV2/RoomHeader.tsx, apps/meteor/tests/e2e/feature-preview.spec.ts, packages/ui-client/src/components/HeaderV2/Header.tsx
- Enable `newNavigation` feature preview
- Open any room
- Should not display the avatar in the room header
[SIDE2-40]
[SIDE2-40]: https://rocketchat.atlassian.net/browse/SIDE2-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Remove room header avatar

ee/packages/license/src/index.ts, ee/packages/license/src/license.ts, ee/packages/license/src/licenseImp.ts
https://rocketchat.atlassian.net/browse/ARCH-1524
Basically, it exposes the license manager interface, allowing its use in dependency injection scenarios.
=> chore: expose `LicenseManagerInterface`

apps/meteor/app/api/server/v1/subscriptions.ts, apps/meteor/app/message-mark-as-unread/server/unreadMessages.ts, apps/meteor/client/components/message/hooks/useMarkAsUnreadMutation.tsx, apps/meteor/client/hooks/menuActions/useToggleReadAction.ts
[ARCH-1527]
[ARCH-1527]: https://rocketchat.atlassian.net/browse/ARCH-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove unreadMessages method usage

apps/meteor/app/livechat/client/collections/LivechatInquiry.ts, apps/meteor/app/livechat/client/lib/stream/queueManager.ts, apps/meteor/client/hooks/useLivechatInquiryStore.ts, apps/meteor/client/providers/OmnichannelProvider.tsx, apps/meteor/client/views/room/Header/Omnichannel/QuickActions/hooks/useQuickActions.tsx, apps/meteor/client/views/room/HeaderV2/Omnichannel/QuickActions/hooks/useQuickActions.tsx
[ARCH-1529](https://rocketchat.atlassian.net/browse/ARCH-1529)
[ARCH-1529]: https://rocketchat.atlassian.net/browse/ARCH-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Replace `LivechatInquiry` collection

apps/uikit-playground/package.json, yarn.lock
https://rocketchat.atlassian.net/browse/VLN-113
=> chore(deps): bump `vite`

apps/meteor/package.json, yarn.lock
https://rocketchat.atlassian.net/browse/VLN-112
=> chore(deps): bump `image-size`

apps/meteor/app/api/server/api.ts, apps/meteor/app/api/server/default/openApi.ts, apps/meteor/app/api/server/definition.ts, apps/meteor/app/api/server/router.ts
https://rocketchat.atlassian.net/browse/ARCH-1520
=> chore: improve api rest class definitions and adjust path

apps/meteor/app/ecdh/Session.ts, apps/meteor/app/file/server/file.server.ts, apps/meteor/app/webdav/server/lib/uploadFileToWebdav.ts, apps/meteor/ee/server/services/package.json, apps/meteor/package.json, apps/meteor/server/lib/dataExport/processDataDownloads.ts, ee/apps/account-service/package.json, ee/apps/authorization-service/package.json, ee/apps/ddp-streamer/package.json, ee/apps/omnichannel-transcript/package.json, ee/apps/presence-service/package.json, ee/apps/queue-worker/package.json, ee/apps/stream-hub-service/package.json, ee/packages/network-broker/package.json, ee/packages/omnichannel-services/package.json, ee/packages/presence/package.json, packages/apps-engine/package.json, packages/message-parser/package.json, packages/peggy-loader/package.json, packages/release-action/package.json, packages/release-changelog/package.json, yarn.lock
https://rocketchat.atlassian.net/browse/ARCH-1533
=> chore: bump node types to 22

apps/meteor/tests/data/livechat/canned-responses.ts, apps/meteor/tests/data/livechat/tags.ts, apps/meteor/tests/end-to-end/api/livechat/15-canned-responses.ts
https://rocketchat.atlassian.net/browse/ARCH-1534
=> test: improve tests to be able to run multiple times

apps/meteor/ee/server/local-services/federation/service.ts, apps/meteor/ee/server/startup/services.ts
https://rocketchat.atlassian.net/browse/ARCH-1554
=> chore(federation): always load endpoints

apps/meteor/app/api/server/v1/custom-user-status.ts, apps/meteor/app/user-status/server/methods/deleteCustomUserStatus.ts, apps/meteor/app/user-status/server/methods/insertOrUpdateUserStatus.ts
https://rocketchat.atlassian.net/browse/ARCH-1557
=> chore: remove custom status meteor calls (server)

apps/meteor/app/api/server/v1/rooms.ts, apps/meteor/app/lib/server/methods/cleanRoomHistory.ts, apps/meteor/app/push-notifications/server/methods/saveNotificationSettings.ts, apps/meteor/server/methods/toggleFavorite.ts, apps/meteor/server/publications/room/index.ts
https://rocketchat.atlassian.net/browse/ARCH-1564
=> chore: remove meteor calls from rooms (server)

apps/meteor/client/components/dashboards/getClosedPeriod.spec.ts, apps/meteor/client/components/dashboards/periods.ts
[ARCH-1566]
[ARCH-1566]: https://rocketchat.atlassian.net/browse/ARCH-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Simplify `getClosedPeriod`

.github/workflows/ci-test-e2e.yml
https://rocketchat.atlassian.net/browse/ARCH-1559
> If a secret has not been set, the return value of an expression referencing the secret (such as ${{ secrets.SuperSecret }} in the example) will be an empty string.
source https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
=> chore: stop reporting outside the main repo

.changeset/tasty-pianos-bathe.md, apps/meteor/app/emoji/client/helpers.ts, apps/meteor/client/providers/EmojiPickerProvider/EmojiPickerProvider.tsx
Introduced here: https://github.com/RocketChat/Rocket.Chat/pull/35605
[CORE-1077](https://rocketchat.atlassian.net/browse/CORE-1077)
[CORE-1077]: https://rocketchat.atlassian.net/browse/CORE-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Quick Reactions missing after refresh

apps/meteor/client/hooks/notification/useNotificationUserCalendar.ts, apps/meteor/client/hooks/notification/useNotifyUser.ts, apps/meteor/client/views/root/AppLayout.tsx, apps/meteor/client/views/root/MainLayout/AuthenticationCheck.tsx, apps/meteor/client/views/root/MainLayout/LoggedInArea.tsx, apps/meteor/client/views/root/hooks/useForceLogout.ts, apps/meteor/client/views/root/hooks/useOTRMessaging.ts, apps/meteor/client/views/root/hooks/useStoreCookiesOnLogin.ts, apps/meteor/client/views/root/hooks/useUpdateVideoConfUser.ts, apps/meteor/client/views/root/hooks/useWebRTC.ts
[ARCH-1556](https://rocketchat.atlassian.net/browse/ARCH-1556)
Create `LoggedInArea` to group hooks that are only supposed to run when user is logged.
- move hooks from `AppLayout` to `LoggedInArea`
- update hooks to receive `user` from parent
[ARCH-1556]: https://rocketchat.atlassian.net/browse/ARCH-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: create `LoggedInArea`

apps/meteor/packages/rocketchat-coverage/.npm/package/npm-shrinkwrap.json, apps/meteor/packages/rocketchat-coverage/package.js, turbo.json
https://rocketchat.atlassian.net/browse/ARCH-1578
---
This pull request updates the Rocket.Chat repository by modifying the `npm-shrinkwrap.json` file in the `rocketchat-coverage` package to use `lockfileVersion 4` and updates several dependencies to their newer versions. Additionally, it updates the Istanbul package versions in the `package.js` file for improved compatibility and security. The changes are made on the `test/coverage` branch and are intended to be merged into the `develop` branch.
=> test: bring back coverage e2e 

apps/meteor/client/components/AutoupdateToastMessage.tsx, apps/meteor/client/hooks/useIdleActiveEvents.ts, apps/meteor/client/hooks/useIdleDetection.ts
refactor needed for: [ARCH-1546](https://rocketchat.atlassian.net/browse/ARCH-1546)
- create `useIdleActiveEvents` that adds listeners for idle and active events
- refactor `useIdleDetection` to only dispatch the idle/active events
[ARCH-1546]: https://rocketchat.atlassian.net/browse/ARCH-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request refactors the idle detection logic in the Rocket.Chat application by splitting it into two separate hooks. The `AutoupdateToastMessage` component is updated to utilize the new `useIdleActiveEvents` hook instead of the previous `useIdleDetection` hook, likely to improve the logic for reloading the page when the user returns from being idle. A new hook, `useIdleActiveEvents`, is …
=> refactor: `useIdleDetection` hooks

apps/meteor/client/providers/EmojiPickerProvider/EmojiPickerProvider.tsx, apps/meteor/client/views/root/MainLayout/LoggedInArea.tsx
[ARCH-1556](https://rocketchat.atlassian.net/browse/ARCH-1556)
[ARCH-1556]: https://rocketchat.atlassian.net/browse/ARCH-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request focuses on updating the `LoggedInArea` component within the Rocket.Chat repository. Specifically, it involves moving the `useCustomEmoji` hook to the `LoggedInArea` component. This change is part of a chore task aimed at improving the organization and functionality of the emoji feature in the application.
- **File Modified**: `apps/meteor/client/views/root/MainLayout/LoggedInArea.tsx`
- Added the `useCustomEmoji` hook to the `LoggedInArea` component.
=> chore: move `useCustomEmoji` call to `LoggedInArea`

apps/meteor/app/api/server/api.ts, apps/meteor/app/api/server/definition.ts
[rocketchat.atlassian.net/browse/ARCH-1485](https://rocketchat.atlassian.net/browse/ARCH-1485)
---
This pull request focuses on enhancing the type definitions and error handling within the Rocket.Chat API. It introduces changes to the `api.ts` file, including improvements to rate limiting options and error handling. In the `definition.ts` file, the TypeScript type definitions are refined, particularly the `InternalError` type, which now includes a generic for more flexible error representation and a constrained status code. Additionally, the `TypedAction` type is updated to incorporate a generic parameter for the `this` context, allowing for greater extensibility and customization in action implementations. These changes aim to improve the robustness and flexibility of the API's type …
=> chore(rest-api): TypedAction/TypedThis types

apps/meteor/app/apps/server/bridges/api.ts, apps/meteor/app/apps/server/bridges/router.spec.ts, apps/meteor/app/apps/server/bridges/router.ts
[rocketchat.atlassian.net/browse/ARCH-1485](https://rocketchat.atlassian.net/browse/ARCH-1485)
This pull request addresses an issue in the Rocket.Chat application where the Apps APIs were not correctly parsing URL-encoded data. The changes are implemented in the `AppApisBridge` class within the `api.ts` file.
- **Middleware Enhancement**: Introduced new middleware routes to handle both private and public API requests.
- **URL-encoded Body Parsing**: Added functionality to parse URL-encoded bodies alongside the existing JSON body parsing. This ensures that API requests with URL-encoded data are correctly processed.
The modification enhances the flexibility and robustness of the API handling within the Rocket.Chat application by supporting multiple content types in API requests. This change …
=> regression: Apps APIs not parsing urlencoded

apps/meteor/client/views/audit/components/SecurityLogsTable.tsx
The entry timestamp was being converted to date twice
[CORE-1094](https://rocketchat.atlassian.net/browse/CORE-1094)
[CORE-1094]: https://rocketchat.atlassian.net/browse/CORE-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix security logs timestamp discrepancy

apps/meteor/client/NavBarV2/NavBarSearch/NavBarSearchListbox.tsx
=> regression: Increase debounce time and add missing margin in `NavBarSearch`

apps/meteor/client/views/audit/components/SecurityLogsTable.tsx
The entry timestamp was being converted to date twice
[CORE-1094](https://rocketchat.atlassian.net/browse/CORE-1094)
[CORE-1094]: https://rocketchat.atlassian.net/browse/CORE-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix security logs timestamp discrepancy (#35865)

apps/meteor/client/sidebar/header/actions/hooks/useAuditItems.tsx
To render the header action for security logs an incorrect permission is used
[CORE-1100](https://rocketchat.atlassian.net/browse/CORE-1100)
[CORE-1100]: https://rocketchat.atlassian.net/browse/CORE-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: wrong permission to display Security_logs item

apps/meteor/client/views/audit/components/SecurityLogsTable.tsx
This reverts commit 9d04feb675b7ef33e915ae94e6061093a6b28766.
---
This pull request reverts the changes made in a previous pull request (#35865) that addressed a timestamp discrepancy in the SecurityLogsTable component. The current change modifies the timestamp format back to a date string format in the `apps/meteor/client/views/audit/components/SecurityLogsTable.tsx` file.
=> regression: revert "regression: fix security logs timestamp discrepancy (#35865)"

apps/meteor/client/lib/actionLinks.ts
[ARCH-1549](https://rocketchat.atlassian.net/browse/ARCH-1549)
[ARCH-1549]: https://rocketchat.atlassian.net/browse/ARCH-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request focuses on refactoring the `actionLinks` module within the Rocket.Chat repository. The changes involve removing the Meteor dependency from the `apps/meteor/client/lib/actionLinks.ts` file. Additionally, the error handling within this module has been simplified. However, there is room for improvement in terms of providing more specific error messages and enhancing type safety. The source branch for this pull request is `refactor/actionLinks`, and it targets the `develop` branch.
=> refactor: remove meteor from `actionLinks`

apps/meteor/tests/e2e/omnichannel/omnichannel-contact-conflict-review.spec.ts
[CTZ-97](https://rocketchat.atlassian.net/browse/CTZ-97)
[CTZ-97]: https://rocketchat.atlassian.net/browse/CTZ-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: Adjusted contact review e2e test to prevent possible flaky behavior

apps/meteor/client/NavBarV2/NavBarSearch/NavBarSearch.tsx, apps/meteor/client/NavBarV2/NavBarSearch/hooks/useSearchClick.ts
Introduced here: #35807
[SIDE2-68]
---
This pull request addresses a regression issue in the Rocket.Chat application where the `NavbarSearch` component was closing its list when clicking on the search field. The changes include the addition of a click handler in the `NavBarSearch.tsx` file to enhance user interaction. Additionally, a new hook, `useSearchClick`, has been introduced to manage the search click functionality and overlay state. These updates aim to improve the search experience in the navigation bar.
[SIDE2-68]: https://rocketchat.atlassian.net/browse/SIDE2-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: `NavbarSearch` closing list when clicking on field

packages/ui-composer/src/MessageComposer/MessageComposerInput.tsx
---
This pull request focuses on improving code maintainability and accessibility within the Rocket.Chat project. It introduces helper functions for generating `aria-describedby` attributes in the `ChangePassword.tsx` file, which helps reduce code duplication. Additionally, in the `PasswordVerifier.tsx` file, the return value is modified to include a hidden span element with a provided id when `passwordVerifications` is empty, instead of returning null. The primary change, as indicated by the pull request title, is in the `MessageComposerInput.tsx` file, where the Box component type is changed from 'label' to 'div'. These changes are aimed at enhancing the overall code structure and accessibility of the application.
=> chore: Change incorrect label tag in `MessageComposerInput`

apps/meteor/app/api/server/router.spec.ts, apps/meteor/app/api/server/router.ts, apps/meteor/jest.config.ts
https://rocketchat.atlassian.net/browse/ARCH-1593
---
This pull request aims to enhance the testing framework for the Rocket.Chat application by focusing on the router's request and response validation. Specifically, it introduces improved error handling within the `apps/meteor/app/api/server/router.ts` file by replacing traditional error throwing with a structured JSON error response, which is particularly beneficial in test environments. Additionally, the Jest configuration file `apps/meteor/jest.config.ts` has been updated to include a `coverageProvider` configuration, which will aid in better test coverage analysis. These changes are proposed from the `test/router` branch to be merged into the `develop` branch.
=> test: Enhance router tests for request and response validation

.github/workflows/ci-deploy-gh-pages.yml, .github/workflows/ci.yml, .github/workflows/new-release.yml, .github/workflows/pr-update-description.yml, .github/workflows/publish-release.yml, .github/workflows/release-candidate.yml, .github/workflows/update-version-durability.yml, apps/meteor/.docker-mongo/Dockerfile, apps/meteor/.docker/Dockerfile.alpine, apps/meteor/.docker/Dockerfile.debian, apps/meteor/.meteor/packages, apps/meteor/.meteor/release, apps/meteor/.meteor/versions, apps/meteor/ee/server/services/Dockerfile, ee/apps/account-service/Dockerfile, ee/apps/authorization-service/Dockerfile, ee/apps/ddp-streamer/Dockerfile, ee/apps/omnichannel-transcript/Dockerfile, ee/apps/presence-service/Dockerfile, ee/apps/queue-worker/Dockerfile, ee/apps/stream-hub-service/Dockerfile, package.json
https://rocketchat.atlassian.net/browse/ARCH-1591
---
This pull request updates the Rocket.Chat repository by bumping the Meteor version to 3.2.2 and the Node.js version to 22.14.0. The changes are applied across various workflow files and Dockerfiles. Specifically, the Node.js version is updated in multiple CI workflow files, including `ci-deploy-gh-pages.yml`, `ci.yml`, `new-release.yml`, `pr-update-description.yml`, `publish-release.yml`, `release-candidate.yml`, and `update-version-durability.yml`. Additionally, the Node.js version is updated in several Dockerfiles, including those located in `apps/meteor/.docker-mongo`, `apps/meteor/.docker/Dockerfile.alpine`, `apps/meteor/.docker/Dockerfile.debian`, and various Dockerfiles within the `ee/apps` directory. The Meteor application also …
=> chore: meteor to 3.2.2 and node to 22.14

apps/meteor/jest.config.ts
While working on issue #35937, I noticed that my tests had no impact on the coverage report. This led me to conclude that something was wrong.
https://rocketchat.atlassian.net/browse/ARCH-1596
---
This pull request updates the Jest configuration in the `apps/meteor/jest.config.ts` file of the Rocket.Chat repository. The changes are aimed at reporting coverage from Meteor unit tests by modifying the coverage path ignore patterns and enabling coverage collection. The source branch for this update is `test/coverage-unit-test`, and it is intended to be merged into the `develop` branch.
=> test: report coverage from meteor unit tests

apps/meteor/app/api/server/middlewares/remoteAddressMiddleware.spec.ts, apps/meteor/app/api/server/middlewares/remoteAddressMiddleware.ts
This pull request enhances the `remoteAddressMiddleware` functionality by adding comprehensive test cases and improving the parsing logic for forwarded IP addresses. The changes ensure better reliability and accuracy when determining the remote address in various scenarios.
* [`apps/meteor/app/api/server/middlewares/remoteAddressMiddleware.spec.ts`](diffhunk://#diff-d007b511132fd599cbbdfa8e3e0a9512146cd9ef5e10f631a6570fff819328c4R1-R131): Added unit tests to validate the behavior of `remoteAddressMiddleware` in scenarios such as handling `x-real-ip`, `x-forwarded-for`, fallback to `socket.remoteAddress`, invalid forwarded count, and missing socket information. These tests improve the middleware's robustness and ensure correct functionality.
* …
=> chore: fix enhance forwarded IPs in `getRemoteAddress` function

apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/hooks.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.ts, apps/meteor/lib/callbacks.ts, apps/meteor/tests/unit/server/livechat/hooks/beforeNewRoom.spec.ts
https://rocketchat.atlassian.net/browse/CTZ-111
---
This pull request refactors the mechanism for augmenting new Omnichannel room data with Service Level Agreement (SLA) and custom fields information in the Rocket.Chat repository. The previous implementation, which used a direct callback, has been replaced with an exported function named `beforeNewRoomPatched`. This function is now applied using the `beforeNewRoom.patch()` method. The refactoring is intended to simplify testing procedures for this enterprise feature. The changes are made in the `apps/meteor/ee/app/livechat-enterprise/server/hooks/beforeNewRoom.ts` file. The source branch for this pull request is `refactor/beforeroom`, and it targets the `develop` branch.
=> refactor: Remove `beforeRoom` callback

apps/meteor/app/livechat/server/hooks/sendToCRM.ts, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/app/livechat/server/lib/hooks.ts, apps/meteor/lib/callbacks.ts
---
This pull request refactors the handling of post-queueing actions in the Rocket.Chat Livechat system. Specifically, it removes the `livechat.roomQueued` callback and introduces a new `afterRoomQueued` function. The `QueueManager.processNewInquiry` method has been updated to execute `afterInquiryQueued` and `afterRoomQueued` concurrently using `Promise.all`, which is intended to enhance performance by parallelizing these asynchronous operations. Additionally, new hook functions have been added to manage queued inquiries and rooms. An import for `afterRoomQueued` has also been included.
=> refactor: Remove `livechat.roomQueued` callback

.changeset/curly-weeks-talk.md, apps/meteor/app/emoji/client/emojiParser.ts, apps/meteor/client/components/message/content/attachments/structure/AttachmentText.tsx, apps/meteor/tests/e2e/messaging.spec.ts, apps/meteor/tests/e2e/page-objects/fragments/home-content.ts, yarn.lock
[SUP-724]
[SUP-724]: https://rocketchat.atlassian.net/browse/SUP-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request addresses an issue in the Rocket.Chat repository where emojis were not being parsed correctly inside code blocks within attachment content when using the `chat.postMessage` API call. The changes involve updating the `emojiParser.ts` file to include emoji handling within CODE elements and refactoring the code to move HTML assignment outside of the conditional block. The source branch for this fix is `fix/attachment-parse-emoji`, and it is targeted to be merged into the `develop` branch.
=> fix: Parsing emojis inside code blocks in attachment content using `chat.postMessage` API call

README.md
[NATIVE-818]
[NATIVE-818]: https://rocketchat.atlassian.net/browse/NATIVE-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This pull request removes the F-Droid app store badge from the README.md file in the RocketChat/Rocket.Chat repository. The Apple App Store and Google Play badges remain unchanged. The changes are made from the `docs.remove-fdroid` branch to the `develop` branch.
=> docs: Remove F-Droid

.changeset/famous-shirts-run.md, apps/meteor/app/theme/client/imports/general/theme_old.css, apps/meteor/app/theme/client/imports/general/variables.css
There are some places on the UI we still need to display the native scrollbar such as the message composer, but the CSS are trying to display an invalid color. This PR aims to fix the color.
- Open any room
- Insert new lines in the message composer
- Check the scrollbar displaying with the proper colors
[CORE-1156]
[CORE-1156]: https://rocketchat.atlassian.net/browse/CORE-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Restore native scrollbar color

apps/meteor/tests/e2e/e2e-encryption.spec.ts
[QA-76](https://rocketchat.atlassian.net/browse/QA-76)
[QA-76]: https://rocketchat.atlassian.net/browse/QA-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(e2e-encryption): dismiss toast to prevent slow run

packages/web-ui-registration/src/components/LoginPoweredBy.tsx
=> chore: Replace outdated `Link` in `LoginPoweredBy`

packages/release-action/src/publishRelease.ts
https://rocketchat.atlassian.net/browse/ARCH-1625
=> ci: merge release branch to master on "cut" action

apps/meteor/client/hooks/useIdleDetection.spec.tsx, apps/meteor/client/hooks/useIdleDetection.ts
=> test: Implement tests for `useIdleDetection` hook

apps/meteor/client/hooks/useIdleConnection.ts
https://rocketchat.atlassian.net/browse/ARCH-1632
in production it's not a big problem, but during testing it makes a significant difference
it also ends up restoring the original behavior (https://github.com/RocketChat/Rocket.Chat/pull/35787)
=> test: Remove `awayOnWindowBlur` option from `useIdleActiveEvents`

.github/workflows/ci.yml
Rocketchatctl and other services use the release service info to determine what versions of Nodejs / mongo etc to install.  Deno has been missing from this leading to invalid versions of deno or not knowing what version to install. This will report the information to the release service so we will have it going forward.
=> chore: Report deno version to release service

apps/meteor/app/autotranslate/client/lib/autotranslate.ts, apps/meteor/app/e2e/client/rocketchat.e2e.room.ts, apps/meteor/app/e2e/client/rocketchat.e2e.ts, apps/meteor/app/models/client/models/CachedChatRoom.ts, apps/meteor/app/models/client/models/CachedChatSubscription.ts, apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.ts, apps/meteor/client/lib/cachedCollections/CachedCollection.ts, apps/meteor/client/lib/cachedCollections/MinimongoCollection.ts, apps/meteor/client/startup/roles.ts, apps/meteor/client/views/room/hooks/useGoToRoom.ts, apps/meteor/client/views/room/providers/hooks/useRoomQuery.ts, packages/mongo-adapter/jest.config.ts, packages/mongo-adapter/package.json, packages/mongo-adapter/src/filter.spec.ts, packages/mongo-adapter/src/filter.ts, yarn.lock
It hides threaded messages from the room list of messages, as expected.
[ARCH-1636](https://rocketchat.atlassian.net/browse/ARCH-1636)
[ARCH-1636]: https://rocketchat.atlassian.net/browse/ARCH-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Threaded messages preview

apps/meteor/app/api/server/ApiClass.ts
While developing a new endpoint with url params (`:id/export-logs` under `/api/apps`), I noticed the type couldn't resolve the `urlParams` property correctly.
Now it does.
=> chore: fix type definition in api methods to properly type urlParams

apps/meteor/client/sidebarv2/RoomList/RoomListFiltersItem.tsx
[SIDE2-54]
[SIDE2-88]
[SIDE2-54]: https://rocketchat.atlassian.net/browse/SIDE2-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE2-88]: https://rocketchat.atlassian.net/browse/SIDE2-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add unread badges in sidebar filters items

.changeset/cuddly-bugs-relax.md, apps/meteor/app/livechat/server/lib/Helper.ts, apps/meteor/app/livechat/server/lib/QueueManager.ts, apps/meteor/app/livechat/server/lib/RoutingManager.ts, apps/meteor/app/livechat/server/lib/routing/External.ts, apps/meteor/ee/app/livechat-enterprise/server/hooks/handleNextAgentPreferredEvents.ts, apps/meteor/tests/data/livechat/department.ts, apps/meteor/tests/data/livechat/users.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
https://rocketchat.atlassian.net/browse/CTZ-210
This should help with some inconsistencies when evaluating this behavior as some places were using it and some others were not.
=> fix: Use `Livechat_enabled_when_agent_idle` settting where it's accepted

apps/meteor/client/lib/cachedCollections/CachedCollection.ts, apps/meteor/client/lib/cachedCollections/Cursor.ts, apps/meteor/client/lib/cachedCollections/DocumentMapStore.ts, apps/meteor/client/lib/cachedCollections/LocalCollection.spec.ts, apps/meteor/client/lib/cachedCollections/LocalCollection.ts, apps/meteor/client/lib/cachedCollections/MinimongoCollection.ts
https://rocketchat.atlassian.net/browse/ARCH-1647
It applies some base-level optimizations for the Minimongo/Zustand adapter.
=> chore: Store optimization

apps/meteor/app/models/client/models/Subscriptions.ts, apps/meteor/client/hooks/useUnread.ts, apps/meteor/client/lib/cachedCollections/DocumentMapStore.ts, apps/meteor/client/lib/cachedCollections/MinimongoCollection.ts
https://rocketchat.atlassian.net/browse/ARCH-1664
It defers and batches the invalidation of Minimongo queries.
=> chore: Schedule and defer some query recomputations

apps/meteor/tests/end-to-end/api/livechat/12-priorites.ts
https://rocketchat.atlassian.net/browse/CTZ-231
=> test: Flaky priorities API test due to name collisions

apps/meteor/client/views/navigation/providers/RoomsNavigationProvider.tsx
[SIDE2-82](https://rocketchat.atlassian.net/browse/SIDE2-82)
[SIDE2-82]: https://rocketchat.atlassian.net/browse/SIDE2-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Teams not showing up on mentions sidebar filter

apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v319.ts
https://rocketchat.atlassian.net/browse/ARCH-1685
introduced here: https://github.com/RocketChat/Rocket.Chat/pull/36259
=> chore: remove migration 319

apps/meteor/app/statistics/server/lib/getEEStatistics.ts, apps/meteor/server/startup/migrations/index.ts, apps/meteor/server/startup/migrations/v319.ts, packages/core-typings/src/IStats.ts, packages/models/src/models/LivechatRooms.ts
https://rocketchat.atlassian.net/browse/CTZ-104
=> chore: Remove deprecated `pdfTranscriptRequested` index

packages/apps-engine/src/definition/api/ApiEndpoint.ts
https://rocketchat.atlassian.net/browse/CTZ-243
Caused by https://github.com/RocketChat/Rocket.Chat/pull/36164
=> regression: Apps Engine failing to respond apps' api when app returned no headers

packages/models/src/models/AppLogsModel.ts
Remove index name on the `rocketchat_apps_logs` collection to avoid warnings during the startup on older workspaces.
No functionality changes
=> chore: remove index name to prevent warnings

apps/meteor/app/livechat/server/api/v1/customField.ts, apps/meteor/app/livechat/server/api/v1/visitor.ts, apps/meteor/app/livechat/server/lib/custom-fields.ts, apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts
https://rocketchat.atlassian.net/browse/CTZ-275
Now, it will go for multiple visitor custom fields.
TBD: room custom fields
=> refactor: Set multiple visitor custom fields at once instead of one by one on `custom.fields` endpoint

apps/meteor/server/methods/saveUserProfile.ts
caused after adding the  `getUserInfo`  call
=> regression: await user info retrieval in notifyOnUserChange 

apps/meteor/client/sidebarv2/RoomList/RoomList.tsx, apps/meteor/client/sidebarv2/RoomList/RoomListCollapser.tsx, apps/meteor/client/views/navigation/sidepanel/hooks/useChannelsChildrenList.ts
This PR fixes 2 bugs on the new sidebar
- Sidepanel filters not showing rooms
- Room list groups incorrect expanded state
=> fix: Sidebar groups expanded and filters

apps/meteor/app/api/server/ApiClass.ts, apps/meteor/app/api/server/definition.ts
required changes to prevent cyclic typing references
noticed here: https://github.com/RocketChat/Rocket.Chat/pull/36146 during a new endpoint creation
=> refactor: Enhance API type definitions for route extraction 

apps/meteor/ee/app/livechat-enterprise/server/api/index.ts, apps/meteor/ee/app/livechat-enterprise/server/api/outbound.ts
=> chore(outbound): Endpoint not being imported by code

apps/meteor/client/sidebarv2/RoomList/SidebarItemWithData.tsx, apps/meteor/client/views/navigation/contexts/RoomsNavigationContext.ts, apps/meteor/client/views/navigation/sidepanel/SidePanel.tsx, apps/meteor/client/views/navigation/sidepanel/SidepanelItem/SidepanelItem.tsx
Show parent room tag only for global filters like all, favorites.
[SIDE2-106](https://rocketchat.atlassian.net/browse/SIDE2-106)
[SIDE2-106]: https://rocketchat.atlassian.net/browse/SIDE2-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove parent room tag on room filters

.github/workflows/ci.yml
This always fails for external contributors. While it doesn't block PR merge, it's difficult to see at a glance whether PRs from forks are passing the tests or not.
https://rocketchat.atlassian.net/browse/CORE-1244
=> ci: skip PR preview on forks

apps/meteor/client/lib/cachedCollections/pipe.spec.ts, apps/meteor/client/lib/cachedCollections/pipe.ts
[ARCH-1671](https://rocketchat.atlassian.net/browse/ARCH-1671)
[ARCH-1671]: https://rocketchat.atlassian.net/browse/ARCH-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add date sorting functionality to pipe

packages/ui-contexts/src/hooks/useTranslation.ts
It adds an annotation deprecating `useTranslation` from `@rocket.chat/ui-contexts` in favor of `useTranslation` from `react-i18next`.
[ARCH-1717](https://rocketchat.atlassian.net/browse/ARCH-1717)
[ARCH-1717]: https://rocketchat.atlassian.net/browse/ARCH-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ui-contexts): Deprecate `useTranslation` in favor of `react-i18next` alternative

apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppLogs/Filters/DateTimeModal.tsx
Amends a small issue done in https://github.com/RocketChat/Rocket.Chat/pull/36288
=> chore: Don't use deprecated `Modal` reference

apps/meteor/client/views/room/body/hooks/useUnreadMessages.ts
https://rocketchat.atlassian.net/browse/ARCH-1719
=> fix: do not resub router on message

apps/meteor/ee/server/local-services/instance/service.ts, packages/model-typings/src/models/IInstanceStatusModel.ts, packages/models/src/models/InstanceStatus.ts
=> feat: use change streams to monitor instances

packages/apps-engine/src/definition/outboundComunication/IOutboundCommsProvider.ts
https://rocketchat.atlassian.net/browse/CTZ-228
=> chore: Missing accessor types on definition of app handlers

apps/meteor/client/views/marketplace/AppDetailsPage/tabs/AppStatus/AppStatus.tsx
Restores one of the font colors on the App Status Tag
[ALT-27](https://rocketchat.atlassian.net/browse/ALT-27)
I've not added tests as the status component needs some serious refactoring before we could do snapshot tests for visual regressions. 
[ALT-27]: https://rocketchat.atlassian.net/browse/ALT-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: missing font color in App Status Tag

apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx, apps/meteor/client/hooks/roomActions/useE2EERoomAction.spec.ts, apps/meteor/client/hooks/roomActions/useE2EERoomAction.ts, apps/meteor/client/hooks/useDialModal.tsx, apps/meteor/client/omnichannel/hooks/useOmnichannelPrioritiesMenu.tsx, apps/meteor/client/views/room/contextualBar/AutoTranslate/AutoTranslateWithData.tsx, apps/meteor/client/views/room/modals/E2EEModals/ResetKeysE2EEModal.tsx, apps/meteor/client/views/setupWizard/steps/RegisterServerStep.tsx
[ARCH-1723](https://rocketchat.atlassian.net/browse/ARCH-1723)
[ARCH-1723]: https://rocketchat.atlassian.net/browse/ARCH-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Consume from the `ToastMessageContext`

packages/message-parser/src/grammar.pegjs, packages/message-parser/src/utils.ts, packages/message-parser/tests/timestamp.test.ts
https://rocketchat.atlassian.net/browse/ARCH-1724
Adds the ability to use iso strings on timestamps in the message parser package
=> feat(message-parser): Make timestamp accept ISO time

apps/meteor/app/livechat/server/lib/Helper.ts
=> fix: Change logic on waiting queue

apps/meteor/package.json, apps/uikit-playground/package.json, ee/packages/ui-theming/package.json, packages/fuselage-ui-kit/package.json, packages/gazzodown/package.json, packages/storybook-config/package.json, packages/ui-avatar/package.json, packages/ui-client/package.json, packages/ui-composer/package.json, packages/ui-video-conf/package.json, packages/ui-voip/package.json, packages/web-ui-registration/package.json, yarn.lock
- bump @rocket.chat/fuselage
[release changes](https://github.com/RocketChat/fuselage/releases/tag/%40rocket.chat%2Ffuselage%400.66.0)
- add @rocket.chat/fuselage-forms
[release changes](https://github.com/RocketChat/fuselage/releases/tag/%40rocket.chat%2Ffuselage-forms%400.1.0)
=> chore: bump `fuselage` and add `fuselage-forms`

apps/meteor/client/components/UserAndRoomAutoCompleteMultiple/UserAndRoomAutoCompleteMultiple.spec.tsx
=> test: Fix `UserAndRoomAutoCompleteMultiple.spec.tsx` and improve it

ee/packages/omni-core-ee/jest.config.ts, ee/packages/omni-core-ee/src/isDepartmentCreationAvailable.spec.ts, packages/omni-core/jest.config.ts, packages/omni-core/src/isDepartmentCreationAvailable.spec.ts
[CTZ-288]
[CTZ-288]: https://rocketchat.atlassian.net/browse/CTZ-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: new tests for `isDepartmentCreationAvailable`

apps/meteor/app/authorization/client/hasPermission.ts, apps/meteor/app/authorization/client/hasRole.ts, apps/meteor/app/authorization/client/index.ts, apps/meteor/app/authorization/client/watch.ts, apps/meteor/app/models/client/models/Roles.ts, apps/meteor/app/models/client/models/Subscriptions.ts, apps/meteor/app/models/client/models/Users.ts, apps/meteor/app/ui/client/lib/UserAction.ts, apps/meteor/app/utils/client/lib/getUserPreference.ts, apps/meteor/app/webrtc/client/WebRTCClass.ts, apps/meteor/client/lib/cachedCollections/DiffSequence.ts, apps/meteor/client/lib/cachedCollections/common.ts, apps/meteor/client/lib/cachedCollections/index.ts, apps/meteor/client/lib/normalizeThreadTitle.ts, apps/meteor/client/lib/objectUtils.ts, apps/meteor/client/lib/rooms/roomTypes/direct.ts, apps/meteor/client/lib/userData.ts, apps/meteor/client/meteorOverrides/userAndUsers.ts, apps/meteor/client/providers/AuthorizationProvider.tsx, apps/meteor/client/providers/UserProvider/UserProvider.tsx, apps/meteor/client/providers/UserProvider/hooks/useUpdateAvatar.ts, packages/core-typings/src/IUser.ts, packages/mock-providers/src/MockedAppRootBuilder.tsx, packages/ui-contexts/src/AuthorizationContext.ts, yarn.lock
[ARCH-1670](https://rocketchat.atlassian.net/browse/ARCH-1670)
Replace the Minimongo collection for Users with the Zustand store.
[ARCH-1670]: https://rocketchat.atlassian.net/browse/ARCH-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: `Users` store

apps/meteor/client/sidebarv2/RoomList/RoomListFilters.tsx, apps/meteor/client/sidebarv2/RoomList/TeamCollabFilters.tsx, apps/meteor/client/views/navigation/contexts/RoomsNavigationContext.ts, apps/meteor/client/views/navigation/sidepanel/SidePanelRouter.tsx, apps/meteor/client/views/navigation/sidepanel/tabs/SidePanelDiscussions.tsx, apps/meteor/client/views/navigation/sidepanel/tabs/SidePanelQueue.tsx, apps/meteor/client/views/navigation/sidepanel/tabs/SidepanelOnHold.tsx
=> fix(sidebarV2): Hide filters based on settings and permissions

.changeset/seven-gorillas-sell.md, apps/meteor/client/hooks/roomActions/useAppsRoomStarActions.tsx, apps/meteor/client/hooks/roomActions/useVideoCallRoomAction.tsx, apps/meteor/client/hooks/roomActions/useVoiceCallRoomAction.tsx
Changes the order of the featured room toolbox actions.
[CORE-1240](https://rocketchat.atlassian.net/browse/CORE-1240)
Not sure if tests are applicable in this case
[CORE-1240]: https://rocketchat.atlassian.net/browse/CORE-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: missing featured RoomToolBoxAction order

.github/CODEOWNERS
Most of the REST API files are under `apps/meteor/app/api/server/*` and the backend team was not owner of it.
=> chore: give backend more ownership

apps/meteor/app/livechat/server/api/v1/agent.ts, apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts, apps/meteor/tests/end-to-end/api/livechat/01-agents.ts, apps/meteor/tests/end-to-end/api/livechat/03-custom-fields.ts, apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
related to: https://github.com/RocketChat/Rocket.Chat/pull/36587
This should help reduce the flakyness of other tests as it will make the queue has less things (or none) to process
=> test: Close rooms when used on tests

apps/meteor/app/api/server/api.helpers.ts, apps/meteor/app/api/server/definition.ts
https://rocketchat.atlassian.net/browse/ARCH-1738
=> chore: `parseDeprecation` showing route as undefined

.changeset/strong-files-work.md, apps/meteor/client/views/room/body/hooks/useRestoreScrollPosition.ts
This reverts commit 0ab304de5fd9e34133ae95e546bacb67270ae814.
The issue is being caused by another function accessing the messagelist ref, the correct solution will be more complex, reverting this commit for now
=> regression: Revert "fix: incorrect scroll position when switching DMs (#36524)"

.changeset/thick-ravens-flow.md, apps/meteor/app/lib/server/functions/saveUser/validateUserEditing.ts, apps/meteor/tests/e2e/containers/saml/config/simplesamlphp/authsources.php, apps/meteor/tests/e2e/fixtures/userStates.ts, apps/meteor/tests/e2e/saml.spec.ts
https://rocketchat.atlassian.net/browse/SUP-804
=> fix: allow users to set password first time 

apps/meteor/app/ui/client/lib/UserAction.ts
[ARCH-1769](https://rocketchat.atlassian.net/browse/ARCH-1769)
[ARCH-1769]: https://rocketchat.atlassian.net/browse/ARCH-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: fix typing streaming 

apps/meteor/app/ui-utils/client/index.ts, apps/meteor/app/ui-utils/client/lib/mainReady.ts, apps/meteor/client/hooks/useReactiveVar.ts, apps/meteor/client/lib/userData.ts, apps/meteor/client/startup/accounts.ts, apps/meteor/client/views/root/MainLayout/EmbeddedPreload.tsx, apps/meteor/client/views/root/MainLayout/Preload.tsx, apps/meteor/client/views/root/hooks/useMainReady.ts
[ARCH-1770](https://rocketchat.atlassian.net/browse/ARCH-1770)
[ARCH-1770]: https://rocketchat.atlassian.net/browse/ARCH-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Assert readiness in “preload components” without `ReactiveVar`

apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessagePreview/OutboundMessagePreview.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessageWizard/forms/MessageForm.spec.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessageWizard/steps/MessageStep.stories.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessageWizard/steps/RecipientStep.spec.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessageWizard/steps/ReviewStep.stories.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/RecipientSelect.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplateEditor.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplatePlaceholderSelector/TemplatePlaceholderButton.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplatePlaceholderSelector/TemplatePlaceholderInput.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplatePreview.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/definitions/template.ts, apps/meteor/client/components/Omnichannel/OutboundMessage/utils/template.spec.ts, apps/meteor/client/components/Omnichannel/OutboundMessage/utils/template.ts, apps/meteor/tests/mocks/data/outbound-message.ts, packages/i18n/src/locales/en.i18n.json
- Update template parameters structure in preparation for sending the outbound message
- Added support for media type
- Updated component type and format to lowecase
[CTZ-250](https://rocketchat.atlassian.net/browse/CTZ-250)
[CTZ-250]: https://rocketchat.atlassian.net/browse/CTZ-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Outbound message template improvements

apps/meteor/tests/e2e/README.md
=> test: add best practices to README

apps/meteor/client/sidebarv2/RoomList/TeamCollabFilters.tsx, apps/meteor/client/views/navigation/sidepanel/SidePanelRouter.tsx
Introduced here: #36049
[SIDE2-139]
[SIDE2-139]: https://rocketchat.atlassian.net/browse/SIDE2-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Hide mentions filter

.changeset/selfish-dancers-study.md, apps/meteor/ee/app/livechat-enterprise/server/hooks/applyDepartmentRestrictions.ts, apps/meteor/ee/app/livechat-enterprise/server/methods/getUnitsFromUserRoles.ts, apps/meteor/tests/end-to-end/api/livechat/22-monitors.ts
https://rocketchat.atlassian.net/browse/CTZ-308
=> fix: `onlyMyDepartments` not applying to agents

apps/meteor/client/definitions/IRocketChatDesktop.ts, apps/meteor/client/lib/userPresence.ts, apps/meteor/client/main.ts, apps/meteor/client/providers/UserPresenceProvider.tsx, apps/meteor/client/startup/fakeUserPresence.ts, apps/meteor/client/views/room/contextualBar/VideoConference/hooks/useVideoConfOpenCall.spec.tsx
It introduces a fake module mimicking `meteor/rocketchat:user-presence` since the desktop app references it directly. Moreover, it handles the desktop's user presence detection (if available) by itself instead of relying on unsafe injected code.
[ARCH-1780](https://rocketchat.atlassian.net/browse/ARCH-1780)
[ARCH-1780]: https://rocketchat.atlassian.net/browse/ARCH-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression(desktop-app): Removed user presence package dependency

apps/meteor/client/components/Omnichannel/OutboundMessage/utils/template.spec.ts, apps/meteor/client/components/Omnichannel/OutboundMessage/utils/template.ts
=> fix: Template placeholder not being used as fallback when parameter is empty

apps/meteor/client/views/navigation/providers/RoomsNavigationProvider.tsx
[SIDE2-145]
[SIDE2-145]: https://rocketchat.atlassian.net/browse/SIDE2-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: Ignore preference to display favorites filter

apps/meteor/client/components/Omnichannel/OutboundMessage/components/OutboundMessageWizard/forms/MessageForm.spec.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplateSelect.spec.tsx, apps/meteor/client/components/Omnichannel/OutboundMessage/components/TemplateSelect.tsx
[CTZ-193](https://rocketchat.atlassian.net/browse/CTZ-193)
[CTZ-193]: https://rocketchat.atlassian.net/browse/CTZ-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(outbound): Added language description to template select component

.changeset/quiet-spoons-lick.md, apps/meteor/client/views/room/contextualBar/Discussions/DiscussionsList.tsx
Introduced here: #33796
When we did the refactor, `Virtuoso` had a `overflow: hidden`, that was there for an unknown reason and with the implementation of `overlayscrollbars` this prop took an undesirable behavior of hidden the overflow
[CORE-1299]
[CORE-1299]: https://rocketchat.atlassian.net/browse/CORE-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Discussions list not being scrollable

.changeset/beige-seahorses-reply.md, apps/meteor/server/methods/sendConfirmationEmail.ts, packages/web-ui-registration/src/EmailConfirmationForm.tsx, packages/web-ui-registration/src/hooks/useLoginSendEmailConfirmation.ts
Removes the deprecated `sendConfirmationEmail` method
[ARCH-1760](https://rocketchat.atlassian.net/browse/ARCH-1760)
[ARCH-1760]: https://rocketchat.atlassian.net/browse/ARCH-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: remove deprecated `sendConfirmationEmail` method

.changeset/metal-rocks-behave.md, apps/meteor/server/methods/saveUserProfile.ts
Removes deprecated method `saveUserProfile`
[ARCH-1763](https://rocketchat.atlassian.net/browse/ARCH-1763)
[ARCH-1763]: https://rocketchat.atlassian.net/browse/ARCH-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove saveUserProfile deprecated method

.changeset/dull-rabbits-add.md, apps/meteor/app/authorization/server/index.ts, apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
Removes the deprecated `authorization:removeUserFromRole` method
[ARCH-1747](https://rocketchat.atlassian.net/browse/ARCH-1747)
[ARCH-1747]: https://rocketchat.atlassian.net/browse/ARCH-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove deprecated `authorization:removeUserFromRole` method

.changeset/wild-hairs-carry.md, apps/meteor/app/authorization/server/methods/addUserToRole.ts
Removes the deprecated `authorization:addUserToRole` method
[ARCH-1745](https://rocketchat.atlassian.net/browse/ARCH-1745)
[ARCH-1745]: https://rocketchat.atlassian.net/browse/ARCH-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore!: Remove deprecated `authorization:addUserToRole` method

apps/meteor/.storybook/main.ts, apps/meteor/client/views/admin/permissions/PermissionsPage.tsx, apps/meteor/client/views/admin/permissions/PermissionsRouter.tsx, apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.spec.tsx, apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.stories.tsx, apps/meteor/client/views/admin/permissions/PermissionsTable/PermissionsTable.tsx, apps/meteor/client/views/admin/permissions/PermissionsTable/__snapshots__/PermissionsTable.spec.tsx.snap
In order to be able to create snapshot tests for `PermissionsTable` its necessary to decouple it from the permissions page, allowing permissions mocking.
[CORE-1323]
[CORE-1323]: https://rocketchat.atlassian.net/browse/CORE-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Decouple permissions table component from page

.changeset/thick-badgers-grab.md
=> chore: changeset for #36935

ee/packages/federation-matrix/src/FederationMatrix.ts, ee/packages/federation-matrix/src/api/_matrix/send-join.ts, ee/packages/federation-matrix/src/api/_matrix/transactions.ts
=> chore: refactor federation to use eventID branded types
