packages/rocketchat-ui-message/startup/messageBoxActions.js
packages/rocketchat-ui/client/views/app/popover.js

[FIX] Audio message icon

---

packages/rocketchat-channel-settings-mail-messages/server/methods/mailMessages.js

Closes #6179
Fixes an error when forwarding messages to someone with a language set.

[FIX] Fix e-mail message forward

---

tests/chimp-config.js

@RocketChat/core Comment updates.

Updated comments.

---

package-lock.json
packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-lib/server/lib/sendEmailOnMessage.js
packages/rocketchat-livechat/app/package-lock.json

Closes #8568
Now the user will receive emails of DM according user preference/room preference

[FIX] User email settings on DM

---

.circleci/update-releases.sh
.docker/Dockerfile

Update path for s3 redirect in circle ci

---

.circleci/setartname.sh
.docker/Dockerfile
.sandstorm/sandstorm-pkgdef.capnp
.travis/snap.sh
HISTORY.md
README.md
package-lock.json
package.json
packages/rocketchat-lib/rocketchat.info

Bump version to 0.60.0-develop

---

.circleci/setartname.sh
.circleci/update-releases.sh

Fix link to .asc file on S3

---

README.md

Add a few dots in readme.md

---

.circleci/config.yml

Fix CircleCI deploy filter

---

.circleci/config.yml

According to [CircleCI docs](https://circleci.com/docs/2.0/workflows/#git-tag-job-execution) we *must* specify a tag filter for every job :man_facepalming:

Fix tag build

---

.snapcraft/snapcraft.yaml

Fix snap download url

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-livechat/app/package-lock.json
packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] flextab height on smaller screens

---

example-build-run.sh

[FIX] Typo Fix

---

packages/rocketchat-theme/client/imports/forms/tags.css

[FIX] icon padding on Invite Users input

---

.postcssrc
package.json
packages/rocketchat-theme/client/imports/forms/tags.css

[FIX] Missing sidebar footer padding

---

packages/rocketchat-theme/client/imports/forms/tags.css
packages/rocketchat-theme/client/imports/general/base.css
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-theme/server/colors.less
packages/rocketchat-ui/client/lib/readMessages.js

[FIX] Change the unread messages style

---

.meteor/versions

Update [multiple-instance-status package to version 1.1.0](https://github.com/Konecty/meteor-multiple-instances-status/blob/master/HISTORY.md#110-2017-12-05) so we can benefit from the new env vars `MULTIPLE_INSTANCES_PING_INTERVAL` and `MULTIPLE_INSTANCES_EXPIRE`

Update multiple-instance-status package

---

packages/rocketchat-integrations/server/lib/validation.js
packages/rocketchat-reactions/client/init.js

[FIX] Error when saving integration with symbol as only trigger

---

packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js

[FIX] Notification is not sent when a video conference start

---

packages/rocketchat-api/server/api.js

Fix api regression (exception when deleting user)

---

packages/rocketchat-api/server/api.js

@RocketChat/core turns off `prettyJson` if the node environment isn't development.
Closes #9057

Turn off prettyJson if the node environment isn't development

---

packages/rocketchat-theme/client/imports/components/modal/create-channel.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css

Closes #9093
Fixed "Create new Channel" plus (+) button size
Fixed "Create new Channel" scroll
Reduce the size of public/private channels icons on room list

[FIX] Some UI problems on 0.60

---

packages/rocketchat-ui/client/views/app/createChannel.html

[FIX] Creating channels on Firefox

---

packages/rocketchat-file-upload/server/lib/FileUpload.js
packages/rocketchat-importer/server/classes/ImporterBase.js

[FIX] REST API file upload not respecting size limit

---

packages/rocketchat-api/server/v1/channels.js

Fix regression in api channels.members

---

.meteor/versions

Fix: users listed as online after API login

---

packages/rocketchat-ui/client/lib/readMessages.js

Fix: Multiple unread indicators

---

packages/rocketchat-ui/client/lib/RoomManager.js
server/methods/loadHistory.js

[FIX] Do not block room while loading history

---

packages/rocketchat-importer-csv/server/importer.js
packages/rocketchat-importer-hipchat-enterprise/server/importer.js
packages/rocketchat-importer-hipchat/server/importer.js
packages/rocketchat-importer-slack-users/server/importer.js
packages/rocketchat-importer-slack/server/importer.js

[FIX] Importers not recovering when an error occurs

---

packages/rocketchat-ui/client/views/app/modal.js

It makes the `closeOnConfirm` option `true` by default
Closes #9130

Fix: Clear all unreads modal not closing after confirming

---

packages/rocketchat-ui/client/views/app/room.js

Fix: Messages being displayed in reverse order

---

packages/rocketchat-theme/client/imports/general/base.css
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui/client/views/app/modal.js
packages/rocketchat-ui/client/views/app/room.js
tests/chimp-config.js

- Do not change the message size when unread mark shows
- Fix: Date was in front of unread bar
- Fix: Unread bar disappear in certain cases
Closes #9140

Fix: Unread line

---

packages/rocketchat-api/server/api.js
packages/rocketchat-livechat/app/package-lock.json

Fix: Can’t login using LDAP via REST

---

packages/rocketchat-google-vision/.npm/package/npm-shrinkwrap.json
packages/rocketchat-lib/.npm/package/npm-shrinkwrap.json
packages/rocketchat-lib/package.js
packages/rocketchat-ui/client/lib/chatMessages.js

[FIX] Last sent message reoccurs in textbox

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Fix: UI: Descenders of glyphs are cut off

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Fix: Click on channel name - hover area bigger than link area

---

packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui-login/client/login/services.html

[FIX] show oauth logins when adblock is used

---

packages/rocketchat-theme/client/imports/components/modal.css
packages/rocketchat-ui/client/lib/fileUpload.js
packages/rocketchat-ui/client/views/app/modal.js

* Send input data when press enter key
* Input focus when open modal
* Fix modal style on file preview

[FIX] modal data on enter and modal style for file preview

---

packages/rocketchat-ui/client/views/app/room.js

[FIX] go to replied message

---

packages/rocketchat-theme/client/imports/components/modal/create-channel.css
packages/rocketchat-ui/client/views/app/createChannel.html

[FIX] channel create scroll on small screens

---

packages/rocketchat-emoji/client/emojiButton.js
packages/rocketchat-emoji/client/emojiPicker.css
packages/rocketchat-ui-message/client/messageBox.html
packages/rocketchat-ui-message/client/messageBox.js
packages/rocketchat-ui-message/client/popup/messagePopupConfig.js

[FIX] "Use Emoji" preference not working

---

packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] Unread bar position when room have announcement

---

packages/rocketchat-emoji-emojione/client/sprites.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] Emoji size on last message preview

---

packages/rocketchat-lib/client/MessageAction.js

[FIX] Cursor position when reply on safari

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-message/client/message.html
packages/rocketchat-ui-message/client/message.js

Fix: Snippet name to not showing in snippet list

---

packages/rocketchat-ui-message/startup/messageBoxActions.js

Closes #9036 #9154 
Now file upload should work on all browsers

[FIX] File upload not working on IE and weird on Chrome

---

packages/rocketchat-lib/server/functions/deleteMessage.js
packages/rocketchat-lib/server/lib/notifyUsersOnMessage.js
packages/rocketchat-lib/server/models/Messages.js
packages/rocketchat-lib/server/models/Rooms.js

Fix: updating last message on message edit or delete

---

packages/rocketchat-lib/server/models/Users.js
server/methods/getUsernameSuggestion.js

Fix: Username find is matching partially

---

packages/rocketchat-theme/client/imports/forms/select-avatar.css
packages/rocketchat-ui-account/client/accountProfile.html
packages/rocketchat-ui-account/client/accountProfile.js

Fix: Missing option to set user's avatar from a url

---

packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js

[FIX] Show modal with announcement

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Fix: Sidebar item on rtl and small devices

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Do not change room icon color when room is unread

---

packages/rocketchat-file-upload/server/lib/FileUpload.js

[FIX] File access not working when passing credentials via querystring

---

packages/rocketchat-irc/README.md

Fix: README typo

---

packages/rocketchat-ui-account/client/accountPreferences.html

This should close https://github.com/RocketChat/Rocket.Chat/issues/9288.

[FIX] Wrong position of notifications alert in accounts preference page

---

README.md

As per Apple's marketing guidelines: https://developer.apple.com/app-store/marketing/guidelines/
Also removed excessive use of exclamation marks; read more like marketing material than a serious feature list that could be referenced on the likes of Wikipedia. :- )

Fix: Improved README.md

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
packages/rocketchat-theme/client/imports/general/variables.css

New the sidebar footer padding is equal to the sidebar header

[FIX] sidebar footer padding

---

packages/rocketchat-theme/client/imports/components/emojiPicker.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] custom emoji size on sidebar item

---

packages/rocketchat-cors/cors.js

[FIX] LDAP TLS not working in some cases

---

packages/rocketchat-markdown/.npm/package/npm-shrinkwrap.json
packages/rocketchat-markdown/package.js

Update Marked dependecy to 0.3.9

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] last message cutting on bottom

---

packages/rocketchat-theme/client/imports/components/popover.css
packages/rocketchat-ui/client/views/app/popover.html
packages/rocketchat-ui/client/views/app/popover.js

[FIX] popover on safari for iOS

---

packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] announcement hyperlink color

---

package-lock.json
package.json
packages/rocketchat-lib/server/lib/interceptDirectReplyEmails.js

Since we are not using Node 4 anymore we do not need to use the mailperser fork, we can use the original one with Node 8

Use correct version of Mailparser module

---

packages/rocketchat-ui-account/client/accountPreferences.js

Hi
Later I was add enter separator support with ##8433 PR but after v60 it's break (I report it in issue #9362)
I fixed this issue with this PR please review and merge 😉

[FIX] Highlight setting not working correctly

---

packages/rocketchat-emoji/client/emojiPicker.html
packages/rocketchat-emoji/client/emojiPicker.js
packages/rocketchat-emoji/client/lib/EmojiPicker.js
packages/rocketchat-theme/client/imports/components/emojiPicker.css
tests/pageobjects/main-content.page.js

[NEW] new layout for emojipicker

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html
packages/rocketchat-ui-sidenav/client/sidebarItem.js

[NEW] Indicate the Self DM room

---

packages/rocketchat-message-mark-as-unread/server/unreadMessages.js
packages/rocketchat-ui-sidenav/client/sidebarItem.js
packages/rocketchat-ui/client/views/app/popover.js

[NEW] Sidebar menu option to mark room as unread

---

packages/rocketchat-livechat/.app/client/lib/chatMessages.js
packages/rocketchat-livechat/server/methods/sendMessageLivechat.js

Pretty much what the title says, fix incoming livechats when using a trigger impersonating an agent.

[FIX] Fix incoming livechat when impersonating an agent

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css

[FIX] Missing sidebar paddings on mobile

---

.github/bot-config.yml

Add community bot

---

packages/rocketchat-livechat/client/views/app/tabbar/visitorEdit.html
packages/rocketchat-livechat/client/views/app/tabbar/visitorEdit.js

[FIX] Fix livechat visitor edit

---

packages/rocketchat-otr/client/rocketchat.otr.room.js

Fix: OTR modal title

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.js

Fix: Last message layout breaking with Markdown and Code Highlight

---

server/startup/avatar.js

This PR updates the way of how the avatar (the SVG file) is built. It adds the corners rounded to the file, making the mobile apps render it as shown in the web application.
Additional information about the need for this PR can be found here: https://github.com/RocketChat/Rocket.Chat.Android/issues/729

[FIX] SVG avatars are not been displayed correctly when load in non HTML containers

---

packages/rocketchat-ui/client/lib/avatar.js

[FIX] Desktop notification not showing when avatar came from external storage service

---

packages/rocketchat-emoji-emojione/client/sprites.css
packages/rocketchat-theme/client/imports/components/emojiPicker.css

[FIX] Weird rendering of emojis at sidebar when `last message` is activated

---

packages/rocketchat-livechat/imports/server/rest/facebook.js
packages/rocketchat-livechat/server/sendMessageBySMS.js

The previous called method does not exists, causing an error `RocketChat.models.Users.getVisitorByToken is not a function`

[FIX] Facebook integration in livechat not working on version 0.61.0

---

packages/rocketchat-livechat/server/lib/Livechat.js
packages/rocketchat-livechat/server/models/LivechatInquiry.js

Closes #9558
This fixes an issue that is occurring when the visitor tries to close the chat.

[FIX] Close Livechat conversation by visitor not working in version 0.61.0

---

packages/rocketchat-emoji-custom/assets/stylesheets/emojiCustomAdmin.css
packages/rocketchat-theme/client/imports/components/emojiPicker.css

[FIX] Custom emoji was cropping sometimes

---

packages/rocketchat-videobridge/client/public/external_api.js

Adds the allow microphone and camera tag in the iframe for jitsi
Closes #9554

[FIX] Chrome 64 breaks jitsi-meet iframe

---

packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js

[FIX] Close button on file upload bar was not working

---

packages/rocketchat-channel-settings/client/views/channelSettings.html
packages/rocketchat-theme/client/imports/components/userInfo.css

[FIX] Wrong behavior of rooms info's *Read Only* and *Collaborative* buttons

---

.docker/Dockerfile
.sandstorm/sandstorm-pkgdef.capnp
.travis/snap.sh
package.json
packages/rocketchat-lib/rocketchat.info

Develop fix sync from master

---

packages/rocketchat-theme/client/imports/general/base.css

Regression: Page was not respecting the window height on Firefox

---

.github/ISSUE_TEMPLATE.md

In some cases this is important to know. Also, if we commit to a specific version, we cannot support other versions - or at least we need to know whether it differs from the default.

[NEW] Request mongoDB version in github issue template

---

packages/rocketchat-theme/client/imports/components/sidebar/toolbar.css

Regression: Search bar is now full width

---

packages/rocketchat-ui-sidenav/client/toolbar.js

Now you can open search using ctrl/cmd + p and ctrl/cmd + k shortcuts again.

Regression: Open search using ctrl/cmd + p and ctrl/cmd + k

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-header.css
packages/rocketchat-ui-sidenav/client/sidebarHeader.js
tests/end-to-end/ui/11-admin.js
tests/end-to-end/ui/12-settings.js
tests/pageobjects/side-nav.page.js

Avatar now show user related options and the 3 dots (...) menu now opens dynamic options and admin
and if you aren't admin and don't have any dynamic options or you're anonymous the menu will disappear

Regression: Avatar now open account related options

---

packages/rocketchat-version-check/server/functions/getNewUpdates.js

[FIX] Silence the update check error message

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Regression: Fix admin/user settings item text

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

Regression: Fix channel icons on safari

---

packages/rocketchat-ui-sidenav/client/roomList.js

Regression: sort on room's list not working correctly

---

packages/rocketchat-lib/server/models/Rooms.js
server/methods/browseChannels.js

Regression: Directory now list default channel

---

packages/rocketchat-livechat/roomType.js
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html
packages/rocketchat-ui-sidenav/client/sidebarItem.js

Regression: Fix livechat queue link

---

packages/rocketchat-theme/client/imports/components/main-content.css

[FIX] New channel page on medium size screens

---

packages/rocketchat-lib/client/lib/cachedCollection.js
packages/rocketchat-ui-sidenav/client/roomList.js

[FIX] Empty sidenav when sorting by activity and there is a subscription without room

---

packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] Two factor authentication modal was not showing

---

packages/rocketchat-ui-account/client/accountProfile.html

[FIX] Avatar input was accepting not supported image types

---

packages/rocketchat-lib/server/models/Users.js
server/methods/saveUserPreferences.js

[FIX] Update preferences of users with settings: null was crashing the server

---

README.md

Summary of changes:
- Removed GitHub issues as a place to suggest, discuss and upvote features.
- Added Discourse Forums as a place to suggest, discuss and upvote features.

Add forums as a place to suggest, discuss and upvote features

---

packages/rocketchat-reactions/client/init.js

[FIX] Reactions not working on mobile

---

packages/rocketchat-theme/client/imports/components/file-list.css
packages/rocketchat-theme/client/main.css

[FIX] Name of files in file upload list cuts down at bottom due to overflow

---

packages/rocketchat-ui-flextab/client/tabs/userInfo.html
packages/rocketchat-ui-flextab/client/tabs/userInfo.js

Fixes https://github.com/RocketChat/Rocket.Chat/issues/9820

[FIX] User status missing on user info

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] Extended view mode on sidebar

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/v1/emoji-custom.js
tests/end-to-end/api/12-emoji-custom.js

Partially: #9326
Docs: RocketChat/docs/pull/550

[NEW] Add REST endpoint to get the list of custom emojis

---

package-lock.json
package.json
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/oauth/facebook.js
packages/rocketchat-lib/server/oauth/twitter.js

[NEW] Add option to login via REST using Facebook and Twitter tokens

---

packages/rocketchat-ui-master/package.js
packages/rocketchat-ui-master/server/dynamic-css.js
packages/rocketchat-ui-master/server/inject.js

Closes #10129 
Dynamic-css script was converted to es5 to work on older browsers.

[FIX] Dynamic CSS script isn't working on older browsers

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] user status on sidenav

---

server/startup/migrations/v108.js

Rename migration name on 108 to match file name

---

.snapcraft/snapcraft.yaml

https://github.com/meteor/meteor/blob/devel/History.md#v1611-2018-04-02

Bump snap version to include security fix

---

packages/rocketchat-i18n/i18n/fr.i18n.json

[FIX] Incorrect French language usage for Disabled

---

.snapcraft/snapcraft.yaml

Closes https://github.com/RocketChat/Rocket.Chat/issues/10363

[FIX] Snaps installations are breaking on avatar requests

---

.docker/Dockerfile.rhel
.docker/licenses/LICENSE
.scripts/set-version.js

add redhat dockerfile to master

---

packages/rocketchat-lib/client/MessageAction.js

Closes #10329 
Adds the quote box that showed messages on Reply to the Quote option as well.
Added a citation when replying to someone (since it is the basic difference between quote and reply)

[NEW] Add message preview when quoting another message

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/sv.i18n.json
packages/rocketchat-ui-flextab/client/tabs/membersList.html
packages/rocketchat-ui/client/views/app/directory.html
packages/rocketchat-ui/client/views/app/home.html
packages/rocketchat-ui/client/views/app/popover.html

Closes #10125
Add some translation calls where it was missing and add the Computer key to i18n list

Add some missing translations

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html

[FIX] Room's name was cutting instead of having ellipses on sidebar

---

packages/meteor-accounts-saml/saml_utils.js

Fixes two more places that TypeErrors are being thrown when using SAML. This code is pulled from #9775

[FIX] Even TypeErrors with SAML

---

packages/rocketchat-lib/server/functions/sendMessage.js

Closes #10568
Ref: https://github.com/meteor/meteor/issues/1233

Regression: Attachments and fields incorrectly failing on validation

---

packages/rocketchat-api/server/v1/settings.js

Fix inconsistent response of settings.oauth endpoint
Closes #10546

Regression: Inconsistent response of settings.oauth endpoint

---

packages/rocketchat-ui-flextab/client/tabs/membersList.js

@sampaiodiego 
go to member list , search for a user like "asdasdasdasda", and done.
apparently `_.first` return null sometimes :x

[FIX] Member list search with no results

---

packages/rocketchat-lib/server/startup/settings.js
packages/rocketchat-setup-wizard/client/setupWizard.html
packages/rocketchat-setup-wizard/client/setupWizard.js
packages/rocketchat-theme/client/imports/components/setup-wizard.css
packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/lib/menu.js
packages/rocketchat-ui/client/lib/tapi18n.js
server/lib/accounts.js
server/startup/initialData.js
server/startup/migrations/v117.js
server/startup/migrations/v119.js
tests/end-to-end/ui/00-login.js
tests/pageobjects/setup-wizard.page.js

* Change wizard state from boolean to `pending`, `in_progress` or `completed`
* Add migration to change the wizard setting to new values and fix the old migration
* Make the wizard responsive for small screens
* Do not publish wizard settings to the client
* Do not show wizard for unlogged users after admin was created

Wizard improvements

---

packages/rocketchat-lib/server/functions/notifications/mobile.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

The screenshots bellow are from a user whom username is `chinello` and name is `Diego`, sending a message to a username `lero2` with name `John Doe`.
Before:
After:

Improvement to push notifications on direct messages

---

packages/rocketchat-file-upload/server/lib/FileUpload.js

[NEW] Now is possible to access files using header authorization (`x-user-id` and `x-auth-token`)

---

packages/rocketchat-lib/client/MessageAction.js

Closes #8936 
This PR fixes an issue that was occurring when a Livechat manager tried to send message in a livechat room. It was happening because when a manager opens a current chat, there is not subscription for the user of the Livechat manager.

[FIX] Livechat managers were not being able to send messages in some cases

---

packages/rocketchat-api/server/helpers/getUserInfo.js

Fix: Regression in REST API endpoint `/me` 

---

server/methods/requestDataDownload.js

[FIX] Internal Error when requesting user data download

---

packages/rocketchat-lazy-load/client/lazyloadImage.js
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui-message/client/popup/messagePopup.js

Fix: Regression on users avatar in admin pages

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css

[FIX] Layout badge cutting on unread messages for long names

---

packages/rocketchat-api/server/v1/misc.js
packages/rocketchat-ui/client/views/app/directory.js
server/methods/browseChannels.js
tests/end-to-end/api/00-miscellaneous.js

[FIX] Missing pagination fields in the response of REST /directory endpoint

---

package-lock.json
packages/rocketchat-livechat/.app/package-lock.json
packages/rocketchat-ui-sidenav/client/roomList.js

[FIX] Sorting in sidebar rooms list

---

README.md

👇 Now you can deploy RocketChat to WeDeploy with one click
[![Deploy](https://cdn.wedeploy.com/images/deploy.svg)](https://console.wedeploy.com/deploy?repo=https://github.com/wedeploy-examples/rocketchat-example)

[NEW] Update WeDeploy deployment

---

packages/rocketchat-2fa/client/accountSecurity.html

All mobile apps support 2FA now.

[FIX] Remove outdated 2FA warning for mobile clients

---

.meteor/versions
package.json
packages/rocketchat-livechat/.app/.meteor/versions
packages/rocketchat-livechat/.app/package.json

[FIX] Livechat not loading

---

packages/rocketchat-theme/client/imports/components/setup-wizard.css

[FIX] Setup wizard info panel width

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-integrations/client/route.js
packages/rocketchat-integrations/client/stylesheets/integrations.css
packages/rocketchat-integrations/client/views/additional/zapier.html
packages/rocketchat-integrations/client/views/additional/zapier.js
packages/rocketchat-integrations/client/views/integrations.html
packages/rocketchat-integrations/package.js

Closes #9420
Closes #7338
Needs to be reviewed for the style and everything. This is what's required for us to launch our Zapier App out of beta.

[NEW] Button to display the Zapier templates inside integrations page

---

packages/rocketchat-oembed/client/oembedAudioWidget.html
packages/rocketchat-oembed/client/oembedFrameWidget.html
packages/rocketchat-oembed/client/oembedImageWidget.html
packages/rocketchat-oembed/client/oembedUrlWidget.html
packages/rocketchat-oembed/client/oembedVideoWidget.html
packages/rocketchat-oembed/client/oembedYoutubeWidget.html
packages/rocketchat-spotify/lib/client/oembedSpotifyWidget.html

Adds noopener and noreferrer to all links on attachments

[FIX] Attachment links are lacking noopener and noreferrer

---

packages/rocketchat-i18n/i18n/en.i18n.json

Closes #8504
This simply adds both shortcuts to the Keyboard Shortcuts tab.

[FIX] Search shortcut text

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/functions/notifications/email.js
packages/rocketchat-lib/server/startup/settings.js

Separate Reply-To email from account username field.
Based on https://github.com/RocketChat/Rocket.Chat/pull/10782
Closes #9564

Pkgodara direct reply separate reply to

---

packages/rocketchat-file-upload/server/lib/FileUpload.js

[FIX] Exception thrown on avatar validation

---

packages/rocketchat-ui-flextab/client/flexTabBar.js

[FIX] flex-tab icons missing

---

.meteor/versions
client/startup/startup.js

We realized we are sending user presence even before the user get logged in.

[FIX] avoid send presence without login

---

.circleci/config.yml
.circleci/setartname.sh
.docker/Dockerfile

This PR will allow us to build docker images to every PR from within the CI.
I've added a new manual approval step for PR workflows, that once approved, will generate a new Docker image tagged as `pr-${ PR_NUMBER }`:
For tag or develop branch builds, the new step will run always, as it previously worked.

Build Docker image on CI

---

.circleci/config.yml

Fix PR Docker image creation by splitting in two build jobs

---

packages/rocketchat-lib/server/models/Users.js

[FIX] Users model was not receiving options

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui-master/client/main.html
packages/rocketchat-ui-master/client/main.js

[FIX] remove sidebar on embedded view

---

packages/rocketchat-livechat/roomType.js
packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html
packages/rocketchat-ui-sidenav/client/sidebarItem.js

[FIX] Livechat icon with status

---

packages/rocketchat-ui/client/components/table.js
packages/rocketchat-ui/client/views/app/directory.js

Users table now has an infinite scroll that works :)

Regression: Directory user table infinite scroll doesn't working

---

packages/rocketchat-user-data-download/server/cronProcessDownloads.js

[FIX] Failure to download user data

---

packages/rocketchat-importer-hipchat/server/importer.js

[FIX] HipChat Cloud import fails to import rooms

---

packages/rocketchat-api/server/helpers/insertUserObject.js

Add verification to make sure the user exists in REST  insert object helper

---

packages/rocketchat-api/server/api.js
tests/end-to-end/api/00-miscellaneous.js

[FIX] REST API: Add more test cases for `/login`

---

.circleci/config.yml

Regression: Fix latest and release-candidate docker images building

---

packages/rocketchat-theme/client/imports/components/table.css
packages/rocketchat-ui/client/components/table.js
packages/rocketchat-ui/client/views/app/directory.html
packages/rocketchat-ui/client/views/app/directory.js
server/methods/browseChannels.js

Regression: Fix directory table loading

---

packages/rocketchat-theme/client/imports/components/table.css
packages/rocketchat-ui/client/views/app/directory.html
packages/rocketchat-ui/client/views/app/directory.js

Regression: Directory sort users, fix null results, text for empty results

---

server/startup/migrations/v123.js

Regression: Skip operations if no actions on livechat migration

---

packages/rocketchat-lib/server/lib/metrics.js

Regression introduced by https://github.com/RocketChat/Rocket.Chat/pull/11115

Regression: Prometheus was not being enabled in some cases

---

packages/rocketchat-cas/server/cas_server.js

[FIX] Internal Server Error on first login with CAS integration

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ldap/server/ldap.js
packages/rocketchat-ldap/server/loginHandler.js
packages/rocketchat-ldap/server/settings.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/11017

[FIX] LDAP was accepting login with empty passwords for certain AD configurations

---

package-lock.json
server/methods/saveUserPreferences.js
server/startup/migrations/v129.js

[FIX] Notification preferences being lost when switching view mode

---

packages/meteor-accounts-saml/saml_utils.js

[FIX] SAML attributes with periods are not properly read.

---

packages/rocketchat-lib/server/models/_BaseDb.js

[FIX] Some updates were returning errors when based on queries with position operators

---

.snapcraft/resources/prepareRocketChat

[FIX] Remove file snap store doesn't like

---

packages/rocketchat-lib/server/functions/notifications/email.js
packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js

[FIX] All messages notifications via email were sent as mention alert

---

client/startup/loginViaQuery.js

[NEW] Accept resumeToken as query param to log in

---

packages/rocketchat-ui-vrecord/client/VRecDialog.js
packages/rocketchat-ui-vrecord/client/vrecord.css
packages/rocketchat-ui-vrecord/client/vrecord.html

[FIX] Record popup

---

packages/rocketchat-ui-message/client/message.js

[FIX] broadcast channel reply

---

packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] Decrease room leader bar z-index

---

packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
packages/rocketchat-theme/client/imports/general/base_old.css

[FIX] empty blockquote

---

packages/rocketchat-api/server/helpers/getUserInfo.js

[FIX] Add customFields property to /me REST endpoint response

---

packages/rocketchat-api/server/v1/channels.js

[FIX] Unreads counter for new rooms on /channels.counters REST endpoin

---

packages/rocketchat-api/server/v1/chat.js
tests/end-to-end/api/05-chat.js

[FIX] Change pagination field to `count` on /chat.search REST endpoint

---

package-lock.json
packages/rocketchat-lib/lib/getValidRoomName.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js

Revert https://github.com/RocketChat/Rocket.Chat/pull/9449/ due to several broken tests.
Looks like a break change that should be better tested and documented.

Revert: Mixed case channel slugs #9449

---

packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-ui-message/client/messageBox.html

[FIX] Render reply preview with message as a common message

---

packages/rocketchat-lib/client/lib/cachedCollection.js

Regression: Update cachedCollection version

---

server/methods/loadHistory.js

[FIX] Missing chat history for users without permission `preview-c-room`

---

packages/rocketchat-lib/server/functions/getFullUserData.js

[FIX] User info APIs not returning customFields correctly

---

server/methods/getRoomIdByNameOrId.js

[FIX] Return room ID for groups where user joined

---

packages/rocketchat-ui-message/client/messageBox.js

[FIX]  Cannot set property 'input' of undefined

---

packages/rocketchat-lazy-load/client/lazyloadImage.html
packages/rocketchat-lazy-load/client/lazyloadImage.js

[FIX] Apply Cordova fix in lazy-loaded images sources

---

packages/rocketchat-livechat/.app/client/views/messages.js
packages/rocketchat-livechat/livechat.js

thanks to @timkinnane who found them.

Regression: Fix livechat code issues after new lint rules

---

packages/rocketchat-apps/client/admin/appManage.html
packages/rocketchat-apps/server/bridges/http.js

[FIX] App's i18nAlert is only being displayed as "i18nAlert"

---

packages/rocketchat-authorization/client/stylesheets/permissions.css

[FIX] permissions name no break

---

packages/rocketchat-api/server/v1/im.js
tests/end-to-end/api/04-direct-message.js

[FIX] REST `im.members` endpoint not working without sort parameter

---

.eslintignore
packages/rocketchat-theme/client/imports/general/base_old.css
packages/rocketchat-theme/client/imports/general/variables.css
packages/rocketchat-ui/client/lib/textarea-autogrow.js

Regression: role tag background, unread item font and message box autogrow

---

.docker/Dockerfile.rhel
.github/history.json
.sandstorm/sandstorm-pkgdef.capnp
.travis/snap.sh
HISTORY.md
package-lock.json
package.json
packages/rocketchat-apps/client/admin/appManage.html
packages/rocketchat-apps/client/admin/appManage.js
packages/rocketchat-apps/client/admin/apps.js
packages/rocketchat-importer-hipchat-enterprise/server/importer.js
packages/rocketchat-importer/server/classes/ImporterBase.js
packages/rocketchat-lib/client/lib/RestApiClient.js
packages/rocketchat-lib/rocketchat.info
packages/rocketchat-message-attachments/client/messageAttachment.html

`2018-08-31  ·  4 🐛  ·  2 👩‍💻👨‍💻`
- Node: `8.11.3`
- NPM: `5.6.0`
- Hipchat import was failing when importing messages from a non existent user ([#11892](https://github.com/RocketChat/Rocket.Chat/pull/11892))
- Hipchat importer was not importing users without emails and uploaded files ([#11910](https://github.com/RocketChat/Rocket.Chat/pull/11910))
- App updates were not being shown correctly ([#11893](https://github.com/RocketChat/Rocket.Chat/pull/11893))
- Duplicated message buttons ([#11853](https://github.com/RocketChat/Rocket.Chat/pull/11853) by [@ubarsaiyan](https://github.com/ubarsaiyan))
- [@ubarsaiyan](https://github.com/ubarsaiyan)
- [@rodrigok](https://github.com/rodrigok)

Release 0.69.1

---

packages/rocketchat-ui-login/client/reset-password/resetPassword.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/11859

[FIX] Reset password link error if already logged in

---

packages/rocketchat-theme/client/imports/components/header.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/components/header/header.html
packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js

[FIX] Hidden admin sidenav on embedded layout

---

.docker/Dockerfile.rhel
.github/history.json
.sandstorm/sandstorm-pkgdef.capnp
.travis/snap.sh
HISTORY.md
package.json
packages/rocketchat-apps/client/admin/appManage.html
packages/rocketchat-apps/client/admin/appManage.js
packages/rocketchat-lib/rocketchat.info
packages/rocketchat-lib/server/functions/saveUser.js
packages/rocketchat-theme/client/imports/components/header.css
packages/rocketchat-theme/client/imports/components/sidebar/sidebar.css
packages/rocketchat-ui-login/client/reset-password/resetPassword.js
packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/components/header/header.html
packages/rocketchat-ui/client/views/app/room.html
packages/rocketchat-ui/client/views/app/room.js
server/stream/messages.js
tests/end-to-end/api/01-users.js

`2018-09-11  ·  1 🎉  ·  4 🐛  ·  6 👩‍💻👨‍💻`
- Node: `8.11.3`
- NPM: `5.6.0`
- Include room name in stream for bots ([#11812](https://github.com/RocketChat/Rocket.Chat/pull/11812))
- Reset password link error if already logged in ([#12022](https://github.com/RocketChat/Rocket.Chat/pull/12022))
- Apps: setting with 'code' type only saving last line ([#11992](https://github.com/RocketChat/Rocket.Chat/pull/11992))
- Update user information not possible by admin if disabled to users ([#11955](https://github.com/RocketChat/Rocket.Chat/pull/11955) by [@kaiiiiiiiii](https://github.com/kaiiiiiiiii))
- Hidden admin sidenav on embedded layout ([#12025](https://github.com/RocketChat/Rocket.Chat/pull/12025))
- [@kaiiiiiiiii](https://github.com/kaiiiiiiiii)
- [@cardoso](https://github.com/cardoso)
- …

Release 0.69.2

---

packages/rocketchat-api/server/v1/im.js

[FIX] Direct messages leaking into logs

---

packages/rocketchat-graphql/server/resolvers/messages/addReactionToMessage.js
packages/rocketchat-graphql/server/schemas/messages/addReactionToMessage.graphqls

[FIX] Message reaction in GraphQL API

---

packages/rocketchat-api/server/api.js

Closes #11737
Closes #11738
Closes #8404

[FIX] Internal error when cross-origin with CORS is disabled

---

packages/rocketchat-api/server/v1/groups.js
tests/end-to-end/api/03-groups.js

[NEW] REST endpoint to set groups' announcement

---

packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js

[FIX] Prevent form submission in Files List search

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js

[NEW] REST endpoints to get moderators from groups and channels

---

packages/rocketchat-apps/server/converters/messages.js

Requires merge in engine repo: https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/62

[NEW] Apps: Add groupable property to message converter

---

packages/rocketchat-api/server/v1/channels.js
packages/rocketchat-api/server/v1/groups.js

The new eslint version used on `update-meteor-1-7` version gets this.

Fix using wrong variable

---

packages/rocketchat-theme/client/imports/components/sidebar/sidebar-item.css
packages/rocketchat-ui-sidenav/client/sidebarItem.html
packages/rocketchat-ui-sidenav/client/sidebarItem.js
packages/rocketchat-videobridge/server/methods/bbb.js

[IMPROVE] BigBlueButton joinViaHtml5 and video icon on sidebar

---

packages/rocketchat-livechat/.app/client/lib/triggers.js

If timed triggers are set too close (like one for 10s and another for 12s) the `getNextAgent` method might be called more than once, which may cause some issues, this PR prevents that.

[IMPROVE] Cache livechat get agent trigger call

---

packages/rocketchat-theme/client/imports/components/modal.css

Regression: Modal height

---

packages/rocketchat-ui/client/lib/textarea-autogrow.js

Regression: fix message box autogrow

---

packages/rocketchat-apps/server/converters/settings.js

Currently Apps can see/view settings which allow are hidden by environmental variables, this will disallow that.

[FIX] Apps being able to see hidden settings

---

packages/rocketchat-livechat/client/views/app/analytics/livechatAnalytics.html
packages/rocketchat-livechat/client/views/app/analytics/livechatRealTimeMonitoring.html
packages/rocketchat-livechat/permissions.js

This PR adds a new permission to allow/deny users access to the Livechat Analytics dashboards.

[NEW] Add Livechat Analytics permission

---

.github/bot-config.yml

Add @reetp to the issues' bot user whitelist.

Add reetp to the issues' bot whitelist

---

package-lock.json
packages/rocketchat-katex/package-lock.json
packages/rocketchat-livechat/server/hooks/sendToCRM.js

The integration of Livechat CRM was running even without having integration credentials informed.

[FIX] Livechat CRM integration running when disabled 

---

packages/rocketchat-livechat/.app/client/lib/triggers.js
packages/rocketchat-livechat/.app/client/views/livechatWindow.js

Triggers was being registered a second time when department was set on livechat

[FIX] Livechat triggers being registered twice after setting department via API

---

packages/rocketchat-ui/client/views/app/modal.js
packages/rocketchat-webdav/client/addWebdavAccount.js
packages/rocketchat-webdav/startup/messageBoxActions.js

Regression: fix modal submit

---

packages/rocketchat-livechat/server/hooks/RDStation.js

We were sending email field as an array but they expect a string.

[FIX] Livechat integration with RDStation

---

packages/rocketchat-oembed/server/jumpToMessage.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/12223

[FIX] Message editing was duplicating reply quotes

---

packages/rocketchat-e2e/client/rocketchat.e2e.js
packages/rocketchat-ui/client/views/app/modal.js

[FIX] E2E password request not closing after entering password

---

packages/rocketchat-apps/client/admin/appManage.js

Last improvements on Marketplace made this code obsolete and duplicate.

Fix: Remove semver satisfies from Apps details that is already done my marketplace

---

packages/rocketchat-e2e/client/events.js

[FIX] E2E alert shows up when encryption is disabled

---

packages/rocketchat-ui/client/views/app/modal.js
packages/rocketchat-webdav/startup/messageBoxActions.js

Proper fix for what https://github.com/RocketChat/Rocket.Chat/pull/12233 tried to accomplish.

[FIX] Modal confirm on enter

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/server/models/Users.js
packages/rocketchat-statistics/server/functions/get.js
server/startup/initialData.js

And a missing translation string as well.

Fix: Add wizard opt-in fields

---

package-lock.json
packages/rocketchat-livechat/server/api/v1/config.js

This PR fixes an error on the payload of the `config` endpoint, which was destructuring an invalid property.

[FIX] Invalid destructuring on Livechat API endpoint

---

packages/rocketchat-lib/server/functions/deleteMessage.js
packages/rocketchat-lib/server/models/Rooms.js

The PR title says everything.
This is broken from version `0.68.0`

[FIX] Last message not updating after message delete if show deleted status is on

---

packages/rocketchat-grant/server/authenticate.js
packages/rocketchat-ui-account/client/avatar/prompt.js

The variables tested on the left and right hand side are identical. Think these can be removed.

Fix: update check on err.details

---

packages/rocketchat-lib/server/functions/settings.js

[FIX] Cast env var setting to int based on option type

---

packages/rocketchat-api/server/v1/users.js
tests/end-to-end/api/01-users.js

[FIX] users.register endpoint to not create an user if username already being used

---

.circleci/config.yml

This will hopefully help tests to pass 👼

Improve: Drop database between running tests on CI

---

packages/rocketchat-api/server/api.js
packages/rocketchat-ldap/server/loginHandler.js

[BREAK] Add expiration to API login tokens and fix duplicate login tokens created by LDAP

---

.circleci/config.yml
packages/rocketchat-blockstack/client/main.js
packages/rocketchat-blockstack/client/routes.js

Closes #12226
This pull request removes `blockstack` dependency from the browser's modules bundle using [dynamic-import](https://docs.meteor.com/packages/dynamic-import.html).

[FIX] Blockstack errors in IE 11

---

packages/rocketchat-mailer/package.js

[FIX] email api

---

packages/rocketchat-ui-message/client/message.js

Regression: do not render pdf preview on safari <= 12

---

packages/rocketchat-graphql/server/resolvers/channels/deleteChannel.js
packages/rocketchat-graphql/server/resolvers/channels/index.js
packages/rocketchat-graphql/server/schemas/channels/deleteChannel.graphqls

Added deleteChannel mutation in GraphQL API

[NEW] Add delete channel mutation to GraphQL API

---

packages/rocketchat-lib/server/functions/saveUser.js

basically it was verifying if I had `edit-other-user-info` permission even when I was trying to edit myself

Fix: wrong saveUser permission validations

---

packages/rocketchat-ui-admin/client/admin.js

[FIX] Custom OAuth Configuration can't be removed

---

packages/rocketchat-mailer/server/api.js

Regression: Fix email headers not being used

---

README.md

Add 'Help Wanted' section to the Readme section.

[NEW] Add "help wanted" section to Readme

---

packages/rocketchat-apps/server/bridges/bridges.js
packages/rocketchat-apps/server/bridges/index.js
packages/rocketchat-apps/server/bridges/internal.js
packages/rocketchat-apps/server/bridges/rooms.js

Apps PR: https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/80

Apps: Room’s usernames was not working

---

packages/rocketchat-lib/server/functions/composeMessageObjectWithUser.js
packages/rocketchat-lib/server/functions/loadMessageHistory.js
packages/rocketchat-message-star/client/actionButton.js
packages/rocketchat-ui/client/views/app/room.js
server/methods/loadNextMessages.js
server/methods/loadSurroundingMessages.js
server/publications/messages.js
tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js
tests/end-to-end/api/04-direct-message.js

Change `starred` message property from object to array.
Change behaviour of [this PR](https://github.com/RocketChat/Rocket.Chat/pull/12266)

Regression: Change `starred` message property from object to array

---

packages/rocketchat-file-upload/server/methods/sendFileMessage.js
packages/rocketchat-ui/client/lib/fileUpload.js

Closes #12401 
Closes #11828
Closes #11163
Closes #10935
Related to #6026

[FIX] Ignore errors when creating image preview for uploads

---

.meteor/versions
packages/rocketchat-lib/server/functions/Notifications.js
server/publications/room.js
server/publications/subscription.js

[FIX] stream room-changed

---

packages/rocketchat-authorization/client/hasPermission.js
packages/rocketchat-authorization/server/functions/canAccessRoom.js
packages/rocketchat-authorization/server/functions/hasPermission.js
packages/rocketchat-emoji-custom/admin/startup.js
packages/rocketchat-integrations/server/lib/validation.js
packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.js
packages/rocketchat-integrations/server/methods/incoming/updateIncomingIntegration.js
packages/rocketchat-lib/README.md
packages/rocketchat-lib/lib/RoomTypeConfig.js
packages/rocketchat-lib/lib/roomTypes/direct.js
packages/rocketchat-lib/lib/roomTypes/private.js
packages/rocketchat-livechat/imports/LivechatRoomType.js
packages/rocketchat-slashcommands-topic/topic.js

[FIX] Manage own integrations permissions check

---

packages/rocketchat-i18n/i18n/es.i18n.json

Fix ES translation

---

packages/rocketchat-assets/package.js
packages/rocketchat-assets/server/assets.js
packages/rocketchat-assets/server/index.js

Convert rocketchat-assets to main module structure

---

packages/rocketchat-api/server/v1/chat.js
tests/end-to-end/api/05-chat.js

[FIX] Fix wrong parameter in chat.delete endpoint and add some test cases

---

packages/rocketchat-livechat/.app/client/stylesheets/main.less
packages/rocketchat-livechat/.app/client/views/livechatWindow.js
packages/rocketchat-livechat/assets/rocket-livechat.js

[NEW] Make Livechat's widget draggable

---

README.md

- Add hyphen.
- Add article.
- Fix spelling.

Fix punctuation, spelling, and grammar

---

packages/rocketchat_theme/client/main.css

Fix CSS import order

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/startup/robots.js
packages/rocketchat-lib/server/startup/settings.js

[NEW] Setting to configure robots.txt content

---

packages/rocketchat-autolinker/client/client.js
packages/rocketchat-autolinker/client/index.js
packages/rocketchat-autolinker/package.js
packages/rocketchat-autolinker/server/index.js
packages/rocketchat-autolinker/server/settings.js

Convert rocketchat-autolinker to main module structure

---

packages/rocketchat-cas/client/cas_client.js
packages/rocketchat-cas/client/index.js
packages/rocketchat-cas/package.js
packages/rocketchat-cas/server/cas_rocketchat.js
packages/rocketchat-cas/server/cas_server.js
packages/rocketchat-cas/server/index.js
packages/rocketchat-cas/server/models/CredentialTokens.js

Convert rocketchat-cas to main module structure

---

packages/rocketchat-colors/client/client.js
packages/rocketchat-colors/client/index.js
packages/rocketchat-colors/package.js
packages/rocketchat-colors/server/index.js
packages/rocketchat-colors/server/settings.js

Convert rocketchat-colors to main module structure

---

.eslintrc
packages/rocketchat-crowd/server/crowd.js
packages/rocketchat-crowd/server/settings.js

- Added new setting for cleaning crowd usernames and creating an RC compliant name
- Added new setting for selecting crowd user data sync interval
- Added new button to force an on demand user data sync
- When a crowd user authenticates the native method for storing passwords is called allowing RC authentication via fallbackDefaultAccountSystem even if Crowd server is offline

- Fix for issue #7674.  Passwords are no longer stored.

---

packages/rocketchat-ui-admin/client/admin.html
packages/rocketchat-ui-admin/client/admin.js
packages/rocketchat_theme/client/imports/forms/button.css
packages/rocketchat_theme/client/imports/forms/input.css
packages/rocketchat_theme/client/imports/forms/select.css
packages/rocketchat_theme/client/imports/general/base_old.css

[FIX] Admin styles

---

packages/rocketchat-cors/client/index.js
packages/rocketchat-cors/lib/common.js
packages/rocketchat-cors/package.js
packages/rocketchat-cors/server/cors.js
packages/rocketchat-cors/server/index.js

Convert rocketchat-cors to main module structure

---

packages/rocketchat-channel-settings/client/index.js
packages/rocketchat-channel-settings/client/lib/ChannelSettings.js
packages/rocketchat-channel-settings/client/startup/messageTypes.js
packages/rocketchat-channel-settings/client/startup/tabBar.js
packages/rocketchat-channel-settings/client/startup/trackSettingsChange.js
packages/rocketchat-channel-settings/client/views/channelSettings.js
packages/rocketchat-channel-settings/package.js
packages/rocketchat-channel-settings/server/functions/saveReactWhenReadOnly.js
packages/rocketchat-channel-settings/server/functions/saveRoomAnnouncement.js
packages/rocketchat-channel-settings/server/functions/saveRoomCustomFields.js
packages/rocketchat-channel-settings/server/functions/saveRoomDescription.js
packages/rocketchat-channel-settings/server/functions/saveRoomName.js
packages/rocketchat-channel-settings/server/functions/saveRoomReadOnly.js
packages/rocketchat-channel-settings/server/functions/saveRoomSystemMessages.js
packages/rocketchat-channel-settings/server/functions/saveRoomTopic.js
packages/rocketchat-channel-settings/server/functions/saveRoomType.js
packages/rocketchat-channel-settings/server/index.js
packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js
packages/rocketchat-channel-settings/server/models/Messages.js
packages/rocketchat-channel-settings/server/models/Rooms.js
packages/rocketchat-channel-settings/server/startup.js
packages/rocketchat-ui/client/lib/RoomManager.js
packages/rocketchat-ui/package.js

 Convert rocketchat-channel-settings to main module structure

---

packages/rocketchat-file/package.js
packages/rocketchat-file/server/file.server.js
packages/rocketchat-file/server/index.js
packages/rocketchat-importer-csv/server/importer.js
packages/rocketchat-importer-hipchat/server/importer.js
packages/rocketchat-importer-slack-users/server/importer.js
packages/rocketchat-importer-slack/server/importer.js
packages/rocketchat-ldap/server/sync.js
packages/rocketchat-lib/package.js
packages/rocketchat-lib/server/functions/setUserAvatar.js
server/startup/initialData.js
server/startup/migrations/v002.js
server/startup/migrations/v099.js

Convert rocketchat-file to main module structure

---

packages/rocketchat-google-natural-language/client/index.js
packages/rocketchat-google-natural-language/package.js
packages/rocketchat-google-natural-language/server/index.js
packages/rocketchat-google-natural-language/server/models/Rooms.js
packages/rocketchat-google-natural-language/server/settings.js

Added imports for global variables in rocketchat-google-natural-language package

---

packages/rocketchat-google-vision/client/googlevision.js
packages/rocketchat-google-vision/client/index.js
packages/rocketchat-google-vision/package.js
packages/rocketchat-google-vision/server/googlevision.js
packages/rocketchat-google-vision/server/index.js
packages/rocketchat-google-vision/server/models/Messages.js
packages/rocketchat-google-vision/server/settings.js

Convert rocketchat-google-vision to main module structure

---

client/startup/unread.js
packages/rocketchat-favico/client/favico.js
packages/rocketchat-favico/client/index.js

Fix favico error introduced by conversion of rocketchat:favico to main module structure

[FIX] Fix favico error

---

packages/rocketchat-importer/client/ImporterWebsocketReceiver.js
packages/rocketchat-importer/client/admin/adminImport.js
packages/rocketchat-importer/client/admin/adminImportPrepare.js
packages/rocketchat-importer/client/admin/adminImportProgress.js
packages/rocketchat-importer/client/index.js
packages/rocketchat-importer/package.js
packages/rocketchat-importer/server/classes/ImporterBase.js
packages/rocketchat-importer/server/index.js
packages/rocketchat-importer/server/methods/getImportProgress.js
packages/rocketchat-importer/server/methods/getSelectionData.js
packages/rocketchat-importer/server/methods/prepareImport.js
packages/rocketchat-importer/server/methods/restartImport.js
packages/rocketchat-importer/server/methods/setupImporter.js
packages/rocketchat-importer/server/methods/startImport.js
packages/rocketchat-importer/server/models/Imports.js
packages/rocketchat-importer/server/models/RawImports.js

Convert rocketchat-importer to main module structure

---

packages/rocketchat-iframe-login/client/iframe_client.js
packages/rocketchat-iframe-login/client/index.js
packages/rocketchat-iframe-login/package.js
packages/rocketchat-iframe-login/server/iframe_rocketchat.js
packages/rocketchat-iframe-login/server/iframe_server.js
packages/rocketchat-iframe-login/server/index.js

Convert rocketchat-iframe-login to main module structure

---

packages/rocketchat-internal-hubot/package.js
packages/rocketchat-internal-hubot/server/hubot.js
packages/rocketchat-internal-hubot/server/index.js
packages/rocketchat-internal-hubot/server/settings.js

Convert rocketchat-internal-hubot to main module structure

---

packages/rocketchat-irc/package.js
packages/rocketchat-irc/server/index.js
packages/rocketchat-irc/server/irc-bridge/index.js
packages/rocketchat-irc/server/irc-bridge/localHandlers/onCreateRoom.js
packages/rocketchat-irc/server/irc-bridge/localHandlers/onCreateUser.js
packages/rocketchat-irc/server/irc-bridge/localHandlers/onLogin.js
packages/rocketchat-irc/server/irc-bridge/localHandlers/onSaveMessage.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/disconnected.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/joinedChannel.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/leftChannel.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/nickChanged.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/sentMessage.js
packages/rocketchat-irc/server/irc-bridge/peerHandlers/userRegistered.js
packages/rocketchat-irc/server/irc-settings.js
packages/rocketchat-irc/server/irc.js
packages/rocketchat-irc/server/methods/resetIrcConnection.js

Convert rocketchat-irc to main module structure

---

packages/rocketchat-issuelinks/client/client.js
packages/rocketchat-issuelinks/client/index.js
packages/rocketchat-issuelinks/package.js
packages/rocketchat-issuelinks/server/index.js
packages/rocketchat-issuelinks/server/settings.js

Convert rocketchat-issuelinks to main module structure

---

packages/rocketchat-ldap/client/index.js
packages/rocketchat-ldap/package.js
packages/rocketchat-ldap/server/ldap.js
packages/rocketchat-ldap/server/loginHandler.js
packages/rocketchat-ldap/server/settings.js
packages/rocketchat-ldap/server/sync.js
packages/rocketchat-ldap/server/syncUsers.js
packages/rocketchat-ldap/server/testConnection.js

Convert rocketchat-ldap to main module structure

---

packages/rocketchat-livestream/client/index.js
packages/rocketchat-livestream/client/oauth.js
packages/rocketchat-livestream/client/tabBar.js
packages/rocketchat-livestream/client/views/broadcastView.js
packages/rocketchat-livestream/client/views/liveStreamTab.js
packages/rocketchat-livestream/package.js
packages/rocketchat-livestream/server/functions/saveStreamingOptions.js
packages/rocketchat-livestream/server/index.js
packages/rocketchat-livestream/server/methods.js
packages/rocketchat-livestream/server/models/Rooms.js
packages/rocketchat-livestream/server/routes.js
packages/rocketchat-livestream/server/settings.js
packages/rocketchat-ui/client/views/app/popout.js
packages/rocketchat-ui/package.js

 Convert rocketchat-livestream to main module structure

---

packages/rocketchat-mail-messages/client/index.js
packages/rocketchat-mail-messages/client/startup.js
packages/rocketchat-mail-messages/client/views/mailer.js
packages/rocketchat-mail-messages/lib/Mailer.js
packages/rocketchat-mail-messages/package.js
packages/rocketchat-mail-messages/server/functions/sendMail.js
packages/rocketchat-mail-messages/server/functions/unsubscribe.js
packages/rocketchat-mail-messages/server/index.js
packages/rocketchat-mail-messages/server/lib/Mailer.js
packages/rocketchat-mail-messages/server/methods/sendMail.js
packages/rocketchat-mail-messages/server/methods/unsubscribe.js
packages/rocketchat-mail-messages/server/models/Users.js
packages/rocketchat-mail-messages/server/startup.js

Convert rocketchat-mail-messages to main module structure

---

packages/rocketchat-ui/client/lib/chatMessages.js

[FIX] Update caret position on insert a new line in message box

---

packages/rocketchat_theme/client/imports/components/message-box.css

Regression: Inherit font-family for message box

---

.eslintignore
imports/personal-access-tokens/client/personalAccessTokens.html
packages/rocketchat-2fa/client/accountSecurity.html
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-account/client/accountIntegrations.html
packages/rocketchat-ui-account/client/accountPreferences.html
packages/rocketchat_theme/client/imports/general/base_old.css

Regression: Account pages layout

---

packages/rocketchat-ui-message/client/message.js

Regression: Fix Safari detection in PDF previewing

---

packages/rocketchat-mentions-flextab/client/actionButton.js
packages/rocketchat-mentions-flextab/client/index.js
packages/rocketchat-mentions-flextab/client/lib/MentionedMessage.js
packages/rocketchat-mentions-flextab/client/tabBar.js
packages/rocketchat-mentions-flextab/client/views/mentionsFlexTab.js
packages/rocketchat-mentions-flextab/package.js
packages/rocketchat-mentions-flextab/server/index.js
packages/rocketchat-mentions-flextab/server/publications/mentionedMessages.js
packages/rocketchat-ui/client/lib/RoomHistoryManager.js
packages/rocketchat-ui/package.js

 Convert rocketchat-mentions-flextab to main module structure

---

packages/rocketchat-message-action/client/index.js
packages/rocketchat-message-action/package.js

Convert rocketchat-message-action to main module structure

---

packages/rocketchat-message-attachments/client/index.js
packages/rocketchat-message-attachments/client/messageAttachment.js
packages/rocketchat-message-attachments/package.js

Convert rocketchat-message-attachments to main module structure

---

packages/rocketchat-message-mark-as-unread/client/actionButton.js
packages/rocketchat-message-mark-as-unread/client/index.js
packages/rocketchat-message-mark-as-unread/package.js
packages/rocketchat-message-mark-as-unread/server/index.js
packages/rocketchat-message-mark-as-unread/server/logger.js
packages/rocketchat-message-mark-as-unread/server/unreadMessages.js

Convert rocketchat-message-mark-as-unread to main module structure

---

packages/rocketchat-migrations/package.js
packages/rocketchat-migrations/server/index.js
packages/rocketchat-migrations/server/migrations.js

Convert rocketchat-migrations to main-module structure

---

packages/rocketchat-oembed/client/index.js
packages/rocketchat-oembed/client/oembedAudioWidget.js
packages/rocketchat-oembed/client/oembedFrameWidget.js
packages/rocketchat-oembed/client/oembedImageWidget.js
packages/rocketchat-oembed/client/oembedUrlWidget.js
packages/rocketchat-oembed/client/oembedVideoWidget.js
packages/rocketchat-oembed/client/oembedYoutubeWidget.js
packages/rocketchat-oembed/package.js
packages/rocketchat-oembed/server/index.js
packages/rocketchat-oembed/server/jumpToMessage.js
packages/rocketchat-oembed/server/models/OEmbedCache.js
packages/rocketchat-oembed/server/providers.js
packages/rocketchat-oembed/server/server.js

Convert rocketchat-oembed to main module structure

---

packages/rocketchat-otr/client/index.js
packages/rocketchat-otr/client/rocketchat.otr.js
packages/rocketchat-otr/client/rocketchat.otr.room.js
packages/rocketchat-otr/client/tabBar.js
packages/rocketchat-otr/client/views/otrFlexTab.js
packages/rocketchat-otr/package.js
packages/rocketchat-otr/server/index.js
packages/rocketchat-otr/server/methods/deleteOldOTRMessages.js
packages/rocketchat-otr/server/methods/updateOTRAck.js
packages/rocketchat-otr/server/models/Messages.js
packages/rocketchat-otr/server/settings.js

Convert rocketchat-otr to main module structure

---

packages/rocketchat-push-notifications/client/index.js
packages/rocketchat-push-notifications/client/tabBar.js
packages/rocketchat-push-notifications/client/views/pushNotificationsFlexTab.js
packages/rocketchat-push-notifications/package.js
packages/rocketchat-push-notifications/server/index.js
packages/rocketchat-push-notifications/server/methods/saveNotificationSettings.js
packages/rocketchat-push-notifications/server/models/Subscriptions.js
packages/rocketchat-ui/client/views/app/popover.js
packages/rocketchat-ui/package.js

Convert rocketchat-push-notifications to main module structure

---

packages/rocketchat-retention-policy/package.js
packages/rocketchat-retention-policy/server/cronPruneMessages.js
packages/rocketchat-retention-policy/server/index.js
packages/rocketchat-retention-policy/server/startup/settings.js

Convert rocketchat-retention-policy to main module structure

---

.circleci/setartname.sh
.circleci/update-releases.sh

Fix CI deploy job

---

packages/rocketchat-setup-wizard/client/final.js
packages/rocketchat-setup-wizard/client/index.js
packages/rocketchat-setup-wizard/client/setupWizard.js
packages/rocketchat-setup-wizard/package.js
packages/rocketchat-setup-wizard/server/getSetupWizardParameters.js
packages/rocketchat-setup-wizard/server/index.js

Convert rocketchat-setup-wizard to main module structure

---

packages/rocketchat-slackbridge/client/index.js
packages/rocketchat-slackbridge/client/slackbridge_import.client.js
packages/rocketchat-slackbridge/package.js
packages/rocketchat-slackbridge/server/RocketAdapter.js
packages/rocketchat-slackbridge/server/SlackAdapter.js
packages/rocketchat-slackbridge/server/index.js
packages/rocketchat-slackbridge/server/logger.js
packages/rocketchat-slackbridge/server/settings.js
packages/rocketchat-slackbridge/server/slackbridge.js
packages/rocketchat-slackbridge/server/slackbridge_import.server.js

Convert rocketchat-slackbridge to main module structure

---

packages/rocketchat-slashcommand-asciiarts/client/index.js
packages/rocketchat-slashcommand-asciiarts/lib/gimme.js
packages/rocketchat-slashcommand-asciiarts/lib/lenny.js
packages/rocketchat-slashcommand-asciiarts/lib/shrug.js
packages/rocketchat-slashcommand-asciiarts/lib/tableflip.js
packages/rocketchat-slashcommand-asciiarts/lib/unflip.js
packages/rocketchat-slashcommand-asciiarts/package.js
packages/rocketchat-slashcommand-asciiarts/server/index.js

Convert rocketchat-slashcommands-asciiarts to main module structure

---

packages/rocketchat-slashcommands-archiveroom/client/client.js
packages/rocketchat-slashcommands-archiveroom/client/index.js
packages/rocketchat-slashcommands-archiveroom/package.js
packages/rocketchat-slashcommands-archiveroom/server/index.js
packages/rocketchat-slashcommands-archiveroom/server/messages.js
packages/rocketchat-slashcommands-archiveroom/server/server.js

Convert rocketchat-slashcomands-archiveroom to main module structure

---

packages/rocketchat-slashcommands-create/client/client.js
packages/rocketchat-slashcommands-create/client/index.js
packages/rocketchat-slashcommands-create/package.js
packages/rocketchat-slashcommands-create/server/index.js
packages/rocketchat-slashcommands-create/server/server.js

Convert rocketchat-slashcommands-create to main module structure

---

packages/rocketchat-slashcommands-help/package.js
packages/rocketchat-slashcommands-help/server/index.js
packages/rocketchat-slashcommands-help/server/server.js

Convert rocketchat-slashcommands-help to main module structure

---

packages/rocketchat-slashcommands-hide/client/hide.js
packages/rocketchat-slashcommands-hide/client/index.js
packages/rocketchat-slashcommands-hide/package.js
packages/rocketchat-slashcommands-hide/server/hide.js
packages/rocketchat-slashcommands-hide/server/index.js

Convert rocketchat-slashcommands-hide to main module structure

---

packages/rocketchat-slashcommands-invite/client/client.js
packages/rocketchat-slashcommands-invite/client/index.js
packages/rocketchat-slashcommands-invite/package.js
packages/rocketchat-slashcommands-invite/server/index.js
packages/rocketchat-slashcommands-invite/server/server.js

Convert rocketchat-slashcommands-invite to main module structure

---

packages/rocketchat-slashcommands-inviteall/client/client.js
packages/rocketchat-slashcommands-inviteall/client/index.js
packages/rocketchat-slashcommands-inviteall/package.js
packages/rocketchat-slashcommands-inviteall/server/index.js
packages/rocketchat-slashcommands-inviteall/server/server.js

Convert rocketchat-slashcommands-inviteall to main module structure

---

packages/rocketchat-slashcommands-join/client/client.js
packages/rocketchat-slashcommands-join/client/index.js
packages/rocketchat-slashcommands-join/package.js
packages/rocketchat-slashcommands-join/server/index.js
packages/rocketchat-slashcommands-join/server/server.js

Convert rocketchat-slashcommands-join to main module structure

---

packages/rocketchat-slashcommands-kick/client/client.js
packages/rocketchat-slashcommands-kick/client/index.js
packages/rocketchat-slashcommands-kick/package.js
packages/rocketchat-slashcommands-kick/server/index.js
packages/rocketchat-slashcommands-kick/server/server.js

Convert rocketchat-slashcommands-kick to main module structure

---

packages/rocketchat-slashcommands-leave/package.js
packages/rocketchat-slashcommands-leave/server/index.js
packages/rocketchat-slashcommands-leave/server/leave.js

Convert rocketchat-slashcommands-leave to main module structure

---

packages/rocketchat-slashcommands-mute/package.js
packages/rocketchat-slashcommands-mute/server/index.js
packages/rocketchat-slashcommands-mute/server/mute.js
packages/rocketchat-slashcommands-mute/server/unmute.js

Convert rocketchat-slashcommands-mute to main module structure

---

packages/rocketchat-slashcommands-open/client/client.js
packages/rocketchat-slashcommands-open/client/index.js
packages/rocketchat-slashcommands-open/package.js

Convert rocketchat-slashcommands-open to main module structure

---

packages/rocketchat-slashcommands-topic/client/index.js
packages/rocketchat-slashcommands-topic/lib/topic.js
packages/rocketchat-slashcommands-topic/package.js
packages/rocketchat-slashcommands-topic/server/index.js

Convert rocketchat-slashcommands-topic to main module structure

---

packages/rocketchat-slashcommands-unarchiveroom/client/client.js
packages/rocketchat-slashcommands-unarchiveroom/client/index.js
packages/rocketchat-slashcommands-unarchiveroom/package.js
packages/rocketchat-slashcommands-unarchiveroom/server/index.js
packages/rocketchat-slashcommands-unarchiveroom/server/messages.js
packages/rocketchat-slashcommands-unarchiveroom/server/server.js

Convert rocketchat-slashcommands-unarchiveroom to main module structure

---

packages/rocketchat-smarsh-connector/client/index.js
packages/rocketchat-smarsh-connector/lib/rocketchat.js
packages/rocketchat-smarsh-connector/package.js
packages/rocketchat-smarsh-connector/server/functions/generateEml.js
packages/rocketchat-smarsh-connector/server/functions/sendEmail.js
packages/rocketchat-smarsh-connector/server/index.js
packages/rocketchat-smarsh-connector/server/models/SmarshHistory.js
packages/rocketchat-smarsh-connector/server/settings.js
packages/rocketchat-smarsh-connector/server/startup.js

Convert rocketchat-smarsh-connector to main module structure

---

packages/rocketchat-sms/package.js
packages/rocketchat-sms/server/SMS.js
packages/rocketchat-sms/server/index.js
packages/rocketchat-sms/server/services/twilio.js
packages/rocketchat-sms/server/settings.js

Convert rocketchat-sms to main module structure

---

packages/rocketchat-spotify/client/index.js
packages/rocketchat-spotify/lib/spotify.js
packages/rocketchat-spotify/package.js
packages/rocketchat-spotify/server/index.js

Convert rocketchat-spotify to main module structure

---

packages/rocketchat-statistics/client/index.js
packages/rocketchat-statistics/lib/rocketchat.js
packages/rocketchat-statistics/package.js
packages/rocketchat-statistics/server/functions/get.js
packages/rocketchat-statistics/server/functions/save.js
packages/rocketchat-statistics/server/index.js
packages/rocketchat-statistics/server/methods/getStatistics.js
packages/rocketchat-statistics/server/models/Statistics.js

Convert rocketchat-statistics to main module structure

---

packages/rocketchat-token-login/client/index.js
packages/rocketchat-token-login/package.js
packages/rocketchat-token-login/server/index.js
packages/rocketchat-token-login/server/login_token_server.js

Convert rocketchat-token-login to main module structure

---

packages/rocketchat-tooltip/client/index.js
packages/rocketchat-tooltip/client/init.js
packages/rocketchat-tooltip/client/rocketchat-tooltip.js
packages/rocketchat-tooltip/package.js

Convert rocketchat-tooltip to main module structure

---

packages/rocketchat-tokenpass/client/index.js
packages/rocketchat-tokenpass/client/roomType.js
packages/rocketchat-tokenpass/client/startup.js
packages/rocketchat-tokenpass/client/tokenChannelsList.js
packages/rocketchat-tokenpass/client/tokenpassChannelSettings.js
packages/rocketchat-tokenpass/lib/common.js
packages/rocketchat-tokenpass/package.js
packages/rocketchat-tokenpass/server/Tokenpass.js
packages/rocketchat-tokenpass/server/cronRemoveUsers.js
packages/rocketchat-tokenpass/server/functions/getProtectedTokenpassBalances.js
packages/rocketchat-tokenpass/server/functions/getPublicTokenpassBalances.js
packages/rocketchat-tokenpass/server/functions/saveRoomTokens.js
packages/rocketchat-tokenpass/server/functions/saveRoomTokensMinimumBalance.js
packages/rocketchat-tokenpass/server/functions/updateUserTokenpassBalances.js
packages/rocketchat-tokenpass/server/index.js
packages/rocketchat-tokenpass/server/methods/findTokenChannels.js
packages/rocketchat-tokenpass/server/methods/getChannelTokenpass.js
packages/rocketchat-tokenpass/server/models/Rooms.js
packages/rocketchat-tokenpass/server/models/Subscriptions.js
packages/rocketchat-tokenpass/server/models/Users.js
packages/rocketchat-tokenpass/server/models/indexes.js
packages/rocketchat-tokenpass/server/startup.js

Convert rocketchat-tokenpass to main module structure

---

packages/rocketchat-file-upload/ufs/GoogleStorage/server.js

It was not working since last updates.

[FIX] Google Cloud Storage storage provider

---

packages/rocketchat-ui-clean-history/client/index.js
packages/rocketchat-ui-clean-history/client/lib/startup.js
packages/rocketchat-ui-clean-history/client/views/cleanHistory.js
packages/rocketchat-ui-clean-history/package.js

Convert rocketchat-ui-clean-history to main module structure

---

packages/rocketchat-importer-hipchat-enterprise/package.js

[FIX] Missing HipChat Enterprise Importer

---

packages/rocketchat-cors/server/index.js

Change file order in rocketchat-cors

---

packages/rocketchat-api/server/v1/users.js

[FIX] API users.info returns caller rooms and not requested user ones

---

packages/rocketchat-ui-account/client/account.js
packages/rocketchat-ui-account/client/accountFlex.js
packages/rocketchat-ui-account/client/accountIntegrations.js
packages/rocketchat-ui-account/client/accountPreferences.js
packages/rocketchat-ui-account/client/accountProfile.js
packages/rocketchat-ui-account/client/avatar/avatar.js
packages/rocketchat-ui-account/client/avatar/prompt.js
packages/rocketchat-ui-account/client/index.js
packages/rocketchat-ui-account/package.js
packages/rocketchat-ui/client/lib/notification.js
packages/rocketchat-ui/package.js

 Convert rocketchat-ui-account to main module structure

---

packages/rocketchat-lazy-load/client/index.js
packages/rocketchat-lib/client/lib/roomExit.js
packages/rocketchat-livechat/.app/package-lock.json
packages/rocketchat-ui/client/lib/sideNav.js

[FIX] Change spread operator to Array.from for Edge browser

---

package-lock.json
package.json

Bump Apps-Engine version

---

packages/rocketchat-ui-flextab/client/flexTabBar.js
packages/rocketchat-ui-flextab/client/index.js
packages/rocketchat-ui-flextab/client/tabs/inviteUsers.js
packages/rocketchat-ui-flextab/client/tabs/membersList.js
packages/rocketchat-ui-flextab/client/tabs/userActions.js
packages/rocketchat-ui-flextab/client/tabs/userEdit.js
packages/rocketchat-ui-flextab/client/tabs/userInfo.js
packages/rocketchat-ui-flextab/package.js
packages/rocketchat-ui/client/lib/collections.js
packages/rocketchat-ui/client/lib/tapi18n.js
packages/rocketchat-ui/package.js

 Convert rocketchat-ui-flextab to main module structure

---

packages/rocketchat-ui/client/views/app/alerts.js
packages/rocketchat-ui/package.js
packages/rocketchat-version-check/client/client.js
packages/rocketchat-version-check/server/addSettings.js
packages/rocketchat-version-check/server/functions/checkVersionUpdate.js
packages/rocketchat-version-check/server/functions/getNewUpdates.js
packages/rocketchat-version-check/server/logger.js
packages/rocketchat-version-check/server/methods/banner_dismiss.js
packages/rocketchat-version-check/server/server.js

Convert rocketchat-version-check to main module structure

---

.circleci/snap.sh

Related to #12351 
cc @LuluGO we forgot the ci 😊

Fix: snap push from ci

---

packages/rocketchat-wordpress/client/index.js
packages/rocketchat-wordpress/lib/common.js
packages/rocketchat-wordpress/package.js
packages/rocketchat-wordpress/server/index.js
packages/rocketchat-wordpress/server/startup.js

Convert rocketchat-wordpress to main module structure

---

packages/rocketchat-message-attachments/client/index.js
packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
packages/rocketchat-message-attachments/package.js
packages/rocketchat-ui-message/client/message.js

[FIX] PDF view loading indicator

---

packages/rocketchat_theme/client/imports/general/base_old.css

[FIX] line-height for unread bar buttons (jump to first and mark as read)

---

packages/rocketchat-lib/server/publications/settings.js

[IMPROVE] Do not emit settings if there are no changes

---

packages/rocketchat-user-data-download/server/cronProcessDownloads.js

[FIX] User data download fails when a room has been deleted.

---

packages/rocketchat_theme/client/imports/components/message-box.css

[FIX] Padding for message box in embedded layout

---

packages/rocketchat-videobridge/client/actionLink.js
packages/rocketchat-videobridge/client/index.js
packages/rocketchat-videobridge/client/public/external_api.js
packages/rocketchat-videobridge/client/tabBar.js
packages/rocketchat-videobridge/client/views/videoFlexTab.js
packages/rocketchat-videobridge/client/views/videoFlexTabBbb.js
packages/rocketchat-videobridge/lib/messageType.js
packages/rocketchat-videobridge/package.js
packages/rocketchat-videobridge/server/actionLink.js
packages/rocketchat-videobridge/server/index.js
packages/rocketchat-videobridge/server/methods/bbb.js
packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js
packages/rocketchat-videobridge/server/models/Rooms.js
packages/rocketchat-videobridge/server/settings.js

Convert rocketchat-videobridge to main module structure

---

packages/rocketchat-katex/client/index.js
packages/rocketchat-katex/lib/katex.js
packages/rocketchat-katex/package.js
packages/rocketchat-katex/server/index.js
packages/rocketchat-katex/server/settings.js

Convert rocketchat-katex to main module structure

---

packages/rocketchat_theme/client/index.js
packages/rocketchat_theme/package.js
packages/rocketchat_theme/server/index.js
packages/rocketchat_theme/server/server.js
packages/rocketchat_theme/server/variables.js

Convert rocketchat-theme to main module structure

---

.eslintrc

Remove global toastr

---

packages/rocketchat-ui/client/views/app/room.js

[FIX] Stop click event propagation on mention link or user card

---

packages/rocketchat_theme/client/imports/general/base_old.css

[FIX] Inherit font family in message user card

---

.eslintrc
packages/rocketchat-ui-master/client/main.js
packages/rocketchat-ui/client/components/icon.js
packages/rocketchat-utils/client/index.js
packages/rocketchat-utils/client/lib/browsers.js

Move isFirefox and isChrome functions to rocketchat-utils

---

packages/rocketchat-ui-account/client/accountFlex.html
packages/rocketchat-ui-account/client/accountFlex.js

[FIX] Webdav integration account settings were being shown even when Webdav was disabled

---

packages/rocketchat-api/server/v1/emoji-custom.js
packages/rocketchat-emoji-custom/server/methods/listEmojiCustom.js
tests/end-to-end/api/12-emoji-custom.js

Part of https://github.com/RocketChat/Rocket.Chat/issues/12730.
Depends of merge of https://github.com/RocketChat/Rocket.Chat/pull/12706.

[NEW] Add query parameter support to emoji-custom endpoint

---

packages/rocketchat-api/server/v1/users.js
packages/rocketchat-lib/server/functions/saveUser.js
tests/end-to-end/api/01-users.js

[FIX] Fix users.setPreferences endpoint, set language correctly

---

packages/rocketchat-importer/server/classes/ImporterBase.js
packages/rocketchat-importer/server/methods/downloadPublicImportFile.js
packages/rocketchat-importer/server/methods/uploadImportFile.js

Improve Importer code quality

---

packages/rocketchat-api/server/v1/chat.js
packages/rocketchat-lib/server/models/_Base.js
packages/rocketchat-lib/server/models/_BaseDb.js

Related to https://github.com/RocketChat/Rocket.Chat/issues/12155

Change `chat.getDeletedMessages` to get messages after informed date and return only message's _id

---

packages/rocketchat-importer/server/startup/store.js

[FIX] Default importer path

---

packages/rocketchat-statistics/server/functions/get.js
server/methods/getUsersOfRoom.js

Regression: Get room's members list not working on MongoDB 3.2

---

packages/rocketchat-i18n/i18n/pt-BR.i18n.json

A better translation was suggested in Lingohub and it's waiting for approval.

Remove incorrect pt-BR translation

---

packages/rocketchat-ui-flextab/client/tabs/userInfo.html
packages/rocketchat-ui/client/components/header/header.html

Status is shown when on DM.
closes #13088

[FIX] User status on header and user info are not translated

---

packages/rocketchat-file-upload/server/index.js

By importing `FileUploadBase` file on server we make sure default permissions are set.

[FIX] Upload permissions

---

packages/rocketchat-livechat/server/api/v1/visitor.js
packages/rocketchat-livechat/server/lib/Livechat.js
packages/rocketchat-livechat/server/visitorStatus.js

This PR adds a new Livechat endpoint, which will be used to update the visitor's status on backend side.

[NEW] Add new Livechat REST endpoint to update the visitor's status

---

packages/rocketchat-statistics/server/functions/get.js

Added new Livechat statistics to statistics collector, which will be used to plan the next steps regarding migrating the Livechat to Enterprise version.

[IMPROVE] New Livechat statistics added to statistics collector

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json
packages/rocketchat-ui-admin/client/adminInfo.html

Administrators should see the version of the Apps Engine their RocketChat is running. That can also help when people are asking for support for apps

[IMPROVE] Add "Apps Engine Version" to Administration > Info

---

packages/rocketchat-livechat/assets/rocket-livechat.js

[FIX] Remove ES6 code from Livechat widget script

---

packages/rocketchat-file-upload/ufs/Webdav/server.js
packages/rocketchat-webdav/server/methods/addWebdavAccount.js
packages/rocketchat-webdav/server/methods/getFileFromWebdav.js
packages/rocketchat-webdav/server/methods/getWebdavFileList.js
packages/rocketchat-webdav/server/methods/uploadFileToWebdav.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13093
Closes https://github.com/RocketChat/Rocket.Chat/issues/13079
As we can see, [the webdav lib](https://github.com/perry-mitchell/webdav-client) we are using, after the last updates, from 1.x version to 2.x changes some functions, causing the errors related in the issue.
[1.x index.js](https://github.com/perry-mitchell/webdav-client/blob/v1.6.1/source/index.js#L8)
[2.x index.js](https://github.com/perry-mitchell/webdav-client/blob/v2.0.0/source/index.js#L8)
[1.x createClient function](https://github.com/perry-mitchell/webdav-client/blob/v1.6.1/source/factory.js#L66)
[2.x createClient function](https://github.com/perry-mitchell/webdav-client/blob/master/source/factory.js#L82)

[FIX] Change webdav creation, due to changes in the npm lib after last update

---

packages/rocketchat-lib/client/lib/RestApiClient.js
packages/rocketchat-ui/client/components/icon.js

[FIX] REST api client base url on subdir

---

packages/rocketchat-file-upload/server/lib/FileUpload.js

[FIX] Avatars with transparency were being converted to black

---

packages/rocketchat-api/package.js
packages/rocketchat-api/server/index.js
packages/rocketchat-api/server/v1/video-conference.js
packages/rocketchat-lib/server/methods/joinRoom.js
tests/end-to-end/api/15-video-conference.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13030

[NEW] Added endpoint to update timeout of the jitsi video conference

---

packages/rocketchat-api/server/v1/users.js
tests/end-to-end/api/01-users.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13116

[FIX] REST API endpoint `users.getPersonalAccessTokens` error when user has no access tokens

---

packages/rocketchat-api/server/v1/emoji-custom.js
tests/end-to-end/api/12-emoji-custom.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13099

[NEW] Add create, update and delete endpoint for custom emojis

---

packages/rocketchat-i18n/i18n/ru.i18n.json

Edit typo "Обновлить" to "Обновить" in ru.i18n.json

Language: Edit typo "Обновлить"

---

packages/rocketchat-lib/server/functions/setRealName.js

[FIX] LDAP login of new users overwriting `fname` from all subscriptions

---

packages/rocketchat-api/server/v1/im.js
packages/rocketchat-callbacks/lib/callbacks.js
packages/rocketchat-callbacks/package.js
packages/rocketchat-metrics/package.js
packages/rocketchat-metrics/server/callbacksMetrics.js
packages/rocketchat-metrics/server/index.js
packages/rocketchat-metrics/server/lib/metrics.js

This removes the cycle dependency on packages to allow better importing of packages.

[IMPROVE] Inject metrics on callbacks

---

package-lock.json
package.json
packages/rocketchat-ui/client/components/header/headerRoom.js
packages/rocketchat-ui/client/views/app/room.js
packages/rocketchat_theme/client/imports/components/table.css

A `ReactiveVar` was missing in `Template.headerRoom`.

Regression: Template error

---

package.json

[FIX] XML-decryption module not found

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-account/client/accountPreferences.html
packages/rocketchat-ui-account/client/accountPreferences.js
packages/rocketchat-ui/client/lib/notification.js

[FIX] "Test Desktop Notifications" not triggering a notification

---

packages/rocketchat-livechat/server/api/v1/agent.js

[FIX] Invalid condition on getting next livechat agent over REST API endpoint

---

packages/rocketchat-apps/package.js

Regression: fix app pages styles

---

packages/rocketchat-statistics/server/lib/SAUMonitor.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13488

[FIX] Error when recording data into the connection object

---

packages/rocketchat-file-upload/server/lib/FileUpload.js

[FIX] .bin extension added to attached file names

---

packages/rocketchat-api/server/api.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13441

[FIX] Restart required to apply changes in API Rate Limiter settings

---

packages/rocketchat-lazy-load/client/index.js
packages/rocketchat-lazy-load/client/lazyloadImage.js
packages/rocketchat-message-attachments/client/messageAttachment.html
packages/rocketchat-message-attachments/client/messageAttachment.js
packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.html
packages/rocketchat-ui-flextab/client/tabs/uploadedFilesList.js

[IMPROVE] Deprecate fixCordova helper

---

README.md

[FIX] link of k8s deploy

---

client/routes/router.js
packages/rocketchat-ui-utils/client/lib/openRoom.js

Regression: Fix embedded layout

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-ui-sidenav/client/sidebarHeader.js

Regression: Sidebar create new channel hover text

---

packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-lib/lib/MessageTypes.js
packages/rocketchat-lib/server/functions/addUserToRoom.js
packages/rocketchat-models/server/models/Messages.js

Regression: User thread join message

---

packages/rocketchat-ui-master/client/main.html
packages/rocketchat_theme/client/imports/general/forms.css

Adds the standard white background used to security tab in the css file general/forms.css
Closes #13645 
Initial State:
Final State:

[FIX] Corrects UI background of forced F2A Authentication

---

packages/rocketchat-ui-flextab/client/tabs/userActions.js

Closes #13627 
cc @tassoevan would you please review

[FIX] Block User Icon

---

package-lock.json
package.json
server/startup/avatar.js

Closes #12890
Related to https://github.com/lovell/sharp/issues/1549 and https://gitlab.gnome.org/GNOME/librsvg/issues/319
Seems the issue was with `librsvg` not resolving font names not surrounded by quotes.

[FIX] Avatar fonts for PNG and JPG

---

packages/rocketchat-livestream/client/views/liveStreamTab.js

[FIX] Stop livestream

---

packages/rocketchat-ui/client/views/cmsPage.html
packages/rocketchat_theme/client/imports/general/base_old.css

Closes #13577
Closes #13626
Co-authored-by: fliptrail

[FIX] Legal page's style

---

package.json

Update husky config

---

package-lock.json
package.json

As requested in
https://github.com/RocketChat/Rocket.Chat/issues/4782#issuecomment-472815758

[FIX] Update bad-words to 3.0.2

---

package.json

Depends on https://github.com/RocketChat/Rocket.Chat.Houston/pull/15

Add Houston config

---

app/ui-message/client/messageBox.js
app/ui-message/client/messageBoxAudioMessage.js
app/ui/client/lib/recorderjs/audioEncoder.js
app/ui/client/lib/recorderjs/audioRecorder.js

Closes #13719
Additionally, this PR eliminates a bug introduced on depackaging.

[FIX] Audio message recording

---

app/lib/server/functions/notifications/email.js
app/message-attachments/client/messageAttachment.html

Closes #13738 
@engelgabriel would you please review

[IMPROVE] Remove unnecessary "File Upload".

---

app/ui-message/client/popup/messagePopupConfig.js

The issue was causing a lot of UI issues also

[FIX] Loading user list from room messages

---

packages/rocketchat-i18n/i18n/fr.i18n.json

Closes #13778
****Initially****
****Finally****

Adds French translation of Personal Access Token

---

app/e2e/client/accountEncryption.js
app/e2e/client/events.js

[FIX] wrong importing of e2e

---

app/authorization/client/views/permissionsRole.js
packages/rocketchat-i18n/i18n/en.i18n.json

User remove role dialog fixed

---

app/theme/client/imports/forms/popup-list.css

[FIX] Avatar image being shrinked on autocomplete

---

app/otr/client/views/otrFlexTab.js

Closes #13754
cc @tassoevan would you please review.

[FIX] OTR dialog issue

---

app/oauth2-server-config/client/oauth/oauth2-client.js
app/utils/client/lib/RestApiClient.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13340
See: https://github.com/RocketChat/Rocket.Chat/issues/13340#issuecomment-466791466

[FIX] Change localStorage keys to work when server is running in a subdir

---

app/apps/client/admin/modalTemplates/iframeModal.html

Improve: Decrease padding for app buy modal

---

app/assets/server/assets.js

[FIX] Add custom MIME types for *.ico extension

---

app/models/client/models/Users.js
app/ui-message/client/messageBox.js
app/ui-utils/client/lib/messageContext.js
app/ui-utils/client/lib/prependReplies.js
app/ui/client/lib/chatMessages.js
app/ui/client/views/app/room.js
app/utils/client/lib/roomTypes.js

By removing reactivity in message box component and the most important one, one the `hasPermission` checks

Fix room re-rendering

---

app/lib/server/lib/notifyUsersOnMessage.js
app/models/server/models/Rooms.js
app/reactions/server/setReaction.js
mocha.opts

And fix deprecation alert from mocha

Fix race condition of lastMessage set

---

app/theme/client/imports/components/modal.css

Fix modal scroll

---

.scripts/start.js

This causes errors when running tests multiple times

Fix: Tests were not exiting RC instances

---

package.json

No idea whether to put new, fix, or what so I'll leave that to others to decide. :)

[IMPROVE] Update the Apps Engine version to v1.4.1

---

app/ui-message/client/message.html
app/ui-message/client/message.js
app/ui-utils/client/lib/MessageAction.js

Fix messages losing thread titles on editing or reaction and improve message actions

---

app/ui/client/views/app/room.js

The signature of `ChatMessages.processSlashCommand()` was changed from returning a `boolean` to returning a `Promise<boolean>`.

Fix action buttons in messages

---

app/message-attachments/client/renderField.html

[FIX] renderField template to correct short property usage

---

app/ui-message/client/messageBox.html
app/ui-message/client/messageBox.js
tests/pageobjects/discussion.page.js

Regression: Message box does not go back to initial state after sending a message

---

app/ui/client/views/app/room.js

Prevent click on reply thread to trigger flex tab closing

---

app/lib/server/functions/notifications/audio.js
client/notifications/notification.js

[FIX] Obey audio notification preferences

---

app/theme/client/imports/general/base_old.css
app/threads/client/flextab/thread.html
app/threads/client/flextab/thread.js
app/ui/client/views/app/room.html
app/ui/client/views/app/room.js

[NEW] allow drop files on thread

---

app/theme/client/imports/general/base_old.css
app/theme/client/imports/general/rtl.css
app/ui-message/client/message.html
app/ui-message/client/message.js
package-lock.json

This PR removes `.collapsed` class from system messages and it modifies the `.system` class itself.
Bugs addressed:

Regression: System messages styling

---

app/theme/client/imports/components/contextual-bar.css
app/theme/client/imports/general/base_old.css
app/ui-admin/client/rooms/adminRoomInfo.html
app/ui-admin/client/users/adminUserInfo.html
app/ui-flextab/client/flexTabBar.html
app/ui-flextab/client/tabs/userEdit.html
package-lock.json

This pull request removes the contextual bar header style when empty, as well as set correct paddings.

Broken styles in Administration's contextual bar

---

imports/personal-access-tokens/client/personalAccessTokens.html

Closes #14209 
Problem was that the table was getting renders but not showing because of 
`class="rc-table-content"`.
cc @tassoevan small fix please review.

[Regression] Personal Access Token list fixed

---

app/threads/client/flextab/thread.html
app/threads/client/flextab/threads.html
app/ui-message/client/message.js
app/ui/client/views/app/room.html

Regression: grouping messages on threads

---

app/ui/client/lib/chatMessages.js

Regression: Cursor position set to beginning when editing a message

---

app/lib/server/lib/sendNotificationsOnMessage.js

Closes item `subscription.receiver is not iterable` of https://github.com/RocketChat/Rocket.Chat/issues/14243

Regression: Exception on notification when adding someone in room via mention

---

app/autotranslate/client/lib/autotranslate.js

[FIX] Auto-translate toggle not updating rendered messages

---

app/theme/client/imports/components/messages.css

Force unstyling of blockquote under .message-body--unstyled

---

app/cloud/server/functions/retrieveRegistrationStatus.js

[FIX] Startup error in registration check

---

server/routes/avatar/utils.js

[FIX] Error when accessing avatar with no token

---

app/theme/client/imports/general/base_old.css
app/ui-message/client/message.js

[FIX] show roles on message

---

server/startup/serverRunning.js

Coerces the MongoDB version string

---

app/lib/server/functions/getAvatarSuggestionForUser.js

Closes : #14300
cc @geekgonecrazy @tassoevan please review

[Regression] Anonymous user fix

---

app/theme/client/imports/forms/select.css

Add cross-browser select arrow positioning

---

app/statistics/server/functions/get.js
server/startup/serverRunning.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14303

[IMPROVE] Better error message when not able to get MongoDB Version

---

app/models/server/models/Messages.js
app/threads/client/flextab/thread.js
app/threads/client/flextab/threads.js
app/threads/server/methods/getThreadMessages.js

[FIX] Duplicate thread message after editing

---

app/lib/server/functions/notifications/audio.js

[FIX] Audio notification for messages on DM

---

app/theme/client/imports/general/base.css

[FIX] Unread line and new day separator was not aligned 

---

app/threads/client/threads.css

[FIX] New day separator overlapping above system message

---

app/livechat/server/api/lib/livechat.js

Returns the list of custom emojis through the Livechat REST API.

[NEW] Returns custom emojis through the Livechat REST API

---

app/threads/client/threads.css

[FIX] Bell was too small on threads

---

app/threads/client/flextab/thread.html
app/threads/client/flextab/thread.js
app/threads/client/flextab/threads.html
app/threads/client/flextab/threads.js

[FIX] Messages on threads disappearing

---

app/ui-message/client/message.js

the message body as helper to allow updates

Fix: Message body was not being updated when user disabled nrr message

---

app/channel-settings/client/views/channelSettings.js
app/channel-settings/server/functions/saveRoomName.js
app/discussion/server/hooks/propagateDiscussionMetadata.js

[NEW] Allow change Discussion's properties

---

app/autotranslate/client/lib/actionButton.js
app/message-star/client/actionButton.js
app/reactions/client/init.js
app/threads/client/messageAction/follow.js
app/threads/client/messageAction/unfollow.js
app/ui-utils/client/lib/MessageAction.js

[FIX] more message actions to threads context(follow, unfollow, copy, delete)

---

app/ui-flextab/client/tabs/membersList.html
app/ui-flextab/client/tabs/membersList.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14249

[FIX] Pressing Enter in User Search field at channel causes reload

---

app/message-attachments/client/messageAttachment.js

[FIX] preview pdf its not working

---

app/mentions-flextab/client/views/mentionsFlexTab.html
app/mentions-flextab/client/views/mentionsFlexTab.js
app/threads/client/flextab/thread.html
app/ui-message/client/message.js

[FIX] Mentions message missing 'jump to message' action

---

app/ui/client/lib/chatMessages.js

[FIX] Escape unrecognized slash command message

---

app/crowd/server/crowd.js

[FIX] Exception on crowd sync due to a wrong logging method

---

app/ui-flextab/client/tabs/userActions.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14159

[FIX] Room name was undefined in some info dialogs

---

.eslintrc

They are now on main eslint-config package

Remove specific eslint rules

---

app/ui/client/views/app/room.js

[FIX] You must join to view messages in this channel

---

app/utils/lib/isURL.js

Some attachments could be broken.

[FIX] Allow data URLs in isURL/getURL helpers

---

app/ui-sidenav/client/sideNav.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13704

[FIX] Fix redirect to First channel after login

---

packages/rocketchat-i18n/i18n/de.i18n.json

[FIX] `Alphabetical` translation in DE

---

app/videobridge/client/views/videoFlexTab.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14489

[FIX] RocketChat client sending out video call requests unnecessarily

---

app/api/server/v1/users.js
tests/end-to-end/api/01-users.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/13894

[FIX] Verify if the user is requesting your own information in users.info

---

tests/end-to-end/api/02-channels.js
tests/end-to-end/api/03-groups.js

eslint errors currently on develop

---

app/ui-message/client/messageBox/messageBoxTyping.js
app/ui/client/lib/chatMessages.js
app/ui/client/lib/msgTyping.js
app/ui/client/views/app/room.js

next step one instance per chatMessage instance.

MsgTyping refactor

---

app.json

[Fix] broken logo url in app.json

---

app/slackbridge/server/RocketAdapter.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14558
Regression introduced by https://github.com/RocketChat/Rocket.Chat/commit/fad728bc3516d5c231130d12a0808eb5f80af327#diff-f23b871abaf6db2da0046d0d7def6ab8L291

[REGRESSION] Fix Slack bridge channel owner on channel creation

---

app/chatpal-search/server/asset/config.js
app/theme/server/server.js
app/ui-master/server/index.js
app/ui-master/server/inject.js
package-lock.json

Closes #14548
Related to #14375
It introduces two helpers, `injectIntoHead()` and `injectIntoBody()`, to replace direct calls to `Inject` (`meteor/meteorhacks:inject-initial`) API.

[FIX] Inject code at the end of <head> tag

---

app/authorization/client/stylesheets/permissions.css

[FIX] Role name spacing on Permissions page

---

app/authorization/client/stylesheets/permissions.css
app/authorization/client/views/permissions.html
app/ui-message/client/messageBox/messageBox.js
app/ui/client/lib/chatMessages.js

sticky header
no border
text ellipsis

Improvement: Permissions table

---

app/ui-message/client/messageBox/messageBoxAutogrow.js
app/ui-utils/client/lib/RoomManager.js

closes https://github.com/RocketChat/Rocket.Chat/issues/14666

[FIX] Load messages after disconnect and message box scroll missing

---

app/theme/client/imports/general/variables.css
private/client/imports/general/variables.css

[IMPROVE] Use configurable colors on sidebar items

---

app/livechat/server/config.js
app/livechat/server/publications/livechatInquiries.js
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json

Adds a new setting to define the max number of items displayed in the incoming livechats queue.

[NEW] Configuration to limit amount of livechat inquiries displayed

---

app/api/server/api.js
app/api/server/v1/misc.js
app/lib/server/startup/settings.js
packages/rocketchat-i18n/i18n/en.i18n.json

Closes https://github.com/RocketChat/Rocket.Chat/issues/14696

[FIX] Increasing time to rate limit in shield.svg endpoint and add a setting to disable API rate limiter

---

app/ui-message/client/messageBox/messageBoxTyping.js
app/ui/client/lib/msgTyping.js

[FIX] users typing forever

---

app/utils/lib/fileUploadRestrictions.js

Regression added by https://github.com/RocketChat/Rocket.Chat/pull/14777

Regression: Fix file upload

---

app/ui-flextab/client/tabs/userInfo.js
client/startup/usersObserve.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14657

[FIX] User status information on User Info panel

---

app/authorization/server/functions/canAccessRoom.js
app/models/server/raw/Roles.js
app/models/server/raw/Users.js

https://github.com/RocketChat/Rocket.Chat/pull/14777 left behind a few pieces yet fully extracted from Meteor and a method missing from Users model.

Fix not fully extracted pieces

---

app/integrations/server/lib/triggerHandler.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14631

[NEW] Add tmid property to outgoing integration

---

app/ui-message/client/message.js

Regression: thread loading parent msg if is not loaded

---

app/e2e/client/rocketchat.e2e.js
app/e2e/client/tabbar.js
app/ui/client/components/header/headerRoom.js
package-lock.json

[FIX] Removes E2E action button, icon and banner when E2E is disabled.

---

app/ui-cached-collection/client/models/CachedCollection.js

Allow debugging of cached collections by name

---

app/ui-cached-collection/client/models/CachedCollection.js

Regression: Allow debugging of cached collections by name

---

app/api/server/v1/channels.js

Closes [Issue 1180](https://github.com/RocketChat/Rocket.Chat.Android/issues/1180) on Rocket.Chat.Android

[FIX] Opening Livechat messages on mobile apps

---

app/ui/client/lib/recorderjs/videoRecorder.js

[FIX] Video recorder message echo

---

app/ui/client/views/app/room.html
app/ui/client/views/app/room.js

[FIX]Wrong custom status displayed on room leader panel

---

server/methods/getUsersOfRoom.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14737

[FIX] Method `getUsersOfRoom` not returning offline users if limit is not defined

---

app/message-pin/client/actionButton.js
app/message-star/client/actionButton.js

[FIX] Jump to message missing in Starred Messages

---

app/ui-utils/client/lib/RoomHistoryManager.js

[FIX] load more messages

---

app/emoji-custom/client/admin/adminEmoji.js

[FIX] 50 custom emoji limit

---

app/channel-settings/client/views/channelSettings.html

[FIX] Wrong label order on room settings

---

app/emoji-emojione/lib/rocketchat.js
app/emoji/client/emojiParser.js
app/utils/lib/getUserAvatarURL.js

Reverts RocketChat/Rocket.Chat#14722

Regression: patch to improve emoji render

---

.meteor/versions

Closes RocketChat/Rocket.Chat#14237
Closes RocketChat/Rocket.Chat#14702

[FIX] Users staying online after logout

---

app/lib/server/functions/setStatusText.js

[FIX] Custom User Status throttled by rate limiter

---

app/ui-flextab/client/tabs/inviteUsers.js

[FIX] Invite users auto complete cropping results

---

app/livechat/client/lib/dataHandler.js

fix #14844 
Changed the label for Average reaction time and Average response time

[FIX] Livechat dashboard average and reaction time labels

---

app/ui/client/lib/chatMessages.js

[FIX] Edit message with arrow up key if not last message

---

app/statistics/server/functions/get.js

Fix statistics error

---

packages/rocketchat-i18n/i18n/fr.i18n.json

Add Message_AllowConvertLongMessagesToAttachment to french translation

Add missing French translation

---

packages/rocketchat-i18n/i18n/de-IN.i18n.json
packages/rocketchat-i18n/i18n/de.i18n.json

There is a small typo in the German translation file.

[FIX] Typo in german translation

---

app/ui-utils/client/lib/MessageAction.js

Wrong text when reporting a message

---

app/lib/server/functions/sendMessage.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14172

[FIX] Message attachments not allowing float numbers

---

packages/rocketchat-livechat/plugin/build.sh

Update the Livechat build file, addressing the download file process to the latest Livechat release:
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/262

Update Livechat widget

---

app/apps/client/admin/helpers.js
app/ui-utils/client/lib/modal.html

Removes additional modal when uninstalling a subscribed app.

Regression: uninstall subscribed app modal

---

app/lib/lib/roomTypes/direct.js
app/ui-admin/client/rooms/adminRooms.js
app/utils/lib/RoomTypeConfig.js

[FIX] Direct Message names not visible on Admin panel

---

app/ui-cached-collection/client/models/CachedCollection.js

Regression: cachedCollection wrong callback parameters

---

app/ui-sidenav/client/sidebarItem.js

removed unwanted code

---

packages/rocketchat-livechat/plugin/build.sh

Update the Livechat build file to get the latest version of the Livechat widget -> `1.1.4`.

Update latest Livechat widget version to 1.1.4

---

app/file-upload/server/config/AmazonS3.js
app/file-upload/server/config/GoogleStorage.js
app/file-upload/server/lib/FileUpload.js
app/file-upload/ufs/AmazonS3/server.js
app/file-upload/ufs/GoogleStorage/server.js
app/message-attachments/client/messageAttachment.html
app/ui/client/views/app/room.js
package-lock.json

[FIX] Attachment download button behavior

---

.meteor/versions

Update package to [2.6.0](https://github.com/Konecty/meteor-user-presence/releases/tag/2.6.0)

Update presence package

---

app/ui-flextab/client/flexTabBar.js

[FIX] TabBar not loading template titles

---

package-lock.json
package.json

Seems 1.1.4 previously installed was incorrect.

Update Livechat to 1.1.6

---

app/api/server/v1/misc.js

Use `/api/info` instead. https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/info/

[BREAK] Remove REST endpoint `/api/v1/info`

---

app/notifications/server/lib/Notifications.js

This was causing issues sometimes that were breaking typing notification.

Change notifications file imports to server

---

app/api/server/v1/commands.js
tests/end-to-end/api/16-commands.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/15165

[IMPROVE] Add possibility to use commands inside threads through Rest API

---

app/discussion/client/views/DiscussionList.html
app/discussion/client/views/DiscussionList.js

[FIX] "Discussion" label in Sidebar not hidden, when Discussions are disabled (#14660)

---

server/publications/userAutocomplete.js

[FIX] User's auto complete showing everyone on the server

---

app/ui-admin/client/admin.js

A wrong variable name was being used when saving the setting.

Regression: Errors on the console preventing some settings to be saved

---

app/authorization/server/publications/permissions/emitter.js

Whenever a permission was changed, users were notified 2 times.

Regression: Remove duplicated permission changes emitter

---

app/apps/client/admin/appInstall.js
app/apps/client/admin/appManage.js
app/apps/server/communication/rest.js
app/apps/server/cron.js
app/utils/client/lib/RestApiClient.js

* Fixes the error preventing the redirect on app installation
* Better messages shown when there is an installation error

[FIX] Redirect on app manual install

---

app/federation/server/functions/helpers.js
app/federation/server/hooks/afterAddedToRoom.js
app/federation/server/hooks/afterCreateDirectRoom.js
app/federation/server/hooks/afterCreateRoom.js
app/federation/server/hooks/afterRemoveFromRoom.js
app/federation/server/hooks/beforeDeleteRoom.js
app/federation/server/normalizers/user.js
server/startup/migrations/index.js
server/startup/migrations/v156.js

Federation migration and additional improvements

---

app/custom-sounds/client/admin/adminSounds.js
app/custom-sounds/client/lib/CustomSounds.js
app/livechat/client/startup/notifyUnreadRooms.js
app/push-notifications/client/views/pushNotificationsFlexTab.js
app/ui-account/client/accountPreferences.js
app/ui/client/lib/notification.js

This helper encapsulates the custom sound handling (querying the DOM tree to get HTMLAudioElement instances).

[IMPROVE] Add CustomSounds.play() helper

---

app/ui-sidenav/client/toolbar.js

[FIX] Duplicate Channels in Search-bar

---

app/ui-admin/client/admin.html
app/ui-admin/client/admin.js
app/ui/client/index.js
app/ui/client/lib/codeMirror/codeMirror.js
app/ui/client/lib/codeMirror/codeMirrorComponent.js
app/ui/client/lib/codeMirror/index.js

This makes it so that all the code that runs codemirror loads to the browser only when the codemirror textarea is rendered

[NEW] Only Load CodeMirror code when it is needed

---

app/theme/client/imports/components/message-box.css

Closes #https://github.com/RocketChat/Rocket.Chat/issues/13886
The line-height css property was on the wrong element

[FIX] Message box not centered

---

app/theme/client/imports/components/message-box.css

Fixes the message box changing size every time someone starts typing on it.

Regression: Messagebox height changing when typing

---

app/ui-flextab/client/tabs/userInfo.js

[FIX] User Profile Time Format

---

app/ui-message/client/message.js

[Fix] Missing space between last username & 'and' word in react notification

---

app/emoji-custom/client/lib/emojiCustom.js

This issue was happening when reloading Rocket.Chat from a room URL due to a race condition where the emoji picker was being rendered before getting the list of custom emojis.
Now it forces a re-render of custom emojis on emoji picker after getting the list of custom emojis from server.
I've also changed to use the REST endpoint instead of the Meteor method.

[FIX] Empty custom emojis on emoji picker

---

app/api/server/v1/users.js
tests/data/user.js
tests/end-to-end/api/01-users.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/15221

[FIX] REST endpoint `users.setPreferences` to not override all user's preferences

---

server/methods/readMessages.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/14517

[FIX] Subscription record not having the `ls` field

---

app/apps/client/admin/appManage.html
app/lazy-load/client/lazyloadImage.html
app/lib/server/startup/settings.js
app/search/client/search/search.html
app/threads/client/flextab/thread.html
app/ui-account/client/avatar/avatar.html
app/ui-account/client/avatar/avatar.js
app/ui-flextab/client/flexTabBar.html
app/ui-flextab/client/tabs/membersList.html
app/ui-flextab/client/tabs/userInfo.html
app/ui-message/client/message.html
app/ui-message/client/messageBox/messageBox.html
app/ui-message/client/messageThread.html
app/ui-sidenav/client/sidebarHeader.html
app/ui-sidenav/client/sidebarHeader.js
app/ui-sidenav/client/sidebarItem.html
app/ui-utils/client/lib/alerts.html
app/ui-utils/client/lib/popout.html
app/ui/client/components/contextualBar.html
app/ui/client/components/header/headerRoom.html
app/ui/client/components/header/headerRoom.js
package-lock.json
tests/pageobjects/main-content.page.js

- Unlabelled buttons
- Images without alt text
- Unidentified popup triggers

[IMPROVE] A11y: Buttons, Images, Popups

---

app/api/server/api.js

Related to https://github.com/RocketChat/Rocket.Chat/pull/15292

Regression: Prevent parsing empty custom field setting

---

app/apps/server/converters/departments.js
app/apps/server/converters/rooms.js
app/apps/server/orchestrator.js

Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/142

Access livechat room’s deparment data

---

client/routes.js
packages/rocketchat-i18n/i18n/en.i18n.json

Regression: setup wizard dynamic import using relative url

---

app/apps/assets/stylesheets/apps.css
app/apps/client/gameCenter/gameCenter.html
app/apps/client/gameCenter/gameCenter.js
app/apps/client/gameCenter/gameContainer.html
app/apps/client/gameCenter/gameContainer.js
app/apps/client/gameCenter/gameModal.html
app/apps/client/index.js

[External Component] External component.contextual bar

---

package-lock.json
package.json

The previous beta version for the Apps-Engine has been promoted, this updates the version accordingly.

Update Apps-Engine version to final version

---

LICENSE

Updating the copyright term from 2018 to 2019

Updating license term

---

app/lib/server/lib/debug.js

[FIX] Exposing some fields on server logs at debug level

---

app/slashcommands-archiveroom/client/client.js
app/slashcommands-archiveroom/server/server.js
app/slashcommands-create/client/client.js
app/slashcommands-create/server/server.js
app/slashcommands-invite/client/client.js
app/slashcommands-invite/server/server.js
app/slashcommands-inviteall/client/client.js
app/slashcommands-inviteall/server/server.js
app/slashcommands-join/client/client.js
app/slashcommands-join/server/server.js
app/slashcommands-kick/client/client.js
app/slashcommands-leave/server/leave.js
app/slashcommands-msg/server/server.js
app/slashcommands-mute/server/mute.js
app/slashcommands-mute/server/unmute.js
app/slashcommands-open/client/client.js
app/slashcommands-topic/lib/topic.js
app/slashcommands-unarchiveroom/client/client.js
app/slashcommands-unarchiveroom/server/server.js

[FIX] Add permissions for slashCommands

---

app/ui/client/views/app/directory.html

[FIX] Add a header for the createAt column in the Directory

---

packages/rocketchat-i18n/i18n/ja.i18n.json

Fix mistranslation in ja.i18n.json for Japanese language.

[FIX] Japanese translation for run import

---

app/channel-settings/client/views/channelSettings.html
app/theme/client/imports/components/userInfo.css

Closes #15235 
This PR fixes the layout in room buttons, as shows the following screenshot

[FIX] Fixes the button layout (#15235)

---

app/apps/server/converters/rooms.js

This PR fixes the behavior where a room loses some custom properties when updated by an app

[FIX] Update apps engine rooms converter to use transformMappedData

---

app/ui-admin/client/rooms/adminRoomInfo.js

[FIX] Self-XSS in validation functionality

---

app/importer-csv/server/importer.js
app/importer/server/classes/ImporterSelectionChannel.js

[NEW] Import DMs from CSV files

---

app/theme/client/imports/forms/button.css

[FIX]  Incorrect display of the button "Invite users"

---

app/ui-message/client/messageBox/messageBoxFormatting.js

Bug Introduced on https://github.com/RocketChat/Rocket.Chat/pull/15398

Regression: Fix broken message formatting box

---

app/apps/server/bridges/commands.js
app/apps/server/converters/messages.js
app/ui-message/client/messageBox/messageBox.js
app/ui-message/client/popup/messagePopupSlashCommandPreview.js
package-lock.json
package.json

Depends on the publication of https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/164

[NEW] Thread support to apps slashcommands and slashcommand previews

---

.github/ISSUE_TEMPLATE/bug_report.md

Chore: Add Client Setup Information to Issue Template

---

app/apps/server/converters/rooms.js

The `departmentId` field was missing.

Regression: AppRoomsConverter on Livechat rooms

---

app/threads/client/flextab/thread.js
app/ui-utils/client/lib/MessageAction.js

[FIX] Edit in thread

---

app/push-notifications/client/views/pushNotificationsFlexTab.js

[FIX] Null value at Notifications Preferences tab

---

packages/rocketchat-i18n/i18n/pt-BR.i18n.json

[FIX] typo on PT-BR translation

---

app/ui-message/client/messageBox/messageBox.js

[FIX] Ignore file uploads from message box if text/plain content is being pasted

---

app/ui-message/client/messageBox/messageBoxAudioMessage.js

[FIX] Use Media Devices API to guess if a microphone is not available

---

app/ui-account/client/accountPreferences.html
app/ui-account/client/accountPreferences.js

Bug Introduced on https://github.com/RocketChat/Rocket.Chat/pull/15694

[REGRESSION] Fix hide avatars in side bar preference

---

app/authorization/server/functions/canSendMessage.js

[FIX] Sending messages to livechat rooms without a subscription

---

app/user-data-download/server/cronProcessDownloads.js

[FIX] Error when exporting user data

---

app/lib/server/startup/settings.js
app/theme/client/imports/general/base_old.css

Removed the gray margins as suggested on #14248

[FIX] Changed cmsPage Style

---

packages/rocketchat-i18n/i18n/pt-BR.i18n.json
packages/rocketchat-i18n/i18n/pt.i18n.json

Improve LDAP Login Fallback setting description in portuguese

---

app/message-attachments/client/messageAttachment.html
app/message-attachments/client/messageAttachment.js

Regression: messageAttachments inside messageAttachments not receiving settings

---

app/theme/client/imports/general/variables.css
private/client/imports/general/variables.css

Allowing Primary Light (@rc-color-primary-light) to change rooms list title color.
closes #14890

[FIX] Sidebar font color was not respecting theming  (#9329)

---

app/apps/client/gameCenter/gameCenter.js
app/apps/client/gameCenter/tabBarButton.js
app/apps/server/communication/rest.js
app/apps/server/orchestrator.js

depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/150

[Apps] Support multiple external components per app

---

app/apps/client/RealAppsEngineUIHost.js
app/apps/server/communication/rest.js

Fix issues introduced by names changing

---

app/mentions/lib/MentionsParser.js

[FIX] Mentions before blockquote

---

app/theme/client/imports/general/reset.css

Closes #12968
The default styling on safari was breaking some buttons css.

[FIX] Add button to reset.css

---

app/livechat/server/lib/Helper.js
app/livechat/server/lib/Livechat.js
app/livechat/server/lib/RoutingManager.js

Minor fixes related to the `Livechat transfer history messages`:
- Fix the transfer history when the transfer request comes from the `visitor`;
- Fix the order of the transfer history messages;

[FIX] Livechat transfer history messages

---

app/ui/client/lib/fileUpload.js

[FIX] Pasting images on reply as thread

---

README.md

[CHORE] Add lingohub to readme

---

server/startup/migrations/index.js
server/startup/migrations/v168.js

Remove unused permission to reset users' E2E key

---

app/ui-message/client/message.js

[FIX] Thread Replies in Search

---

app/ui-utils/client/lib/messageContext.js

[FIX] Auto load image user preference

---

app/cloud/server/functions/syncWorkspace.js

[FIX] Server crash on sync with no response

---

app/custom-oauth/client/custom_oauth_client.js

[FIX] Invalid Redirect URI on Custom OAuth

---

README.md

Fix 'How it all started' link on README

---

app/livechat/client/views/app/livechatAppearance.html

Closes #15974 
The show_agent_info variable was not getting properly rendered. Corrected the issue by making I lowercased

[FIX] Incorrect translation key in Livechat Appearance template

---

app/user-data-download/server/cronProcessDownloads.js

[FIX] Error of bind environment on user data export

---

packages/rocketchat-mongo-config/package.js
packages/rocketchat-mongo-config/server/index.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/15130

[NEW] Do not print emails in console on production mode

---

app/ui-utils/client/lib/RoomManager.js
app/ui/client/views/app/room.js

Closes #10219 
Fixing the bug that happens when you react to any message, the popup doesn't appear anymore.

[FIX] new message popup

---

app/ldap/server/sync.js
app/lib/server/functions/getUsernameSuggestion.js
package-lock.json
package.json

Closes https://github.com/RocketChat/Rocket.Chat/issues/15999
On limax version 2.0 separateNumbers is false by default.

Upgrade limax to 2.0.0

---

README.md

<h1>Description</h1>
I have corrected some grammatical errors. Please review them.
Thanks a lot!

Fixed Grammatical Mistakes.

---

app/theme/client/imports/general/base_old.css

Closes #12928 
Increased upload-progress-text width, so the error doesn't happen anymore.

[FIX] width of upload-progress-text

---

app/importer-slack-users/lib/info.js
app/importer/client/admin/adminImport.html
app/importer/client/admin/adminImport.js

[FIX] Importer: Variable name appearing instead of it's value

---

app/theme/client/imports/forms/input.css
app/ui-flextab/client/tabs/createInviteLink.html
app/ui-flextab/client/tabs/createInviteLink.js
app/ui-flextab/client/tabs/membersList.html

Regression: Missing button to copy Invite links

---

app/api/server/api.js
app/integrations/server/api/api.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/15820

[FIX] api-bypass-rate-limiter permission was not working

---

app/api/server/v1/users.js
app/lib/server/startup/settings.js
app/ui-account/client/accountPreferences.html
app/ui-account/client/accountPreferences.js
app/ui-sidenav/client/roomList.html
app/ui-sidenav/client/roomList.js
server/methods/saveUserPreferences.js
server/startup/migrations/index.js
server/startup/migrations/v171.js
tests/data/user.js
tests/end-to-end/api/00-miscellaneous.js
tests/end-to-end/ui/11-admin.js
tests/pageobjects/administration.page.js

Closes #8616
Removed the setting "Show room counter" from the preferences menu, under "sidebar" section. Removed every part of code responsible for showing when enabled. Removed showRoomCounter field from mongo.

[BREAK] Removed room counter from sidebar

---

app/theme/client/imports/forms/button.css
app/ui-flextab/client/tabs/userEdit.html
app/ui-flextab/client/tabs/userEdit.js
package-lock.json
packages/rocketchat-i18n/i18n/en.i18n.json
packages/rocketchat-i18n/i18n/pt-BR.i18n.json

Closes https://github.com/RocketChat/Rocket.Chat/issues/15880

[FIX] Add missing password field back to administration area

---

README.md

Closes #16194
Removed old job postings and placed website jobs link instead.

[FIX]Readme Help wanted section

---

app/integrations/client/route.js

Closes #16178
Fixed async function without return.

[FIX] Integrations admin page

---

app/message-attachments/client/messageAttachment.html
packages/rocketchat-i18n/i18n/en.i18n.json

[FIX] The "click to load" text is hard-coded and not translated.

---

.github/workflows/build_and_test.yml

Current develop builds are breaking due this error.

Fix assets download on CI

---

app/apps/client/admin/appLogs.html
app/apps/server/storage/logs-storage.js
app/models/server/models/apps-logs-model.js

It may cause a huge delay and memory overload if the app contains a huge history of logs

[FIX] App removal was moving logs to the trash collection

---

app/channel-settings-mail-messages/client/views/mailMessagesInstructions.js

[FIX] Mail Msg Cancel button not closing the flexbar

---

app/theme/client/imports/general/base.css

Some pages over some resolutions were behaving badly.

[FIX] Container heights

---

app/apps/server/bridges/messages.js
app/lib/server/functions/sendMessage.js
app/lib/server/methods/sendMessage.js
tests/end-to-end/api/05-chat.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/16382
Closes https://github.com/RocketChat/Rocket.Chat/pull/16345
Closes https://github.com/RocketChat/Rocket.Chat/issues/16291
Revert validation for fields alias, avatar.

Revert message properties validation

---

app/lib/server/startup/rateLimiter.js

[IMPROVE] Log as info level when Method Rate Limiters are reached

---

app/ui-message/client/message.js
app/ui/client/views/app/room.html

after the NRR removal in some occasions, the messages were grouping by the wrong user

Regression: Fix sequential messages grouping

---

app/ui-utils/client/lib/RoomManager.js

Closes #16278
Closes https://github.com/RocketChat/Rocket.Chat/pull/16293/

Regression: Fix sending a message not scrolling to bottom

---

app/lib/server/functions/setUserAvatar.js

Closes https://github.com/RocketChat/Rocket.Chat/issues/16110

[FIX] Result of get avatar from url can be null

---

app/ui-message/client/message.js

[FIX] Missing edited icon in newly created messages

---

.meteor/versions

Update presence package to try fixing user presence issues.

Update presence package to 2.6.1

---

app/cloud/server/functions/saveRegistrationData.js

Fix: License missing from manual register handler

---

app/authorization/server/functions/canSendMessage.js
app/lib/server/functions/deleteMessage.js
app/lib/server/methods/sendMessage.js
app/models/server/models/Messages.js
app/ui-message/client/message.html
package-lock.json
package.json

Regression: Ui Kit messaging issues

---

app/ui-message/client/blocks/Blocks.js
app/ui-message/client/blocks/ModalBlock.js
package-lock.json
package.json

Regression: UIKit - Send container info on block actions triggered on a message

---

app/ui-message/client/blocks/MessageBlock.js
app/ui-message/client/blocks/ModalBlock.js

Pressing "Enter" while focus was on "create" (poll app) would duplicate the poll.

Regression: Modal onSubmit

---

.github/history-manual.json

Add breaking notice regarding TLS

---

package-lock.json
package.json

Update Apps-Engine version

---

app/ui/client/views/app/room.js

Regression: fix read unread messages

---

.snapcraft/snap/snapcraft.yaml

Closes #13391.
cc @geekgonecrazy does this solves the issue?

fix: add option to mount media on snap

---

app/threads/client/messageAction/replyInThread.js

[IMPROVE] Removed the 'reply in thread' from thread replies

---

app/message-pin/client/actionButton.js

[FIX] Added an option to pin/unpin a thread message

---

app/ui/client/lib/chatMessages.js

[FIX]  Bug making us to reload the page after cancel was clicked on editing

---

app/ui/client/views/app/directory.js

Closes #16216
Focus should be on search box of directory component, when user clicks on Directory button.

[IMPROVE] Added autofocus to Directory

---

app/ui/client/lib/fileUpload.js

Issue introduced by the change to REST uploads.

Regression: Show upload errors

---

app/ui-sidenav/client/userPresence.js
imports/client/query-string
imports/client/scheduler
imports/client/split-on-first
imports/client/strict-uri-encode

[FIX] ie11 support

---

app/ui-sidenav/client/userPresence.js

[FIX] Console error on login

---

README.md

Update links in README from uApp Explorer to Snap Store.

[CHORE] Update snap install instructions

---

client/components/admin/settings/inputs/LanguageSettingInput.js
client/components/setupWizard/steps/SettingsBasedStep.js

Closes #16687
Changed SelectInput to Select.

[CHORE] Changed remaining SelectInput's to Select

---

.docker-mongo/Dockerfile
.docker-mongo/entrypoint.sh
.github/workflows/build_and_test.yml

Docker preview image was broken due to the requirement for a replica set mongo and it was not being built with the latest CI change.
This PR fixes both cases.

Fix Docker preview image

---

app/file-upload/server/startup/settings.js

[IMPROVE] Accept open formarts of text, spreadsheet, presentation for upload by default

---

app/slackbridge/server/slackbridge_import.server.js

[FIX] Slackbridge-import command doesn't work

---

app/slackbridge/server/SlackAPI.js

[FIX] Get all channels from Slack via REST API

---

app/message-pin/client/actionButton.js

[FIX] Cannot pin direct messages

---

LICENSE
ee/LICENSE

This is a preparation to move Enterprise code to community repo.

Add Enterprise Edition license

---

app/message-attachments/client/messageAttachment.html
packages/rocketchat-i18n/i18n/en.i18n.json

[FIX] Removed some hardcoded texts

---

app/ui-admin/client/adminFlex.html
app/ui-admin/client/adminFlex.js

[FIX] No settings to be displayed if search not found

---

app/livechat/imports/server/rest/facebook.js

[FIX] Facebook integration missing visitor data after registerGuest

---

app/search/client/search/search.js
app/ui-flextab/client/tabs/membersList.js
app/ui-flextab/client/tabs/uploadedFilesList.js

Added autofocus to search, File List and Members List.

[IMPROVE] Context menu autofocus

---

client/components/basic/Page.js

Depends on https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/155

[IMPROVE] Added border to page header.

---

package-lock.json
package.json

Upgrade the Livechat widget dependency to the latest version(1.4.0)

Upgrade Livechat Widget version to 1.4.0

---

app/lib/server/functions/getAvatarSuggestionForUser.js
server/lib/accounts.js

Login with Linkedin was not getting the user name from the correct location.
Linkedin changed it to include a preferredLocale.

[FIX] Login with LinkedIn not mapping name and picture correctly

---

app/slackbridge/server/SlackAdapter.js

[FIX] Messages doesn't send to Slack via SlackBridge after renaming channel

---

app/channel-settings/client/views/channelSettings.js

Fixed translate variable in UnarchiveRoom Modal

---

app/otr/client/rocketchat.otr.room.js

[FIX] Explicitly set text of confirmation button

---

app/lib/server/functions/deleteUser.js
app/models/server/models/Messages.js
app/models/server/models/Rooms.js
app/models/server/models/Subscriptions.js

Removing an user was not removing his 1-on-1 DMs completely as before, lefting behind his subscription from other users.

Regression: Fix removing user not removing his 1-on-1 DMs

---

app/apps/server/communication/websockets.js

[FIX] Error when websocket received status update event
